// Azərbaycan dili — 7-ci sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Feil  2) Feilin qrammatik məna növləri  3) Təsriflənməyən feillər
// 4) Zərf  5) Köməkçi nitq hissələri (qoşma, bağlayıcı, ədat)
// 6) Modal sözlər, nida və söz birləşmələri.
// Hər dərs: 15 əsas + 5 bonus. id prefiksi az7-*.

import type { Subject } from "../types";

export const azerbaijani7: Subject = {
  slug: "azerbaycan-dili-7",
  name: "Azərbaycan dili",
  grade: 7,
  icon: "A",
  color: "rose",
  units: [
    // ═══════════════ 1. Feil ═══════════════
    {
      id: "az7-feil",
      title: "Feil",
      description:
        "Feil əsas nitq hissəsi kimi, onun əlamətləri, quruluşca növləri (sadə, düzəltmə, mürəkkəb) və zamanları.",
      lessons: [
        {
          id: "az7-feil-l1",
          title: "Feil və onun əlamətləri",
          intro: "Feil iş, hal və hərəkət bildirən əsas nitq hissəsidir.",
          sections: [
            { heading: "Feil nədir?", body: "İş, hal və ya hərəkət bildirən, 'nə etmək?', 'nə olmaq?' suallarına cavab verən əsas nitq hissəsinə feil deyilir: yazmaq, oxumaq, gülmək, düşünmək." },
            { heading: "Təsdiq və inkar", body: "Feil təsdiqdə (gəldi) və inkarda (gəlmədi) olur. İnkar -ma²/-mə şəkilçisi ilə düzəlir: bax → baxma, gəl → gəlmə." },
          ],
          tasks: [
            { id: "az7-feil-l1-t1", type: "multiple_choice", prompt: "Feil hansı suallara cavab verir?", options: ["nə etmək? nə olmaq?", "kim? nə?", "necə? nə cür?", "neçə? nə qədər?"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-feil-l1-t2", type: "multiple_choice", prompt: "Aşağıdakılardan hansı feildir?", options: ["yazmaq", "kitab", "gözəl", "beş"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-feil-l1-t3", type: "multiple_choice", prompt: "Feil nə bildirir?", options: ["iş, hal, hərəkət", "əşya", "əlamət", "say"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-feil-l1-t4", type: "multiple_choice", prompt: "'gəlmədi' feili hansı formadadır?", options: ["inkar", "təsdiq", "sual", "əmr"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-feil-l1-t5", type: "fill_blank", prompt: "'oxu' feilinin inkar formasını yaz.", accepted: ["oxuma"], xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-feil-l1-t6", type: "fill_blank", prompt: "'gəl' feilinin inkar formasını yaz.", accepted: ["gəlmə"], xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-feil-l1-t7", type: "multiple_choice", prompt: "İnkar şəkilçisi hansıdır?", options: ["-ma/-mə", "-lı/-li", "-çı/-çi", "-lıq/-lik"], correctIndex: 0, xp: 10, skills: ["az.morph.root"] },
            { id: "az7-feil-l1-t8", type: "multiple_choice", prompt: "Aşağıdakılardan hansı feil DEYİL?", options: ["dostluq", "danışmaq", "getmək", "baxmaq"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-feil-l1-t9", type: "multiple_choice", prompt: "'işləyir' sözü hansı nitq hissəsidir?", options: ["feil", "isim", "sifət", "zərf"], correctIndex: 0, xp: 10, skills: ["az.phon.letters"] },
            { id: "az7-feil-l1-t10", type: "multiple_choice", prompt: "Hansı cümlədə feil var?", options: ["Uşaq oxuyur.", "Gözəl gül.", "İki dəftər.", "Ağ divar."], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-feil-l1-t11", type: "fill_blank", prompt: "'yaz' feilinin inkar formasını yaz.", accepted: ["yazma"], xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-feil-l1-t12", type: "multiple_choice", prompt: "'düşünmək' sözünün sualı hansıdır?", options: ["nə etmək?", "kim?", "necə?", "haçan?"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_tense"] },
            { id: "az7-feil-l1-t13", type: "multiple_choice", prompt: "Aşağıdakılardan hansı təsdiq feildir?", options: ["gördü", "görmədi", "baxmadı", "gəlmədi"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-feil-l1-t14", type: "multiple_choice", prompt: "'gülmək' feili nə bildirir?", options: ["hərəkət/hal", "əşya", "əlamət", "miqdar"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-feil-l1-t15", type: "fill_blank", prompt: "'danış' feilinin inkar formasını yaz.", accepted: ["danışma"], xp: 15, skills: ["az.pos.verb"] },
          ],
          bonusTasks: [
            { id: "az7-feil-l1-b1", type: "multiple_choice", prompt: "'Mən heç vaxt yalan danışmaram.' cümləsində feil hansıdır?", options: ["danışmaram", "heç vaxt", "yalan", "mən"], correctIndex: 0, xp: 15, skills: ["az.pos.verb"] },
            { id: "az7-feil-l1-b2", type: "fill_blank", prompt: "'işlə' feilinin inkar formasını yaz.", accepted: ["işləmə"], xp: 15, skills: ["az.pos.verb"] },
            { id: "az7-feil-l1-b3", type: "multiple_choice", prompt: "Hansı söz feildən düzəlməyib?", options: ["kitabça", "yazı", "baxış", "gülüş"], correctIndex: 0, xp: 15, skills: ["az.pos.verb"] },
            { id: "az7-feil-l1-b4", type: "multiple_choice", prompt: "'oxumamışdı' feili neçə dəfə şəkilçi qəbul edib təxminən? (mürəkkəb formadır)", options: ["çox (mürəkkəb)", "heç", "yalnız bir", "sözdür, şəkilçi yox"], correctIndex: 0, xp: 15, skills: ["az.morph.root","az.pos.verb"] },
            { id: "az7-feil-l1-b5", type: "multiple_choice", prompt: "'nə olmaq?' sualına cavab verən feilə misal?", options: ["böyümək", "qaçmaq", "yazmaq", "oxumaq"], correctIndex: 0, xp: 15, skills: ["az.pos.verb"] },
          ],
        },
        {
          id: "az7-feil-l2",
          title: "Feilin quruluşca növləri",
          intro: "Feillər quruluşca sadə, düzəltmə və mürəkkəb olur.",
          sections: [
            { heading: "Sadə feil", body: "Yalnız kökdən (və qrammatik şəkilçilərdən) ibarət feil sadədir: yaz, gəl, oxu, bax." },
            { heading: "Düzəltmə feil", body: "Sözdüzəldici şəkilçi ilə düzələn feil: ağ → ağar-maq, təmiz → təmizlə-mək, su → sula-maq." },
            { heading: "Mürəkkəb feil", body: "İki sözün birləşməsindən əmələ gələn feil: kömək etmək, əl çalmaq, iştirak etmək, qəbul etmək." },
          ],
          tasks: [
            { id: "az7-feil-l2-t1", type: "multiple_choice", prompt: "'yazmaq' feili quruluşca necədir?", options: ["sadə", "düzəltmə", "mürəkkəb", "alınma"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-feil-l2-t2", type: "multiple_choice", prompt: "'təmizləmək' feili quruluşca necədir?", options: ["düzəltmə", "sadə", "mürəkkəb", "alınma"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-feil-l2-t3", type: "multiple_choice", prompt: "'kömək etmək' feili quruluşca necədir?", options: ["mürəkkəb", "sadə", "düzəltmə", "alınma"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-feil-l2-t4", type: "multiple_choice", prompt: "Aşağıdakılardan hansı sadə feildir?", options: ["gəlmək", "sulamaq", "iştirak etmək", "ağarmaq"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-feil-l2-t5", type: "multiple_choice", prompt: "Aşağıdakılardan hansı düzəltmə feildir?", options: ["gözləmək", "baxmaq", "qəbul etmək", "oxumaq"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation","az.pos.verb"] },
            { id: "az7-feil-l2-t6", type: "multiple_choice", prompt: "Aşağıdakılardan hansı mürəkkəb feildir?", options: ["əl çalmaq", "yazmaq", "sulamaq", "gəlmək"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-feil-l2-t7", type: "multiple_choice", prompt: "'sulamaq' feilinin kökü hansıdır?", options: ["su", "sula", "lamaq", "sul"], correctIndex: 0, xp: 10, skills: ["az.morph.root","az.pos.verb"] },
            { id: "az7-feil-l2-t8", type: "multiple_choice", prompt: "Düzəltmə feil necə əmələ gəlir?", options: ["sözdüzəldici şəkilçi ilə", "iki sözün birləşməsi ilə", "yalnız kökdən", "qoşma ilə"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation","az.pos.verb"] },
            { id: "az7-feil-l2-t9", type: "multiple_choice", prompt: "'iştirak etmək' neçə sözdən ibarətdir?", options: ["iki", "bir", "üç", "dörd"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_tense"] },
            { id: "az7-feil-l2-t10", type: "multiple_choice", prompt: "'baxmaq' feili quruluşca necədir?", options: ["sadə", "düzəltmə", "mürəkkəb", "alınma"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-feil-l2-t11", type: "multiple_choice", prompt: "'işıqlanmaq' feili quruluşca necədir?", options: ["düzəltmə", "sadə", "mürəkkəb", "alınma"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-feil-l2-t12", type: "multiple_choice", prompt: "'qəbul etmək' feili quruluşca necədir?", options: ["mürəkkəb", "sadə", "düzəltmə", "alınma"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-feil-l2-t13", type: "multiple_choice", prompt: "Hansı feil kökdən + sözdüzəldici şəkilçidən ibarətdir?", options: ["gözləmək", "gəlmək", "yazmaq", "baxmaq"], correctIndex: 0, xp: 10, skills: ["az.morph.root","az.pos.verb"] },
            { id: "az7-feil-l2-t14", type: "multiple_choice", prompt: "'söhbət etmək' feili quruluşca necədir?", options: ["mürəkkəb", "sadə", "düzəltmə", "alınma"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-feil-l2-t15", type: "multiple_choice", prompt: "'oxumaq' feili quruluşca necədir?", options: ["sadə", "düzəltmə", "mürəkkəb", "alınma"], correctIndex: 0, xp: 15, skills: ["az.pos.verb"] },
          ],
          bonusTasks: [
            { id: "az7-feil-l2-b1", type: "multiple_choice", prompt: "'yaşıllaşmaq' feili quruluşca necədir?", options: ["düzəltmə", "sadə", "mürəkkəb", "alınma"], correctIndex: 0, xp: 15, skills: ["az.pos.verb"] },
            { id: "az7-feil-l2-b2", type: "multiple_choice", prompt: "'imtahan vermək' feili quruluşca necədir?", options: ["mürəkkəb", "sadə", "düzəltmə", "alınma"], correctIndex: 0, xp: 15, skills: ["az.pos.verb"] },
            { id: "az7-feil-l2-b3", type: "multiple_choice", prompt: "Hansı sırada yalnız mürəkkəb feillər var?", options: ["kömək etmək, əl çalmaq", "yazmaq, gəlmək", "sulamaq, ağarmaq", "baxmaq, oxumaq"], correctIndex: 0, xp: 15, skills: ["az.pos.verb"] },
            { id: "az7-feil-l2-b4", type: "multiple_choice", prompt: "'duzlamaq' feilinin kökü hansıdır?", options: ["duz", "duzla", "lamaq", "duzl"], correctIndex: 0, xp: 15, skills: ["az.morph.root","az.pos.verb"] },
            { id: "az7-feil-l2-b5", type: "multiple_choice", prompt: "Hansı feil düzəltmədir?", options: ["genişlənmək", "getmək", "durmaq", "vermək"], correctIndex: 0, xp: 15, skills: ["az.morph.derivation","az.pos.verb"] },
          ],
        },
        {
          id: "az7-feil-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az7-feil-l3",
          title: "Feilin zamanları",
          intro: "Feil üç zamanda olur: keçmiş, indiki və gələcək zaman.",
          sections: [
            { heading: "Keçmiş zaman", body: "İş danışıqdan əvvəl olub. Şühudi keçmiş -dı⁴ (yazdı), nəqli keçmiş -mış⁴ (yazmış/yazıb). Məs.: gəldi, oxudu, baxmışdı." },
            { heading: "İndiki zaman", body: "İş danışıq anında baş verir. Şəkilçisi -ır⁴/-yır⁴: yazır, oxuyur, gəlir." },
            { heading: "Gələcək zaman", body: "İş sonra baş verəcək. Qəti gələcək -acaq²/-əcək (yazacaq), qeyri-qəti gələcək -ar²/-ər (yazar, gələr)." },
          ],
          tasks: [
            { id: "az7-feil-l3-t1", type: "multiple_choice", prompt: "'yazdı' feili hansı zamandadır?", options: ["keçmiş", "indiki", "gələcək", "əmr"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_tense"] },
            { id: "az7-feil-l3-t2", type: "multiple_choice", prompt: "'yazır' feili hansı zamandadır?", options: ["indiki", "keçmiş", "gələcək", "əmr"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_tense"] },
            { id: "az7-feil-l3-t3", type: "multiple_choice", prompt: "'yazacaq' feili hansı zamandadır?", options: ["gələcək", "indiki", "keçmiş", "əmr"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_tense"] },
            { id: "az7-feil-l3-t4", type: "multiple_choice", prompt: "İndiki zaman şəkilçisi hansıdır?", options: ["-ır/-ir/-ur/-ür", "-dı/-di", "-acaq/-əcək", "-mış/-miş"], correctIndex: 0, xp: 10, skills: ["az.morph.root"] },
            { id: "az7-feil-l3-t5", type: "multiple_choice", prompt: "'gəldi' feili hansı zamandadır?", options: ["keçmiş", "indiki", "gələcək", "arzu"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_tense"] },
            { id: "az7-feil-l3-t6", type: "multiple_choice", prompt: "'oxuyur' feili hansı zamandadır?", options: ["indiki", "keçmiş", "gələcək", "əmr"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_tense"] },
            { id: "az7-feil-l3-t7", type: "multiple_choice", prompt: "Qəti gələcək zaman şəkilçisi hansıdır?", options: ["-acaq/-əcək", "-ar/-ər", "-ır/-ir", "-dı/-di"], correctIndex: 0, xp: 10, skills: ["az.morph.root"] },
            { id: "az7-feil-l3-t8", type: "fill_blank", prompt: "'gəl' feilini indiki zamana çevir (3-cü şəxs tək).", accepted: ["gəlir"], xp: 10, skills: ["az.pos.verb_tense"] },
            { id: "az7-feil-l3-t9", type: "fill_blank", prompt: "'yaz' feilini qəti gələcək zamana çevir (3-cü şəxs tək).", accepted: ["yazacaq"], xp: 10, skills: ["az.pos.verb_tense"] },
            { id: "az7-feil-l3-t10", type: "multiple_choice", prompt: "'baxmışdı' feili hansı zamandadır?", options: ["keçmiş", "indiki", "gələcək", "indiki-gələcək"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_tense"] },
            { id: "az7-feil-l3-t11", type: "multiple_choice", prompt: "'gələr' feili hansı zamandadır?", options: ["qeyri-qəti gələcək", "keçmiş", "indiki", "əmr"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_tense"] },
            { id: "az7-feil-l3-t12", type: "fill_blank", prompt: "'oxu' feilini keçmiş zamana çevir (şühudi, 3-cü şəxs tək).", accepted: ["oxudu"], xp: 10, skills: ["az.pos.verb_tense"] },
            { id: "az7-feil-l3-t13", type: "multiple_choice", prompt: "Danışıq anında baş verən iş hansı zamandır?", options: ["indiki", "keçmiş", "gələcək", "arzu"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_tense"] },
            { id: "az7-feil-l3-t14", type: "multiple_choice", prompt: "Şühudi keçmiş zaman şəkilçisi hansıdır?", options: ["-dı/-di/-du/-dü", "-mış/-miş", "-ır/-ir", "-acaq/-əcək"], correctIndex: 0, xp: 10, skills: ["az.morph.root"] },
            { id: "az7-feil-l3-t15", type: "multiple_choice", prompt: "'işləyəcək' feili hansı zamandadır?", options: ["gələcək", "indiki", "keçmiş", "əmr"], correctIndex: 0, xp: 15, skills: ["az.pos.verb_tense"] },
          ],
          bonusTasks: [
            { id: "az7-feil-l3-b1", type: "multiple_choice", prompt: "'yazmışam' feili hansı zamandadır?", options: ["nəqli keçmiş", "şühudi keçmiş", "indiki", "gələcək"], correctIndex: 0, xp: 15, skills: ["az.pos.verb_tense"] },
            { id: "az7-feil-l3-b2", type: "fill_blank", prompt: "'bax' feilini indiki zamana çevir (3-cü şəxs tək).", accepted: ["baxır"], xp: 15, skills: ["az.pos.verb_tense"] },
            { id: "az7-feil-l3-b3", type: "multiple_choice", prompt: "'Sabah məktəbə gedəcəyəm.' cümləsindəki feil hansı zamandadır?", options: ["gələcək", "indiki", "keçmiş", "arzu"], correctIndex: 0, xp: 15, skills: ["az.pos.verb_tense"] },
            { id: "az7-feil-l3-b4", type: "multiple_choice", prompt: "'Hər səhər idman edirəm.' cümləsindəki feil hansı zamandadır?", options: ["indiki", "keçmiş", "gələcək", "əmr"], correctIndex: 0, xp: 15, skills: ["az.pos.verb_tense"] },
            { id: "az7-feil-l3-b5", type: "fill_blank", prompt: "'gəl' feilini qəti gələcək zamana çevir (3-cü şəxs tək).", accepted: ["gələcək"], xp: 15, skills: ["az.pos.verb_tense"] },
          ],
        },
        {
          id: "az7-feil-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        }
      ],
    },
    // ═══════════════ 2. Feilin qrammatik məna növləri ═══════════════
    {
      id: "az7-nov",
      title: "Feilin qrammatik məna növləri",
      description:
        "Feilin beş məna növü: məlum, məchul, qayıdış, qarşılıq-birgəlik və icbar növ.",
      lessons: [
        {
          id: "az7-nov-l1",
          title: "Məlum və məchul növ",
          intro: "İşin icraçısı bəlli olduqda məlum, bəlli olmadıqda məchul növ.",
          sections: [
            { heading: "Məlum növ", body: "İşi görənin (subyektin) kim olduğu bəllidir: Uşaq kitabı oxudu. (icraçı — uşaq)." },
            { heading: "Məchul növ", body: "İşi görən bəlli deyil. -ıl⁴/-ın⁴ şəkilçisi ilə düzəlir: Kitab oxundu. Ev tikildi. Məktub yazıldı." },
          ],
          tasks: [
            { id: "az7-nov-l1-t1", type: "multiple_choice", prompt: "'Uşaq kitabı oxudu.' — feil hansı növdədir?", options: ["məlum", "məchul", "qayıdış", "icbar"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-nov-l1-t2", type: "multiple_choice", prompt: "'Kitab oxundu.' — feil hansı növdədir?", options: ["məchul", "məlum", "qayıdış", "icbar"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-nov-l1-t3", type: "multiple_choice", prompt: "Məchul növ şəkilçisi hansıdır?", options: ["-ıl/-il, -ın/-in", "-ma/-mə", "-dır/-dir", "-laş/-ləş"], correctIndex: 0, xp: 10, skills: ["az.morph.root","az.pos.verb_voice"] },
            { id: "az7-nov-l1-t4", type: "multiple_choice", prompt: "Hansı feil məchuldur?", options: ["yazıldı", "yazdı", "yazır", "yazacaq"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_voice","az.pos.verb"] },
            { id: "az7-nov-l1-t5", type: "multiple_choice", prompt: "Məlum növdə nə bəllidir?", options: ["işi görən (icraçı)", "yalnız iş", "zaman", "yer"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_voice"] },
            { id: "az7-nov-l1-t6", type: "fill_blank", prompt: "'yaz' feilini məchul növə çevir (keçmiş, 3-cü şəxs).", accepted: ["yazıldı"], xp: 10, skills: ["az.pos.verb_voice","az.pos.verb_tense"] },
            { id: "az7-nov-l1-t7", type: "fill_blank", prompt: "'tik' feilini məchul növə çevir (keçmiş, 3-cü şəxs).", accepted: ["tikildi"], xp: 10, skills: ["az.pos.verb_voice","az.pos.verb_tense"] },
            { id: "az7-nov-l1-t8", type: "multiple_choice", prompt: "'Ev tikildi.' cümləsində feil hansı növdədir?", options: ["məchul", "məlum", "qayıdış", "qarşılıq"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-nov-l1-t9", type: "multiple_choice", prompt: "'Ana uşağı geyindirdi.' cümləsindəki feilin növünə ən yaxın?", options: ["məlum (icraçı bəlli)", "məchul", "yoxdur", "yalnız qayıdış"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_voice","az.pos.verb"] },
            { id: "az7-nov-l1-t10", type: "multiple_choice", prompt: "Hansı cümlədə feil məchuldur?", options: ["Məktub göndərildi.", "O məktub göndərdi.", "Uşaq oxuyur.", "Biz gəldik."], correctIndex: 0, xp: 10, skills: ["az.pos.verb_voice","az.pos.verb"] },
            { id: "az7-nov-l1-t11", type: "fill_blank", prompt: "'oxu' feilini məchul növə çevir (keçmiş, 3-cü şəxs).", accepted: ["oxundu"], xp: 10, skills: ["az.pos.verb_voice","az.pos.verb_tense"] },
            { id: "az7-nov-l1-t12", type: "multiple_choice", prompt: "'açıldı' feili hansı növdədir?", options: ["məchul", "məlum", "icbar", "qarşılıq"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-nov-l1-t13", type: "multiple_choice", prompt: "'Bağçada güllər sulandı.' feili hansı növə yaxındır?", options: ["məchul", "məlum", "icbar", "qarşılıq"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-nov-l1-t14", type: "multiple_choice", prompt: "Məchul növdə iş kimin tərəfindən görülür?", options: ["bəlli deyil", "həmişə uşaq", "danışan", "yalnız cəm"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_voice"] },
            { id: "az7-nov-l1-t15", type: "fill_blank", prompt: "'sil' feilini məchul növə çevir (keçmiş, 3-cü şəxs).", accepted: ["silindi"], xp: 15, skills: ["az.pos.verb_voice","az.pos.verb_tense"] },
          ],
          bonusTasks: [
            { id: "az7-nov-l1-b1", type: "multiple_choice", prompt: "'Divar boyandı.' feili hansı növdədir?", options: ["məchul", "məlum", "icbar", "qayıdış"], correctIndex: 0, xp: 15, skills: ["az.pos.verb"] },
            { id: "az7-nov-l1-b2", type: "fill_blank", prompt: "'gör' feilini məchul növə çevir (keçmiş, 3-cü şəxs).", accepted: ["görüldü"], xp: 15, skills: ["az.pos.verb_voice","az.pos.verb_tense"] },
            { id: "az7-nov-l1-b3", type: "multiple_choice", prompt: "Hansı sırada yalnız məchul feillər var?", options: ["yazıldı, oxundu, tikildi", "yazdı, oxudu, tikdi", "yazır, oxuyur, tikir", "yazacaq, oxuyacaq"], correctIndex: 0, xp: 15, skills: ["az.pos.verb_voice","az.pos.verb"] },
            { id: "az7-nov-l1-b4", type: "multiple_choice", prompt: "'Şeir əzbərləndi.' cümləsində icraçı bəllidir?", options: ["xeyr (məchul)", "bəli", "yalnız zaman", "yalnız yer"], correctIndex: 0, xp: 15, skills: ["az.syn.sentence","az.text.genre"] },
            { id: "az7-nov-l1-b5", type: "fill_blank", prompt: "'qır' feilini məchul növə çevir (keçmiş, 3-cü şəxs).", accepted: ["qırıldı"], xp: 15, skills: ["az.pos.verb_voice","az.pos.verb_tense"] },
          ],
        },
        {
          id: "az7-nov-l2",
          title: "Qayıdış və qarşılıq növ",
          intro: "İş icraçının özünə qayıdırsa qayıdış, qarşılıqlı/birgə görülürsə qarşılıq növ.",
          sections: [
            { heading: "Qayıdış növ", body: "İcraçı işi öz üzərində icra edir. -ın⁴/-n şəkilçisi: geyindi, yuyundu, darandı, hazırlandı. (özü-özünü geyindirdi)." },
            { heading: "Qarşılıq-birgəlik növ", body: "İş iki və ya çox subyekt tərəfindən qarşılıqlı və ya birgə görülür. -ış⁴/-laş⁴ şəkilçisi: görüşdü, məktublaşdı, salamlaşdı, öpüşdü." },
          ],
          tasks: [
            { id: "az7-nov-l2-t1", type: "multiple_choice", prompt: "'yuyundu' feili hansı növdədir?", options: ["qayıdış", "qarşılıq", "məchul", "icbar"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-nov-l2-t2", type: "multiple_choice", prompt: "'görüşdü' feili hansı növdədir?", options: ["qarşılıq", "qayıdış", "məchul", "icbar"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-nov-l2-t3", type: "multiple_choice", prompt: "Qayıdış növdə iş kimə yönəlir?", options: ["icraçının özünə", "başqasına", "əşyaya", "heç kimə"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_voice"] },
            { id: "az7-nov-l2-t4", type: "multiple_choice", prompt: "'salamlaşdı' feili hansı növdədir?", options: ["qarşılıq", "qayıdış", "məchul", "məlum"], correctIndex: 0, xp: 10, skills: ["az.pos.verb","az.text.etiquette"] },
            { id: "az7-nov-l2-t5", type: "multiple_choice", prompt: "'geyindi' feili hansı növdədir?", options: ["qayıdış", "qarşılıq", "məchul", "icbar"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-nov-l2-t6", type: "multiple_choice", prompt: "Qarşılıq növ neçə subyektin iştirakını bildirir?", options: ["iki və ya çox", "yalnız bir", "heç", "yalnız üç"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_voice"] },
            { id: "az7-nov-l2-t7", type: "multiple_choice", prompt: "'darandı' feili hansı növdədir?", options: ["qayıdış", "qarşılıq", "məchul", "icbar"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-nov-l2-t8", type: "multiple_choice", prompt: "'məktublaşdılar' feili hansı növdədir?", options: ["qarşılıq", "qayıdış", "məchul", "məlum"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-nov-l2-t9", type: "multiple_choice", prompt: "Hansı feil qayıdışdır?", options: ["hazırlandı", "görüşdü", "yazıldı", "yazdırdı"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_voice","az.pos.verb"] },
            { id: "az7-nov-l2-t10", type: "multiple_choice", prompt: "Hansı feil qarşılıqdır?", options: ["öpüşdü", "yuyundu", "geyindi", "silindi"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_voice","az.pos.verb"] },
            { id: "az7-nov-l2-t11", type: "fill_blank", prompt: "'geyin-' kökünə uyğun qayıdış feil: 'uşaq özü ___'.", accepted: ["geyindi"], xp: 10, skills: ["az.morph.root","az.pos.verb_voice","az.pos.verb"] },
            { id: "az7-nov-l2-t12", type: "multiple_choice", prompt: "'baxışdılar' feili hansı növdədir?", options: ["qarşılıq", "qayıdış", "məchul", "məlum"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-nov-l2-t13", type: "multiple_choice", prompt: "'Uşaq soyundu.' feili hansı növdədir?", options: ["qayıdış", "qarşılıq", "məchul", "icbar"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-nov-l2-t14", type: "multiple_choice", prompt: "'vuruşdular' feili hansı növdədir?", options: ["qarşılıq", "qayıdış", "məchul", "məlum"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-nov-l2-t15", type: "multiple_choice", prompt: "'hazırlandı' feilində iş kimə qayıdır?", options: ["icraçının özünə", "başqasına", "əşyaya", "heç kimə"], correctIndex: 0, xp: 15, skills: ["az.pos.verb"] },
          ],
          bonusTasks: [
            { id: "az7-nov-l2-b1", type: "multiple_choice", prompt: "'Onlar məktubla yazışırdılar.' feili hansı növdədir?", options: ["qarşılıq", "qayıdış", "məchul", "icbar"], correctIndex: 0, xp: 15, skills: ["az.pos.verb"] },
            { id: "az7-nov-l2-b2", type: "multiple_choice", prompt: "Hansı sırada qayıdış feillər var?", options: ["yuyundu, geyindi, darandı", "görüşdü, öpüşdü", "yazıldı, oxundu", "yazdırdı, oxutdurdu"], correctIndex: 0, xp: 15, skills: ["az.pos.verb_voice","az.pos.verb"] },
            { id: "az7-nov-l2-b3", type: "multiple_choice", prompt: "'söhbətləşdilər' hansı növdədir?", options: ["qarşılıq", "qayıdış", "məchul", "məlum"], correctIndex: 0, xp: 15, skills: ["az.pos.verb_voice"] },
            { id: "az7-nov-l2-b4", type: "multiple_choice", prompt: "Qayıdış və məchul növün şəkilçiləri bəzən oxşardır. Fərq nədir?", options: ["qayıdışda icraçı işi özünə edir", "heç fərq yox", "məchulda icraçı bəlli", "qayıdış həmişə cəm"], correctIndex: 0, xp: 15, skills: ["az.morph.root","az.pos.verb_voice"] },
            { id: "az7-nov-l2-b5", type: "multiple_choice", prompt: "'küsüşdülər' feili hansı növdədir?", options: ["qarşılıq", "qayıdış", "məchul", "məlum"], correctIndex: 0, xp: 15, skills: ["az.pos.verb"] },
          ],
        },
        {
          id: "az7-nov-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az7-nov-l3",
          title: "İcbar növ və növlərin təkrarı",
          intro: "İş başqasına gördürülürsə icbar növ. Beş növün ümumi təkrarı.",
          sections: [
            { heading: "İcbar növ", body: "İcraçı işi özü görmür, başqasına gördürür. -dır⁴/-t/-ıt⁴ şəkilçisi: yazdırdı, oxutdu, tikdirdi, geyindirdi. (Müəllim şagirdə şeir əzbərlətdi.)" },
            { heading: "Beş növ", body: "Məlum, məchul, qayıdış, qarşılıq-birgəlik, icbar. Yalnız məlum növün xüsusi şəkilçisi yoxdur." },
          ],
          tasks: [
            { id: "az7-nov-l3-t1", type: "multiple_choice", prompt: "'yazdırdı' feili hansı növdədir?", options: ["icbar", "məlum", "məchul", "qayıdış"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-nov-l3-t2", type: "multiple_choice", prompt: "İcbar növdə iş kim tərəfindən görülür?", options: ["başqasına gördürülür", "icraçının özü", "bəlli deyil", "qarşılıqlı"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_voice"] },
            { id: "az7-nov-l3-t3", type: "multiple_choice", prompt: "İcbar növ şəkilçisi hansıdır?", options: ["-dır/-dir, -t, -ıt", "-ıl/-il", "-ış/-iş", "-ma/-mə"], correctIndex: 0, xp: 10, skills: ["az.morph.root"] },
            { id: "az7-nov-l3-t4", type: "multiple_choice", prompt: "'oxutdu' feili hansı növdədir?", options: ["icbar", "məlum", "məchul", "qayıdış"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-nov-l3-t5", type: "multiple_choice", prompt: "Feilin neçə məna növü var?", options: ["beş", "üç", "dörd", "altı"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-nov-l3-t6", type: "multiple_choice", prompt: "Hansı növün xüsusi şəkilçisi yoxdur?", options: ["məlum", "məchul", "icbar", "qayıdış"], correctIndex: 0, xp: 10, skills: ["az.morph.root"] },
            { id: "az7-nov-l3-t7", type: "multiple_choice", prompt: "'tikdirdi' feili hansı növdədir?", options: ["icbar", "məchul", "qayıdış", "qarşılıq"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-nov-l3-t8", type: "fill_blank", prompt: "'yaz' feilini icbar növə çevir (keçmiş, 3-cü şəxs).", accepted: ["yazdırdı"], xp: 10, skills: ["az.pos.verb_voice","az.pos.verb_tense"] },
            { id: "az7-nov-l3-t9", type: "multiple_choice", prompt: "'Müəllim şagirdə məsələ həll etdirdi.' feili hansı növdədir?", options: ["icbar", "məlum", "məchul", "qayıdış"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-nov-l3-t10", type: "multiple_choice", prompt: "'oxundu' feili hansı növdədir?", options: ["məchul", "icbar", "qayıdış", "məlum"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-nov-l3-t11", type: "multiple_choice", prompt: "'geyindi' feili hansı növdədir?", options: ["qayıdış", "icbar", "məchul", "qarşılıq"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-nov-l3-t12", type: "multiple_choice", prompt: "'görüşdülər' feili hansı növdədir?", options: ["qarşılıq", "icbar", "məchul", "qayıdış"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-nov-l3-t13", type: "multiple_choice", prompt: "'Uşaq kitabı oxudu.' feili hansı növdədir?", options: ["məlum", "icbar", "məchul", "qayıdış"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-nov-l3-t14", type: "fill_blank", prompt: "'oxu' feilini icbar növə çevir (keçmiş, 3-cü şəxs).", accepted: ["oxutdu"], xp: 10, skills: ["az.pos.verb_voice","az.pos.verb_tense"] },
            { id: "az7-nov-l3-t15", type: "multiple_choice", prompt: "'geyindirdi' feili hansı növdədir?", options: ["icbar", "qayıdış", "məchul", "qarşılıq"], correctIndex: 0, xp: 15, skills: ["az.pos.verb"] },
          ],
          bonusTasks: [
            { id: "az7-nov-l3-b1", type: "multiple_choice", prompt: "Aşağıdakılardan hansı icbar növdədir?", options: ["yazdırdı", "yazıldı", "yuyundu", "görüşdü"], correctIndex: 0, xp: 15, skills: ["az.pos.verb_voice"] },
            { id: "az7-nov-l3-b2", type: "multiple_choice", prompt: "'daşıtdırdı' feili hansı növdədir?", options: ["icbar", "məchul", "qayıdış", "qarşılıq"], correctIndex: 0, xp: 15, skills: ["az.pos.verb"] },
            { id: "az7-nov-l3-b3", type: "multiple_choice", prompt: "'Bağban ağacları suvardı, sonra fəhləyə də suvartdırdı.' — sonuncu feil?", options: ["icbar", "məlum", "məchul", "qayıdış"], correctIndex: 0, xp: 15, skills: ["az.pos.verb"] },
            { id: "az7-nov-l3-b4", type: "multiple_choice", prompt: "Hansı cütlük düzgündür?", options: ["yazıldı — məchul", "yazdırdı — məchul", "yuyundu — icbar", "görüşdü — qayıdış"], correctIndex: 0, xp: 15, skills: ["az.pos.verb_voice"] },
            { id: "az7-nov-l3-b5", type: "fill_blank", prompt: "'tik' feilini icbar növə çevir (keçmiş, 3-cü şəxs).", accepted: ["tikdirdi"], xp: 15, skills: ["az.pos.verb_voice","az.pos.verb_tense"] },
          ],
        },
        {
          id: "az7-nov-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        }
      ],
    },
    // ═══════════════ 3. Təsriflənməyən feillər ═══════════════
    {
      id: "az7-tesrif",
      title: "Təsriflənməyən feillər",
      description:
        "Şəxsə və zamana görə dəyişməyən feil formaları: məsdər, feili sifət və feili bağlama.",
      lessons: [
        {
          id: "az7-tesrif-l1",
          title: "Məsdər",
          intro: "Feilin -maq²/-mək şəkilçili, iş adını bildirən formasıdır.",
          sections: [
            { heading: "Məsdər nədir?", body: "İşin adını bildirən, -maq/-mək şəkilçili feil formasına məsdər deyilir: yazmaq, oxumaq, gəlmək. Məsdər həm feilə (iş bildirir), həm də isimə (hallanır) oxşayır." },
            { heading: "Xüsusiyyəti", body: "Məsdər şəxsə və zamana görə dəyişmir (təsriflənmir), amma isim kimi hallana bilir: oxumaq — oxumağı, oxumağa, oxumaqda." },
          ],
          tasks: [
            { id: "az7-tesrif-l1-t1", type: "multiple_choice", prompt: "Məsdər şəkilçisi hansıdır?", options: ["-maq/-mək", "-an/-ən", "-ıb/-ib", "-dıqca"], correctIndex: 0, xp: 10, skills: ["az.morph.root","az.pos.verb_nonfinite"] },
            { id: "az7-tesrif-l1-t2", type: "multiple_choice", prompt: "Aşağıdakılardan hansı məsdərdir?", options: ["oxumaq", "oxuyan", "oxuyub", "oxudu"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite"] },
            { id: "az7-tesrif-l1-t3", type: "multiple_choice", prompt: "Məsdər nə bildirir?", options: ["işin adını", "əşyanın əlamətini", "sayı", "yeri"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite"] },
            { id: "az7-tesrif-l1-t4", type: "fill_blank", prompt: "'gəl' feilinin məsdər formasını yaz.", accepted: ["gəlmək"], xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
            { id: "az7-tesrif-l1-t5", type: "fill_blank", prompt: "'yaz' feilinin məsdər formasını yaz.", accepted: ["yazmaq"], xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
            { id: "az7-tesrif-l1-t6", type: "multiple_choice", prompt: "Məsdər hansı iki nitq hissəsinə oxşayır?", options: ["feilə və isimə", "sifətə və zərfə", "saya və əvəzliyə", "yalnız feilə"], correctIndex: 0, xp: 10, skills: ["az.phon.letters","az.pos.verb_nonfinite"] },
            { id: "az7-tesrif-l1-t7", type: "multiple_choice", prompt: "'İdman etmək sağlamlıqdır.' cümləsində məsdər hansıdır?", options: ["etmək", "idman", "sağlamlıq", "sağlamlıqdır"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite"] },
            { id: "az7-tesrif-l1-t8", type: "multiple_choice", prompt: "Məsdər zamana görə dəyişirmi?", options: ["xeyr (təsriflənmir)", "bəli", "yalnız keçmişdə", "yalnız gələcəkdə"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite"] },
            { id: "az7-tesrif-l1-t9", type: "fill_blank", prompt: "'oxu' feilinin məsdər formasını yaz.", accepted: ["oxumaq"], xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
            { id: "az7-tesrif-l1-t10", type: "multiple_choice", prompt: "'oxumağı' sözü məsdərin hansı formasıdır?", options: ["hallanmış (təsirlik hal)", "cəm", "inkar", "feili sifət"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite"] },
            { id: "az7-tesrif-l1-t11", type: "multiple_choice", prompt: "Aşağıdakılardan hansı məsdər DEYİL?", options: ["yazan", "yazmaq", "gəlmək", "oxumaq"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite"] },
            { id: "az7-tesrif-l1-t12", type: "fill_blank", prompt: "'işlə' feilinin məsdər formasını yaz.", accepted: ["işləmək"], xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
            { id: "az7-tesrif-l1-t13", type: "multiple_choice", prompt: "'gülmək' sözü hansı formadadır?", options: ["məsdər", "feili sifət", "feili bağlama", "əmr"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite"] },
            { id: "az7-tesrif-l1-t14", type: "multiple_choice", prompt: "Məsdər isim kimi nə edə bilir?", options: ["hallana bilir", "zamana görə dəyişir", "şəxsə görə dəyişir", "əmr olur"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.noun"] },
            { id: "az7-tesrif-l1-t15", type: "fill_blank", prompt: "'danış' feilinin məsdər formasını yaz.", accepted: ["danışmaq"], xp: 15, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
          ],
          bonusTasks: [
            { id: "az7-tesrif-l1-b1", type: "multiple_choice", prompt: "'Oxumaq mənə xoşdur.' cümləsində məsdər hansı üzvdür (təxminən)?", options: ["mübtəda kimi", "xəbər kimi", "zərflik", "yoxdur"], correctIndex: 0, xp: 15, skills: ["az.pos.verb_nonfinite"] },
            { id: "az7-tesrif-l1-b2", type: "fill_blank", prompt: "'gör' feilinin məsdər formasını yaz.", accepted: ["görmək"], xp: 15, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
            { id: "az7-tesrif-l1-b3", type: "multiple_choice", prompt: "'yazmaqdan' sözü nədir?", options: ["hallanmış məsdər", "feili sifət", "feili bağlama", "sadə isim"], correctIndex: 0, xp: 15, skills: ["az.pos.verb_nonfinite"] },
            { id: "az7-tesrif-l1-b4", type: "multiple_choice", prompt: "Hansı sırada yalnız məsdərlər var?", options: ["gəlmək, yazmaq, oxumaq", "gələn, yazan, oxuyan", "gəlib, yazıb, oxuyub", "gəldi, yazdı, oxudu"], correctIndex: 0, xp: 15, skills: ["az.pos.verb_nonfinite"] },
            { id: "az7-tesrif-l1-b5", type: "fill_blank", prompt: "'bil' feilinin məsdər formasını yaz.", accepted: ["bilmək"], xp: 15, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
          ],
        },
        {
          id: "az7-tesrif-l2",
          title: "Feili sifət",
          intro: "Həm feilə, həm sifətə aid xüsusiyyət daşıyan, əşyanın əlamətini iş kimi bildirən forma.",
          sections: [
            { heading: "Feili sifət nədir?", body: "Feildən əmələ gələn, əşyanın əlamətini bildirən formadır. Şəkilçiləri: -an²/-yan², -mış⁴, -ası²/-əsi, -dıq⁴, -acaq²/-əcək. Məs.: oxuyan uşaq, yazılmış məktub, görünəcək mənzərə." },
            { heading: "Sifətə oxşarlığı", body: "İsimdən əvvəl gəlib onu təyin edir: gələn qonaq, açılan qapı, solmuş gül. 'Necə?', 'hansı?' sualına cavab verir." },
          ],
          tasks: [
            { id: "az7-tesrif-l2-t1", type: "multiple_choice", prompt: "Aşağıdakılardan hansı feili sifətdir?", options: ["oxuyan", "oxumaq", "oxuyub", "oxudu"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.adjective","az.pos.verb"] },
            { id: "az7-tesrif-l2-t2", type: "multiple_choice", prompt: "Feili sifət nəyi bildirir?", options: ["əşyanın əlamətini", "işin adını", "işin tərzini", "sayı"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.adjective","az.pos.verb"] },
            { id: "az7-tesrif-l2-t3", type: "multiple_choice", prompt: "'gələn qonaq' ifadəsində feili sifət hansıdır?", options: ["gələn", "qonaq", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.adjective","az.pos.verb"] },
            { id: "az7-tesrif-l2-t4", type: "multiple_choice", prompt: "Feili sifət şəkilçilərindən biri hansıdır?", options: ["-an/-ən", "-maq/-mək", "-araq/-ərək", "-dıqca"], correctIndex: 0, xp: 10, skills: ["az.morph.root","az.pos.verb_nonfinite","az.pos.adjective","az.pos.verb"] },
            { id: "az7-tesrif-l2-t5", type: "fill_blank", prompt: "'oxu' feilindən -an şəkilçisi ilə feili sifət düzəlt.", accepted: ["oxuyan"], xp: 10, skills: ["az.morph.root","az.pos.verb_nonfinite","az.pos.adjective","az.pos.verb"] },
            { id: "az7-tesrif-l2-t6", type: "fill_blank", prompt: "'gəl' feilindən -ən şəkilçisi ilə feili sifət düzəlt.", accepted: ["gələn"], xp: 10, skills: ["az.morph.root","az.pos.verb_nonfinite","az.pos.adjective","az.pos.verb"] },
            { id: "az7-tesrif-l2-t7", type: "multiple_choice", prompt: "'yazılmış məktub' — feili sifət hansıdır?", options: ["yazılmış", "məktub", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.adjective","az.pos.verb"] },
            { id: "az7-tesrif-l2-t8", type: "multiple_choice", prompt: "Feili sifət hansı suala cavab verir?", options: ["necə? hansı?", "nə etmək?", "nə qədər?", "harada?"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.adjective","az.pos.verb"] },
            { id: "az7-tesrif-l2-t9", type: "multiple_choice", prompt: "'solmuş gül' — feili sifət hansıdır?", options: ["solmuş", "gül", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.adjective","az.pos.verb"] },
            { id: "az7-tesrif-l2-t10", type: "multiple_choice", prompt: "Feili sifət cümlədə çox vaxt hansı sözdən əvvəl gəlir?", options: ["isimdən", "feildən", "saydan", "qoşmadan"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.adjective","az.pos.verb"] },
            { id: "az7-tesrif-l2-t11", type: "fill_blank", prompt: "'bax' feilindən -an/-ən ilə feili sifət düzəlt.", accepted: ["baxan"], xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.adjective","az.pos.verb"] },
            { id: "az7-tesrif-l2-t12", type: "multiple_choice", prompt: "Aşağıdakılardan hansı feili sifət DEYİL?", options: ["oxumaq", "oxuyan", "oxunmuş", "oxuyacaq"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.adjective","az.pos.verb"] },
            { id: "az7-tesrif-l2-t13", type: "multiple_choice", prompt: "'görünəcək mənzərə' — feili sifət hansıdır?", options: ["görünəcək", "mənzərə", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.adjective","az.pos.verb"] },
            { id: "az7-tesrif-l2-t14", type: "fill_blank", prompt: "'yaz' feilindən -an ilə feili sifət düzəlt.", accepted: ["yazan"], xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.adjective","az.pos.verb"] },
            { id: "az7-tesrif-l2-t15", type: "multiple_choice", prompt: "Feili sifət hansı iki nitq hissəsinin xüsusiyyətini daşıyır?", options: ["feil və sifət", "feil və isim", "sifət və zərf", "isim və say"], correctIndex: 0, xp: 15, skills: ["az.phon.letters","az.pos.verb_nonfinite","az.pos.adjective","az.pos.verb"] },
          ],
          bonusTasks: [
            { id: "az7-tesrif-l2-b1", type: "multiple_choice", prompt: "'Kitab oxuyan uşaq zəkalı olur.' cümləsində feili sifət?", options: ["oxuyan", "kitab", "uşaq", "zəkalı"], correctIndex: 0, xp: 15, skills: ["az.pos.verb_nonfinite","az.pos.adjective","az.pos.verb"] },
            { id: "az7-tesrif-l2-b2", type: "fill_blank", prompt: "'aç' feilindən -ılan/-ilən ilə feili sifət düzəlt (məs. 'açılan qapı').", accepted: ["açılan"], xp: 15, skills: ["az.pos.verb_nonfinite","az.pos.adjective","az.pos.verb"] },
            { id: "az7-tesrif-l2-b3", type: "multiple_choice", prompt: "Hansı sırada yalnız feili sifətlər var?", options: ["gələn, yazılmış, oxuyacaq", "gəlmək, yazmaq", "gəlib, yazıb", "gəldi, yazdı"], correctIndex: 0, xp: 15, skills: ["az.pos.verb_nonfinite","az.pos.adjective","az.pos.verb"] },
            { id: "az7-tesrif-l2-b4", type: "multiple_choice", prompt: "Feili sifəti sadə sifətdən fərqləndirən nədir?", options: ["feildən düzəlir, iş məzmunu var", "heç fərq yox", "həmişə cəm olur", "hallanmır"], correctIndex: 0, xp: 15, skills: ["az.pos.verb_nonfinite","az.pos.adjective","az.pos.verb"] },
            { id: "az7-tesrif-l2-b5", type: "fill_blank", prompt: "'sön' feilindən -müş ilə feili sifət düzəlt.", accepted: ["sönmüş"], xp: 15, skills: ["az.pos.verb_nonfinite","az.pos.adjective","az.pos.verb"] },
          ],
        },
        {
          id: "az7-tesrif-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az7-tesrif-l3",
          title: "Feili bağlama",
          intro: "Həm feilə, həm zərfə aid xüsusiyyət daşıyan, işin tərzini/zamanını bildirən forma.",
          sections: [
            { heading: "Feili bağlama nədir?", body: "Feildən əmələ gəlib, əsas feilə bağlanan və işin tərzini, zamanını bildirən formadır. Şəkilçiləri: -ıb⁴, -araq²/-ərək, -anda²/-əndə, -dıqca⁴, -madan²/-mədən. Məs.: gülərək danışdı, gələndə gördü." },
            { heading: "Zərfə oxşarlığı", body: "Feili bağlama əsas feilin necə, nə vaxt icra olunduğunu göstərir: 'Qaçaraq gəldi' (necə gəldi? — qaçaraq)." },
          ],
          tasks: [
            { id: "az7-tesrif-l3-t1", type: "multiple_choice", prompt: "Aşağıdakılardan hansı feili bağlamadır?", options: ["gülərək", "gülən", "gülmək", "güldü"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
            { id: "az7-tesrif-l3-t2", type: "multiple_choice", prompt: "Feili bağlama nəyi bildirir?", options: ["işin tərzini/zamanını", "əşyanın əlamətini", "işin adını", "sayı"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
            { id: "az7-tesrif-l3-t3", type: "multiple_choice", prompt: "Feili bağlama şəkilçilərindən biri hansıdır?", options: ["-araq/-ərək", "-an/-ən", "-maq/-mək", "-lı/-li"], correctIndex: 0, xp: 10, skills: ["az.morph.root","az.pos.verb_nonfinite","az.pos.verb"] },
            { id: "az7-tesrif-l3-t4", type: "multiple_choice", prompt: "'Qaçaraq gəldi.' — feili bağlama hansıdır?", options: ["qaçaraq", "gəldi", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
            { id: "az7-tesrif-l3-t5", type: "fill_blank", prompt: "'gül' feilindən -ərək ilə feili bağlama düzəlt.", accepted: ["gülərək"], xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
            { id: "az7-tesrif-l3-t6", type: "fill_blank", prompt: "'qaç' feilindən -araq ilə feili bağlama düzəlt.", accepted: ["qaçaraq"], xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
            { id: "az7-tesrif-l3-t7", type: "multiple_choice", prompt: "'Gələndə məni gördü.' — feili bağlama hansıdır?", options: ["gələndə", "gördü", "məni", "heç biri"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
            { id: "az7-tesrif-l3-t8", type: "multiple_choice", prompt: "Feili bağlama hansı iki nitq hissəsinin xüsusiyyətini daşıyır?", options: ["feil və zərf", "feil və sifət", "feil və isim", "sifət və zərf"], correctIndex: 0, xp: 10, skills: ["az.phon.letters","az.pos.verb_nonfinite","az.pos.verb"] },
            { id: "az7-tesrif-l3-t9", type: "multiple_choice", prompt: "Aşağıdakılardan hansı feili bağlama DEYİL?", options: ["oxuyan", "oxuyaraq", "oxuyub", "oxuyanda"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
            { id: "az7-tesrif-l3-t10", type: "fill_blank", prompt: "'gəl' feilindən -ib/-ıb ilə feili bağlama düzəlt.", accepted: ["gəlib"], xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
            { id: "az7-tesrif-l3-t11", type: "multiple_choice", prompt: "'Kitabı oxuyub qutuya qoydu.' — feili bağlama hansıdır?", options: ["oxuyub", "qoydu", "kitabı", "qutuya"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
            { id: "az7-tesrif-l3-t12", type: "multiple_choice", prompt: "Feili bağlama əsas feilin nəyini göstərir?", options: ["necə/nə vaxt icra olunduğunu", "əşyasını", "sayını", "yerini yalnız"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
            { id: "az7-tesrif-l3-t13", type: "fill_blank", prompt: "'baxma' formasından -dan ilə feili bağlama: 'ona ___ keçdi' (baxmadan).", accepted: ["baxmadan"], xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
            { id: "az7-tesrif-l3-t14", type: "multiple_choice", prompt: "'Sən gələndə mən yatmışdım.' — feili bağlama hansıdır?", options: ["gələndə", "yatmışdım", "sən", "mən"], correctIndex: 0, xp: 10, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
            { id: "az7-tesrif-l3-t15", type: "multiple_choice", prompt: "Təsriflənməyən feillərin üç növü hansıdır?", options: ["məsdər, feili sifət, feili bağlama", "keçmiş, indiki, gələcək", "məlum, məchul, icbar", "sadə, düzəltmə, mürəkkəb"], correctIndex: 0, xp: 15, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
          ],
          bonusTasks: [
            { id: "az7-tesrif-l3-b1", type: "multiple_choice", prompt: "'Uşaq sevinərək atıldı.' cümləsində feili bağlama?", options: ["sevinərək", "atıldı", "uşaq", "yoxdur"], correctIndex: 0, xp: 15, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
            { id: "az7-tesrif-l3-b2", type: "fill_blank", prompt: "'oxu' feilindən -yaraq ilə feili bağlama düzəlt.", accepted: ["oxuyaraq"], xp: 15, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
            { id: "az7-tesrif-l3-b3", type: "multiple_choice", prompt: "Hansı sırada yalnız feili bağlamalar var?", options: ["gülərək, gəlib, gələndə", "gülən, gələn", "gülmək, gəlmək", "güldü, gəldi"], correctIndex: 0, xp: 15, skills: ["az.pos.verb_nonfinite","az.pos.verb"] },
            { id: "az7-tesrif-l3-b4", type: "multiple_choice", prompt: "Feili sifət isimdən əvvəl, feili bağlama isə əsasən nədən əvvəl/yanında gəlir?", options: ["feildən (əsas feilə bağlanır)", "isimdən", "saydan", "qoşmadan"], correctIndex: 0, xp: 15, skills: ["az.pos.verb_nonfinite","az.pos.adjective","az.pos.noun","az.pos.verb"] },
            { id: "az7-tesrif-l3-b5", type: "fill_blank", prompt: "'de' feilindən -yərək/-yib formasına: 'salam ___ girdi' (deyib).", accepted: ["deyib"], xp: 15, skills: ["az.pos.verb","az.text.etiquette"] },
          ],
        },
        {
          id: "az7-tesrif-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        }
      ],
    },
    // ═══════════════ 4. Zərf ═══════════════
    {
      id: "az7-zerf",
      title: "Zərf",
      description:
        "İşin tərzini, zamanını, yerini, kəmiyyətini bildirən nitq hissəsi; zərfin məna və quruluşca növləri.",
      lessons: [
        {
          id: "az7-zerf-l1",
          title: "Zərf və onun məna növləri (I)",
          intro: "Zərf işin əlamətini bildirir. Tərz, zaman və yer zərfləri.",
          sections: [
            { heading: "Zərf nədir?", body: "İşin (hərəkətin) tərzini, zamanını, yerini, kəmiyyətini bildirən nitq hissəsinə zərf deyilir. Əsasən feili izah edir: sürətlə qaçdı, dünən gəldi." },
            { heading: "Tərz, zaman, yer zərfləri", body: "Tərz zərfi 'necə?': tez, yavaş, gözəl, birlikdə. Zaman zərfi 'nə vaxt?': dünən, bu gün, həmişə, indi. Yer zərfi 'harada/haraya?': irəli, geri, yuxarı, uzaqda." },
          ],
          tasks: [
            { id: "az7-zerf-l1-t1", type: "multiple_choice", prompt: "Zərf nəyi bildirir?", options: ["işin əlamətini (tərz, zaman, yer...)", "əşyanı", "əşyanın əlamətini", "sayı"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l1-t2", type: "multiple_choice", prompt: "'dünən' hansı zərf növüdür?", options: ["zaman zərfi", "tərz zərfi", "yer zərfi", "kəmiyyət zərfi"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l1-t3", type: "multiple_choice", prompt: "'sürətlə' hansı zərf növüdür?", options: ["tərz zərfi", "zaman zərfi", "yer zərfi", "kəmiyyət zərfi"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l1-t4", type: "multiple_choice", prompt: "'irəli' hansı zərf növüdür?", options: ["yer zərfi", "zaman zərfi", "tərz zərfi", "kəmiyyət zərfi"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l1-t5", type: "multiple_choice", prompt: "Tərz zərfi hansı suala cavab verir?", options: ["necə?", "nə vaxt?", "harada?", "nə qədər?"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l1-t6", type: "multiple_choice", prompt: "Zaman zərfi hansı suala cavab verir?", options: ["nə vaxt?", "necə?", "harada?", "nə qədər?"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb","az.pos.verb_tense"] },
            { id: "az7-zerf-l1-t7", type: "multiple_choice", prompt: "Yer zərfi hansı suala cavab verir?", options: ["harada? haraya?", "necə?", "nə vaxt?", "nə qədər?"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l1-t8", type: "multiple_choice", prompt: "'həmişə' hansı zərf növüdür?", options: ["zaman zərfi", "tərz zərfi", "yer zərfi", "kəmiyyət zərfi"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l1-t9", type: "multiple_choice", prompt: "'yavaş' hansı zərf növüdür?", options: ["tərz zərfi", "zaman zərfi", "yer zərfi", "kəmiyyət zərfi"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l1-t10", type: "multiple_choice", prompt: "Zərf əsasən hansı nitq hissəsini izah edir?", options: ["feili", "ismi", "sayı", "qoşmanı"], correctIndex: 0, xp: 10, skills: ["az.phon.letters","az.pos.adverb"] },
            { id: "az7-zerf-l1-t11", type: "multiple_choice", prompt: "'yuxarı' hansı zərf növüdür?", options: ["yer zərfi", "zaman zərfi", "tərz zərfi", "kəmiyyət zərfi"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l1-t12", type: "multiple_choice", prompt: "'Uşaq gözəl oxudu.' cümləsində zərf hansıdır?", options: ["gözəl", "uşaq", "oxudu", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l1-t13", type: "multiple_choice", prompt: "'indi' hansı zərf növüdür?", options: ["zaman zərfi", "yer zərfi", "tərz zərfi", "kəmiyyət zərfi"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l1-t14", type: "multiple_choice", prompt: "'Biz uzaqda yaşayırıq.' cümləsində zərf hansıdır?", options: ["uzaqda", "biz", "yaşayırıq", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l1-t15", type: "multiple_choice", prompt: "'birlikdə' hansı zərf növüdür?", options: ["tərz zərfi", "zaman zərfi", "yer zərfi", "kəmiyyət zərfi"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb"] },
          ],
          bonusTasks: [
            { id: "az7-zerf-l1-b1", type: "multiple_choice", prompt: "'Sabah imtahan verəcəyəm.' cümləsində zaman zərfi?", options: ["sabah", "imtahan", "verəcəyəm", "yoxdur"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l1-b2", type: "multiple_choice", prompt: "Hansı sırada yalnız tərz zərfləri var?", options: ["tez, yavaş, gözəl", "dünən, bu gün, indi", "irəli, geri, yuxarı", "çox, az, bir qədər"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l1-b3", type: "multiple_choice", prompt: "Zərflə sifətin fərqi nədir?", options: ["zərf feili, sifət ismi izah edir", "heç fərq yox", "zərf hallanır", "sifət feili izah edir"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb","az.pos.adjective"] },
            { id: "az7-zerf-l1-b4", type: "multiple_choice", prompt: "'aşağı' sözü cümlədə yer zərfi ola bilər?", options: ["bəli", "xeyr", "yalnız isim", "yalnız sifət"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l1-b5", type: "multiple_choice", prompt: "'Səhər tezdən durdu.' cümləsində neçə zərf var (səhər/tezdən)?", options: ["iki", "bir", "heç", "üç"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb"] },
          ],
        },
        {
          id: "az7-zerf-l2",
          title: "Zərfin məna növləri (II)",
          intro: "Kəmiyyət zərfi və səbəb-məqsəd zərfi.",
          sections: [
            { heading: "Kəmiyyət zərfi", body: "İşin miqdarını, dərəcəsini bildirir, 'nə qədər?', 'neçə dəfə?' suallarına cavab verir: çox, az, bir qədər, tamamilə, ikiqat." },
            { heading: "Səbəb-məqsəd zərfi", body: "İşin səbəbini və ya məqsədini bildirir, 'niyə?', 'nə üçün?', 'nə məqsədlə?' suallarına cavab verir: qəsdən, əbəs, nahaq, məcburən." },
          ],
          tasks: [
            { id: "az7-zerf-l2-t1", type: "multiple_choice", prompt: "'çox' hansı zərf növüdür?", options: ["kəmiyyət zərfi", "tərz zərfi", "zaman zərfi", "yer zərfi"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l2-t2", type: "multiple_choice", prompt: "Kəmiyyət zərfi hansı suala cavab verir?", options: ["nə qədər? neçə dəfə?", "necə?", "nə vaxt?", "harada?"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l2-t3", type: "multiple_choice", prompt: "'qəsdən' hansı zərf növüdür?", options: ["səbəb-məqsəd zərfi", "kəmiyyət zərfi", "tərz zərfi", "yer zərfi"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l2-t4", type: "multiple_choice", prompt: "Səbəb-məqsəd zərfi hansı suala cavab verir?", options: ["niyə? nə üçün?", "necə?", "nə vaxt?", "nə qədər?"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l2-t5", type: "multiple_choice", prompt: "'az' hansı zərf növüdür?", options: ["kəmiyyət zərfi", "tərz zərfi", "zaman zərfi", "səbəb-məqsəd"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l2-t6", type: "multiple_choice", prompt: "'nahaq' hansı zərf növüdür?", options: ["səbəb-məqsəd zərfi", "kəmiyyət zərfi", "tərz zərfi", "yer zərfi"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l2-t7", type: "multiple_choice", prompt: "'Çox oxudu.' cümləsində kəmiyyət zərfi?", options: ["çox", "oxudu", "hər ikisi", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l2-t8", type: "multiple_choice", prompt: "'bir qədər' hansı zərf növüdür?", options: ["kəmiyyət zərfi", "tərz zərfi", "zaman zərfi", "yer zərfi"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l2-t9", type: "multiple_choice", prompt: "'məcburən' hansı zərf növüdür?", options: ["səbəb-məqsəd zərfi", "kəmiyyət zərfi", "tərz zərfi", "yer zərfi"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l2-t10", type: "multiple_choice", prompt: "'tamamilə' hansı zərf növüdür?", options: ["kəmiyyət zərfi", "səbəb-məqsəd", "yer zərfi", "zaman zərfi"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l2-t11", type: "multiple_choice", prompt: "'Qəsdən gecikdi.' cümləsində zərf hansı növdür?", options: ["səbəb-məqsəd", "kəmiyyət", "tərz", "yer"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l2-t12", type: "multiple_choice", prompt: "'ikiqat' hansı zərf növüdür?", options: ["kəmiyyət zərfi", "tərz zərfi", "zaman zərfi", "yer zərfi"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l2-t13", type: "multiple_choice", prompt: "Zərfin neçə məna növü var (əsas)?", options: ["beş", "üç", "iki", "yeddi"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l2-t14", type: "multiple_choice", prompt: "'olduqca' hansı zərf növünə yaxındır?", options: ["kəmiyyət (dərəcə)", "yer", "zaman", "səbəb"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l2-t15", type: "multiple_choice", prompt: "Zərfin beş məna növü hansılardır?", options: ["tərz, zaman, yer, kəmiyyət, səbəb-məqsəd", "sadə, düzəltmə, mürəkkəb, alınma, əsl", "məlum, məchul, qayıdış, qarşılıq, icbar", "isim, sifət, say, feil, zərf"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb"] },
          ],
          bonusTasks: [
            { id: "az7-zerf-l2-b1", type: "multiple_choice", prompt: "'Dərsi tamamilə başa düşdüm.' cümləsində kəmiyyət zərfi?", options: ["tamamilə", "dərsi", "başa", "düşdüm"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l2-b2", type: "multiple_choice", prompt: "Hansı sırada yalnız kəmiyyət zərfləri var?", options: ["çox, az, bir qədər", "dünən, indi, sabah", "irəli, geri", "qəsdən, nahaq"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l2-b3", type: "multiple_choice", prompt: "'Nahaq gəldin.' cümləsində zərf hansı növdür?", options: ["səbəb-məqsəd", "kəmiyyət", "tərz", "yer"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l2-b4", type: "multiple_choice", prompt: "'çox gözəl' ifadəsində 'çox' nəyi izah edir?", options: ["dərəcəni (kəmiyyət zərfi)", "yeri", "zamanı", "səbəbi"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l2-b5", type: "multiple_choice", prompt: "'Bilə-bilə səhv etdi.' cümləsində zərf hansı növə yaxındır?", options: ["səbəb-məqsəd/tərz", "yer", "kəmiyyət", "zaman"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb"] },
          ],
        },
        {
          id: "az7-zerf-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az7-zerf-l3",
          title: "Zərfin quruluşca növləri",
          intro: "Zərflər quruluşca sadə, düzəltmə və mürəkkəb olur.",
          sections: [
            { heading: "Quruluşca növlər", body: "Sadə zərf: tez, çox, dünən. Düzəltmə zərf (şəkilçi ilə): gecə-lə-r, sürət-lə, insan-casına. Mürəkkəb zərf: gündən-günə, addım-addım, səhər-axşam." },
          ],
          tasks: [
            { id: "az7-zerf-l3-t1", type: "multiple_choice", prompt: "'tez' zərfi quruluşca necədir?", options: ["sadə", "düzəltmə", "mürəkkəb", "alınma"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l3-t2", type: "multiple_choice", prompt: "'sürətlə' zərfi quruluşca necədir?", options: ["düzəltmə", "sadə", "mürəkkəb", "alınma"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l3-t3", type: "multiple_choice", prompt: "'gündən-günə' zərfi quruluşca necədir?", options: ["mürəkkəb", "sadə", "düzəltmə", "alınma"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l3-t4", type: "multiple_choice", prompt: "Aşağıdakılardan hansı sadə zərfdir?", options: ["çox", "gecələr", "addım-addım", "insancasına"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l3-t5", type: "multiple_choice", prompt: "Aşağıdakılardan hansı düzəltmə zərfdir?", options: ["dostcasına", "tez", "səhər-axşam", "az"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation","az.pos.adverb"] },
            { id: "az7-zerf-l3-t6", type: "multiple_choice", prompt: "Aşağıdakılardan hansı mürəkkəb zərfdir?", options: ["səhər-axşam", "tez", "sürətlə", "çox"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l3-t7", type: "multiple_choice", prompt: "'addım-addım' zərfi necə əmələ gəlib?", options: ["sözün təkrarı ilə", "şəkilçi ilə", "yalnız kökdən", "qoşma ilə"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l3-t8", type: "multiple_choice", prompt: "'qəhrəmancasına' zərfi quruluşca necədir?", options: ["düzəltmə", "sadə", "mürəkkəb", "alınma"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l3-t9", type: "multiple_choice", prompt: "'dünən' zərfi quruluşca necədir?", options: ["sadə", "düzəltmə", "mürəkkəb", "alınma"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l3-t10", type: "multiple_choice", prompt: "'yavaş-yavaş' zərfi quruluşca necədir?", options: ["mürəkkəb", "sadə", "düzəltmə", "alınma"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l3-t11", type: "multiple_choice", prompt: "Düzəltmə zərf necə əmələ gəlir?", options: ["sözdüzəldici şəkilçi ilə", "sözün təkrarı ilə", "iki fərqli söz ilə", "qoşma ilə"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation","az.pos.adverb"] },
            { id: "az7-zerf-l3-t12", type: "multiple_choice", prompt: "'gecə-gündüz' zərfi quruluşca necədir?", options: ["mürəkkəb", "sadə", "düzəltmə", "alınma"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l3-t13", type: "multiple_choice", prompt: "'indi' zərfi quruluşca necədir?", options: ["sadə", "düzəltmə", "mürəkkəb", "alınma"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l3-t14", type: "multiple_choice", prompt: "'-casına/-cəsinə' şəkilçisi hansı quruluşca zərf düzəldir?", options: ["düzəltmə", "sadə", "mürəkkəb", "heç"], correctIndex: 0, xp: 10, skills: ["az.morph.root","az.pos.adverb"] },
            { id: "az7-zerf-l3-t15", type: "multiple_choice", prompt: "'uca-uca' zərfi quruluşca necədir?", options: ["mürəkkəb", "sadə", "düzəltmə", "alınma"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb"] },
          ],
          bonusTasks: [
            { id: "az7-zerf-l3-b1", type: "multiple_choice", prompt: "Hansı sırada yalnız mürəkkəb zərflər var?", options: ["addım-addım, səhər-axşam", "tez, çox", "sürətlə, gecələr", "dünən, indi"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l3-b2", type: "multiple_choice", prompt: "'dostcasına' zərfində hansı şəkilçi var?", options: ["-casına", "-lə", "-lar", "-dan"], correctIndex: 0, xp: 15, skills: ["az.morph.root","az.pos.adverb"] },
            { id: "az7-zerf-l3-b3", type: "multiple_choice", prompt: "Sözün təkrarı ilə əmələ gələn zərf hansı quruluşdadır?", options: ["mürəkkəb", "sadə", "düzəltmə", "alınma"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l3-b4", type: "multiple_choice", prompt: "'birdən-birə' zərfi quruluşca necədir?", options: ["mürəkkəb", "sadə", "düzəltmə", "alınma"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb"] },
            { id: "az7-zerf-l3-b5", type: "multiple_choice", prompt: "'gizlicə' zərfi quruluşca necədir?", options: ["düzəltmə", "sadə", "mürəkkəb", "alınma"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb"] },
          ],
        },
        {
          id: "az7-zerf-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        }
      ],
    },
    // ═══════════════ 5. Köməkçi nitq hissələri ═══════════════
    {
      id: "az7-komekci",
      title: "Köməkçi nitq hissələri",
      description:
        "Müstəqil məna daşımayan, sözləri və cümlələri bağlayan köməkçi nitq hissələri: qoşma, bağlayıcı, ədat.",
      lessons: [
        {
          id: "az7-komekci-l1",
          title: "Qoşma",
          intro: "Sözlərə qoşularaq onlar arasında məna əlaqəsi yaradan köməkçi nitq hissəsi.",
          sections: [
            { heading: "Qoşma nədir?", body: "İsim, əvəzlik və digər sözlərə qoşularaq müxtəlif məna çalarları yaradan köməkçi nitq hissəsinə qoşma deyilir: kimi, üçün, qədər, ilə, kimi, tək, sarı, görə, əvvəl, sonra." },
            { heading: "Nümunələr", body: "'Sənin üçün gəldim.' (məqsəd), 'Quş kimi uçur.' (bənzətmə), 'Axşama qədər işlədi.' (hədd), 'Dostu ilə getdi.' (birgəlik)." },
          ],
          tasks: [
            { id: "az7-komekci-l1-t1", type: "multiple_choice", prompt: "Aşağıdakılardan hansı qoşmadır?", options: ["üçün", "və", "amma", "kaş"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l1-t2", type: "multiple_choice", prompt: "Qoşma nə edir?", options: ["sözlər arasında məna əlaqəsi yaradır", "əşya bildirir", "iş bildirir", "əlamət bildirir"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l1-t3", type: "multiple_choice", prompt: "'Sənin üçün gəldim.' cümləsində qoşma hansıdır?", options: ["üçün", "sənin", "gəldim", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l1-t4", type: "multiple_choice", prompt: "'Quş kimi uçur.' cümləsində qoşma hansıdır?", options: ["kimi", "quş", "uçur", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l1-t5", type: "multiple_choice", prompt: "Aşağıdakılardan hansı qoşmadır?", options: ["qədər", "çünki", "də", "vay"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l1-t6", type: "multiple_choice", prompt: "'Axşama qədər işlədi.' — qoşma hansıdır?", options: ["qədər", "axşama", "işlədi", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l1-t7", type: "multiple_choice", prompt: "'ilə' qoşması hansı məna çaları verir?", options: ["birgəlik/vasitə", "məqsəd", "səbəb", "bənzətmə"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l1-t8", type: "multiple_choice", prompt: "'üçün' qoşması hansı məna verir?", options: ["məqsəd/səbəb", "bənzətmə", "hədd", "yer"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l1-t9", type: "multiple_choice", prompt: "Qoşma müstəqil məna daşıyırmı?", options: ["xeyr (köməkçidir)", "bəli", "yalnız cümlə əvvəlində", "yalnız feillə"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l1-t10", type: "multiple_choice", prompt: "'Dərsdən sonra gəzdik.' — qoşma hansıdır?", options: ["sonra", "dərsdən", "gəzdik", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l1-t11", type: "multiple_choice", prompt: "'görə' qoşması hansı məna verir?", options: ["səbəb", "bənzətmə", "birgəlik", "məqsəd"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l1-t12", type: "multiple_choice", prompt: "Aşağıdakılardan hansı qoşma DEYİL?", options: ["lakin", "üçün", "kimi", "qədər"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l1-t13", type: "multiple_choice", prompt: "'Aslan tək güclüdür.' — qoşma hansıdır?", options: ["tək", "aslan", "güclüdür", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l1-t14", type: "multiple_choice", prompt: "'əvvəl' sözü qoşma kimi işlənə bilər?", options: ["bəli (dərsdən əvvəl)", "xeyr", "yalnız isimdir", "yalnız feildir"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l1-t15", type: "multiple_choice", prompt: "Qoşma hansı nitq hissəsi qrupuna aiddir?", options: ["köməkçi nitq hissələri", "əsas nitq hissələri", "feillər", "adlar"], correctIndex: 0, xp: 15, skills: ["az.phon.letters","az.pos.auxiliary"] },
          ],
          bonusTasks: [
            { id: "az7-komekci-l1-b1", type: "multiple_choice", prompt: "'Xəstə olduğuna görə gəlmədi.' — qoşma və mənası?", options: ["görə — səbəb", "görə — məqsəd", "olduğuna — hədd", "gəlmədi — bənzətmə"], correctIndex: 0, xp: 15, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l1-b2", type: "multiple_choice", prompt: "Hansı sırada yalnız qoşmalar var?", options: ["üçün, kimi, qədər", "və, amma, çünki", "də, belə, məhz", "kaş, gərək"], correctIndex: 0, xp: 15, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l1-b3", type: "multiple_choice", prompt: "'Bulaq kimi saf.' — 'kimi' hansı məna verir?", options: ["bənzətmə", "səbəb", "məqsəd", "hədd"], correctIndex: 0, xp: 15, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l1-b4", type: "multiple_choice", prompt: "Qoşma cümlədə hansı sözlərə qoşulur əsasən?", options: ["isim və əvəzliyə", "yalnız feilə", "yalnız zərfə", "heç birinə"], correctIndex: 0, xp: 15, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l1-b5", type: "multiple_choice", prompt: "'Səhərə sarı yol gedirdik.' — qoşma hansıdır?", options: ["sarı", "səhərə", "yol", "gedirdik"], correctIndex: 0, xp: 15, skills: ["az.pos.auxiliary"] },
          ],
        },
        {
          id: "az7-komekci-l2",
          title: "Bağlayıcı",
          intro: "Cümlə üzvlərini və cümlələri bir-birinə bağlayan köməkçi nitq hissəsi.",
          sections: [
            { heading: "Bağlayıcı nədir?", body: "Həmcins üzvləri və ya cümlələri bir-birinə bağlayan köməkçi nitq hissəsinə bağlayıcı deyilir: və, ilə, həm, amma, lakin, ancaq, çünki, ona görə ki, ya, və ya, nə... nə." },
            { heading: "Növləri", body: "Tabesizlik bağlayıcıları (və, amma, lakin, ya) bərabərhüquqlu üzvləri/cümlələri; tabelilik bağlayıcıları (çünki, ki, əgər) baş və budaq cümləni bağlayır." },
          ],
          tasks: [
            { id: "az7-komekci-l2-t1", type: "multiple_choice", prompt: "Aşağıdakılardan hansı bağlayıcıdır?", options: ["amma", "üçün", "kimi", "kaş"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l2-t2", type: "multiple_choice", prompt: "Bağlayıcı nə edir?", options: ["üzvləri/cümlələri bağlayır", "əşya bildirir", "əlamət bildirir", "iş bildirir"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l2-t3", type: "multiple_choice", prompt: "'Ali və Vəli gəldi.' — bağlayıcı hansıdır?", options: ["və", "Ali", "Vəli", "gəldi"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l2-t4", type: "multiple_choice", prompt: "'Getmək istədim, amma gecikdim.' — bağlayıcı hansıdır?", options: ["amma", "getmək", "gecikdim", "istədim"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l2-t5", type: "multiple_choice", prompt: "'və', 'amma' hansı bağlayıcı növüdür?", options: ["tabesizlik bağlayıcıları", "tabelilik bağlayıcıları", "qoşma", "ədat"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l2-t6", type: "multiple_choice", prompt: "'çünki' hansı bağlayıcı növüdür?", options: ["tabelilik bağlayıcısı", "tabesizlik bağlayıcısı", "qoşma", "ədat"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l2-t7", type: "multiple_choice", prompt: "'Gəlmədi, çünki xəstə idi.' — bağlayıcı hansıdır?", options: ["çünki", "gəlmədi", "xəstə", "idi"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l2-t8", type: "multiple_choice", prompt: "Aşağıdakılardan hansı bağlayıcı DEYİL?", options: ["qədər", "lakin", "ancaq", "həm"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l2-t9", type: "multiple_choice", prompt: "'ya... ya' hansı köməkçi nitq hissəsidir?", options: ["bağlayıcı", "qoşma", "ədat", "modal söz"], correctIndex: 0, xp: 10, skills: ["az.phon.letters"] },
            { id: "az7-komekci-l2-t10", type: "multiple_choice", prompt: "'Həm oxudu, həm işlədi.' — bağlayıcı hansıdır?", options: ["həm", "oxudu", "işlədi", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l2-t11", type: "multiple_choice", prompt: "Tabesizlik bağlayıcısı nəyi bağlayır?", options: ["bərabərhüquqlu üzvləri/cümlələri", "yalnız budaq cümləni", "yalnız qoşmanı", "yalnız zərfi"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l2-t12", type: "multiple_choice", prompt: "'lakin' bağlayıcısı hansı məna verir?", options: ["qarşılaşdırma/ziddiyyət", "səbəb", "birləşdirmə", "şərt"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l2-t13", type: "multiple_choice", prompt: "'əgər' hansı bağlayıcı növüdür?", options: ["tabelilik (şərt)", "tabesizlik", "qoşma", "ədat"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l2-t14", type: "multiple_choice", prompt: "Aşağıdakılardan hansı tabesizlik bağlayıcısıdır?", options: ["ancaq", "çünki", "ki", "əgər"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l2-t15", type: "multiple_choice", prompt: "Bağlayıcı ilə qoşmanın fərqi nədir?", options: ["bağlayıcı bağlayır, qoşma söz sonuna qoşulub məna verir", "heç fərq yox", "qoşma cümlə bağlayır", "bağlayıcı əşya bildirir"], correctIndex: 0, xp: 15, skills: ["az.pos.auxiliary"] },
          ],
          bonusTasks: [
            { id: "az7-komekci-l2-b1", type: "multiple_choice", prompt: "Hansı sırada yalnız bağlayıcılar var?", options: ["və, amma, çünki", "üçün, kimi, qədər", "də, belə, məhz", "kaş, gərək"], correctIndex: 0, xp: 15, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l2-b2", type: "multiple_choice", prompt: "'Nə oxudu, nə də dinlədi.' — bağlayıcı hansıdır?", options: ["nə... nə də", "oxudu", "dinlədi", "yoxdur"], correctIndex: 0, xp: 15, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l2-b3", type: "multiple_choice", prompt: "'ona görə ki' hansı bağlayıcı növüdür?", options: ["tabelilik (səbəb)", "tabesizlik", "qoşma", "ədat"], correctIndex: 0, xp: 15, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l2-b4", type: "multiple_choice", prompt: "'İşlədim, ona görə də yoruldum.' — bağlayıcı ifadə?", options: ["ona görə də", "işlədim", "yoruldum", "yoxdur"], correctIndex: 0, xp: 15, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l2-b5", type: "multiple_choice", prompt: "Bağlayıcı cümlə üzvü olurmu?", options: ["xeyr (köməkçidir)", "bəli, mübtəda", "bəli, xəbər", "bəli, zərflik"], correctIndex: 0, xp: 15, skills: ["az.pos.auxiliary"] },
          ],
        },
        {
          id: "az7-komekci-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az7-komekci-l3",
          title: "Ədat",
          intro: "Sözün və ya cümlənin mənasını qüvvətləndirən, məhdudlaşdıran köməkçi nitq hissəsi.",
          sections: [
            { heading: "Ədat nədir?", body: "Sözə və ya cümləyə müxtəlif məna çaları (qüvvətləndirmə, məhdudlaşdırma, sual, təsdiq, inkar) verən köməkçi nitq hissəsinə ədat deyilir: də/da, belə, hətta, ancaq, yalnız, təkcə, məgər, ki, axı, məhz." },
            { heading: "Nümunələr", body: "'Mən də gəldim.' (qüvvətləndirmə), 'Yalnız sən bilirsən.' (məhdudlaşdırma), 'Məgər bilmirsən?' (sual), 'Hətta o da razılaşdı.' (qüvvətləndirmə)." },
          ],
          tasks: [
            { id: "az7-komekci-l3-t1", type: "multiple_choice", prompt: "Aşağıdakılardan hansı ədatdır?", options: ["yalnız", "üçün", "və", "kimi"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l3-t2", type: "multiple_choice", prompt: "Ədat nə edir?", options: ["mənanı qüvvətləndirir/məhdudlaşdırır", "cümlələri bağlayır", "əşya bildirir", "iş bildirir"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l3-t3", type: "multiple_choice", prompt: "'Mən də gəldim.' — ədat hansıdır?", options: ["də", "mən", "gəldim", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l3-t4", type: "multiple_choice", prompt: "'Yalnız sən bilirsən.' — ədat hansıdır?", options: ["yalnız", "sən", "bilirsən", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l3-t5", type: "multiple_choice", prompt: "'Məgər bilmirsən?' — ədat hansıdır?", options: ["məgər", "bilmirsən", "sən", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l3-t6", type: "multiple_choice", prompt: "'də/da' ədatı hansı məna verir?", options: ["qüvvətləndirmə", "sual", "inkar", "məhdudlaşdırma"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l3-t7", type: "multiple_choice", prompt: "'yalnız', 'təkcə' ədatları hansı məna verir?", options: ["məhdudlaşdırma", "sual", "qüvvətləndirmə", "təsdiq"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l3-t8", type: "multiple_choice", prompt: "'Hətta o da razılaşdı.' — ədat hansıdır?", options: ["hətta", "o", "razılaşdı", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l3-t9", type: "multiple_choice", prompt: "'məgər' ədatı hansı məna verir?", options: ["sual", "təsdiq", "qüvvətləndirmə", "məhdudlaşdırma"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l3-t10", type: "multiple_choice", prompt: "Aşağıdakılardan hansı ədat DEYİL?", options: ["çünki", "belə", "hətta", "yalnız"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l3-t11", type: "multiple_choice", prompt: "'Belə söz olmaz.' — ədat hansıdır?", options: ["belə", "söz", "olmaz", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l3-t12", type: "multiple_choice", prompt: "Köməkçi nitq hissələri neçədir?", options: ["üç (qoşma, bağlayıcı, ədat)", "iki", "beş", "dörd"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l3-t13", type: "multiple_choice", prompt: "'axı' ədatı cümləyə hansı çalar verir?", options: ["izah/qüvvətləndirmə", "sual", "inkar", "məhdudlaşdırma"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l3-t14", type: "multiple_choice", prompt: "'məhz' ədatı hansı məna verir?", options: ["dəqiqləşdirmə/qüvvətləndirmə", "sual", "inkar", "şərt"], correctIndex: 0, xp: 10, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l3-t15", type: "multiple_choice", prompt: "Ədat müstəqil cümlə üzvü olurmu?", options: ["xeyr (köməkçidir)", "bəli, mübtəda", "bəli, xəbər", "bəli, tamamlıq"], correctIndex: 0, xp: 15, skills: ["az.pos.auxiliary"] },
          ],
          bonusTasks: [
            { id: "az7-komekci-l3-b1", type: "multiple_choice", prompt: "Hansı sırada yalnız ədatlar var?", options: ["yalnız, hətta, məgər", "və, amma, çünki", "üçün, kimi, qədər", "kaş, gərək, bəlkə"], correctIndex: 0, xp: 15, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l3-b2", type: "multiple_choice", prompt: "'Sən ki bunu bilirdin.' — 'ki' burada nədir?", options: ["ədat (qüvvətləndirmə)", "bağlayıcı", "qoşma", "modal söz"], correctIndex: 0, xp: 15, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l3-b3", type: "multiple_choice", prompt: "'də' ədatı ilə '-də' yerlik hal şəkilçisinin fərqi?", options: ["ədat ayrı yazılır, şəkilçi bitişik", "heç fərq yox", "ədat bitişik yazılır", "ikisi də şəkilçidir"], correctIndex: 0, xp: 15, skills: ["az.morph.root","az.pos.noun_case","az.pos.auxiliary"] },
            { id: "az7-komekci-l3-b4", type: "multiple_choice", prompt: "'Təkcə o gəldi.' cümləsində ədatın mənası?", options: ["məhdudlaşdırma", "qüvvətləndirmə", "sual", "təsdiq"], correctIndex: 0, xp: 15, skills: ["az.pos.auxiliary"] },
            { id: "az7-komekci-l3-b5", type: "multiple_choice", prompt: "Qoşma, bağlayıcı, ədat — bunların ortaq cəhəti nədir?", options: ["hamısı köməkçi nitq hissəsidir", "hamısı əşya bildirir", "hamısı hallanır", "hamısı feildir"], correctIndex: 0, xp: 15, skills: ["az.pos.auxiliary"] },
          ],
        },
        {
          id: "az7-komekci-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        }
      ],
    },
    // ═══════════════ 6. Modal sözlər, nida və söz birləşmələri ═══════════════
    {
      id: "az7-modal",
      title: "Modal sözlər, nida və söz birləşmələri",
      description:
        "Danışanın münasibətini bildirən modal sözlər, hiss-həyəcan bildirən nidalar və söz birləşmələri.",
      lessons: [
        {
          id: "az7-modal-l1",
          title: "Modal sözlər",
          intro: "Danışanın söylədiyi fikrə münasibətini bildirən sözlər.",
          sections: [
            { heading: "Modal söz nədir?", body: "Danışanın öz fikrinə münasibətini (əminlik, şübhə, arzu, təəssüf) bildirən sözlərə modal sözlər deyilir: əlbəttə, şübhəsiz, doğrudan, bəlkə, gərək, kaş, təəssüf ki, deməli, məncə." },
            { heading: "Xüsusiyyəti", body: "Modal sözlər cümlə üzvü olmur, çox vaxt vergüllə ayrılır: 'Əlbəttə, gələcəyəm.', 'Bəlkə, sabah görüşərik.'" },
          ],
          tasks: [
            { id: "az7-modal-l1-t1", type: "multiple_choice", prompt: "Aşağıdakılardan hansı modal sözdür?", options: ["əlbəttə", "və", "üçün", "vay"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l1-t2", type: "multiple_choice", prompt: "Modal söz nə bildirir?", options: ["danışanın fikrə münasibətini", "hiss-həyəcan", "əşya", "iş"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l1-t3", type: "multiple_choice", prompt: "'Əlbəttə, gələcəyəm.' — modal söz hansıdır?", options: ["əlbəttə", "gələcəyəm", "yoxdur", "hər ikisi"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l1-t4", type: "multiple_choice", prompt: "'bəlkə' modal sözü hansı münasibəti bildirir?", options: ["şübhə/ehtimal", "əminlik", "təəssüf", "hiss"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l1-t5", type: "multiple_choice", prompt: "'şübhəsiz' modal sözü hansı münasibəti bildirir?", options: ["əminlik", "şübhə", "təəssüf", "arzu"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l1-t6", type: "multiple_choice", prompt: "'kaş' modal sözü hansı münasibəti bildirir?", options: ["arzu", "əminlik", "şübhə", "sual"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l1-t7", type: "multiple_choice", prompt: "Modal söz cümlə üzvü olurmu?", options: ["xeyr", "bəli, mübtəda", "bəli, xəbər", "bəli, tamamlıq"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l1-t8", type: "multiple_choice", prompt: "'təəssüf ki' hansı münasibəti bildirir?", options: ["təəssüf/heyfslənmə", "əminlik", "arzu", "sevinc"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l1-t9", type: "multiple_choice", prompt: "'Məncə, bu doğrudur.' — modal söz hansıdır?", options: ["məncə", "bu", "doğrudur", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l1-t10", type: "multiple_choice", prompt: "Modal söz cümlədə çox vaxt necə ayrılır?", options: ["vergüllə", "nöqtə ilə", "sual işarəsi ilə", "heç cür"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l1-t11", type: "multiple_choice", prompt: "Aşağıdakılardan hansı modal söz DEYİL?", options: ["amma", "əlbəttə", "bəlkə", "gərək"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l1-t12", type: "multiple_choice", prompt: "'gərək' modal sözü hansı məna verir?", options: ["lazımlıq/zərurət", "sevinc", "sual", "təəssüf"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l1-t13", type: "multiple_choice", prompt: "'deməli' modal sözü hansı funksiyanı daşıyır?", options: ["nəticə/ümumiləşdirmə", "sual", "hiss", "əşya"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l1-t14", type: "multiple_choice", prompt: "'doğrudan' modal sözü hansı münasibəti bildirir?", options: ["təsdiq/əminlik", "şübhə", "arzu", "təəssüf"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l1-t15", type: "multiple_choice", prompt: "'Bəlkə, sabah yağış yağar.' cümləsində modal söz hansı çalar verir?", options: ["ehtimal", "əminlik", "arzu", "təəssüf"], correctIndex: 0, xp: 15, skills: ["az.pos.modal"] },
          ],
          bonusTasks: [
            { id: "az7-modal-l1-b1", type: "multiple_choice", prompt: "Hansı sırada yalnız modal sözlər var?", options: ["əlbəttə, bəlkə, gərək", "və, amma, çünki", "üçün, kimi, qədər", "vay, ah, of"], correctIndex: 0, xp: 15, skills: ["az.pos.modal"] },
            { id: "az7-modal-l1-b2", type: "multiple_choice", prompt: "Modal sözlə ədatın fərqi nədir?", options: ["modal söz danışanın münasibətini bildirir", "heç fərq yox", "ədat vergüllə ayrılır", "modal söz bağlayır"], correctIndex: 0, xp: 15, skills: ["az.pos.auxiliary","az.pos.modal"] },
            { id: "az7-modal-l1-b3", type: "multiple_choice", prompt: "'Yəqin ki, o da bilir.' — modal söz hansı çalar verir?", options: ["ehtimal/güman", "əminlik tam", "təəssüf", "arzu"], correctIndex: 0, xp: 15, skills: ["az.pos.modal"] },
            { id: "az7-modal-l1-b4", type: "multiple_choice", prompt: "'Kaş imtahandan keçəydim!' — modal söz hansı çalar verir?", options: ["arzu", "əminlik", "şübhə", "nəticə"], correctIndex: 0, xp: 15, skills: ["az.pos.modal"] },
            { id: "az7-modal-l1-b5", type: "multiple_choice", prompt: "'Görünür, yağış yağacaq.' — modal söz hansıdır?", options: ["görünür", "yağış", "yağacaq", "yoxdur"], correctIndex: 0, xp: 15, skills: ["az.pos.modal"] },
          ],
        },
        {
          id: "az7-modal-l2",
          title: "Nida",
          intro: "Hiss-həyəcanı, müxtəlif duyğuları bildirən köməkçi nitq hissəsi.",
          sections: [
            { heading: "Nida nədir?", body: "Sevinc, kədər, təəccüb, qorxu kimi hiss və həyəcanı bildirən sözlərə nida deyilir: ah, oh, vay, ay, of, əh, aman, oho, afərin, ura." },
            { heading: "Xüsusiyyəti", body: "Nida cümlə üzvü olmur, əksər hallarda nida işarəsi (!) və ya vergüllə ayrılır: 'Vay, nə gözəldir!', 'Afərin, uşaqlar!'" },
          ],
          tasks: [
            { id: "az7-modal-l2-t1", type: "multiple_choice", prompt: "Aşağıdakılardan hansı nidadır?", options: ["vay", "və", "üçün", "əlbəttə"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l2-t2", type: "multiple_choice", prompt: "Nida nə bildirir?", options: ["hiss-həyəcanı", "əşya", "iş", "danışanın münasibətini"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l2-t3", type: "multiple_choice", prompt: "'Vay, nə gözəldir!' — nida hansıdır?", options: ["vay", "gözəldir", "nə", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l2-t4", type: "multiple_choice", prompt: "'Afərin, uşaqlar!' — nida hansıdır?", options: ["afərin", "uşaqlar", "yoxdur", "hər ikisi"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l2-t5", type: "multiple_choice", prompt: "Nida cümlə üzvü olurmu?", options: ["xeyr", "bəli, mübtəda", "bəli, xəbər", "bəli, zərflik"], correctIndex: 0, xp: 10, skills: ["az.syn.sentence_type"] },
            { id: "az7-modal-l2-t6", type: "multiple_choice", prompt: "Nida çox vaxt hansı durğu işarəsi ilə ayrılır?", options: ["nida işarəsi (!) və ya vergül", "nöqtə", "sual işarəsi", "iki nöqtə"], correctIndex: 0, xp: 10, skills: ["az.pos.modal","az.orth.punctuation"] },
            { id: "az7-modal-l2-t7", type: "multiple_choice", prompt: "'Oho, nə böyükdür!' — nida hansıdır?", options: ["oho", "böyükdür", "nə", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l2-t8", type: "multiple_choice", prompt: "Aşağıdakılardan hansı nida DEYİL?", options: ["gərək", "ah", "of", "vay"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l2-t9", type: "multiple_choice", prompt: "'Ah' nidası hansı hissi bildirə bilər?", options: ["kədər/təəssüf", "yalnız sevinc", "yalnız qorxu", "heç bir hiss"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l2-t10", type: "multiple_choice", prompt: "'Ura! Biz qalib gəldik!' — nida hansıdır?", options: ["ura", "qalib", "gəldik", "biz"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l2-t11", type: "multiple_choice", prompt: "'aman' nidası hansı hissi bildirə bilər?", options: ["qorxu/yalvarış", "sevinc", "təəccüb", "razılıq"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l2-t12", type: "multiple_choice", prompt: "Nida hansı nitq hissəsi qrupuna aiddir?", options: ["köməkçi nitq hissələri", "əsas nitq hissələri", "feillər", "adlar"], correctIndex: 0, xp: 10, skills: ["az.phon.letters","az.pos.modal"] },
            { id: "az7-modal-l2-t13", type: "multiple_choice", prompt: "'Of, çox yoruldum!' — nida hansıdır?", options: ["of", "yoruldum", "çox", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l2-t14", type: "multiple_choice", prompt: "Nida ilə modal sözün fərqi nədir?", options: ["nida hiss, modal söz münasibət bildirir", "heç fərq yox", "nida cümlə üzvüdür", "modal söz hiss bildirir"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l2-t15", type: "multiple_choice", prompt: "'Ay aman, gecikdim!' cümləsində nida neçə sözdür?", options: ["ay aman (iki)", "bir", "heç", "üç"], correctIndex: 0, xp: 15, skills: ["az.pos.modal"] },
          ],
          bonusTasks: [
            { id: "az7-modal-l2-b1", type: "multiple_choice", prompt: "Hansı sırada yalnız nidalar var?", options: ["ah, oh, vay", "əlbəttə, bəlkə", "və, amma", "üçün, kimi"], correctIndex: 0, xp: 15, skills: ["az.pos.modal"] },
            { id: "az7-modal-l2-b2", type: "multiple_choice", prompt: "'Afərin!' nidası hansı hissi bildirir?", options: ["bəyənmə/təqdir", "kədər", "qorxu", "təəssüf"], correctIndex: 0, xp: 15, skills: ["az.pos.modal"] },
            { id: "az7-modal-l2-b3", type: "multiple_choice", prompt: "Nida ilə başlayan cümlədə nidadan sonra hansı işarə qoyula bilər?", options: ["vergül və ya nida işarəsi", "yalnız nöqtə", "iki nöqtə", "heç bir"], correctIndex: 0, xp: 15, skills: ["az.pos.modal"] },
            { id: "az7-modal-l2-b4", type: "multiple_choice", prompt: "'Eh, keçən günlər!' — nida hansı çalar verir?", options: ["həsrət/təəssüf", "sevinc", "təəccüb", "razılıq"], correctIndex: 0, xp: 15, skills: ["az.pos.modal"] },
            { id: "az7-modal-l2-b5", type: "multiple_choice", prompt: "Nida sözlərinin əsas funksiyası nədir?", options: ["hiss və həyəcanı ifadə etmək", "əşya adlandırmaq", "iş bildirmək", "cümlələri bağlamaq"], correctIndex: 0, xp: 15, skills: ["az.pos.modal"] },
          ],
        },
        {
          id: "az7-modal-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az7-modal-l3",
          title: "Söz birləşmələri",
          intro: "İki və daha çox müstəqil sözün məna və qrammatik cəhətdən birləşməsi.",
          sections: [
            { heading: "Söz birləşməsi nədir?", body: "Bir-biri ilə məna və qrammatik cəhətdən bağlanan iki və daha çox müstəqil sözün birləşməsinə söz birləşməsi deyilir: gözəl mənzərə, dağın zirvəsi, kitab oxumaq." },
            { heading: "Növləri", body: "İsmi birləşmə (əsas söz isim: qırmızı gül, uşağın kitabı) və feili birləşmə (əsas söz feil: tez getmək, məktub yazmaq)." },
          ],
          tasks: [
            { id: "az7-modal-l3-t1", type: "multiple_choice", prompt: "Söz birləşməsi ən azı neçə müstəqil sözdən ibarətdir?", options: ["iki", "bir", "üç", "dörd"], correctIndex: 0, xp: 10, skills: ["az.syn.phrase"] },
            { id: "az7-modal-l3-t2", type: "multiple_choice", prompt: "'gözəl mənzərə' nədir?", options: ["söz birləşməsi", "cümlə", "tək söz", "qoşma"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l3-t3", type: "multiple_choice", prompt: "'qırmızı gül' birləşməsi hansı növdür?", options: ["ismi birləşmə", "feili birləşmə", "cümlə", "sadə söz"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l3-t4", type: "multiple_choice", prompt: "'kitab oxumaq' birləşməsi hansı növdür?", options: ["feili birləşmə", "ismi birləşmə", "cümlə", "sadə söz"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l3-t5", type: "multiple_choice", prompt: "İsmi birləşmədə əsas söz hansı nitq hissəsidir?", options: ["isim", "feil", "zərf", "qoşma"], correctIndex: 0, xp: 10, skills: ["az.phon.letters"] },
            { id: "az7-modal-l3-t6", type: "multiple_choice", prompt: "Feili birləşmədə əsas söz hansı nitq hissəsidir?", options: ["feil", "isim", "sifət", "say"], correctIndex: 0, xp: 10, skills: ["az.phon.letters","az.pos.verb"] },
            { id: "az7-modal-l3-t7", type: "multiple_choice", prompt: "'dağın zirvəsi' birləşməsi hansı növdür?", options: ["ismi birləşmə", "feili birləşmə", "cümlə", "sadə söz"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l3-t8", type: "multiple_choice", prompt: "'tez getmək' birləşməsi hansı növdür?", options: ["feili birləşmə", "ismi birləşmə", "cümlə", "sadə söz"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l3-t9", type: "multiple_choice", prompt: "Söz birləşməsi cümlədən nə ilə fərqlənir?", options: ["bitmiş fikir bildirmir", "sözlərdən ibarətdir", "məna daşıyır", "heç nə ilə"], correctIndex: 0, xp: 10, skills: ["az.syn.phrase"] },
            { id: "az7-modal-l3-t10", type: "multiple_choice", prompt: "Aşağıdakılardan hansı söz birləşməsidir?", options: ["uca dağ", "Uşaq oxuyur.", "vay", "və"], correctIndex: 0, xp: 10, skills: ["az.syn.phrase"] },
            { id: "az7-modal-l3-t11", type: "multiple_choice", prompt: "'məktub yazmaq' birləşməsində əsas söz hansıdır?", options: ["yazmaq", "məktub", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l3-t12", type: "multiple_choice", prompt: "'ağ kağız' birləşməsində asılı söz hansıdır?", options: ["ağ", "kağız", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az7-modal-l3-t13", type: "multiple_choice", prompt: "Aşağıdakılardan hansı söz birləşməsi DEYİL?", options: ["Quşlar uçur.", "yaşıl yarpaq", "isti çay", "böyük ev"], correctIndex: 0, xp: 10, skills: ["az.syn.phrase"] },
            { id: "az7-modal-l3-t14", type: "multiple_choice", prompt: "'kitab oxumaq' birləşməsində əsas söz feildir, ona görə...", options: ["feili birləşmədir", "ismi birləşmədir", "cümlədir", "sadə sözdür"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az7-modal-l3-t15", type: "multiple_choice", prompt: "Söz birləşməsinin cümlədən əsas fərqi nədir?", options: ["bitmiş fikir və xəbər ifadə etmir", "sözlərdən ibarətdir", "böyük hərflə başlayır", "vergül olur"], correctIndex: 0, xp: 15, skills: ["az.syn.phrase"] },
          ],
          bonusTasks: [
            { id: "az7-modal-l3-b1", type: "multiple_choice", prompt: "'yüksək dağların zirvəsi' — bu nədir?", options: ["söz birləşməsi", "sadə cümlə", "tək söz", "nida"], correctIndex: 0, xp: 15, skills: ["az.pos.modal"] },
            { id: "az7-modal-l3-b2", type: "multiple_choice", prompt: "Hansı sırada yalnız feili birləşmələr var?", options: ["tez getmək, məktub yazmaq", "qırmızı gül, uca dağ", "isti çay, ağ qar", "gözəl bağ, yaşıl ot"], correctIndex: 0, xp: 15, skills: ["az.pos.verb"] },
            { id: "az7-modal-l3-b3", type: "multiple_choice", prompt: "'dostumun kitabı' birləşməsi hansı növdür?", options: ["ismi birləşmə", "feili birləşmə", "cümlə", "nida"], correctIndex: 0, xp: 15, skills: ["az.pos.modal"] },
            { id: "az7-modal-l3-b4", type: "multiple_choice", prompt: "Söz birləşməsində sözlər arasında hansı əlaqə var?", options: ["məna və qrammatik", "yalnız səs", "heç bir", "yalnız durğu"], correctIndex: 0, xp: 15, skills: ["az.syn.phrase"] },
            { id: "az7-modal-l3-b5", type: "multiple_choice", prompt: "'sürətlə qaçmaq' birləşməsində əsas söz hansıdır?", options: ["qaçmaq", "sürətlə", "hər ikisi", "heç biri"], correctIndex: 0, xp: 15, skills: ["az.pos.modal"] },
          ],
        },
        {
          id: "az7-modal-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        }
      ],
    },
  ],
};
