// Azərbaycan dili — 3-cü sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Nitq səsləri və heca  2) Sözün quruluşu (kök və şəkilçi)  3) İsim
// 4) Sifət və say  5) Feil  6) Cümlə və mətn.
// 3-cü sinif üçün sadə. id prefiksi az3-*.

import type { Subject } from "../types";

export const azerbaijani3: Subject = {
  slug: "azerbaycan-dili-3",
  name: "Azərbaycan dili",
  grade: 3,
  icon: "A",
  color: "rose",
  units: [
    // ═══════════════ 1. Nitq səsləri və heca ═══════════════
    {
      id: "az3-fonetika",
      title: "Nitq səsləri və heca",
      description: "Sait və samitlərin təkrarı, heca və vurğu.",
      lessons: [
        {
          id: "az3-fonetika-l1",
          title: "Səslər, heca və vurğu",
          intro: "Saitlər, samitlər, heca bölgüsü və vurğu.",
          sections: [
            { heading: "Səslər", body: "9 sait (a, e, ə, ı, i, o, ö, u, ü) və 23 samit var. Cəmi 32 hərf." },
            { heading: "Heca və vurğu", body: "Sözdə neçə sait varsa, o qədər heca var. Vurğu sözün bir hecasının daha güclü deyilməsidir. Azərbaycan dilində vurğu adətən son hecaya düşür: kitáb, aná." },
          ],
          tasks: [
            { id: "az3-fonetika-l1-t1", type: "numeric", prompt: "Azərbaycan dilində neçə sait var?", answer: 9, xp: 10, explanation: "Saitlər: a, e, ə, ı, i, o, ö, u, ü — cəmi 9." },
            { id: "az3-fonetika-l1-t2", type: "numeric", prompt: "Azərbaycan dilində neçə samit var?", answer: 23, xp: 10, explanation: "Əlifbadakı 32 hərfin 9-u saitdir, qalanı samit: 32 − 9 = 23." },
            { id: "az3-fonetika-l1-t3", type: "numeric", prompt: "'kitab' sözündə neçə heca var? (ki-tab)", answer: 2, xp: 10, explanation: "«kitab» sözündə iki sait var (i, a), ona görə iki heca: ki-tab." },
            { id: "az3-fonetika-l1-t4", type: "numeric", prompt: "'məktəb' sözündə neçə heca var? (mək-təb)", answer: 2, xp: 10, explanation: "«məktəb» sözündə iki sait var (ə, ə), ona görə iki heca: mək-təb." },
            { id: "az3-fonetika-l1-t5", type: "numeric", prompt: "'kitabxana' sözündə neçə heca var? (ki-tab-xa-na)", answer: 4, xp: 10, explanation: "«kitabxana» sözündə dörd sait var (i, a, a, a), ona görə dörd heca." },
            { id: "az3-fonetika-l1-t6", type: "multiple_choice", prompt: "Aşağıdakılardan hansı saitdir?", options: ["ə", "k", "s", "t"], correctIndex: 0, xp: 10, explanation: "«ə» saitdir; t, k, s isə samitdir." },
            { id: "az3-fonetika-l1-t7", type: "multiple_choice", prompt: "Aşağıdakılardan hansı samitdir?", options: ["m", "a", "o", "ü"], correctIndex: 0, xp: 10, explanation: "«m» samitdir; o, ü, a isə saitdir." },
            { id: "az3-fonetika-l1-t8", type: "multiple_choice", prompt: "Sözdə heca sayını nə göstərir?", options: ["saitlərin sayı", "samitlərin sayı", "hərflərin sayı", "vurğu"], correctIndex: 0, xp: 10, explanation: "Hər hecanın mərkəzində bir sait durur, ona görə heca sayı saitlərin sayı qədərdir." },
            { id: "az3-fonetika-l1-t9", type: "multiple_choice", prompt: "Azərbaycan dilində vurğu adətən hansı hecaya düşür?", options: ["son hecaya", "birinci hecaya", "orta hecaya", "vurğu yoxdur"], correctIndex: 0, xp: 10, explanation: "Azərbaycan dilində vurğu adətən sözün son hecasına düşür: kitáb, uşáq, mərtəbə́." },
            { id: "az3-fonetika-l1-t10", type: "numeric", prompt: "'alma' sözündə neçə heca var?", answer: 2, xp: 10, explanation: "«alma» sözündə iki sait var (a, a), ona görə iki heca: al-ma." },
            { id: "az3-fonetika-l1-t11", type: "multiple_choice", prompt: "'a' saiti qalın, yoxsa incədir?", options: ["qalın", "incə", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«a» qalın saitlərdəndir: a, ı, o, u." },
            { id: "az3-fonetika-l1-t12", type: "multiple_choice", prompt: "'e' saiti qalın, yoxsa incədir?", options: ["incə", "qalın", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«e» incə saitlərdəndir: e, ə, i, ö, ü." },
            { id: "az3-fonetika-l1-t13", type: "numeric", prompt: "'su' sözündə neçə heca var?", answer: 1, xp: 10, explanation: "«su» sözündə tək bir sait var (u), ona görə 1 heca." },
            { id: "az3-fonetika-l1-t14", type: "numeric", prompt: "'balaca' sözündə neçə heca var? (ba-la-ca)", answer: 3, xp: 10, explanation: "«balaca» sözündə üç sait var (a, a, a), ona görə üç heca." },
            { id: "az3-fonetika-l1-t15", type: "numeric", prompt: "Cəmi neçə hərf var? (9 + 23)", answer: 32, xp: 15, explanation: "9 sait + 23 samit = 32 hərf." },
          ],
          bonusTasks: [
            { id: "az3-fonetika-l1-b1", type: "numeric", prompt: "'ayaqqabı' sözündə neçə heca var? (a-yaq-qa-bı)", answer: 4, xp: 15, explanation: "«ayaqqabı» sözündə dörd sait var (a, a, a, ı), ona görə dörd heca." },
            { id: "az3-fonetika-l1-b2", type: "multiple_choice", prompt: "Hansı sırada yalnız qalın saitlər var?", options: ["a, ı, o, u", "e, ə, i, ö", "a, e, i, o", "u, ü, ö, ı"], correctIndex: 0, xp: 15, explanation: "Qalın saitlərin tam siyahısı budur: a, ı, o, u." },
            { id: "az3-fonetika-l1-b3", type: "numeric", prompt: "'təbiət' sözündə neçə heca var? (tə-bi-ət)", answer: 3, xp: 15, explanation: "«təbiət» sözündə üç sait var (ə, i, ə), ona görə üç heca: tə-bi-ət." },
            { id: "az3-fonetika-l1-b4", type: "multiple_choice", prompt: "Hansı sırada yalnız incə saitlər var?", options: ["e, ə, i, ö, ü", "a, ı, o, u", "a, e, o, u", "i, o, u, a"], correctIndex: 0, xp: 15, explanation: "İncə saitlərin tam siyahısı budur: e, ə, i, ö, ü." },
            { id: "az3-fonetika-l1-b5", type: "numeric", prompt: "'gül' sözündə neçə heca var?", answer: 1, xp: 15, explanation: "«gül» sözündə tək bir sait var (ü), ona görə 1 heca." },
          ],
        },
        {
          id: "az3-fonetika-l2",
          title: "Sait ahəngi",
          intro: "Azərbaycan dilində saitlər bir-birinə uyğunlaşır.",
          sections: [
            { heading: "Qalın və incə", body: "Qalın saitlər: a, ı, o, u. İncə saitlər: e, ə, i, ö, ü. Bir sözdə adətən ya hamısı qalın, ya hamısı incə olur." },
            { heading: "Şəkilçi seçimi", body: "Söz qalın saitlə bitirsə şəkilçi də qalın olur: kitab-lar. İncə olsa incə: ev-lər." },
          ],
          tasks: [
            { id: "az3-fonetika-l2-t1", type: "multiple_choice", prompt: "Hansı sait QALINDIR?", options: ["a", "e", "i", "ə"], correctIndex: 0, xp: 10, explanation: "«a» qalın saitlərdəndir: a, ı, o, u. Digərləri (e, ə, i) incədir." },
            { id: "az3-fonetika-l2-t2", type: "multiple_choice", prompt: "Hansı sait İNCƏDİR?", options: ["ü", "ı", "o", "u"], correctIndex: 0, xp: 10, explanation: "«ü» incə saitlərdəndir: e, ə, i, ö, ü. Digərləri (u, o, ı) qalındır." },
            { id: "az3-fonetika-l2-t3", type: "multiple_choice", prompt: "'kitab' sözündəki saitlər necədir?", options: ["Qalın", "İncə", "Qarışıq", "Sait yoxdur"], correctIndex: 0, xp: 10, explanation: "«kitab» sözündə i və a var. Sözün son saiti a-dır, ona görə söz qalın sayılır və qalın şəkilçi qəbul edir." },
            { id: "az3-fonetika-l2-t4", type: "multiple_choice", prompt: "'ev' sözündəki sait necədir?", options: ["İncə", "Qalın", "Qarışıq", "Sait yoxdur"], correctIndex: 0, xp: 10, explanation: "«ev» sözündəki yeganə sait e-dir, e isə incədir." },
            { id: "az3-fonetika-l2-t5", type: "multiple_choice", prompt: "Qalın saitlə bitən sözə hansı şəkilçi qoşulur?", options: ["-lar", "-lər", "İkisi də", "Heç biri"], correctIndex: 0, xp: 10, explanation: "Ahəng qanununa görə qalın saitli sözə qalın şəkilçi qoşulur: -lar." },
            { id: "az3-fonetika-l2-t6", type: "multiple_choice", prompt: "'gül' sözünə hansı cəm şəkilçisi uyğundur?", options: ["-lər", "-lar", "-lir", "-lur"], correctIndex: 0, xp: 10, explanation: "«gül» sözünün saiti ü-dür, yəni incədir — ona görə incə şəkilçi qoşulur: güllər." },
            { id: "az3-fonetika-l2-t7", type: "multiple_choice", prompt: "Azərbaycan dilində neçə sait var?", options: ["9", "6", "5", "12"], correctIndex: 0, xp: 10, explanation: "Saitlər: a, e, ə, ı, i, o, ö, u, ü — cəmi 9." },
            { id: "az3-fonetika-l2-t8", type: "fill_blank", prompt: "Qalın saitlər: a, ı, o, ______ . (bir hərf)", accepted: ["u", "U"], xp: 10, explanation: "Qalın saitlər dörddür: a, ı, o və u." },
            { id: "az3-fonetika-l2-t9", type: "multiple_choice", prompt: "'uşaq' sözündəki saitlər necədir?", options: ["Qalın", "İncə", "Qarışıq", "Sait yoxdur"], correctIndex: 0, xp: 10, explanation: "«uşaq» sözündə u və a var — hər ikisi qalın saitdir." },
            { id: "az3-fonetika-l2-t10", type: "multiple_choice", prompt: "Sait ahəngi nə deməkdir?", options: ["Saitlərin bir-birinə uyğunlaşması", "Sözün uzunluğu", "Hecaların sayı", "Samitlərin sırası"], correctIndex: 0, xp: 10, explanation: "Sait ahəngi odur ki, sözdəki saitlər eyni qrupdan olur və şəkilçi də həmin qrupa uyğun seçilir." },
          ],
          bonusTasks: [
            { id: "az3-fonetika-l2-b1", type: "multiple_choice", prompt: "Hansı söz sait ahənginə uyğun DEYİL?", options: ["kitabler", "kitablar", "evlər", "güllər"], correctIndex: 0, xp: 15, explanation: "«kitab» qalın saitli sözdür, ona görə -lar qoşulmalıdır: kitablar. «Kitabler» ahəngi pozur." },
            { id: "az3-fonetika-l2-b2", type: "multiple_choice", prompt: "'məktəb' sözünə hansı şəkilçi uyğundur?", options: ["-lər", "-lar", "-luq", "-lıq"], correctIndex: 0, xp: 15, explanation: "«məktəb» sözünün saitləri incədir (ə, ə), ona görə incə şəkilçi qoşulur: -lər." },
            { id: "az3-fonetika-l2-b3", type: "multiple_choice", prompt: "İncə saitlər hansılardır?", options: ["e, ə, i, ö, ü", "a, ı, o, u", "a, e, i", "o, ö, u, ü"], correctIndex: 0, xp: 15, explanation: "İncə saitlərin tam siyahısı budur: e, ə, i, ö, ü." },
            { id: "az3-fonetika-l2-b4", type: "multiple_choice", prompt: "Alınma sözlərdə sait ahəngi həmişə gözlənilirmi?", options: ["Xeyr, pozula bilər", "Bəli, həmişə", "Yalnız uzun sözlərdə", "Bilmək olmur"], correctIndex: 0, xp: 15, explanation: "Başqa dillərdən keçən sözlərdə (kitab, televizor) saitlər fərqli qruplardan ola bilər — ahəng pozulur." },
          ],
        },
        {
          id: "az3-fonetika-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az3-fonetika-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 2. Sözün quruluşu ═══════════════
    {
      id: "az3-qurulus",
      title: "Sözün quruluşu",
      description: "Sözün kökü və şəkilçisi.",
      lessons: [
        {
          id: "az3-qurulus-l1",
          title: "Kök və şəkilçi",
          intro: "Sözün əsas hissəsi kök, ona qoşulan hissə şəkilçidir.",
          sections: [
            { heading: "Kök", body: "Sözün məna daşıyan əsas hissəsi köküdür: 'kitab' sözündə kök 'kitab'-dır." },
            { heading: "Şəkilçi", body: "Kökə qoşulan hissə şəkilçidir: 'kitablar' — kök 'kitab', şəkilçi '-lar' (cəm). 'evdə' — kök 'ev', şəkilçi '-də'." },
          ],
          tasks: [
            { id: "az3-qurulus-l1-t1", type: "multiple_choice", prompt: "'kitablar' sözünün kökü hansıdır?", options: ["kitab", "lar", "kitabl", "ar"], correctIndex: 0, xp: 10, explanation: "Sözü hissələrə ayırırıq: kitab + lar. Şəkilçini atsaq, məna daşıyan kök qalır — kitab." },
            { id: "az3-qurulus-l1-t2", type: "multiple_choice", prompt: "'evlər' sözünün kökü hansıdır?", options: ["ev", "lər", "evl", "ər"], correctIndex: 0, xp: 10, explanation: "Sözü hissələrə ayırırıq: ev + lər. Kök ev-dir." },
            { id: "az3-qurulus-l1-t3", type: "multiple_choice", prompt: "'kitablar' sözündə şəkilçi hansıdır?", options: ["-lar", "kitab", "-ar", "kit"], correctIndex: 0, xp: 10, explanation: "«Kitablar» sözündə kök kitab, ona qoşulan hissə isə -lar şəkilçisidir." },
            { id: "az3-qurulus-l1-t4", type: "multiple_choice", prompt: "Sözün əsas, məna daşıyan hissəsi necə adlanır?", options: ["kök", "şəkilçi", "heca", "səs"], correctIndex: 0, xp: 10, explanation: "Sözün əsas mənasını daşıyan, şəkilçisiz hissəsi kök adlanır." },
            { id: "az3-qurulus-l1-t5", type: "multiple_choice", prompt: "Kökə qoşulan hissə necə adlanır?", options: ["şəkilçi", "kök", "heca", "vurğu"], correctIndex: 0, xp: 10, explanation: "Kökə qoşulub ona yeni və ya qrammatik məna verən hissə şəkilçidir." },
            { id: "az3-qurulus-l1-t6", type: "multiple_choice", prompt: "'güllər' sözünün kökü hansıdır?", options: ["gül", "lər", "gül­l", "ər"], correctIndex: 0, xp: 10, explanation: "Sözü hissələrə ayırırıq: gül + lər. Kök gül-dür." },
            { id: "az3-qurulus-l1-t7", type: "multiple_choice", prompt: "'evdə' sözünün kökü hansıdır?", options: ["ev", "də", "evd", "ə"], correctIndex: 0, xp: 10, explanation: "Sözü hissələrə ayırırıq: ev + də. Kök ev-dir, -də isə yer bildirən şəkilçidir." },
            { id: "az3-qurulus-l1-t8", type: "multiple_choice", prompt: "'-lar/-lər' şəkilçisi nə bildirir?", options: ["cəm (çoxluq)", "yer", "sahiblik", "hərəkət"], correctIndex: 0, xp: 10, explanation: "-lar/-lər şəkilçisi əşyanın birdən çox olduğunu, yəni çoxluğu bildirir." },
            { id: "az3-qurulus-l1-t9", type: "multiple_choice", prompt: "'uşaqlar' sözünün kökü hansıdır?", options: ["uşaq", "lar", "uşaql", "ar"], correctIndex: 0, xp: 10, explanation: "Sözü hissələrə ayırırıq: uşaq + lar. Kök uşaq-dır." },
            { id: "az3-qurulus-l1-t10", type: "multiple_choice", prompt: "'dağlar' sözünün kökü hansıdır?", options: ["dağ", "lar", "dağl", "ar"], correctIndex: 0, xp: 10, explanation: "Sözü hissələrə ayırırıq: dağ + lar. Kök dağ-dır." },
            { id: "az3-qurulus-l1-t11", type: "multiple_choice", prompt: "'kitabım' sözündə şəkilçi hansıdır?", options: ["-ım", "kitab", "-m", "kit"], correctIndex: 0, xp: 10, explanation: "Sözü hissələrə ayırırıq: kitab + ım. -ım şəkilçisi kitabın kimə aid olduğunu bildirir." },
            { id: "az3-qurulus-l1-t12", type: "multiple_choice", prompt: "'meşədə' sözünün kökü hansıdır?", options: ["meşə", "də", "meş", "ə"], correctIndex: 0, xp: 10, explanation: "Sözü hissələrə ayırırıq: meşə + də. Kök meşə-dir." },
            { id: "az3-qurulus-l1-t13", type: "multiple_choice", prompt: "Hər sözdə mütləq olan hissə hansıdır?", options: ["kök", "şəkilçi", "cəm şəkilçisi", "vurğu"], correctIndex: 0, xp: 10, explanation: "Şəkilçi olmaya bilər, amma kök olmasa söz heç bir məna daşımaz — deməli kök mütləqdir." },
            { id: "az3-qurulus-l1-t14", type: "multiple_choice", prompt: "'quşlar' sözünün kökü hansıdır?", options: ["quş", "lar", "quşl", "ar"], correctIndex: 0, xp: 10, explanation: "Sözü hissələrə ayırırıq: quş + lar. Kök quş-dur." },
            { id: "az3-qurulus-l1-t15", type: "multiple_choice", prompt: "'baxçalar' sözündə şəkilçi hansıdır?", options: ["-lar", "baxça", "-ar", "bax"], correctIndex: 0, xp: 15, explanation: "«Baxçalar» sözündə kök baxça, şəkilçi isə -lar-dır." },
          ],
          bonusTasks: [
            { id: "az3-qurulus-l1-b1", type: "multiple_choice", prompt: "'kitabxanada' sözünün kökü hansıdır?", options: ["kitabxana", "da", "kitab", "xana"], correctIndex: 0, xp: 15, explanation: "«Kitabxanada» sözündən yer şəkilçisi -da-nı ayırırıq. Qalan «kitabxana» bütöv bir söz kimi kökdür." },
            { id: "az3-qurulus-l1-b2", type: "multiple_choice", prompt: "'evimiz' sözündə şəkilçi hansıdır?", options: ["-imiz", "ev", "-miz", "evi"], correctIndex: 0, xp: 15, explanation: "Sözü hissələrə ayırırıq: ev + imiz. -imiz şəkilçisi evin bizə aid olduğunu bildirir." },
            { id: "az3-qurulus-l1-b3", type: "multiple_choice", prompt: "Kök tək başına söz ola bilərmi?", options: ["bəli", "xeyr", "yalnız cəmdə", "yalnız feildə"], correctIndex: 0, xp: 15, explanation: "Kök özü də tam mənalı sözdür: «ev», «gül», «kitab» — hamısı şəkilçisiz işlənə bilir." },
            { id: "az3-qurulus-l1-b4", type: "multiple_choice", prompt: "'ağaclar' sözünün kökü hansıdır?", options: ["ağac", "lar", "ağacl", "ar"], correctIndex: 0, xp: 15, explanation: "Sözü hissələrə ayırırıq: ağac + lar. Kök ağac-dır." },
            { id: "az3-qurulus-l1-b5", type: "multiple_choice", prompt: "Şəkilçi sözə nə əlavə edir?", options: ["yeni məna/qrammatik məna", "heca", "vurğu", "səs"], correctIndex: 0, xp: 15, explanation: "Şəkilçi ya yeni söz yaradır (iş → işçi), ya da qrammatik məna verir (ev → evlər)." },
          ],
        },
        {
          id: "az3-qurulus-l2",
          title: "Düzəltmə sözlər",
          intro: "Şəkilçi kökə yeni məna verir.",
          sections: [
            { heading: "Söz düzəldən şəkilçi", body: "Kökə qoşulub YENİ SÖZ düzəldir: iş → işçi, su → suvarmaq, kitab → kitabça, duz → duzlu." },
            { heading: "Fərq", body: "Söz düzəldən şəkilçi yeni məna yaradır (bal → balıq deyil, bal → ballı). Sözü dəyişən şəkilçi isə yalnız formanı dəyişir (kitab → kitablar)." },
          ],
          tasks: [
            { id: "az3-qurulus-l2-t1", type: "multiple_choice", prompt: "'iş' sözündən hansı düzəltmə söz alınır?", options: ["işçi", "işlər", "işi", "işdə"], correctIndex: 0, xp: 10, explanation: "-çi şəkilçisi peşə bildirən yeni söz yaradır: iş → işçi. «İşlər» və «işdə» isə yeni söz deyil, formadır." },
            { id: "az3-qurulus-l2-t2", type: "multiple_choice", prompt: "'duz' sözündən hansı düzəltmə söz alınır?", options: ["duzlu", "duzlar", "duzu", "duzda"], correctIndex: 0, xp: 10, explanation: "-lu şəkilçisi əlamət bildirən yeni söz yaradır: duz → duzlu." },
            { id: "az3-qurulus-l2-t3", type: "multiple_choice", prompt: "'kitab' sözünün KÖKÜ hansıdır?", options: ["kitab", "kitablar", "-lar", "kitabça"], correctIndex: 0, xp: 10, explanation: "«Kitab» sözü şəkilçisizdir, yəni özü kökdür. Kitablar və kitabçada isə şəkilçi var." },
            { id: "az3-qurulus-l2-t4", type: "multiple_choice", prompt: "'meşəçi' sözündə şəkilçi hansıdır?", options: ["-çi", "meşə", "-lər", "meşəç"], correctIndex: 0, xp: 10, explanation: "Sözü hissələrə ayırırıq: meşə + çi. Peşə bildirən şəkilçi -çi-dir." },
            { id: "az3-qurulus-l2-t5", type: "multiple_choice", prompt: "Hansı söz DÜZƏLTMƏdir?", options: ["üzgüçü", "üzgüçülər", "üzür", "üzdü"], correctIndex: 0, xp: 10, explanation: "«Üzgüçü» sözü üz kökündən -güçü şəkilçisi ilə düzəlib və yeni peşə mənası daşıyır. Üzür və üzdü isə sadəcə feilin formalarıdır." },
            { id: "az3-qurulus-l2-t6", type: "multiple_choice", prompt: "Hansı söz SADƏdir (şəkilçisiz)?", options: ["ağac", "ağaclıq", "ağaclar", "ağacda"], correctIndex: 0, xp: 10, explanation: "«Ağac» sözünə heç bir şəkilçi qoşulmayıb — deməli sadə sözdür." },
            { id: "az3-qurulus-l2-t7", type: "fill_blank", prompt: "'süd' sözündən 'südçü' düzəldi. Şəkilçi ______-dür. (məs. -çü)", accepted: ["-çü", "çü", "-cü"], xp: 10, explanation: "Sözü hissələrə ayırırıq: süd + çü. Ahəngə görə şəkilçi -çü şəklində qoşulub." },
            { id: "az3-qurulus-l2-t8", type: "multiple_choice", prompt: "'yaz' kökündən hansı düzəltmə söz alınır?", options: ["yazıçı", "yazdım", "yazır", "yazacaq"], correctIndex: 0, xp: 10, explanation: "-ıçı şəkilçisi peşə bildirən yeni söz yaradır: yaz → yazıçı. Yazır və yazdım isə feilin zaman formalarıdır." },
            { id: "az3-qurulus-l2-t9", type: "multiple_choice", prompt: "Şəkilçi sözün harasına qoşulur?", options: ["Sonuna", "Əvvəlinə", "Ortasına", "Fərqi yoxdur"], correctIndex: 0, xp: 10, explanation: "Azərbaycan dilində şəkilçilər həmişə kökün sonuna qoşulur." },
            { id: "az3-qurulus-l2-t10", type: "multiple_choice", prompt: "'bağban' sözünün kökü hansıdır?", options: ["bağ", "ban", "bağba", "bağban"], correctIndex: 0, xp: 10, explanation: "Sözü hissələrə ayırırıq: bağ + ban. Kök bağ-dır, -ban isə peşə bildirən şəkilçidir." },
          ],
          bonusTasks: [
            { id: "az3-qurulus-l2-b1", type: "multiple_choice", prompt: "Hansı cütlükdə hər ikisi düzəltmə sözdür?", options: ["dəmirçi, çörəkçi", "kitab, qələm", "ev, su", "ağac, dağ"], correctIndex: 0, xp: 15, explanation: "Dəmir → dəmirçi, çörək → çörəkçi: hər ikisində -çi şəkilçisi yeni peşə sözü yaradıb. Digər cütlüklərdə şəkilçi yoxdur." },
            { id: "az3-qurulus-l2-b2", type: "multiple_choice", prompt: "'-lıq / -lik' şəkilçisi hansı sözü düzəldir?", options: ["dostluq", "dostlar", "dostu", "dosta"], correctIndex: 0, xp: 15, explanation: "-luq/-lik şəkilçisi anlayış bildirən yeni söz yaradır: dost → dostluq. «Dostlar» isə sadəcə cəmdir." },
            { id: "az3-qurulus-l2-b3", type: "multiple_choice", prompt: "'gözlük' sözünün kökü nədir?", options: ["göz", "lük", "gözlü", "gözlük"], correctIndex: 0, xp: 15, explanation: "Sözü hissələrə ayırırıq: göz + lük. Kök göz-dür." },
            { id: "az3-qurulus-l2-b4", type: "multiple_choice", prompt: "Söz düzəldən və söz dəyişdirən şəkilçi arasındakı fərq nədir?", options: ["Biri yeni söz yaradır, digəri formanı dəyişir", "Fərq yoxdur", "Biri uzundur", "Biri əvvəldə gəlir"], correctIndex: 0, xp: 15, explanation: "Söz düzəldən şəkilçi lüğətdə yeni söz yaradır (iş → işçi); söz dəyişdirən isə eyni sözün formasını dəyişir (iş → işdə)." },
          ],
        },
        {
          id: "az3-qurulus-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az3-qurulus-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 3. İsim ═══════════════
    {
      id: "az3-isim",
      title: "İsim",
      description: "Əşyanın adını bildirən söz; tək və cəm, xüsusi və ümumi isimlər.",
      lessons: [
        {
          id: "az3-isim-l1",
          title: "İsim: tək və cəm",
          intro: "İsim əşyanın adıdır; təkdə və cəmdə olur.",
          sections: [
            { heading: "İsim", body: "Əşyanın adını bildirən, 'kim?', 'nə?' suallarına cavab verən sözə isim deyilir: kitab, uşaq, dağ." },
            { heading: "Tək və cəm", body: "Tək: bir əşya (kitab). Cəm: çox əşya (kitablar). Cəm '-lar/-lər' şəkilçisi ilə düzəlir." },
            { heading: "Xüsusi və ümumi", body: "Xüsusi isimlər (adlar, şəhərlər) böyük hərflə yazılır: Ayşə, Bakı. Ümumi isimlər kiçik hərflə: qız, şəhər." },
          ],
          tasks: [
            { id: "az3-isim-l1-t1", type: "multiple_choice", prompt: "İsim hansı suallara cavab verir?", options: ["kim? nə?", "necə?", "nə edir?", "neçə?"], correctIndex: 0, xp: 10, explanation: "İsim əşya və varlıqların adıdır: canlılara «kim?», cansızlara «nə?» sualı verilir." },
            { id: "az3-isim-l1-t2", type: "multiple_choice", prompt: "Aşağıdakılardan hansı isimdir?", options: ["kitab", "oxumaq", "gözəl", "tez"], correctIndex: 0, xp: 10, explanation: "«Kitab» əşyanın adıdır. Gözəl sifət, tez zərf, oxumaq isə feildir." },
            { id: "az3-isim-l1-t3", type: "multiple_choice", prompt: "'kitab' sözünün cəmi hansıdır?", options: ["kitablar", "kitabı", "kitabda", "kitabın"], correctIndex: 0, xp: 10, explanation: "«Kitab» qalın saitli sözdür, ona görə cəm şəkilçisi -lar olur: kitablar. Kitabı və kitabın isə cəm deyil." },
            { id: "az3-isim-l1-t4", type: "multiple_choice", prompt: "'uşaq' sözünün cəmi hansıdır?", options: ["uşaqlar", "uşağı", "uşaqda", "uşağın"], correctIndex: 0, xp: 10, explanation: "«Uşaq» qalın saitli sözdür, ona görə: uşaqlar." },
            { id: "az3-isim-l1-t5", type: "multiple_choice", prompt: "Cəm şəkilçisi hansıdır?", options: ["-lar/-lər", "-da/-də", "-ın/-in", "-ı/-i"], correctIndex: 0, xp: 10, explanation: "Cəm şəkilçisi ahəngə görə iki cür olur: -lar (qalın) və -lər (incə)." },
            { id: "az3-isim-l1-t6", type: "multiple_choice", prompt: "Xüsusi isimlər necə yazılır?", options: ["böyük hərflə", "kiçik hərflə", "cəmdə", "rəqəmlə"], correctIndex: 0, xp: 10, explanation: "Xüsusi isim konkret bir varlığın adıdır, ona görə həmişə böyük hərflə yazılır." },
            { id: "az3-isim-l1-t7", type: "multiple_choice", prompt: "Aşağıdakılardan hansı xüsusi isimdir?", options: ["Bakı", "şəhər", "dağ", "çay"], correctIndex: 0, xp: 10, explanation: "«Bakı» konkret bir şəhərin adıdır — deməli xüsusi isimdir. Çay, dağ, şəhər isə ümumidir." },
            { id: "az3-isim-l1-t8", type: "multiple_choice", prompt: "Aşağıdakılardan hansı ümumi isimdir?", options: ["qız", "Ayşə", "Gəncə", "Kür"], correctIndex: 0, xp: 10, explanation: "«Qız» bütün qızlara aid ümumi addır. Ayşə, Gəncə, Kür isə konkret varlıqların adıdır." },
            { id: "az3-isim-l1-t9", type: "multiple_choice", prompt: "'gül' sözünün cəmi hansıdır?", options: ["güllər", "gülü", "güldə", "gülün"], correctIndex: 0, xp: 10, explanation: "«Gül» incə saitli sözdür, ona görə: güllər." },
            { id: "az3-isim-l1-t10", type: "multiple_choice", prompt: "'dağlar' sözü təkdə, yoxsa cəmdədir?", options: ["cəmdə", "təkdə", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Dağlar» sözündə -lar cəm şəkilçisi var — deməli birdən çox dağ nəzərdə tutulur." },
            { id: "az3-isim-l1-t11", type: "multiple_choice", prompt: "Aşağıdakılardan hansı isim DEYİL?", options: ["qaçmaq", "kitab", "dağ", "quş"], correctIndex: 0, xp: 10, explanation: "Quş, kitab və dağ əşyaların adıdır. «Qaçmaq» isə hərəkət bildirir, yəni feildir." },
            { id: "az3-isim-l1-t12", type: "multiple_choice", prompt: "İnsan adları hansı isim növüdür?", options: ["xüsusi", "ümumi", "cəm", "tək deyil"], correctIndex: 0, xp: 10, explanation: "İnsan adı konkret bir adamı bildirir — deməli xüsusi isimdir." },
            { id: "az3-isim-l1-t13", type: "multiple_choice", prompt: "'Elçin məktəbə getdi.' — isim hansıdır?", options: ["Elçin, məktəb", "getdi", "Elçin getdi", "heç biri"], correctIndex: 0, xp: 10, explanation: "Cümlədə «Elçin» insan adı, «məktəb» isə əşya adıdır. «Getdi» feildir." },
            { id: "az3-isim-l1-t14", type: "multiple_choice", prompt: "'quş' sözünün cəmi hansıdır?", options: ["quşlar", "quşu", "quşda", "quşun"], correctIndex: 0, xp: 10, explanation: "«Quş» qalın saitli sözdür, ona görə: quşlar." },
            { id: "az3-isim-l1-t15", type: "multiple_choice", prompt: "Aşağıdakılardan hansı xüsusi isimdir?", options: ["Nərmin", "uşaq", "kitab", "ev"], correctIndex: 0, xp: 15, explanation: "«Nərmin» konkret bir insanın adıdır — deməli xüsusi isimdir." },
          ],
          bonusTasks: [
            { id: "az3-isim-l1-b1", type: "multiple_choice", prompt: "'ağac' sözünün cəmi hansıdır?", options: ["ağaclar", "ağacı", "ağacda", "ağacın"], correctIndex: 0, xp: 15, explanation: "«Ağac» qalın saitli sözdür, ona görə: ağaclar." },
            { id: "az3-isim-l1-b2", type: "multiple_choice", prompt: "Şəhər, çay, dağ adları hansı isim növüdür?", options: ["xüsusi", "ümumi", "cəm", "tək"], correctIndex: 0, xp: 15, explanation: "Şəhər, çay və dağ adları konkret yerləri bildirir — deməli xüsusi isimdir." },
            { id: "az3-isim-l1-b3", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["Bakı", "bakı", "BAKı", "baKı"], correctIndex: 0, xp: 15, explanation: "Bakı xüsusi isimdir: yalnız ilk hərfi böyük yazılır." },
            { id: "az3-isim-l1-b4", type: "multiple_choice", prompt: "'pəncərələr' sözü hansı formadadır?", options: ["cəm", "tək", "xüsusi", "feil"], correctIndex: 0, xp: 15, explanation: "«Pəncərələr» sözündə -lər cəm şəkilçisi var." },
            { id: "az3-isim-l1-b5", type: "multiple_choice", prompt: "'Kür' sözü nəyin adıdır?", options: ["çayın (xüsusi isim)", "dağın", "şəhərin", "əşyanın"], correctIndex: 0, xp: 15, explanation: "Kür Azərbaycandan axan konkret bir çayın adıdır — deməli xüsusi isimdir." },
          ],
        },
        {
          id: "az3-isim-l2",
          title: "Xüsusi və ümumi isimlər",
          intro: "Adlar böyük, ümumi sözlər kiçik hərflə yazılır.",
          sections: [
            { heading: "Xüsusi isim", body: "Konkret bir varlığın adıdır: Aysel, Bakı, Kür, Azərbaycan. Həmişə BÖYÜK hərflə yazılır." },
            { heading: "Ümumi isim", body: "Eyni növdən olan hər şeyin adıdır: şəhər, çay, uşaq, ölkə. Kiçik hərflə yazılır." },
          ],
          tasks: [
            { id: "az3-isim-l2-t1", type: "multiple_choice", prompt: "Hansı XÜSUSİ isimdir?", options: ["Bakı", "şəhər", "küçə", "ev"], correctIndex: 0, xp: 10, explanation: "«Bakı» konkret bir şəhərin adıdır. Ev, şəhər, küçə isə hamıya aid ümumi adlardır." },
            { id: "az3-isim-l2-t2", type: "multiple_choice", prompt: "Hansı ÜMUMİ isimdir?", options: ["çay", "Kür", "Araz", "Xəzər"], correctIndex: 0, xp: 10, explanation: "«Çay» bütün çaylara aid ümumi addır. Xəzər, Araz, Kür isə konkret su hövzələrinin adıdır." },
            { id: "az3-isim-l2-t3", type: "multiple_choice", prompt: "Xüsusi isimlər necə yazılır?", options: ["Böyük hərflə", "Kiçik hərflə", "Fərqi yoxdur", "Dırnaqda"], correctIndex: 0, xp: 10, explanation: "Xüsusi isim konkret varlığı bildirir və həmişə böyük hərflə yazılır." },
            { id: "az3-isim-l2-t4", type: "multiple_choice", prompt: "Hansı XÜSUSİ isimdir?", options: ["Azərbaycan", "ölkə", "dövlət", "xalq"], correctIndex: 0, xp: 10, explanation: "«Azərbaycan» konkret bir ölkənin adıdır. Dövlət, ölkə, xalq isə ümumi addır." },
            { id: "az3-isim-l2-t5", type: "multiple_choice", prompt: "Hansı ÜMUMİ isimdir?", options: ["müəllim", "Aysel", "Nihad", "Leyla"], correctIndex: 0, xp: 10, explanation: "«Müəllim» bütün müəllimlərə aid ümumi addır. Aysel, Nihad, Leyla isə konkret insanların adıdır." },
            { id: "az3-isim-l2-t6", type: "multiple_choice", prompt: "'Nizami' sözü hansı isimdir?", options: ["Xüsusi", "Ümumi", "Sifət", "Feil"], correctIndex: 0, xp: 10, explanation: "Nizami konkret bir şairin adıdır — deməli xüsusi isimdir." },
            { id: "az3-isim-l2-t7", type: "fill_blank", prompt: "İnsan adları ______ hərflə yazılır. (bir söz)", accepted: ["böyük", "Böyük"], xp: 10, explanation: "İnsan adları xüsusi isim olduğu üçün böyük hərflə yazılır." },
            { id: "az3-isim-l2-t8", type: "multiple_choice", prompt: "Hansı cümlədə xüsusi isim var?", options: ["Aysel məktəbə getdi.", "Uşaq məktəbə getdi.", "O, məktəbə getdi.", "Məktəbə getdilər."], correctIndex: 0, xp: 10, explanation: "«Aysel» konkret bir insanın adıdır. Digər cümlələrdə «uşaq» və «o» ümumi sözlərdir." },
            { id: "az3-isim-l2-t9", type: "multiple_choice", prompt: "'dəniz' və 'Xəzər' — hansı xüsusidir?", options: ["Xəzər", "dəniz", "İkisi də", "Heç biri"], correctIndex: 0, xp: 10, explanation: "«Dəniz» ümumi addır, «Xəzər» isə konkret bir dənizin adıdır — deməli xüsusidir." },
            { id: "az3-isim-l2-t10", type: "multiple_choice", prompt: "Şəhər adları hansı isimdir?", options: ["Xüsusi", "Ümumi", "Sifət", "Say"], correctIndex: 0, xp: 10, explanation: "Şəhər adları konkret yerləri bildirir — deməli xüsusi isimdir." },
          ],
          bonusTasks: [
            { id: "az3-isim-l2-b1", type: "multiple_choice", prompt: "Hansı cümlədə səhv var?", options: ["mən bakıda yaşayıram.", "Mən Bakıda yaşayıram.", "Bakı gözəldir.", "Aysel Bakıdandır."], correctIndex: 0, xp: 15, explanation: "«Mən» cümlənin ilk sözüdür, «Bakı» isə xüsusi isimdir — hər ikisi böyük yazılmalıdır." },
            { id: "az3-isim-l2-b2", type: "multiple_choice", prompt: "Kitab adları necə yazılır?", options: ["Böyük hərflə və dırnaqda", "Kiçik hərflə", "Yalnız dırnaqda", "Fərqi yoxdur"], correctIndex: 0, xp: 15, explanation: "Kitab adı xüsusi addır: böyük hərflə başlayır və dırnaq içinə alınır — «Dədə Qorqud»." },
            { id: "az3-isim-l2-b3", type: "multiple_choice", prompt: "Hansı sırada hamısı xüsusi isimdir?", options: ["Gəncə, Kür, Nizami", "şəhər, çay, şair", "ev, su, ağac", "dağ, dəniz, göl"], correctIndex: 0, xp: 15, explanation: "Gəncə şəhər, Kür çay, Nizami isə şair adıdır — üçü də konkret varlığı bildirir." },
            { id: "az3-isim-l2-b4", type: "multiple_choice", prompt: "Heyvan adları (məs. pişiyin adı 'Pambıq') hansı isimdir?", options: ["Xüsusi", "Ümumi", "Sifət", "Feil"], correctIndex: 0, xp: 15, explanation: "Heyvana verilən ad konkret bir heyvanı bildirir — deməli xüsusi isimdir və böyük yazılır." },
          ],
        },
        {
          id: "az3-isim-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az3-isim-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 4. Sifət və say ═══════════════
    {
      id: "az3-sifetsay",
      title: "Sifət və say",
      description: "Əlamət bildirən sifət və miqdar bildirən say.",
      lessons: [
        {
          id: "az3-sifetsay-l1",
          title: "Sifət və say",
          intro: "Sifət əlaməti, say miqdarı bildirir.",
          sections: [
            { heading: "Sifət", body: "Əşyanın əlamətini bildirən, 'necə?', 'nə cür?' suallarına cavab verən sözə sifət deyilir: gözəl, böyük, qırmızı." },
            { heading: "Say", body: "Əşyanın miqdarını, sayını bildirən, 'neçə?', 'nə qədər?' suallarına cavab verən sözə say deyilir: bir, iki, beş, on." },
          ],
          tasks: [
            { id: "az3-sifetsay-l1-t1", type: "multiple_choice", prompt: "Sifət hansı suala cavab verir?", options: ["necə?", "kim?", "nə edir?", "neçə?"], correctIndex: 0, xp: 10, explanation: "Sifət əşyanın necə olduğunu bildirir, ona görə «necə?» sualına cavab verir." },
            { id: "az3-sifetsay-l1-t2", type: "multiple_choice", prompt: "Say hansı suala cavab verir?", options: ["neçə? nə qədər?", "necə?", "kim?", "nə edir?"], correctIndex: 0, xp: 10, explanation: "Say əşyanın miqdarını bildirir, ona görə «neçə? nə qədər?» suallarına cavab verir." },
            { id: "az3-sifetsay-l1-t3", type: "multiple_choice", prompt: "Aşağıdakılardan hansı sifətdir?", options: ["gözəl", "kitab", "beş", "oxumaq"], correctIndex: 0, xp: 10, explanation: "«Gözəl» əlamət bildirir. Kitab isim, beş say, oxumaq isə feildir." },
            { id: "az3-sifetsay-l1-t4", type: "multiple_choice", prompt: "Aşağıdakılardan hansı saydır?", options: ["üç", "gözəl", "kitab", "qaçmaq"], correctIndex: 0, xp: 10, explanation: "«Üç» miqdar bildirir, yəni saydır. Kitab isim, gözəl sifət, qaçmaq isə feildir." },
            { id: "az3-sifetsay-l1-t5", type: "multiple_choice", prompt: "'qırmızı gül' — hansı söz sifətdir?", options: ["qırmızı", "gül", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Gül» əşyanın adıdır, «qırmızı» isə onun rəngini, yəni əlamətini bildirir." },
            { id: "az3-sifetsay-l1-t6", type: "multiple_choice", prompt: "'beş kitab' — hansı söz saydır?", options: ["beş", "kitab", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Kitab» əşyanın adıdır, «beş» isə onların sayını bildirir." },
            { id: "az3-sifetsay-l1-t7", type: "multiple_choice", prompt: "Aşağıdakılardan hansı sifətdir?", options: ["böyük", "iki", "ev", "getmək"], correctIndex: 0, xp: 10, explanation: "«Böyük» ölçü, yəni əlamət bildirir. Ev isim, iki say, getmək isə feildir." },
            { id: "az3-sifetsay-l1-t8", type: "multiple_choice", prompt: "Aşağıdakılardan hansı saydır?", options: ["on", "isti", "su", "içmək"], correctIndex: 0, xp: 10, explanation: "«On» miqdar bildirir, yəni saydır. Su isim, isti sifət, içmək isə feildir." },
            { id: "az3-sifetsay-l1-t9", type: "multiple_choice", prompt: "'üç alma' — hansı söz saydır?", options: ["üç", "alma", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Alma» əşyanın adıdır, «üç» isə onların sayını bildirir." },
            { id: "az3-sifetsay-l1-t10", type: "multiple_choice", prompt: "'isti çay' — hansı söz sifətdir?", options: ["isti", "çay", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Çay» əşyanın adıdır, «isti» isə onun necə olduğunu bildirir." },
            { id: "az3-sifetsay-l1-t11", type: "multiple_choice", prompt: "'yaşıl yarpaq' — sifət hansıdır?", options: ["yaşıl", "yarpaq", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Yarpaq» əşyanın adıdır, «yaşıl» isə onun rəngini bildirir." },
            { id: "az3-sifetsay-l1-t12", type: "multiple_choice", prompt: "Sifət əşyanın nəyini bildirir?", options: ["əlamətini", "sayını", "hərəkətini", "adını"], correctIndex: 0, xp: 10, explanation: "Sifət əşyanın rəngini, ölçüsünü, dadını — bir sözlə əlamətini bildirir." },
            { id: "az3-sifetsay-l1-t13", type: "multiple_choice", prompt: "Say əşyanın nəyini bildirir?", options: ["miqdarını/sayını", "əlamətini", "hərəkətini", "adını"], correctIndex: 0, xp: 10, explanation: "Say əşyanın neçə dənə olduğunu, yəni miqdarını bildirir." },
            { id: "az3-sifetsay-l1-t14", type: "multiple_choice", prompt: "'iki gözəl gül' — say hansıdır?", options: ["iki", "gözəl", "gül", "heç biri"], correctIndex: 0, xp: 10, explanation: "İfadədə «gül» isim, «gözəl» sifət, «iki» isə saydır — gülün sayını göstərir." },
            { id: "az3-sifetsay-l1-t15", type: "multiple_choice", prompt: "'böyük' sözünün əksi (antonim) hansıdır?", options: ["kiçik", "gözəl", "isti", "yeni"], correctIndex: 0, xp: 15, explanation: "Böyük çox, kiçik isə az yer tutan deməkdir — bunlar bir-birinin əksidir." },
          ],
          bonusTasks: [
            { id: "az3-sifetsay-l1-b1", type: "multiple_choice", prompt: "'On beş dəftər' — say hansıdır?", options: ["on beş", "dəftər", "on", "beş"], correctIndex: 0, xp: 15, explanation: "Say bir neçə sözdən ibarət ola bilər. Burada dəftərin sayı «on beş»dir, təkcə «on» və ya «beş» yox." },
            { id: "az3-sifetsay-l1-b2", type: "multiple_choice", prompt: "'təmiz, işıqlı otaq' — neçə sifət var?", options: ["2 (təmiz, işıqlı)", "1", "3", "0"], correctIndex: 0, xp: 15, explanation: "Otağın necə olduğunu iki söz göstərir: «təmiz» və «işıqlı»." },
            { id: "az3-sifetsay-l1-b3", type: "multiple_choice", prompt: "'birinci' sözü hansı nitq hissəsidir?", options: ["say (sıra)", "sifət", "isim", "feil"], correctIndex: 0, xp: 15, explanation: "«Birinci» miqdar yox, sıra bildirir — «neçənci?» sualına cavab verir." },
            { id: "az3-sifetsay-l1-b4", type: "multiple_choice", prompt: "'soyuq' sözünün əksi hansıdır?", options: ["isti", "böyük", "təmiz", "yeni"], correctIndex: 0, xp: 15, explanation: "Soyuq aşağı, isti isə yüksək istilik bildirir — bunlar bir-birinin əksidir." },
            { id: "az3-sifetsay-l1-b5", type: "multiple_choice", prompt: "'üç böyük ağac' — bu ifadədə isim hansıdır?", options: ["ağac", "üç", "böyük", "heç biri"], correctIndex: 0, xp: 15, explanation: "İfadədə «üç» say, «böyük» sifət, «ağac» isə əşyanın adıdır, yəni isimdir." },
          ],
        },
        {
          id: "az3-sifetsay-l2",
          title: "Miqdar və sıra sayları",
          intro: "Neçə? və neçənci? — iki fərqli sual.",
          sections: [
            { heading: "Miqdar sayı", body: "'Neçə?' sualına cavab verir: bir, iki, üç, on. Məsələn: beş kitab." },
            { heading: "Sıra sayı", body: "'Neçənci?' sualına cavab verir və -ıncı/-inci şəkilçisi alır: birinci, ikinci, beşinci." },
          ],
          tasks: [
            { id: "az3-sifetsay-l2-t1", type: "multiple_choice", prompt: "'beş kitab' — burada 'beş' hansı saydır?", options: ["Miqdar", "Sıra", "Sifət", "İsim"], correctIndex: 0, xp: 10, explanation: "«Beş» kitabların neçə dənə olduğunu göstərir — deməli miqdar sayıdır." },
            { id: "az3-sifetsay-l2-t2", type: "multiple_choice", prompt: "'beşinci sinif' — burada 'beşinci' hansı saydır?", options: ["Sıra", "Miqdar", "Sifət", "İsim"], correctIndex: 0, xp: 10, explanation: "«Beşinci» sinifin neçənci olduğunu göstərir — deməli sıra sayıdır." },
            { id: "az3-sifetsay-l2-t3", type: "multiple_choice", prompt: "Miqdar sayı hansı suala cavab verir?", options: ["Neçə?", "Neçənci?", "Necə?", "Harada?"], correctIndex: 0, xp: 10, explanation: "Miqdar sayı əşyanın sayını bildirir, ona görə «Neçə?» sualına cavab verir." },
            { id: "az3-sifetsay-l2-t4", type: "multiple_choice", prompt: "Sıra sayı hansı suala cavab verir?", options: ["Neçənci?", "Neçə?", "Necə?", "Nə vaxt?"], correctIndex: 0, xp: 10, explanation: "Sıra sayı əşyanın sırada yerini bildirir, ona görə «Neçənci?» sualına cavab verir." },
            { id: "az3-sifetsay-l2-t5", type: "multiple_choice", prompt: "Hansı SIRA sayıdır?", options: ["üçüncü", "üç", "üçlük", "üçdə"], correctIndex: 0, xp: 10, explanation: "«Üçüncü» sözündə -üncü sıra şəkilçisi var — deməli sıra sayıdır." },
            { id: "az3-sifetsay-l2-t6", type: "multiple_choice", prompt: "Hansı MİQDAR sayıdır?", options: ["yeddi", "yeddinci", "yeddilik", "yeddidə"], correctIndex: 0, xp: 10, explanation: "«Yeddi» heç bir şəkilçi olmadan sadəcə miqdar bildirir." },
            { id: "az3-sifetsay-l2-t7", type: "fill_blank", prompt: "Sıra sayının şəkilçisi ______ / -inci-dir. (məs. -ıncı)", accepted: ["-ıncı", "ıncı", "-inci"], xp: 10, explanation: "Sıra sayı miqdar sayına -ıncı, -inci, -uncu, -üncü şəkilçisi qoşmaqla düzəlir: beş → beşinci." },
            { id: "az3-sifetsay-l2-t8", type: "multiple_choice", prompt: "'On beş şagird' ifadəsində say hansıdır?", options: ["on beş", "şagird", "on", "beş şagird"], correctIndex: 0, xp: 10, explanation: "Şagirdlərin sayı «on beş»dir — say bir neçə sözdən ibarət ola bilər." },
            { id: "az3-sifetsay-l2-t9", type: "multiple_choice", prompt: "'Birinci yer' — 'birinci' nəyi bildirir?", options: ["Sıranı", "Miqdarı", "Rəngi", "Ölçünü"], correctIndex: 0, xp: 10, explanation: "«Birinci» yerin sırada neçənci olduğunu göstərir." },
            { id: "az3-sifetsay-l2-t10", type: "multiple_choice", prompt: "Hansı cümlədə sıra sayı var?", options: ["İkinci dərs başladı.", "İki dərs var.", "Dərs iki saatdır.", "Dərsə iki nəfər gəldi."], correctIndex: 0, xp: 10, explanation: "«İkinci» sözündə -inci sıra şəkilçisi var. Digər cümlələrdə «iki» sadəcə miqdar bildirir." },
          ],
          bonusTasks: [
            { id: "az3-sifetsay-l2-b1", type: "multiple_choice", prompt: "'Yüz iyirmi beşinci' — bu hansı saydır?", options: ["Sıra", "Miqdar", "Sifət", "İsim"], correctIndex: 0, xp: 15, explanation: "Sonuncu sözdə -inci sıra şəkilçisi var — deməli bütün ifadə sıra sayıdır." },
            { id: "az3-sifetsay-l2-b2", type: "multiple_choice", prompt: "Saylar hansı sözlərlə birlikdə işlənir?", options: ["İsimlərlə", "Feillərlə", "Zərflərlə", "Bağlayıcılarla"], correctIndex: 0, xp: 15, explanation: "Say əşyanın miqdarını və ya sırasını bildirir, ona görə isimlərin yanında işlənir: beş kitab, ikinci sinif." },
            { id: "az3-sifetsay-l2-b3", type: "multiple_choice", prompt: "'Üç qat' ifadəsində say nə bildirir?", options: ["Miqdarı", "Sıranı", "Rəngi", "Yeri"], correctIndex: 0, xp: 15, explanation: "«Üç qat» nə qədər olduğunu göstərir — deməli miqdar bildirir." },
            { id: "az3-sifetsay-l2-b4", type: "multiple_choice", prompt: "Sıra sayları rəqəmlə necə yazılır?", options: ["5-ci", "5 ci", "5.ci", "ci-5"], correctIndex: 0, xp: 15, explanation: "Sıra sayı rəqəmlə yazılanda şəkilçi defislə ayrılır: 5-ci, 2-ci, 10-cu." },
          ],
        },
        {
          id: "az3-sifetsay-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az3-sifetsay-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 5. Feil ═══════════════
    {
      id: "az3-feil",
      title: "Feil",
      description: "Hərəkət bildirən söz və onun zamanları.",
      lessons: [
        {
          id: "az3-feil-l1",
          title: "Feil və zamanları",
          intro: "Feil hərəkət bildirir; keçmiş, indiki, gələcək zamanda olur.",
          sections: [
            { heading: "Feil", body: "İşi, hərəkəti bildirən söz feildir: gəlir, oxudu, yazacaq. 'Nə edir?', 'nə etdi?', 'nə edəcək?' suallarına cavab verir." },
            { heading: "Zamanlar", body: "Keçmiş: gəldi (oldu). İndiki: gəlir (indi olur). Gələcək: gələcək (sonra olacaq)." },
          ],
          tasks: [
            { id: "az3-feil-l1-t1", type: "multiple_choice", prompt: "Feil hansı suala cavab verir?", options: ["nə edir?", "kim?", "necə?", "neçə?"], correctIndex: 0, xp: 10, explanation: "Feil işin görülməsini bildirir, ona görə «nə edir?» sualına cavab verir." },
            { id: "az3-feil-l1-t2", type: "multiple_choice", prompt: "Aşağıdakılardan hansı feildir?", options: ["oxuyur", "kitab", "gözəl", "beş"], correctIndex: 0, xp: 10, explanation: "«Oxuyur» iş bildirir. Kitab isim, gözəl sifət, beş isə saydır." },
            { id: "az3-feil-l1-t3", type: "multiple_choice", prompt: "'gəldi' feili hansı zamandadır?", options: ["keçmiş", "indiki", "gələcək", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Gəldi» sözündə -di şəkilçisi var və iş artıq bitib — deməli keçmiş zamandır." },
            { id: "az3-feil-l1-t4", type: "multiple_choice", prompt: "'gəlir' feili hansı zamandadır?", options: ["indiki", "keçmiş", "gələcək", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Gəlir» sözündə -ir şəkilçisi var və iş indi davam edir — deməli indiki zamandır." },
            { id: "az3-feil-l1-t5", type: "multiple_choice", prompt: "'gələcək' feili hansı zamandadır?", options: ["gələcək", "keçmiş", "indiki", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Gələcək» sözündə -əcək şəkilçisi var və iş hələ olmayıb — deməli gələcək zamandır." },
            { id: "az3-feil-l1-t6", type: "multiple_choice", prompt: "'Uşaq oynayır.' — feil hansıdır?", options: ["oynayır", "uşaq", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Uşaq» işi görəndir, «oynayır» isə görülən işdir." },
            { id: "az3-feil-l1-t7", type: "multiple_choice", prompt: "'yazdı' feili hansı zamandadır?", options: ["keçmiş", "indiki", "gələcək", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Yazdı» sözündə -dı şəkilçisi var və iş bitib — deməli keçmiş zamandır." },
            { id: "az3-feil-l1-t8", type: "multiple_choice", prompt: "'oxuyacaq' feili hansı zamandadır?", options: ["gələcək", "keçmiş", "indiki", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Oxuyacaq» sözündə -acaq şəkilçisi var — deməli gələcək zamandır." },
            { id: "az3-feil-l1-t9", type: "fill_blank", prompt: "'gəl' feilini keçmiş zamana çevir (3-cü şəxs tək).", accepted: ["gəldi"], xp: 10, explanation: "Kökə keçmiş zaman şəkilçisi qoşuruq: gəl + di = gəldi." },
            { id: "az3-feil-l1-t10", type: "fill_blank", prompt: "'yaz' feilini indiki zamana çevir (3-cü şəxs tək).", accepted: ["yazır"], xp: 10, explanation: "Kökə indiki zaman şəkilçisi qoşuruq: yaz + ır = yazır." },
            { id: "az3-feil-l1-t11", type: "multiple_choice", prompt: "Aşağıdakılardan hansı feil DEYİL?", options: ["kitab", "gəlir", "oxudu", "yazacaq"], correctIndex: 0, xp: 10, explanation: "Yazacaq, gəlir və oxudu iş bildirir. «Kitab» isə əşyanın adıdır." },
            { id: "az3-feil-l1-t12", type: "multiple_choice", prompt: "'Quş uçur.' — feil hansı zamandadır?", options: ["indiki", "keçmiş", "gələcək", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Uçur» sözündə -ur şəkilçisi var və iş indi davam edir — deməli indiki zamandır." },
            { id: "az3-feil-l1-t13", type: "multiple_choice", prompt: "Feil neçə zamanda olur?", options: ["üç (keçmiş, indiki, gələcək)", "iki", "dörd", "bir"], correctIndex: 0, xp: 10, explanation: "İş ya artıq olub, ya indi olur, ya da hələ olacaq — buna görə üç zaman var." },
            { id: "az3-feil-l1-t14", type: "fill_blank", prompt: "'oxu' feilini gələcək zamana çevir (3-cü şəxs tək).", accepted: ["oxuyacaq"], xp: 10, explanation: "Kökə gələcək zaman şəkilçisi qoşuruq: oxu + yacaq = oxuyacaq." },
            { id: "az3-feil-l1-t15", type: "multiple_choice", prompt: "'Sabah gedəcəyəm.' — feil hansı zamandadır?", options: ["gələcək", "keçmiş", "indiki", "heç biri"], correctIndex: 0, xp: 15, explanation: "«Sabah» sözü və -əcək şəkilçisi işin hələ olmadığını göstərir." },
          ],
          bonusTasks: [
            { id: "az3-feil-l1-b1", type: "multiple_choice", prompt: "'Dünən oxudum.' — feil hansı zamandadır?", options: ["keçmiş", "indiki", "gələcək", "heç biri"], correctIndex: 0, xp: 15, explanation: "«Dünən» sözü və -du şəkilçisi işin artıq bitdiyini göstərir." },
            { id: "az3-feil-l1-b2", type: "fill_blank", prompt: "'get' feilini keçmiş zamana çevir (3-cü şəxs tək).", accepted: ["getdi"], xp: 15, explanation: "Kökə keçmiş zaman şəkilçisi qoşuruq: get + di = getdi." },
            { id: "az3-feil-l1-b3", type: "multiple_choice", prompt: "'Ağ pişik yatır.' — feil hansıdır?", options: ["yatır", "ağ", "pişik", "heç biri"], correctIndex: 0, xp: 15, explanation: "Cümlədə «ağ» sifət, «pişik» isim, «yatır» isə feildir." },
            { id: "az3-feil-l1-b4", type: "multiple_choice", prompt: "İnkar: 'gəl' feilinin inkarı hansıdır?", options: ["gəlmə", "gəldi", "gəlir", "gələcək"], correctIndex: 0, xp: 15, explanation: "İnkar üçün kökə -mə şəkilçisi qoşulur: gəl + mə = gəlmə." },
            { id: "az3-feil-l1-b5", type: "fill_blank", prompt: "'yaz' feilinin inkar formasını yaz.", accepted: ["yazma"], xp: 15, explanation: "İnkar üçün kökə -ma şəkilçisi qoşulur: yaz + ma = yazma." },
          ],
        },
        {
          id: "az3-feil-l2",
          title: "Feilin şəxsə görə dəyişməsi",
          intro: "Kim edir? — feil buna görə dəyişir.",
          sections: [
            { heading: "Şəxs şəkilçiləri", body: "mən yazıram, sən yazırsan, o yazır, biz yazırıq, siz yazırsınız, onlar yazırlar." },
            { heading: "Təsdiq və inkar", body: "Feilə -ma / -mə əlavə edəndə inkar olur: gəlirəm → gəlmirəm, yazdım → yazmadım." },
          ],
          tasks: [
            { id: "az3-feil-l2-t1", type: "multiple_choice", prompt: "'Mən ______' — hansı forma düzgündür?", options: ["yazıram", "yazırsan", "yazır", "yazırıq"], correctIndex: 0, xp: 10, explanation: "«Mən» I şəxs təkdir, ona görə feilə -am şəxs şəkilçisi qoşulur: yazıram." },
            { id: "az3-feil-l2-t2", type: "multiple_choice", prompt: "'Onlar ______' — hansı forma düzgündür?", options: ["gəlirlər", "gəlirəm", "gəlirsən", "gəlir"], correctIndex: 0, xp: 10, explanation: "«Onlar» III şəxs cəmdir, ona görə feilə -lər qoşulur: gəlirlər." },
            { id: "az3-feil-l2-t3", type: "multiple_choice", prompt: "'Biz ______' — hansı forma düzgündür?", options: ["oxuyuruq", "oxuyuram", "oxuyur", "oxuyursan"], correctIndex: 0, xp: 10, explanation: "«Biz» I şəxs cəmdir, ona görə feilə -uq qoşulur: oxuyuruq." },
            { id: "az3-feil-l2-t4", type: "multiple_choice", prompt: "'gəlirəm' feilinin inkarı hansıdır?", options: ["gəlmirəm", "gəldim", "gələcəyəm", "gəlirsən"], correctIndex: 0, xp: 10, explanation: "İnkar şəkilçisi kökdən sonra gəlir: gəl + mir + əm = gəlmirəm." },
            { id: "az3-feil-l2-t5", type: "multiple_choice", prompt: "'yazdım' feilinin inkarı hansıdır?", options: ["yazmadım", "yazıram", "yazacağam", "yazdın"], correctIndex: 0, xp: 10, explanation: "İnkar şəkilçisi kökdən sonra gəlir: yaz + ma + dım = yazmadım." },
            { id: "az3-feil-l2-t6", type: "multiple_choice", prompt: "İnkar şəkilçisi hansıdır?", options: ["-ma / -mə", "-lar / -lər", "-dı / -di", "-ır / -ir"], correctIndex: 0, xp: 10, explanation: "Feilin inkarı -ma/-mə şəkilçisi ilə düzəlir: gəlmə, yazma." },
            { id: "az3-feil-l2-t7", type: "multiple_choice", prompt: "'Sən ______' — hansı forma düzgündür?", options: ["gedirsən", "gedirəm", "gedir", "gedirik"], correctIndex: 0, xp: 10, explanation: "«Sən» II şəxs təkdir, ona görə feilə -sən qoşulur: gedirsən." },
            { id: "az3-feil-l2-t8", type: "fill_blank", prompt: "'O ______' (oxumaq, indiki zaman) — düzgün forma nədir?", accepted: ["oxuyur", "Oxuyur"], xp: 10, explanation: "«O» III şəxs təkdir və indiki zamanda əlavə şəxs şəkilçisi almır: oxuyur." },
            { id: "az3-feil-l2-t9", type: "multiple_choice", prompt: "Feil nəyə görə dəyişir?", options: ["Şəxsə və zamana", "Rəngə", "Ölçüyə", "Yerə"], correctIndex: 0, xp: 10, explanation: "Feil həm işin nə vaxt olduğunu (zaman), həm də kimin gördüyünü (şəxs) bildirir — hər ikisinə görə dəyişir." },
            { id: "az3-feil-l2-t10", type: "multiple_choice", prompt: "'Siz gəlirsiniz' cümləsində şəxs hansıdır?", options: ["II şəxs cəm", "I şəxs tək", "III şəxs tək", "I şəxs cəm"], correctIndex: 0, xp: 10, explanation: "«Siz» ünvanlandığımız bir neçə adamı bildirir — deməli II şəxs cəmdir." },
          ],
          bonusTasks: [
            { id: "az3-feil-l2-b1", type: "multiple_choice", prompt: "'Onlar gəlmədilər' cümləsi necədir?", options: ["İnkar, keçmiş zaman", "Təsdiq, keçmiş zaman", "İnkar, gələcək zaman", "Təsdiq, indiki zaman"], correctIndex: 0, xp: 15, explanation: "Sözü hissələrə ayırırıq: gəl + mə (inkar) + di (keçmiş) + lər (cəm)." },
            { id: "az3-feil-l2-b2", type: "multiple_choice", prompt: "'Oxumuram' feilində neçə şəkilçi var?", options: ["İki: inkar və şəxs", "Bir", "Üç", "Heç biri"], correctIndex: 0, xp: 15, explanation: "Sözü hissələrə ayırırıq: oxu + mur (inkar) + am (şəxs) — iki şəkilçi var." },
            { id: "az3-feil-l2-b3", type: "multiple_choice", prompt: "Hansı cümlədə feil III şəxs cəmdədir?", options: ["Uşaqlar oynayırlar.", "Uşaq oynayır.", "Mən oynayıram.", "Sən oynayırsan."], correctIndex: 0, xp: 15, explanation: "«Uşaqlar» III şəxs cəmdir, feil də ona uyğun -lar şəkilçisi alıb: oynayırlar." },
            { id: "az3-feil-l2-b4", type: "multiple_choice", prompt: "'Gəlməyəcəyəm' feilində zaman hansıdır?", options: ["Gələcək", "Keçmiş", "İndiki", "Zamansız"], correctIndex: 0, xp: 15, explanation: "Sözdə -əcək şəkilçisi var — iş hələ baş verməyib, sadəcə inkar edilib." },
          ],
        },
        {
          id: "az3-feil-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az3-feil-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 6. Cümlə və mətn ═══════════════
    {
      id: "az3-cumle",
      title: "Cümlə və mətn",
      description: "Cümlə növləri, mübtəda-xəbər və mətn.",
      lessons: [
        {
          id: "az3-cumle-l1",
          title: "Cümlə",
          intro: "Cümlə növləri və əsas üzvləri.",
          sections: [
            { heading: "Cümlə növləri", body: "Nəqli cümlə məlumat verir (nöqtə). Sual cümləsi sual verir (?). Nida cümləsi hiss bildirir (!)." },
            { heading: "Kim/nə iş görür?", body: "Cümlədə iş görəni bildirən söz mübtəda, işi bildirən söz xəbərdir: 'Uşaq oxuyur.' — uşaq (mübtəda), oxuyur (xəbər)." },
          ],
          tasks: [
            { id: "az3-cumle-l1-t1", type: "multiple_choice", prompt: "Məlumat verən cümlə necə adlanır?", options: ["nəqli", "sual", "nida", "əmr"], correctIndex: 0, xp: 10, explanation: "Nəqli cümlə nəyisə xəbər verir, məlumat çatdırır və nöqtə ilə bitir." },
            { id: "az3-cumle-l1-t2", type: "multiple_choice", prompt: "Sual cümləsi hansı işarə ilə bitir?", options: ["sual işarəsi (?)", "nöqtə (.)", "nida işarəsi (!)", "vergül"], correctIndex: 0, xp: 10, explanation: "Sual cümləsində nəsə soruşulur, ona görə sonunda sual işarəsi qoyulur." },
            { id: "az3-cumle-l1-t3", type: "multiple_choice", prompt: "Nida cümləsi hansı işarə ilə bitir?", options: ["nida işarəsi (!)", "nöqtə", "sual işarəsi", "vergül"], correctIndex: 0, xp: 10, explanation: "Nida cümləsi güclü hiss bildirir, ona görə sonunda nida işarəsi qoyulur." },
            { id: "az3-cumle-l1-t4", type: "multiple_choice", prompt: "'Yağış yağır.' hansı cümlə növüdür?", options: ["nəqli", "sual", "nida", "əmr"], correctIndex: 0, xp: 10, explanation: "Cümlə sadəcə hava haqqında məlumat verir, sual vermir və güclü hiss bildirmir — deməli nəqlidir." },
            { id: "az3-cumle-l1-t5", type: "multiple_choice", prompt: "'Sən hara gedirsən?' hansı cümlə növüdür?", options: ["sual", "nəqli", "nida", "əmr"], correctIndex: 0, xp: 10, explanation: "Cümlədə «hara» sözü ilə sual verilir və sonda sual işarəsi var." },
            { id: "az3-cumle-l1-t6", type: "multiple_choice", prompt: "'Nə gözəldir!' hansı cümlə növüdür?", options: ["nida", "nəqli", "sual", "əmr"], correctIndex: 0, xp: 10, explanation: "Cümlə heyranlıq bildirir və nida işarəsi ilə bitir." },
            { id: "az3-cumle-l1-t7", type: "multiple_choice", prompt: "'Uşaq oxuyur.' — mübtəda hansıdır?", options: ["uşaq", "oxuyur", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "Mübtəda işi görəni bildirir. Burada oxuyan uşaqdır." },
            { id: "az3-cumle-l1-t8", type: "multiple_choice", prompt: "'Uşaq oxuyur.' — xəbər hansıdır?", options: ["oxuyur", "uşaq", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "Xəbər görülən işi bildirir. Burada iş «oxuyur»dur." },
            { id: "az3-cumle-l1-t9", type: "multiple_choice", prompt: "Cümlə hansı hərflə başlayır?", options: ["böyük hərflə", "kiçik hərflə", "rəqəmlə", "fərq etməz"], correctIndex: 0, xp: 10, explanation: "Cümlənin harada başladığı bilinsin deyə ilk hərf böyük yazılır." },
            { id: "az3-cumle-l1-t10", type: "multiple_choice", prompt: "'Quşlar cənuba uçur.' — mübtəda hansıdır?", options: ["quşlar", "cənuba", "uçur", "heç biri"], correctIndex: 0, xp: 10, explanation: "Uçan kimdir? — quşlar. Deməli mübtəda «quşlar»dır." },
            { id: "az3-cumle-l1-t11", type: "multiple_choice", prompt: "Nəqli cümlə hansı işarə ilə bitir?", options: ["nöqtə (.)", "sual işarəsi", "nida işarəsi", "vergül"], correctIndex: 0, xp: 10, explanation: "Nəqli cümlədə fikir bitir, bunu nöqtə göstərir." },
            { id: "az3-cumle-l1-t12", type: "multiple_choice", prompt: "'Bahar gəldi.' — xəbər hansıdır?", options: ["gəldi", "bahar", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "Xəbər görülən işi bildirir. Burada iş «gəldi»dir, «bahar» isə mübtədadır." },
            { id: "az3-cumle-l1-t13", type: "multiple_choice", prompt: "İş görəni bildirən üzv necə adlanır?", options: ["mübtəda", "xəbər", "təyin", "tamamlıq"], correctIndex: 0, xp: 10, explanation: "İşi görəni bildirən baş üzv mübtəda adlanır." },
            { id: "az3-cumle-l1-t14", type: "multiple_choice", prompt: "İşi bildirən üzv necə adlanır?", options: ["xəbər", "mübtəda", "təyin", "tamamlıq"], correctIndex: 0, xp: 10, explanation: "Görülən işi bildirən baş üzv xəbər adlanır." },
            { id: "az3-cumle-l1-t15", type: "multiple_choice", prompt: "'Günəş parlayır.' — xəbər hansıdır?", options: ["parlayır", "günəş", "hər ikisi", "heç biri"], correctIndex: 0, xp: 15, explanation: "Parlayan nədir? — günəş (mübtəda). Gördüyü iş isə «parlayır»dır (xəbər)." },
          ],
          bonusTasks: [
            { id: "az3-cumle-l1-b1", type: "multiple_choice", prompt: "'Mən kitab oxuyuram.' — mübtəda hansıdır?", options: ["mən", "kitab", "oxuyuram", "heç biri"], correctIndex: 0, xp: 15, explanation: "Oxuyan kimdir? — mən. Deməli mübtəda «mən»dir, «kitab» isə tamamlıqdır." },
            { id: "az3-cumle-l1-b2", type: "multiple_choice", prompt: "Mətn nədən ibarətdir?", options: ["cümlələrdən", "yalnız sözlərdən", "hərflərdən", "hecalardan"], correctIndex: 0, xp: 15, explanation: "Mətn mənaca bir-biri ilə bağlı cümlələrdən qurulur." },
            { id: "az3-cumle-l1-b3", type: "multiple_choice", prompt: "'Diqqətli ol!' hansı cümlə növüdür?", options: ["nida/əmr", "nəqli", "sual", "adi"], correctIndex: 0, xp: 15, explanation: "Cümlə əmr, xəbərdarlıq bildirir və nida işarəsi ilə bitir." },
            { id: "az3-cumle-l1-b4", type: "multiple_choice", prompt: "Mətnin adı necə adlanır?", options: ["başlıq", "cümlə", "abzas", "söz"], correctIndex: 0, xp: 15, explanation: "Mətnin nədən bəhs etdiyini qısaca bildirən ad başlıq adlanır." },
            { id: "az3-cumle-l1-b5", type: "multiple_choice", prompt: "'Uşaqlar bağçada oynayır.' — xəbər hansıdır?", options: ["oynayır", "uşaqlar", "bağçada", "heç biri"], correctIndex: 0, xp: 15, explanation: "Oynayan kimdir? — uşaqlar (mübtəda). Gördükləri iş isə «oynayır»dır (xəbər)." },
          ],
        },
        {
          id: "az3-cumle-l2",
          title: "Cümlənin növləri",
          intro: "Cümlə nə məqsədlə deyilir?",
          sections: [
            { heading: "Növlər", body: "NƏQLİ: məlumat verir (Bu gün hava gözəldir.). SUAL: soruşur (Hava necədir?). ƏMR: göstəriş verir (Qapını bağla!). NİDA: hissi bildirir (Nə gözəl gündür!)." },
            { heading: "Durğu işarəsi", body: "Nəqli cümlə nöqtə ilə, sual cümləsi sual işarəsi ilə, əmr və nida cümləsi nida işarəsi ilə bitir." },
          ],
          tasks: [
            { id: "az3-cumle-l2-t1", type: "multiple_choice", prompt: "'Bu gün hava gözəldir.' — hansı cümlədir?", options: ["Nəqli", "Sual", "Əmr", "Nida"], correctIndex: 0, xp: 10, explanation: "Cümlə hava haqqında məlumat verir və nöqtə ilə bitir — deməli nəqlidir." },
            { id: "az3-cumle-l2-t2", type: "multiple_choice", prompt: "'Hava necədir?' — hansı cümlədir?", options: ["Sual", "Nəqli", "Əmr", "Nida"], correctIndex: 0, xp: 10, explanation: "Cümlədə «necə» sözü ilə soruşulur və sonda sual işarəsi var." },
            { id: "az3-cumle-l2-t3", type: "multiple_choice", prompt: "'Qapını bağla!' — hansı cümlədir?", options: ["Əmr", "Sual", "Nəqli", "Nida"], correctIndex: 0, xp: 10, explanation: "Cümlə iş görülməsini tələb edir — deməli əmr cümləsidir." },
            { id: "az3-cumle-l2-t4", type: "multiple_choice", prompt: "'Nə gözəl gündür!' — hansı cümlədir?", options: ["Nida", "Sual", "Nəqli", "Əmr"], correctIndex: 0, xp: 10, explanation: "Cümlə heyranlıq bildirir və nida işarəsi ilə bitir." },
            { id: "az3-cumle-l2-t5", type: "multiple_choice", prompt: "Sual cümləsinin sonunda hansı işarə qoyulur?", options: ["?", "!", ".", ","], correctIndex: 0, xp: 10, explanation: "Sual cümləsində nəsə soruşulur, ona görə sual işarəsi qoyulur." },
            { id: "az3-cumle-l2-t6", type: "multiple_choice", prompt: "Nəqli cümlənin sonunda hansı işarə qoyulur?", options: [".", "?", "!", ";"], correctIndex: 0, xp: 10, explanation: "Nəqli cümlədə fikir bitir, bunu nöqtə göstərir." },
            { id: "az3-cumle-l2-t7", type: "fill_blank", prompt: "Əmr cümləsi ______ işarəsi ilə bitir. (işarəni yaz)", accepted: ["!", "nida"], xp: 10, explanation: "Əmr cümləsi tələb və çağırış bildirir, ona görə nida işarəsi ilə bitir." },
            { id: "az3-cumle-l2-t8", type: "multiple_choice", prompt: "'Kitabı mənə ver.' — hansı cümlədir?", options: ["Əmr", "Sual", "Nida", "Heç biri"], correctIndex: 0, xp: 10, explanation: "Cümlə nəyinsə verilməsini tələb edir — deməli əmr cümləsidir." },
            { id: "az3-cumle-l2-t9", type: "multiple_choice", prompt: "Cümlə hansı hərflə başlayır?", options: ["Böyük", "Kiçik", "Fərqi yoxdur", "Rəqəmlə"], correctIndex: 0, xp: 10, explanation: "Cümlənin harada başladığı bilinsin deyə ilk hərf böyük yazılır." },
            { id: "az3-cumle-l2-t10", type: "multiple_choice", prompt: "'Sən hara gedirsən?' cümləsi hansı növdür?", options: ["Sual", "Nəqli", "Əmr", "Nida"], correctIndex: 0, xp: 10, explanation: "Cümlədə «hara» sözü ilə soruşulur və sonda sual işarəsi var." },
          ],
          bonusTasks: [
            { id: "az3-cumle-l2-b1", type: "multiple_choice", prompt: "Hansı cümlədə durğu işarəsi SƏHVDİR?", options: ["Necəsən.", "Necəsən?", "Yaxşıyam.", "Nə yaxşı!"], correctIndex: 0, xp: 15, explanation: "«Necəsən» sual verir, ona görə sonunda nöqtə yox, sual işarəsi olmalıdır." },
            { id: "az3-cumle-l2-b2", type: "multiple_choice", prompt: "Bir cümlə həm sual, həm nida ola bilərmi?", options: ["Bəli: 'Doğrudanmı?!'", "Xeyr", "Yalnız yazıda", "Yalnız şeirdə"], correctIndex: 0, xp: 15, explanation: "Həm sual, həm güclü təəccüb bildirən cümlədə iki işarə birlikdə yazıla bilər: «Doğrudanmı?!»" },
            { id: "az3-cumle-l2-b3", type: "multiple_choice", prompt: "'Gəl!' cümləsində neçə söz var?", options: ["1", "2", "3", "0"], correctIndex: 0, xp: 15, explanation: "Cümlə tək bir sözdən ibarətdir — «Gəl». Nida işarəsi söz sayılmır." },
            { id: "az3-cumle-l2-b4", type: "multiple_choice", prompt: "Mətn nədir?", options: ["Mənaca bağlı cümlələr toplusu", "Bir cümlə", "Bir söz", "Bir abzas işarəsi"], correctIndex: 0, xp: 15, explanation: "Mətn təsadüfi cümlələr yığını deyil — cümlələr eyni mövzuya bağlı olmalıdır." },
          ],
        },
        {
          id: "az3-cumle-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az3-cumle-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
  ],
};
