// Azərbaycan dili — 1-ci sinif proqramı (savad təlimi, Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Səslər və hərflər  2) Saitlər  3) Samitlər  4) Heca
// 5) Söz və cümlə  6) Oxu və nitq.
// 1-ci sinif üçün suallar ÇOX SADƏ: hərf tanıma, sait/samit, heca sayma. id prefiksi az1-*.

import type { Subject } from "../types";

export const azerbaijani1: Subject = {
  slug: "azerbaycan-dili-1",
  name: "Azərbaycan dili",
  grade: 1,
  icon: "A",
  color: "rose",
  units: [
    // ═══════════════ 1. Səslər və hərflər ═══════════════
    {
      id: "az1-sesler",
      title: "Səslər və hərflər",
      description: "Hərflər, saitlər, samitlər və qalın-incə saitlər.",
      lessons: [
        {
          id: "az1-ses-l1",
          title: "Hərfləri tanı",
          intro: "Sözlərin hansı hərflə başladığını tapaq.",
          sections: [
            { heading: "Səs və hərf", body: "Danışanda səs çıxarırıq, yazanda hərf yazırıq. Azərbaycan əlifbasında 32 hərf var. Hər söz bir hərflə başlayır: 'ana' — a hərfi ilə." },
          ],
          tasks: [
            { id: "az1-ses-l1-t1", type: "multiple_choice", prompt: "'ana' sözü hansı hərflə başlayır?", options: ["a", "n", "l", "m"], correctIndex: 0, xp: 10, explanation: "«ana» sözünü hecalayanda eşitdiyimiz ilk səs a-dır: a-na." },
            { id: "az1-ses-l1-t2", type: "multiple_choice", prompt: "'baba' sözü hansı hərflə başlayır?", options: ["b", "a", "d", "n"], correctIndex: 0, xp: 10, explanation: "«baba» sözünün ilk səsi b-dir: ba-ba." },
            { id: "az1-ses-l1-t3", type: "multiple_choice", prompt: "'kitab' sözü hansı hərflə başlayır?", options: ["k", "t", "b", "a"], correctIndex: 0, xp: 10, explanation: "«kitab» sözü k səsi ilə başlayır: ki-tab." },
            { id: "az1-ses-l1-t4", type: "multiple_choice", prompt: "'su' sözü hansı hərflə başlayır?", options: ["s", "u", "l", "n"], correctIndex: 0, xp: 10, explanation: "«su» sözünün ilk səsi s-dir." },
            { id: "az1-ses-l1-t5", type: "multiple_choice", prompt: "'alma' sözü hansı hərflə başlayır?", options: ["a", "l", "m", "n"], correctIndex: 0, xp: 10, explanation: "«alma» sözünün ilk səsi a-dır: al-ma." },
            { id: "az1-ses-l1-t6", type: "multiple_choice", prompt: "'dovşan' sözü hansı hərflə başlayır?", options: ["d", "o", "v", "ş"], correctIndex: 0, xp: 10, explanation: "«dovşan» sözü d səsi ilə başlayır: dov-şan." },
            { id: "az1-ses-l1-t7", type: "multiple_choice", prompt: "'ev' sözü hansı hərflə başlayır?", options: ["e", "v", "l", "a"], correctIndex: 0, xp: 10, explanation: "«ev» sözünün ilk səsi e-dir." },
            { id: "az1-ses-l1-t8", type: "multiple_choice", prompt: "'top' sözü hansı hərflə başlayır?", options: ["t", "o", "p", "s"], correctIndex: 0, xp: 10, explanation: "«top» sözü t səsi ilə başlayır." },
            { id: "az1-ses-l1-t9", type: "multiple_choice", prompt: "'ana' sözü hansı hərflə bitir?", options: ["a", "n", "m", "l"], correctIndex: 0, xp: 10, explanation: "«ana» sözünü sona qədər deyirik: a-n-a. Son səs a-dır." },
            { id: "az1-ses-l1-t10", type: "multiple_choice", prompt: "'kitab' sözü hansı hərflə bitir?", options: ["b", "k", "t", "a"], correctIndex: 0, xp: 10, explanation: "«kitab» sözünün son səsi b-dir: ki-tab." },
            { id: "az1-ses-l1-t11", type: "multiple_choice", prompt: "'top' sözü hansı hərflə bitir?", options: ["p", "t", "o", "s"], correctIndex: 0, xp: 10, explanation: "«top» sözünün son səsi p-dir: to-p." },
            { id: "az1-ses-l1-t12", type: "fill_blank", prompt: "'nar' sözünün ilk hərfini yaz.", accepted: ["n", "N"], xp: 10, explanation: "«nar» sözünün ilk səsi n-dir, ona görə ilk hərf n yazılır." },
            { id: "az1-ses-l1-t13", type: "fill_blank", prompt: "'gül' sözünün ilk hərfini yaz.", accepted: ["g", "G"], xp: 10, explanation: "«gül» sözünün ilk səsi g-dir, ona görə ilk hərf g yazılır." },
            { id: "az1-ses-l1-t14", type: "numeric", prompt: "Azərbaycan əlifbasında neçə hərf var?", answer: 32, xp: 10, explanation: "Əlifbada 9 sait və 23 samit var: 9 + 23 = 32 hərf." },
            { id: "az1-ses-l1-t15", type: "multiple_choice", prompt: "'göl' sözü hansı hərflə başlayır?", options: ["g", "ö", "l", "k"], correctIndex: 0, xp: 15, explanation: "«göl» sözünün ilk səsi g-dir." },
          ],
          bonusTasks: [
            { id: "az1-ses-l1-b1", type: "fill_blank", prompt: "'armud' sözünün ilk hərfini yaz.", accepted: ["a", "A"], xp: 15, explanation: "«armud» sözünün ilk səsi a-dır: ar-mud." },
            { id: "az1-ses-l1-b2", type: "multiple_choice", prompt: "'quş' sözü hansı hərflə bitir?", options: ["ş", "q", "u", "s"], correctIndex: 0, xp: 15, explanation: "«quş» sözünün son səsi ş-dir: qu-ş." },
            { id: "az1-ses-l1-b3", type: "fill_blank", prompt: "'balıq' sözünün son hərfini yaz.", accepted: ["q", "Q"], xp: 15, explanation: "«balıq» sözünün son səsi q-dır: ba-lıq." },
            { id: "az1-ses-l1-b4", type: "multiple_choice", prompt: "'çiçək' sözü hansı hərflə başlayır?", options: ["ç", "i", "t", "k"], correctIndex: 0, xp: 15, explanation: "«çiçək» sözü ç səsi ilə başlayır: çi-çək." },
            { id: "az1-ses-l1-b5", type: "multiple_choice", prompt: "Danışanda nə çıxarırıq?", options: ["səs", "hərf", "söz", "cümlə"], correctIndex: 0, xp: 15, explanation: "Danışanda ağzımızdan səs çıxır. Hərf isə həmin səsin yazıdakı işarəsidir." },
          ],
        },
        {
          id: "az1-sait-l1",
          title: "Saitləri tanı",
          intro: "Saitlər asanlıqla, maneəsiz deyilən səslərdir.",
          sections: [
            { heading: "Saitlər", body: "Azərbaycan dilində 9 sait var: a, e, ə, ı, i, o, ö, u, ü. Saitləri deyəndə ağızda maneə olmur, ağzımızı aça bilirik." },
          ],
          tasks: [
            { id: "az1-sait-l1-t1", type: "numeric", prompt: "Azərbaycan dilində neçə sait var?", answer: 9, xp: 10, explanation: "Saitlər: a, e, ə, ı, i, o, ö, u, ü — cəmi 9 dənədir." },
            { id: "az1-sait-l1-t2", type: "multiple_choice", prompt: "Aşağıdakılardan hansı saitdir?", options: ["a", "b", "k", "m"], correctIndex: 0, xp: 10, explanation: "«a» saitdir — onu uzada bilirik: aaa. b, k, m isə samitdir." },
            { id: "az1-sait-l1-t3", type: "multiple_choice", prompt: "Aşağıdakılardan hansı saitdir?", options: ["e", "d", "n", "s"], correctIndex: 0, xp: 10, explanation: "«e» saitdir; n, d, s samitdir." },
            { id: "az1-sait-l1-t4", type: "multiple_choice", prompt: "Aşağıdakılardan hansı saitdir?", options: ["ə", "t", "l", "r"], correctIndex: 0, xp: 10, explanation: "«ə» saitdir; l, r, t samitdir." },
            { id: "az1-sait-l1-t5", type: "multiple_choice", prompt: "Aşağıdakılardan hansı saitdir?", options: ["o", "p", "ş", "ç"], correctIndex: 0, xp: 10, explanation: "«o» saitdir; p, ç, ş samitdir." },
            { id: "az1-sait-l1-t6", type: "multiple_choice", prompt: "Aşağıdakılardan hansı saitdir?", options: ["u", "v", "z", "g"], correctIndex: 0, xp: 10, explanation: "«u» saitdir; v, z, g samitdir." },
            { id: "az1-sait-l1-t7", type: "multiple_choice", prompt: "Aşağıdakılardan hansı sait DEYİL?", options: ["b", "a", "e", "o"], correctIndex: 0, xp: 10, explanation: "e, o, a saitdir. «b»-ni deyəndə dodaqlar birləşir, hava maneəyə rast gəlir — deməli samitdir." },
            { id: "az1-sait-l1-t8", type: "multiple_choice", prompt: "Aşağıdakılardan hansı sait DEYİL?", options: ["k", "i", "u", "ə"], correctIndex: 0, xp: 10, explanation: "u, ə, i saitdir. «k» isə samitdir." },
            { id: "az1-sait-l1-t9", type: "multiple_choice", prompt: "'ana' sözündə neçə sait var? (a, a)", options: ["2", "1", "3", "0"], correctIndex: 0, xp: 10, explanation: "«ana» sözündə a iki dəfə gəlir: a-n-a. Deməli 2 sait var." },
            { id: "az1-sait-l1-t10", type: "multiple_choice", prompt: "'top' sözündə hansı saitdir?", options: ["o", "t", "p", "heç biri"], correctIndex: 0, xp: 10, explanation: "«top» sözünün ortasındakı o saitdir; t və p samitdir." },
            { id: "az1-sait-l1-t11", type: "multiple_choice", prompt: "'ev' sözündə hansı saitdir?", options: ["e", "v", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«ev» sözündə e saitdir; v samitdir." },
            { id: "az1-sait-l1-t12", type: "multiple_choice", prompt: "Aşağıdakılardan hansı saitdir?", options: ["ö", "s", "n", "d"], correctIndex: 0, xp: 10, explanation: "«ö» saitdir; s, n, d samitdir." },
            { id: "az1-sait-l1-t13", type: "multiple_choice", prompt: "Aşağıdakılardan hansı saitdir?", options: ["ü", "y", "q", "x"], correctIndex: 0, xp: 10, explanation: "«ü» saitdir; y, x, q samitdir." },
            { id: "az1-sait-l1-t14", type: "multiple_choice", prompt: "Aşağıdakılardan hansı saitdir?", options: ["ı", "l", "m", "r"], correctIndex: 0, xp: 10, explanation: "«ı» saitdir; l, r, m samitdir." },
            { id: "az1-sait-l1-t15", type: "multiple_choice", prompt: "'su' sözündə hansı saitdir?", options: ["u", "s", "hər ikisi", "heç biri"], correctIndex: 0, xp: 15, explanation: "«su» sözündə u saitdir; s samitdir." },
          ],
          bonusTasks: [
            { id: "az1-sait-l1-b1", type: "multiple_choice", prompt: "'alma' sözündə neçə sait var? (a, a)", options: ["2", "1", "3", "4"], correctIndex: 0, xp: 15, explanation: "«alma» sözündə a iki dəfə gəlir: a-l-m-a. Deməli 2 sait var." },
            { id: "az1-sait-l1-b2", type: "multiple_choice", prompt: "'kitab' sözündə neçə sait var? (i, a)", options: ["2", "1", "3", "4"], correctIndex: 0, xp: 15, explanation: "«kitab» sözündə i və a saitdir: k-i-t-a-b. Deməli 2 sait var." },
            { id: "az1-sait-l1-b3", type: "multiple_choice", prompt: "Saitləri deyəndə ağızda nə olur?", options: ["maneə olmur", "maneə olur", "səs çıxmır", "hərf yazılır"], correctIndex: 0, xp: 15, explanation: "Saiti deyəndə hava ağızdan sərbəst çıxır, dil və dodaq onu kəsmir. Ona görə saitləri uzada bilirik: aaaa." },
            { id: "az1-sait-l1-b4", type: "multiple_choice", prompt: "Hansı sırada yalnız saitlər var?", options: ["a, e, o", "a, b, c", "k, l, m", "s, t, r"], correctIndex: 0, xp: 15, explanation: "a, e, o — üçü də saitdir. Digər sıralarda samitlər qarışıb." },
            { id: "az1-sait-l1-b5", type: "multiple_choice", prompt: "'göl' sözündə hansı saitdir?", options: ["ö", "g", "l", "heç biri"], correctIndex: 0, xp: 15, explanation: "«göl» sözündə ö saitdir; g və l samitdir." },
          ],
        },
        {
          id: "az1-samit-l1",
          title: "Samitləri tanı",
          intro: "Samitlər deyilərkən ağızda maneə olan səslərdir.",
          sections: [
            { heading: "Samitlər", body: "Azərbaycan dilində 23 samit var: b, c, ç, d, f, g, ğ, h, x, j, k, q, l, m, n, p, r, s, ş, t, v, y, z. Samitləri deyəndə dil, dodaq və ya dişlər maneə yaradır." },
          ],
          tasks: [
            { id: "az1-samit-l1-t1", type: "numeric", prompt: "Azərbaycan dilində neçə samit var?", answer: 23, xp: 10, explanation: "Əlifbadakı 32 hərfin 9-u saitdir, qalanı samit: 32 − 9 = 23." },
            { id: "az1-samit-l1-t2", type: "multiple_choice", prompt: "Aşağıdakılardan hansı samitdir?", options: ["b", "a", "e", "o"], correctIndex: 0, xp: 10, explanation: "«b» samitdir; e, a, o saitdir." },
            { id: "az1-samit-l1-t3", type: "multiple_choice", prompt: "Aşağıdakılardan hansı samitdir?", options: ["k", "i", "u", "ə"], correctIndex: 0, xp: 10, explanation: "«k» samitdir; i, u, ə saitdir." },
            { id: "az1-samit-l1-t4", type: "multiple_choice", prompt: "Aşağıdakılardan hansı samitdir?", options: ["m", "a", "o", "ü"], correctIndex: 0, xp: 10, explanation: "«m» samitdir; ü, a, o saitdir." },
            { id: "az1-samit-l1-t5", type: "multiple_choice", prompt: "Aşağıdakılardan hansı samitdir?", options: ["s", "e", "ı", "i"], correctIndex: 0, xp: 10, explanation: "«s» samitdir; e, ı, i saitdir." },
            { id: "az1-samit-l1-t6", type: "multiple_choice", prompt: "Aşağıdakılardan hansı samit DEYİL?", options: ["a", "b", "k", "s"], correctIndex: 0, xp: 10, explanation: "s, k, b samitdir. «a» isə saitdir — deyəndə hava sərbəst çıxır." },
            { id: "az1-samit-l1-t7", type: "multiple_choice", prompt: "Aşağıdakılardan hansı samit DEYİL?", options: ["o", "d", "n", "t"], correctIndex: 0, xp: 10, explanation: "n, d, t samitdir. «o» isə saitdir." },
            { id: "az1-samit-l1-t8", type: "multiple_choice", prompt: "'top' sözündə hansı samitdir?", options: ["t", "o", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«top» sözündə o saitdir, t isə samitdir." },
            { id: "az1-samit-l1-t9", type: "multiple_choice", prompt: "'nar' sözündə neçə samit var? (n, r)", options: ["2", "1", "3", "0"], correctIndex: 0, xp: 10, explanation: "«nar» sözündə n və r samitdir, a saitdir. Deməli 2 samit var." },
            { id: "az1-samit-l1-t10", type: "multiple_choice", prompt: "Aşağıdakılardan hansı samitdir?", options: ["r", "a", "e", "u"], correctIndex: 0, xp: 10, explanation: "«r» samitdir; u, e, a saitdir." },
            { id: "az1-samit-l1-t11", type: "multiple_choice", prompt: "Aşağıdakılardan hansı samitdir?", options: ["l", "i", "o", "ə"], correctIndex: 0, xp: 10, explanation: "«l» samitdir; o, ə, i saitdir." },
            { id: "az1-samit-l1-t12", type: "multiple_choice", prompt: "Samitləri deyəndə ağızda nə olur?", options: ["maneə olur", "maneə olmur", "səs çıxmır", "heç nə"], correctIndex: 0, xp: 10, explanation: "Samiti deyəndə hava dilə, dişə və ya dodağa toxunur — maneəyə rast gəlir. Ona görə samiti sait kimi uzada bilmirik." },
            { id: "az1-samit-l1-t13", type: "multiple_choice", prompt: "Hansı sırada yalnız samitlər var?", options: ["b, k, s", "a, e, o", "i, u, ü", "a, b, e"], correctIndex: 0, xp: 10, explanation: "b, k, s — üçü də samitdir. Digər sıralarda saitlər qarışıb." },
            { id: "az1-samit-l1-t14", type: "multiple_choice", prompt: "'su' sözündə hansı samitdir?", options: ["s", "u", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«su» sözündə s samitdir, u saitdir." },
            { id: "az1-samit-l1-t15", type: "multiple_choice", prompt: "'kitab' sözündə neçə samit var? (k, t, b)", options: ["3", "2", "4", "1"], correctIndex: 0, xp: 15, explanation: "«kitab» sözündə k, t, b samitdir — 3 dənə. i və a isə saitdir." },
          ],
          bonusTasks: [
            { id: "az1-samit-l1-b1", type: "multiple_choice", prompt: "'alma' sözündə neçə samit var? (l, m)", options: ["2", "1", "3", "4"], correctIndex: 0, xp: 15, explanation: "«alma» sözündə l və m samitdir — 2 dənə. İki a isə saitdir." },
            { id: "az1-samit-l1-b2", type: "multiple_choice", prompt: "Sait və samit birlikdə nəyi əmələ gətirir?", options: ["hecanı/sözü", "cümləni yalnız", "mətni", "səhifəni"], correctIndex: 0, xp: 15, explanation: "Tək samit heca düzəltmir. Sait ona qoşulanda heca alınır: k + a = ka. Hecalardan da söz yaranır." },
            { id: "az1-samit-l1-b3", type: "multiple_choice", prompt: "Aşağıdakılardan hansı samitdir?", options: ["ş", "a", "o", "u"], correctIndex: 0, xp: 15, explanation: "«ş» samitdir; o, u, a saitdir." },
            { id: "az1-samit-l1-b4", type: "multiple_choice", prompt: "9 sait + 23 samit = neçə hərf?", options: ["32", "30", "31", "33"], correctIndex: 0, xp: 15, explanation: "9 + 23 = 32. Azərbaycan əlifbasında bu qədər hərf var." },
            { id: "az1-samit-l1-b5", type: "multiple_choice", prompt: "'göl' sözündə neçə samit var? (g, l)", options: ["2", "1", "3", "0"], correctIndex: 0, xp: 15, explanation: "«göl» sözündə g və l samitdir — 2 dənə. ö isə saitdir." },
          ],
        },
        {
          id: "az1-ses-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az1-qalinince-l1",
          title: "Qalın və incə saitlər",
          intro: "Saitlər iki qrupa ayrılır: qalın və incə.",
          sections: [
            { heading: "İki qrup", body: "Qalın saitlər: a, ı, o, u. İncə saitlər: e, ə, i, ö, ü. Sait 9-dur: 4 qalın, 5 incə." },
          ],
          tasks: [
            { id: "az1-qalinince-l1-t1", type: "multiple_choice", prompt: "Hansı sırada yalnız QALIN saitlər var?", options: ["e, ə, i", "a, ı, o", "ö, ü, e", "i, ö, ü"], correctIndex: 1, xp: 10, explanation: "Qalın saitlər: a, ı, o, u. Bu sırada üçü də həmin qrupdandır." },
            { id: "az1-qalinince-l1-t2", type: "multiple_choice", prompt: "Hansı sırada yalnız İNCƏ saitlər var?", options: ["a, o, u", "ı, a, o", "e, ə, i", "a, ı, u"], correctIndex: 2, xp: 10, explanation: "İncə saitlər: e, ə, i, ö, ü. Bu sırada üçü də həmin qrupdandır." },
            { id: "az1-qalinince-l1-t3", type: "multiple_choice", prompt: "'a' saiti hansı qrupdandır?", options: ["incə", "qalın", "samit", "heç biri"], correctIndex: 1, xp: 10, explanation: "«a» qalın saitlərdəndir: a, ı, o, u." },
            { id: "az1-qalinince-l1-t4", type: "multiple_choice", prompt: "'ə' saiti hansı qrupdandır?", options: ["qalın", "samit", "incə", "heç biri"], correctIndex: 2, xp: 10, explanation: "«ə» incə saitlərdəndir: e, ə, i, ö, ü." },
            { id: "az1-qalinince-l1-t5", type: "multiple_choice", prompt: "'o' saiti hansı qrupdandır?", options: ["qalın", "incə", "samit", "rəqəm"], correctIndex: 0, xp: 10, explanation: "«o» qalın saitlərdəndir: a, ı, o, u." },
            { id: "az1-qalinince-l1-t6", type: "multiple_choice", prompt: "'ü' saiti hansı qrupdandır?", options: ["qalın", "incə", "samit", "heç biri"], correctIndex: 1, xp: 10, explanation: "«ü» incə saitlərdəndir: e, ə, i, ö, ü." },
            { id: "az1-qalinince-l1-t7", type: "numeric", prompt: "Neçə qalın sait var?", answer: 4, xp: 10, explanation: "Qalın saitləri sayaq: a, ı, o, u — 4 dənə." },
            { id: "az1-qalinince-l1-t8", type: "numeric", prompt: "Neçə incə sait var?", answer: 5, xp: 10, explanation: "İncə saitləri sayaq: e, ə, i, ö, ü — 5 dənə." },
            { id: "az1-qalinince-l1-t9", type: "multiple_choice", prompt: "'alma' sözündəki saitlər (a, a) hansı qrupdandır?", options: ["incə", "qalın", "qarışıq", "samit"], correctIndex: 1, xp: 10, explanation: "«alma» sözündə hər iki sait a-dır, a isə qalın saitdir." },
            { id: "az1-qalinince-l1-t10", type: "multiple_choice", prompt: "'çiçək' sözündəki saitlər (i, ə) hansı qrupdandır?", options: ["qalın", "incə", "samit", "rəqəm"], correctIndex: 1, xp: 10, explanation: "«çiçək» sözündə i və ə var; hər ikisi incə saitdir." },
          ],
          bonusTasks: [
            { id: "az1-qalinince-l1-b1", type: "multiple_choice", prompt: "'oxu' sözündəki saitlər (o, u) hansı qrupdandır?", options: ["qalın", "incə", "qarışıq", "yoxdur"], correctIndex: 0, xp: 15, explanation: "«oxu» sözündə o və u var; hər ikisi qalın saitdir." },
            { id: "az1-qalinince-l1-b2", type: "multiple_choice", prompt: "Hansı söz yalnız incə saitlidir?", options: ["ana", "qapı", "sevgi", "araba"], correctIndex: 2, xp: 15, explanation: "«sevgi» sözündə e və i var — ikisi də incədir. Digər sözlərdə a, ı kimi qalın saitlər işlənib." },
            { id: "az1-qalinince-l1-b3", type: "numeric", prompt: "Cəmi neçə sait var?", answer: 9, xp: 15, explanation: "4 qalın + 5 incə = 9 sait." },
            { id: "az1-qalinince-l1-b4", type: "multiple_choice", prompt: "'ı' saiti hansı qrupdandır?", options: ["incə", "samit", "qalın", "heç biri"], correctIndex: 2, xp: 15, explanation: "«ı» qalın saitlərdəndir: a, ı, o, u." },
          ],
        },
        {
          id: "az1-ses-mesq",
          title: "Məşq",
          intro: "Öyrəndiyin hərfləri və səsləri məşq edək!",
          sections: [
            { heading: "Yadına salaq", body: "Sait səslər: a, e, ə, ı, i, o, ö, u, ü. Qalanları samitdir. Qalın saitlər: a, ı, o, u. İncə saitlər: e, ə, i, ö, ü." },
          ],
          tasks: [
            { id: "az1-ses-mesq-t1", type: "multiple_choice", prompt: "'ilan' sözü hansı hərflə başlayır?", options: ["i", "l", "a", "n"], correctIndex: 0, xp: 10, explanation: "«ilan» sözünün ilk səsi i-dir: i-lan." },
            { id: "az1-ses-mesq-t2", type: "multiple_choice", prompt: "'göy' sözündə neçə sait var?", options: ["1", "2", "3", "0"], correctIndex: 0, xp: 10, explanation: "«göy» sözündə yalnız ö saitdir; g və y samitdir. Deməli 1 sait var." },
            { id: "az1-ses-mesq-t3", type: "multiple_choice", prompt: "Hansı saitdir?", options: ["ö", "k", "m", "t"], correctIndex: 0, xp: 10, explanation: "«ö» saitdir; t, k, m samitdir." },
            { id: "az1-ses-mesq-t4", type: "multiple_choice", prompt: "Hansı samitdir?", options: ["s", "a", "ü", "e"], correctIndex: 0, xp: 10, explanation: "«s» samitdir; a, ü, e saitdir." },
            { id: "az1-ses-mesq-t5", type: "multiple_choice", prompt: "'quş' sözündəki sait hansıdır?", options: ["u", "q", "ş", "heç biri"], correctIndex: 0, xp: 10, explanation: "«quş» sözündə u saitdir; q və ş samitdir." },
            { id: "az1-ses-mesq-t6", type: "multiple_choice", prompt: "'ev' sözündəki sait qalındır, yoxsa incə?", options: ["incə", "qalın", "hər ikisi", "sait yoxdur"], correctIndex: 0, xp: 10, explanation: "«ev» sözündəki sait e-dir, e isə incə saitdir." },
            { id: "az1-ses-mesq-t7", type: "multiple_choice", prompt: "'at' sözündəki sait qalındır, yoxsa incə?", options: ["qalın", "incə", "hər ikisi", "sait yoxdur"], correctIndex: 0, xp: 10, explanation: "«at» sözündəki sait a-dır, a isə qalın saitdir." },
            { id: "az1-ses-mesq-t8", type: "numeric", prompt: "Azərbaycan dilində neçə sait var?", answer: 9, xp: 10, explanation: "Saitlər: a, e, ə, ı, i, o, ö, u, ü — cəmi 9." },
            { id: "az1-ses-mesq-t9", type: "multiple_choice", prompt: "'top' sözü hansı hərflə bitir?", options: ["p", "t", "o", "heç biri"], correctIndex: 0, xp: 10, explanation: "«top» sözünün son səsi p-dir: to-p." },
            { id: "az1-ses-mesq-t10", type: "multiple_choice", prompt: "Hansı sözdə 'ə' hərfi var?", options: ["əl", "at", "top", "quş"], correctIndex: 0, xp: 10, explanation: "«əl» sözü məhz ə hərfi ilə başlayır. Top, at və quş sözlərində ə yoxdur." },
          ],
          bonusTasks: [
            { id: "az1-ses-mesq-b1", type: "multiple_choice", prompt: "Hansı sırada yalnız saitlər var?", options: ["a, e, i", "a, b, c", "k, l, m", "s, t, u"], correctIndex: 0, xp: 15, explanation: "a, e, i — üçü də saitdir." },
            { id: "az1-ses-mesq-b2", type: "numeric", prompt: "'ana' sözündə neçə hərf var?", answer: 3, xp: 15, explanation: "«ana» sözünü hərf-hərf sayaq: a, n, a — 3 hərf." },
            { id: "az1-ses-mesq-b3", type: "multiple_choice", prompt: "'ördək' sözü hansı saitlə başlayır?", options: ["ö", "r", "d", "ə"], correctIndex: 0, xp: 15, explanation: "«ördək» sözünün ilk səsi ö-dür, ö isə saitdir." },
            { id: "az1-ses-mesq-b4", type: "multiple_choice", prompt: "Hansı sözdə qalın sait var?", options: ["qar", "bel", "gül", "üzüm"], correctIndex: 0, xp: 15, explanation: "«qar» sözündə a var, a isə qalın saitdir. Bel, gül, üzüm sözlərində incə saitlər var." },
            { id: "az1-ses-mesq-b5", type: "numeric", prompt: "'kitab' sözündə neçə sait var?", answer: 2, xp: 15, explanation: "«kitab» sözündə i və a saitdir — 2 dənə." },
          ],
        },
        {
          id: "az1-ses-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    {
      id: "az1-sozler",
      title: "Söz, heca və cümlə",
      description: "Sözü hecalara bölmək, söz və cümlə qurmaq.",
      lessons: [
        {
          id: "az1-heca-l1",
          title: "Sözü hecalara böl",
          intro: "Söz neçə saitdən ibarətdirsə, o qədər hecası var.",
          sections: [
            { heading: "Heca", body: "Sözü tələffüz edəndə hissə-hissə deyirik: a-na (2 heca), ki-tab (2 heca), al-ma (2 heca). Qayda: sözdə neçə sait varsa, o qədər heca var." },
          ],
          tasks: [
            { id: "az1-heca-l1-t1", type: "numeric", prompt: "'ana' sözündə neçə heca var? (a-na)", answer: 2, xp: 10, explanation: "«ana» sözündə iki sait var (a, a), ona görə iki heca alınır: a-na." },
            { id: "az1-heca-l1-t2", type: "numeric", prompt: "'kitab' sözündə neçə heca var? (ki-tab)", answer: 2, xp: 10, explanation: "«kitab» sözündə iki sait var (i, a), ona görə iki heca alınır: ki-tab." },
            { id: "az1-heca-l1-t3", type: "numeric", prompt: "'alma' sözündə neçə heca var? (al-ma)", answer: 2, xp: 10, explanation: "«alma» sözündə iki sait var (a, a), ona görə iki heca alınır: al-ma." },
            { id: "az1-heca-l1-t4", type: "numeric", prompt: "'su' sözündə neçə heca var? (su)", answer: 1, xp: 10, explanation: "«su» sözündə tək bir sait var (u), ona görə sözü bölmək olmur: su — 1 heca." },
            { id: "az1-heca-l1-t5", type: "numeric", prompt: "'top' sözündə neçə heca var? (top)", answer: 1, xp: 10, explanation: "«top» sözündə tək bir sait var (o), ona görə 1 heca: top." },
            { id: "az1-heca-l1-t6", type: "numeric", prompt: "'ev' sözündə neçə heca var? (ev)", answer: 1, xp: 10, explanation: "«ev» sözündə tək bir sait var (e), ona görə 1 heca: ev." },
            { id: "az1-heca-l1-t7", type: "numeric", prompt: "'məktəb' sözündə neçə heca var? (mək-təb)", answer: 2, xp: 10, explanation: "«məktəb» sözündə iki sait var (ə, ə), ona görə iki heca: mək-təb." },
            { id: "az1-heca-l1-t8", type: "numeric", prompt: "'balaca' sözündə neçə heca var? (ba-la-ca)", answer: 3, xp: 10, explanation: "«balaca» sözündə üç sait var (a, a, a), ona görə üç heca: ba-la-ca." },
            { id: "az1-heca-l1-t9", type: "numeric", prompt: "'dovşan' sözündə neçə heca var? (dov-şan)", answer: 2, xp: 10, explanation: "«dovşan» sözündə iki sait var (o, a), ona görə iki heca: dov-şan." },
            { id: "az1-heca-l1-t10", type: "numeric", prompt: "'armud' sözündə neçə heca var? (ar-mud)", answer: 2, xp: 10, explanation: "«armud» sözündə iki sait var (a, u), ona görə iki heca: ar-mud." },
            { id: "az1-heca-l1-t11", type: "numeric", prompt: "'nar' sözündə neçə heca var? (nar)", answer: 1, xp: 10, explanation: "«nar» sözündə tək bir sait var (a), ona görə 1 heca: nar." },
            { id: "az1-heca-l1-t12", type: "numeric", prompt: "'ata' sözündə neçə heca var? (a-ta)", answer: 2, xp: 10, explanation: "«ata» sözündə iki sait var (a, a), ona görə iki heca: a-ta." },
            { id: "az1-heca-l1-t13", type: "numeric", prompt: "'qələm' sözündə neçə heca var? (qə-ləm)", answer: 2, xp: 10, explanation: "«qələm» sözündə iki sait var (ə, ə), ona görə iki heca: qə-ləm." },
            { id: "az1-heca-l1-t14", type: "multiple_choice", prompt: "Sözdə heca sayını nə göstərir?", options: ["saitlərin sayı", "samitlərin sayı", "hərflərin sayı", "sözlərin sayı"], correctIndex: 0, xp: 10, explanation: "Hər hecada mütləq bir sait olur. Ona görə sözdəki saitləri saymaqla heca sayını tapırıq." },
            { id: "az1-heca-l1-t15", type: "numeric", prompt: "'kitabxana' sözündə neçə heca var? (ki-tab-xa-na)", answer: 4, xp: 15, explanation: "«kitabxana» sözündə dörd sait var (i, a, a, a), ona görə dörd heca: ki-tab-xa-na." },
          ],
          bonusTasks: [
            { id: "az1-heca-l1-b1", type: "numeric", prompt: "'ayaqqabı' sözündə neçə heca var? (a-yaq-qa-bı)", answer: 4, xp: 15, explanation: "«ayaqqabı» sözündə dörd sait var (a, a, a, ı), ona görə dörd heca: a-yaq-qa-bı." },
            { id: "az1-heca-l1-b2", type: "numeric", prompt: "'məktəbli' sözündə neçə heca var? (mək-təb-li)", answer: 3, xp: 15, explanation: "«məktəbli» sözündə üç sait var (ə, ə, i), ona görə üç heca: mək-təb-li." },
            { id: "az1-heca-l1-b3", type: "multiple_choice", prompt: "'gül' sözü neçə hecadan ibarətdir?", options: ["1", "2", "3", "0"], correctIndex: 0, xp: 15, explanation: "«gül» sözündə tək bir sait var (ü), ona görə 1 heca." },
            { id: "az1-heca-l1-b4", type: "numeric", prompt: "'baba' sözündə neçə heca var? (ba-ba)", answer: 2, xp: 15, explanation: "«baba» sözündə iki sait var (a, a), ona görə iki heca: ba-ba." },
            { id: "az1-heca-l1-b5", type: "numeric", prompt: "'təbiət' sözündə neçə heca var? (tə-bi-ət)", answer: 3, xp: 15, explanation: "«təbiət» sözündə üç sait var (ə, i, ə), ona görə üç heca: tə-bi-ət." },
          ],
        },
        {
          id: "az1-soz-l1",
          title: "Söz və cümlə",
          intro: "Sözlər birləşib cümlə əmələ gətirir.",
          sections: [
            { heading: "Cümlə", body: "Bitmiş fikir bildirən sözlər qrupu cümlədir: 'Ana gəldi.' Cümlə böyük hərflə başlayır və nöqtə ilə bitir." },
          ],
          tasks: [
            { id: "az1-soz-l1-t1", type: "multiple_choice", prompt: "Cümlə hansı hərflə başlayır?", options: ["böyük hərflə", "kiçik hərflə", "rəqəmlə", "nöqtə ilə"], correctIndex: 0, xp: 10, explanation: "Cümlənin başladığını göstərmək üçün ilk sözün ilk hərfi böyük yazılır." },
            { id: "az1-soz-l1-t2", type: "multiple_choice", prompt: "Nəqli cümlə hansı işarə ilə bitir?", options: ["nöqtə (.)", "vergül (,)", "sual işarəsi (?)", "heç bir"], correctIndex: 0, xp: 10, explanation: "Nəqli cümlə nəyisə xəbər verir və fikir bitəndə nöqtə qoyulur." },
            { id: "az1-soz-l1-t3", type: "multiple_choice", prompt: "'Ana gəldi.' neçə sözdən ibarətdir?", options: ["2", "1", "3", "4"], correctIndex: 0, xp: 10, explanation: "Sözləri sayaq: «Ana» və «gəldi» — 2 söz." },
            { id: "az1-soz-l1-t4", type: "multiple_choice", prompt: "'Uşaq oynayır.' neçə sözdən ibarətdir?", options: ["2", "1", "3", "4"], correctIndex: 0, xp: 10, explanation: "Sözləri sayaq: «Uşaq» və «oynayır» — 2 söz." },
            { id: "az1-soz-l1-t5", type: "multiple_choice", prompt: "Bitmiş fikir bildirən sözlər qrupu nədir?", options: ["cümlə", "heca", "hərf", "səs"], correctIndex: 0, xp: 10, explanation: "Sözlər birləşib tam, bitmiş fikir bildirəndə cümlə alınır." },
            { id: "az1-soz-l1-t6", type: "multiple_choice", prompt: "'ana' — bu nədir?", options: ["söz", "cümlə", "heca", "mətn"], correctIndex: 0, xp: 10, explanation: "«ana» tək başına bir mənanı bildirir, amma bitmiş fikir deyil — deməli sözdür." },
            { id: "az1-soz-l1-t7", type: "multiple_choice", prompt: "'Quşlar uçur.' — bu nədir?", options: ["cümlə", "söz", "heca", "hərf"], correctIndex: 0, xp: 10, explanation: "«Quşlar uçur.» bitmiş fikir bildirir, böyük hərflə başlayıb nöqtə ilə bitir — deməli cümlədir." },
            { id: "az1-soz-l1-t8", type: "multiple_choice", prompt: "İnsan adları hansı hərflə başlayır?", options: ["böyük hərflə", "kiçik hərflə", "rəqəmlə", "fərq etməz"], correctIndex: 0, xp: 10, explanation: "İnsan adları xüsusi addır, ona görə həmişə böyük hərflə yazılır." },
            { id: "az1-soz-l1-t9", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["Ayşə", "ayşə", "AYŞə", "ayŞə"], correctIndex: 0, xp: 10, explanation: "İnsan adında yalnız ilk hərf böyük, qalanları kiçik yazılır: Ayşə." },
            { id: "az1-soz-l1-t10", type: "multiple_choice", prompt: "'Bahar gəldi.' cümləsi hansı işarə ilə bitir?", options: ["nöqtə", "vergül", "sual", "nida"], correctIndex: 0, xp: 10, explanation: "«Bahar gəldi.» nəyisə xəbər verir, sual vermir — ona görə sonunda nöqtə var." },
            { id: "az1-soz-l1-t11", type: "multiple_choice", prompt: "'Gül açdı.' neçə sözdən ibarətdir?", options: ["2", "1", "3", "4"], correctIndex: 0, xp: 10, explanation: "Sözləri sayaq: «Gül» və «açdı» — 2 söz." },
            { id: "az1-soz-l1-t12", type: "multiple_choice", prompt: "Sözlər birləşəndə nə əmələ gəlir?", options: ["cümlə", "hərf", "səs", "heca"], correctIndex: 0, xp: 10, explanation: "Sözlər yan-yana düzülüb bitmiş fikir bildirəndə cümlə yaranır." },
            { id: "az1-soz-l1-t13", type: "multiple_choice", prompt: "Sual cümləsi hansı işarə ilə bitir?", options: ["sual işarəsi (?)", "nöqtə (.)", "vergül (,)", "heç bir"], correctIndex: 0, xp: 10, explanation: "Sual cümləsində nəsə soruşulur, ona görə sonunda sual işarəsi qoyulur." },
            { id: "az1-soz-l1-t14", type: "multiple_choice", prompt: "Hansı düzgün cümlədir?", options: ["Uşaq gülür.", "uşaq gülür", "Uşaq gülür", "uşaq Gülür."], correctIndex: 0, xp: 10, explanation: "«Uşaq gülür.» — həm böyük hərflə başlayır, həm də nöqtə ilə bitir. Digər variantlarda biri çatmır." },
            { id: "az1-soz-l1-t15", type: "multiple_choice", prompt: "'Mən məktəbə gedirəm.' neçə sözdən ibarətdir?", options: ["3", "2", "4", "1"], correctIndex: 0, xp: 15, explanation: "Sözləri sayaq: «Mən», «məktəbə», «gedirəm» — 3 söz." },
          ],
          bonusTasks: [
            { id: "az1-soz-l1-b1", type: "multiple_choice", prompt: "Şəhər adları necə yazılır?", options: ["böyük hərflə", "kiçik hərflə", "rəqəmlə", "fərq etməz"], correctIndex: 0, xp: 15, explanation: "Şəhər adları xüsusi addır, ona görə böyük hərflə yazılır." },
            { id: "az1-soz-l1-b2", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["Bakı", "bakı", "BAKı", "baKı"], correctIndex: 0, xp: 15, explanation: "Şəhər adında yalnız ilk hərf böyükdür: Bakı." },
            { id: "az1-soz-l1-b3", type: "multiple_choice", prompt: "'Bu gün hava gözəldir.' neçə sözdən ibarətdir?", options: ["4", "3", "5", "2"], correctIndex: 0, xp: 15, explanation: "Sözləri sayaq: «Bu», «gün», «hava», «gözəldir» — 4 söz." },
            { id: "az1-soz-l1-b4", type: "multiple_choice", prompt: "Nida cümləsi hansı işarə ilə bitir?", options: ["nida işarəsi (!)", "nöqtə", "vergül", "sual"], correctIndex: 0, xp: 15, explanation: "Nida cümləsində güclü hiss — sevinc, təəccüb, çağırış bildirilir, ona görə nida işarəsi qoyulur." },
            { id: "az1-soz-l1-b5", type: "multiple_choice", prompt: "'İt hürür.' — bu nədir?", options: ["cümlə", "söz", "heca", "hərf"], correctIndex: 0, xp: 15, explanation: "«İt hürür.» bitmiş fikir bildirir — deməli cümlədir." },
          ],
        },
        {
          id: "az1-soz-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az1-kimne-l1",
          title: "Kim? Nə? Nə edir?",
          intro: "Sözlər canlını, əşyanı və ya hərəkəti bildirir.",
          sections: [
            { heading: "Suallar", body: "İnsan/heyvan → 'kim?' (ana, pişik). Əşya → 'nə?' (kitab, alma). Hərəkət → 'nə edir?' (qaçır, oxuyur)." },
          ],
          tasks: [
            { id: "az1-kimne-l1-t1", type: "multiple_choice", prompt: "'kitab' sözü hansı suala cavab verir?", options: ["kim?", "nə?", "nə edir?", "necə?"], correctIndex: 1, xp: 10, explanation: "Kitab cansız əşyadır, ona görə «nə?» sualına cavab verir." },
            { id: "az1-kimne-l1-t2", type: "multiple_choice", prompt: "'ana' sözü hansı suala cavab verir?", options: ["kim?", "nə?", "nə edir?", "harada?"], correctIndex: 0, xp: 10, explanation: "Ana insandır, yəni canlıdır — ona görə «kim?» sualına cavab verir." },
            { id: "az1-kimne-l1-t3", type: "multiple_choice", prompt: "'qaçır' sözü hansı suala cavab verir?", options: ["kim?", "nə?", "nə edir?", "neçə?"], correctIndex: 2, xp: 10, explanation: "«qaçır» iş, hərəkət bildirir — ona görə «nə edir?» sualına cavab verir." },
            { id: "az1-kimne-l1-t4", type: "multiple_choice", prompt: "'alma' sözü hansı suala cavab verir?", options: ["nə edir?", "kim?", "nə?", "harada?"], correctIndex: 2, xp: 10, explanation: "Alma cansız əşyadır, ona görə «nə?» sualına cavab verir." },
            { id: "az1-kimne-l1-t5", type: "multiple_choice", prompt: "'oxuyur' sözü hansı suala cavab verir?", options: ["nə edir?", "kim?", "nə?", "necə?"], correctIndex: 0, xp: 10, explanation: "«oxuyur» hərəkət bildirir — ona görə «nə edir?» sualına cavab verir." },
            { id: "az1-kimne-l1-t6", type: "multiple_choice", prompt: "'müəllim' sözü hansı suala cavab verir?", options: ["nə?", "nə edir?", "kim?", "harada?"], correctIndex: 2, xp: 10, explanation: "Müəllim insandır — ona görə «kim?» sualına cavab verir." },
            { id: "az1-kimne-l1-t7", type: "multiple_choice", prompt: "'qələm' sözü hansı suala cavab verir?", options: ["kim?", "nə edir?", "necə?", "nə?"], correctIndex: 3, xp: 10, explanation: "Qələm cansız əşyadır, ona görə «nə?» sualına cavab verir." },
            { id: "az1-kimne-l1-t8", type: "multiple_choice", prompt: "'uçur' sözü hansı suala cavab verir?", options: ["nə edir?", "nə?", "kim?", "harada?"], correctIndex: 0, xp: 10, explanation: "«uçur» hərəkət bildirir — ona görə «nə edir?» sualına cavab verir." },
            { id: "az1-kimne-l1-t9", type: "multiple_choice", prompt: "'pişik' sözü hansı suala cavab verir?", options: ["nə?", "kim?", "nə edir?", "neçə?"], correctIndex: 1, xp: 10, explanation: "Pişik canlıdır — ona görə «kim?» sualına cavab verir." },
            { id: "az1-kimne-l1-t10", type: "multiple_choice", prompt: "Hansı söz hərəkət bildirir?", options: ["ev", "gülür", "top", "su"], correctIndex: 1, xp: 10, explanation: "«gülür» iş bildirir. Su, ev, top isə əşyadır, hərəkət deyil." },
          ],
          bonusTasks: [
            { id: "az1-kimne-l1-b1", type: "multiple_choice", prompt: "Hansı söz əşya bildirir?", options: ["yazır", "stol", "gedir", "oynayır"], correctIndex: 1, xp: 15, explanation: "Stol əşyadır. Oynayır, gedir, yazır isə hərəkət bildirir." },
            { id: "az1-kimne-l1-b2", type: "multiple_choice", prompt: "Hansı söz canlı (kim?) bildirir?", options: ["daş", "quş", "kitab", "qapı"], correctIndex: 1, xp: 15, explanation: "Quş nəfəs alır, hərəkət edir — canlıdır. Qapı, kitab və daş cansızdır." },
            { id: "az1-kimne-l1-b3", type: "multiple_choice", prompt: "'Uşaq oynayır.' — 'oynayır' hansı suala cavabdır?", options: ["kim?", "nə?", "nə edir?", "harada?"], correctIndex: 2, xp: 15, explanation: "«Uşaq oynayır.» cümləsində uşağın nə etdiyini «oynayır» bildirir — deməli «nə edir?» sualının cavabıdır." },
            { id: "az1-kimne-l1-b4", type: "multiple_choice", prompt: "Hansı söz hərəkət bildirmir?", options: ["qaçır", "gülür", "masa", "yeyir"], correctIndex: 2, xp: 15, explanation: "Masa əşyadır. Yeyir, gülür, qaçır isə hərəkət bildirir." },
          ],
        },
        {
          id: "az1-soz-mesq",
          title: "Məşq",
          intro: "Heca, söz və cümləni birlikdə məşq edək!",
          sections: [
            { heading: "Yadına salaq", body: "Sözdə neçə sait varsa, o qədər heca var: a-na (2 heca). Cümlə böyük hərflə başlayır və nöqtə ilə bitir." },
          ],
          tasks: [
            { id: "az1-soz-mesq-t1", type: "numeric", prompt: "'ba-la' sözündə neçə heca var?", answer: 2, xp: 10, explanation: "«bala» sözündə iki sait var (a, a), ona görə iki heca: ba-la." },
            { id: "az1-soz-mesq-t2", type: "numeric", prompt: "'gül' sözündə neçə heca var?", answer: 1, xp: 10, explanation: "«gül» sözündə tək bir sait var (ü), ona görə 1 heca." },
            { id: "az1-soz-mesq-t3", type: "numeric", prompt: "'a-ta' sözündə neçə heca var?", answer: 2, xp: 10, explanation: "«ata» sözündə iki sait var (a, a), ona görə iki heca: a-ta." },
            { id: "az1-soz-mesq-t4", type: "numeric", prompt: "'ki-ta-bım' sözündə neçə heca var?", answer: 3, xp: 10, explanation: "«kitabım» sözündə üç sait var (i, a, ı), ona görə üç heca: ki-ta-bım." },
            { id: "az1-soz-mesq-t5", type: "multiple_choice", prompt: "Cümlə nə ilə bitir?", options: ["Nöqtə ilə", "Vergül ilə", "Heç nə ilə", "Hərflə"], correctIndex: 0, xp: 10, explanation: "Cümlədə fikir bitir, bunu göstərmək üçün sonda nöqtə qoyulur." },
            { id: "az1-soz-mesq-t6", type: "multiple_choice", prompt: "Cümlə hansı hərflə başlayır?", options: ["Böyük hərflə", "Kiçik hərflə", "Rəqəmlə", "Fərqi yoxdur"], correctIndex: 0, xp: 10, explanation: "Cümlənin başladığı bilinsin deyə ilk hərf böyük yazılır." },
            { id: "az1-soz-mesq-t7", type: "multiple_choice", prompt: "Hansı cümlədir?", options: ["Ana evdədir.", "ana ev", "evdə", "ana"], correctIndex: 0, xp: 10, explanation: "«Ana evdədir.» bitmiş fikir bildirir, böyük hərflə başlayıb nöqtə ilə bitir. Qalanları yarımçıqdır." },
            { id: "az1-soz-mesq-t8", type: "multiple_choice", prompt: "'Kim?' sualına hansı cavab verilir?", options: ["Ana", "Kitab", "Qırmızı", "Getdi"], correctIndex: 0, xp: 10, explanation: "Ana insandır, yəni canlıdır — «kim?» sualı canlılara verilir." },
            { id: "az1-soz-mesq-t9", type: "multiple_choice", prompt: "'Nə?' sualına hansı cavab verilir?", options: ["Alma", "Baba", "Müəllim", "Qardaş"], correctIndex: 0, xp: 10, explanation: "Alma cansız əşyadır — «nə?» sualı cansızlara verilir. Qardaş, müəllim, baba isə «kim?»dir." },
            { id: "az1-soz-mesq-t10", type: "multiple_choice", prompt: "'Nə edir?' sualına hansı cavab verilir?", options: ["Oxuyur", "Kitab", "Ana", "Qırmızı"], correctIndex: 0, xp: 10, explanation: "«Oxuyur» hərəkət bildirir. Kitab və ana əşya/canlı, qırmızı isə rəngdir." },
          ],
          bonusTasks: [
            { id: "az1-soz-mesq-b1", type: "numeric", prompt: "'mək-təb' sözündə neçə heca var?", answer: 2, xp: 15, explanation: "«məktəb» sözündə iki sait var (ə, ə), ona görə iki heca: mək-təb." },
            { id: "az1-soz-mesq-b2", type: "multiple_choice", prompt: "«Baba bağda işləyir.» — burada 'Kim?' sualının cavabı nədir?", options: ["Baba", "Bağda", "İşləyir", "Bağ"], correctIndex: 0, xp: 15, explanation: "Cümlədə işi görən Babadır — «Kim işləyir?» sualının cavabı odur." },
            { id: "az1-soz-mesq-b3", type: "numeric", prompt: "'a-yaq-qa-bı' sözündə neçə heca var?", answer: 4, xp: 15, explanation: "«ayaqqabı» sözündə dörd sait var (a, a, a, ı), ona görə dörd heca." },
            { id: "az1-soz-mesq-b4", type: "multiple_choice", prompt: "«Nərgiz kitab oxuyur.» — 'Nə edir?' sualının cavabı?", options: ["Oxuyur", "Nərgiz", "Kitab", "Kitab oxuyur"], correctIndex: 0, xp: 15, explanation: "Nərgizin gördüyü iş «oxuyur»dur. «Kitab» isə nəyi oxuduğunu bildirir, hərəkəti yox." },
            { id: "az1-soz-mesq-b5", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["Mən məktəbə gedirəm.", "mən məktəbə gedirəm", "Mən məktəbə gedirəm", "mən Məktəbə gedirəm."], correctIndex: 0, xp: 15, explanation: "«Mən məktəbə gedirəm.» — həm böyük hərflə başlayır, həm nöqtə ilə bitir. Digərlərində biri əskikdir." },
          ],
        },
        {
          id: "az1-soz-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    {
      id: "az1-oxunitq",
      title: "Oxu və nəzakət",
      description: "Oxu bacarığı və gündəlik nəzakət sözləri.",
      lessons: [
        {
          id: "az1-oxu-l1",
          title: "Oxu və tanı",
          intro: "Sözləri oxuyub şəkillə uyğunlaşdıraq.",
          sections: [
            { heading: "Oxu", body: "Hərfləri birləşdirib söz oxuyuruq: k + i + t + a + b = kitab. Şəkli görüb sözünü tapırıq." },
          ],
          tasks: [
            { id: "az1-oxu-l1-t1", type: "multiple_choice", prompt: "🍎 — bu nədir?", options: ["alma", "armud", "üzüm", "nar"], correctIndex: 0, xp: 10, explanation: "🍎 qırmızı, yumru meyvədir — bu, almadır." },
            { id: "az1-oxu-l1-t2", type: "multiple_choice", prompt: "🐱 — bu nədir?", options: ["pişik", "it", "quş", "balıq"], correctIndex: 0, xp: 10, explanation: "🐱 bığları və şiş qulaqları olan ev heyvanıdır — bu, pişikdir." },
            { id: "az1-oxu-l1-t3", type: "multiple_choice", prompt: "🐶 — bu nədir?", options: ["it", "pişik", "at", "inək"], correctIndex: 0, xp: 10, explanation: "🐶 sallaq qulaqlı, sadiq ev heyvanıdır — bu, itdir." },
            { id: "az1-oxu-l1-t4", type: "multiple_choice", prompt: "☀️ — bu nədir?", options: ["günəş", "ay", "ulduz", "bulud"], correctIndex: 0, xp: 10, explanation: "☀️ gündüz işıq və istilik verən parlaq cisimdir — bu, günəşdir." },
            { id: "az1-oxu-l1-t5", type: "multiple_choice", prompt: "🌸 — bu nədir?", options: ["çiçək", "ağac", "ot", "yarpaq"], correctIndex: 0, xp: 10, explanation: "🌸 ləçəkləri olan bitkidir — bu, çiçəkdir." },
            { id: "az1-oxu-l1-t6", type: "multiple_choice", prompt: "🏠 — bu nədir?", options: ["ev", "məktəb", "mağaza", "körpü"], correctIndex: 0, xp: 10, explanation: "🏠 damı və qapısı olan, insanların yaşadığı yerdir — bu, evdir." },
            { id: "az1-oxu-l1-t7", type: "multiple_choice", prompt: "📖 — bu nədir?", options: ["kitab", "dəftər", "qələm", "çanta"], correctIndex: 0, xp: 10, explanation: "📖 açılmış səhifələri olan, oxuduğumuz şeydir — bu, kitabdır." },
            { id: "az1-oxu-l1-t8", type: "multiple_choice", prompt: "🐟 — bu nədir?", options: ["balıq", "quş", "pişik", "dovşan"], correctIndex: 0, xp: 10, explanation: "🐟 suda üzən, üzgəcləri olan canlıdır — bu, balıqdır." },
            { id: "az1-oxu-l1-t9", type: "multiple_choice", prompt: "🚗 — bu nədir?", options: ["maşın", "avtobus", "təyyarə", "qatar"], correctIndex: 0, xp: 10, explanation: "🚗 dörd təkərli minik nəqliyyatıdır — bu, maşındır." },
            { id: "az1-oxu-l1-t10", type: "multiple_choice", prompt: "Kimsə sənə kömək etdi. Nə deyərsən?", options: ["Sağ ol / təşəkkür", "Salam", "Xeyr", "Yox"], correctIndex: 0, xp: 10, explanation: "Kömək edənə minnətdarlıq bildirmək üçün «sağ ol» deyirik. «Salam» isə görüşmə sözüdür." },
            { id: "az1-oxu-l1-t11", type: "multiple_choice", prompt: "Səhər böyüklərə nə deyirik?", options: ["Sabahınız xeyir", "Gecən xeyrə", "Sağ ol", "Yox"], correctIndex: 0, xp: 10, explanation: "«Sabahınız xeyir» məhz səhər deyilən salamdır. «Gecən xeyrə» yatmazdan əvvəl deyilir." },
            { id: "az1-oxu-l1-t12", type: "multiple_choice", prompt: "'k + i + t + a + b' hərflərindən hansı söz alınır?", options: ["kitab", "kabit", "tabik", "bakit"], correctIndex: 0, xp: 10, explanation: "Hərfləri sıra ilə birləşdiririk: k-i-t-a-b → kitab. Digər variantlarda hərflərin yeri dəyişib və söz mənasını itirir." },
            { id: "az1-oxu-l1-t13", type: "multiple_choice", prompt: "'a + n + a' hərflərindən hansı söz alınır?", options: ["ana", "naa", "aan", "nan"], correctIndex: 0, xp: 10, explanation: "Hərfləri sıra ilə birləşdiririk: a-n-a → ana." },
            { id: "az1-oxu-l1-t14", type: "multiple_choice", prompt: "🐦 — bu nədir?", options: ["quş", "balıq", "pişik", "at"], correctIndex: 0, xp: 10, explanation: "🐦 dimdiyi və qanadları olan, uçan canlıdır — bu, quşdur." },
            { id: "az1-oxu-l1-t15", type: "multiple_choice", prompt: "Nəsə xahiş edəndə hansı nəzakət sözünü deyirik?", options: ["zəhmət olmasa", "yox", "get", "dur"], correctIndex: 0, xp: 15, explanation: "Xahişi nəzakətli etmək üçün «zəhmət olmasa» deyirik. Get, dur, yox isə əmrdir." },
          ],
          bonusTasks: [
            { id: "az1-oxu-l1-b1", type: "multiple_choice", prompt: "'s + u' hərflərindən hansı söz alınır?", options: ["su", "us", "sus", "uu"], correctIndex: 0, xp: 15, explanation: "Hərfləri birləşdiririk: s-u → su." },
            { id: "az1-oxu-l1-b2", type: "multiple_choice", prompt: "🌙 — bu nədir?", options: ["ay", "günəş", "ulduz", "bulud"], correctIndex: 0, xp: 15, explanation: "🌙 gecə göydə görünən oraq formalı cisimdir — bu, aydır." },
            { id: "az1-oxu-l1-b3", type: "multiple_choice", prompt: "Yaşlı adamla necə danışmalıyıq?", options: ["nəzakətlə (Siz)", "qışqıraraq", "gülərək", "susaraq"], correctIndex: 0, xp: 15, explanation: "Yaşlı adama hörmət göstərmək üçün ona «Siz» deyə, sakit və nəzakətlə müraciət edirik." },
            { id: "az1-oxu-l1-b4", type: "multiple_choice", prompt: "🍞 — bu nədir?", options: ["çörək", "alma", "su", "süd"], correctIndex: 0, xp: 15, explanation: "🍞 dilimlənən, hər gün süfrəmizdə olan yeməkdir — bu, çörəkdir." },
            { id: "az1-oxu-l1-b5", type: "multiple_choice", prompt: "'a + t' hərflərindən hansı söz alınır?", options: ["at", "ta", "aat", "tt"], correctIndex: 0, xp: 15, explanation: "Hərfləri birləşdiririk: a-t → at." },
          ],
        },
        {
          id: "az1-nezaket-l1",
          title: "Nəzakət sözləri",
          intro: "Nəzakətli olmaq üçün gözəl sözlər deyirik.",
          sections: [
            { heading: "Nəzakət sözləri", body: "Salam, sağ ol / təşəkkür edirəm, buyurun, zəhmət olmasa, bağışlayın, xudahafiz. Böyüklərə 'Siz' deyirik." },
          ],
          tasks: [
            { id: "az1-nezaket-l1-t1", type: "multiple_choice", prompt: "Səhər görüşəndə nə deyirik?", options: ["Sabahınız xeyir", "Gecən xeyrə", "Xudahafiz", "Yox"], correctIndex: 0, xp: 10, explanation: "«Sabahınız xeyir» günün əvvəlində, səhər deyilən salamdır." },
            { id: "az1-nezaket-l1-t2", type: "multiple_choice", prompt: "Kimsə sənə kömək etdi. Nə deyərsən?", options: ["Get", "Təşəkkür edirəm", "Yox", "Dur"], correctIndex: 1, xp: 10, explanation: "Kömək edənə minnətdarlığımızı «təşəkkür edirəm» sözü ilə bildiririk." },
            { id: "az1-nezaket-l1-t3", type: "multiple_choice", prompt: "Nəsə xahiş edəndə nə deyirik?", options: ["Tez ol", "Ver", "Zəhmət olmasa", "Yox"], correctIndex: 2, xp: 10, explanation: "«Zəhmət olmasa» xahişi yumşaldır və qarşıdakına hörmət göstərir." },
            { id: "az1-nezaket-l1-t4", type: "multiple_choice", prompt: "Ayrılanda nə deyirik?", options: ["Salam", "Sabahınız xeyir", "Buyurun", "Sağ ol, xudahafiz"], correctIndex: 3, xp: 10, explanation: "«Sağ ol, xudahafiz» vidalaşma sözüdür — ayrılarkən deyilir." },
            { id: "az1-nezaket-l1-t5", type: "multiple_choice", prompt: "Səhvin üçün nə deyirsən?", options: ["Bağışlayın", "Sağ ol", "Salam", "Buyurun"], correctIndex: 0, xp: 10, explanation: "Səhv edəndə üzr istəyirik, bunun üçün «bağışlayın» deyilir." },
            { id: "az1-nezaket-l1-t6", type: "multiple_choice", prompt: "Böyüklərə necə müraciət edirik?", options: ["'sən' deyə", "'Siz' deyə", "adı ilə", "qışqıraraq"], correctIndex: 1, xp: 10, explanation: "Böyüklərə hörmət əlaməti olaraq «Siz» deyə müraciət edirik." },
            { id: "az1-nezaket-l1-t7", type: "multiple_choice", prompt: "Qonaq gələndə nə deyirik?", options: ["Get", "Xoş gəlmisiniz", "Yox", "Sonra"], correctIndex: 1, xp: 10, explanation: "Qonağı xoş qarşılamaq üçün «xoş gəlmisiniz» deyirik." },
            { id: "az1-nezaket-l1-t8", type: "multiple_choice", prompt: "Kimsə 'sağ ol' dedi. Cavabında nə deyərsən?", options: ["Dəyməz / buyurun", "Yox", "Get", "Bilmirəm"], correctIndex: 0, xp: 10, explanation: "Təşəkkürə cavab olaraq «dəyməz» və ya «buyurun» deyilir." },
            { id: "az1-nezaket-l1-t9", type: "multiple_choice", prompt: "Yeməkdən əvvəl/sonra nə demək gözəldir?", options: ["Nuş olsun / afiyət olsun", "Get", "Yox", "Sonra"], correctIndex: 0, xp: 10, explanation: "Yeməklə bağlı xoş arzu «nuş olsun / afiyət olsun» sözləri ilə bildirilir." },
            { id: "az1-nezaket-l1-t10", type: "multiple_choice", prompt: "Nəzakətli danışıq necə olur?", options: ["qışqıraraq", "təhqir edərək", "sakit və hörmətlə", "gülərək"], correctIndex: 2, xp: 15, explanation: "Nəzakət səsi ucaltmadan, qarşıdakına hörmətlə danışmaq deməkdir." },
          ],
          bonusTasks: [
            { id: "az1-nezaket-l1-b1", type: "multiple_choice", prompt: "Sinifə girəndə müəllimə nə deyirik?", options: ["Salam / Sabahınız xeyir", "Get", "Yox", "Sonra"], correctIndex: 0, xp: 15, explanation: "Sinifə girəndə müəllimi salamlayırıq: «Salam» və ya «Sabahınız xeyir»." },
            { id: "az1-nezaket-l1-b2", type: "multiple_choice", prompt: "Kimisə narahat etdin. Nə deyirsən?", options: ["Sağ ol", "Bağışlayın", "Salam", "Buyurun"], correctIndex: 1, xp: 15, explanation: "Kimisə narahat etmişiksə üzr istəyirik — «bağışlayın» deyirik." },
            { id: "az1-nezaket-l1-b3", type: "multiple_choice", prompt: "Nəyisə təklif edəndə nə deyirik?", options: ["Buyurun", "Get", "Yox", "Tez ol"], correctIndex: 0, xp: 15, explanation: "Nəyisə uzadanda, təklif edəndə «buyurun» deyilir." },
            { id: "az1-nezaket-l1-b4", type: "multiple_choice", prompt: "Nəzakət sözü hansıdır?", options: ["ver", "təşəkkür edirəm", "tez ol", "dur"], correctIndex: 1, xp: 15, explanation: "«Təşəkkür edirəm» minnətdarlıq bildirir. Dur, ver, tez ol isə əmrdir." },
          ],
        },
        {
          id: "az1-oxu-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az1-oxu-mesq",
          title: "Məşq",
          intro: "Oxu və nəzakət sözlərini məşq edək!",
          sections: [
            { heading: "Yadına salaq", body: "Nəzakət sözləri: salam, sağ ol, zəhmət olmasa, bağışlayın, xoş gəldiniz, gecəniz xeyrə qalsın." },
          ],
          tasks: [
            { id: "az1-oxu-mesq-t1", type: "multiple_choice", prompt: "Səhər görüşəndə nə deyirsən?", options: ["Sabahın xeyir", "Gecən xeyrə qalsın", "Sağ ol", "Bağışla"], correctIndex: 0, xp: 10, explanation: "«Sabahın xeyir» səhər deyilən salamdır." },
            { id: "az1-oxu-mesq-t2", type: "multiple_choice", prompt: "Kimsə sənə kömək edəndə nə deyirsən?", options: ["Sağ ol", "Salam", "Bağışlayın", "Buyurun"], correctIndex: 0, xp: 10, explanation: "Köməyə görə minnətdarlıq «sağ ol» sözü ilə bildirilir." },
            { id: "az1-oxu-mesq-t3", type: "multiple_choice", prompt: "Nəsə istəyəndə hansı sözü işlədirsən?", options: ["Zəhmət olmasa", "Sağ ol", "Salam", "Əlvida"], correctIndex: 0, xp: 10, explanation: "«Zəhmət olmasa» istəyi nəzakətli xahişə çevirir." },
            { id: "az1-oxu-mesq-t4", type: "multiple_choice", prompt: "Səhv edəndə nə deyirsən?", options: ["Bağışlayın", "Sağ ol", "Buyurun", "Salam"], correctIndex: 0, xp: 10, explanation: "Səhvə görə üzr istəyirik: «bağışlayın»." },
            { id: "az1-oxu-mesq-t5", type: "multiple_choice", prompt: "Qonaq gələndə nə deyirsən?", options: ["Xoş gəldiniz", "Sağ ol", "Bağışlayın", "Gecən xeyrə"], correctIndex: 0, xp: 10, explanation: "Qonağı «xoş gəldiniz» sözü ilə qarşılayırıq." },
            { id: "az1-oxu-mesq-t6", type: "multiple_choice", prompt: "Yatmağa gedəndə nə deyirsən?", options: ["Gecən xeyrə qalsın", "Sabahın xeyir", "Salam", "Sağ ol"], correctIndex: 0, xp: 10, explanation: "«Gecən xeyrə qalsın» yatmazdan əvvəl deyilən arzudur." },
            { id: "az1-oxu-mesq-t7", type: "multiple_choice", prompt: "«Sağ ol» nə vaxt deyilir?", options: ["Təşəkkür edəndə", "Görüşəndə", "Ayrılanda", "Səhv edəndə"], correctIndex: 0, xp: 10, explanation: "«Sağ ol» minnətdarlıq sözüdür — kimsə bizə yaxşılıq edəndə deyilir." },
            { id: "az1-oxu-mesq-t8", type: "multiple_choice", prompt: "Müəllimlə görüşəndə hansı daha nəzakətlidir?", options: ["Salam, müəllim!", "Ey!", "Nə var?", "Hey!"], correctIndex: 0, xp: 10, explanation: "«Salam, müəllim!» həm salamlaşır, həm hörmət göstərir. «Hey!» və «Ey!» kobud müraciətdir." },
            { id: "az1-oxu-mesq-t9", type: "multiple_choice", prompt: "«Buyurun» nə vaxt deyilir?", options: ["Nəyisə təklif edəndə", "Yatanda", "Səhv edəndə", "Qaçanda"], correctIndex: 0, xp: 10, explanation: "«Buyurun» nəyisə uzadanda, təklif edəndə deyilir." },
            { id: "az1-oxu-mesq-t10", type: "multiple_choice", prompt: "Nəzakətli uşaq necə danışır?", options: ["Mehriban və hörmətlə", "Qışqıraraq", "Kobud", "Danışmır"], correctIndex: 0, xp: 10, explanation: "Nəzakətli uşaq səsini ucaltmır, hamı ilə mehriban və hörmətlə danışır." },
          ],
          bonusTasks: [
            { id: "az1-oxu-mesq-b1", type: "multiple_choice", prompt: "Dostun sənə hədiyyə verdi. Nə deyirsən?", options: ["Çox sağ ol!", "Bağışla!", "Salam!", "Buyur!"], correctIndex: 0, xp: 15, explanation: "Hədiyyəyə görə minnətdarlıq bildiririk: «Çox sağ ol!»" },
            { id: "az1-oxu-mesq-b2", type: "multiple_choice", prompt: "Avtobusda yaşlı adam gəlib. Nə edərsən?", options: ["Yerimi verərəm", "Oturmağa davam edərəm", "Baxmaram", "Qaçaram"], correctIndex: 0, xp: 15, explanation: "Yaşlıya hörmət göstərmək üçün ayağa qalxıb yerimizi veririk." },
            { id: "az1-oxu-mesq-b3", type: "multiple_choice", prompt: "«Zəhmət olmasa» sözü nəyi göstərir?", options: ["Nəzakətli xahiş", "Əmr", "Təşəkkür", "Salam"], correctIndex: 0, xp: 15, explanation: "«Zəhmət olmasa» əmr deyil — istəyi nəzakətli xahişə çevirir." },
            { id: "az1-oxu-mesq-b4", type: "multiple_choice", prompt: "Sinifdə müəllim danışanda nə etməlisən?", options: ["Diqqətlə dinləmək", "Danışmaq", "Oynamaq", "Qışqırmaq"], correctIndex: 0, xp: 15, explanation: "Müəllim danışanda diqqətlə dinləmək həm hörmət göstərir, həm də öyrənməyə kömək edir." },
            { id: "az1-oxu-mesq-b5", type: "multiple_choice", prompt: "Hansı nəzakət sözü DEYİL?", options: ["Get!", "Sağ ol", "Zəhmət olmasa", "Bağışlayın"], correctIndex: 0, xp: 15, explanation: "«Get!» əmrdir və kobud səslənir. Digər üçü isə nəzakət sözüdür." },
          ],
        },
        {
          id: "az1-oxu-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    {
      id: "az1-yazi",
      title: "Yazı və böyük hərf",
      description: "Hərfləri və sözləri düzgün yazmaq.",
      lessons: [
        {
          id: "az1-yazi-l1",
          title: "Böyük və kiçik hərflər",
          intro: "Hər hərfin iki forması var.",
          sections: [
            { heading: "İki forma", body: "Hər hərfin BÖYÜK (A, B, C) və KİÇİK (a, b, c) forması var." },
            { heading: "Nə vaxt böyük?", body: "Cümlənin əvvəlində və adlarda böyük hərf yazılır: Aysel, Bakı, Mən." },
          ],
          tasks: [
            { id: "az1-yazi-l1-t1", type: "multiple_choice", prompt: "'A' hərfinin kiçik forması hansıdır?", options: ["a", "ə", "e", "o"], correctIndex: 0, xp: 10, explanation: "«A» hərfinin kiçik forması a-dır. o, ə, e isə tamam başqa hərflərdir." },
            { id: "az1-yazi-l1-t2", type: "multiple_choice", prompt: "'B' hərfinin kiçik forması hansıdır?", options: ["b", "d", "p", "q"], correctIndex: 0, xp: 10, explanation: "«B» hərfinin kiçik forması b-dir. d və p ona oxşayır, amma dik xəttin yeri fərqlidir." },
            { id: "az1-yazi-l1-t3", type: "multiple_choice", prompt: "Cümlə hansı hərflə başlayır?", options: ["Böyük", "Kiçik", "Rəqəmlə", "Fərqi yoxdur"], correctIndex: 0, xp: 10, explanation: "Cümlənin harada başladığı bilinsin deyə ilk hərf böyük yazılır." },
            { id: "az1-yazi-l1-t4", type: "multiple_choice", prompt: "İnsan adları necə yazılır?", options: ["Böyük hərflə", "Kiçik hərflə", "Fərqi yoxdur", "Rəqəmlə"], correctIndex: 0, xp: 10, explanation: "İnsan adları xüsusi addır, ona görə böyük hərflə yazılır." },
            { id: "az1-yazi-l1-t5", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["Aysel", "aysel", "AYsel", "aYsel"], correctIndex: 0, xp: 10, explanation: "Adda yalnız ilk hərf böyük, qalanları kiçik olur: Aysel." },
            { id: "az1-yazi-l1-t6", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["Mən məktəbə gedirəm.", "mən məktəbə gedirəm.", "Mən Məktəbə Gedirəm.", "mən Məktəbə gedirəm."], correctIndex: 0, xp: 10, explanation: "«Mən məktəbə gedirəm.» — yalnız ilk söz böyük hərflədir və sonda nöqtə var. Ortadakı sözlər böyük yazılmır." },
            { id: "az1-yazi-l1-t7", type: "multiple_choice", prompt: "'Ə' hərfinin kiçik forması hansıdır?", options: ["ə", "a", "e", "o"], correctIndex: 0, xp: 10, explanation: "«Ə» hərfinin kiçik forması ə-dir. e və a ona oxşayır, amma fərqli səslərdir." },
            { id: "az1-yazi-l1-t8", type: "multiple_choice", prompt: "Şəhər adları necə yazılır?", options: ["Böyük hərflə", "Kiçik hərflə", "Dırnaqda", "Rəqəmlə"], correctIndex: 0, xp: 10, explanation: "Şəhər adları xüsusi addır, ona görə böyük hərflə yazılır." },
            { id: "az1-yazi-l1-t9", type: "fill_blank", prompt: "'bakı' sözü düzgün necə yazılır? (bir söz)", accepted: ["Bakı", "bakı"], xp: 10, explanation: "Bakı şəhər adıdır, yəni xüsusi addır — ilk hərfi böyük yazılır." },
            { id: "az1-yazi-l1-t10", type: "multiple_choice", prompt: "Hansı hərf BÖYÜKDÜR?", options: ["M", "m", "n", "r"], correctIndex: 0, xp: 10, explanation: "M böyük hərfdir; m, n, r isə kiçik hərflərdir." },
          ],
          bonusTasks: [
            { id: "az1-yazi-l1-b1", type: "multiple_choice", prompt: "'mənim adım aysel' — burada neçə böyük hərf lazımdır?", options: ["İki", "Bir", "Üç", "Heç biri"], correctIndex: 0, xp: 15, explanation: "«Mənim» cümlənin ilk sözüdür, «Aysel» isə addır. Deməli iki böyük hərf lazımdır." },
            { id: "az1-yazi-l1-b2", type: "multiple_choice", prompt: "Niyə böyük hərf işlədirik?", options: ["Cümlənin başını və adları göstərmək üçün", "Gözəl görünsün deyə", "Yer tutsun deyə", "Səbəbi yoxdur"], correctIndex: 0, xp: 15, explanation: "Böyük hərf oxuyana iki şeyi göstərir: cümlə burada başlayır və bu söz addır." },
            { id: "az1-yazi-l1-b3", type: "multiple_choice", prompt: "Heyvanın adı (məs. Pambıq) necə yazılır?", options: ["Böyük hərflə", "Kiçik hərflə", "Dırnaqda", "Fərqi yoxdur"], correctIndex: 0, xp: 15, explanation: "Heyvana verilən xüsusi ad da ad sayılır, ona görə böyük hərflə yazılır: Pambıq." },
            { id: "az1-yazi-l1-b4", type: "multiple_choice", prompt: "Hansı cümlə tam düzgündür?", options: ["Bu, mənim dostum Nihaddır.", "bu, mənim dostum nihaddır.", "Bu, Mənim Dostum Nihaddır.", "bu, Mənim dostum Nihaddır."], correctIndex: 0, xp: 15, explanation: "«Bu, mənim dostum Nihaddır.» — ilk söz və ad böyük, qalan sözlər isə kiçik yazılıb." },
          ],
        },
        {
          id: "az1-yazi-l2",
          title: "Sözü düzgün yaz",
          intro: "Hərfləri düzgün sırada.",
          sections: [
            { heading: "Sıra vacibdir", body: "Hərflərin sırası dəyişsə söz mənasını itirir: 'ana' düzdür, 'naa' söz deyil." },
            { heading: "Diqqət", body: "Oxşar hərflərə fikir ver: b–d, q–ğ, n–m." },
          ],
          tasks: [
            { id: "az1-yazi-l2-t1", type: "multiple_choice", prompt: "Hansı düzgün sözdür?", options: ["ana", "naa", "aan", "nan"], correctIndex: 0, xp: 10, explanation: "Hərflərin düzgün sırası a-n-a-dır. Digərlərində hərflər yerini dəyişib və söz mənasını itirib." },
            { id: "az1-yazi-l2-t2", type: "multiple_choice", prompt: "Hansı düzgün sözdür?", options: ["kitab", "kitba", "ktiab", "kaitb"], correctIndex: 0, xp: 10, explanation: "Hərflərin düzgün sırası k-i-t-a-b-dır." },
            { id: "az1-yazi-l2-t3", type: "multiple_choice", prompt: "Hansı düzgün sözdür?", options: ["məktəb", "mətkəb", "məkdəb", "mkətəb"], correctIndex: 0, xp: 10, explanation: "Söz «məktəb» kimi yazılır: mək-təb. Digərlərində k və t yerini dəyişib." },
            { id: "az1-yazi-l2-t4", type: "multiple_choice", prompt: "Hansı düzgün sözdür?", options: ["alma", "amla", "lama", "mala"], correctIndex: 0, xp: 10, explanation: "Hərflərin düzgün sırası a-l-m-a-dır." },
            { id: "az1-yazi-l2-t5", type: "multiple_choice", prompt: "Hansı düzgün sözdür?", options: ["su", "us", "sus", "uu"], correctIndex: 0, xp: 10, explanation: "Hərflərin düzgün sırası s-u-dur." },
            { id: "az1-yazi-l2-t6", type: "multiple_choice", prompt: "Hansı düzgün sözdür?", options: ["dost", "dsot", "tsod", "odst"], correctIndex: 0, xp: 10, explanation: "Hərflərin düzgün sırası d-o-s-t-dur." },
            { id: "az1-yazi-l2-t7", type: "fill_blank", prompt: "'q-ə-l-ə-m' hərflərindən hansı söz alınır?", accepted: ["qələm", "Qələm"], xp: 10, explanation: "Hərfləri sıra ilə birləşdiririk: q-ə-l-ə-m → qələm." },
            { id: "az1-yazi-l2-t8", type: "multiple_choice", prompt: "Hansı düzgün sözdür?", options: ["gül", "lüg", "ügl", "glü"], correctIndex: 0, xp: 10, explanation: "Hərflərin düzgün sırası g-ü-l-dür." },
            { id: "az1-yazi-l2-t9", type: "multiple_choice", prompt: "Hansı düzgün sözdür?", options: ["ev", "ve", "eve", "vv"], correctIndex: 0, xp: 10, explanation: "Hərflərin düzgün sırası e-v-dir." },
            { id: "az1-yazi-l2-t10", type: "multiple_choice", prompt: "Hansı düzgün sözdür?", options: ["bala", "abla", "laba", "alba"], correctIndex: 0, xp: 10, explanation: "Hərflərin düzgün sırası b-a-l-a-dır." },
          ],
          bonusTasks: [
            { id: "az1-yazi-l2-b1", type: "multiple_choice", prompt: "'k-i-t-a-b' hərflərinin sırası dəyişsə nə olur?", options: ["Söz mənasını itirir", "Heç nə", "Daha gözəl olur", "Söz uzanır"], correctIndex: 0, xp: 15, explanation: "Hərflərin yeri dəyişəndə «kitab» sözü tanınmaz olur və heç nə bildirmir." },
            { id: "az1-yazi-l2-b2", type: "multiple_choice", prompt: "'d' və 'b' hərfləri niyə qarışdırılır?", options: ["Görünüşü oxşardır", "Səsi eynidir", "Mənası eynidir", "Qarışdırılmır"], correctIndex: 0, xp: 15, explanation: "«d» və «b» eyni dairə və dik xəttdən qurulub, sadəcə dik xətt fərqli tərəfdədir — ona görə qarışdırılır." },
            { id: "az1-yazi-l2-b3", type: "fill_blank", prompt: "'a-t-a' hərflərindən hansı söz alınır?", accepted: ["ata", "Ata"], xp: 15, explanation: "Hərfləri sıra ilə birləşdiririk: a-t-a → ata." },
            { id: "az1-yazi-l2-b4", type: "multiple_choice", prompt: "Hansı düzgün sözdür?", options: ["dəftər", "dəftrə", "dfətər", "dəfrət"], correctIndex: 0, xp: 15, explanation: "Hərflərin düzgün sırası d-ə-f-t-ə-r-dir." },
          ],
        },
        {
          id: "az1-yazi-l3",
          title: "Cümləni düzgün yaz",
          intro: "Böyük hərflə başla, nöqtə ilə bitir.",
          sections: [
            { heading: "İki qayda", body: "Cümlə BÖYÜK hərflə başlayır və NÖQTƏ ilə bitir." },
            { heading: "Söz arası", body: "Sözlərin arasında boşluq qoyulur: 'Mən oxuyuram.' — 'Mənoxuyuram.' deyil." },
          ],
          tasks: [
            { id: "az1-yazi-l3-t1", type: "multiple_choice", prompt: "Cümlənin sonunda hansı işarə qoyulur?", options: [".", "?", "!", ","], correctIndex: 0, xp: 10, explanation: "Nəqli cümlədə fikir bitir, bunu nöqtə göstərir." },
            { id: "az1-yazi-l3-t2", type: "multiple_choice", prompt: "Hansı cümlə düzgündür?", options: ["Mən oxuyuram.", "mən oxuyuram", "Mən oxuyuram", "mən oxuyuram."], correctIndex: 0, xp: 10, explanation: "«Mən oxuyuram.» — həm böyük hərflə başlayır, həm nöqtə ilə bitir. Digərlərində biri əskikdir." },
            { id: "az1-yazi-l3-t3", type: "multiple_choice", prompt: "Sözlərin arasında nə qoyulur?", options: ["Boşluq", "Nöqtə", "Vergül", "Heç nə"], correctIndex: 0, xp: 10, explanation: "Sözlər bir-birinə qarışmasın deyə aralarında boşluq buraxılır." },
            { id: "az1-yazi-l3-t4", type: "multiple_choice", prompt: "Sual cümləsinin sonunda hansı işarə qoyulur?", options: ["?", ".", "!", ","], correctIndex: 0, xp: 10, explanation: "Sual cümləsində nəsə soruşulur, ona görə sonda sual işarəsi qoyulur." },
            { id: "az1-yazi-l3-t5", type: "multiple_choice", prompt: "Hansı düzgündür?", options: ["Bu, mənim kitabımdır.", "bu mənim kitabımdır", "Bu mənim kitabımdır", "bu, mənim kitabımdır"], correctIndex: 0, xp: 10, explanation: "«Bu, mənim kitabımdır.» — yeganə variantdır ki, həm böyük hərflə başlayır, həm nöqtə ilə bitir." },
            { id: "az1-yazi-l3-t6", type: "multiple_choice", prompt: "'Sən hara gedirsən' — nə çatışmır?", options: ["Sual işarəsi", "Nöqtə", "Vergül", "Heç nə"], correctIndex: 0, xp: 10, explanation: "Cümlədə «hara» sözü ilə sual verilir, amma sonunda heç bir işarə yoxdur — sual işarəsi çatışmır." },
            { id: "az1-yazi-l3-t7", type: "multiple_choice", prompt: "Cümlə nədir?", options: ["Bitmiş fikri bildirən sözlər", "Bir söz", "Bir hərf", "Bir səs"], correctIndex: 0, xp: 10, explanation: "Cümlə tam, bitmiş fikir bildirir. Tək söz və ya tək hərf bunu edə bilmir." },
            { id: "az1-yazi-l3-t8", type: "fill_blank", prompt: "Cümlə ______ hərflə başlayır. (bir söz)", accepted: ["böyük", "Böyük"], xp: 10, explanation: "Cümlənin harada başladığı bilinsin deyə ilk hərf böyük yazılır." },
            { id: "az1-yazi-l3-t9", type: "multiple_choice", prompt: "'Salam!' cümləsinin sonunda hansı işarə var?", options: ["!", ".", "?", ","], correctIndex: 0, xp: 10, explanation: "«Salam!» müraciət və güclü hiss bildirir — ona görə nida işarəsi ilə bitir." },
            { id: "az1-yazi-l3-t10", type: "multiple_choice", prompt: "Hansı cümlədə boşluq səhvi var?", options: ["Mənoxuyuram.", "Mən oxuyuram.", "Mən kitab oxuyuram.", "Kitab oxuyuram."], correctIndex: 0, xp: 10, explanation: "«Mənoxuyuram.» — «mən» və «oxuyuram» ayrı sözlərdir, aralarında boşluq olmalıdır." },
          ],
          bonusTasks: [
            { id: "az1-yazi-l3-b1", type: "multiple_choice", prompt: "'mən aysellə oynadım' cümləsində neçə səhv var?", options: ["İki: böyük hərf və nöqtə", "Bir", "Üç", "Səhv yoxdur"], correctIndex: 0, xp: 15, explanation: "İki səhv var: cümlə kiçik hərflə başlayıb və sonunda nöqtə qoyulmayıb." },
            { id: "az1-yazi-l3-b2", type: "multiple_choice", prompt: "Nida cümləsi hansı işarə ilə bitir?", options: ["!", ".", "?", ";"], correctIndex: 0, xp: 15, explanation: "Nida cümləsi güclü hiss — sevinc, təəccüb, çağırış bildirir, ona görə nida işarəsi ilə bitir." },
            { id: "az1-yazi-l3-b3", type: "multiple_choice", prompt: "'Aysel və Nihad gəldi.' cümləsində neçə söz var?", options: ["4", "3", "5", "2"], correctIndex: 0, xp: 15, explanation: "Sözləri sayaq: «Aysel», «və», «Nihad», «gəldi» — 4 söz." },
            { id: "az1-yazi-l3-b4", type: "multiple_choice", prompt: "Niyə nöqtə qoyulur?", options: ["Cümlənin bitdiyini göstərmək üçün", "Gözəllik üçün", "Boşluq üçün", "Səbəbi yoxdur"], correctIndex: 0, xp: 15, explanation: "Nöqtə oxuyana fikrin burada bitdiyini bildirir." },
          ],
        },
        {
          id: "az1-yazi-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az1-yazi-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    {
      id: "az1-nagil",
      title: "Nağıl, şeir və tapmaca",
      description: "Dinlə, anla və cavab ver.",
      lessons: [
        {
          id: "az1-nagil-l1",
          title: "Nağılı dinlə və anla",
          intro: "Nağılda kim var, nə baş verir?",
          sections: [
            { heading: "Nağıl", body: "Nağıl uydurma hekayədir. Orada qəhrəmanlar olur və çox vaxt yaxşılıq qalib gəlir." },
            { heading: "Suallar", body: "Nağılı oxuyandan sonra soruş: Kim? Nə etdi? Sonda nə oldu?" },
          ],
          tasks: [
            { id: "az1-nagil-l1-t1", type: "multiple_choice", prompt: "Nağıl nədir?", options: ["Uydurma hekayə", "Real xəbər", "Dərs kitabı", "Lüğət"], correctIndex: 0, xp: 10, explanation: "Nağıldakı hadisələr həqiqətdə baş verməyib — onları xalq uydurub və nəsildən-nəslə danışıb." },
            { id: "az1-nagil-l1-t2", type: "multiple_choice", prompt: "Nağılın qəhrəmanı kim ola bilər?", options: ["İnsan və ya heyvan", "Yalnız insan", "Yalnız əşya", "Heç kim"], correctIndex: 0, xp: 10, explanation: "Nağılda heyvanlar da insan kimi danışıb hərəkət edə bilir, ona görə qəhrəman həm insan, həm heyvan ola bilər." },
            { id: "az1-nagil-l1-t3", type: "multiple_choice", prompt: "'Tülkü və qarğa' nağılında tülkü necədir?", options: ["Hiyləgər", "Sadəlövh", "Qorxaq", "Tənbəl"], correctIndex: 0, xp: 10, explanation: "Tülkü qarğanı tərifləyərək aldadır və pendiri əlindən alır — bu, hiyləgərlikdir." },
            { id: "az1-nagil-l1-t4", type: "multiple_choice", prompt: "Nağıl adətən necə başlayır?", options: ["Biri var idi, biri yox idi...", "Sonda...", "Nəticə budur ki...", "Salam!"], correctIndex: 0, xp: 10, explanation: "Nağıllar ənənəvi olaraq «Biri var idi, biri yox idi...» sözləri ilə başlayır." },
            { id: "az1-nagil-l1-t5", type: "multiple_choice", prompt: "Nağılın sonunda nə olur?", options: ["Adətən yaxşılıq qalib gəlir", "Heç nə", "Nağıl davam edir", "Sual verilir"], correctIndex: 0, xp: 10, explanation: "Nağılın sonunda yaxşı qəhrəman qalib gəlir, pislik isə cəzasını alır." },
            { id: "az1-nagil-l1-t6", type: "multiple_choice", prompt: "'Kim?' sualı nəyi soruşur?", options: ["Qəhrəmanı", "Yeri", "Vaxtı", "Səbəbi"], correctIndex: 0, xp: 10, explanation: "«Kim?» sualı canlıya verilir — nağılda bu, hadisələri yaşayan qəhrəmandır." },
            { id: "az1-nagil-l1-t7", type: "multiple_choice", prompt: "'Harada?' sualı nəyi soruşur?", options: ["Yeri", "Qəhrəmanı", "Vaxtı", "Sayı"], correctIndex: 0, xp: 10, explanation: "«Harada?» sualı hadisənin baş verdiyi yeri soruşur." },
            { id: "az1-nagil-l1-t8", type: "multiple_choice", prompt: "Nağıl bizə nə öyrədir?", options: ["Yaxşı və pisi ayırmağı", "Riyaziyyatı", "Coğrafiyanı", "Heç nə"], correctIndex: 0, xp: 10, explanation: "Nağılda yaxşı qəhrəman mükafat, pis obraz cəza alır — beləcə yaxşı ilə pisi ayırmağı öyrənirik." },
            { id: "az1-nagil-l1-t9", type: "multiple_choice", prompt: "Nağılı kim danışır?", options: ["Nağılçı", "Müəllim", "Həkim", "Sürücü"], correctIndex: 0, xp: 10, explanation: "Nağılı danışan adama nağılçı deyilir." },
            { id: "az1-nagil-l1-t10", type: "multiple_choice", prompt: "Nağılda 'qəhrəman' kimdir?", options: ["Əsas obraz", "Yazıçı", "Oxucu", "Kitab"], correctIndex: 0, xp: 10, explanation: "Qəhrəman nağılın əsas obrazıdır — hadisələr onun başına gəlir." },
          ],
          bonusTasks: [
            { id: "az1-nagil-l1-b1", type: "multiple_choice", prompt: "Nağılla real hekayə arasındakı fərq nədir?", options: ["Nağıl uydurmadır", "Fərq yoxdur", "Nağıl qısadır", "Nağıl uzundur"], correctIndex: 0, xp: 15, explanation: "Real hekayədəki hadisələr həqiqətən baş verib, nağıldakılar isə uydurmadır." },
            { id: "az1-nagil-l1-b2", type: "multiple_choice", prompt: "'Cırtdan' nağılında Cırtdan necədir?", options: ["Ağıllı və cəsur", "Qorxaq", "Tənbəl", "Nadinc"], correctIndex: 0, xp: 15, explanation: "Cırtdan balaca olsa da, divi ağlı ilə aldadır və dostlarını xilas edir — deməli ağıllı və cəsurdur." },
            { id: "az1-nagil-l1-b3", type: "multiple_choice", prompt: "Nağılı oxuyandan sonra nə etmək faydalıdır?", options: ["Danışıb müzakirə etmək", "Unutmaq", "Cırmaq", "Heç nə"], correctIndex: 0, xp: 15, explanation: "Nağılı danışıb müzakirə edəndə onun ibrətini daha yaxşı başa düşür və yadda saxlayırıq." },
            { id: "az1-nagil-l1-b4", type: "multiple_choice", prompt: "Nağılın 'ibrəti' nədir?", options: ["Öyrətdiyi dərs", "Adı", "Uzunluğu", "Şəkli"], correctIndex: 0, xp: 15, explanation: "İbrət nağılın bizə öyrətdiyi dərsdir — hadisələrdən çıxarılan nəticə." },
          ],
        },
        {
          id: "az1-nagil-l2",
          title: "Şeir və qafiyə",
          intro: "Şeirdə sözlər həmahəng bitir.",
          sections: [
            { heading: "Qafiyə", body: "Şeirdə sətirlərin sonu oxşar səslənir: 'gül' — 'bülbül', 'ana' — 'yana'." },
            { heading: "Şeir necədir?", body: "Şeir sətir-sətir yazılır, oxunanda ahəng yaranır." },
          ],
          tasks: [
            { id: "az1-nagil-l2-t1", type: "multiple_choice", prompt: "'gül' sözü ilə hansı qafiyələnir?", options: ["bülbül", "kitab", "ağac", "su"], correctIndex: 0, xp: 10, explanation: "«gül» və «bülbül» sözlərinin sonu eyni səslənir: -ül. Deməli qafiyələnir." },
            { id: "az1-nagil-l2-t2", type: "multiple_choice", prompt: "'ana' sözü ilə hansı qafiyələnir?", options: ["yana", "kitab", "dost", "gül"], correctIndex: 0, xp: 10, explanation: "«ana» və «yana» sözlərinin sonu eyni səslənir: -ana." },
            { id: "az1-nagil-l2-t3", type: "multiple_choice", prompt: "Qafiyə nədir?", options: ["Sətir sonlarının oxşar səslənməsi", "Sözün uzunluğu", "Hərflərin sayı", "Şeirin adı"], correctIndex: 0, xp: 10, explanation: "Qafiyə misraların sonundakı sözlərin oxşar səslənməsidir." },
            { id: "az1-nagil-l2-t4", type: "multiple_choice", prompt: "Şeir necə yazılır?", options: ["Sətir-sətir", "Bir bütöv abzas", "Cədvəl kimi", "Siyahı kimi"], correctIndex: 0, xp: 10, explanation: "Şeir sətir-sətir, yəni misralarla yazılır — hər misra ayrı sətirdə olur." },
            { id: "az1-nagil-l2-t5", type: "multiple_choice", prompt: "'top' sözü ilə hansı qafiyələnir?", options: ["hop", "kitab", "ana", "gül"], correctIndex: 0, xp: 10, explanation: "«top» və «hop» sözlərinin sonu eyni səslənir: -op." },
            { id: "az1-nagil-l2-t6", type: "multiple_choice", prompt: "Şeiri kim yazır?", options: ["Şair", "Həkim", "Müəllim", "Sürücü"], correctIndex: 0, xp: 10, explanation: "Şeir yazan adama şair deyilir." },
            { id: "az1-nagil-l2-t7", type: "multiple_choice", prompt: "'dost' sözü ilə hansı qafiyələnir?", options: ["post", "kitab", "alma", "su"], correctIndex: 0, xp: 10, explanation: "«dost» və «post» sözlərinin sonu eyni səslənir: -ost." },
            { id: "az1-nagil-l2-t8", type: "multiple_choice", prompt: "Şeirin bir sırası necə adlanır?", options: ["Misra", "Abzas", "Cümlə", "Söz"], correctIndex: 0, xp: 10, explanation: "Şeirin hər bir sırasına misra deyilir." },
            { id: "az1-nagil-l2-t9", type: "multiple_choice", prompt: "Şeiri oxuyanda nəyə diqqət etmək lazımdır?", options: ["Ahəngə və duyğuya", "Yalnız uzunluğa", "Yalnız hərflərə", "Heç nəyə"], correctIndex: 0, xp: 10, explanation: "Şeir sadəcə söz yığını deyil — onun ahəngi və bildirdiyi duyğu var, oxuyarkən buna diqqət edirik." },
            { id: "az1-nagil-l2-t10", type: "multiple_choice", prompt: "'quş' sözü ilə hansı qafiyələnir?", options: ["duş", "dost", "gül", "ana"], correctIndex: 0, xp: 10, explanation: "«quş» və «duş» sözlərinin sonu eyni səslənir: -uş. Dost, gül, ana isə fərqli bitir." },
          ],
          bonusTasks: [
            { id: "az1-nagil-l2-b1", type: "multiple_choice", prompt: "Niyə şeirdə qafiyə işlədilir?", options: ["Ahəng və yadda qalma üçün", "Uzatmaq üçün", "Çətinləşdirmək üçün", "Səbəbi yoxdur"], correctIndex: 0, xp: 15, explanation: "Qafiyə şeirə musiqi kimi ahəng verir və misraları yadda saxlamağı asanlaşdırır." },
            { id: "az1-nagil-l2-b2", type: "multiple_choice", prompt: "Nizami Gəncəvi kimdir?", options: ["Böyük Azərbaycan şairi", "Rəssam", "Həkim", "Müğənni"], correctIndex: 0, xp: 15, explanation: "Nizami Gəncəvi Gəncədə yaşamış, dünya şöhrətli poemalar yazmış böyük Azərbaycan şairidir." },
            { id: "az1-nagil-l2-b3", type: "multiple_choice", prompt: "Şeir və nağıl arasındakı əsas fərq nədir?", options: ["Şeir misralarla yazılır", "Fərq yoxdur", "Şeir uzundur", "Nağıl qafiyəlidir"], correctIndex: 0, xp: 15, explanation: "Nağıl adi cümlələrlə danışılır, şeir isə misralara bölünür və çox vaxt qafiyəli olur." },
            { id: "az1-nagil-l2-b4", type: "multiple_choice", prompt: "'bahar' sözü ilə hansı qafiyələnir?", options: ["nahar", "qış", "yay", "payız"], correctIndex: 0, xp: 15, explanation: "«bahar» və «nahar» sözlərinin sonu eyni səslənir: -ahar. Qış, yay, payız isə qafiyələnmir." },
          ],
        },
        {
          id: "az1-nagil-l3",
          title: "Tapmaca və atalar sözü",
          intro: "Xalq müdrikliyi qısa sözlərdə.",
          sections: [
            { heading: "Tapmaca", body: "Tapmaca gizli sual verir, cavabını tapmaq lazımdır: 'Ağzı var, dili yox' — kitab." },
            { heading: "Atalar sözü", body: "Qısa, müdrik fikir: 'Tələsən təndirə düşər', 'Vaxt qızıldır'." },
          ],
          tasks: [
            { id: "az1-nagil-l3-t1", type: "multiple_choice", prompt: "'Ağzı var, dili yox' tapmacasının cavabı nədir?", options: ["Kitab", "Quş", "İnsan", "Pişik"], correctIndex: 0, xp: 10, explanation: "Kitab açılanda sanki ağzı görünür, amma özü danışmır — fikri hərflərlə çatdırır." },
            { id: "az1-nagil-l3-t2", type: "multiple_choice", prompt: "Tapmaca nə üçündür?", options: ["Fikirləşdirmək üçün", "Güldürmək üçün", "Qorxutmaq üçün", "Heç nə üçün"], correctIndex: 0, xp: 10, explanation: "Tapmaca cavabı gizlədir və bizi düşünməyə, əlamətlərə görə tapmağa vadar edir." },
            { id: "az1-nagil-l3-t3", type: "multiple_choice", prompt: "'Vaxt qızıldır' nə deməkdir?", options: ["Vaxt çox dəyərlidir", "Qızıl bahalıdır", "Saat qızıldandır", "Vaxt keçir"], correctIndex: 0, xp: 10, explanation: "Qızıl kimi vaxt da çox qiymətlidir — itirilən vaxtı heç nə ilə geri qaytarmaq olmur." },
            { id: "az1-nagil-l3-t4", type: "multiple_choice", prompt: "'Tələsən təndirə düşər' nə öyrədir?", options: ["Tələsməmək lazımdır", "Tez getmək lazımdır", "Təndir təhlükəlidir", "Heç nə"], correctIndex: 0, xp: 10, explanation: "Təndirə düşmək bədbəxtlik deməkdir. Tələsən adam səhv edib zərər çəkir — deməli tələsməmək lazımdır." },
            { id: "az1-nagil-l3-t5", type: "multiple_choice", prompt: "Atalar sözü kimindir?", options: ["Xalqın", "Bir şairin", "Müəllimin", "Kitabın"], correctIndex: 0, xp: 10, explanation: "Atalar sözlərini müəyyən bir adam yazmayıb — onları xalq əsrlər boyu yaradıb və nəsildən-nəslə ötürüb." },
            { id: "az1-nagil-l3-t6", type: "multiple_choice", prompt: "'Bir əldə iki qarpız tutulmaz' nə öyrədir?", options: ["Bir işə cəm ol", "İki qarpız ağırdır", "Qarpız yemə", "Heç nə"], correctIndex: 0, xp: 10, explanation: "İki qarpızı bir əldə tutmaq mümkün olmadığı kimi, eyni anda iki işi də yaxşı görmək olmur — bir işə cəm olmaq lazımdır." },
            { id: "az1-nagil-l3-t7", type: "multiple_choice", prompt: "Tapmacanın cavabı harada olur?", options: ["Gizli, tapmaq lazımdır", "Sualın içində", "Kitabın sonunda", "Yoxdur"], correctIndex: 0, xp: 10, explanation: "Tapmacada cavab birbaşa deyilmir, əlamətlərin arxasında gizlədilir — onu düşünüb tapmalıyıq." },
            { id: "az1-nagil-l3-t8", type: "multiple_choice", prompt: "'Sözün düzü' nə deməkdir?", options: ["Doğru söz", "Uzun söz", "Gözəl söz", "Çətin söz"], correctIndex: 0, xp: 10, explanation: "«Sözün düzü» olduğu kimi, həqiqəti söyləyən doğru sözü bildirir." },
            { id: "az1-nagil-l3-t9", type: "multiple_choice", prompt: "Atalar sözləri necədir?", options: ["Qısa və müdrik", "Uzun və çətin", "Uydurma", "Mənasız"], correctIndex: 0, xp: 10, explanation: "Atalar sözləri qısa olur, amma içində xalqın uzun illərlik təcrübəsi və müdrikliyi var." },
            { id: "az1-nagil-l3-t10", type: "multiple_choice", prompt: "'Oxumaq gücdür' ifadəsi nə öyrədir?", options: ["Bilik güc verir", "Kitab ağırdır", "Oxumaq çətindir", "Heç nə"], correctIndex: 0, xp: 10, explanation: "Oxuyan adam çox şey bilir, bilik isə insana güc və üstünlük verir." },
          ],
          bonusTasks: [
            { id: "az1-nagil-l3-b1", type: "multiple_choice", prompt: "'Damcı-damcı göl olar' nə öyrədir?", options: ["Az-az yığmaqla çox olar", "Yağış yağır", "Göl böyükdür", "Damcı kiçikdir"], correctIndex: 0, xp: 15, explanation: "Bir damcı azdır, amma damcılar toplanıb göl əmələ gətirir — az-az yığılan şey zamanla çox olur." },
            { id: "az1-nagil-l3-b2", type: "multiple_choice", prompt: "'Qonşu qonşuya baxar, canını oda yaxar' nə öyrədir?", options: ["Başqasını təqlid etmə", "Qonşu pisdir", "Odla oyna", "Heç nə"], correctIndex: 0, xp: 15, explanation: "Qonşuya baxıb onun kimi etməyə çalışan adam öz imkanını aşır və zərər çəkir — başqasını təqlid etmək düzgün deyil." },
            { id: "az1-nagil-l3-b3", type: "multiple_choice", prompt: "Tapmaca ilə atalar sözü arasındakı fərq nədir?", options: ["Tapmacada cavab tapılır, atalar sözü nəsihət verir", "Fərq yoxdur", "Biri uzundur", "Biri şeirdir"], correctIndex: 0, xp: 15, explanation: "Tapmacada gizli cavabı özümüz tapmalıyıq, atalar sözü isə hazır nəsihət verir." },
            { id: "az1-nagil-l3-b4", type: "multiple_choice", prompt: "'Yaxşılıq et, dənizə at' nə öyrədir?", options: ["Yaxşılığı əvəzsiz et", "Dənizə get", "Bir şey atma", "Heç nə"], correctIndex: 0, xp: 15, explanation: "Dənizə atılan şey geri qayıtmır. Deməli yaxşılığı əvəz gözləmədən etmək lazımdır." },
          ],
        },
        {
          id: "az1-nagil-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az1-nagil-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
  ],
};
