// Azərbaycan dili — 5-ci sinif proqramı. Bölmələrin sırası kurikuluma uyğundur:
// 1) Dil qaydaları (Qrammatika)  2) Yazı və oxu mədəniyyəti  3) Nitq bacarıqları.
// Hər dərs bir layihədir (project). Standart: 15 əsas + 5 bonus tapşırıq.
// Qeyd: Fonetika, Leksika və Nitq hissələri (İsim/Sifət/Feil) tamdır; qalan mövzular
// struktur + qaydalar + başlanğıc tapşırıqlarla verilib, mərhələli olaraq 15+5-ə dolacaq.

import type { Subject } from "../types";

export const azerbaijani: Subject = {
  slug: "azerbaycan-dili",
  name: "Azərbaycan dili",
  grade: 5,
  icon: "A",
  color: "rose",
  units: [
    // ═══════════════ 1. Dil qaydaları (Qrammatika) ═══════════════
    {
      id: "az-grammar",
      title: "Dil qaydaları (Qrammatika)",
      description:
        "Fonetika, leksika, söz yaradıcılığı, nitq hissələri və sintaksis.",
      lessons: [
        {
          id: "az-fonetika",
          title: "Fonetika: səslər və hərflər",
          intro: "Səs və hərf, sait və samitlər, heca və vurğu.",
          visual: "fonetika",
          sections: [
            { heading: "Səs və hərf", body: "Danışarkən tələffüz etdiyimiz — səsdir; yazıda onu göstərən işarə — hərfdir. Azərbaycan əlifbasında 32 hərf var." },
            { heading: "Saitlər", body: "Ağız boşluğunda sərbəst tələffüz olunan səslər saitdir. Azərbaycan dilində 9 sait var: a, ı, o, u, e, ə, i, ö, ü. Qalın saitlər: a, ı, o, u; incə saitlər: e, ə, i, ö, ü." },
            { heading: "Samitlər", body: "Tələffüzdə maneəyə rast gələn səslər samitdir. Samitlər kar və cingiltili olur." },
            { heading: "Heca və vurğu", body: "Söz saitlərin sayı qədər hecaya bölünür. Vurğu adətən sözün son hecasına düşür." },
          ],
          tasks: [
            { id: "az-fonetika-t1", type: "multiple_choice", prompt: "Azərbaycan əlifbasında neçə hərf var?", options: ["26", "29", "32", "33"], correctIndex: 2, xp: 10, skills: ["az.phon.alphabet"] },
            { id: "az-fonetika-t2", type: "multiple_choice", prompt: "'a, ı, o, u' hansı saitlərdir?", options: ["qalın", "incə", "kar", "cingiltili"], correctIndex: 0, xp: 10, skills: ["az.phon.vowels"] },
            { id: "az-fonetika-t3", type: "multiple_choice", prompt: "Azərbaycan dilində neçə sait var?", options: ["7", "8", "9", "10"], correctIndex: 2, xp: 10, skills: ["az.phon.vowels"] },
            { id: "az-fonetika-t4", type: "numeric", prompt: "'Kitab' sözündə neçə heca var?", answer: 2, xp: 10, skills: ["az.phon.syllable"] },
            { id: "az-fonetika-t5", type: "multiple_choice", prompt: "Aşağıdakılardan hansı incə saitdir?", options: ["a", "o", "ə", "ı"], correctIndex: 2, xp: 10, skills: ["az.phon.vowels"] },
            { id: "az-fonetika-t6", type: "multiple_choice", prompt: "Yazıda səsi göstərən işarə necə adlanır?", options: ["səs", "hərf", "heca", "vurğu"], correctIndex: 1, xp: 10, skills: ["az.phon.letters"] },
            { id: "az-fonetika-t7", type: "numeric", prompt: "'Məktəb' sözündə neçə heca var?", answer: 2, xp: 10, skills: ["az.phon.syllable"] },
            { id: "az-fonetika-t8", type: "multiple_choice", prompt: "Aşağıdakılardan hansı samitdir?", options: ["a", "e", "m", "ü"], correctIndex: 2, xp: 10, skills: ["az.phon.consonants"] },
            { id: "az-fonetika-t9", type: "fill_blank", prompt: "Söz ___ səslərin sayı qədər hecaya bölünür.", accepted: ["sait", "saitlərin", "saitlerin"], xp: 10, skills: ["az.phon.syllable","az.pos.numeral"] },
            { id: "az-fonetika-t10", type: "multiple_choice", prompt: "Vurğu adətən sözün hansı hecasına düşür?", options: ["birinci", "ortadakı", "son", "heç birinə"], correctIndex: 2, xp: 10, skills: ["az.phon.syllable","az.phon.stress"] },
            { id: "az-fonetika-t11", type: "multiple_choice", prompt: "'o' və 'ö' saitlərindən hansı incədir?", options: ["o", "ö", "hər ikisi", "heç biri"], correctIndex: 1, xp: 10, skills: ["az.phon.vowels"] },
            { id: "az-fonetika-t12", type: "numeric", prompt: "'Alma' sözündə neçə sait var?", answer: 2, xp: 10, skills: ["az.phon.vowels"] },
            { id: "az-fonetika-t13", type: "multiple_choice", prompt: "Sait səslər necə tələffüz olunur?", options: ["maneə ilə", "sərbəst", "kar", "cingiltili"], correctIndex: 1, xp: 10, skills: ["az.phon.vowels"] },
            { id: "az-fonetika-t14", type: "multiple_choice", prompt: "Aşağıdakılardan hansı qalın saitdir?", options: ["i", "e", "u", "ö"], correctIndex: 2, xp: 10, skills: ["az.phon.vowels"] },
            { id: "az-fonetika-t15", type: "multiple_choice", prompt: "Səslərin yazıdakı işarələri toplusu necə adlanır?", options: ["heca", "əlifba", "vurğu", "səs"], correctIndex: 1, xp: 15, skills: ["az.phon.letters"] },
          ],
          bonusTasks: [
            { id: "az-fonetika-b1", type: "multiple_choice", prompt: "'ü' saiti qalındır, yoxsa incə?", options: ["qalın", "incə"], correctIndex: 1, xp: 15, skills: ["az.phon.vowels","az.phon.harmony"] },
            { id: "az-fonetika-b2", type: "numeric", prompt: "'Gözəllik' sözündə neçə heca var?", answer: 3, xp: 15, skills: ["az.phon.syllable"] },
            { id: "az-fonetika-b3", type: "fill_blank", prompt: "Samitlər ___ və cingiltili olur.", accepted: ["kar"], xp: 15, skills: ["az.phon.consonants"] },
            { id: "az-fonetika-b4", type: "multiple_choice", prompt: "Hansı qrupda yalnız saitlər var?", options: ["a, ə, o", "b, c, d", "a, b, c", "m, n, s"], correctIndex: 0, xp: 15, skills: ["az.phon.vowels"] },
            { id: "az-fonetika-b5", type: "numeric", prompt: "'Su' sözündə neçə səs var?", answer: 2, xp: 15, skills: ["az.phon.letters"] },
          ],
        },
        {
          id: "az-leksika",
          title: "Leksika: sözün mənası",
          intro: "Həqiqi və məcazi məna, sinonim, antonim, omonim, frazeologizm.",
          visual: "leksika",
          sections: [
            { heading: "Həqiqi və məcazi məna", body: "Sözün əsl mənası həqiqi, obrazlı işlənməsi məcazi mənadır. Məsələn: 'dəmir qapı' (həqiqi), 'dəmir iradə' (məcazi)." },
            { heading: "Sinonim və antonim", body: "Mənaca yaxın sözlər sinonim (gözəl–qəşəng), əks mənalı sözlər antonimdir (böyük–kiçik)." },
            { heading: "Omonim və çoxmənalılıq", body: "Eyni yazılıb-tələffüz olunan, mənaca fərqli sözlər omonimdir (üz – sifət / üz – üzmək). Çoxmənalı söz bir neçə əlaqəli məna daşıyır." },
            { heading: "Frazeoloji birləşmə", body: "Sözlərin sabit, obrazlı birləşməsi frazeologizmdir: əl-ələ vermək, ağzını açmaq." },
          ],
          tasks: [
            { id: "az-leksika-t1", type: "multiple_choice", prompt: "'gözəl' sözünün sinonimi hansıdır?", options: ["çirkin", "qəşəng", "böyük", "ağ"], correctIndex: 1, xp: 10, skills: ["az.lex.synonym"] },
            { id: "az-leksika-t2", type: "multiple_choice", prompt: "'böyük' sözünün antonimi hansıdır?", options: ["geniş", "balaca", "hündür", "uzun"], correctIndex: 1, xp: 10, skills: ["az.lex.antonym"] },
            { id: "az-leksika-t3", type: "multiple_choice", prompt: "'dəmir iradə' birləşməsində 'dəmir' hansı mənadadır?", options: ["həqiqi", "məcazi"], correctIndex: 1, xp: 10, skills: ["az.phon.harmony"] },
            { id: "az-leksika-t4", type: "multiple_choice", prompt: "Mənaca əks olan sözlər necə adlanır?", options: ["sinonim", "antonim", "omonim", "frazeologizm"], correctIndex: 1, xp: 10, skills: ["az.phon.harmony"] },
            { id: "az-leksika-t5", type: "fill_blank", prompt: "Mənaca yaxın sözlər ___ adlanır.", accepted: ["sinonim", "sinonimlər", "sinonimler"], xp: 10, skills: ["az.phon.harmony"] },
            { id: "az-leksika-t6", type: "multiple_choice", prompt: "'isti' sözünün antonimi hansıdır?", options: ["ilıq", "soyuq", "qaynar", "yay"], correctIndex: 1, xp: 10, skills: ["az.lex.antonym"] },
            { id: "az-leksika-t7", type: "multiple_choice", prompt: "'üz' (sifət) və 'üz' (üzmək) sözləri hansı hadisədir?", options: ["sinonim", "omonim", "antonim", "frazeologizm"], correctIndex: 1, xp: 10, skills: ["az.pos.adjective"] },
            { id: "az-leksika-t8", type: "multiple_choice", prompt: "'qaranlıq' sözünün antonimi hansıdır?", options: ["qara", "işıqlı", "gecə", "tünd"], correctIndex: 1, xp: 10, skills: ["az.lex.antonym"] },
            { id: "az-leksika-t9", type: "multiple_choice", prompt: "'cəsur' sözünün sinonimi hansıdır?", options: ["qorxaq", "igid", "zəif", "sakit"], correctIndex: 1, xp: 10, skills: ["az.lex.synonym"] },
            { id: "az-leksika-t10", type: "multiple_choice", prompt: "'əl-ələ vermək' ifadəsi nədir?", options: ["frazeoloji birləşmə", "omonim", "antonim", "sinonim"], correctIndex: 0, xp: 10, skills: ["az.phon.harmony"] },
            { id: "az-leksika-t11", type: "fill_blank", prompt: "Sözün əsl mənası ___ məna adlanır.", accepted: ["həqiqi", "heqiqi"], xp: 10, skills: ["az.phon.harmony"] },
            { id: "az-leksika-t12", type: "multiple_choice", prompt: "'ağ' sözünün antonimi hansıdır?", options: ["boz", "qara", "sarı", "mavi"], correctIndex: 1, xp: 10, skills: ["az.lex.antonym"] },
            { id: "az-leksika-t13", type: "multiple_choice", prompt: "'sevincli' sözünün sinonimi hansıdır?", options: ["kədərli", "şad", "yorğun", "acıqlı"], correctIndex: 1, xp: 10, skills: ["az.lex.synonym"] },
            { id: "az-leksika-t14", type: "multiple_choice", prompt: "'yuxulu — oyaq' cütü hansı hadisədir?", options: ["sinonim", "antonim", "omonim", "frazeologizm"], correctIndex: 1, xp: 10, skills: ["az.phon.harmony"] },
            { id: "az-leksika-t15", type: "multiple_choice", prompt: "Eyni cür yazılıb fərqli məna daşıyan sözlər necə adlanır?", options: ["sinonim", "omonim", "antonim", "frazeologizm"], correctIndex: 1, xp: 15, skills: ["az.phon.harmony"] },
          ],
          bonusTasks: [
            { id: "az-leksika-b1", type: "multiple_choice", prompt: "'sürətli' sözünün sinonimi hansıdır?", options: ["yavaş", "iti", "ağır", "sakit"], correctIndex: 1, xp: 15, skills: ["az.lex.synonym"] },
            { id: "az-leksika-b2", type: "multiple_choice", prompt: "'dost' sözünün antonimi hansıdır?", options: ["yoldaş", "düşmən", "qonşu", "tanış"], correctIndex: 1, xp: 15, skills: ["az.lex.antonym"] },
            { id: "az-leksika-b3", type: "fill_blank", prompt: "'Ağzını açmaq' ifadəsi ___ birləşmədir.", accepted: ["frazeoloji", "frazeologizm"], xp: 15, skills: ["az.phon.harmony"] },
            { id: "az-leksika-b4", type: "multiple_choice", prompt: "'acı' sözünün antonimi hansıdır?", options: ["şor", "şirin", "turş", "duzlu"], correctIndex: 1, xp: 15, skills: ["az.lex.antonym"] },
            { id: "az-leksika-b5", type: "multiple_choice", prompt: "'zəngin' sözünün sinonimi hansıdır?", options: ["kasıb", "varlı", "yoxsul", "sadə"], correctIndex: 1, xp: 15, skills: ["az.lex.synonym"] },
          ],
        },
        {
          id: "az-grammar-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az-soz-yaradiciligi",
          title: "Söz yaradıcılığı",
          intro: "Sözün kökü, şəkilçilər və sözün tərkibi.",
          sections: [
            { heading: "Kök və şəkilçi", body: "Sözün əsas mənalı hissəsi kök, sonuna əlavə olunan hissə şəkilçidir. Məsələn, 'meşəlik' sözündə kök 'meşə', şəkilçi '-lik'-dir." },
            { heading: "Leksik və qrammatik şəkilçi", body: "Leksik şəkilçi yeni söz düzəldir (kitab → kitabçı). Qrammatik şəkilçi sözü dəyişir, yeni söz yaratmır (kitab → kitablar)." },
            { heading: "Başlanğıc forma", body: "Sözün şəkilçisiz, əsas forması onun başlanğıc formasıdır." },
          ],
          tasks: [
            { id: "az-soz-t1", type: "multiple_choice", prompt: "'meşəlik' sözündə kök hansıdır?", options: ["meşə", "lik", "meşəl", "əlik"], correctIndex: 0, xp: 10, skills: ["az.morph.root"] },
            { id: "az-soz-t2", type: "fill_blank", prompt: "'Kitabçı' sözündəki şəkilçini yaz.", accepted: ["-çı", "çı"], xp: 10, skills: ["az.morph.root"] },
            { id: "az-soz-t3", type: "multiple_choice", prompt: "Yeni söz düzəldən şəkilçi necə adlanır?", options: ["leksik", "qrammatik"], correctIndex: 0, xp: 10, skills: ["az.morph.root"] },
            { id: "az-soz-t4", type: "multiple_choice", prompt: "'evlər' sözündə '-lər' hansı şəkilçidir?", options: ["leksik", "qrammatik"], correctIndex: 1, xp: 10, skills: ["az.morph.root"] },
            { id: "az-soz-t5", type: "multiple_choice", prompt: "Sözün əsas mənalı hissəsi necə adlanır?", options: ["kök", "şəkilçi", "vurğu", "heca"], correctIndex: 0, xp: 10, skills: ["az.phon.letters"] },
            { id: "az-soz-t6", type: "multiple_choice", prompt: "'gülüş' sözündə kök hansıdır?", options: ["gül", "üş", "gülü", "lüş"], correctIndex: 0, xp: 10, skills: ["az.morph.root"] },
            { id: "az-soz-t7", type: "multiple_choice", prompt: "'işçi' sözündə şəkilçi hansıdır?", options: ["-çi", "iş", "işç", "çı"], correctIndex: 0, xp: 10, skills: ["az.morph.root"] },
            { id: "az-soz-t8", type: "fill_blank", prompt: "Sözün əsas mənalı hissəsi ___ adlanır.", accepted: ["kök", "kok"], xp: 10, skills: ["az.phon.letters"] },
            { id: "az-soz-t9", type: "multiple_choice", prompt: "'duzlu' sözündə '-lu' hansı şəkilçidir?", options: ["leksik", "qrammatik"], correctIndex: 0, xp: 10, skills: ["az.morph.root"] },
            { id: "az-soz-t10", type: "multiple_choice", prompt: "'qələmlər' sözündə '-lər' hansı şəkilçidir?", options: ["leksik", "qrammatik"], correctIndex: 1, xp: 10, skills: ["az.morph.root"] },
            { id: "az-soz-t11", type: "multiple_choice", prompt: "'meyvəçi' sözündə kök hansıdır?", options: ["meyvə", "çi", "meyv", "əçi"], correctIndex: 0, xp: 10, skills: ["az.morph.root"] },
            { id: "az-soz-t12", type: "fill_blank", prompt: "'Kitablar' sözünün başlanğıc (şəkilçisiz) forması ___-dır.", accepted: ["kitab"], xp: 10, skills: ["az.morph.root"] },
            { id: "az-soz-t13", type: "multiple_choice", prompt: "Aşağıdakı şəkilçilərdən hansı yeni söz düzəldir?", options: ["-lar", "-çı", "-ə", "-i"], correctIndex: 1, xp: 10, skills: ["az.morph.root"] },
            { id: "az-soz-t14", type: "multiple_choice", prompt: "'sözlük' sözündə kök hansıdır?", options: ["söz", "lük", "sözl", "özlük"], correctIndex: 0, xp: 10, skills: ["az.morph.root"] },
            { id: "az-soz-t15", type: "multiple_choice", prompt: "Sözü dəyişən, amma yeni söz yaratmayan şəkilçi necə adlanır?", options: ["leksik", "qrammatik"], correctIndex: 1, xp: 15, skills: ["az.morph.root"] },
          ],
          bonusTasks: [
            { id: "az-soz-b1", type: "multiple_choice", prompt: "'balıqçı' sözündə şəkilçi hansıdır?", options: ["-çı", "balıq", "-ıq", "balı"], correctIndex: 0, xp: 15, skills: ["az.morph.root"] },
            { id: "az-soz-b2", type: "fill_blank", prompt: "'-lar / -lər' ___ şəkilçidir. (leksik / qrammatik)", accepted: ["qrammatik"], xp: 15, skills: ["az.morph.root"] },
            { id: "az-soz-b3", type: "multiple_choice", prompt: "'yolçu' sözündə kök hansıdır?", options: ["yol", "çu", "yolç", "olçu"], correctIndex: 0, xp: 15, skills: ["az.morph.root"] },
            { id: "az-soz-b4", type: "multiple_choice", prompt: "Hansı sözdə leksik şəkilçi var?", options: ["evlər", "işçi", "kitabı", "gülə"], correctIndex: 1, xp: 15, skills: ["az.morph.root"] },
            { id: "az-soz-b5", type: "multiple_choice", prompt: "'gözlük' sözündə kök hansıdır?", options: ["göz", "lük", "gözl", "özlük"], correctIndex: 0, xp: 15, skills: ["az.morph.root"] },
          ],
        },
        {
          id: "az-sintaksis",
          title: "Sintaksis: söz birləşməsi və cümlə",
          intro: "Söz birləşmələri, cümlənin növləri və üzvləri.",
          sections: [
            { heading: "Söz birləşməsi və cümlə", body: "İki və daha çox sözün mənaca əlaqəsi söz birləşməsidir. Fikri bitkin ifadə edən söz qrupu cümlədir." },
            { heading: "Məqsədə görə cümlələr", body: "Nəqli (məlumat verir), sual (soruşur), əmr (əmr edir) və nida (güclü hiss bildirir) cümlələri." },
            { heading: "Cümlə üzvləri", body: "Mübtəda iş görəni, xəbər isə işi bildirir. Məsələn, 'Uşaq oxuyur' cümləsində 'uşaq' mübtəda, 'oxuyur' xəbərdir." },
          ],
          tasks: [
            { id: "az-sintaksis-t1", type: "multiple_choice", prompt: "Fikri bitkin ifadə edən söz qrupu necə adlanır?", options: ["söz", "heca", "cümlə", "hərf"], correctIndex: 2, xp: 10, skills: ["az.phon.harmony"] },
            { id: "az-sintaksis-t2", type: "multiple_choice", prompt: "'Kitab oxu!' hansı cümlədir?", options: ["nəqli", "sual", "əmr", "nida"], correctIndex: 2, xp: 10, skills: ["az.syn.sentence"] },
            { id: "az-sintaksis-t3", type: "multiple_choice", prompt: "Sonunda sual işarəsi olan cümlə necə adlanır?", options: ["nəqli", "sual", "nida", "əmr"], correctIndex: 1, xp: 10, skills: ["az.syn.sentence"] },
            { id: "az-sintaksis-t4", type: "fill_blank", prompt: "Cümlədə iş görəni bildirən üzv ___ adlanır.", accepted: ["mübtəda", "mubteda"], xp: 10, skills: ["az.syn.sentence"] },
            { id: "az-sintaksis-t5", type: "multiple_choice", prompt: "'Uşaq oxuyur' cümləsində xəbər hansıdır?", options: ["uşaq", "oxuyur", "hər ikisi", "heç biri"], correctIndex: 1, xp: 10, skills: ["az.syn.main_parts"] },
            { id: "az-sintaksis-t6", type: "multiple_choice", prompt: "'Hava çox gözəldir!' hansı cümlədir?", options: ["nəqli", "sual", "əmr", "nida"], correctIndex: 3, xp: 10, skills: ["az.syn.sentence"] },
            { id: "az-sintaksis-t7", type: "multiple_choice", prompt: "'Mən məktəbə gedirəm.' hansı cümlədir?", options: ["nəqli", "sual", "əmr", "nida"], correctIndex: 0, xp: 10, skills: ["az.syn.sentence"] },
            { id: "az-sintaksis-t8", type: "fill_blank", prompt: "Cümlədə işi, hərəkəti bildirən üzv ___ adlanır.", accepted: ["xəbər", "xeber"], xp: 10, skills: ["az.syn.sentence"] },
            { id: "az-sintaksis-t9", type: "multiple_choice", prompt: "'Quşlar uçur' cümləsində mübtəda hansıdır?", options: ["quşlar", "uçur", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, skills: ["az.syn.main_parts"] },
            { id: "az-sintaksis-t10", type: "multiple_choice", prompt: "İki və daha çox sözün mənaca əlaqəsi necə adlanır?", options: ["cümlə", "söz birləşməsi", "heca", "hərf"], correctIndex: 1, xp: 10, skills: ["az.phon.harmony"] },
            { id: "az-sintaksis-t11", type: "multiple_choice", prompt: "'Sən hara gedirsən?' hansı cümlədir?", options: ["nəqli", "sual", "əmr", "nida"], correctIndex: 1, xp: 10, skills: ["az.syn.sentence"] },
            { id: "az-sintaksis-t12", type: "fill_blank", prompt: "'Uşaq oxuyur' cümləsində mübtəda ___ sözüdür.", accepted: ["uşaq", "usaq"], xp: 10, skills: ["az.syn.main_parts"] },
            { id: "az-sintaksis-t13", type: "multiple_choice", prompt: "Əmr bildirən cümlə necə adlanır?", options: ["nəqli", "əmr", "sual", "nida"], correctIndex: 1, xp: 10, skills: ["az.syn.sentence"] },
            { id: "az-sintaksis-t14", type: "multiple_choice", prompt: "'Gözəl mənzərə' — bu nədir?", options: ["cümlə", "söz birləşməsi", "heca", "mətn"], correctIndex: 1, xp: 10, skills: ["az.phon.harmony"] },
            { id: "az-sintaksis-t15", type: "multiple_choice", prompt: "'Anam çörək bişirir' cümləsində xəbər hansıdır?", options: ["anam", "çörək", "bişirir", "heç biri"], correctIndex: 2, xp: 15, skills: ["az.syn.main_parts"] },
          ],
          bonusTasks: [
            { id: "az-sintaksis-b1", type: "multiple_choice", prompt: "Cümlənin baş üzvləri hansılardır?", options: ["mübtəda və xəbər", "isim və feil", "kök və şəkilçi", "sait və samit"], correctIndex: 0, xp: 15, skills: ["az.syn.sentence"] },
            { id: "az-sintaksis-b2", type: "fill_blank", prompt: "Məlumat verən cümlə ___ cümlədir.", accepted: ["nəqli", "neqli"], xp: 15, skills: ["az.syn.sentence"] },
            { id: "az-sintaksis-b3", type: "multiple_choice", prompt: "'Nə gözəl gün!' hansı cümlədir?", options: ["nida", "sual", "nəqli", "əmr"], correctIndex: 0, xp: 15, skills: ["az.syn.sentence"] },
            { id: "az-sintaksis-b4", type: "multiple_choice", prompt: "Fikri bitkin ifadə edən söz qrupu necə adlanır?", options: ["cümlə", "söz birləşməsi", "heca", "vurğu"], correctIndex: 0, xp: 15, skills: ["az.phon.harmony"] },
            { id: "az-sintaksis-b5", type: "multiple_choice", prompt: "Cümlə adətən nə ilə bitir?", options: ["durğu işarəsi", "həmişə vergül", "heca", "kök"], correctIndex: 0, xp: 15, skills: ["az.syn.sentence"] },
          ],
        },
        {
          id: "az-grammar-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        }
      ],
    },

    // ═══════════════ 2. Nitq hissələri ═══════════════
    {
      id: "az-parts-of-speech",
      title: "Nitq hissələri",
      description:
        "İsim, sifət, say, əvəzlik, feil və zərf — sözlərin mənaca qrupları.",
      lessons: [
        {
          id: "az-u1-l1",
          title: "İsim",
          intro: "İsim əşyaların adıdır.",
          visual: "noun-cards",
          sections: [
            { heading: "İsim nədir?", body: "İsim əşyaların, insanların, canlıların və yerlərin adını bildirən nitq hissəsidir." },
            { heading: "kim? / nə?", body: "Canlılar 'kim?' sualına cavab verir (uşaq, quş). Cansız əşyalar 'nə?' sualına cavab verir (alma, kitab)." },
            { heading: "Ümumi və xüsusi isim", body: "Ümumi isim ortaq adı bildirir (şəhər, çay). Xüsusi isim konkret addır və həmişə böyük hərflə yazılır (Bakı, Nigar)." },
          ],
          tasks: [
            { id: "az-u1-l1-t1", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı isimdir?", options: ["gözəl", "oxumaq", "pəncərə", "tez"], correctIndex: 2, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-u1-l1-t2", type: "multiple_choice", prompt: "Hansı söz 'kim?' sualına cavab verir?", options: ["daş", "müəllim", "yaşıl", "qaçmaq"], correctIndex: 1, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-u1-l1-t3", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı xüsusi isimdir?", options: ["şəhər", "Gəncə", "çay", "dağ"], correctIndex: 1, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-u1-l1-t4", type: "fill_blank", prompt: "'Kitablar' sözündəki cəm şəkilçisini yaz.", accepted: ["-lar", "lar"], xp: 10, skills: ["az.morph.root","az.pos.noun_possess"] },
            { id: "az-u1-l1-t5", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı 'nə?' sualına cavab verir?", options: ["dost", "sərçə", "alma", "bacı"], correctIndex: 2, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-u1-l1-t6", type: "fill_blank", prompt: "Xüsusi isimlər həmişə ___ hərflə yazılır.", accepted: ["böyük", "boyuk"], xp: 10, skills: ["az.phon.letters","az.pos.noun","az.orth.capital"] },
            { id: "az-u1-l1-t7", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı isimdir?", options: ["qırmızı", "dəniz", "sürətli", "oxumaq"], correctIndex: 1, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-u1-l1-t8", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı xüsusi isimdir?", options: ["ölkə", "Azərbaycan", "şəhər", "kənd"], correctIndex: 1, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-u1-l1-t9", type: "fill_blank", prompt: "İsim 'kim?' və '___?' suallarına cavab verir.", accepted: ["nə", "ne"], xp: 10, skills: ["az.pos.noun"] },
            { id: "az-u1-l1-t10", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı 'kim?' sualına cavab verir?", options: ["ana", "daş", "qapı", "su"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-u1-l1-t11", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı ümumi isimdir?", options: ["Nigar", "dağ", "Gəncə", "Xəzər"], correctIndex: 1, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-u1-l1-t12", type: "fill_blank", prompt: "'Bakı' sözü ___ isimdir. (ümumi / xüsusi)", accepted: ["xüsusi", "xususi"], xp: 10, skills: ["az.pos.noun"] },
            { id: "az-u1-l1-t13", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı cansız əşyanın adıdır?", options: ["pişik", "quş", "kitab", "uşaq"], correctIndex: 2, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-u1-l1-t14", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı cəm haldadır?", options: ["gül", "güllər", "gülü", "gülə"], correctIndex: 1, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-u1-l1-t15", type: "fill_blank", prompt: "İnsan adları ___ isimlərdir. (ümumi / xüsusi)", accepted: ["xüsusi", "xususi"], xp: 15, skills: ["az.pos.noun"] },
          ],
          bonusTasks: [
            { id: "az-u1-l1-b1", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı isim deyil?", options: ["pəncərə", "stol", "gözəl", "quş"], correctIndex: 2, xp: 15, skills: ["az.pos.noun"] },
            { id: "az-u1-l1-b2", type: "multiple_choice", prompt: "Aşağıdakılardan hansı düzgün yazılıb?", options: ["bakı", "Bakı", "BAKı", "baKı"], correctIndex: 1, xp: 15, skills: ["az.orth.spelling"] },
            { id: "az-u1-l1-b3", type: "fill_blank", prompt: "'Şagirdlər' sözündəki cəm şəkilçisini yaz.", accepted: ["-lər", "lər"], xp: 15, skills: ["az.morph.root","az.pos.noun_possess"] },
            { id: "az-u1-l1-b4", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı 'nə?' sualına cavab verir?", options: ["müəllim", "dost", "ağac", "bacı"], correctIndex: 2, xp: 15, skills: ["az.pos.noun"] },
            { id: "az-u1-l1-b5", type: "multiple_choice", prompt: "Hansı qrup yalnız isimlərdən ibarətdir?", options: ["ev, kitab, quş", "gözəl, ev, qaçmaq", "getmək, oxumaq, yazmaq", "ağ, qırmızı, yaşıl"], correctIndex: 0, xp: 15, skills: ["az.pos.noun"] },
          ],
        },
        {
          id: "az-u1-l2",
          title: "Sifət",
          intro: "Sifət əşyanın necə olduğunu bildirir.",
          visual: "adjective-apple",
          sections: [
            { heading: "Sifət nədir?", body: "Sifət əşyanın əlamətini, keyfiyyətini və ya rəngini bildirən nitq hissəsidir." },
            { heading: "Suallar", body: "Sifət 'necə?' və 'hansı?' suallarına cavab verir və çox zaman ismin yanında işlənir (qırmızı alma)." },
            { heading: "Nümunələr", body: "Sifət rəngi (ağ), ölçünü (böyük), dadı (şirin) və formanı (yumru) bildirə bilər." },
          ],
          tasks: [
            { id: "az-u1-l2-t1", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı sifətdir?", options: ["qələm", "şirin", "getmək", "şagird"], correctIndex: 1, xp: 10, skills: ["az.pos.adjective"] },
            { id: "az-u1-l2-t2", type: "multiple_choice", prompt: "'Hündür ağac' birləşməsində sifət hansıdır?", options: ["hündür", "ağac", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, skills: ["az.pos.adjective"] },
            { id: "az-u1-l2-t3", type: "multiple_choice", prompt: "Sifət aşağıdakı suallardan hansına cavab verir?", options: ["kim?", "nə?", "necə?", "harada?"], correctIndex: 2, xp: 10, skills: ["az.pos.adjective"] },
            { id: "az-u1-l2-t4", type: "fill_blank", prompt: "'Böyük ev' birləşməsində əşyanın əlamətini bildirən sözü yaz.", accepted: ["böyük", "boyuk"], xp: 10, skills: ["az.pos.noun"] },
            { id: "az-u1-l2-t5", type: "multiple_choice", prompt: "Aşağıdakılardan hansı rəng bildirən sifətdir?", options: ["yumru", "yaşıl", "acı", "kiçik"], correctIndex: 1, xp: 10, skills: ["az.pos.adjective"] },
            { id: "az-u1-l2-t6", type: "multiple_choice", prompt: "Hansı söz birləşməsində sifət var?", options: ["isti çay", "su içmək", "evə getmək", "kitab oxumaq"], correctIndex: 0, xp: 10, skills: ["az.pos.adjective","az.syn.phrase"] },
            { id: "az-u1-l2-t7", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı sifətdir?", options: ["qırmızı", "qaçmaq", "ev", "uşaq"], correctIndex: 0, xp: 10, skills: ["az.pos.adjective"] },
            { id: "az-u1-l2-t8", type: "multiple_choice", prompt: "'İsti çörək' birləşməsində sifət hansıdır?", options: ["isti", "çörək", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, skills: ["az.pos.adjective"] },
            { id: "az-u1-l2-t9", type: "fill_blank", prompt: "Sifət 'necə?' və '___?' suallarına cavab verir.", accepted: ["hansı", "hansi"], xp: 10, skills: ["az.pos.adjective"] },
            { id: "az-u1-l2-t10", type: "multiple_choice", prompt: "Aşağıdakılardan hansı ölçü bildirən sifətdir?", options: ["kiçik", "alma", "getmək", "tez"], correctIndex: 0, xp: 10, skills: ["az.pos.adjective"] },
            { id: "az-u1-l2-t11", type: "multiple_choice", prompt: "Aşağıdakılardan hansı dad bildirən sifətdir?", options: ["şirin", "mavi", "uzun", "yumru"], correctIndex: 0, xp: 10, skills: ["az.pos.adjective"] },
            { id: "az-u1-l2-t12", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı sifət deyil?", options: ["gözəl", "hündür", "kitab", "ağ"], correctIndex: 2, xp: 10, skills: ["az.pos.adjective"] },
            { id: "az-u1-l2-t13", type: "fill_blank", prompt: "'Yaşıl yarpaq' birləşməsində əlaməti bildirən sözü yaz.", accepted: ["yaşıl", "yasil"], xp: 10, skills: ["az.pos.noun"] },
            { id: "az-u1-l2-t14", type: "multiple_choice", prompt: "'Böyük' sözünün əksi olan sifət hansıdır?", options: ["kiçik", "geniş", "uzun", "hündür"], correctIndex: 0, xp: 10, skills: ["az.lex.antonym","az.pos.adjective"] },
            { id: "az-u1-l2-t15", type: "multiple_choice", prompt: "Hansı söz birləşməsində sifət var?", options: ["soyuq su", "su içmək", "kitab oxumaq", "evə getmək"], correctIndex: 0, xp: 15, skills: ["az.pos.adjective","az.syn.phrase"] },
          ],
          bonusTasks: [
            { id: "az-u1-l2-b1", type: "multiple_choice", prompt: "Aşağıdakılardan hansı rəng bildirən sifətdir?", options: ["sürətli", "qara", "acı", "yumşaq"], correctIndex: 1, xp: 15, skills: ["az.pos.adjective"] },
            { id: "az-u1-l2-b2", type: "fill_blank", prompt: "Sifət çox zaman ___ yanında işlənir. (nitq hissəsi)", accepted: ["isim", "ismin", "isimin"], xp: 15, skills: ["az.phon.letters","az.pos.adjective"] },
            { id: "az-u1-l2-b3", type: "multiple_choice", prompt: "Hansı qrup yalnız sifətlərdən ibarətdir?", options: ["ağ, şirin, böyük", "ev, ağ, qaçmaq", "getmək, gözəl, dost", "kitab, alma, quş"], correctIndex: 0, xp: 15, skills: ["az.pos.adjective"] },
            { id: "az-u1-l2-b4", type: "multiple_choice", prompt: "'Hündür' sözü nəyi bildirir?", options: ["rəngi", "ölçünü", "dadı", "hərəkəti"], correctIndex: 1, xp: 15, skills: ["az.pos.noun"] },
            { id: "az-u1-l2-b5", type: "fill_blank", prompt: "'Acı' sözü ___ bildirən sifətdir. (rəng / dad / ölçü)", accepted: ["dad", "dadı", "dadi"], xp: 15, skills: ["az.pos.adjective"] },
          ],
        },
        {
          id: "az-say",
          title: "Say",
          intro: "Say əşyanın miqdarını və ya sırasını bildirir.",
          sections: [
            { heading: "Say nədir?", body: "Say əşyanın miqdarını və ya sırasını bildirən nitq hissəsidir." },
            { heading: "Növləri", body: "Miqdar sayı miqdarı bildirir (bir, iki, on) və 'neçə?' sualına cavab verir. Sıra sayı sıranı bildirir (birinci, ikinci) və 'neçənci?' sualına cavab verir." },
          ],
          tasks: [
            { id: "az-say-t1", type: "multiple_choice", prompt: "'beş' hansı saydır?", options: ["miqdar", "sıra"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-say-t2", type: "multiple_choice", prompt: "'üçüncü' hansı saydır?", options: ["miqdar", "sıra"], correctIndex: 1, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-say-t3", type: "multiple_choice", prompt: "Miqdar sayı hansı suala cavab verir?", options: ["kim?", "neçə?", "necə?", "harada?"], correctIndex: 1, xp: 10, skills: ["az.pos.numeral"] },
            { id: "az-say-t4", type: "fill_blank", prompt: "'İkinci' ___ saydır. (miqdar / sıra)", accepted: ["sıra", "sira"], xp: 10, skills: ["az.pos.noun"] },
            { id: "az-say-t5", type: "multiple_choice", prompt: "Aşağıdakılardan hansı miqdar sayıdır?", options: ["birinci", "on", "beşinci", "üçüncü"], correctIndex: 1, xp: 10, skills: ["az.pos.numeral"] },
            { id: "az-say-t6", type: "multiple_choice", prompt: "'on' hansı saydır?", options: ["miqdar", "sıra"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-say-t7", type: "multiple_choice", prompt: "'beşinci' hansı saydır?", options: ["miqdar", "sıra"], correctIndex: 1, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-say-t8", type: "multiple_choice", prompt: "Sıra sayı hansı suala cavab verir?", options: ["neçə?", "neçənci?", "necə?", "harada?"], correctIndex: 1, xp: 10, skills: ["az.pos.numeral"] },
            { id: "az-say-t9", type: "fill_blank", prompt: "'Yeddi' ___ sayıdır. (miqdar / sıra)", accepted: ["miqdar"], xp: 10, skills: ["az.pos.numeral"] },
            { id: "az-say-t10", type: "multiple_choice", prompt: "Aşağıdakılardan hansı sıra sayıdır?", options: ["iki", "ikinci", "üç", "dörd"], correctIndex: 1, xp: 10, skills: ["az.pos.numeral"] },
            { id: "az-say-t11", type: "multiple_choice", prompt: "'birinci' sözü hansı suala cavab verir?", options: ["neçə?", "neçənci?", "necə?", "nə?"], correctIndex: 1, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-say-t12", type: "multiple_choice", prompt: "Aşağıdakılardan hansı miqdar sayıdır?", options: ["üçüncü", "altı", "onuncu", "beşinci"], correctIndex: 1, xp: 10, skills: ["az.pos.numeral"] },
            { id: "az-say-t13", type: "fill_blank", prompt: "Miqdar sayı ___ sualına cavab verir.", accepted: ["neçə", "nece", "neçə?"], xp: 10, skills: ["az.pos.numeral"] },
            { id: "az-say-t14", type: "multiple_choice", prompt: "'onuncu sinif' birləşməsində 'onuncu' hansı saydır?", options: ["miqdar", "sıra"], correctIndex: 1, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-say-t15", type: "multiple_choice", prompt: "'üç alma' birləşməsində 'üç' hansı saydır?", options: ["miqdar", "sıra"], correctIndex: 0, xp: 15, skills: ["az.pos.noun"] },
          ],
          bonusTasks: [
            { id: "az-say-b1", type: "numeric", prompt: "Say neçə əsas növə bölünür?", answer: 2, xp: 15, skills: ["az.pos.numeral"] },
            { id: "az-say-b2", type: "fill_blank", prompt: "'Doqquzuncu' ___ sayıdır. (miqdar / sıra)", accepted: ["sıra", "sira"], xp: 15, skills: ["az.pos.numeral"] },
            { id: "az-say-b3", type: "multiple_choice", prompt: "Hansı qrupda yalnız miqdar sayları var?", options: ["bir, iki, üç", "birinci, ikinci", "üç, üçüncü", "on, onuncu"], correctIndex: 0, xp: 15, skills: ["az.pos.numeral"] },
            { id: "az-say-b4", type: "multiple_choice", prompt: "'İkinci mərtəbə' birləşməsində say hansıdır?", options: ["ikinci", "mərtəbə", "hər ikisi", "heç biri"], correctIndex: 0, xp: 15, skills: ["az.pos.numeral"] },
            { id: "az-say-b5", type: "multiple_choice", prompt: "'neçənci?' sualına cavab verən say hansıdır?", options: ["miqdar", "sıra"], correctIndex: 1, xp: 15, skills: ["az.pos.numeral"] },
          ],
        },
        {
          id: "az-parts-of-speech-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az-evezlik",
          title: "Əvəzlik",
          intro: "Əvəzlik ismin, sifətin yerində işlənir.",
          sections: [
            { heading: "Əvəzlik nədir?", body: "Əvəzlik ismi, sifəti və ya sayı əvəz edən nitq hissəsidir." },
            { heading: "Şəxs əvəzlikləri", body: "mən, sən, o, biz, siz, onlar — şəxs əvəzlikləridir." },
          ],
          tasks: [
            { id: "az-evezlik-t1", type: "multiple_choice", prompt: "'mən, sən, o' hansı əvəzliklərdir?", options: ["şəxs", "işarə", "sual"], correctIndex: 0, xp: 10, skills: ["az.pos.pronoun"] },
            { id: "az-evezlik-t2", type: "multiple_choice", prompt: "Əvəzlik əsasən nəyi əvəz edir?", options: ["feili", "ismi", "yalnız sayı", "heç nəyi"], correctIndex: 1, xp: 10, skills: ["az.pos.pronoun"] },
            { id: "az-evezlik-t3", type: "fill_blank", prompt: "'Biz' ___ əvəzliyidir. (şəxs / işarə)", accepted: ["şəxs", "sexs"], xp: 10, skills: ["az.pos.noun"] },
            { id: "az-evezlik-t4", type: "multiple_choice", prompt: "Aşağıdakılardan hansı şəxs əvəzliyidir?", options: ["bu", "onlar", "gözəl", "kitab"], correctIndex: 1, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-evezlik-t5", type: "multiple_choice", prompt: "'O gəldi' cümləsində əvəzlik hansıdır?", options: ["o", "gəldi", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, skills: ["az.pos.pronoun"] },
            { id: "az-evezlik-t6", type: "multiple_choice", prompt: "'biz, siz, onlar' hansı əvəzliklərdir?", options: ["şəxs", "işarə", "sual", "təyini"], correctIndex: 0, xp: 10, skills: ["az.pos.pronoun"] },
            { id: "az-evezlik-t7", type: "multiple_choice", prompt: "'Sən gəldin' cümləsində əvəzlik hansıdır?", options: ["sən", "gəldin", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, skills: ["az.pos.pronoun"] },
            { id: "az-evezlik-t8", type: "fill_blank", prompt: "'Mən' ___ əvəzliyidir. (şəxs / işarə)", accepted: ["şəxs", "sexs", "şexs"], xp: 10, skills: ["az.pos.noun"] },
            { id: "az-evezlik-t9", type: "numeric", prompt: "Neçə şəxs əvəzliyi var? (mən, sən, o, biz, siz, onlar)", answer: 6, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-evezlik-t10", type: "multiple_choice", prompt: "Aşağıdakılardan hansı şəxs əvəzliyidir?", options: ["o", "gözəl", "kitab", "qaçmaq"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-evezlik-t11", type: "multiple_choice", prompt: "'Biz oxuyuruq' cümləsində əvəzlik hansıdır?", options: ["biz", "oxuyuruq", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, skills: ["az.pos.pronoun"] },
            { id: "az-evezlik-t12", type: "multiple_choice", prompt: "Əvəzlik əsasən hansı nitq hissəsini əvəz edir?", options: ["feili", "ismi", "yalnız sayı", "heç birini"], correctIndex: 1, xp: 10, skills: ["az.phon.letters","az.pos.pronoun"] },
            { id: "az-evezlik-t13", type: "fill_blank", prompt: "'Siz' ___ əvəzliyidir. (şəxs / işarə)", accepted: ["şəxs", "sexs", "şexs"], xp: 10, skills: ["az.pos.noun"] },
            { id: "az-evezlik-t14", type: "multiple_choice", prompt: "Aşağıdakılardan hansı əvəzlikdir?", options: ["mən", "getmək", "ağ", "kitab"], correctIndex: 0, xp: 10, skills: ["az.pos.pronoun"] },
            { id: "az-evezlik-t15", type: "multiple_choice", prompt: "'O gözəldir' cümləsində əvəzlik hansıdır?", options: ["o", "gözəldir", "hər ikisi", "heç biri"], correctIndex: 0, xp: 15, skills: ["az.pos.pronoun"] },
          ],
          bonusTasks: [
            { id: "az-evezlik-b1", type: "multiple_choice", prompt: "'onlar' əvəzliyi tək, yoxsa cəm haldadır?", options: ["tək", "cəm"], correctIndex: 1, xp: 15, skills: ["az.pos.noun"] },
            { id: "az-evezlik-b2", type: "fill_blank", prompt: "Danışan özünü ___ əvəzliyi ilə bildirir.", accepted: ["mən", "men"], xp: 15, skills: ["az.pos.noun"] },
            { id: "az-evezlik-b3", type: "multiple_choice", prompt: "Hansı qrupda yalnız şəxs əvəzlikləri var?", options: ["mən, sən, o", "bu, o, gözəl", "mən, kitab, o", "sən, ağ, biz"], correctIndex: 0, xp: 15, skills: ["az.pos.pronoun"] },
            { id: "az-evezlik-b4", type: "numeric", prompt: "'Sən və mən' ifadəsində neçə əvəzlik var?", answer: 2, xp: 15, skills: ["az.pos.pronoun"] },
            { id: "az-evezlik-b5", type: "multiple_choice", prompt: "Əvəzlik cümlədə əsasən nəyi əvəz edir?", options: ["adları", "hərəkəti", "durğu işarəsini", "hecanı"], correctIndex: 0, xp: 15, skills: ["az.pos.pronoun"] },
          ],
        },
        {
          id: "az-u1-l3",
          title: "Feil",
          intro: "Feil hərəkəti bildirir.",
          visual: "verb-timeline",
          sections: [
            { heading: "Feil nədir?", body: "Feil əşyanın hərəkətini və ya iş prosesini bildirən nitq hissəsidir (qaçmaq, yazmaq, gülmək)." },
            { heading: "Suallar", body: "Feil 'nə etdi?', 'nə edir?', 'nə edəcək?' kimi suallara cavab verir." },
            { heading: "Zaman", body: "Feillər zamana görə dəyişir: yazdı (keçmiş), yazır (indiki), yazacaq (gələcək)." },
          ],
          tasks: [
            { id: "az-u1-l3-t1", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı feildir?", options: ["gözəl", "qaçmaq", "kitab", "yaşıl"], correctIndex: 1, xp: 10, skills: ["az.pos.verb"] },
            { id: "az-u1-l3-t2", type: "multiple_choice", prompt: "Hansı söz 'nə etdi?' sualına cavab verir?", options: ["gəldi", "şagird", "ağ", "stol"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-u1-l3-t3", type: "multiple_choice", prompt: "'Uşaq oxuyur' cümləsində feil hansıdır?", options: ["uşaq", "oxuyur", "hər ikisi", "heç biri"], correctIndex: 1, xp: 10, skills: ["az.pos.verb"] },
            { id: "az-u1-l3-t4", type: "fill_blank", prompt: "'Yazdı' feili hansı zamandadır? (keçmiş / indiki / gələcək)", accepted: ["keçmiş", "kecmis", "keçmiş zaman"], xp: 10, skills: ["az.pos.verb_tense"] },
            { id: "az-u1-l3-t5", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı gələcək zamanı bildirir?", options: ["gəldi", "gəlir", "gələcək", "gəlmək"], correctIndex: 2, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-u1-l3-t6", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı hərəkət bildirir?", options: ["sevinc", "gülmək", "şən", "dost"], correctIndex: 1, xp: 10, skills: ["az.pos.verb"] },
            { id: "az-u1-l3-t7", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı feildir?", options: ["yazmaq", "kitab", "gözəl", "dost"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az-u1-l3-t8", type: "multiple_choice", prompt: "'Quş uçur' cümləsində feil hansıdır?", options: ["quş", "uçur", "hər ikisi", "heç biri"], correctIndex: 1, xp: 10, skills: ["az.pos.verb"] },
            { id: "az-u1-l3-t9", type: "fill_blank", prompt: "'Gələcək' feili hansı zamandadır? (keçmiş / indiki / gələcək)", accepted: ["gələcək", "gelecek", "gələcək zaman"], xp: 10, skills: ["az.pos.verb_tense"] },
            { id: "az-u1-l3-t10", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı keçmiş zamanı bildirir?", options: ["oxudu", "oxuyur", "oxuyacaq", "oxumaq"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-u1-l3-t11", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı indiki zamanı bildirir?", options: ["gəldi", "gəlir", "gələcək", "gəlmək"], correctIndex: 1, xp: 10, skills: ["az.pos.noun"] },
            { id: "az-u1-l3-t12", type: "fill_blank", prompt: "Feil əşyanın ___ bildirir.", accepted: ["hərəkət", "hereket", "hərəkətini", "hereketini"], xp: 10, skills: ["az.pos.verb"] },
            { id: "az-u1-l3-t13", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı hərəkət bildirir?", options: ["qaçmaq", "sevinc", "şən", "dost"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az-u1-l3-t14", type: "multiple_choice", prompt: "'Yazacaq' feili hansı zamandadır?", options: ["keçmiş", "indiki", "gələcək", "heç biri"], correctIndex: 2, xp: 10, skills: ["az.pos.verb_tense"] },
            { id: "az-u1-l3-t15", type: "multiple_choice", prompt: "'Uşaqlar oynayır' cümləsində feil hansıdır?", options: ["uşaqlar", "oynayır", "hər ikisi", "heç biri"], correctIndex: 1, xp: 15, skills: ["az.pos.verb"] },
          ],
          bonusTasks: [
            { id: "az-u1-l3-b1", type: "multiple_choice", prompt: "Hansı qrup yalnız feillərdən ibarətdir?", options: ["yazmaq, qaçmaq, gülmək", "ev, kitab, quş", "gözəl, ağ, şirin", "dost, bacı, ana"], correctIndex: 0, xp: 15, skills: ["az.pos.verb"] },
            { id: "az-u1-l3-b2", type: "fill_blank", prompt: "Feillər ___ görə dəyişir. (nəyə görə)", accepted: ["zamana", "zaman"], xp: 15, skills: ["az.pos.verb"] },
            { id: "az-u1-l3-b3", type: "multiple_choice", prompt: "'Getdi' feili hansı zamandadır?", options: ["keçmiş", "indiki", "gələcək", "heç biri"], correctIndex: 0, xp: 15, skills: ["az.pos.verb_tense"] },
            { id: "az-u1-l3-b4", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı feil deyil?", options: ["oxumaq", "yazmaq", "qələm", "gülmək"], correctIndex: 2, xp: 15, skills: ["az.pos.verb"] },
            { id: "az-u1-l3-b5", type: "fill_blank", prompt: "'Nə edir?' sualına cavab verən söz hansı nitq hissəsidir?", accepted: ["feil", "feildir"], xp: 15, skills: ["az.phon.letters"] },
          ],
        },
        {
          id: "az-zerf",
          title: "Zərf",
          intro: "Zərf hərəkətin tərzini, zamanını və yerini bildirir.",
          sections: [
            { heading: "Zərf nədir?", body: "Zərf feilin əlamətini — hərəkətin tərzini, zamanını, yerini və ya səbəbini bildirən nitq hissəsidir." },
            { heading: "Suallar", body: "Zərf 'necə?', 'nə vaxt?', 'harada?' və 'nə üçün?' suallarına cavab verir." },
            { heading: "Növləri", body: "Tərzi-hərəkət zərfi (tez, yavaş), zaman zərfi (dünən, indi, sabah) və yer zərfi (irəli, geri, burada) olur." },
          ],
          tasks: [
            { id: "az-zerf-t1", type: "multiple_choice", prompt: "'yavaş' sözü hansı nitq hissəsidir?", options: ["isim", "sifət", "zərf", "say"], correctIndex: 2, xp: 10, skills: ["az.phon.letters"] },
            { id: "az-zerf-t2", type: "multiple_choice", prompt: "Zərf əsasən hansı nitq hissəsi ilə işlənir?", options: ["isim", "feil", "say", "əvəzlik"], correctIndex: 1, xp: 10, skills: ["az.phon.letters","az.pos.adverb"] },
            { id: "az-zerf-t3", type: "multiple_choice", prompt: "'dünən' zərfi hansı suala cavab verir?", options: ["necə?", "nə vaxt?", "harada?", "kim?"], correctIndex: 1, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az-zerf-t4", type: "fill_blank", prompt: "'tez' zərfi '___?' sualına cavab verir.", accepted: ["necə", "nece", "necə?"], xp: 10, skills: ["az.pos.adverb"] },
            { id: "az-zerf-t5", type: "multiple_choice", prompt: "Aşağıdakılardan hansı zaman zərfidir?", options: ["burada", "sabah", "yavaş", "gözəl"], correctIndex: 1, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az-zerf-t6", type: "multiple_choice", prompt: "'Uşaq tez qaçdı' cümləsində zərf hansıdır?", options: ["uşaq", "tez", "qaçdı", "heç biri"], correctIndex: 1, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az-zerf-t7", type: "multiple_choice", prompt: "Aşağıdakılardan hansı yer zərfidir?", options: ["dünən", "irəli", "yavaş", "tez"], correctIndex: 1, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az-zerf-t8", type: "multiple_choice", prompt: "Aşağıdakılardan hansı tərzi-hərəkət zərfidir?", options: ["sabah", "yavaş", "burada", "dünən"], correctIndex: 1, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az-zerf-t9", type: "fill_blank", prompt: "'sabah' ___ zərfidir. (zaman / yer)", accepted: ["zaman"], xp: 10, skills: ["az.pos.adverb"] },
            { id: "az-zerf-t10", type: "multiple_choice", prompt: "'irəli, geri, burada' hansı zərflərdir?", options: ["zaman", "yer", "tərzi-hərəkət", "səbəb"], correctIndex: 1, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az-zerf-t11", type: "multiple_choice", prompt: "'Biz sabah gedəcəyik' cümləsində zərf hansıdır?", options: ["biz", "sabah", "gedəcəyik", "heç biri"], correctIndex: 1, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az-zerf-t12", type: "multiple_choice", prompt: "Zərf aşağıdakı suallardan hansına cavab vermir?", options: ["necə?", "nə vaxt?", "harada?", "kim?"], correctIndex: 3, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az-zerf-t13", type: "fill_blank", prompt: "Hərəkətin tərzini bildirən zərf '___?' sualına cavab verir.", accepted: ["necə", "nece", "necə?"], xp: 10, skills: ["az.pos.adverb"] },
            { id: "az-zerf-t14", type: "multiple_choice", prompt: "Aşağıdakılardan hansı yer zərfidir?", options: ["yavaş", "aşağı", "dünən", "tez"], correctIndex: 1, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az-zerf-t15", type: "multiple_choice", prompt: "'O gözəl oxuyur' cümləsində zərf hansıdır?", options: ["o", "gözəl", "oxuyur", "heç biri"], correctIndex: 1, xp: 15, skills: ["az.pos.adverb"] },
          ],
          bonusTasks: [
            { id: "az-zerf-b1", type: "multiple_choice", prompt: "Hansı qrup yalnız zərflərdən ibarətdir?", options: ["tez, yavaş, dünən", "ev, kitab, quş", "ağ, gözəl, şirin", "mən, sən, o"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb"] },
            { id: "az-zerf-b2", type: "fill_blank", prompt: "'dünən' ___ zərfidir. (zaman / yer / tərz)", accepted: ["zaman"], xp: 15, skills: ["az.pos.adverb"] },
            { id: "az-zerf-b3", type: "multiple_choice", prompt: "'Quş yüksək uçur' cümləsində zərf hansıdır?", options: ["quş", "yüksək", "uçur", "heç biri"], correctIndex: 1, xp: 15, skills: ["az.pos.adverb"] },
            { id: "az-zerf-b4", type: "multiple_choice", prompt: "Zərf əsasən nəyin əlamətini bildirir?", options: ["ismin", "feilin", "sayın", "durğu işarəsinin"], correctIndex: 1, xp: 15, skills: ["az.pos.adverb"] },
            { id: "az-zerf-b5", type: "fill_blank", prompt: "'harada?' sualına cavab verən zərf ___ zərfidir.", accepted: ["yer"], xp: 15, skills: ["az.pos.adverb"] },
          ],
        },
        {
          id: "az-parts-of-speech-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        }
      ],
    },

    // ═══════════════ 3. Yazı və oxu mədəniyyəti ═══════════════
    {
      id: "az-writing",
      title: "Yazı və oxu mədəniyyəti",
      description:
        "Orfoqrafiya-orfoepiya, durğu işarələri, mətnlə iş və janrlar.",
      lessons: [
        {
          id: "az-orfoqrafiya",
          title: "Orfoqrafiya və orfoepiya",
          intro: "Sözlərin düzgün yazılışı və düzgün tələffüzü.",
          sections: [
            { heading: "Orfoqrafiya", body: "Sözlərin düzgün yazılışı qaydalarına orfoqrafiya deyilir." },
            { heading: "Orfoepiya", body: "Sözlərin düzgün tələffüz (deyiliş) qaydalarına orfoepiya deyilir." },
          ],
          tasks: [
            { id: "az-orfoqrafiya-t1", type: "multiple_choice", prompt: "Sözlərin düzgün yazılışı qaydaları necə adlanır?", options: ["orfoqrafiya", "orfoepiya"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-orfoqrafiya-t2", type: "multiple_choice", prompt: "Sözlərin düzgün tələffüzü qaydaları necə adlanır?", options: ["orfoqrafiya", "orfoepiya"], correctIndex: 1, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-orfoqrafiya-t3", type: "multiple_choice", prompt: "Hansı söz düzgün yazılıb?", options: ["gəldı", "gəldi", "geldi", "gəldï"], correctIndex: 1, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-orfoqrafiya-t4", type: "multiple_choice", prompt: "Hansı söz düzgün yazılıb?", options: ["kitap", "kitab", "gitab", "kıtab"], correctIndex: 1, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-orfoqrafiya-t5", type: "fill_blank", prompt: "Sözün düzgün deyilişi ___ adlanır.", accepted: ["orfoepiya"], xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-orfoqrafiya-t6", type: "multiple_choice", prompt: "Hansı söz düzgün yazılıb?", options: ["məktəp", "məktəb", "mekteb", "məktab"], correctIndex: 1, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-orfoqrafiya-t7", type: "multiple_choice", prompt: "Hansı söz düzgün yazılıb?", options: ["təftər", "dəftər", "deftər", "dəftar"], correctIndex: 1, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-orfoqrafiya-t8", type: "fill_blank", prompt: "Sözlərin düzgün yazılışı ___ adlanır.", accepted: ["orfoqrafiya"], xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-orfoqrafiya-t9", type: "multiple_choice", prompt: "Hansı söz düzgün yazılıb?", options: ["gəlır", "gəlir", "gelir", "gəlïr"], correctIndex: 1, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-orfoqrafiya-t10", type: "multiple_choice", prompt: "Hansı söz düzgün yazılıb?", options: ["uşax", "uşaq", "usaq", "uşag"], correctIndex: 1, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-orfoqrafiya-t11", type: "multiple_choice", prompt: "Hansı söz düzgün yazılıb?", options: ["çörəy", "çörək", "cörək", "çörəx"], correctIndex: 1, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-orfoqrafiya-t12", type: "fill_blank", prompt: "Sözün düzgün tələffüzü ___ qaydalarıdır.", accepted: ["orfoepiya"], xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-orfoqrafiya-t13", type: "multiple_choice", prompt: "Hansı söz düzgün yazılıb?", options: ["ağaç", "ağac", "agac", "ahac"], correctIndex: 1, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-orfoqrafiya-t14", type: "multiple_choice", prompt: "Hansı söz düzgün yazılıb?", options: ["sahər", "səhər", "seher", "səhar"], correctIndex: 1, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-orfoqrafiya-t15", type: "multiple_choice", prompt: "Hansı söz düzgün yazılıb?", options: ["kömey", "kömək", "komək", "kömax"], correctIndex: 1, xp: 15, skills: ["az.orth.spelling"] },
          ],
          bonusTasks: [
            { id: "az-orfoqrafiya-b1", type: "multiple_choice", prompt: "Hansı söz düzgün yazılıb?", options: ["qardas", "qardaş", "gardaş", "qardaç"], correctIndex: 1, xp: 15, skills: ["az.orth.spelling"] },
            { id: "az-orfoqrafiya-b2", type: "fill_blank", prompt: "Orfoqrafiya sözlərin düzgün ___ deməkdir.", accepted: ["yazılışı", "yazilisi", "yazılış"], xp: 15, skills: ["az.orth.spelling"] },
            { id: "az-orfoqrafiya-b3", type: "multiple_choice", prompt: "Hansı söz düzgün yazılıb?", options: ["bilix", "bilik", "bılık", "bilig"], correctIndex: 1, xp: 15, skills: ["az.orth.spelling"] },
            { id: "az-orfoqrafiya-b4", type: "multiple_choice", prompt: "Hansı söz düzgün yazılıb?", options: ["günes", "günəş", "günəs", "gunəş"], correctIndex: 1, xp: 15, skills: ["az.orth.spelling"] },
            { id: "az-orfoqrafiya-b5", type: "multiple_choice", prompt: "Hansı söz düzgün yazılıb?", options: ["yağıs", "yağış", "yagış", "yağiş"], correctIndex: 1, xp: 15, skills: ["az.orth.spelling"] },
          ],
        },
        {
          id: "az-durgu",
          title: "Durğu işarələri",
          intro: "Cümlədə nöqtə, vergül, sual və nida işarələri.",
          sections: [
            { heading: "Cümlə sonunda", body: "Nəqli cümlədən sonra nöqtə (.), sual cümləsindən sonra sual işarəsi (?), güclü hiss bildirən cümlədən sonra nida işarəsi (!) qoyulur." },
            { heading: "Cümlə daxilində", body: "Sadalama və ayrı-ayrı hissələr arasında vergül (,) işlənir." },
          ],
          tasks: [
            { id: "az-durgu-t1", type: "multiple_choice", prompt: "Nəqli cümlənin sonunda hansı işarə qoyulur?", options: ["nöqtə", "sual işarəsi", "nida işarəsi", "vergül"], correctIndex: 0, xp: 10, skills: ["az.syn.sentence_type"] },
            { id: "az-durgu-t2", type: "multiple_choice", prompt: "Sual cümləsinin sonunda hansı işarə qoyulur?", options: ["nöqtə", "sual işarəsi", "vergül", "nida işarəsi"], correctIndex: 1, xp: 10, skills: ["az.syn.sentence_type"] },
            { id: "az-durgu-t3", type: "multiple_choice", prompt: "Güclü hiss bildirən cümlədən sonra hansı işarə qoyulur?", options: ["nöqtə", "vergül", "nida işarəsi", "sual işarəsi"], correctIndex: 2, xp: 10, skills: ["az.syn.sentence"] },
            { id: "az-durgu-t4", type: "fill_blank", prompt: "Cümlə daxilində sadalamada ___ işarəsi qoyulur.", accepted: ["vergül", "vergul"], xp: 10, skills: ["az.syn.sentence"] },
            { id: "az-durgu-t5", type: "multiple_choice", prompt: "'Sən hara gedirsən' cümləsinin sonunda hansı işarə olmalıdır?", options: ["nöqtə", "sual işarəsi", "nida işarəsi", "vergül"], correctIndex: 1, xp: 10, skills: ["az.syn.sentence"] },
            { id: "az-durgu-t6", type: "multiple_choice", prompt: "'Ura, biz qalib gəldik' cümləsinin sonunda hansı işarə olmalıdır?", options: ["nöqtə", "nida işarəsi", "sual işarəsi", "vergül"], correctIndex: 1, xp: 10, skills: ["az.syn.sentence"] },
            { id: "az-durgu-t7", type: "multiple_choice", prompt: "'Kitab oxuyuram' cümləsinin sonunda hansı işarə olmalıdır?", options: ["nöqtə", "sual işarəsi", "nida işarəsi", "vergül"], correctIndex: 0, xp: 10, skills: ["az.syn.sentence"] },
            { id: "az-durgu-t8", type: "fill_blank", prompt: "Sual cümləsinin sonunda ___ işarəsi qoyulur.", accepted: ["sual", "sual işarəsi"], xp: 10, skills: ["az.syn.sentence_type"] },
            { id: "az-durgu-t9", type: "multiple_choice", prompt: "'Alma, armud, heyva aldım' cümləsində sözləri ayıran işarə hansıdır?", options: ["nöqtə", "vergül", "sual işarəsi", "nida işarəsi"], correctIndex: 1, xp: 10, skills: ["az.syn.sentence"] },
            { id: "az-durgu-t10", type: "multiple_choice", prompt: "Hansı cümlə nida işarəsi ilə bitir?", options: ["Sən gəldin", "Nə gözəl gündür", "Kitab hardadır", "Mən oxuyuram"], correctIndex: 1, xp: 10, skills: ["az.syn.sentence"] },
            { id: "az-durgu-t11", type: "multiple_choice", prompt: "'Sən haradasan' cümləsinin sonunda hansı işarə olmalıdır?", options: ["nöqtə", "sual işarəsi", "nida işarəsi", "vergül"], correctIndex: 1, xp: 10, skills: ["az.syn.sentence"] },
            { id: "az-durgu-t12", type: "fill_blank", prompt: "Güclü hiss bildirən cümlədən sonra ___ işarəsi qoyulur.", accepted: ["nida", "nida işarəsi"], xp: 10, skills: ["az.syn.sentence"] },
            { id: "az-durgu-t13", type: "multiple_choice", prompt: "Nöqtə hansı cümlədən sonra qoyulur?", options: ["nəqli", "sual", "nida", "əmr"], correctIndex: 0, xp: 10, skills: ["az.syn.sentence","az.orth.punctuation"] },
            { id: "az-durgu-t14", type: "multiple_choice", prompt: "Vergül əsasən harada işlənir?", options: ["cümlə sonunda", "cümlə daxilində", "sözün ortasında", "hecada"], correctIndex: 1, xp: 10, skills: ["az.orth.punctuation"] },
            { id: "az-durgu-t15", type: "numeric", prompt: "'Ah, nə yaxşı!' cümləsində neçə durğu işarəsi var?", answer: 2, xp: 15, skills: ["az.syn.sentence","az.orth.punctuation"] },
          ],
          bonusTasks: [
            { id: "az-durgu-b1", type: "multiple_choice", prompt: "Sadalama zamanı hansı işarə işlənir?", options: ["nöqtə", "vergül", "sual işarəsi", "nida işarəsi"], correctIndex: 1, xp: 15, skills: ["az.orth.spelling"] },
            { id: "az-durgu-b2", type: "fill_blank", prompt: "Nəqli cümlədən sonra ___ qoyulur.", accepted: ["nöqtə", "noqte"], xp: 15, skills: ["az.syn.sentence_type"] },
            { id: "az-durgu-b3", type: "multiple_choice", prompt: "'Yaşasın!' cümləsinin sonunda hansı işarə var?", options: ["nida işarəsi", "nöqtə", "sual işarəsi", "vergül"], correctIndex: 0, xp: 15, skills: ["az.syn.sentence"] },
            { id: "az-durgu-b4", type: "multiple_choice", prompt: "Sual işarəsinin forması hansıdır?", options: [".", "?", "!", ","], correctIndex: 1, xp: 15, skills: ["az.orth.spelling"] },
            { id: "az-durgu-b5", type: "numeric", prompt: "'Hara, nə vaxt, necə?' cümləsində neçə vergül var?", answer: 2, xp: 15, skills: ["az.syn.sentence","az.orth.punctuation"] },
          ],
        },
        {
          id: "az-writing-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az-metn",
          title: "Mətnlə iş",
          intro: "Mətnin hissələri, planı və başlığı.",
          sections: [
            { heading: "Mətnin hissələri", body: "Mətn üç hissədən ibarətdir: giriş, əsas hissə və nəticə." },
            { heading: "Plan və başlıq", body: "Mətnin qısa məzmununu maddələrlə yazmaq — plan tutmaqdır. Mətnin əsas fikrini əks etdirən ad — başlıqdır." },
          ],
          tasks: [
            { id: "az-metn-t1", type: "multiple_choice", prompt: "Mətnin ilk hissəsi necə adlanır?", options: ["giriş", "əsas hissə", "nəticə", "plan"], correctIndex: 0, xp: 10, skills: ["az.phon.letters","az.text.structure"] },
            { id: "az-metn-t2", type: "multiple_choice", prompt: "Mətnin əsas fikri hansı hissədə açılır?", options: ["giriş", "əsas hissə", "nəticə", "başlıq"], correctIndex: 1, xp: 10, skills: ["az.text.structure"] },
            { id: "az-metn-t3", type: "multiple_choice", prompt: "Mətnə ad seçmək nə deməkdir?", options: ["plan tutmaq", "başlıq seçmək", "nəticə yazmaq", "giriş yazmaq"], correctIndex: 1, xp: 10, skills: ["az.text.structure"] },
            { id: "az-metn-t4", type: "fill_blank", prompt: "Mətnin son hissəsi ___ adlanır.", accepted: ["nəticə", "netice"], xp: 10, skills: ["az.phon.letters","az.text.structure"] },
            { id: "az-metn-t5", type: "multiple_choice", prompt: "Mətnin qısa məzmununu maddələrlə yazmaq necə adlanır?", options: ["plan tutmaq", "başlıq seçmək", "giriş", "nəticə"], correctIndex: 0, xp: 10, skills: ["az.text.structure"] },
            { id: "az-metn-t6", type: "numeric", prompt: "Mətn neçə əsas hissədən ibarətdir?", answer: 3, xp: 10, skills: ["az.text.structure"] },
            { id: "az-metn-t7", type: "multiple_choice", prompt: "Hadisə hansı hissədə yekunlaşır?", options: ["giriş", "əsas hissə", "nəticə", "başlıq"], correctIndex: 2, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-metn-t8", type: "fill_blank", prompt: "Mətnin ortadakı, ən geniş hissəsi ___ hissə adlanır.", accepted: ["əsas", "esas"], xp: 10, skills: ["az.phon.letters","az.text.structure"] },
            { id: "az-metn-t9", type: "multiple_choice", prompt: "Mətnin adı necə adlanır?", options: ["plan", "başlıq", "nəticə", "giriş"], correctIndex: 1, xp: 10, skills: ["az.text.structure"] },
            { id: "az-metn-t10", type: "multiple_choice", prompt: "Mətnin əvvəli, giriş hissəsi nə edir?", options: ["mövzunu təqdim edir", "nəticə çıxarır", "sadalama edir", "sual verir"], correctIndex: 0, xp: 10, skills: ["az.phon.letters","az.text.structure"] },
            { id: "az-metn-t11", type: "multiple_choice", prompt: "Mətnin əsas fikri hansı hissədə açılır?", options: ["giriş", "əsas hissə", "nəticə", "başlıq"], correctIndex: 1, xp: 10, skills: ["az.text.structure"] },
            { id: "az-metn-t12", type: "fill_blank", prompt: "Mətnin son hissəsi ___ adlanır.", accepted: ["nəticə", "netice"], xp: 10, skills: ["az.phon.letters","az.text.structure"] },
            { id: "az-metn-t13", type: "multiple_choice", prompt: "Yaxşı başlıq necə olmalıdır?", options: ["mövzuya uyğun", "çox uzun", "təsadüfi", "mənasız"], correctIndex: 0, xp: 10, skills: ["az.text.structure"] },
            { id: "az-metn-t14", type: "multiple_choice", prompt: "Mətni öz sözlərinlə danışmaq necə adlanır?", options: ["məzmununu danışmaq", "plan tutmaq", "başlıq seçmək", "giriş"], correctIndex: 0, xp: 10, skills: ["az.text.structure"] },
            { id: "az-metn-t15", type: "multiple_choice", prompt: "Mətnin hissələri hansı düzgün sıradadır?", options: ["giriş, əsas hissə, nəticə", "nəticə, giriş, əsas hissə", "əsas hissə, giriş, nəticə", "başlıq, nəticə, giriş"], correctIndex: 0, xp: 15, skills: ["az.text.structure"] },
          ],
          bonusTasks: [
            { id: "az-metn-b1", type: "multiple_choice", prompt: "Plan nə üçün lazımdır?", options: ["mətni nizamlamaq", "rəsm çəkmək", "oxumaq", "saymaq"], correctIndex: 0, xp: 15, skills: ["az.orth.spelling"] },
            { id: "az-metn-b2", type: "fill_blank", prompt: "Mətnə ad seçmək ___ seçməkdir.", accepted: ["başlıq", "baslıq", "basliq"], xp: 15, skills: ["az.text.structure"] },
            { id: "az-metn-b3", type: "multiple_choice", prompt: "Mətnin qısa məzmununu maddələrlə yazmaq necə adlanır?", options: ["plan", "başlıq", "giriş", "nəticə"], correctIndex: 0, xp: 15, skills: ["az.text.structure"] },
            { id: "az-metn-b4", type: "multiple_choice", prompt: "Mətndə əsas fikir harada olur?", options: ["girişdə", "əsas hissədə", "yalnız başlıqda", "heç yerdə"], correctIndex: 1, xp: 15, skills: ["az.text.structure"] },
            { id: "az-metn-b5", type: "numeric", prompt: "Mətnin neçə əsas hissəsi var?", answer: 3, xp: 15, skills: ["az.phon.letters","az.text.structure"] },
          ],
        },
        {
          id: "az-uslub",
          title: "Üslub və janrlar",
          intro: "Hekayə, nağıl, şeir, təmsil.",
          sections: [
            { heading: "Janrlar", body: "Nağıl — xəyali, sehrli hadisələr; təmsil — heyvanlar dilindən ibrətamiz əsər; şeir — vəznli, qafiyəli əsər; hekayə — real həyata əsaslanan kiçik bədii əsər." },
          ],
          tasks: [
            { id: "az-uslub-t1", type: "multiple_choice", prompt: "Uşaqlar üçün sehrli, xəyali hadisələr olan janr hansıdır?", options: ["nağıl", "məqalə", "elan", "məktub"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-uslub-t2", type: "multiple_choice", prompt: "Heyvanlar dilindən ibrətamiz janr hansıdır?", options: ["təmsil", "şeir", "hekayə", "nağıl"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-uslub-t3", type: "multiple_choice", prompt: "Vəznli və qafiyəli əsər hansıdır?", options: ["şeir", "hekayə", "nağıl", "təmsil"], correctIndex: 0, xp: 10, skills: ["az.text.genre"] },
            { id: "az-uslub-t4", type: "multiple_choice", prompt: "Real hadisə əsasında yazılmış kiçik bədii əsər hansıdır?", options: ["hekayə", "şeir", "nağıl", "təmsil"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-uslub-t5", type: "fill_blank", prompt: "'Tülkü və Qarğa' hansı janrdır?", accepted: ["təmsil", "temsil"], xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-uslub-t6", type: "multiple_choice", prompt: "'Cırtdan' hansı janrdır?", options: ["nağıl", "şeir", "hekayə", "məqalə"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-uslub-t7", type: "multiple_choice", prompt: "Qafiyəli, vəznli əsər hansıdır?", options: ["şeir", "hekayə", "nağıl", "elan"], correctIndex: 0, xp: 10, skills: ["az.text.genre"] },
            { id: "az-uslub-t8", type: "fill_blank", prompt: "Heyvanlar dilindən ibrət verən janr ___-dır.", accepted: ["təmsil", "temsil"], xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-uslub-t9", type: "multiple_choice", prompt: "Sehrli, xəyali hadisələr olan janr hansıdır?", options: ["nağıl", "təmsil", "hekayə", "məktub"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-uslub-t10", type: "multiple_choice", prompt: "Real həyatı əks etdirən kiçik bədii əsər hansıdır?", options: ["hekayə", "nağıl", "şeir", "təmsil"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-uslub-t11", type: "multiple_choice", prompt: "Şeirin əsas xüsusiyyəti nədir?", options: ["qafiyə", "ibrət", "sehr", "elan"], correctIndex: 0, xp: 10, skills: ["az.text.genre"] },
            { id: "az-uslub-t12", type: "fill_blank", prompt: "Nağıllar çox vaxt 'Biri var idi, ___ yox idi' ifadəsi ilə başlayır.", accepted: ["biri"], xp: 10, skills: ["az.text.genre"] },
            { id: "az-uslub-t13", type: "multiple_choice", prompt: "Təmsildə iştirak edən əsasən kimlərdir?", options: ["heyvanlar", "robotlar", "planetlər", "rəqəmlər"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-uslub-t14", type: "multiple_choice", prompt: "Hansı janr sehrli deyil, realdır?", options: ["hekayə", "nağıl", "əfsanə", "təmsil"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az-uslub-t15", type: "multiple_choice", prompt: "Şeirin hər sətri necə adlanır?", options: ["misra", "abzas", "başlıq", "heca"], correctIndex: 0, xp: 15, skills: ["az.text.genre"] },
          ],
          bonusTasks: [
            { id: "az-uslub-b1", type: "multiple_choice", prompt: "'Tısbağa və Dovşan' hansı janrdır?", options: ["təmsil", "şeir", "hekayə", "roman"], correctIndex: 0, xp: 15, skills: ["az.orth.spelling"] },
            { id: "az-uslub-b2", type: "fill_blank", prompt: "Vəznli və qafiyəli əsər ___ adlanır.", accepted: ["şeir", "seir"], xp: 15, skills: ["az.text.genre"] },
            { id: "az-uslub-b3", type: "multiple_choice", prompt: "Nağılın sonu adətən necə olur?", options: ["xeyirin qələbəsi", "qeyri-müəyyən", "kədərli", "təsadüfi"], correctIndex: 0, xp: 15, skills: ["az.text.genre"] },
            { id: "az-uslub-b4", type: "multiple_choice", prompt: "Hekayə ilə nağılın əsas fərqi nədir?", options: ["hekayə realdır", "hər ikisi sehrlidir", "hekayə qafiyəlidir", "fərq yoxdur"], correctIndex: 0, xp: 15, skills: ["az.text.genre"] },
            { id: "az-uslub-b5", type: "fill_blank", prompt: "Təmsilin sonunda oxucuya ___ (nəticə) verilir.", accepted: ["ibrət", "ibret", "nəticə"], xp: 15, skills: ["az.text.structure"] },
          ],
        },
        {
          id: "az-writing-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        }
      ],
    },

    // ═══════════════ 4. Nitq bacarıqlarının inkişafı ═══════════════
    {
      id: "az-speech",
      title: "Nitq bacarıqlarının inkişafı",
      description: "Şifahi və yazılı nitq bacarıqları.",
      lessons: [
        {
          id: "az-sifahi",
          title: "Şifahi nitq",
          intro: "Məruzə, müsahibə, diskussiya və fikrin əsaslandırılması.",
          sections: [
            { heading: "Şifahi nitq nədir?", body: "Danışıq yolu ilə ünsiyyət şifahi nitqdir." },
            { heading: "Formaları", body: "Məruzə — bir mövzuda hazırlanmış çıxış; müsahibə — sual-cavab; diskussiya — fərqli fikirlərin müzakirəsi. Fikri əsaslandırmaq — sübutlarla izah etməkdir." },
          ],
          tasks: [
            { id: "az-sifahi-t1", type: "multiple_choice", prompt: "Bir mövzuda hazırlanmış çıxış necə adlanır?", options: ["məruzə", "məktub", "inşa", "elan"], correctIndex: 0, xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-sifahi-t2", type: "multiple_choice", prompt: "İki nəfərin sual-cavabı necə adlanır?", options: ["müsahibə", "məruzə", "inşa", "diskussiya"], correctIndex: 0, xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-sifahi-t3", type: "multiple_choice", prompt: "Fərqli fikirlərin müzakirəsi necə adlanır?", options: ["diskussiya", "elan", "məktub", "məruzə"], correctIndex: 0, xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-sifahi-t4", type: "multiple_choice", prompt: "Fikri əsaslandırmaq nə deməkdir?", options: ["sübut gətirmək", "susmaq", "sual vermək", "yazmaq"], correctIndex: 0, xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-sifahi-t5", type: "fill_blank", prompt: "Danışıq yolu ilə ünsiyyət ___ nitqdir.", accepted: ["şifahi", "sifahi"], xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-sifahi-t6", type: "multiple_choice", prompt: "Auditoriya qarşısında hazırlanmış çıxış necə adlanır?", options: ["məruzə", "məktub", "inşa", "elan"], correctIndex: 0, xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-sifahi-t7", type: "multiple_choice", prompt: "Jurnalistin kiminləsə sual-cavabı necə adlanır?", options: ["müsahibə", "inşa", "elan", "təbriknamə"], correctIndex: 0, xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-sifahi-t8", type: "fill_blank", prompt: "Fərqli fikirlərin müzakirəsi ___ adlanır.", accepted: ["diskussiya"], xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-sifahi-t9", type: "multiple_choice", prompt: "Şifahi nitq nə ilə həyata keçir?", options: ["danışıqla", "yazı ilə", "rəsmlə", "işarə ilə"], correctIndex: 0, xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-sifahi-t10", type: "multiple_choice", prompt: "Fikri əsaslandırmaq üçün nə lazımdır?", options: ["dəlil (sübut)", "susmaq", "təkrar", "sual"], correctIndex: 0, xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-sifahi-t11", type: "multiple_choice", prompt: "Yaxşı məruzə necə olmalıdır?", options: ["aydın və mövzuya uyğun", "qarışıq", "çox uzun", "mənasız"], correctIndex: 0, xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-sifahi-t12", type: "fill_blank", prompt: "Sual verib cavab almaq ___ adlanır.", accepted: ["müsahibə", "musahibe"], xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-sifahi-t13", type: "multiple_choice", prompt: "Diskussiyada iştirakçılar nə edir?", options: ["fikir bildirir", "susur", "yazır", "oxuyur"], correctIndex: 0, xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-sifahi-t14", type: "multiple_choice", prompt: "Şifahi nitqdə hansı bacarıq vacibdir?", options: ["düzgün tələffüz", "gözəl xətt", "sürətli yazı", "rəsm"], correctIndex: 0, xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-sifahi-t15", type: "multiple_choice", prompt: "Məruzəçi kimdir?", options: ["çıxış edən", "dinləyən", "yazan", "oxuyan"], correctIndex: 0, xp: 15, skills: ["az.text.etiquette"] },
          ],
          bonusTasks: [
            { id: "az-sifahi-b1", type: "multiple_choice", prompt: "Müsahibədə ən azı neçə tərəf olur?", options: ["ən azı iki", "yalnız bir", "üç", "beş"], correctIndex: 0, xp: 15, skills: ["az.text.etiquette"] },
            { id: "az-sifahi-b2", type: "fill_blank", prompt: "Danışıqla ünsiyyət ___ nitqdir.", accepted: ["şifahi", "sifahi"], xp: 15, skills: ["az.text.etiquette"] },
            { id: "az-sifahi-b3", type: "multiple_choice", prompt: "Fikri əsaslandırmaq nə deməkdir?", options: ["sübutla izah etmək", "təkrarlamaq", "susmaq", "soruşmaq"], correctIndex: 0, xp: 15, skills: ["az.text.etiquette"] },
            { id: "az-sifahi-b4", type: "multiple_choice", prompt: "Diskussiyanın məqsədi nədir?", options: ["həqiqəti aydınlaşdırmaq", "mübahisə salmaq", "susmaq", "yazmaq"], correctIndex: 0, xp: 15, skills: ["az.text.etiquette"] },
            { id: "az-sifahi-b5", type: "multiple_choice", prompt: "Yaxşı dinləyici necə olmalıdır?", options: ["diqqətli", "laqeyd", "səs-küylü", "tələsik"], correctIndex: 0, xp: 15, skills: ["az.text.etiquette"] },
          ],
        },
        {
          id: "az-yazili",
          title: "Yazılı nitq",
          intro: "İnşa, məktub, elan və təbriknamə.",
          sections: [
            { heading: "İnşa", body: "Bir mövzuda yazılı əsər inşadır. Növləri: təsviri (təsvir edir), nəqli (hadisəni danışır), mühakimə (fikir yürüdür)." },
            { heading: "Digər yazılar", body: "Məktub — kiməsə ünvanlanan yazı; elan — məlumat verən mətn; təbriknamə — bayram/uğur münasibətilə yazılan təbrik." },
          ],
          tasks: [
            { id: "az-yazili-t1", type: "multiple_choice", prompt: "Bir mövzuda yazılı əsər necə adlanır?", options: ["inşa", "məruzə", "diskussiya", "müsahibə"], correctIndex: 0, xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-yazili-t2", type: "multiple_choice", prompt: "Hadisəni ardıcıl danışan inşa növü hansıdır?", options: ["təsviri", "nəqli", "mühakimə"], correctIndex: 1, xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-yazili-t3", type: "multiple_choice", prompt: "Əşyanı və ya mənzərəni təsvir edən inşa növü hansıdır?", options: ["təsviri", "nəqli", "mühakimə"], correctIndex: 0, xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-yazili-t4", type: "multiple_choice", prompt: "Kiməsə ünvanlanan yazı necə adlanır?", options: ["məktub", "elan", "inşa", "məruzə"], correctIndex: 0, xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-yazili-t5", type: "fill_blank", prompt: "Bayram münasibətilə yazılan təbrik ___ adlanır.", accepted: ["təbriknamə", "tebrikname"], xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-yazili-t6", type: "multiple_choice", prompt: "Fikir yürüdən, mühakimə edən inşa növü hansıdır?", options: ["mühakimə", "təsviri", "nəqli", "elan"], correctIndex: 0, xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-yazili-t7", type: "multiple_choice", prompt: "Doğum günü münasibətilə yazılan yazı hansıdır?", options: ["təbriknamə", "elan", "məruzə", "inşa"], correctIndex: 0, xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-yazili-t8", type: "fill_blank", prompt: "Kiməsə ünvanlanan yazı ___ adlanır.", accepted: ["məktub", "mektub"], xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-yazili-t9", type: "multiple_choice", prompt: "Tədbir haqqında məlumat verən qısa yazı hansıdır?", options: ["elan", "məktub", "inşa", "şeir"], correctIndex: 0, xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-yazili-t10", type: "multiple_choice", prompt: "Mənzərəni və ya əşyanı təsvir edən inşa növü hansıdır?", options: ["təsviri", "nəqli", "mühakimə", "elan"], correctIndex: 0, xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-yazili-t11", type: "numeric", prompt: "İnşanın neçə əsas növü var? (təsviri, nəqli, mühakimə)", answer: 3, xp: 10, skills: ["az.syn.sentence_type"] },
            { id: "az-yazili-t12", type: "fill_blank", prompt: "Hadisəni ardıcıl danışan inşa ___ inşadır.", accepted: ["nəqli", "neqli"], xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-yazili-t13", type: "multiple_choice", prompt: "'Bayramınız mübarək!' ifadəsi hansı yazıya aiddir?", options: ["təbriknamə", "elan", "məruzə", "inşa"], correctIndex: 0, xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-yazili-t14", type: "multiple_choice", prompt: "Məktubda kimə müraciət olunur?", options: ["konkret şəxsə", "hamıya", "heç kimə", "heyvanlara"], correctIndex: 0, xp: 10, skills: ["az.text.etiquette"] },
            { id: "az-yazili-t15", type: "multiple_choice", prompt: "Yazılı nitqdə nə vacibdir?", options: ["düzgün yazılış", "ucadan oxu", "sürətli danışıq", "jest"], correctIndex: 0, xp: 15, skills: ["az.text.etiquette"] },
          ],
          bonusTasks: [
            { id: "az-yazili-b1", type: "multiple_choice", prompt: "'Payız' mövzusunda mənzərə təsviri yazsan, bu hansı inşadır?", options: ["təsviri", "nəqli", "mühakimə", "elan"], correctIndex: 0, xp: 15, skills: ["az.text.etiquette"] },
            { id: "az-yazili-b2", type: "fill_blank", prompt: "Bayram münasibətilə yazılan yazı ___-dir.", accepted: ["təbriknamə", "tebrikname"], xp: 15, skills: ["az.text.etiquette"] },
            { id: "az-yazili-b3", type: "multiple_choice", prompt: "Elan nə üçündür?", options: ["məlumat vermək", "hadisə danışmaq", "təsvir etmək", "təbrik etmək"], correctIndex: 0, xp: 15, skills: ["az.text.etiquette"] },
            { id: "az-yazili-b4", type: "multiple_choice", prompt: "Mühakimə inşasında nə edilir?", options: ["fikir əsaslandırılır", "yalnız təsvir olunur", "hadisə danışılır", "elan verilir"], correctIndex: 0, xp: 15, skills: ["az.text.etiquette"] },
            { id: "az-yazili-b5", type: "multiple_choice", prompt: "Məktubun sonunda adətən nə yazılır?", options: ["imza (ad)", "başlıq", "sual", "plan"], correctIndex: 0, xp: 15, skills: ["az.text.etiquette"] },
          ],
        },
      ],
    },
  ],
};
