// Azərbaycan dili — 2-ci sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Əlifba sırası  2) Qalın və incə saitlər  3) Əşyanın adı (isim)
// 4) Əlamət bildirən sözlər (sifət)  5) Hərəkət bildirən sözlər (feil)  6) Sözün mənası və orfoqrafiya.
// 2-ci sinif üçün sadə. id prefiksi az2-*.

import type { Subject } from "../types";

export const azerbaijani2: Subject = {
  slug: "azerbaycan-dili-2",
  name: "Azərbaycan dili",
  grade: 2,
  icon: "A",
  color: "rose",
  units: [
    // ═══════════════ 1. Əlifba sırası ═══════════════
    {
      id: "az2-elifba",
      title: "Əlifba sırası",
      description: "Hərfləri əlifba sırası ilə düzmək və lüğətdə söz axtarmaq.",
      lessons: [
        {
          id: "az2-elifba-l1",
          title: "Əlifba sırası",
          intro: "Hərflərin əlifbadakı sırasını öyrənək.",
          sections: [
            { heading: "Əlifba", body: "Azərbaycan əlifbasında 32 hərf müəyyən sıra ilə düzülür: a, b, c, ç, d, e, ə, f, g, ğ, h, x, ı, i, j, k, q, l, m, n, o, ö, p, r, s, ş, t, u, ü, v, y, z." },
            { heading: "Faydası", body: "Lüğətdə sözlər əlifba sırası ilə düzülür. Bu, sözü tez tapmağa kömək edir." },
          ],
          tasks: [
            { id: "az2-elifba-l1-t1", type: "multiple_choice", prompt: "Əlifbada 'a'-dan sonra hansı hərf gəlir?", options: ["b", "c", "d", "e"], correctIndex: 0, xp: 10, explanation: "Əlifba belə başlayır: a, b, c, ç... Deməli a-dan sonra b gəlir.", skills: ["az.phon.alphabet"] },
            { id: "az2-elifba-l1-t2", type: "multiple_choice", prompt: "Əlifbada ilk hərf hansıdır?", options: ["a", "b", "z", "e"], correctIndex: 0, xp: 10, explanation: "Əlifba a hərfi ilə başlayır.", skills: ["az.phon.alphabet"] },
            { id: "az2-elifba-l1-t3", type: "multiple_choice", prompt: "Əlifbada son hərf hansıdır?", options: ["z", "y", "a", "v"], correctIndex: 0, xp: 10, explanation: "Əlifba z hərfi ilə bitir — o, 32-ci hərfdir.", skills: ["az.phon.alphabet"] },
            { id: "az2-elifba-l1-t4", type: "multiple_choice", prompt: "'b' və 'c' hərflərindən hansı əvvəl gəlir?", options: ["b", "c", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "Əlifba sırasında b, c-dən əvvəl gəlir: a, b, c.", skills: ["az.phon.letters"] },
            { id: "az2-elifba-l1-t5", type: "multiple_choice", prompt: "'m' və 'n' hərflərindən hansı əvvəl gəlir?", options: ["m", "n", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "Əlifba sırasında m, n-dən əvvəl gəlir: l, m, n.", skills: ["az.phon.letters"] },
            { id: "az2-elifba-l1-t6", type: "multiple_choice", prompt: "'d'-dən sonra hansı hərf gəlir?", options: ["e", "c", "b", "f"], correctIndex: 0, xp: 10, explanation: "Əlifba sırası: c, ç, d, e. Deməli d-dən sonra e gəlir.", skills: ["az.phon.letters"] },
            { id: "az2-elifba-l1-t7", type: "multiple_choice", prompt: "Lüğətdə sözlər necə düzülür?", options: ["əlifba sırası ilə", "uzunluğuna görə", "təsadüfi", "rəngə görə"], correctIndex: 0, xp: 10, explanation: "Lüğətdə söz tez tapılsın deyə sözlər əlifba sırası ilə düzülür.", skills: ["az.phon.alphabet"] },
            { id: "az2-elifba-l1-t8", type: "multiple_choice", prompt: "'alma' və 'baba' sözlərindən hansı lüğətdə əvvəl gəlir?", options: ["alma", "baba", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "İlk hərflərə baxırıq: a və b. Əlifbada a, b-dən əvvəl gəlir, deməli «alma» birincidir.", skills: ["az.phon.alphabet"] },
            { id: "az2-elifba-l1-t9", type: "multiple_choice", prompt: "'kitab' və 'su' sözlərindən hansı lüğətdə əvvəl gəlir?", options: ["kitab", "su", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "İlk hərflərə baxırıq: k və s. Əlifbada k, s-dən əvvəl gəlir, deməli «kitab» birincidir.", skills: ["az.phon.alphabet"] },
            { id: "az2-elifba-l1-t10", type: "multiple_choice", prompt: "'r' və 's' hərflərindən hansı əvvəl gəlir?", options: ["r", "s", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "Əlifba sırasında r, s-dən əvvəl gəlir: r, s, ş.", skills: ["az.phon.letters"] },
            { id: "az2-elifba-l1-t11", type: "numeric", prompt: "Əlifbada neçə hərf var?", answer: 32, xp: 10, explanation: "Azərbaycan əlifbasında 9 sait və 23 samit var: 9 + 23 = 32 hərf.", skills: ["az.phon.alphabet"] },
            { id: "az2-elifba-l1-t12", type: "multiple_choice", prompt: "'e'-dən sonra hansı hərf gəlir?", options: ["ə", "d", "f", "c"], correctIndex: 0, xp: 10, explanation: "Əlifba sırası: d, e, ə, f. Deməli e-dən sonra ə gəlir.", skills: ["az.phon.letters"] },
            { id: "az2-elifba-l1-t13", type: "multiple_choice", prompt: "'ana', 'baba', 'dağ' sözlərindən hansı əlifbada birinci gəlir?", options: ["ana", "baba", "dağ", "heç biri"], correctIndex: 0, xp: 10, explanation: "İlk hərflər: a, b, d. Əlifbada a hamısından əvvəl gəlir, deməli «ana» birincidir.", skills: ["az.phon.alphabet"] },
            { id: "az2-elifba-l1-t14", type: "multiple_choice", prompt: "'z'-dən əvvəl hansı hərf gəlir?", options: ["y", "v", "a", "s"], correctIndex: 0, xp: 10, explanation: "Əlifbanın sonu: v, y, z. Deməli z-dən əvvəl y gəlir.", skills: ["az.phon.letters"] },
            { id: "az2-elifba-l1-t15", type: "multiple_choice", prompt: "'top' və 'ağac' sözlərindən hansı lüğətdə əvvəl gəlir?", options: ["ağac", "top", "bərabər", "heç biri"], correctIndex: 0, xp: 15, explanation: "İlk hərflərə baxırıq: a və t. Əlifbada a əvvəl gəlir, deməli «ağac» birincidir.", skills: ["az.phon.alphabet"] },
          ],
          bonusTasks: [
            { id: "az2-elifba-l1-b1", type: "multiple_choice", prompt: "'gül', 'çiçək', 'ağac' — əlifbada birinci gələn hansıdır?", options: ["ağac", "çiçək", "gül", "heç biri"], correctIndex: 0, xp: 15, explanation: "İlk hərflər: g, ç, a. Əlifba sırası a, ç, g olduğu üçün «ağac» birincidir.", skills: ["az.phon.alphabet"] },
            { id: "az2-elifba-l1-b2", type: "multiple_choice", prompt: "'k' və 'q' hərflərindən hansı əvvəl gəlir?", options: ["k", "q", "bərabər", "heç biri"], correctIndex: 0, xp: 15, explanation: "Azərbaycan əlifbasında k hərfi q-dan əvvəl gəlir: k, q, l.", skills: ["az.phon.letters"] },
            { id: "az2-elifba-l1-b3", type: "multiple_choice", prompt: "'ata' və 'ana' sözlərindən hansı lüğətdə əvvəl gəlir? (2-ci hərfə bax)", options: ["ana", "ata", "bərabər", "heç biri"], correctIndex: 0, xp: 15, explanation: "İlk hərflər eynidir (a), ona görə ikinci hərflərə baxırıq: n və t. Əlifbada n əvvəl gəlir, deməli «ana» birincidir.", skills: ["az.phon.letters"] },
            { id: "az2-elifba-l1-b4", type: "multiple_choice", prompt: "'ö'-dən sonra hansı hərf gəlir?", options: ["p", "o", "r", "n"], correctIndex: 0, xp: 15, explanation: "Əlifba sırası: o, ö, p. Deməli ö-dən sonra p gəlir.", skills: ["az.phon.letters"] },
            { id: "az2-elifba-l1-b5", type: "multiple_choice", prompt: "'su', 'sən', 'saç' — əlifbada birinci gələn hansıdır? (2-ci hərf)", options: ["saç", "sən", "su", "heç biri"], correctIndex: 0, xp: 15, explanation: "İlk hərflər eynidir (s), ona görə ikinci hərflərə baxırıq: u, ə, a. Əlifbada a birincidir, deməli «saç» birinci gəlir.", skills: ["az.phon.alphabet"] },
          ],
        },
        {
          id: "az2-elifba-l2",
          title: "Hərflərin sırası",
          intro: "Sözləri lüğətdəki kimi sıralamağı öyrənək.",
          sections: [
            { heading: "Əlifba sırası", body: "Sözləri sıralayanda ƏVVƏL birinci hərfə baxırıq. Birinci hərf eynidirsə, ikinci hərfə keçirik: 'alma' və 'armud' — hər ikisi a ilə başlayır, sonra l < r, deməli 'alma' əvvəl gəlir." },
            { heading: "Nə üçün lazımdır?", body: "Lüğətdə, ensiklopediyada və jurnalda adlar əlifba sırası ilə düzülür — söz axtarmaq asan olsun deyə." },
          ],
          tasks: [
            { id: "az2-elifba-l2-t1", type: "multiple_choice", prompt: "Əlifbada hansı hərf birinci gəlir?", options: ["A", "B", "C", "Ç"], correctIndex: 0, xp: 10, explanation: "Əlifba A hərfi ilə başlayır.", skills: ["az.phon.alphabet"] },
            { id: "az2-elifba-l2-t2", type: "multiple_choice", prompt: "'alma' və 'armud' — hansı əlifbada əvvəl gəlir?", options: ["alma", "armud", "İkisi eynidir", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "İlk hərflər eynidir (a), ikinci hərflərə baxırıq: l və r. Əlifbada l əvvəl gəlir, deməli «alma» birincidir.", skills: ["az.phon.alphabet"] },
            { id: "az2-elifba-l2-t3", type: "multiple_choice", prompt: "'kitab' və 'qələm' — hansı əvvəl gəlir?", options: ["kitab", "qələm", "İkisi eynidir", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "İlk hərflərə baxırıq: k və q. Azərbaycan əlifbasında k, q-dan əvvəl gəlir, deməli «kitab» birincidir.", skills: ["az.phon.alphabet"] },
            { id: "az2-elifba-l2-t4", type: "multiple_choice", prompt: "Birinci hərflər eynidirsə nəyə baxırıq?", options: ["İkinci hərfə", "Sözün uzunluğuna", "Sonuncu hərfə", "Heç nəyə"], correctIndex: 0, xp: 10, explanation: "Sıralama hərf-hərf aparılır: birinci hərflər eyni olanda ikinci hərflər müqayisə edilir.", skills: ["az.phon.letters"] },
            { id: "az2-elifba-l2-t5", type: "multiple_choice", prompt: "'top', 'tel', 'tut' — hansı əvvəl gəlir?", options: ["tel", "top", "tut", "Fərqi yoxdur"], correctIndex: 0, xp: 10, explanation: "İlk hərflər eynidir (t), ikinci hərflərə baxırıq: o, e, u. Əlifbada e birincidir, deməli «tel» əvvəl gəlir.", skills: ["az.phon.alphabet"] },
            { id: "az2-elifba-l2-t6", type: "multiple_choice", prompt: "Lüğətdə sözlər necə düzülür?", options: ["Əlifba sırası ilə", "Uzunluğuna görə", "Təsadüfi", "Mənasına görə"], correctIndex: 0, xp: 10, explanation: "Lüğətdə söz tez tapılsın deyə sözlər əlifba sırası ilə düzülür.", skills: ["az.phon.alphabet"] },
            { id: "az2-elifba-l2-t7", type: "multiple_choice", prompt: "Əlifbada 'M' hərfindən sonra hansı gəlir?", options: ["N", "L", "K", "O"], correctIndex: 0, xp: 10, explanation: "Əlifba sırası: L, M, N, O. Deməli M-dən sonra N gəlir.", skills: ["az.phon.alphabet"] },
            { id: "az2-elifba-l2-t8", type: "multiple_choice", prompt: "'ana' və 'ata' — hansı əvvəl gəlir?", options: ["ana", "ata", "İkisi eynidir", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "İlk hərflər eynidir (a), ikinci hərflərə baxırıq: n və t. Əlifbada n əvvəl gəlir, deməli «ana» birincidir.", skills: ["az.phon.alphabet"] },
            { id: "az2-elifba-l2-t9", type: "fill_blank", prompt: "Əlifbanın birinci hərfi ______-dır. (bir hərf)", accepted: ["A", "a"], xp: 10, explanation: "Əlifbanın birinci hərfi A-dır.", skills: ["az.phon.alphabet"] },
            { id: "az2-elifba-l2-t10", type: "multiple_choice", prompt: "'su', 'sual', 'səs' — əlifbada birinci hansıdır?", options: ["səs", "su", "sual", "Fərqi yoxdur"], correctIndex: 0, xp: 10, explanation: "İlk hərflər eynidir (s), ikinci hərflərə baxırıq: u, u, ə. Əlifbada ə, u-dan əvvəl gəlir, deməli «səs» birincidir.", skills: ["az.phon.alphabet"] },
          ],
          bonusTasks: [
            { id: "az2-elifba-l2-b1", type: "multiple_choice", prompt: "'dəftər', 'dərs', 'dəniz' — birinci hansıdır?", options: ["dəftər", "dəniz", "dərs", "Fərqi yoxdur"], correctIndex: 0, xp: 15, explanation: "İlk iki hərf eynidir (də), üçüncü hərflərə baxırıq: f, r, n. Əlifba sırası f, n, r olduğu üçün «dəftər» birincidir.", skills: ["az.phon.alphabet"] },
            { id: "az2-elifba-l2-b2", type: "multiple_choice", prompt: "Niyə telefon kitabçasında adlar əlifba ilə yazılır?", options: ["Tez tapmaq üçün", "Gözəl görünsün deyə", "Az yer tutsun deyə", "Səbəbi yoxdur"], correctIndex: 0, xp: 15, explanation: "Adlar əlifba ilə düzüləndə axtarılan ad dərhal öz hərfinin yanında tapılır — vaxta qənaət olur.", skills: ["az.phon.alphabet"] },
            { id: "az2-elifba-l2-b3", type: "multiple_choice", prompt: "Əlifbada 'Ə' hərfi hansından sonra gəlir?", options: ["E", "A", "D", "F"], correctIndex: 0, xp: 15, explanation: "Əlifba sırası: D, E, Ə, F. Deməli Ə hərfi E-dən sonra gəlir.", skills: ["az.phon.alphabet"] },
            { id: "az2-elifba-l2-b4", type: "multiple_choice", prompt: "'bal', 'bala', 'balıq' — birinci hansıdır?", options: ["bal", "bala", "balıq", "Fərqi yoxdur"], correctIndex: 0, xp: 15, explanation: "Üç sözün də başlanğıcı eynidir, amma «bal» ən qısadır və digərləri onunla başlayır — qısa söz əvvəl gəlir.", skills: ["az.phon.alphabet"] },
          ],
        },
        {
          id: "az2-elifba-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az2-elifba-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 2. Qalın və incə saitlər ═══════════════
    {
      id: "az2-sait",
      title: "Qalın və incə saitlər",
      description: "Saitləri qalın (a, ı, o, u) və incə (e, ə, i, ö, ü) saitlərə ayırmaq.",
      lessons: [
        {
          id: "az2-sait-l1",
          title: "Qalın və incə saitlər",
          intro: "9 sait iki qrupa bölünür: qalın və incə.",
          sections: [
            { heading: "Qalın saitlər", body: "a, ı, o, u — bunlar qalın saitlərdir (4 dənə)." },
            { heading: "İncə saitlər", body: "e, ə, i, ö, ü — bunlar incə saitlərdir (5 dənə)." },
          ],
          tasks: [
            { id: "az2-sait-l1-t1", type: "multiple_choice", prompt: "Aşağıdakılardan hansı qalın saitdir?", options: ["a", "e", "i", "ə"], correctIndex: 0, xp: 10, explanation: "Qalın saitlər: a, ı, o, u. Bunlardan yalnız «a» variantlar arasındadır.", skills: ["az.phon.vowels"] },
            { id: "az2-sait-l1-t2", type: "multiple_choice", prompt: "Aşağıdakılardan hansı incə saitdir?", options: ["e", "a", "o", "u"], correctIndex: 0, xp: 10, explanation: "İncə saitlər: e, ə, i, ö, ü. Bunlardan yalnız «e» variantlar arasındadır.", skills: ["az.phon.vowels"] },
            { id: "az2-sait-l1-t3", type: "multiple_choice", prompt: "'o' saiti hansı qrupdandır?", options: ["qalın", "incə", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«o» qalın saitlərdəndir: a, ı, o, u.", skills: ["az.phon.vowels"] },
            { id: "az2-sait-l1-t4", type: "multiple_choice", prompt: "'ə' saiti hansı qrupdandır?", options: ["incə", "qalın", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«ə» incə saitlərdəndir: e, ə, i, ö, ü.", skills: ["az.phon.vowels"] },
            { id: "az2-sait-l1-t5", type: "multiple_choice", prompt: "Aşağıdakılardan hansı qalın saitdir?", options: ["u", "i", "ö", "ü"], correctIndex: 0, xp: 10, explanation: "«u» qalın saitlərdəndir: a, ı, o, u.", skills: ["az.phon.vowels"] },
            { id: "az2-sait-l1-t6", type: "multiple_choice", prompt: "Aşağıdakılardan hansı incə saitdir?", options: ["ü", "a", "ı", "o"], correctIndex: 0, xp: 10, explanation: "«ü» incə saitlərdəndir: e, ə, i, ö, ü.", skills: ["az.phon.vowels"] },
            { id: "az2-sait-l1-t7", type: "numeric", prompt: "Neçə qalın sait var? (a, ı, o, u)", answer: 4, xp: 10, explanation: "Qalın saitləri sayaq: a, ı, o, u — 4 dənə.", skills: ["az.phon.vowels"] },
            { id: "az2-sait-l1-t8", type: "numeric", prompt: "Neçə incə sait var? (e, ə, i, ö, ü)", answer: 5, xp: 10, explanation: "İncə saitləri sayaq: e, ə, i, ö, ü — 5 dənə.", skills: ["az.phon.vowels"] },
            { id: "az2-sait-l1-t9", type: "multiple_choice", prompt: "'ı' saiti hansı qrupdandır?", options: ["qalın", "incə", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«ı» qalın saitlərdəndir: a, ı, o, u.", skills: ["az.phon.vowels"] },
            { id: "az2-sait-l1-t10", type: "multiple_choice", prompt: "'i' saiti hansı qrupdandır?", options: ["incə", "qalın", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«i» incə saitlərdəndir: e, ə, i, ö, ü.", skills: ["az.phon.vowels"] },
            { id: "az2-sait-l1-t11", type: "multiple_choice", prompt: "'alma' sözündəki saitlər (a, a) hansı qrupdandır?", options: ["qalın", "incə", "qarışıq", "heç biri"], correctIndex: 0, xp: 10, explanation: "«alma» sözündə hər iki sait a-dır, a isə qalın saitdir.", skills: ["az.phon.vowels"] },
            { id: "az2-sait-l1-t12", type: "multiple_choice", prompt: "'ev' sözündəki sait (e) hansı qrupdandır?", options: ["incə", "qalın", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«ev» sözündəki yeganə sait e-dir, e isə incə saitdir.", skills: ["az.phon.vowels"] },
            { id: "az2-sait-l1-t13", type: "multiple_choice", prompt: "Hansı sırada yalnız qalın saitlər var?", options: ["a, o, u", "e, i, ə", "a, e, i", "o, ö, ü"], correctIndex: 0, xp: 10, explanation: "a, o, u — üçü də qalın saitlər siyahısındadır (a, ı, o, u).", skills: ["az.phon.vowels"] },
            { id: "az2-sait-l1-t14", type: "multiple_choice", prompt: "Hansı sırada yalnız incə saitlər var?", options: ["e, ə, i", "a, ı, o", "a, e, o", "u, ü, ı"], correctIndex: 0, xp: 10, explanation: "e, ə, i — üçü də incə saitlər siyahısındadır (e, ə, i, ö, ü).", skills: ["az.phon.vowels"] },
            { id: "az2-sait-l1-t15", type: "multiple_choice", prompt: "'ö' saiti hansı qrupdandır?", options: ["incə", "qalın", "hər ikisi", "heç biri"], correctIndex: 0, xp: 15, explanation: "«ö» incə saitlərdəndir: e, ə, i, ö, ü.", skills: ["az.phon.vowels"] },
          ],
          bonusTasks: [
            { id: "az2-sait-l1-b1", type: "multiple_choice", prompt: "'gül' sözündəki sait (ü) hansı qrupdandır?", options: ["incə", "qalın", "hər ikisi", "heç biri"], correctIndex: 0, xp: 15, explanation: "«gül» sözündəki sait ü-dür, ü isə incə saitdir.", skills: ["az.phon.vowels"] },
            { id: "az2-sait-l1-b2", type: "multiple_choice", prompt: "'qutu' sözündəki saitlər (u, u) hansı qrupdandır?", options: ["qalın", "incə", "qarışıq", "heç biri"], correctIndex: 0, xp: 15, explanation: "«qutu» sözündə hər iki sait u-dur, u isə qalın saitdir.", skills: ["az.phon.vowels"] },
            { id: "az2-sait-l1-b3", type: "numeric", prompt: "4 qalın + 5 incə = neçə sait?", answer: 9, xp: 15, explanation: "Bütün saitlər iki qrupa bölünür: 4 + 5 = 9 sait.", skills: ["az.phon.vowels","az.phon.harmony"] },
            { id: "az2-sait-l1-b4", type: "multiple_choice", prompt: "'kitab' sözündə qalın saitlər (i incədir, a qalın) — 'a' hansı qrupdandır?", options: ["qalın", "incə", "hər ikisi", "heç biri"], correctIndex: 0, xp: 15, explanation: "«a» qalın saitlərdəndir: a, ı, o, u. Sözdə həm qalın, həm incə sait ola bilər.", skills: ["az.phon.vowels","az.phon.harmony"] },
            { id: "az2-sait-l1-b5", type: "multiple_choice", prompt: "'ördək' sözündəki 'ö' saiti hansı qrupdandır?", options: ["incə", "qalın", "hər ikisi", "heç biri"], correctIndex: 0, xp: 15, explanation: "«ö» incə saitlərdəndir: e, ə, i, ö, ü.", skills: ["az.phon.vowels"] },
          ],
        },
        {
          id: "az2-sait-l2",
          title: "Sözü hecalara böl",
          intro: "Hər hecada bir sait var — heca saymaq asandır.",
          sections: [
            { heading: "Heca nədir?", body: "Söz tələffüz edərkən hissə-hissə deyilir: ki-tab, mək-təb. Hər hissəyə HECA deyilir." },
            { heading: "Qayda", body: "Sözdə neçə SAİT varsa, o qədər heca var: 'alma' → a-l-m-a, iki sait (a, a) → iki heca: al-ma." },
          ],
          tasks: [
            { id: "az2-sait-l2-t1", type: "multiple_choice", prompt: "'kitab' sözündə neçə heca var?", options: ["2", "1", "3", "4"], correctIndex: 0, xp: 10, explanation: "«kitab» sözündə iki sait var (i, a), ona görə iki heca: ki-tab.", skills: ["az.phon.syllable"] },
            { id: "az2-sait-l2-t2", type: "multiple_choice", prompt: "'məktəb' sözündə neçə heca var?", options: ["2", "1", "3", "4"], correctIndex: 0, xp: 10, explanation: "«məktəb» sözündə iki sait var (ə, ə), ona görə iki heca: mək-təb.", skills: ["az.phon.syllable"] },
            { id: "az2-sait-l2-t3", type: "multiple_choice", prompt: "'alma' sözündə neçə heca var?", options: ["2", "1", "3", "4"], correctIndex: 0, xp: 10, explanation: "«alma» sözündə iki sait var (a, a), ona görə iki heca: al-ma.", skills: ["az.phon.syllable"] },
            { id: "az2-sait-l2-t4", type: "multiple_choice", prompt: "Heca sayını nə müəyyən edir?", options: ["Saitlərin sayı", "Samitlərin sayı", "Hərflərin sayı", "Sözün uzunluğu"], correctIndex: 0, xp: 10, explanation: "Hər hecanın mərkəzində mütləq bir sait durur, ona görə heca sayı saitlərin sayı qədərdir.", skills: ["az.phon.syllable","az.pos.numeral"] },
            { id: "az2-sait-l2-t5", type: "multiple_choice", prompt: "'ana' sözündə neçə heca var?", options: ["2", "1", "3", "4"], correctIndex: 0, xp: 10, explanation: "«ana» sözündə iki sait var (a, a), ona görə iki heca: a-na.", skills: ["az.phon.syllable"] },
            { id: "az2-sait-l2-t6", type: "multiple_choice", prompt: "'qələm' sözündə neçə heca var?", options: ["2", "1", "3", "4"], correctIndex: 0, xp: 10, explanation: "«qələm» sözündə iki sait var (ə, ə), ona görə iki heca: qə-ləm.", skills: ["az.phon.syllable"] },
            { id: "az2-sait-l2-t7", type: "multiple_choice", prompt: "'top' sözündə neçə heca var?", options: ["1", "2", "3", "4"], correctIndex: 0, xp: 10, explanation: "«top» sözündə tək bir sait var (o), ona görə 1 heca.", skills: ["az.phon.syllable"] },
            { id: "az2-sait-l2-t8", type: "multiple_choice", prompt: "'ba-la-ca' — bu sözdə neçə heca var?", options: ["3", "2", "4", "1"], correctIndex: 0, xp: 10, explanation: "Sözdə üç sait var (a, a, a), ona görə üç heca: ba-la-ca.", skills: ["az.phon.syllable"] },
            { id: "az2-sait-l2-t9", type: "fill_blank", prompt: "Sözdə neçə ______ varsa, o qədər heca var. (bir söz)", accepted: ["sait", "Sait", "saitli"], xp: 10, explanation: "Hər hecada bir sait olduğu üçün heca sayı sait sayı qədərdir.", skills: ["az.phon.syllable"] },
            { id: "az2-sait-l2-t10", type: "multiple_choice", prompt: "'su' sözündə neçə heca var?", options: ["1", "2", "3", "0"], correctIndex: 0, xp: 10, explanation: "«su» sözündə tək bir sait var (u), ona görə 1 heca.", skills: ["az.phon.syllable"] },
          ],
          bonusTasks: [
            { id: "az2-sait-l2-b1", type: "multiple_choice", prompt: "'müəllim' sözündə neçə heca var?", options: ["3", "2", "4", "1"], correctIndex: 0, xp: 15, explanation: "«müəllim» sözündə üç sait var (ü, ə, i), ona görə üç heca: mü-əl-lim.", skills: ["az.phon.syllable"] },
            { id: "az2-sait-l2-b2", type: "multiple_choice", prompt: "Bir hecada ən azı neçə sait olur?", options: ["1", "0", "2", "3"], correctIndex: 0, xp: 15, explanation: "Saitsiz heca olmur, ona görə hər hecada ən azı 1 sait var.", skills: ["az.phon.vowels","az.phon.syllable"] },
            { id: "az2-sait-l2-b3", type: "multiple_choice", prompt: "'Azərbaycan' sözündə neçə heca var?", options: ["4", "3", "5", "2"], correctIndex: 0, xp: 15, explanation: "«Azərbaycan» sözündə dörd sait var (a, ə, a, a), ona görə dörd heca: A-zər-bay-can.", skills: ["az.phon.syllable"] },
            { id: "az2-sait-l2-b4", type: "multiple_choice", prompt: "Hansı sözdə hecaların sayı ən çoxdur?", options: ["kitabxana", "kitab", "kitabça", "ki"], correctIndex: 0, xp: 15, explanation: "Hecaları sayaq: ki (1), ki-tab (2), ki-tab-ça (3), ki-tab-xa-na (4). Ən çoxu «kitabxana»dadır.", skills: ["az.phon.syllable","az.pos.numeral"] },
          ],
        },
        {
          id: "az2-sait-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az2-sait-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 3. Əşyanın adı (isim) ═══════════════
    {
      id: "az2-isim",
      title: "Əşyanın adı (isim)",
      description: "Əşyanın adını bildirən, 'kim?', 'nə?' suallarına cavab verən sözlər.",
      lessons: [
        {
          id: "az2-isim-l1",
          title: "Əşyanın adını bildirən sözlər",
          intro: "'Kim?' və 'nə?' suallarına cavab verən sözlər.",
          sections: [
            { heading: "Əşyanın adı", body: "İnsanları, əşyaları, heyvanları, yerləri adlandıran sözlər əşyanın adıdır (isim). 'Kim?' (insan/heyvan) və ya 'nə?' (əşya) suallarına cavab verir: ana, kitab, pişik, məktəb." },
          ],
          tasks: [
            { id: "az2-isim-l1-t1", type: "multiple_choice", prompt: "Aşağıdakılardan hansı əşyanın adıdır?", options: ["kitab", "oxumaq", "gözəl", "tez"], correctIndex: 0, xp: 10, explanation: "«Kitab» əlimizlə tuta bildiyimiz əşyadır. Oxumaq hərəkət, gözəl əlamət, tez isə tərz bildirir.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l1-t2", type: "multiple_choice", prompt: "Aşağıdakılardan hansı əşyanın adıdır?", options: ["pişik", "qaçmaq", "böyük", "yavaş"], correctIndex: 0, xp: 10, explanation: "«Pişik» canlı varlıqdır. Yavaş və böyük əlamət, qaçmaq isə hərəkət bildirir.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l1-t3", type: "multiple_choice", prompt: "'ana' sözü hansı suala cavab verir?", options: ["kim?", "necə?", "nə edir?", "neçə?"], correctIndex: 0, xp: 10, explanation: "Ana insandır, yəni canlıdır — canlılara «kim?» sualı verilir.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l1-t4", type: "multiple_choice", prompt: "'kitab' sözü hansı suala cavab verir?", options: ["nə?", "kim?", "necə?", "nə edir?"], correctIndex: 0, xp: 10, explanation: "Kitab cansız əşyadır — cansızlara «nə?» sualı verilir.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l1-t5", type: "multiple_choice", prompt: "Aşağıdakılardan hansı əşyanın adı DEYİL?", options: ["oxumaq", "kitab", "məktəb", "uşaq"], correctIndex: 0, xp: 10, explanation: "Məktəb, uşaq və kitab adlardır. «Oxumaq» isə iş, hərəkət bildirir.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l1-t6", type: "multiple_choice", prompt: "'müəllim' sözü hansı suala cavab verir?", options: ["kim?", "nə?", "necə?", "harada?"], correctIndex: 0, xp: 10, explanation: "Müəllim insandır — canlılara «kim?» sualı verilir.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l1-t7", type: "multiple_choice", prompt: "Aşağıdakılardan hansı əşyanın adıdır?", options: ["ev", "gəlmək", "isti", "çox"], correctIndex: 0, xp: 10, explanation: "«Ev» əşyadır. İsti əlamət, gəlmək hərəkət, çox isə kəmiyyət bildirir.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l1-t8", type: "multiple_choice", prompt: "Heyvan adları hansı suala cavab verir?", options: ["kim?", "necə?", "nə edir?", "haçan?"], correctIndex: 0, xp: 10, explanation: "Heyvanlar canlıdır, ona görə onların adları «kim?» sualına cavab verir.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l1-t9", type: "multiple_choice", prompt: "'Uşaq kitab oxuyur.' cümləsində əşya adları hansılardır?", options: ["uşaq, kitab", "oxuyur", "uşaq oxuyur", "heç biri"], correctIndex: 0, xp: 10, explanation: "Cümlədə «uşaq» və «kitab» adlardır. «Oxuyur» isə hərəkət bildirir.", skills: ["az.syn.sentence"] },
            { id: "az2-isim-l1-t10", type: "multiple_choice", prompt: "Aşağıdakılardan hansı əşyanın adıdır?", options: ["dağ", "böyük", "getmək", "gözəl"], correctIndex: 0, xp: 10, explanation: "«Dağ» yer, yəni əşya adıdır. Gözəl və böyük əlamət, getmək isə hərəkət bildirir.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l1-t11", type: "multiple_choice", prompt: "'çanta' sözü hansı suala cavab verir?", options: ["nə?", "kim?", "necə?", "neçə?"], correctIndex: 0, xp: 10, explanation: "Çanta cansız əşyadır — cansızlara «nə?» sualı verilir.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l1-t12", type: "multiple_choice", prompt: "İnsan adları (Ayşə, Elçin) necə yazılır?", options: ["böyük hərflə", "kiçik hərflə", "rəqəmlə", "fərq etməz"], correctIndex: 0, xp: 10, explanation: "İnsan adları xüsusi addır, ona görə həmişə böyük hərflə yazılır.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l1-t13", type: "multiple_choice", prompt: "Aşağıdakılardan hansı əşyanın adıdır?", options: ["su", "içmək", "soyuq", "tez"], correctIndex: 0, xp: 10, explanation: "«Su» əşyadır. Soyuq əlamət, içmək hərəkət, tez isə tərz bildirir.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l1-t14", type: "multiple_choice", prompt: "'Bakı' sözü nəyin adıdır?", options: ["şəhərin (yer)", "əşyanın", "heyvanın", "rəngin"], correctIndex: 0, xp: 10, explanation: "Bakı bir şəhərin xüsusi adıdır, yəni yer adıdır.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l1-t15", type: "multiple_choice", prompt: "Aşağıdakılardan hansı əşyanın adıdır?", options: ["quş", "uçmaq", "yaşıl", "yüksək"], correctIndex: 0, xp: 15, explanation: "«Quş» canlıdır və addır. Yüksək və yaşıl əlamət, uçmaq isə hərəkət bildirir.", skills: ["az.pos.noun"] },
          ],
          bonusTasks: [
            { id: "az2-isim-l1-b1", type: "multiple_choice", prompt: "'Gözəl gül bağçada açdı.' — əşya adları hansılardır?", options: ["gül, bağça", "gözəl", "açdı", "gözəl açdı"], correctIndex: 0, xp: 15, explanation: "Cümlədə «gül» və «bağça» adlardır. «Gözəl» əlamət, «açdı» isə hərəkət bildirir.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l1-b2", type: "multiple_choice", prompt: "Aşağıdakı sıradan əşya adını seç.", options: ["dəftər", "yazmaq", "səliqəli", "dünən"], correctIndex: 0, xp: 15, explanation: "«Dəftər» əşyadır. Səliqəli əlamət, yazmaq hərəkət, dünən isə vaxt bildirir.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l1-b3", type: "multiple_choice", prompt: "'kim?' sualına cavab verən söz kimi/nəyi bildirir?", options: ["insan və ya heyvanı", "əşyanı", "rəngi", "hərəkəti"], correctIndex: 0, xp: 15, explanation: "«Kim?» sualı yalnız canlılara — insan və heyvanlara verilir.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l1-b4", type: "multiple_choice", prompt: "'nə?' sualına cavab verən söz nəyi bildirir?", options: ["cansız əşyanı", "insanı", "hərəkəti", "əlaməti"], correctIndex: 0, xp: 15, explanation: "«Nə?» sualı canlı olmayan əşyalara verilir.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l1-b5", type: "multiple_choice", prompt: "Aşağıdakılardan hansı əşyanın adı DEYİL?", options: ["qırmızı", "alma", "top", "ev"], correctIndex: 0, xp: 15, explanation: "Alma, ev və top əşyadır. «Qırmızı» isə əşyanın rəngini, yəni əlamətini bildirir.", skills: ["az.pos.noun"] },
          ],
        },
        {
          id: "az2-isim-l2",
          title: "Tək və cəm",
          intro: "Bir əşya — tək, çox əşya — cəmdir.",
          sections: [
            { heading: "Cəm şəkilçisi", body: "İsimlərə -lar / -lər əlavə edərək cəm düzəldirik: kitab → kitablar, ev → evlər." },
            { heading: "Hansını seçək?", body: "Sözün son saiti QALIN (a, ı, o, u) olsa -lar; İNCƏ (e, ə, i, ö, ü) olsa -lər yazılır." },
          ],
          tasks: [
            { id: "az2-isim-l2-t1", type: "multiple_choice", prompt: "'kitab' sözünün cəmi hansıdır?", options: ["kitablar", "kitablər", "kitabler", "kitabıq"], correctIndex: 0, xp: 10, explanation: "«Kitab» sözünün son saiti a-dır, yəni qalındır — ona görə qalın şəkilçi qoşulur: kitablar.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l2-t2", type: "multiple_choice", prompt: "'ev' sözünün cəmi hansıdır?", options: ["evlər", "evlar", "evler", "evıq"], correctIndex: 0, xp: 10, explanation: "«Ev» sözünün saiti e-dir, yəni incədir — ona görə incə şəkilçi qoşulur: evlər.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l2-t3", type: "multiple_choice", prompt: "'quş' sözünün cəmi hansıdır?", options: ["quşlar", "quşlər", "quşler", "quşuq"], correctIndex: 0, xp: 10, explanation: "«Quş» sözünün saiti u-dur, yəni qalındır — ona görə: quşlar.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l2-t4", type: "multiple_choice", prompt: "Cəm şəkilçiləri hansılardır?", options: ["-lar, -lər", "-da, -də", "-ın, -in", "-çı, -çi"], correctIndex: 0, xp: 10, explanation: "Cəm şəkilçisi ahəngə görə iki cür olur: qalın sözlərə -lar, incə sözlərə -lər.", skills: ["az.morph.root","az.pos.noun_possess"] },
            { id: "az2-isim-l2-t5", type: "multiple_choice", prompt: "Son sait qalın olanda hansı şəkilçi yazılır?", options: ["-lar", "-lər", "İkisi də", "Heç biri"], correctIndex: 0, xp: 10, explanation: "Ahəng qanununa görə qalın saitli sözə qalın şəkilçi — yəni -lar qoşulur.", skills: ["az.phon.vowels","az.morph.root"] },
            { id: "az2-isim-l2-t6", type: "multiple_choice", prompt: "'gül' sözünün cəmi hansıdır?", options: ["güllər", "güllar", "gullar", "gülıq"], correctIndex: 0, xp: 10, explanation: "«Gül» sözünün saiti ü-dür, yəni incədir — ona görə: güllər.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l2-t7", type: "multiple_choice", prompt: "'uşaq' sözünün cəmi hansıdır?", options: ["uşaqlar", "uşaqlər", "uşaqler", "uşaqıq"], correctIndex: 0, xp: 10, explanation: "«Uşaq» sözünün son saiti a-dır, yəni qalındır — ona görə: uşaqlar.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l2-t8", type: "fill_blank", prompt: "'dəftər' sözünün cəmi ______-dir.", accepted: ["dəftərlər", "Dəftərlər", "dəfterler"], xp: 10, explanation: "«Dəftər» sözünün saitləri incədir (ə, ə), ona görə -lər qoşulur: dəftərlər.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l2-t9", type: "multiple_choice", prompt: "Hansı söz cəmdədir?", options: ["ağaclar", "ağac", "ağacın", "ağaca"], correctIndex: 0, xp: 10, explanation: "«Ağaclar» sözündə -lar cəm şəkilçisi var — deməli birdən çox ağac nəzərdə tutulur.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l2-t10", type: "multiple_choice", prompt: "Hansı söz təkdədir?", options: ["pəncərə", "pəncərələr", "kitablar", "güllər"], correctIndex: 0, xp: 10, explanation: "«Pəncərə» sözündə cəm şəkilçisi yoxdur — deməli bir dənədir, təkdir.", skills: ["az.pos.noun"] },
          ],
          bonusTasks: [
            { id: "az2-isim-l2-b1", type: "multiple_choice", prompt: "'meyvə' sözünün cəmi hansıdır?", options: ["meyvələr", "meyvalar", "meyvelər", "meyvəıq"], correctIndex: 0, xp: 15, explanation: "«Meyvə» sözünün saitləri incədir (e, ə), ona görə -lər qoşulur: meyvələr.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l2-b2", type: "multiple_choice", prompt: "'oğlan' və 'oğlanlar' arasındakı fərq nədir?", options: ["Biri tək, digəri cəmdir", "Mənaları fərqlidir", "Fərq yoxdur", "Biri sifətdir"], correctIndex: 0, xp: 15, explanation: "«Oğlan» bir nəfəri, «oğlanlar» isə -lar şəkilçisi sayəsində bir neçə nəfəri bildirir.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l2-b3", type: "multiple_choice", prompt: "Hansı cümlədə cəm isim var?", options: ["Bağçada güllər açıb.", "Bağçada gül açıb.", "Gül gözəldir.", "Bu, güldür."], correctIndex: 0, xp: 15, explanation: "«Güllər» sözündə -lər cəm şəkilçisi var. Digər cümlələrdə «gül» təkdir.", skills: ["az.pos.noun"] },
            { id: "az2-isim-l2-b4", type: "multiple_choice", prompt: "'su' sözünün cəmi necə yazılır?", options: ["sular", "sulər", "suler", "suıq"], correctIndex: 0, xp: 15, explanation: "«Su» sözünün saiti u-dur, yəni qalındır — ona görə: sular.", skills: ["az.pos.noun"] },
          ],
        },
        {
          id: "az2-isim-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az2-isim-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 4. Əlamət bildirən sözlər (sifət) ═══════════════
    {
      id: "az2-sifet",
      title: "Əlamət bildirən sözlər",
      description: "Əşyanın əlamətini bildirən, 'necə?', 'nə cür?' suallarına cavab verən sözlər.",
      lessons: [
        {
          id: "az2-sifet-l1",
          title: "Əlamət bildirən sözlər",
          intro: "Əşyanın rəngini, ölçüsünü, keyfiyyətini bildirən sözlər.",
          sections: [
            { heading: "Əlamət", body: "Əşyanın əlamətini (rəng, ölçü, keyfiyyət) bildirən, 'necə?', 'nə cür?' suallarına cavab verən sözlər: qırmızı, böyük, gözəl, isti, təmiz." },
          ],
          tasks: [
            { id: "az2-sifet-l1-t1", type: "multiple_choice", prompt: "Aşağıdakılardan hansı əlamət bildirir?", options: ["gözəl", "kitab", "oxumaq", "uşaq"], correctIndex: 0, xp: 10, explanation: "«Gözəl» əşyanın necə olduğunu bildirir. Kitab və uşaq ad, oxumaq isə hərəkətdir.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l1-t2", type: "multiple_choice", prompt: "Aşağıdakılardan hansı əlamət bildirir?", options: ["böyük", "ev", "getmək", "ana"], correctIndex: 0, xp: 10, explanation: "«Böyük» əşyanın ölçüsünü, yəni əlamətini bildirir. Ana və ev ad, getmək isə hərəkətdir.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l1-t3", type: "multiple_choice", prompt: "Əlamət bildirən sözlər hansı suala cavab verir?", options: ["necə? nə cür?", "kim? nə?", "nə edir?", "neçə?"], correctIndex: 0, xp: 10, explanation: "Əlamət əşyanın necə olduğunu göstərir, ona görə «necə? nə cür?» suallarına cavab verir.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l1-t4", type: "multiple_choice", prompt: "'qırmızı' sözü nəyi bildirir?", options: ["rəngi (əlamət)", "əşyanı", "hərəkəti", "sayı"], correctIndex: 0, xp: 10, explanation: "Rəng əşyanın necə göründüyünü bildirir, yəni onun əlamətidir.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l1-t5", type: "multiple_choice", prompt: "'Gözəl gül' — 'gözəl' sözü nəyi bildirir?", options: ["əlaməti", "əşyanı", "hərəkəti", "sayı"], correctIndex: 0, xp: 10, explanation: "«Gözəl» sözü gülün necə olduğunu göstərir — deməli əlamət bildirir.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l1-t6", type: "multiple_choice", prompt: "Aşağıdakılardan hansı əlamət bildirir?", options: ["isti", "su", "içmək", "yay"], correctIndex: 0, xp: 10, explanation: "«İsti» əlamət bildirir. Su və yay ad, içmək isə hərəkətdir.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l1-t7", type: "multiple_choice", prompt: "'böyük ev' — hansı söz əlamət bildirir?", options: ["böyük", "ev", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Ev» əşyanın adıdır, «böyük» isə onun necə olduğunu göstərir.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l1-t8", type: "multiple_choice", prompt: "Aşağıdakılardan hansı əlamət bildirir?", options: ["təmiz", "otaq", "yumaq", "sabah"], correctIndex: 0, xp: 10, explanation: "«Təmiz» əlamət bildirir. Otaq ad, yumaq hərəkət, sabah isə vaxt bildirir.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l1-t9", type: "multiple_choice", prompt: "'soyuq su' — hansı söz əlamət bildirir?", options: ["soyuq", "su", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Su» əşyanın adıdır, «soyuq» isə onun necə olduğunu göstərir.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l1-t10", type: "multiple_choice", prompt: "Aşağıdakılardan hansı əlamət bildirir?", options: ["yaşıl", "yarpaq", "düşmək", "payız"], correctIndex: 0, xp: 10, explanation: "«Yaşıl» rəng, yəni əlamət bildirir. Yarpaq və payız ad, düşmək isə hərəkətdir.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l1-t11", type: "multiple_choice", prompt: "'ağ qar' — hansı söz əlamət bildirir?", options: ["ağ", "qar", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Qar» əşyanın adıdır, «ağ» isə onun rəngini, yəni əlamətini bildirir.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l1-t12", type: "multiple_choice", prompt: "'yüksək dağ' — hansı söz əlamət bildirir?", options: ["yüksək", "dağ", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Dağ» əşyanın adıdır, «yüksək» isə onun necə olduğunu göstərir.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l1-t13", type: "multiple_choice", prompt: "Aşağıdakılardan hansı əlamət DEYİL?", options: ["kitab", "maraqlı", "qalın", "yeni"], correctIndex: 0, xp: 10, explanation: "Qalın, maraqlı və yeni əlamət bildirir. «Kitab» isə əşyanın öz adıdır.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l1-t14", type: "multiple_choice", prompt: "'şirin alma' — hansı söz əlamət bildirir?", options: ["şirin", "alma", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Alma» əşyanın adıdır, «şirin» isə onun dadını, yəni əlamətini bildirir.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l1-t15", type: "multiple_choice", prompt: "'kiçik' sözünün əksi (antonim) hansıdır?", options: ["böyük", "gözəl", "ağ", "isti"], correctIndex: 0, xp: 15, explanation: "Kiçik az yer tutan, böyük isə çox yer tutan deməkdir — bunlar bir-birinin əksidir.", skills: ["az.lex.antonym"] },
          ],
          bonusTasks: [
            { id: "az2-sifet-l1-b1", type: "multiple_choice", prompt: "'Uzun, qara saç' — neçə əlamət bildirən söz var?", options: ["2 (uzun, qara)", "1", "3", "0"], correctIndex: 0, xp: 15, explanation: "Saçın necə olduğunu iki söz göstərir: «uzun» (uzunluğu) və «qara» (rəngi).", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l1-b2", type: "multiple_choice", prompt: "'isti' sözünün əksi hansıdır?", options: ["soyuq", "böyük", "təmiz", "yeni"], correctIndex: 0, xp: 15, explanation: "İsti yüksək, soyuq isə aşağı istilik bildirir — bunlar bir-birinin əksidir.", skills: ["az.lex.antonym"] },
            { id: "az2-sifet-l1-b3", type: "multiple_choice", prompt: "'təmiz' sözünün əksi hansıdır?", options: ["çirkli", "böyük", "isti", "gözəl"], correctIndex: 0, xp: 15, explanation: "Təmizin əksi çirklidir — biri kirin olmamasını, digəri olmasını bildirir.", skills: ["az.lex.antonym"] },
            { id: "az2-sifet-l1-b4", type: "multiple_choice", prompt: "Əlamət bildirən söz hansı sözü izah edir?", options: ["əşya adını", "hərəkəti", "sayı", "yeri"], correctIndex: 0, xp: 15, explanation: "Əlamət bildirən söz əşyanın necə olduğunu göstərir, ona görə əşya adının yanında işlənir.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l1-b5", type: "multiple_choice", prompt: "'yeni' sözünün əksi hansıdır?", options: ["köhnə", "böyük", "isti", "ağ"], correctIndex: 0, xp: 15, explanation: "Yeni indi alınmış, köhnə isə çoxdan işlənmiş deməkdir — bunlar bir-birinin əksidir.", skills: ["az.lex.antonym"] },
          ],
        },
        {
          id: "az2-sifet-l2",
          title: "Sifət ismi necə tamamlayır",
          intro: "Sifət həmişə ismin yanında durur və onu izah edir.",
          sections: [
            { heading: "Yerləşmə", body: "Azərbaycan dilində sifət ismin ÖNÜNDƏ gəlir: qırmızı alma, böyük ev, isti çay." },
            { heading: "Sual", body: "Sifət 'necə?', 'hansı?' suallarına cavab verir. 'Qırmızı alma' — alma NECƏ? Qırmızı." },
          ],
          tasks: [
            { id: "az2-sifet-l2-t1", type: "multiple_choice", prompt: "'Qırmızı alma' — burada sifət hansıdır?", options: ["qırmızı", "alma", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Alma» əşyanın adıdır, «qırmızı» isə onun rəngini bildirir — deməli sifət odur.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l2-t2", type: "multiple_choice", prompt: "Sifət hansı suala cavab verir?", options: ["Necə?", "Nə edir?", "Harada?", "Nə vaxt?"], correctIndex: 0, xp: 10, explanation: "Sifət əşyanın necə olduğunu göstərir, ona görə «Necə?» sualına cavab verir.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l2-t3", type: "multiple_choice", prompt: "Sifət ismin harasında durur?", options: ["Önündə", "Arxasında", "Ortasında", "Fərqi yoxdur"], correctIndex: 0, xp: 10, explanation: "Azərbaycan dilində sifət təyin etdiyi ismin önündə durur: «böyük ev», «qırmızı alma».", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l2-t4", type: "multiple_choice", prompt: "'Böyük ev' — burada isim hansıdır?", options: ["ev", "böyük", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Ev» əşyanın adıdır, yəni isimdir. «Böyük» isə onun əlamətidir.", skills: ["az.pos.noun"] },
            { id: "az2-sifet-l2-t5", type: "multiple_choice", prompt: "Hansı söz sifətdir?", options: ["şirin", "şəkər", "yemək", "içmək"], correctIndex: 0, xp: 10, explanation: "«Şirin» dadı bildirir, yəni sifətdir. Şəkər isim, yemək və içmək isə hərəkətdir.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l2-t6", type: "multiple_choice", prompt: "Hansı söz sifətdir?", options: ["soyuq", "su", "içmək", "stəkan"], correctIndex: 0, xp: 10, explanation: "«Soyuq» əlamət bildirir, yəni sifətdir. Su və stəkan isim, içmək isə hərəkətdir.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l2-t7", type: "fill_blank", prompt: "'İsti çay' ifadəsində sifət ______ sözüdür.", accepted: ["isti", "İsti"], xp: 10, explanation: "Çayın necə olduğunu «isti» sözü göstərir — deməli sifət odur.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l2-t8", type: "multiple_choice", prompt: "'Hündür ağac' — ağac necədir?", options: ["Hündür", "Ağac", "Yaşıl", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "İfadədə ağacın əlamətini «hündür» sözü bildirir.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l2-t9", type: "multiple_choice", prompt: "Hansı ifadədə sifət var?", options: ["yeni kitab", "kitab oxumaq", "kitabxana", "kitabı"], correctIndex: 0, xp: 10, explanation: "«Yeni kitab» ifadəsində kitabın necə olduğu göstərilir. Digərlərində sifət yoxdur.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l2-t10", type: "multiple_choice", prompt: "Hansı söz sifət DEYİL?", options: ["qaçmaq", "gözəl", "kiçik", "ağ"], correctIndex: 0, xp: 10, explanation: "Kiçik, gözəl və ağ əlamət bildirir. «Qaçmaq» isə hərəkətdir.", skills: ["az.pos.adjective"] },
          ],
          bonusTasks: [
            { id: "az2-sifet-l2-b1", type: "multiple_choice", prompt: "Bir ismin yanında neçə sifət ola bilər?", options: ["Bir neçə: 'böyük qırmızı alma'", "Yalnız bir", "Heç biri", "İkidən çox olmaz"], correctIndex: 0, xp: 15, explanation: "Bir əşyanın eyni anda bir neçə əlaməti ola bilər — ölçüsü, rəngi, dadı: «böyük qırmızı alma».", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l2-b2", type: "multiple_choice", prompt: "'Aysel çalışqandır' — burada sifət hansıdır?", options: ["çalışqan", "Aysel", "dır", "heç biri"], correctIndex: 0, xp: 15, explanation: "Cümlədə Ayselin necə olduğunu «çalışqan» sözü bildirir — deməli sifət odur.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l2-b3", type: "multiple_choice", prompt: "Rəng bildirən sözlər hansı qrupa aiddir?", options: ["Sifət", "İsim", "Feil", "Say"], correctIndex: 0, xp: 15, explanation: "Rəng əşyanın necə göründüyünü bildirir, bu isə sifətin vəzifəsidir.", skills: ["az.pos.adjective"] },
            { id: "az2-sifet-l2-b4", type: "multiple_choice", prompt: "'Sürətli qatar' ifadəsinin əksi hansıdır?", options: ["Yavaş qatar", "Böyük qatar", "Yeni qatar", "Uzun qatar"], correctIndex: 0, xp: 15, explanation: "Sifəti öz əksi ilə əvəz edirik: sürətlinin əksi yavaşdır.", skills: ["az.lex.antonym"] },
          ],
        },
        {
          id: "az2-sifet-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az2-sifet-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 5. Hərəkət bildirən sözlər (feil) ═══════════════
    {
      id: "az2-feil",
      title: "Hərəkət bildirən sözlər",
      description: "Hərəkəti bildirən, 'nə edir?', 'nə etdi?' suallarına cavab verən sözlər.",
      lessons: [
        {
          id: "az2-feil-l1",
          title: "Hərəkət bildirən sözlər",
          intro: "İşi, hərəkəti bildirən sözlər.",
          sections: [
            { heading: "Hərəkət", body: "İşi, hərəkəti bildirən, 'nə edir?', 'nə etdi?', 'nə edəcək?' suallarına cavab verən sözlər (feil): oxuyur, gəldi, qaçır, yazacaq." },
          ],
          tasks: [
            { id: "az2-feil-l1-t1", type: "multiple_choice", prompt: "Aşağıdakılardan hansı hərəkət bildirir?", options: ["oxuyur", "kitab", "gözəl", "uşaq"], correctIndex: 0, xp: 10, explanation: "«Oxuyur» iş, hərəkət bildirir. Uşaq və kitab ad, gözəl isə əlamətdir.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l1-t2", type: "multiple_choice", prompt: "Aşağıdakılardan hansı hərəkət bildirir?", options: ["qaçır", "ev", "böyük", "ana"], correctIndex: 0, xp: 10, explanation: "«Qaçır» hərəkət bildirir. Ev və ana ad, böyük isə əlamətdir.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l1-t3", type: "multiple_choice", prompt: "Hərəkət bildirən sözlər hansı suala cavab verir?", options: ["nə edir?", "kim? nə?", "necə?", "neçə?"], correctIndex: 0, xp: 10, explanation: "Hərəkət işin görülməsini bildirir, ona görə «nə edir?» sualına cavab verir.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l1-t4", type: "multiple_choice", prompt: "'gəldi' sözü hansı suala cavab verir?", options: ["nə etdi?", "kim?", "necə?", "nə?"], correctIndex: 0, xp: 10, explanation: "«Gəldi» iş artıq baş verib bitib — ona görə «nə etdi?» sualına cavab verir.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l1-t5", type: "multiple_choice", prompt: "'Uşaq oynayır.' — hansı söz hərəkət bildirir?", options: ["oynayır", "uşaq", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Uşaq» işi görəndir, «oynayır» isə onun gördüyü işdir.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l1-t6", type: "multiple_choice", prompt: "Aşağıdakılardan hansı hərəkət bildirir?", options: ["yazır", "dəftər", "təmiz", "sabah"], correctIndex: 0, xp: 10, explanation: "«Yazır» hərəkət bildirir. Dəftər ad, təmiz əlamət, sabah isə vaxt bildirir.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l1-t7", type: "multiple_choice", prompt: "Aşağıdakılardan hansı hərəkət DEYİL?", options: ["kitab", "gəlir", "oxudu", "yazacaq"], correctIndex: 0, xp: 10, explanation: "Gəlir, oxudu, yazacaq — üçü də iş bildirir. «Kitab» isə əşyanın adıdır.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l1-t8", type: "multiple_choice", prompt: "'Quş uçur.' — hansı söz hərəkət bildirir?", options: ["uçur", "quş", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Quş» işi görəndir, «uçur» isə onun gördüyü işdir.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l1-t9", type: "multiple_choice", prompt: "Aşağıdakılardan hansı hərəkət bildirir?", options: ["gülür", "gül", "gözəl", "bağ"], correctIndex: 0, xp: 10, explanation: "«Gülür» hərəkət bildirir. Gül və bağ ad, gözəl isə əlamətdir.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l1-t10", type: "multiple_choice", prompt: "'içdi' sözü hansı zamana aiddir?", options: ["keçmiş", "indiki", "gələcək", "heç biri"], correctIndex: 0, xp: 10, explanation: "«İçdi» sözündə -di şəkilçisi var və iş artıq bitib — deməli keçmiş zamandır.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l1-t11", type: "multiple_choice", prompt: "'gedəcək' sözü hansı zamana aiddir?", options: ["gələcək", "keçmiş", "indiki", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Gedəcək» sözündə -əcək şəkilçisi var və iş hələ baş verməyib — deməli gələcək zamandır.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l1-t12", type: "multiple_choice", prompt: "'oxuyur' sözü hansı zamana aiddir?", options: ["indiki", "keçmiş", "gələcək", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Oxuyur» sözündə -ur şəkilçisi var və iş elə indi davam edir — deməli indiki zamandır.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l1-t13", type: "multiple_choice", prompt: "'Ana çörək bişirir.' — hansı söz hərəkət bildirir?", options: ["bişirir", "ana", "çörək", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Ana» işi görəndir, «çörək» əşyadır, «bişirir» isə görülən işdir.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l1-t14", type: "multiple_choice", prompt: "Aşağıdakılardan hansı hərəkət bildirir?", options: ["danışır", "söz", "hündür", "dünən"], correctIndex: 0, xp: 10, explanation: "«Danışır» hərəkət bildirir. Söz ad, hündür əlamət, dünən isə vaxt bildirir.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l1-t15", type: "multiple_choice", prompt: "'yatdı' sözü hansı suala cavab verir?", options: ["nə etdi?", "kim?", "necə?", "nə?"], correctIndex: 0, xp: 15, explanation: "«Yatdı» işi artıq bitmiş kimi bildirir — ona görə «nə etdi?» sualına cavab verir.", skills: ["az.pos.verb"] },
          ],
          bonusTasks: [
            { id: "az2-feil-l1-b1", type: "multiple_choice", prompt: "'Balaca uşaq şən oynayır.' — hərəkət bildirən söz hansıdır?", options: ["oynayır", "balaca", "uşaq", "şən"], correctIndex: 0, xp: 15, explanation: "Cümlədə «balaca» və «şən» əlamət, «uşaq» ad, «oynayır» isə hərəkət bildirir.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l1-b2", type: "multiple_choice", prompt: "Bir cümlədə əşya adı, əlamət və hərəkət ola bilər. 'Ağ pişik yatır.' — hərəkət hansıdır?", options: ["yatır", "ağ", "pişik", "heç biri"], correctIndex: 0, xp: 15, explanation: "Cümlədə «ağ» əlamət, «pişik» ad, «yatır» isə hərəkət bildirir.", skills: ["az.syn.sentence"] },
            { id: "az2-feil-l1-b3", type: "multiple_choice", prompt: "Aşağıdakı sıradan hərəkət bildirən sözü seç.", options: ["gülümsəyir", "gülüş", "gülməli", "gül"], correctIndex: 0, xp: 15, explanation: "«Gülümsəyir» iş bildirir. Gül ad, gülüş ad, gülməli isə əlamətdir.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l1-b4", type: "multiple_choice", prompt: "'gəldi', 'gəlir', 'gələcək' — bunlar nəyi bildirir?", options: ["hərəkəti (feil)", "əşyanı", "əlaməti", "sayı"], correctIndex: 0, xp: 15, explanation: "Üç sözün də kökü eynidir və iş bildirir; yalnız zamanları fərqlidir — keçmiş, indiki, gələcək.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l1-b5", type: "multiple_choice", prompt: "'Mən məktəbə gedirəm.' — hərəkət bildirən söz hansıdır?", options: ["gedirəm", "mən", "məktəbə", "heç biri"], correctIndex: 0, xp: 15, explanation: "Cümlədə «mən» işi görən, «məktəbə» yer, «gedirəm» isə görülən işdir.", skills: ["az.pos.verb"] },
          ],
        },
        {
          id: "az2-feil-l2",
          title: "Zaman: indi, keçmiş, gələcək",
          intro: "Feil işin nə vaxt olduğunu göstərir.",
          sections: [
            { heading: "Üç zaman", body: "KEÇMİŞ: oxudum. İNDİKİ: oxuyuram. GƏLƏCƏK: oxuyacağam." },
            { heading: "Necə tanıyaq?", body: "Feilin sonundakı şəkilçi zamanı bildirir: -dı/-di keçmiş, -ır/-ir indiki, -acaq/-əcək gələcək zamandır." },
          ],
          tasks: [
            { id: "az2-feil-l2-t1", type: "multiple_choice", prompt: "'oxudum' hansı zamandadır?", options: ["Keçmiş", "İndiki", "Gələcək", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "«Oxudum» sözündə -du şəkilçisi var və iş bitib — deməli keçmiş zamandır.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l2-t2", type: "multiple_choice", prompt: "'oxuyuram' hansı zamandadır?", options: ["İndiki", "Keçmiş", "Gələcək", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "«Oxuyuram» sözündə -yur şəkilçisi var və iş indi davam edir — deməli indiki zamandır.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l2-t3", type: "multiple_choice", prompt: "'oxuyacağam' hansı zamandadır?", options: ["Gələcək", "Keçmiş", "İndiki", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "«Oxuyacağam» sözündə -acaq şəkilçisi var və iş hələ olmayıb — deməli gələcək zamandır.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l2-t4", type: "multiple_choice", prompt: "'getdi' hansı zamandadır?", options: ["Keçmiş", "İndiki", "Gələcək", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "«Getdi» sözündə -di şəkilçisi var və iş bitib — deməli keçmiş zamandır.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l2-t5", type: "multiple_choice", prompt: "'gəlirəm' hansı zamandadır?", options: ["İndiki", "Keçmiş", "Gələcək", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "«Gəlirəm» sözündə -ir şəkilçisi var və iş indi davam edir — deməli indiki zamandır.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l2-t6", type: "multiple_choice", prompt: "'yazacaq' hansı zamandadır?", options: ["Gələcək", "Keçmiş", "İndiki", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "«Yazacaq» sözündə -acaq şəkilçisi var və iş hələ olmayıb — deməli gələcək zamandır.", skills: ["az.pos.verb"] },
            { id: "az2-feil-l2-t7", type: "multiple_choice", prompt: "Keçmiş zamanın şəkilçisi hansıdır?", options: ["-dı / -di", "-ır / -ir", "-acaq / -əcək", "-lar / -lər"], correctIndex: 0, xp: 10, explanation: "Keçmiş zaman -dı, -di, -du, -dü şəkilçisi ilə düzəlir: getdi, oxudu, gördü.", skills: ["az.morph.root"] },
            { id: "az2-feil-l2-t8", type: "fill_blank", prompt: "'Sabah məktəbə ______.' — gələcək zamanda hansı feil uyğundur? (gedəcəyəm)", accepted: ["gedəcəyəm", "Gedəcəyəm", "gedecem"], xp: 10, explanation: "«Sabah» sözü işin hələ olmadığını göstərir, ona görə feil gələcək zamanda olmalıdır: gedəcəyəm.", skills: ["az.pos.verb_tense"] },
            { id: "az2-feil-l2-t9", type: "multiple_choice", prompt: "'Dünən kitab oxudum' cümləsi hansı zamandadır?", options: ["Keçmiş", "İndiki", "Gələcək", "Zamansız"], correctIndex: 0, xp: 10, explanation: "«Dünən» sözü və «oxudum» feilindəki -du şəkilçisi işin artıq bitdiyini göstərir.", skills: ["az.syn.sentence"] },
            { id: "az2-feil-l2-t10", type: "multiple_choice", prompt: "Feil hansı suala cavab verir?", options: ["Nə edir?", "Necə?", "Hansı?", "Neçə?"], correctIndex: 0, xp: 10, explanation: "Feil işin görülməsini bildirir, ona görə «Nə edir?» sualına cavab verir.", skills: ["az.pos.verb"] },
          ],
          bonusTasks: [
            { id: "az2-feil-l2-b1", type: "multiple_choice", prompt: "'İndi yeyirəm' cümləsini keçmiş zamana çevir.", options: ["İndi yedim", "İndi yeyəcəyəm", "İndi yeyirəm", "İndi yeyərəm"], correctIndex: 0, xp: 15, explanation: "İndiki zaman şəkilçisini keçmiş zaman şəkilçisi ilə əvəz edirik: yeyirəm → yedim.", skills: ["az.syn.sentence"] },
            { id: "az2-feil-l2-b2", type: "multiple_choice", prompt: "Hansı cümlə gələcək zamandadır?", options: ["Sabah gələcəyəm.", "Dünən gəldim.", "İndi gəlirəm.", "Həmişə gəlirəm."], correctIndex: 0, xp: 15, explanation: "«Sabah» sözü və -əcək şəkilçisi işin hələ baş vermədiyini göstərir. Digər cümlələr keçmiş və indiki zamandadır.", skills: ["az.syn.sentence"] },
            { id: "az2-feil-l2-b3", type: "multiple_choice", prompt: "'Qaçdı' feilində zaman şəkilçisi hansıdır?", options: ["-dı", "-qaç", "-ır", "-acaq"], correctIndex: 0, xp: 15, explanation: "Sözü hissələrə ayırırıq: qaç (kök) + dı (zaman şəkilçisi). Deməli zaman şəkilçisi -dı-dır.", skills: ["az.morph.root","az.pos.verb_tense"] },
            { id: "az2-feil-l2-b4", type: "multiple_choice", prompt: "Bir cümlədə zaman nə üçün vacibdir?", options: ["İşin nə vaxt olduğunu bildirir", "Cümləni uzadır", "Sifət düzəldir", "Heç nə üçün"], correctIndex: 0, xp: 15, explanation: "Zaman olmasa, işin dünən, indi, yoxsa sabah olduğunu bilmərik — cümlənin mənası dolaşıq qalar.", skills: ["az.syn.sentence"] },
          ],
        },
        {
          id: "az2-feil-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az2-feil-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 6. Sözün mənası və orfoqrafiya ═══════════════
    {
      id: "az2-mena",
      title: "Sözün mənası və orfoqrafiya",
      description: "Sinonim, antonim və düzgün yazılış qaydaları.",
      lessons: [
        {
          id: "az2-mena-l1",
          title: "Yaxın və əks mənalı sözlər",
          intro: "Sinonim (yaxın məna) və antonim (əks məna) sözləri.",
          sections: [
            { heading: "Yaxın mənalı (sinonim)", body: "Mənası yaxın olan sözlər: gözəl — qəşəng, böyük — iri, şən — sevincli." },
            { heading: "Əks mənalı (antonim)", body: "Mənası əks olan sözlər: böyük — kiçik, isti — soyuq, gecə — gündüz, yaxşı — pis." },
          ],
          tasks: [
            { id: "az2-mena-l1-t1", type: "multiple_choice", prompt: "'böyük' sözünün əksi hansıdır?", options: ["kiçik", "iri", "gözəl", "uzun"], correctIndex: 0, xp: 10, explanation: "Böyük çox, kiçik isə az yer tutan deməkdir — bunlar bir-birinin əksidir. İri və nəhəng isə böyüyə yaxın mənalıdır.", skills: ["az.lex.antonym"] },
            { id: "az2-mena-l1-t2", type: "multiple_choice", prompt: "'isti' sözünün əksi hansıdır?", options: ["soyuq", "təmiz", "yeni", "böyük"], correctIndex: 0, xp: 10, explanation: "İsti yüksək, soyuq isə aşağı istilik bildirir — bunlar bir-birinin əksidir.", skills: ["az.lex.antonym"] },
            { id: "az2-mena-l1-t3", type: "multiple_choice", prompt: "'gecə' sözünün əksi hansıdır?", options: ["gündüz", "səhər", "axşam", "gün"], correctIndex: 0, xp: 10, explanation: "Gecə qaranlıq, gündüz isə işıqlı vaxtdır — bunlar bir-birinin əksidir.", skills: ["az.lex.antonym"] },
            { id: "az2-mena-l1-t4", type: "multiple_choice", prompt: "'yaxşı' sözünün əksi hansıdır?", options: ["pis", "gözəl", "böyük", "təmiz"], correctIndex: 0, xp: 10, explanation: "Yaxşı müsbət, pis isə mənfi qiymət bildirir — bunlar bir-birinin əksidir.", skills: ["az.lex.antonym"] },
            { id: "az2-mena-l1-t5", type: "multiple_choice", prompt: "'gözəl' sözünün yaxın mənalısı hansıdır?", options: ["qəşəng", "kiçik", "soyuq", "pis"], correctIndex: 0, xp: 10, explanation: "«Qəşəng» də gözəllik bildirir, yəni mənaca gözələ yaxındır. Pis və kiçik isə fərqli mənalıdır.", skills: ["az.lex.synonym"] },
            { id: "az2-mena-l1-t6", type: "multiple_choice", prompt: "'böyük' sözünün yaxın mənalısı hansıdır?", options: ["iri", "kiçik", "gözəl", "soyuq"], correctIndex: 0, xp: 10, explanation: "«İri» də böyüklük bildirir, yəni mənaca böyüyə yaxındır. Kiçik isə onun əksidir.", skills: ["az.lex.synonym"] },
            { id: "az2-mena-l1-t7", type: "multiple_choice", prompt: "'uzun' sözünün əksi hansıdır?", options: ["qısa", "geniş", "böyük", "hündür"], correctIndex: 0, xp: 10, explanation: "Uzun çox, qısa isə az uzunluq bildirir — bunlar bir-birinin əksidir.", skills: ["az.lex.antonym"] },
            { id: "az2-mena-l1-t8", type: "multiple_choice", prompt: "'açıq' sözünün əksi hansıdır?", options: ["bağlı", "böyük", "təmiz", "isti"], correctIndex: 0, xp: 10, explanation: "Açıq girişin sərbəst, bağlı isə qapalı olmasını bildirir — bunlar bir-birinin əksidir.", skills: ["az.lex.antonym"] },
            { id: "az2-mena-l1-t9", type: "multiple_choice", prompt: "'sevincli' sözünün yaxın mənalısı hansıdır?", options: ["şən", "kədərli", "böyük", "soyuq"], correctIndex: 0, xp: 10, explanation: "«Şən» də sevinc bildirir, yəni mənaca sevincliyə yaxındır. Kədərli isə onun əksidir.", skills: ["az.lex.synonym"] },
            { id: "az2-mena-l1-t10", type: "multiple_choice", prompt: "'aşağı' sözünün əksi hansıdır?", options: ["yuxarı", "sağ", "sol", "irəli"], correctIndex: 0, xp: 10, explanation: "Aşağı və yuxarı əks istiqamətləri bildirir.", skills: ["az.lex.antonym"] },
            { id: "az2-mena-l1-t11", type: "multiple_choice", prompt: "'tez' sözünün əksi hansıdır?", options: ["gec", "yavaş", "böyük", "uzaq"], correctIndex: 0, xp: 10, explanation: "Tez vaxtından əvvəl, gec isə vaxtından sonra deməkdir — bunlar bir-birinin əksidir.", skills: ["az.lex.antonym"] },
            { id: "az2-mena-l1-t12", type: "multiple_choice", prompt: "Mənası yaxın olan sözlərə nə deyilir?", options: ["sinonim (yaxın mənalı)", "antonim (əks mənalı)", "isim", "feil"], correctIndex: 0, xp: 10, explanation: "Mənaca yaxın sözlərə sinonim deyilir: gözəl — qəşəng.", skills: ["az.lex.meaning"] },
            { id: "az2-mena-l1-t13", type: "multiple_choice", prompt: "Mənası əks olan sözlərə nə deyilir?", options: ["antonim (əks mənalı)", "sinonim (yaxın mənalı)", "isim", "sifət"], correctIndex: 0, xp: 10, explanation: "Mənaca əks sözlərə antonim deyilir: isti — soyuq.", skills: ["az.lex.meaning"] },
            { id: "az2-mena-l1-t14", type: "multiple_choice", prompt: "'ağ' sözünün əksi hansıdır?", options: ["qara", "qırmızı", "mavi", "yaşıl"], correctIndex: 0, xp: 10, explanation: "Ağ ən açıq, qara isə ən tünd rəngdir — bunlar bir-birinin əksidir.", skills: ["az.lex.antonym"] },
            { id: "az2-mena-l1-t15", type: "multiple_choice", prompt: "'uzaq' sözünün əksi hansıdır?", options: ["yaxın", "böyük", "hündür", "geniş"], correctIndex: 0, xp: 15, explanation: "Uzaq böyük məsafə, yaxın isə kiçik məsafə bildirir — bunlar bir-birinin əksidir.", skills: ["az.lex.antonym"] },
          ],
          bonusTasks: [
            { id: "az2-mena-l1-b1", type: "multiple_choice", prompt: "Cümlə həmişə hansı hərflə başlayır?", options: ["böyük hərflə", "kiçik hərflə", "saitlə", "samitlə"], correctIndex: 0, xp: 15, explanation: "Cümlənin harada başladığı bilinsin deyə ilk hərf böyük yazılır.", skills: ["az.phon.letters"] },
            { id: "az2-mena-l1-b2", type: "multiple_choice", prompt: "İnsan adları, şəhər adları necə yazılır?", options: ["böyük hərflə", "kiçik hərflə", "rəqəmlə", "fərq etməz"], correctIndex: 0, xp: 15, explanation: "İnsan və şəhər adları xüsusi addır, ona görə böyük hərflə yazılır.", skills: ["az.lex.meaning"] },
            { id: "az2-mena-l1-b3", type: "multiple_choice", prompt: "'dost' sözünün əksi hansıdır?", options: ["düşmən", "yoldaş", "qonşu", "qardaş"], correctIndex: 0, xp: 15, explanation: "Dost yaxşılıq istəyən, düşmən isə pislik istəyən deməkdir — bunlar bir-birinin əksidir. Yoldaş və qardaş isə dosta yaxın mənalıdır.", skills: ["az.lex.antonym"] },
            { id: "az2-mena-l1-b4", type: "multiple_choice", prompt: "'çətin' sözünün əksi hansıdır?", options: ["asan", "böyük", "uzun", "isti"], correctIndex: 0, xp: 15, explanation: "Çətin çox zəhmət tələb edən, asan isə az zəhmət tələb edən deməkdir — bunlar bir-birinin əksidir.", skills: ["az.lex.antonym"] },
            { id: "az2-mena-l1-b5", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["Nərmin məktəbə getdi.", "nərmin məktəbə getdi.", "Nərmin Məktəbə getdi.", "nərmin Məktəbə Getdi."], correctIndex: 0, xp: 15, explanation: "«Nərmin məktəbə getdi.» — ad və cümlənin əvvəli böyük, qalan sözlər kiçik yazılıb.", skills: ["az.orth.spelling"] },
          ],
        },
        {
          id: "az2-mena-l2",
          title: "Yaxın və əks mənalı sözlər",
          intro: "Bəzi sözlər eyni, bəziləri əks məna daşıyır.",
          sections: [
            { heading: "Yaxın mənalı", body: "Mənası bir-birinə yaxın olan sözlər: gözəl — qəşəng, böyük — iri, sürətli — cəld." },
            { heading: "Əks mənalı", body: "Mənası bir-birinin əksi olan sözlər: böyük — kiçik, isti — soyuq, gündüz — gecə." },
          ],
          tasks: [
            { id: "az2-mena-l2-t1", type: "multiple_choice", prompt: "'böyük' sözünün əksi hansıdır?", options: ["kiçik", "iri", "nəhəng", "geniş"], correctIndex: 0, xp: 10, explanation: "Böyüyün əksi kiçikdir. Geniş, iri və nəhəng isə böyüyə yaxın mənalıdır.", skills: ["az.lex.antonym"] },
            { id: "az2-mena-l2-t2", type: "multiple_choice", prompt: "'isti' sözünün əksi hansıdır?", options: ["soyuq", "ilıq", "qaynar", "yay"], correctIndex: 0, xp: 10, explanation: "İstinin əksi soyuqdur. Qaynar və ilıq isə istiliyin dərəcələridir.", skills: ["az.lex.antonym"] },
            { id: "az2-mena-l2-t3", type: "multiple_choice", prompt: "'gündüz' sözünün əksi hansıdır?", options: ["gecə", "səhər", "axşam", "günorta"], correctIndex: 0, xp: 10, explanation: "Gündüz işıqlı, gecə isə qaranlıq vaxtdır — bunlar bir-birinin əksidir.", skills: ["az.lex.antonym"] },
            { id: "az2-mena-l2-t4", type: "multiple_choice", prompt: "'gözəl' sözünə mənaca yaxın hansıdır?", options: ["qəşəng", "çirkin", "balaca", "uzun"], correctIndex: 0, xp: 10, explanation: "«Qəşəng» də gözəllik bildirir — deməli mənaca yaxındır. Çirkin isə əks mənalıdır.", skills: ["az.lex.meaning"] },
            { id: "az2-mena-l2-t5", type: "multiple_choice", prompt: "'uzun' sözünün əksi hansıdır?", options: ["qısa", "hündür", "geniş", "böyük"], correctIndex: 0, xp: 10, explanation: "Uzunun əksi qısadır. Hündür və geniş isə başqa ölçüləri bildirir.", skills: ["az.lex.antonym"] },
            { id: "az2-mena-l2-t6", type: "multiple_choice", prompt: "'açıq' sözünün əksi hansıdır?", options: ["bağlı", "geniş", "işıqlı", "təmiz"], correctIndex: 0, xp: 10, explanation: "Açığın əksi bağlıdır — biri girişin sərbəst, digəri qapalı olmasını bildirir.", skills: ["az.lex.antonym"] },
            { id: "az2-mena-l2-t7", type: "multiple_choice", prompt: "'sürətli' sözünə yaxın hansıdır?", options: ["cəld", "yavaş", "ağır", "sakit"], correctIndex: 0, xp: 10, explanation: "«Cəld» də sürət bildirir, yəni mənaca sürətliyə yaxındır. Yavaş və ağır isə əks mənalıdır.", skills: ["az.lex.meaning"] },
            { id: "az2-mena-l2-t8", type: "fill_blank", prompt: "'yaxşı' sözünün əksi ______-dır. (bir söz)", accepted: ["pis", "Pis"], xp: 10, explanation: "Yaxşı müsbət, pis isə mənfi qiymət bildirir — bunlar bir-birinin əksidir.", skills: ["az.lex.antonym"] },
            { id: "az2-mena-l2-t9", type: "multiple_choice", prompt: "'təmiz' sözünün əksi hansıdır?", options: ["çirkli", "səliqəli", "ağ", "yeni"], correctIndex: 0, xp: 10, explanation: "Təmizin əksi çirklidir. Səliqəli isə təmizə yaxın mənalıdır.", skills: ["az.lex.antonym"] },
            { id: "az2-mena-l2-t10", type: "multiple_choice", prompt: "'çətin' sözünün əksi hansıdır?", options: ["asan", "ağır", "uzun", "dar"], correctIndex: 0, xp: 10, explanation: "Çətinin əksi asandır. Ağır və dar isə başqa əlamətləri bildirir.", skills: ["az.lex.antonym"] },
          ],
          bonusTasks: [
            { id: "az2-mena-l2-b1", type: "multiple_choice", prompt: "Hansı cütlük ƏKS mənalıdır?", options: ["gec — tez", "sevinc — şadlıq", "böyük — iri", "qəşəng — gözəl"], correctIndex: 0, xp: 15, explanation: "Gec və tez əks vaxtı bildirir. Digər cütlüklərdə sözlər mənaca yaxındır.", skills: ["az.lex.antonym"] },
            { id: "az2-mena-l2-b2", type: "multiple_choice", prompt: "Hansı cütlük YAXIN mənalıdır?", options: ["cəsur — igid", "ağ — qara", "gəl — get", "az — çox"], correctIndex: 0, xp: 15, explanation: "Cəsur və igid eyni keyfiyyəti — qorxmazlığı bildirir. Digər cütlüklər isə əks mənalıdır.", skills: ["az.lex.meaning"] },
            { id: "az2-mena-l2-b3", type: "multiple_choice", prompt: "'Zəif' sözünün əksi hansıdır?", options: ["güclü", "incə", "kiçik", "yumşaq"], correctIndex: 0, xp: 15, explanation: "Zəif az, güclü isə çox qüvvə bildirir — bunlar bir-birinin əksidir.", skills: ["az.lex.antonym"] },
            { id: "az2-mena-l2-b4", type: "multiple_choice", prompt: "Əks mənalı sözlər nə üçün faydalıdır?", options: ["Fikri dəqiq ifadə etmək üçün", "Cümləni uzatmaq üçün", "Yazını çətinləşdirmək üçün", "Faydası yoxdur"], correctIndex: 0, xp: 15, explanation: "Əks mənalı sözlər fərqi aydın göstərir: «böyük deyil, kiçik» deyəndə fikir dəqiqləşir.", skills: ["az.lex.antonym"] },
          ],
        },
        {
          id: "az2-mena-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az2-mena-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
  ],
};
