// Azərbaycan dili — 4-cü sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) İsim və halları  2) Əvəzlik  3) Zərf  4) Cümlə üzvləri
// 5) Söz yaradıcılığı və orfoqrafiya  6) Mətn və nitq.
// 4-cü sinif üçün. id prefiksi az4-*.

import type { Subject } from "../types";

export const azerbaijani4: Subject = {
  slug: "azerbaycan-dili-4",
  name: "Azərbaycan dili",
  grade: 4,
  icon: "A",
  color: "rose",
  units: [
    // ═══════════════ 1. İsim və halları ═══════════════
    {
      id: "az4-isim",
      title: "İsim və halları",
      description: "İsmin təkrarı, tək/cəm, xüsusi/ümumi və halları ilə ilkin tanışlıq.",
      lessons: [
        {
          id: "az4-isim-l1",
          title: "İsim və halları",
          intro: "İsim əşyanın adıdır; suala görə hallanır.",
          sections: [
            { heading: "İsim", body: "Əşyanın adını bildirən söz isimdir: 'kim?' (insan/heyvan), 'nə?' (əşya). Tək/cəm, xüsusi/ümumi olur." },
            { heading: "Hallar", body: "İsim suala görə dəyişir (hallanır): adlıq (kim? nə?), yiyəlik (kimin? nəyin?), yönlük (kimə? nəyə?), təsirlik (kimi? nəyi?), yerlik (kimdə? nədə?), çıxışlıq (kimdən? nədən?)." },
          ],
          tasks: [
            { id: "az4-isim-l1-t1", type: "multiple_choice", prompt: "İsim hansı suallara cavab verir?", options: ["kim? nə?", "necə?", "nə edir?", "neçə?"], correctIndex: 0, xp: 10, explanation: "İsim əşya və varlıqların adıdır: canlılara «kim?», cansızlara «nə?» sualı verilir.", skills: ["az.pos.noun_case"] },
            { id: "az4-isim-l1-t2", type: "multiple_choice", prompt: "Adlıq hal hansı suala cavab verir?", options: ["kim? nə?", "kimin?", "kimə?", "kimdən?"], correctIndex: 0, xp: 10, explanation: "Adlıq hal ismin heç bir hal şəkilçisi almamış ilkin formasıdır — «kim? nə?» suallarına cavab verir.", skills: ["az.pos.noun_case"] },
            { id: "az4-isim-l1-t3", type: "multiple_choice", prompt: "'kimin? nəyin?' hansı haldır?", options: ["yiyəlik", "adlıq", "yönlük", "təsirlik"], correctIndex: 0, xp: 10, explanation: "«Kimin? nəyin?» sualları sahibliyi göstərir — bu, yiyəlik haldır.", skills: ["az.pos.noun_case"] },
            { id: "az4-isim-l1-t4", type: "multiple_choice", prompt: "'kimə? nəyə?' hansı haldır?", options: ["yönlük", "yiyəlik", "təsirlik", "yerlik"], correctIndex: 0, xp: 10, explanation: "«Kimə? nəyə?» sualları hərəkətin yönəldiyi tərəfi göstərir — bu, yönlük haldır.", skills: ["az.pos.noun_case"] },
            { id: "az4-isim-l1-t5", type: "multiple_choice", prompt: "'kimi? nəyi?' hansı haldır?", options: ["təsirlik", "yönlük", "yerlik", "çıxışlıq"], correctIndex: 0, xp: 10, explanation: "«Kimi? nəyi?» sualları hərəkətin üzərinə düşdüyü əşyanı göstərir — bu, təsirlik haldır.", skills: ["az.pos.noun_case"] },
            { id: "az4-isim-l1-t6", type: "multiple_choice", prompt: "'kimdə? nədə?' hansı haldır?", options: ["yerlik", "çıxışlıq", "yönlük", "adlıq"], correctIndex: 0, xp: 10, explanation: "«Kimdə? nədə?» sualları yeri göstərir — bu, yerlik haldır.", skills: ["az.pos.noun_case"] },
            { id: "az4-isim-l1-t7", type: "multiple_choice", prompt: "'kimdən? nədən?' hansı haldır?", options: ["çıxışlıq", "yerlik", "yönlük", "təsirlik"], correctIndex: 0, xp: 10, explanation: "«Kimdən? nədən?» sualları başlanğıc nöqtəni göstərir — bu, çıxışlıq haldır.", skills: ["az.pos.noun_case"] },
            { id: "az4-isim-l1-t8", type: "numeric", prompt: "İsmin neçə halı var?", answer: 6, xp: 10, explanation: "Hallar: adlıq, yiyəlik, yönlük, təsirlik, yerlik, çıxışlıq — cəmi 6.", skills: ["az.pos.noun_case"] },
            { id: "az4-isim-l1-t9", type: "multiple_choice", prompt: "'kitabı' sözü hansı haldadır?", options: ["təsirlik (nəyi?)", "adlıq", "yiyəlik", "yerlik"], correctIndex: 0, xp: 10, explanation: "«Kitabı» sözü «nəyi?» sualına cavab verir — deməli təsirlik haldadır.", skills: ["az.pos.noun_case"] },
            { id: "az4-isim-l1-t10", type: "multiple_choice", prompt: "'evdə' sözü hansı haldadır?", options: ["yerlik (nədə?)", "yönlük", "çıxışlıq", "adlıq"], correctIndex: 0, xp: 10, explanation: "«Evdə» sözündə -də şəkilçisi var və «nədə?» sualına cavab verir — yerlik haldır.", skills: ["az.pos.noun_case"] },
            { id: "az4-isim-l1-t11", type: "multiple_choice", prompt: "'evə' sözü hansı haldadır?", options: ["yönlük (nəyə?)", "yerlik", "çıxışlıq", "adlıq"], correctIndex: 0, xp: 10, explanation: "«Evə» sözündə -ə şəkilçisi var və «nəyə?» sualına cavab verir — yönlük haldır.", skills: ["az.pos.noun_case"] },
            { id: "az4-isim-l1-t12", type: "multiple_choice", prompt: "'evdən' sözü hansı haldadır?", options: ["çıxışlıq (nədən?)", "yerlik", "yönlük", "adlıq"], correctIndex: 0, xp: 10, explanation: "«Evdən» sözündə -dən şəkilçisi var və «nədən?» sualına cavab verir — çıxışlıq haldır.", skills: ["az.pos.noun_case"] },
            { id: "az4-isim-l1-t13", type: "multiple_choice", prompt: "Xüsusi isimlər necə yazılır?", options: ["böyük hərflə", "kiçik hərflə", "cəmdə", "rəqəmlə"], correctIndex: 0, xp: 10, explanation: "Xüsusi isim konkret bir varlığın adıdır, ona görə həmişə böyük hərflə yazılır.", skills: ["az.pos.noun","az.orth.capital"] },
            { id: "az4-isim-l1-t14", type: "multiple_choice", prompt: "'uşaqlar' sözü hansı formadadır?", options: ["cəm", "tək", "xüsusi", "feil"], correctIndex: 0, xp: 10, explanation: "«Uşaqlar» sözündə -lar cəm şəkilçisi var — deməli birdən çox uşaq nəzərdə tutulur.", skills: ["az.pos.noun_case"] },
            { id: "az4-isim-l1-t15", type: "multiple_choice", prompt: "'uşağın' sözü hansı haldadır?", options: ["yiyəlik (kimin?)", "adlıq", "təsirlik", "yerlik"], correctIndex: 0, xp: 15, explanation: "«Uşağın» sözü «kimin?» sualına cavab verir — deməli yiyəlik haldadır.", skills: ["az.pos.noun_case"] },
          ],
          bonusTasks: [
            { id: "az4-isim-l1-b1", type: "multiple_choice", prompt: "'məktəbə' sözü hansı haldadır?", options: ["yönlük", "yerlik", "çıxışlıq", "adlıq"], correctIndex: 0, xp: 15, explanation: "«Məktəbə» sözü «nəyə?» sualına cavab verir — yönlük haldır.", skills: ["az.pos.noun_case"] },
            { id: "az4-isim-l1-b2", type: "multiple_choice", prompt: "'dostumdan' sözü hansı haldadır?", options: ["çıxışlıq", "yönlük", "yerlik", "təsirlik"], correctIndex: 0, xp: 15, explanation: "«Dostumdan» sözündə -dan şəkilçisi var və «kimdən?» sualına cavab verir — çıxışlıq haldır.", skills: ["az.pos.noun_case"] },
            { id: "az4-isim-l1-b3", type: "multiple_choice", prompt: "Adlıq hal ismin hansı formasıdır?", options: ["ilkin/əsas forma", "cəm forma", "kiçildilmiş forma", "feil forma"], correctIndex: 0, xp: 15, explanation: "Adlıq halda isim heç bir hal şəkilçisi almır — lüğətdə də bu formada yazılır.", skills: ["az.pos.noun_case"] },
            { id: "az4-isim-l1-b4", type: "multiple_choice", prompt: "'kitabda' sözü hansı haldadır?", options: ["yerlik", "yönlük", "çıxışlıq", "təsirlik"], correctIndex: 0, xp: 15, explanation: "«Kitabda» sözü «nədə?» sualına cavab verir — yerlik haldır.", skills: ["az.pos.noun_case"] },
            { id: "az4-isim-l1-b5", type: "multiple_choice", prompt: "'Bakıya' sözü hansı haldadır?", options: ["yönlük", "yerlik", "çıxışlıq", "adlıq"], correctIndex: 0, xp: 15, explanation: "«Bakıya» sözü «hara? nəyə?» sualına cavab verir — yönlük haldır.", skills: ["az.pos.noun_case"] },
          ],
        },
        {
          id: "az4-isim-l2",
          title: "Mənsubiyyət və kəmiyyət",
          intro: "İsim kimə aiddir və neçədir?",
          sections: [
            { heading: "Mənsubiyyət", body: "İsim kimə aid olduğunu bildirir: kitab-ım, kitab-ın, kitab-ı, kitab-ımız, kitab-ınız, kitab-ları." },
            { heading: "Kəmiyyət", body: "Tək: kitab. Cəm: kitablar. Cəm şəkilçisi -lar/-lər həmişə mənsubiyyətdən ƏVVƏL gəlir: kitab-lar-ım." },
          ],
          tasks: [
            { id: "az4-isim-l2-t1", type: "multiple_choice", prompt: "'kitabım' sözü kimə aiddir?", options: ["Mənə", "Sənə", "Ona", "Bizə"], correctIndex: 0, xp: 10, explanation: "-ım mənsubiyyət şəkilçisi I şəxs təki bildirir: mənim kitabım.", skills: ["az.pos.noun_case"] },
            { id: "az4-isim-l2-t2", type: "multiple_choice", prompt: "'kitabın' sözü kimə aiddir?", options: ["Sənə", "Mənə", "Ona", "Onlara"], correctIndex: 0, xp: 10, explanation: "-ın mənsubiyyət şəkilçisi II şəxs təki bildirir: sənin kitabın.", skills: ["az.pos.noun_case"] },
            { id: "az4-isim-l2-t3", type: "multiple_choice", prompt: "'kitabımız' sözü kimə aiddir?", options: ["Bizə", "Mənə", "Sizə", "Onlara"], correctIndex: 0, xp: 10, explanation: "-ımız mənsubiyyət şəkilçisi I şəxs cəmi bildirir: bizim kitabımız.", skills: ["az.pos.noun_case"] },
            { id: "az4-isim-l2-t4", type: "multiple_choice", prompt: "'kitablarım' sözündə şəkilçilərin sırası necədir?", options: ["Əvvəl cəm, sonra mənsubiyyət", "Əvvəl mənsubiyyət, sonra cəm", "Fərqi yoxdur", "Şəkilçi yoxdur"], correctIndex: 0, xp: 10, explanation: "Sözü hissələrə ayırırıq: kitab + lar (cəm) + ım (mənsubiyyət). Deməli əvvəl cəm gəlir.", skills: ["az.morph.root"] },
            { id: "az4-isim-l2-t5", type: "multiple_choice", prompt: "Hansı söz cəmdə və mənsubiyyətdədir?", options: ["dostlarım", "dostum", "dostlar", "dost"], correctIndex: 0, xp: 10, explanation: "«Dostlarım» sözündə iki şəkilçi var: -lar cəmi, -ım isə mənə aid olduğunu bildirir.", skills: ["az.pos.noun_possess"] },
            { id: "az4-isim-l2-t6", type: "multiple_choice", prompt: "'evimiz' sözünün kökü hansıdır?", options: ["ev", "evim", "imiz", "evi"], correctIndex: 0, xp: 10, explanation: "Sözü hissələrə ayırırıq: ev + imiz. Kök ev-dir.", skills: ["az.morph.root"] },
            { id: "az4-isim-l2-t7", type: "fill_blank", prompt: "'qələm' sözünə 'mənim' mənsubiyyəti əlavə et: ______", accepted: ["qələmim", "Qələmim"], xp: 10, explanation: "I şəxs təkin mənsubiyyət şəkilçisini qoşuruq: qələm + im = qələmim.", skills: ["az.pos.noun_possess"] },
            { id: "az4-isim-l2-t8", type: "multiple_choice", prompt: "'onların kitabı' necə yazılır?", options: ["kitabları", "kitabım", "kitabın", "kitabımız"], correctIndex: 0, xp: 10, explanation: "III şəxs cəmə aid olduğunu -ları şəkilçisi bildirir: onların kitabları → kitabları.", skills: ["az.pos.noun_case"] },
            { id: "az4-isim-l2-t9", type: "multiple_choice", prompt: "Mənsubiyyət şəkilçisi nəyi bildirir?", options: ["Sahibliyi", "Zamanı", "Yeri", "Sayı"], correctIndex: 0, xp: 10, explanation: "Mənsubiyyət şəkilçisi əşyanın kimə aid olduğunu, yəni sahibliyi bildirir.", skills: ["az.morph.root","az.pos.noun_possess"] },
            { id: "az4-isim-l2-t10", type: "multiple_choice", prompt: "'anam' sözündə mənsubiyyət şəkilçisi hansıdır?", options: ["-m", "ana", "-am", "an"], correctIndex: 0, xp: 10, explanation: "Sözü hissələrə ayırırıq: ana + m. -m şəkilçisi ananın mənə aid olduğunu bildirir.", skills: ["az.morph.root","az.pos.noun_possess"] },
          ],
          bonusTasks: [
            { id: "az4-isim-l2-b1", type: "multiple_choice", prompt: "'sinif yoldaşlarımız' ifadəsində neçə şəkilçi var?", options: ["İki: cəm və mənsubiyyət", "Bir", "Üç", "Heç biri"], correctIndex: 0, xp: 15, explanation: "«Yoldaşlarımız» sözündə iki şəkilçi var: -lar cəmi, -ımız isə bizə aid olduğunu bildirir.", skills: ["az.morph.root"] },
            { id: "az4-isim-l2-b2", type: "multiple_choice", prompt: "Hansı sırada həm cəm, həm mənsubiyyət var?", options: ["dəftərlərin", "dəftər", "dəftərlər", "dəftərə"], correctIndex: 0, xp: 15, explanation: "«Dəftərlərin» sözündə -lər cəmi, -in isə sənə aid olduğunu bildirir. «Dəftərlər»də isə yalnız cəm var.", skills: ["az.pos.noun_possess"] },
            { id: "az4-isim-l2-b3", type: "multiple_choice", prompt: "'Bizim şəhərimiz' ifadəsində mənsubiyyət hansı sözdədir?", options: ["şəhərimiz", "bizim", "hər ikisində", "heç birində"], correctIndex: 0, xp: 15, explanation: "Mənsubiyyət şəkilçisi sahib olunan əşyaya qoşulur: şəhər + imiz. «Bizim» isə ayrıca əvəzlikdir.", skills: ["az.pos.noun_possess"] },
            { id: "az4-isim-l2-b4", type: "multiple_choice", prompt: "İsmin kəmiyyət kateqoriyası nəyi bildirir?", options: ["Tək və ya cəm olduğunu", "Sahibini", "Yerini", "Zamanını"], correctIndex: 0, xp: 15, explanation: "Kəmiyyət ismin bir dənə (tək), yoxsa bir neçə (cəm) olduğunu göstərir.", skills: ["az.pos.noun_possess"] },
          ],
        },
        {
          id: "az4-isim-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az4-isim-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 2. Əvəzlik ═══════════════
    {
      id: "az4-evezlik",
      title: "Əvəzlik",
      description: "İsim, sifət və sayın yerində işlənən sözlər: mən, sən, o, bu.",
      lessons: [
        {
          id: "az4-evezlik-l1",
          title: "Əvəzlik",
          intro: "Adların yerində işlənən sözlər.",
          sections: [
            { heading: "Şəxs əvəzlikləri", body: "İnsanları əvəz edir: mən, sən, o, biz, siz, onlar." },
            { heading: "İşarə əvəzlikləri", body: "Əşyaya işarə edir: bu, o, elə, belə." },
          ],
          tasks: [
            { id: "az4-evezlik-l1-t1", type: "multiple_choice", prompt: "Aşağıdakılardan hansı şəxs əvəzliyidir?", options: ["mən", "kitab", "gözəl", "oxumaq"], correctIndex: 0, xp: 10, explanation: "«Mən» danışanın özünü bildirir — deməli şəxs əvəzliyidir. Kitab isim, gözəl sifət, oxumaq feildir.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l1-t2", type: "multiple_choice", prompt: "Aşağıdakılardan hansı şəxs əvəzliyidir?", options: ["sən", "ev", "böyük", "getmək"], correctIndex: 0, xp: 10, explanation: "«Sən» müraciət olunan şəxsi bildirir — deməli şəxs əvəzliyidir.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l1-t3", type: "multiple_choice", prompt: "Neçə şəxs əvəzliyi var?", options: ["6 (mən, sən, o, biz, siz, onlar)", "3", "4", "5"], correctIndex: 0, xp: 10, explanation: "Şəxs əvəzlikləri: mən, sən, o (tək) və biz, siz, onlar (cəm) — cəmi 6.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l1-t4", type: "multiple_choice", prompt: "'o' hansı əvəzlikdir?", options: ["şəxs (III tək)", "işarə yalnız", "sual", "sifət"], correctIndex: 0, xp: 10, explanation: "«O» danışıqda iştirak etməyən bir nəfəri bildirir — III şəxs tək şəxs əvəzliyidir.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l1-t5", type: "multiple_choice", prompt: "'biz' neçənci şəxsdir?", options: ["I şəxs cəm", "II şəxs tək", "III şəxs cəm", "I şəxs tək"], correctIndex: 0, xp: 10, explanation: "«Biz» danışanı və onunla birlikdə olanları bildirir — I şəxs cəmdir.", skills: ["az.pos.numeral"] },
            { id: "az4-evezlik-l1-t6", type: "multiple_choice", prompt: "'onlar' neçənci şəxsdir?", options: ["III şəxs cəm", "I şəxs cəm", "II şəxs cəm", "III şəxs tək"], correctIndex: 0, xp: 10, explanation: "«Onlar» danışıqda iştirak etməyən bir neçə nəfəri bildirir — III şəxs cəmdir.", skills: ["az.pos.numeral"] },
            { id: "az4-evezlik-l1-t7", type: "multiple_choice", prompt: "Aşağıdakılardan hansı işarə əvəzliyidir?", options: ["bu", "mən", "gözəl", "beş"], correctIndex: 0, xp: 10, explanation: "«Bu» əşyanı göstərir, adını çəkmir — deməli işarə əvəzliyidir.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l1-t8", type: "multiple_choice", prompt: "Əvəzlik nəyin yerində işlənir?", options: ["ismin, sifətin, sayın", "yalnız feilin", "yalnız zərfin", "heç birinin"], correctIndex: 0, xp: 10, explanation: "Əvəzlik adı təkrarlamamaq üçün ismin, sifətin və ya sayın yerində işlənir.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l1-t9", type: "multiple_choice", prompt: "'Mən kitab oxuyuram.' — əvəzlik hansıdır?", options: ["mən", "kitab", "oxuyuram", "heç biri"], correctIndex: 0, xp: 10, explanation: "Cümlədə «mən» şəxs əvəzliyidir, «kitab» isim, «oxuyuram» isə feildir.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l1-t10", type: "multiple_choice", prompt: "'siz' neçənci şəxsdir?", options: ["II şəxs cəm", "I şəxs cəm", "III şəxs cəm", "II şəxs tək"], correctIndex: 0, xp: 10, explanation: "«Siz» müraciət olunan bir neçə nəfəri (və ya hörmətlə bir nəfəri) bildirir — II şəxs cəmdir.", skills: ["az.pos.numeral"] },
            { id: "az4-evezlik-l1-t11", type: "multiple_choice", prompt: "'Ayşə' əvəzinə hansı əvəzlik işlənə bilər?", options: ["o", "mən", "biz", "siz"], correctIndex: 0, xp: 10, explanation: "Ayşə danışıqda iştirak etməyən bir nəfərdir, onu «o» əvəzliyi əvəz edir.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l1-t12", type: "multiple_choice", prompt: "'Uşaqlar' əvəzinə hansı əvəzlik işlənə bilər?", options: ["onlar", "o", "mən", "sən"], correctIndex: 0, xp: 10, explanation: "«Uşaqlar» bir neçə nəfərdir və danışıqda iştirak etmir — onları «onlar» əvəz edir.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l1-t13", type: "multiple_choice", prompt: "Aşağıdakılardan hansı əvəzlik DEYİL?", options: ["kitab", "mən", "o", "bu"], correctIndex: 0, xp: 10, explanation: "Bu, o, mən — üçü də adı əvəz edir. «Kitab» isə əşyanın öz adıdır, yəni isimdir.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l1-t14", type: "multiple_choice", prompt: "'sən' neçənci şəxsdir?", options: ["II şəxs tək", "I şəxs tək", "III şəxs tək", "II şəxs cəm"], correctIndex: 0, xp: 10, explanation: "«Sən» müraciət olunan bir nəfəri bildirir — II şəxs təkdir.", skills: ["az.pos.numeral"] },
            { id: "az4-evezlik-l1-t15", type: "multiple_choice", prompt: "'mən' neçənci şəxsdir?", options: ["I şəxs tək", "II şəxs tək", "III şəxs tək", "I şəxs cəm"], correctIndex: 0, xp: 15, explanation: "«Mən» danışanın özünü bildirir — I şəxs təkdir.", skills: ["az.pos.numeral"] },
          ],
          bonusTasks: [
            { id: "az4-evezlik-l1-b1", type: "multiple_choice", prompt: "'Bu mənim kitabımdır.' — əvəzliklər hansılardır?", options: ["bu, mənim", "kitab", "kitabımdır", "heç biri"], correctIndex: 0, xp: 15, explanation: "Cümlədə «bu» işarə, «mənim» isə şəxs əvəzliyidir. «Kitabımdır» isimdir.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l1-b2", type: "multiple_choice", prompt: "'kim?', 'nə?' hansı əvəzlik növüdür?", options: ["sual əvəzliyi", "şəxs əvəzliyi", "işarə əvəzliyi", "sifət"], correctIndex: 0, xp: 15, explanation: "«Kim?» və «nə?» sual verərkən adın yerində işlənir — deməli sual əvəzliyidir.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l1-b3", type: "multiple_choice", prompt: "'Elçin və Ayşə' əvəzinə hansı əvəzlik işlənər?", options: ["onlar", "o", "biz", "siz"], correctIndex: 0, xp: 15, explanation: "«Elçin və Ayşə» iki nəfərdir və danışıqda iştirak etmir — onları «onlar» əvəz edir.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l1-b4", type: "multiple_choice", prompt: "Əvəzlik cümlədə hansı üzv ola bilər?", options: ["mübtəda (kim? — o gəldi)", "yalnız xəbər", "heç bir", "yalnız təyin"], correctIndex: 0, xp: 15, explanation: "Əvəzlik ismin yerində işləndiyi üçün onun cümlədəki vəzifəsini də daşıyır: «O gəldi» cümləsində mübtədadır.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l1-b5", type: "multiple_choice", prompt: "'sən və mən' əvəzinə hansı əvəzlik işlənər?", options: ["biz", "siz", "onlar", "o"], correctIndex: 0, xp: 15, explanation: "«Sən və mən» danışanı və müraciət olunanı birləşdirir — bu, «biz» deməkdir.", skills: ["az.pos.pronoun"] },
          ],
        },
        {
          id: "az4-evezlik-l2",
          title: "Əvəzliyin növləri",
          intro: "Əvəzlik ismin, sifətin və ya sayın yerində işlənir.",
          sections: [
            { heading: "Şəxs əvəzlikləri", body: "mən, sən, o, biz, siz, onlar — insanı və ya əşyanı əvəz edir." },
            { heading: "Digər növlər", body: "İŞARƏ: bu, o, elə, belə. SUAL: kim, nə, hansı, neçə. QEYRİ-MÜƏYYƏN: bəzi, hər, heç kim." },
          ],
          tasks: [
            { id: "az4-evezlik-l2-t1", type: "multiple_choice", prompt: "'mən' hansı əvəzlikdir?", options: ["Şəxs", "İşarə", "Sual", "Qeyri-müəyyən"], correctIndex: 0, xp: 10, explanation: "«Mən» danışanın özünü bildirir — şəxs əvəzliyidir.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l2-t2", type: "multiple_choice", prompt: "'bu' hansı əvəzlikdir?", options: ["İşarə", "Şəxs", "Sual", "Qeyri-müəyyən"], correctIndex: 0, xp: 10, explanation: "«Bu» yaxındakı əşyanı göstərir — işarə əvəzliyidir.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l2-t3", type: "multiple_choice", prompt: "'kim' hansı əvəzlikdir?", options: ["Sual", "Şəxs", "İşarə", "Qeyri-müəyyən"], correctIndex: 0, xp: 10, explanation: "«Kim» sual verərkən adın yerində işlənir — sual əvəzliyidir.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l2-t4", type: "multiple_choice", prompt: "'hər kəs' hansı əvəzlikdir?", options: ["Qeyri-müəyyən", "Şəxs", "İşarə", "Sual"], correctIndex: 0, xp: 10, explanation: "«Hər kəs» konkret kimisə göstərmir, ümumi bildirir — qeyri-müəyyən əvəzlikdir.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l2-t5", type: "multiple_choice", prompt: "Şəxs əvəzlikləri hansılardır?", options: ["mən, sən, o, biz, siz, onlar", "bu, o, elə", "kim, nə, hansı", "bəzi, hər"], correctIndex: 0, xp: 10, explanation: "Şəxs əvəzlikləri danışan, dinləyən və üçüncü şəxsi bildirir: mən, sən, o, biz, siz, onlar.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l2-t6", type: "multiple_choice", prompt: "Əvəzlik nəyin yerində işlənir?", options: ["İsim, sifət və sayın", "Yalnız feilin", "Yalnız zərfin", "Heç nəyin"], correctIndex: 0, xp: 10, explanation: "Əvəzlik adı təkrarlamamaq üçün ismin, sifətin və ya sayın yerində işlənir.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l2-t7", type: "multiple_choice", prompt: "'Onlar gəldilər.' — 'onlar' hansı əvəzlikdir?", options: ["Şəxs", "İşarə", "Sual", "Qeyri-müəyyən"], correctIndex: 0, xp: 10, explanation: "«Onlar» danışıqda iştirak etməyən bir neçə nəfəri bildirir — şəxs əvəzliyidir.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l2-t8", type: "fill_blank", prompt: "III şəxs tək şəxs əvəzliyi ______-dur. (bir söz)", accepted: ["o", "O"], xp: 10, explanation: "III şəxs tək danışıqda iştirak etməyən bir nəfəri bildirir — bu, «o»dur.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l2-t9", type: "multiple_choice", prompt: "'Bu kitab mənimdir.' — burada işarə əvəzliyi hansıdır?", options: ["Bu", "kitab", "mənim", "dir"], correctIndex: 0, xp: 10, explanation: "«Bu» kitabı göstərir, adını çəkmir — işarə əvəzliyidir. «Mənim» isə şəxs əvəzliyidir.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l2-t10", type: "multiple_choice", prompt: "'neçə' hansı əvəzlikdir?", options: ["Sual", "Şəxs", "İşarə", "Qeyri-müəyyən"], correctIndex: 0, xp: 10, explanation: "«Neçə» sayı soruşur, yəni sayın yerində işlənir — sual əvəzliyidir.", skills: ["az.pos.pronoun"] },
          ],
          bonusTasks: [
            { id: "az4-evezlik-l2-b1", type: "multiple_choice", prompt: "Niyə əvəzlik işlədirik?", options: ["Sözü təkrar etməmək üçün", "Cümləni uzatmaq üçün", "Qrammatika üçün", "Səbəbi yoxdur"], correctIndex: 0, xp: 15, explanation: "Əvəzlik olmasa, eyni ad hər cümlədə təkrarlanardı: «Aysel gəldi. Aysel şaddır» — bu, ağır səslənir.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l2-b2", type: "multiple_choice", prompt: "'Aysel gəldi. O, çox şaddır.' — 'o' nəyi əvəz edir?", options: ["Aysel", "gəldi", "şad", "heç nəyi"], correctIndex: 0, xp: 15, explanation: "İkinci cümlədə «o» birinci cümlədə adı çəkilən Ayseli əvəz edir.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l2-b3", type: "multiple_choice", prompt: "Hansı sırada hamısı sual əvəzliyidir?", options: ["kim, nə, hansı", "mən, sən, o", "bu, o, belə", "bəzi, hər, heç"], correctIndex: 0, xp: 15, explanation: "Kim, nə, hansı — üçü də sual verir. Digər sıralarda işarə, qeyri-müəyyən və şəxs əvəzlikləri var.", skills: ["az.pos.pronoun"] },
            { id: "az4-evezlik-l2-b4", type: "multiple_choice", prompt: "Şəxs əvəzlikləri neçə şəxsə görə dəyişir?", options: ["Üç: I, II, III", "İki", "Dörd", "Dəyişmir"], correctIndex: 0, xp: 15, explanation: "Danışan (I), dinləyən (II) və haqqında danışılan (III) — üç şəxs var, hər biri tək və cəm olur.", skills: ["az.pos.pronoun"] },
          ],
        },
        {
          id: "az4-evezlik-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az4-evezlik-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 3. Zərf ═══════════════
    {
      id: "az4-zerf",
      title: "Zərf",
      description: "İşin tərzini, zamanını, yerini bildirən sözlər.",
      lessons: [
        {
          id: "az4-zerf-l1",
          title: "Zərf",
          intro: "Hərəkətin necə, nə vaxt, harada olduğunu bildirir.",
          sections: [
            { heading: "Zərf", body: "İşin əlamətini bildirir: tərz (necə? — tez, yavaş), zaman (nə vaxt? — dünən, sabah), yer (harada? — irəli, geri)." },
          ],
          tasks: [
            { id: "az4-zerf-l1-t1", type: "multiple_choice", prompt: "Aşağıdakılardan hansı zərfdir?", options: ["tez", "kitab", "gözəl", "beş"], correctIndex: 0, xp: 10, explanation: "«Tez» işin necə görüldüyünü bildirir — deməli zərfdir. Kitab isim, beş say, gözəl isə sifətdir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l1-t2", type: "multiple_choice", prompt: "'dünən' hansı zərf növüdür?", options: ["zaman", "tərz", "yer", "kəmiyyət"], correctIndex: 0, xp: 10, explanation: "«Dünən» işin nə vaxt olduğunu bildirir — zaman zərfidir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l1-t3", type: "multiple_choice", prompt: "'tez' hansı zərf növüdür?", options: ["tərz", "zaman", "yer", "kəmiyyət"], correctIndex: 0, xp: 10, explanation: "«Tez» işin necə görüldüyünü bildirir — tərz zərfidir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l1-t4", type: "multiple_choice", prompt: "'irəli' hansı zərf növüdür?", options: ["yer", "zaman", "tərz", "kəmiyyət"], correctIndex: 0, xp: 10, explanation: "«İrəli» işin hansı istiqamətdə olduğunu bildirir — yer zərfidir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l1-t5", type: "multiple_choice", prompt: "Tərz zərfi hansı suala cavab verir?", options: ["necə?", "nə vaxt?", "harada?", "neçə?"], correctIndex: 0, xp: 10, explanation: "Tərz işin necə görüldüyünü göstərir, ona görə «necə?» sualına cavab verir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l1-t6", type: "multiple_choice", prompt: "Zaman zərfi hansı suala cavab verir?", options: ["nə vaxt?", "necə?", "harada?", "neçə?"], correctIndex: 0, xp: 10, explanation: "Zaman işin nə vaxt olduğunu göstərir, ona görə «nə vaxt?» sualına cavab verir.", skills: ["az.pos.adverb","az.pos.verb_tense"] },
            { id: "az4-zerf-l1-t7", type: "multiple_choice", prompt: "Yer zərfi hansı suala cavab verir?", options: ["harada?", "necə?", "nə vaxt?", "neçə?"], correctIndex: 0, xp: 10, explanation: "Yer işin harada olduğunu göstərir, ona görə «harada?» sualına cavab verir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l1-t8", type: "multiple_choice", prompt: "'Uşaq gözəl oxuyur.' — zərf hansıdır?", options: ["gözəl", "uşaq", "oxuyur", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Gözəl» burada oxumağın necə olduğunu bildirir, yəni feili izah edir — deməli zərfdir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l1-t9", type: "multiple_choice", prompt: "'sabah' hansı zərf növüdür?", options: ["zaman", "yer", "tərz", "kəmiyyət"], correctIndex: 0, xp: 10, explanation: "«Sabah» işin nə vaxt olacağını bildirir — zaman zərfidir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l1-t10", type: "multiple_choice", prompt: "'yavaş' hansı zərf növüdür?", options: ["tərz", "zaman", "yer", "kəmiyyət"], correctIndex: 0, xp: 10, explanation: "«Yavaş» işin necə görüldüyünü bildirir — tərz zərfidir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l1-t11", type: "multiple_choice", prompt: "'Dünən gəldim.' — zərf hansıdır?", options: ["dünən", "gəldim", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Dünən» gəlmənin nə vaxt olduğunu bildirir — zərfdir. «Gəldim» isə feildir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l1-t12", type: "multiple_choice", prompt: "Zərf əsasən hansı sözü izah edir?", options: ["feili", "ismi", "sayı", "qoşmanı"], correctIndex: 0, xp: 10, explanation: "Zərf işin necə, nə vaxt, harada görüldüyünü bildirir — yəni feili izah edir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l1-t13", type: "multiple_choice", prompt: "'geri' hansı zərf növüdür?", options: ["yer", "zaman", "tərz", "kəmiyyət"], correctIndex: 0, xp: 10, explanation: "«Geri» istiqaməti bildirir — yer zərfidir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l1-t14", type: "multiple_choice", prompt: "'həmişə' hansı zərf növüdür?", options: ["zaman", "yer", "tərz", "kəmiyyət"], correctIndex: 0, xp: 10, explanation: "«Həmişə» işin nə vaxt olduğunu bildirir — zaman zərfidir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l1-t15", type: "multiple_choice", prompt: "Aşağıdakılardan hansı zərf DEYİL?", options: ["kitab", "tez", "dünən", "yavaş"], correctIndex: 0, xp: 15, explanation: "Dünən, tez, yavaş — üçü də feili izah edir. «Kitab» isə əşyanın adıdır.", skills: ["az.pos.adverb"] },
          ],
          bonusTasks: [
            { id: "az4-zerf-l1-b1", type: "multiple_choice", prompt: "'Səhər tez durdum.' — neçə zərf var? (səhər/tez)", options: ["2", "1", "3", "0"], correctIndex: 0, xp: 15, explanation: "Cümlədə iki söz durmağı izah edir: «səhər» nə vaxt, «tez» isə necə.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l1-b2", type: "multiple_choice", prompt: "Zərflə sifətin fərqi nədir?", options: ["zərf feili, sifət ismi izah edir", "heç fərq yox", "zərf ismi izah edir", "sifət feili izah edir"], correctIndex: 0, xp: 15, explanation: "Sifət əşyanı izah edir («gözəl mahnı»), zərf isə hərəkəti («gözəl oxuyur»).", skills: ["az.pos.adverb","az.pos.adjective"] },
            { id: "az4-zerf-l1-b3", type: "multiple_choice", prompt: "'çox' hansı zərf növüdür?", options: ["kəmiyyət", "yer", "zaman", "tərz"], correctIndex: 0, xp: 15, explanation: "«Çox» işin nə qədər olduğunu bildirir — kəmiyyət zərfidir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l1-b4", type: "multiple_choice", prompt: "'Uşaqlar bağçada oynayır.' — zərf hansıdır?", options: ["bağçada", "uşaqlar", "oynayır", "heç biri"], correctIndex: 0, xp: 15, explanation: "«Bağçada» oynamağın harada olduğunu bildirir — yer mənası daşıyır.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l1-b5", type: "multiple_choice", prompt: "'birlikdə' hansı zərf növüdür?", options: ["tərz", "zaman", "yer", "kəmiyyət"], correctIndex: 0, xp: 15, explanation: "«Birlikdə» işin necə görüldüyünü bildirir — tərz zərfidir.", skills: ["az.pos.adverb"] },
          ],
        },
        {
          id: "az4-zerf-l2",
          title: "Zərfin növləri",
          intro: "Zərf hərəkətin necə, nə vaxt və harada olduğunu bildirir.",
          sections: [
            { heading: "Növlər", body: "TƏRZİ-HƏRƏKƏT: necə? (tez, yavaş, gözəl). ZAMAN: nə vaxt? (dünən, sabah, indi). YER: harada? (burada, orada, irəli). MİQDAR: nə qədər? (çox, az)." },
            { heading: "Fərq", body: "Sifət İSMİ, zərf isə FEİLİ izah edir: 'gözəl mahnı' (sifət) — 'gözəl oxuyur' (zərf)." },
          ],
          tasks: [
            { id: "az4-zerf-l2-t1", type: "multiple_choice", prompt: "'tez qaçdı' — 'tez' hansı zərfdir?", options: ["Tərzi-hərəkət", "Zaman", "Yer", "Miqdar"], correctIndex: 0, xp: 10, explanation: "«Tez» qaçmağın necə olduğunu bildirir — tərzi-hərəkət zərfidir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l2-t2", type: "multiple_choice", prompt: "'dünən gəldi' — 'dünən' hansı zərfdir?", options: ["Zaman", "Yer", "Tərzi-hərəkət", "Miqdar"], correctIndex: 0, xp: 10, explanation: "«Dünən» gəlmənin nə vaxt olduğunu bildirir — zaman zərfidir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l2-t3", type: "multiple_choice", prompt: "'burada dayandı' — 'burada' hansı zərfdir?", options: ["Yer", "Zaman", "Miqdar", "Tərzi-hərəkət"], correctIndex: 0, xp: 10, explanation: "«Burada» dayanmağın harada olduğunu bildirir — yer zərfidir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l2-t4", type: "multiple_choice", prompt: "'çox oxudu' — 'çox' hansı zərfdir?", options: ["Miqdar", "Zaman", "Yer", "Tərzi-hərəkət"], correctIndex: 0, xp: 10, explanation: "«Çox» oxumağın nə qədər olduğunu bildirir — miqdar zərfidir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l2-t5", type: "multiple_choice", prompt: "Zərf nəyi izah edir?", options: ["Feili", "İsmi", "Sayı", "Bağlayıcını"], correctIndex: 0, xp: 10, explanation: "Zərf işin necə, nə vaxt, harada və nə qədər görüldüyünü bildirir — yəni feili izah edir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l2-t6", type: "multiple_choice", prompt: "'gözəl mahnı' ifadəsində 'gözəl' nədir?", options: ["Sifət", "Zərf", "Feil", "İsim"], correctIndex: 0, xp: 10, explanation: "«Gözəl» burada mahnını, yəni ismi izah edir — deməli sifətdir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l2-t7", type: "multiple_choice", prompt: "'gözəl oxuyur' ifadəsində 'gözəl' nədir?", options: ["Zərf", "Sifət", "İsim", "Say"], correctIndex: 0, xp: 10, explanation: "«Gözəl» burada oxumağı, yəni feili izah edir — deməli zərfdir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l2-t8", type: "fill_blank", prompt: "Zaman zərfi ______ sualına cavab verir. (məs. nə vaxt)", accepted: ["nə vaxt", "Nə vaxt", "nevaxt"], xp: 10, explanation: "Zaman işin nə vaxt olduğunu göstərir: dünən, sabah, indi.", skills: ["az.pos.adverb","az.pos.verb_tense"] },
            { id: "az4-zerf-l2-t9", type: "multiple_choice", prompt: "Hansı söz YER zərfidir?", options: ["irəli", "yavaş", "sabah", "az"], correctIndex: 0, xp: 10, explanation: "«İrəli» istiqaməti, yəni yeri bildirir. Yavaş tərz, sabah zaman, az isə miqdar zərfidir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l2-t10", type: "multiple_choice", prompt: "Hansı söz ZAMAN zərfidir?", options: ["indi", "orada", "tez", "çox"], correctIndex: 0, xp: 10, explanation: "«İndi» vaxtı bildirir. Tez tərz, orada yer, çox isə miqdar zərfidir.", skills: ["az.pos.adverb"] },
          ],
          bonusTasks: [
            { id: "az4-zerf-l2-b1", type: "multiple_choice", prompt: "'Sürətlə qaçdı' ifadəsində zərf hansıdır?", options: ["Sürətlə", "qaçdı", "hər ikisi", "heç biri"], correctIndex: 0, xp: 15, explanation: "«Sürətlə» qaçmağın necə olduğunu bildirir — deməli zərfdir. «Qaçdı» isə feildir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l2-b2", type: "multiple_choice", prompt: "Eyni söz həm sifət, həm zərf ola bilərmi?", options: ["Bəli, cümlədəki roluna görə", "Xeyr", "Yalnız şeirdə", "Yalnız yazıda"], correctIndex: 0, xp: 15, explanation: "Söz nəyi izah etməsindən asılıdır: «gözəl mahnı»da sifət, «gözəl oxuyur»da zərfdir.", skills: ["az.pos.adverb","az.pos.adjective"] },
            { id: "az4-zerf-l2-b3", type: "multiple_choice", prompt: "'Az danışdı, çox işlədi' cümləsində neçə zərf var?", options: ["2", "1", "3", "0"], correctIndex: 0, xp: 15, explanation: "«Az» danışmağı, «çox» isə işləməyi izah edir — hər ikisi zərfdir.", skills: ["az.pos.adverb"] },
            { id: "az4-zerf-l2-b4", type: "multiple_choice", prompt: "Zərflər dəyişirmi (hallanır, cəmlənir)?", options: ["Xeyr, dəyişməzdir", "Bəli, hallanır", "Bəli, cəmlənir", "Yalnız cəmlənir"], correctIndex: 0, xp: 15, explanation: "Zərflər hal şəkilçisi və cəm şəkilçisi qəbul etmir — həmişə eyni formada qalır.", skills: ["az.pos.adverb"] },
          ],
        },
        {
          id: "az4-zerf-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az4-zerf-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 4. Cümlə üzvləri ═══════════════
    {
      id: "az4-uzvler",
      title: "Cümlə üzvləri",
      description: "Baş üzvlər (mübtəda, xəbər) və ikinci dərəcəli üzvlər.",
      lessons: [
        {
          id: "az4-uzvler-l1",
          title: "Cümlə üzvləri",
          intro: "Cümlədə hər sözün vəzifəsi var.",
          sections: [
            { heading: "Baş üzvlər", body: "Mübtəda — iş görəni bildirir (kim? nə?). Xəbər — işi bildirir (nə edir?). 'Uşaq oxuyur.' — uşaq (mübtəda), oxuyur (xəbər)." },
            { heading: "İkinci dərəcəli üzvlər", body: "Tamamlıq (nəyi? kimə?), təyin (necə? hansı?), zərflik (harada? nə vaxt?) baş üzvləri izah edir." },
          ],
          tasks: [
            { id: "az4-uzvler-l1-t1", type: "multiple_choice", prompt: "İş görəni bildirən üzv necə adlanır?", options: ["mübtəda", "xəbər", "təyin", "tamamlıq"], correctIndex: 0, xp: 10, explanation: "İşi görəni bildirən baş üzv mübtəda adlanır — «kim? nə?» suallarına cavab verir.", skills: ["az.syn.main_parts"] },
            { id: "az4-uzvler-l1-t2", type: "multiple_choice", prompt: "İşi bildirən üzv necə adlanır?", options: ["xəbər", "mübtəda", "təyin", "zərflik"], correctIndex: 0, xp: 10, explanation: "Görülən işi bildirən baş üzv xəbər adlanır.", skills: ["az.syn.main_parts"] },
            { id: "az4-uzvler-l1-t3", type: "multiple_choice", prompt: "'Uşaq oxuyur.' — mübtəda hansıdır?", options: ["uşaq", "oxuyur", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "Oxuyan kimdir? — uşaq. Deməli mübtəda «uşaq»dır.", skills: ["az.syn.main_parts"] },
            { id: "az4-uzvler-l1-t4", type: "multiple_choice", prompt: "'Uşaq oxuyur.' — xəbər hansıdır?", options: ["oxuyur", "uşaq", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "Uşaq nə edir? — oxuyur. Deməli xəbər «oxuyur»dur.", skills: ["az.syn.main_parts"] },
            { id: "az4-uzvler-l1-t5", type: "multiple_choice", prompt: "Baş üzvlər hansılardır?", options: ["mübtəda və xəbər", "təyin və tamamlıq", "zərflik", "hamısı"], correctIndex: 0, xp: 10, explanation: "Mübtəda və xəbər cümlənin özəyini qurur, ona görə baş üzv sayılır.", skills: ["az.syn.main_parts"] },
            { id: "az4-uzvler-l1-t6", type: "multiple_choice", prompt: "'Gözəl gül açdı.' — təyin hansıdır?", options: ["gözəl", "gül", "açdı", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Gözəl» gülün necə olduğunu bildirir, yəni ismi izah edir — deməli təyindir.", skills: ["az.syn.secondary_parts"] },
            { id: "az4-uzvler-l1-t7", type: "multiple_choice", prompt: "'Kitabı oxudum.' — tamamlıq hansıdır?", options: ["kitabı", "oxudum", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Kitabı» «nəyi?» sualına cavab verir və hərəkətin üzərinə düşdüyü əşyanı bildirir — tamamlıqdır.", skills: ["az.syn.secondary_parts"] },
            { id: "az4-uzvler-l1-t8", type: "multiple_choice", prompt: "'Səhər durdum.' — zərflik hansıdır?", options: ["səhər", "durdum", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Səhər» durmağın nə vaxt olduğunu bildirir — zərflikdir.", skills: ["az.pos.adverb","az.syn.secondary_parts"] },
            { id: "az4-uzvler-l1-t9", type: "multiple_choice", prompt: "'Quşlar uçur.' — mübtəda hansıdır?", options: ["quşlar", "uçur", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "Uçan kimdir? — quşlar. Deməli mübtəda «quşlar»dır.", skills: ["az.syn.main_parts"] },
            { id: "az4-uzvler-l1-t10", type: "multiple_choice", prompt: "Təyin hansı suala cavab verir?", options: ["necə? hansı?", "nə edir?", "kim?", "harada?"], correctIndex: 0, xp: 10, explanation: "Təyin əşyanın əlamətini bildirir, ona görə «necə? hansı?» suallarına cavab verir.", skills: ["az.syn.secondary_parts"] },
            { id: "az4-uzvler-l1-t11", type: "multiple_choice", prompt: "Tamamlıq hansı suala cavab verir?", options: ["nəyi? kimə?", "necə?", "harada?", "nə vaxt?"], correctIndex: 0, xp: 10, explanation: "Tamamlıq hərəkətin yönəldiyi əşyanı bildirir, ona görə «nəyi? kimə?» suallarına cavab verir.", skills: ["az.syn.secondary_parts"] },
            { id: "az4-uzvler-l1-t12", type: "multiple_choice", prompt: "'Bahar gəldi.' — xəbər hansıdır?", options: ["gəldi", "bahar", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, explanation: "Bahar nə etdi? — gəldi. Deməli xəbər «gəldi»dir.", skills: ["az.syn.main_parts"] },
            { id: "az4-uzvler-l1-t13", type: "multiple_choice", prompt: "İkinci dərəcəli üzvlər hansılardır?", options: ["tamamlıq, təyin, zərflik", "mübtəda, xəbər", "isim, feil", "qoşma, bağlayıcı"], correctIndex: 0, xp: 10, explanation: "Tamamlıq, təyin və zərflik baş üzvləri izah edir — ona görə ikinci dərəcəli sayılır.", skills: ["az.syn.main_parts"] },
            { id: "az4-uzvler-l1-t14", type: "multiple_choice", prompt: "'Mən kitab oxuyuram.' — mübtəda hansıdır?", options: ["mən", "kitab", "oxuyuram", "heç biri"], correctIndex: 0, xp: 10, explanation: "Oxuyan kimdir? — mən. Deməli mübtəda «mən»dir, «kitab» isə tamamlıqdır.", skills: ["az.syn.main_parts"] },
            { id: "az4-uzvler-l1-t15", type: "multiple_choice", prompt: "'Balaca uşaq şən oynayır.' — xəbər hansıdır?", options: ["oynayır", "balaca", "uşaq", "şən"], correctIndex: 0, xp: 15, explanation: "Uşaq nə edir? — oynayır. Deməli xəbər «oynayır»dır.", skills: ["az.syn.main_parts"] },
          ],
          bonusTasks: [
            { id: "az4-uzvler-l1-b1", type: "multiple_choice", prompt: "'Balaca uşaq şən oynayır.' — təyin hansıdır?", options: ["balaca", "uşaq", "şən", "oynayır"], correctIndex: 0, xp: 15, explanation: "«Balaca» uşağın necə olduğunu bildirir, yəni ismi izah edir — təyindir.", skills: ["az.syn.secondary_parts"] },
            { id: "az4-uzvler-l1-b2", type: "multiple_choice", prompt: "'Balaca uşaq şən oynayır.' — zərflik hansıdır?", options: ["şən", "balaca", "uşaq", "oynayır"], correctIndex: 0, xp: 15, explanation: "«Şən» oynamağın necə olduğunu bildirir, yəni feili izah edir — zərflikdir.", skills: ["az.pos.adverb","az.syn.secondary_parts"] },
            { id: "az4-uzvler-l1-b3", type: "multiple_choice", prompt: "Cümlədə mütləq olan üzv hansıdır?", options: ["xəbər", "təyin", "tamamlıq", "zərflik"], correctIndex: 0, xp: 15, explanation: "Xəbər olmasa, cümlədə iş bildirilmir və fikir bitmir — ona görə o, mütləqdir.", skills: ["az.syn.sentence"] },
            { id: "az4-uzvler-l1-b4", type: "multiple_choice", prompt: "'Dostuma məktub yazdım.' — tamamlıq hansıdır (nəyi?)?", options: ["məktub", "dostuma", "yazdım", "heç biri"], correctIndex: 0, xp: 15, explanation: "«Məktub» «nəyi?» sualına cavab verir. «Dostuma» isə «kimə?» sualına cavab verən tamamlıqdır.", skills: ["az.syn.secondary_parts"] },
            { id: "az4-uzvler-l1-b5", type: "multiple_choice", prompt: "Cümləni üzvlərinə görə təhlil etmək necə adlanır?", options: ["sintaktik təhlil", "fonetik təhlil", "leksik təhlil", "heç biri"], correctIndex: 0, xp: 15, explanation: "Cümlənin üzvlərə ayrılması və aralarındakı əlaqənin araşdırılması sintaktik təhlil adlanır.", skills: ["az.syn.sentence"] },
          ],
        },
        {
          id: "az4-uzvler-l2",
          title: "İkinci dərəcəli üzvlər",
          intro: "Mübtəda və xəbərdən başqa üzvlər.",
          sections: [
            { heading: "Tamamlıq", body: "Feilin təsir etdiyi əşyanı bildirir, 'nəyi? kimi?' suallarına cavab verir: 'Kitabı oxudum' — kitabı tamamlıqdır." },
            { heading: "Təyin və zərflik", body: "TƏYİN ismi izah edir ('gözəl gül'). ZƏRFLİK hərəkətin yerini/zamanını bildirir ('səhər gəldi')." },
          ],
          tasks: [
            { id: "az4-uzvler-l2-t1", type: "multiple_choice", prompt: "'Kitabı oxudum' cümləsində tamamlıq hansıdır?", options: ["Kitabı", "oxudum", "mən", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Kitabı» «nəyi?» sualına cavab verir — tamamlıqdır. «Oxudum» isə xəbərdir.", skills: ["az.syn.secondary_parts"] },
            { id: "az4-uzvler-l2-t2", type: "multiple_choice", prompt: "Tamamlıq hansı suala cavab verir?", options: ["Nəyi? Kimi?", "Kim? Nə?", "Necə?", "Nə vaxt?"], correctIndex: 0, xp: 10, explanation: "Tamamlıq hərəkətin üzərinə düşdüyü əşyanı bildirir, ona görə «nəyi? kimi?» suallarına cavab verir.", skills: ["az.syn.secondary_parts"] },
            { id: "az4-uzvler-l2-t3", type: "multiple_choice", prompt: "'Gözəl gül açdı' cümləsində təyin hansıdır?", options: ["Gözəl", "gül", "açdı", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Gözəl» gülün əlamətini bildirir, yəni ismi izah edir — təyindir.", skills: ["az.syn.secondary_parts"] },
            { id: "az4-uzvler-l2-t4", type: "multiple_choice", prompt: "'Səhər məktəbə getdim' cümləsində zərflik hansıdır?", options: ["Səhər", "məktəbə", "getdim", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Səhər» getmənin nə vaxt olduğunu bildirir — zərflikdir. «Məktəbə» isə tamamlıqdır.", skills: ["az.pos.adverb","az.syn.secondary_parts"] },
            { id: "az4-uzvler-l2-t5", type: "multiple_choice", prompt: "Təyin nəyi izah edir?", options: ["İsmi", "Feili", "Sayı", "Bağlayıcını"], correctIndex: 0, xp: 10, explanation: "Təyin əşyanın necə olduğunu göstərir, ona görə ismin yanında işlənir və onu izah edir.", skills: ["az.syn.secondary_parts"] },
            { id: "az4-uzvler-l2-t6", type: "multiple_choice", prompt: "Cümlənin baş üzvləri hansılardır?", options: ["Mübtəda və xəbər", "Tamamlıq və təyin", "Zərflik və təyin", "Heç biri"], correctIndex: 0, xp: 10, explanation: "Mübtəda və xəbər cümlənin özəyini qurur — onlarsız fikir bitmir.", skills: ["az.syn.sentence"] },
            { id: "az4-uzvler-l2-t7", type: "multiple_choice", prompt: "'Aysel məktubu yazdı' cümləsində mübtəda hansıdır?", options: ["Aysel", "məktubu", "yazdı", "heç biri"], correctIndex: 0, xp: 10, explanation: "Yazan kimdir? — Aysel. Deməli mübtəda «Aysel»dir.", skills: ["az.syn.main_parts"] },
            { id: "az4-uzvler-l2-t8", type: "fill_blank", prompt: "Cümlədə iş görəni bildirən üzv ______ adlanır. (bir söz)", accepted: ["mübtəda", "Mübtəda"], xp: 10, explanation: "İşi görəni bildirən baş üzv mübtəda adlanır.", skills: ["az.syn.sentence"] },
            { id: "az4-uzvler-l2-t9", type: "multiple_choice", prompt: "'Uşaqlar həyətdə oynayır' cümləsində zərflik hansıdır?", options: ["həyətdə", "Uşaqlar", "oynayır", "heç biri"], correctIndex: 0, xp: 10, explanation: "«Həyətdə» oynamağın harada olduğunu bildirir — zərflikdir.", skills: ["az.pos.adverb","az.syn.secondary_parts"] },
            { id: "az4-uzvler-l2-t10", type: "multiple_choice", prompt: "Xəbər hansı suala cavab verir?", options: ["Nə edir? Nədir?", "Kim?", "Necə?", "Harada?"], correctIndex: 0, xp: 10, explanation: "Xəbər görülən işi və ya mübtədanın nə olduğunu bildirir — «nə edir? nədir?» suallarına cavab verir.", skills: ["az.syn.main_parts"] },
          ],
          bonusTasks: [
            { id: "az4-uzvler-l2-b1", type: "multiple_choice", prompt: "'Kiçik qardaşım dünən yeni kitab aldı' cümləsində neçə ikinci dərəcəli üzv var?", options: ["Üç: kiçik, dünən, yeni kitab", "Bir", "İki", "Heç biri"], correctIndex: 0, xp: 15, explanation: "Baş üzvlər «qardaşım aldı»dır. Qalanları onları izah edir: «kiçik» (təyin), «dünən» (zərflik), «yeni kitab» (tamamlıq).", skills: ["az.syn.secondary_parts"] },
            { id: "az4-uzvler-l2-b2", type: "multiple_choice", prompt: "Cümlə ən azı hansı üzvlərdən ibarət olmalıdır?", options: ["Mübtəda və xəbər", "Yalnız xəbər", "Tamamlıq və təyin", "Zərflik"], correctIndex: 0, xp: 15, explanation: "Cümlədə ən azı işi görən (mübtəda) və görülən iş (xəbər) olmalıdır ki, fikir bitsin.", skills: ["az.syn.sentence"] },
            { id: "az4-uzvler-l2-b3", type: "multiple_choice", prompt: "'Anam mənə hədiyyə verdi' cümləsində tamamlıq hansıdır?", options: ["hədiyyə", "Anam", "verdi", "mənə hədiyyə verdi"], correctIndex: 0, xp: 15, explanation: "«Hədiyyə» «nəyi?» sualına cavab verir. «Mənə» isə «kimə?» sualına cavab verən başqa tamamlıqdır.", skills: ["az.syn.secondary_parts"] },
            { id: "az4-uzvler-l2-b4", type: "multiple_choice", prompt: "İkinci dərəcəli üzvlər cümlədə nə edir?", options: ["Baş üzvləri izah edir", "Cümləni bitirir", "Sual verir", "Heç nə"], correctIndex: 0, xp: 15, explanation: "İkinci dərəcəli üzvlər baş üzvləri dəqiqləşdirir: nə vaxt, harada, necə, nəyi.", skills: ["az.syn.sentence"] },
          ],
        },
        {
          id: "az4-uzvler-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az4-uzvler-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 5. Söz yaradıcılığı və orfoqrafiya ═══════════════
    {
      id: "az4-soz",
      title: "Söz yaradıcılığı və orfoqrafiya",
      description: "Düzəltmə sözlər, kök və şəkilçi, düzgün yazılış.",
      lessons: [
        {
          id: "az4-soz-l1",
          title: "Düzəltmə sözlər və orfoqrafiya",
          intro: "Şəkilçilərlə yeni sözlər düzəltmək.",
          sections: [
            { heading: "Düzəltmə söz", body: "Kökə sözdüzəldici şəkilçi əlavə edərək yeni söz düzəldirik: iş → işçi, su → sulu, kitab → kitabça." },
            { heading: "Orfoqrafiya", body: "Cümlə böyük hərflə başlayır, nöqtə ilə bitir. Xüsusi isimlər böyük hərflə yazılır." },
          ],
          tasks: [
            { id: "az4-soz-l1-t1", type: "multiple_choice", prompt: "'iş' sözündən hansı düzəltmə söz yaranır?", options: ["işçi", "kitab", "gözəl", "tez"], correctIndex: 0, xp: 10, explanation: "-çi şəkilçisi peşə bildirən yeni söz yaradır: iş → işçi.", skills: ["az.morph.derivation"] },
            { id: "az4-soz-l1-t2", type: "multiple_choice", prompt: "'su' sözündən hansı düzəltmə söz yaranır?", options: ["sulu", "kitab", "ev", "dağ"], correctIndex: 0, xp: 10, explanation: "-lu şəkilçisi nəyəsə malik olmağı bildirir: su → sulu.", skills: ["az.morph.derivation"] },
            { id: "az4-soz-l1-t3", type: "multiple_choice", prompt: "'işçi' sözünün kökü hansıdır?", options: ["iş", "çi", "işç", "i"], correctIndex: 0, xp: 10, explanation: "Sözü hissələrə ayırırıq: iş + çi. Kök iş-dir.", skills: ["az.morph.root"] },
            { id: "az4-soz-l1-t4", type: "multiple_choice", prompt: "'duzlu' sözünün kökü hansıdır?", options: ["duz", "lu", "duzl", "u"], correctIndex: 0, xp: 10, explanation: "Sözü hissələrə ayırırıq: duz + lu. Kök duz-dur.", skills: ["az.morph.root"] },
            { id: "az4-soz-l1-t5", type: "multiple_choice", prompt: "'-çı/-çi' şəkilçisi nə düzəldir?", options: ["peşə/məşğuliyyət bildirən söz", "cəm", "hal", "feil"], correctIndex: 0, xp: 10, explanation: "-çı/-çi şəkilçisi işlə məşğul olan adamı bildirir: balıqçı, meşəçi, işçi.", skills: ["az.morph.root"] },
            { id: "az4-soz-l1-t6", type: "multiple_choice", prompt: "Cümlə hansı hərflə başlayır?", options: ["böyük hərflə", "kiçik hərflə", "rəqəmlə", "fərq etməz"], correctIndex: 0, xp: 10, explanation: "Cümlənin harada başladığı bilinsin deyə ilk hərf böyük yazılır.", skills: ["az.phon.letters"] },
            { id: "az4-soz-l1-t7", type: "multiple_choice", prompt: "Nəqli cümlə hansı işarə ilə bitir?", options: ["nöqtə", "sual işarəsi", "nida işarəsi", "vergül"], correctIndex: 0, xp: 10, explanation: "Nəqli cümlədə fikir bitir, bunu nöqtə göstərir.", skills: ["az.syn.sentence_type"] },
            { id: "az4-soz-l1-t8", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["Bakı", "bakı", "BAKı", "baKı"], correctIndex: 0, xp: 10, explanation: "Bakı xüsusi isimdir: yalnız ilk hərfi böyük yazılır.", skills: ["az.orth.spelling"] },
            { id: "az4-soz-l1-t9", type: "multiple_choice", prompt: "'kitabça' sözünün kökü hansıdır?", options: ["kitab", "ça", "kitabç", "a"], correctIndex: 0, xp: 10, explanation: "Sözü hissələrə ayırırıq: kitab + ça. Kök kitab-dır.", skills: ["az.morph.root"] },
            { id: "az4-soz-l1-t10", type: "multiple_choice", prompt: "'meşəçi' sözü hansı sözdən düzəlib?", options: ["meşə", "çi", "meşəç", "iş"], correctIndex: 0, xp: 10, explanation: "Sözü hissələrə ayırırıq: meşə + çi. Kök meşə-dir.", skills: ["az.morph.derivation"] },
            { id: "az4-soz-l1-t11", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["Nərmin məktəbə getdi.", "nərmin məktəbə getdi.", "Nərmin Məktəbə getdi.", "nərmin Məktəbə Getdi."], correctIndex: 0, xp: 10, explanation: "«Nərmin məktəbə getdi.» — ad və cümlə əvvəli böyük, qalan sözlər kiçik yazılıb.", skills: ["az.orth.spelling"] },
            { id: "az4-soz-l1-t12", type: "multiple_choice", prompt: "'daşlı' sözünün kökü hansıdır?", options: ["daş", "lı", "daşl", "ı"], correctIndex: 0, xp: 10, explanation: "Sözü hissələrə ayırırıq: daş + lı. Kök daş-dır.", skills: ["az.morph.root"] },
            { id: "az4-soz-l1-t13", type: "multiple_choice", prompt: "Xüsusi isimlər (ad, şəhər) necə yazılır?", options: ["böyük hərflə", "kiçik hərflə", "rəqəmlə", "fərq etməz"], correctIndex: 0, xp: 10, explanation: "Xüsusi isim konkret varlığı bildirir, ona görə böyük hərflə yazılır.", skills: ["az.pos.noun","az.orth.capital"] },
            { id: "az4-soz-l1-t14", type: "multiple_choice", prompt: "'balıqçı' sözü hansı sözdən düzəlib?", options: ["balıq", "çı", "balıqç", "iş"], correctIndex: 0, xp: 10, explanation: "Sözü hissələrə ayırırıq: balıq + çı. Kök balıq-dır.", skills: ["az.morph.derivation"] },
            { id: "az4-soz-l1-t15", type: "multiple_choice", prompt: "Sual cümləsi hansı işarə ilə bitir?", options: ["sual işarəsi (?)", "nöqtə", "nida işarəsi", "vergül"], correctIndex: 0, xp: 15, explanation: "Sual cümləsində nəsə soruşulur, ona görə sonda sual işarəsi qoyulur.", skills: ["az.syn.sentence_type"] },
          ],
          bonusTasks: [
            { id: "az4-soz-l1-b1", type: "multiple_choice", prompt: "'-lı/-li/-lu/-lü' şəkilçisi nə bildirir?", options: ["nəyəsə malik olmaq (sulu, daşlı)", "peşə", "cəm", "hal"], correctIndex: 0, xp: 15, explanation: "-lı/-li/-lu/-lü şəkilçisi əşyada nəyinsə olduğunu bildirir: suyu olan → sulu.", skills: ["az.morph.root"] },
            { id: "az4-soz-l1-b2", type: "multiple_choice", prompt: "'gözlük' sözü hansı sözdən düzəlib?", options: ["göz", "lük", "gözl", "ük"], correctIndex: 0, xp: 15, explanation: "Sözü hissələrə ayırırıq: göz + lük. Kök göz-dür.", skills: ["az.morph.derivation"] },
            { id: "az4-soz-l1-b3", type: "multiple_choice", prompt: "Ay, çay, dağ adları necə yazılır?", options: ["böyük hərflə (xüsusi isim)", "kiçik hərflə", "rəqəmlə", "fərq etməz"], correctIndex: 0, xp: 15, explanation: "Ay, çay və dağ adları konkret yerləri bildirir, yəni xüsusi isimdir — böyük yazılır.", skills: ["az.morph.derivation"] },
            { id: "az4-soz-l1-b4", type: "multiple_choice", prompt: "Nida cümləsi hansı işarə ilə bitir?", options: ["nida işarəsi (!)", "nöqtə", "sual", "vergül"], correctIndex: 0, xp: 15, explanation: "Nida cümləsi güclü hiss bildirir, ona görə nida işarəsi ilə bitir.", skills: ["az.syn.sentence_type"] },
            { id: "az4-soz-l1-b5", type: "multiple_choice", prompt: "'yağışlı' sözünün kökü hansıdır?", options: ["yağış", "lı", "yağışl", "ı"], correctIndex: 0, xp: 15, explanation: "Sözü hissələrə ayırırıq: yağış + lı. Kök yağış-dır.", skills: ["az.morph.root"] },
          ],
        },
        {
          id: "az4-soz-l2",
          title: "Böyük hərf və durğu işarələri",
          intro: "Yazıda əsas orfoqrafiya qaydaları.",
          sections: [
            { heading: "Böyük hərf", body: "Cümlənin əvvəlində, insan/şəhər/ölkə adlarında, kitab və qəzet adlarında böyük hərf yazılır." },
            { heading: "Vergül", body: "Sadalanan sözlər arasında vergül qoyulur: 'Çantada kitab, dəftər, qələm var.'" },
          ],
          tasks: [
            { id: "az4-soz-l2-t1", type: "multiple_choice", prompt: "Cümlə hansı hərflə başlayır?", options: ["Böyük", "Kiçik", "Fərqi yoxdur", "Rəqəmlə"], correctIndex: 0, xp: 10, explanation: "Cümlənin harada başladığı bilinsin deyə ilk hərf böyük yazılır.", skills: ["az.phon.letters"] },
            { id: "az4-soz-l2-t2", type: "multiple_choice", prompt: "Hansı cümlə düzgün yazılıb?", options: ["Mən Bakıda yaşayıram.", "mən bakıda yaşayıram.", "Mən bakıda yaşayıram.", "mən Bakıda yaşayıram."], correctIndex: 0, xp: 10, explanation: "«Mən» cümlənin ilk sözüdür, «Bakı» isə xüsusi isimdir — hər ikisi böyük yazılır.", skills: ["az.syn.sentence","az.orth.spelling"] },
            { id: "az4-soz-l2-t3", type: "multiple_choice", prompt: "Sadalanan sözlər arasında hansı işarə qoyulur?", options: ["Vergül", "Nöqtə", "Sual işarəsi", "Heç bir"], correctIndex: 0, xp: 10, explanation: "Sadalanan sözlər bir-birindən vergüllə ayrılır: kitab, dəftər, qələm.", skills: ["az.morph.derivation"] },
            { id: "az4-soz-l2-t4", type: "multiple_choice", prompt: "'Çantada kitab dəftər qələm var' — nə çatışmır?", options: ["Vergüllər", "Nöqtə", "Böyük hərf", "Heç nə"], correctIndex: 0, xp: 10, explanation: "Kitab, dəftər və qələm sadalanır, amma aralarında vergül yoxdur.", skills: ["az.morph.derivation"] },
            { id: "az4-soz-l2-t5", type: "multiple_choice", prompt: "Ölkə adları necə yazılır?", options: ["Böyük hərflə", "Kiçik hərflə", "Dırnaqda", "Fərqi yoxdur"], correctIndex: 0, xp: 10, explanation: "Ölkə adları xüsusi isimdir, ona görə böyük hərflə yazılır.", skills: ["az.morph.derivation"] },
            { id: "az4-soz-l2-t6", type: "multiple_choice", prompt: "Kitab adları necə yazılır?", options: ["Böyük hərf və dırnaqda", "Kiçik hərflə", "Yalnız böyük hərflə", "Mötərizədə"], correctIndex: 0, xp: 10, explanation: "Kitab adı xüsusi addır: böyük hərflə başlayır və dırnaq içinə alınır.", skills: ["az.morph.derivation"] },
            { id: "az4-soz-l2-t7", type: "multiple_choice", prompt: "Nəqli cümlənin sonunda hansı işarə qoyulur?", options: [".", "?", "!", ","], correctIndex: 0, xp: 10, explanation: "Nəqli cümlədə fikir bitir, bunu nöqtə göstərir.", skills: ["az.syn.sentence_type"] },
            { id: "az4-soz-l2-t8", type: "multiple_choice", prompt: "Müraciət sözündən sonra hansı işarə qoyulur?", options: ["Vergül", "Nöqtə", "Defis", "Heç bir"], correctIndex: 0, xp: 10, explanation: "Müraciət cümlənin qalan hissəsindən vergüllə ayrılır: «Aysel, bura gəl».", skills: ["az.morph.derivation"] },
            { id: "az4-soz-l2-t9", type: "fill_blank", prompt: "Cümlənin sonunda ______ qoyulur (nəqli cümlədə, işarəni yaz).", accepted: [".", "nöqtə", "Nöqtə"], xp: 10, explanation: "Nəqli cümlədə fikrin bitdiyini nöqtə göstərir.", skills: ["az.syn.sentence_type"] },
            { id: "az4-soz-l2-t10", type: "multiple_choice", prompt: "'aysel və nihad gəldilər.' — burada neçə səhv var?", options: ["İki böyük hərf səhvi", "Bir", "Üç", "Səhv yoxdur"], correctIndex: 0, xp: 10, explanation: "İki səhv var: «aysel» və «nihad» insan adıdır, hər ikisi böyük hərflə yazılmalıdır.", skills: ["az.morph.derivation"] },
          ],
          bonusTasks: [
            { id: "az4-soz-l2-b1", type: "multiple_choice", prompt: "Hansı cümlə tam düzgündür?", options: ["Bakı, Gəncə və Şəki gözəl şəhərlərdir.", "bakı, gəncə və şəki gözəl şəhərlərdir.", "Bakı Gəncə və Şəki gözəl şəhərlərdir", "Bakı, gəncə və Şəki gözəl şəhərlərdir."], correctIndex: 0, xp: 15, explanation: "Üç şəhər adı da böyük yazılıb, sadalama vergüllə ayrılıb və cümlə nöqtə ilə bitib.", skills: ["az.syn.sentence"] },
            { id: "az4-soz-l2-b2", type: "multiple_choice", prompt: "Dialoqda replikanın əvvəlində hansı işarə qoyulur?", options: ["Tire (—)", "Vergül", "Nöqtə", "Sual işarəsi"], correctIndex: 0, xp: 15, explanation: "Dialoqda hər replikanın kimə aid olduğu bilinsin deyə əvvəlinə tire qoyulur.", skills: ["az.morph.derivation"] },
            { id: "az4-soz-l2-b3", type: "multiple_choice", prompt: "'Salam, Aysel!' cümləsində vergül niyə qoyulub?", options: ["Müraciəti ayırmaq üçün", "Sadalama üçün", "Səhvdir", "Uzun olduğu üçün"], correctIndex: 0, xp: 15, explanation: "«Aysel» müraciətdir — kimə deyildiyini bildirir və cümlədən vergüllə ayrılır.", skills: ["az.syn.sentence","az.orth.punctuation","az.text.etiquette"] },
            { id: "az4-soz-l2-b4", type: "multiple_choice", prompt: "Bayram adları (məs. Novruz) necə yazılır?", options: ["Böyük hərflə", "Kiçik hərflə", "Dırnaqda", "Fərqi yoxdur"], correctIndex: 0, xp: 15, explanation: "Bayram adları xüsusi addır, ona görə böyük hərflə yazılır: Novruz, Ramazan.", skills: ["az.morph.derivation"] },
          ],
        },
        {
          id: "az4-soz-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az4-soz-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 6. Mətn və nitq ═══════════════
    {
      id: "az4-metn",
      title: "Mətn və nitq",
      description: "Mətn, başlıq, abzas və nitq mədəniyyəti.",
      lessons: [
        {
          id: "az4-metn-l1",
          title: "Mətn və nitq mədəniyyəti",
          intro: "Mətn cümlələrdən ibarətdir; nəzakətli danışıq.",
          sections: [
            { heading: "Mətn", body: "Bir-biri ilə bağlı cümlələrin toplusu mətndir. Mətnin başlığı və abzasları olur. Başlıq mətnin adıdır." },
            { heading: "Nitq mədəniyyəti", body: "Nəzakətli sözlər: sağ ol, zəhmət olmasa, buyurun, üzr istəyirəm. Böyüklərlə 'Siz' deyə danışmaq nəzakətlidir." },
          ],
          tasks: [
            { id: "az4-metn-l1-t1", type: "multiple_choice", prompt: "Mətn nədən ibarətdir?", options: ["bağlı cümlələrdən", "yalnız sözlərdən", "hərflərdən", "hecalardan"], correctIndex: 0, xp: 10, explanation: "Mətn mənaca bir-biri ilə bağlı cümlələrdən qurulur.", skills: ["az.text.structure"] },
            { id: "az4-metn-l1-t2", type: "multiple_choice", prompt: "Mətnin adı necə adlanır?", options: ["başlıq", "abzas", "cümlə", "söz"], correctIndex: 0, xp: 10, explanation: "Mətnin nədən bəhs etdiyini qısaca bildirən ad başlıq adlanır.", skills: ["az.text.structure"] },
            { id: "az4-metn-l1-t3", type: "multiple_choice", prompt: "Mətnin hissələri (paraqrafları) necə adlanır?", options: ["abzas", "başlıq", "cümlə", "heca"], correctIndex: 0, xp: 10, explanation: "Yeni sətirdən başlayan hissə abzas adlanır — hər abzas ayrı bir fikri açır.", skills: ["az.text.structure"] },
            { id: "az4-metn-l1-t4", type: "multiple_choice", prompt: "Kimsə sənə kömək etdi. Nə deyərsən?", options: ["Sağ olun / təşəkkür", "Get", "Yox", "Dur"], correctIndex: 0, xp: 10, explanation: "Kömək edənə minnətdarlıq bildiririk: «sağ olun», «təşəkkür edirəm».", skills: ["az.text.structure"] },
            { id: "az4-metn-l1-t5", type: "multiple_choice", prompt: "Nəsə xahiş edəndə hansı nəzakət sözünü deyirik?", options: ["zəhmət olmasa", "yox", "get", "dur"], correctIndex: 0, xp: 10, explanation: "«Zəhmət olmasa» xahişi yumşaldır və qarşıdakına hörmət göstərir.", skills: ["az.text.etiquette"] },
            { id: "az4-metn-l1-t6", type: "multiple_choice", prompt: "Böyüklərlə necə danışmaq nəzakətlidir?", options: ["'Siz' deyə", "'sən' deyə qışqıraraq", "gülərək", "susaraq"], correctIndex: 0, xp: 10, explanation: "Böyüklərə hörmət əlaməti olaraq «Siz» deyə müraciət edilir.", skills: ["az.text.etiquette"] },
            { id: "az4-metn-l1-t7", type: "multiple_choice", prompt: "Səhvə görə nə deyirik?", options: ["üzr istəyirəm", "sağ ol", "buyurun", "salam"], correctIndex: 0, xp: 10, explanation: "Səhv edəndə üzr istəyirik: «üzr istəyirəm», «bağışlayın».", skills: ["az.text.structure"] },
            { id: "az4-metn-l1-t8", type: "multiple_choice", prompt: "Mətndə cümlələr necə olmalıdır?", options: ["bir-biri ilə bağlı", "təsadüfi", "bağsız", "eyni"], correctIndex: 0, xp: 10, explanation: "Mətndə cümlələr eyni mövzuya xidmət etməlidir — yoxsa mətn deyil, sadəcə cümlələr yığını olar.", skills: ["az.syn.sentence","az.text.structure"] },
            { id: "az4-metn-l1-t9", type: "multiple_choice", prompt: "Başlıq mətnin nəyini bildirir?", options: ["mövzusunu/adını", "sonunu", "səhvini", "uzunluğunu"], correctIndex: 0, xp: 10, explanation: "Başlıq mətnin nədən bəhs etdiyini, yəni mövzusunu qısaca bildirir.", skills: ["az.text.structure"] },
            { id: "az4-metn-l1-t10", type: "multiple_choice", prompt: "Kiməsə nəyisə verəndə nə deyirik?", options: ["buyurun", "yox", "get", "dur"], correctIndex: 0, xp: 10, explanation: "Nəyisə uzadanda, təklif edəndə «buyurun» deyilir.", skills: ["az.text.structure"] },
            { id: "az4-metn-l1-t11", type: "multiple_choice", prompt: "Görüşəndə nə deyirik?", options: ["salam", "əlvida", "yox", "get"], correctIndex: 0, xp: 10, explanation: "Görüşərkən salamlaşırıq: «salam».", skills: ["az.text.structure"] },
            { id: "az4-metn-l1-t12", type: "multiple_choice", prompt: "Ayrılanda nə deyirik?", options: ["sağ ol / əlvida", "salam", "buyurun", "üzr istəyirəm"], correctIndex: 0, xp: 10, explanation: "Ayrılarkən vidalaşırıq: «sağ ol», «əlvida».", skills: ["az.text.structure"] },
            { id: "az4-metn-l1-t13", type: "multiple_choice", prompt: "Mətn neçə cümlədən ibarət ola bilər?", options: ["bir neçə (çox)", "yalnız bir", "yalnız iki", "heç"], correctIndex: 0, xp: 10, explanation: "Mətn bir neçə cümlədən qurulur — bir cümlə tək başına mətn sayılmır.", skills: ["az.syn.sentence","az.text.structure"] },
            { id: "az4-metn-l1-t14", type: "multiple_choice", prompt: "Nəzakətli danışıq nədir?", options: ["hörmətlə, nəzakət sözləri ilə", "qışqıraraq", "kobud", "susaraq"], correctIndex: 0, xp: 10, explanation: "Nəzakətli danışıq səs ucaltmadan, hörmətlə və nəzakət sözləri işlədərək danışmaqdır.", skills: ["az.text.etiquette"] },
            { id: "az4-metn-l1-t15", type: "multiple_choice", prompt: "Aşağıdakılardan hansı nəzakət sözüdür?", options: ["təşəkkür edirəm", "get", "sus", "yox"], correctIndex: 0, xp: 15, explanation: "«Təşəkkür edirəm» minnətdarlıq bildirir. Sus, get, yox isə kobud səslənir.", skills: ["az.text.etiquette"] },
          ],
          bonusTasks: [
            { id: "az4-metn-l1-b1", type: "multiple_choice", prompt: "Mətnin əvvəlində nə olur?", options: ["başlıq", "nöqtə", "abzas boşluğu yalnız", "imza"], correctIndex: 0, xp: 15, explanation: "Mətn başlıqla açılır — oxucu ilk növbədə mövzunu görür.", skills: ["az.text.structure"] },
            { id: "az4-metn-l1-b2", type: "multiple_choice", prompt: "Yeni fikrə keçəndə mətndə nə edirik?", options: ["yeni abzasa başlayırıq", "böyük hərf yazmırıq", "nöqtə qoymuruq", "heç nə"], correctIndex: 0, xp: 15, explanation: "Hər yeni fikir ayrıca abzasda verilir ki, mətn aydın oxunsun.", skills: ["az.text.structure"] },
            { id: "az4-metn-l1-b3", type: "multiple_choice", prompt: "Telefonda danışanda əvvəlcə nə deyirik?", options: ["salam / alo", "get", "yox", "dur"], correctIndex: 0, xp: 15, explanation: "Telefonda əvvəlcə salamlaşırıq: «salam» və ya «alo».", skills: ["az.text.structure"] },
            { id: "az4-metn-l1-b4", type: "multiple_choice", prompt: "Mətnin növləri hansılardır (ümumi)?", options: ["nağıl, hekayə, şeir və s.", "yalnız şeir", "yalnız cümlə", "yalnız söz"], correctIndex: 0, xp: 15, explanation: "Mətnlər məzmununa görə müxtəlif olur: nağıl, hekayə, şeir, məqalə və s.", skills: ["az.text.structure"] },
            { id: "az4-metn-l1-b5", type: "multiple_choice", prompt: "Müəllimə müraciət edəndə necə danışırıq?", options: ["nəzakətlə, 'Siz' deyə", "kobud", "qışqıraraq", "susaraq"], correctIndex: 0, xp: 15, explanation: "Müəllim böyükdür və hörmət tələb edir, ona görə «Siz» deyə, nəzakətlə müraciət edilir.", skills: ["az.text.etiquette"] },
          ],
        },
        {
          id: "az4-metn-l2",
          title: "Mətnin hissələri və planı",
          intro: "Hər mətnin başlanğıcı, əsas hissəsi və sonu var.",
          sections: [
            { heading: "Üç hissə", body: "GİRİŞ mövzunu açır, ƏSAS HİSSƏ hadisəni danışır, NƏTİCƏ yekun fikri verir." },
            { heading: "Plan", body: "Mətni yazmadan əvvəl plan qurmaq faydalıdır: hər hissəyə bir cümlə ilə ad ver." },
          ],
          tasks: [
            { id: "az4-metn-l2-t1", type: "multiple_choice", prompt: "Mətn neçə əsas hissədən ibarətdir?", options: ["Üç", "İki", "Dörd", "Bir"], correctIndex: 0, xp: 10, explanation: "Mətn giriş, əsas hissə və nəticədən qurulur — cəmi üç hissə.", skills: ["az.text.structure"] },
            { id: "az4-metn-l2-t2", type: "multiple_choice", prompt: "Mətnin birinci hissəsi necə adlanır?", options: ["Giriş", "Nəticə", "Əsas hissə", "Başlıq"], correctIndex: 0, xp: 10, explanation: "Mətnin əvvəlində mövzu təqdim olunur — bu hissə giriş adlanır.", skills: ["az.phon.letters","az.text.structure"] },
            { id: "az4-metn-l2-t3", type: "multiple_choice", prompt: "Mətnin son hissəsi necə adlanır?", options: ["Nəticə", "Giriş", "Əsas hissə", "Plan"], correctIndex: 0, xp: 10, explanation: "Mətnin sonunda fikir yekunlaşdırılır — bu hissə nəticə adlanır.", skills: ["az.phon.letters","az.text.structure"] },
            { id: "az4-metn-l2-t4", type: "multiple_choice", prompt: "Başlıq nə üçündür?", options: ["Mətnin mövzusunu bildirmək üçün", "Yer doldurmaq üçün", "Uzunluq üçün", "Səbəbi yoxdur"], correctIndex: 0, xp: 10, explanation: "Başlıq oxucuya mətnin nədən bəhs etdiyini əvvəlcədən bildirir.", skills: ["az.text.structure"] },
            { id: "az4-metn-l2-t5", type: "multiple_choice", prompt: "Plan nə vaxt qurulur?", options: ["Yazmadan əvvəl", "Yazandan sonra", "Heç vaxt", "Yazı zamanı"], correctIndex: 0, xp: 10, explanation: "Plan fikirlərin sırasını əvvəlcədən müəyyən edir, ona görə yazmadan əvvəl qurulur.", skills: ["az.text.structure"] },
            { id: "az4-metn-l2-t6", type: "multiple_choice", prompt: "Abzas nədir?", options: ["Mətnin yeni sətirdən başlayan hissəsi", "Bir cümlə", "Bir söz", "Durğu işarəsi"], correctIndex: 0, xp: 10, explanation: "Abzas yeni sətirdən başlayan hissədir və mətndə ayrı bir fikri açır.", skills: ["az.text.structure"] },
            { id: "az4-metn-l2-t7", type: "multiple_choice", prompt: "Mətn nədir?", options: ["Mənaca bağlı cümlələr", "Bir cümlə", "Bir söz", "Sözlər siyahısı"], correctIndex: 0, xp: 10, explanation: "Mətn təsadüfi cümlələr yığını deyil — cümlələr mənaca bir-birinə bağlı olmalıdır.", skills: ["az.text.structure"] },
            { id: "az4-metn-l2-t8", type: "fill_blank", prompt: "Mətnin ilk hissəsi ______ adlanır. (bir söz)", accepted: ["giriş", "Giriş"], xp: 10, explanation: "Mətnin mövzunu təqdim edən ilk hissəsi giriş adlanır.", skills: ["az.phon.letters","az.text.structure"] },
            { id: "az4-metn-l2-t9", type: "multiple_choice", prompt: "Nəqli mətn nəyi danışır?", options: ["Hadisəni", "Əşyanın görünüşünü", "Fikri sübut edir", "Heç nəyi"], correctIndex: 0, xp: 10, explanation: "Nəqli mətn baş verən hadisəni ardıcıllıqla danışır.", skills: ["az.syn.sentence_type","az.text.structure"] },
            { id: "az4-metn-l2-t10", type: "multiple_choice", prompt: "Təsviri mətn nəyi göstərir?", options: ["Əşyanın və ya təbiətin görünüşünü", "Hadisəni", "Sübutu", "Sualı"], correctIndex: 0, xp: 10, explanation: "Təsviri mətn əşyanın, insanın və ya təbiətin necə göründüyünü canlandırır.", skills: ["az.text.structure"] },
          ],
          bonusTasks: [
            { id: "az4-metn-l2-b1", type: "multiple_choice", prompt: "Yaxşı başlıq necə olmalıdır?", options: ["Qısa və mövzunu əks etdirən", "Uzun və çətin", "Mətnin surəti", "Sual olmalı"], correctIndex: 0, xp: 15, explanation: "Başlıq bir baxışda anlaşılmalıdır: qısa olmalı və mövzunu düzgün əks etdirməlidir.", skills: ["az.text.structure"] },
            { id: "az4-metn-l2-b2", type: "multiple_choice", prompt: "Mühakimə mətni nə edir?", options: ["Fikri əsaslandırır", "Hadisə danışır", "Görünüşü təsvir edir", "Sual verir"], correctIndex: 0, xp: 15, explanation: "Mühakimə mətnində fikir irəli sürülür və dəlillərlə əsaslandırılır.", skills: ["az.text.structure"] },
            { id: "az4-metn-l2-b3", type: "multiple_choice", prompt: "Mətnin əsas fikri harada olur?", options: ["Adətən nəticədə və ya başlıqda", "Yalnız birinci sözdə", "Yalnız sonuncu sözdə", "Heç yerdə"], correctIndex: 0, xp: 15, explanation: "Əsas fikir çox vaxt başlıqda işarə olunur və nəticədə açıq şəkildə yekunlaşdırılır.", skills: ["az.text.structure"] },
            { id: "az4-metn-l2-b4", type: "multiple_choice", prompt: "Niyə abzaslara bölürük?", options: ["Oxunuşu asanlaşdırmaq üçün", "Yer doldurmaq üçün", "Qayda tələb edir deyə", "Səbəbi yoxdur"], correctIndex: 0, xp: 15, explanation: "Abzaslar fikirləri ayırır — göz yorulmur və oxucu hər fikri ayrıca izləyə bilir.", skills: ["az.text.structure"] },
          ],
        },
        {
          id: "az4-metn-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az4-metn-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
  ],
};
