// Azərbaycan dili — 6-cı sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Fonetika  2) Leksika  3) Sözün tərkibi və söz yaradıcılığı
// 4) Nitq hissələri I (isim, sifət, say, əvəzlik)  5) Nitq hissələri II (feil, zərf)
// 6) Orfoqrafiya, durğu işarələri və mətn.
// Hər dərs: 15 əsas + 5 bonus. Mərhələli doldurulur. id prefiksi az6-*.

import type { Subject } from "../types";

export const azerbaijani6: Subject = {
  slug: "azerbaycan-dili-6",
  name: "Azərbaycan dili",
  grade: 6,
  icon: "A",
  color: "rose",
  units: [
    // ═══════════════ 1. Fonetika ═══════════════
    {
      id: "az6-fonetika",
      title: "Fonetika",
      description:
        "Səs və hərf, saitlər və samitlər, ahəng qanunu, heca, vurğu və fonetik təhlil.",
      lessons: [
        {
          id: "az6-fon-l1",
          title: "Səs və hərf. Saitlər və samitlər",
          intro: "Səs və hərfin fərqi, saitlərin və samitlərin təsnifatı.",
          sections: [
            { heading: "Səs və hərf", body: "Tələffüz etdiyimiz — səs, yazıda onu göstərən işarə — hərfdir. Azərbaycan əlifbasında 32 hərf var." },
            { heading: "Saitlər (9)", body: "a, ı, o, u — qalın saitlər; e, ə, i, ö, ü — incə saitlər. Dodaqlanan: o, u, ö, ü; dodaqlanmayan: a, ı, e, ə, i." },
            { heading: "Samitlər", body: "Kar samitlər: p, f, t, s, ş, ç, k, x, h. Cingiltili samitlər: b, v, d, z, j, c, q, g, ğ və s. Kar-cingiltili cütlər: p-b, t-d, k-q." },
          ],
          tasks: [
            { id: "az6-fon-l1-t1", type: "multiple_choice", prompt: "Azərbaycan əlifbasında neçə hərf var?", options: ["29", "32", "33", "26"], correctIndex: 1, xp: 10, skills: ["az.phon.alphabet"] },
            { id: "az6-fon-l1-t2", type: "numeric", prompt: "Azərbaycan dilində neçə sait var?", answer: 9, xp: 10, skills: ["az.phon.vowels"] },
            { id: "az6-fon-l1-t3", type: "multiple_choice", prompt: "Hansı qalın saitdir?", options: ["ə", "e", "o", "i"], correctIndex: 2, xp: 10, skills: ["az.phon.vowels"] },
            { id: "az6-fon-l1-t4", type: "multiple_choice", prompt: "Hansı incə saitdir?", options: ["a", "ı", "ü", "u"], correctIndex: 2, xp: 10, skills: ["az.phon.vowels"] },
            { id: "az6-fon-l1-t5", type: "multiple_choice", prompt: "Hansı dodaqlanan saitdir?", options: ["a", "ö", "e", "ı"], correctIndex: 1, xp: 10, skills: ["az.phon.vowels"] },
            { id: "az6-fon-l1-t6", type: "multiple_choice", prompt: "'p' səsi necə samitdir?", options: ["kar", "cingiltili", "sait", "qoşa"], correctIndex: 0, xp: 10, skills: ["az.phon.consonants"] },
            { id: "az6-fon-l1-t7", type: "multiple_choice", prompt: "'b' səsi necə samitdir?", options: ["cingiltili", "kar", "sait", "yarımsait"], correctIndex: 0, xp: 10, skills: ["az.phon.consonants"] },
            { id: "az6-fon-l1-t8", type: "multiple_choice", prompt: "'t' samitinin cingiltili cütü hansıdır?", options: ["d", "s", "k", "p"], correctIndex: 0, xp: 10, skills: ["az.phon.consonants"] },
            { id: "az6-fon-l1-t9", type: "multiple_choice", prompt: "'k' samitinin cingiltili cütü hansıdır?", options: ["q", "g", "x", "h"], correctIndex: 0, xp: 10, skills: ["az.phon.consonants"] },
            { id: "az6-fon-l1-t10", type: "fill_blank", prompt: "Yazıda səsi göstərən işarə necə adlanır?", accepted: ["hərf", "herf"], xp: 10, skills: ["az.phon.letters"] },
            { id: "az6-fon-l1-t11", type: "multiple_choice", prompt: "Hansı dodaqlanmayan saitdir?", options: ["o", "u", "a", "ö"], correctIndex: 2, xp: 10, skills: ["az.phon.vowels"] },
            { id: "az6-fon-l1-t12", type: "multiple_choice", prompt: "'s' səsi necə samitdir?", options: ["kar", "cingiltili", "sait", "qoşa"], correctIndex: 0, xp: 10, skills: ["az.phon.consonants"] },
            { id: "az6-fon-l1-t13", type: "numeric", prompt: "'a, ı, o, u' — neçə qalın saitdir?", answer: 4, xp: 10, skills: ["az.phon.vowels"] },
            { id: "az6-fon-l1-t14", type: "numeric", prompt: "'e, ə, i, ö, ü' — neçə incə saitdir?", answer: 5, xp: 10, skills: ["az.phon.vowels"] },
            { id: "az6-fon-l1-t15", type: "multiple_choice", prompt: "'q' səsi necə samitdir?", options: ["cingiltili", "kar", "sait", "yarımsait"], correctIndex: 0, xp: 15, skills: ["az.phon.consonants"] },
          ],
          bonusTasks: [
            { id: "az6-fon-l1-b1", type: "multiple_choice", prompt: "Hansı sırada yalnız qalın saitlər var?", options: ["a, ı, o, u", "e, ə, i", "a, e, o", "ü, ö, u"], correctIndex: 0, xp: 15, skills: ["az.phon.vowels"] },
            { id: "az6-fon-l1-b2", type: "multiple_choice", prompt: "'ç' samitinin kar/cingiltili qarşılığı 'c'-dir. 'ç' necədir?", options: ["kar", "cingiltili", "sait", "qoşa"], correctIndex: 0, xp: 15, skills: ["az.phon.consonants"] },
            { id: "az6-fon-l1-b3", type: "multiple_choice", prompt: "Hansı sırada yalnız incə saitlər var?", options: ["e, ə, i, ö, ü", "a, ı, o, u", "a, e, i", "o, u, ü"], correctIndex: 0, xp: 15, skills: ["az.phon.vowels"] },
            { id: "az6-fon-l1-b4", type: "multiple_choice", prompt: "'z' səsi necə samitdir?", options: ["cingiltili", "kar", "sait", "yarımsait"], correctIndex: 0, xp: 15, skills: ["az.phon.consonants"] },
            { id: "az6-fon-l1-b5", type: "fill_blank", prompt: "Tələffüz etdiyimiz — ___-dir (hərfin qarşılığı).", accepted: ["səs", "ses"], xp: 15, skills: ["az.phon.letters"] },
          ],
        },
        {
          id: "az6-fon-l2",
          title: "Ahəng qanunu",
          intro: "Sözdə saitlərin bir-birinə uyğunlaşması qanunu.",
          sections: [
            { heading: "Ahəng qanunu nədir?", body: "Sözdə saitlərin qalınlıq-incəliyə görə bir-birinə uyğunlaşmasına ahəng qanunu deyilir: kitablar (a-a-a — qalın), evlər (e-ə — incə)." },
            { heading: "Damaq ahəngi", body: "Qalın saitdən sonra qalın, incə saitdən sonra incə sait gəlir: yollar (qalın), gəlirlər (incə)." },
            { heading: "Pozulma", body: "Bəzi sözlərdə (alınma sözlər) ahəng qanunu pozulur: kitab, məktəb, tələbə. Şəkilçilər son saitə uyğunlaşır." },
          ],
          tasks: [
            { id: "az6-fon-l2-t1", type: "multiple_choice", prompt: "Sözdə saitlərin bir-birinə uyğunlaşmasına nə deyilir?", options: ["ahəng qanunu", "vurğu", "heca", "səsartımı"], correctIndex: 0, xp: 10, skills: ["az.phon.vowels"] },
            { id: "az6-fon-l2-t2", type: "multiple_choice", prompt: "'yollar' sözündə saitlər necədir?", options: ["qalın", "incə", "qarışıq", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.phon.vowels"] },
            { id: "az6-fon-l2-t3", type: "multiple_choice", prompt: "'evlər' sözündə saitlər necədir?", options: ["incə", "qalın", "qarışıq", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.phon.vowels"] },
            { id: "az6-fon-l2-t4", type: "multiple_choice", prompt: "Qalın saitdən sonra hansı şəkilçi gəlir?", options: ["qalın saitli", "incə saitli", "samitli", "fərqi yoxdur"], correctIndex: 0, xp: 10, skills: ["az.phon.vowels","az.morph.root"] },
            { id: "az6-fon-l2-t5", type: "multiple_choice", prompt: "Hansı sözdə ahəng qanunu var (qalın)?", options: ["qapılar", "evlər", "gəmilər", "üzüklər"], correctIndex: 0, xp: 10, skills: ["az.phon.harmony"] },
            { id: "az6-fon-l2-t6", type: "multiple_choice", prompt: "Hansı sözdə ahəng qanunu pozulub (alınma söz)?", options: ["kitab", "yollar", "daşlar", "qollar"], correctIndex: 0, xp: 10, skills: ["az.phon.harmony","az.lex.origin"] },
            { id: "az6-fon-l2-t7", type: "multiple_choice", prompt: "'kitab' sözünə cəm şəkilçisi hansı formada gələr?", options: ["-lar", "-lər", "hər ikisi", "gəlməz"], correctIndex: 0, xp: 10, skills: ["az.morph.root","az.pos.noun_possess"] },
            { id: "az6-fon-l2-t8", type: "multiple_choice", prompt: "'ev' sözünə cəm şəkilçisi hansı formada gələr?", options: ["-lər", "-lar", "hər ikisi", "gəlməz"], correctIndex: 0, xp: 10, skills: ["az.morph.root","az.pos.noun_possess"] },
            { id: "az6-fon-l2-t9", type: "multiple_choice", prompt: "Hansı söz incə saitlidir?", options: ["üzüm", "qapı", "yol", "daş"], correctIndex: 0, xp: 10, skills: ["az.phon.vowels"] },
            { id: "az6-fon-l2-t10", type: "multiple_choice", prompt: "Hansı söz qalın saitlidir?", options: ["armud", "gəl", "ev", "il"], correctIndex: 0, xp: 10, skills: ["az.phon.vowels"] },
            { id: "az6-fon-l2-t11", type: "fill_blank", prompt: "'qız' sözünə cəm şəkilçisi: qız___", accepted: ["lar"], xp: 10, skills: ["az.morph.root","az.pos.noun_possess"] },
            { id: "az6-fon-l2-t12", type: "fill_blank", prompt: "'gül' sözünə cəm şəkilçisi: gül___", accepted: ["lər"], xp: 10, skills: ["az.morph.root","az.pos.noun_possess"] },
            { id: "az6-fon-l2-t13", type: "multiple_choice", prompt: "Ahəng qanununa görə şəkilçi nəyə uyğunlaşır?", options: ["son saitə", "ilk saitə", "samitə", "vurğuya"], correctIndex: 0, xp: 10, skills: ["az.phon.harmony","az.morph.root"] },
            { id: "az6-fon-l2-t14", type: "multiple_choice", prompt: "Hansı sözdə ahəng qanunu pozulub?", options: ["tələbə", "sular", "quşlar", "yollar"], correctIndex: 0, xp: 10, skills: ["az.phon.harmony"] },
            { id: "az6-fon-l2-t15", type: "fill_blank", prompt: "'at' sözünə cəm şəkilçisi: at___", accepted: ["lar"], xp: 15, skills: ["az.morph.root","az.pos.noun_possess"] },
          ],
          bonusTasks: [
            { id: "az6-fon-l2-b1", type: "multiple_choice", prompt: "'məktəb' sözündə ahəng qanunu:", options: ["pozulub (alınma)", "qalın", "incə", "yoxdur"], correctIndex: 0, xp: 15, skills: ["az.phon.harmony"] },
            { id: "az6-fon-l2-b2", type: "fill_blank", prompt: "'kitab' sözünə yer şəkilçisi: kitab___ (da/də)", accepted: ["da"], xp: 15, skills: ["az.morph.root"] },
            { id: "az6-fon-l2-b3", type: "multiple_choice", prompt: "Hansı söz tam incə saitlidir?", options: ["sevgi", "qapı", "ata", "yol"], correctIndex: 0, xp: 15, skills: ["az.phon.vowels"] },
            { id: "az6-fon-l2-b4", type: "fill_blank", prompt: "'ürək' sözünə cəm şəkilçisi: ürək___", accepted: ["lər"], xp: 15, skills: ["az.morph.root","az.pos.noun_possess"] },
            { id: "az6-fon-l2-b5", type: "multiple_choice", prompt: "Ahəng qanunu əsasən nəyə əsaslanır?", options: ["saitlərin qalın-incəliyinə", "samitlərə", "vurğuya", "heca sayına"], correctIndex: 0, xp: 15, skills: ["az.phon.harmony"] },
          ],
        },
        {
          id: "az6-fonetika-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az6-fon-l3",
          title: "Heca, vurğu və böyük hərf",
          intro: "Sözü hecalara bölmək, vurğunu təyin etmək və böyük hərf qaydaları.",
          sections: [
            { heading: "Heca", body: "Söz saitlərin sayı qədər hecaya bölünür: ki-tab (2 heca), mə-ni-si (3 heca). Hecasız söz olmur." },
            { heading: "Vurğu", body: "Sözdə bir hecanın digərlərindən qüvvətli deyilməsi vurğudur. Azərbaycan dilində vurğu adətən son hecaya düşür: kitáb, evlér." },
            { heading: "Böyük hərf", body: "Cümlənin əvvəli, xüsusi isimlər (adlar, şəhərlər, ölkələr) böyük hərflə yazılır: Bakı, Azərbaycan, Nizami." },
          ],
          tasks: [
            { id: "az6-fon-l3-t1", type: "numeric", prompt: "'kitab' sözündə neçə heca var?", answer: 2, xp: 10, skills: ["az.phon.syllable"] },
            { id: "az6-fon-l3-t2", type: "numeric", prompt: "'məktəb' sözündə neçə heca var?", answer: 2, xp: 10, skills: ["az.phon.syllable"] },
            { id: "az6-fon-l3-t3", type: "numeric", prompt: "'Azərbaycan' sözündə neçə heca var?", answer: 4, xp: 10, skills: ["az.phon.syllable"] },
            { id: "az6-fon-l3-t4", type: "multiple_choice", prompt: "Söz neçə hecaya bölünür?", options: ["saitlərin sayı qədər", "samitlərin sayı qədər", "hərflərin sayı qədər", "həmişə 2"], correctIndex: 0, xp: 10, skills: ["az.phon.syllable"] },
            { id: "az6-fon-l3-t5", type: "multiple_choice", prompt: "Azərbaycan dilində vurğu adətən hansı hecaya düşür?", options: ["son", "ilk", "orta", "heç birinə"], correctIndex: 0, xp: 10, skills: ["az.phon.syllable","az.phon.stress"] },
            { id: "az6-fon-l3-t6", type: "numeric", prompt: "'alma' sözündə neçə heca var?", answer: 2, xp: 10, skills: ["az.phon.syllable"] },
            { id: "az6-fon-l3-t7", type: "numeric", prompt: "'ev' sözündə neçə heca var?", answer: 1, xp: 10, skills: ["az.phon.syllable"] },
            { id: "az6-fon-l3-t8", type: "multiple_choice", prompt: "Hansı böyük hərflə yazılmalıdır?", options: ["bakı", "kitab", "alma", "su"], correctIndex: 0, xp: 10, skills: ["az.phon.letters","az.orth.capital"] },
            { id: "az6-fon-l3-t9", type: "multiple_choice", prompt: "Hansı xüsusi isimdir (böyük hərflə)?", options: ["Nizami", "şagird", "müəllim", "dağ"], correctIndex: 0, xp: 10, skills: ["az.phon.letters","az.pos.noun","az.orth.capital"] },
            { id: "az6-fon-l3-t10", type: "numeric", prompt: "'müəllim' sözündə neçə heca var?", answer: 3, xp: 10, skills: ["az.phon.syllable"] },
            { id: "az6-fon-l3-t11", type: "multiple_choice", prompt: "Cümlənin əvvəlində söz necə yazılır?", options: ["böyük hərflə", "kiçik hərflə", "fərqi yoxdur", "hamısı böyük"], correctIndex: 0, xp: 10, skills: ["az.syn.sentence"] },
            { id: "az6-fon-l3-t12", type: "numeric", prompt: "'gül' sözündə neçə heca var?", answer: 1, xp: 10, skills: ["az.phon.syllable"] },
            { id: "az6-fon-l3-t13", type: "multiple_choice", prompt: "Hansı ölkə adıdır (böyük hərflə)?", options: ["Azərbaycan", "şəhər", "ölkə", "dəniz"], correctIndex: 0, xp: 10, skills: ["az.phon.letters","az.orth.capital"] },
            { id: "az6-fon-l3-t14", type: "numeric", prompt: "'dəftər' sözündə neçə heca var?", answer: 2, xp: 10, skills: ["az.phon.syllable"] },
            { id: "az6-fon-l3-t15", type: "numeric", prompt: "'qələmdanlıq' sözündə neçə heca var?", answer: 4, xp: 15, skills: ["az.phon.syllable"] },
          ],
          bonusTasks: [
            { id: "az6-fon-l3-b1", type: "numeric", prompt: "'təbiət' sözündə neçə heca var?", answer: 3, xp: 15, skills: ["az.phon.syllable"] },
            { id: "az6-fon-l3-b2", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["Bakı şəhəri", "bakı şəhəri", "BAKI şəhəri", "Bakı Şəhəri"], correctIndex: 0, xp: 15, skills: ["az.orth.spelling"] },
            { id: "az6-fon-l3-b3", type: "numeric", prompt: "'kompüter' sözündə neçə heca var?", answer: 3, xp: 15, skills: ["az.phon.syllable"] },
            { id: "az6-fon-l3-b4", type: "multiple_choice", prompt: "İnsan adları necə yazılır?", options: ["böyük hərflə", "kiçik hərflə", "fərqi yoxdur", "dırnaqda"], correctIndex: 0, xp: 15, skills: ["az.phon.vowels"] },
            { id: "az6-fon-l3-b5", type: "numeric", prompt: "'yaz-mı-şam' — 'yazmışam' sözündə neçə heca var?", answer: 3, xp: 15, skills: ["az.phon.syllable"] },
          ],
        },
        {
          id: "az6-fonetika-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        }
      ],
    },

    // ═══════════════ 2. Leksika ═══════════════
    {
      id: "az6-leksika",
      title: "Leksika",
      description:
        "Sözün həqiqi və məcazi mənası, sinonim, antonim, omonim və çoxmənalı sözlər.",
      lessons: [
        {
          id: "az6-lek-l1",
          title: "Sözün həqiqi və məcazi mənası",
          intro: "Sözün ilkin (həqiqi) və köçürülmüş (məcazi) mənasını ayırd etmək.",
          sections: [
            { heading: "Həqiqi məna", body: "Sözün ilk, əsas mənasına həqiqi məna deyilir: 'dəmir qapı' — dəmirdən düzəlmiş qapı." },
            { heading: "Məcazi məna", body: "Sözün başqa əşyaya köçürülmüş, obrazlı mənasına məcazi məna deyilir: 'dəmir iradə' — möhkəm iradə. Burada 'dəmir' həqiqi deyil." },
            { heading: "Necə ayıraq?", body: "Söz doğrudan həmin əşyanı bildirirsə — həqiqi; oxşatma, obraz üçün işlənirsə — məcazidir: 'şirin çay' (həqiqi), 'şirin söz' (məcazi)." },
          ],
          tasks: [
            { id: "az6-lek-l1-t1", type: "multiple_choice", prompt: "Sözün ilk, əsas mənasına nə deyilir?", options: ["həqiqi məna", "məcazi məna", "sinonim", "antonim"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l1-t2", type: "multiple_choice", prompt: "Sözün obrazlı, köçürülmüş mənasına nə deyilir?", options: ["məcazi məna", "həqiqi məna", "omonim", "heca"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l1-t3", type: "multiple_choice", prompt: "'dəmir qapı' — 'dəmir' necə mənadadır?", options: ["həqiqi", "məcazi", "sinonim", "antonim"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l1-t4", type: "multiple_choice", prompt: "'dəmir iradə' — 'dəmir' necə mənadadır?", options: ["məcazi", "həqiqi", "omonim", "heca"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l1-t5", type: "multiple_choice", prompt: "'şirin alma' — 'şirin' necə mənadadır?", options: ["həqiqi", "məcazi", "antonim", "sinonim"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l1-t6", type: "multiple_choice", prompt: "'şirin söz' — 'şirin' necə mənadadır?", options: ["məcazi", "həqiqi", "omonim", "heca"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l1-t7", type: "multiple_choice", prompt: "'soyuq hava' — 'soyuq' necə mənadadır?", options: ["həqiqi", "məcazi", "sinonim", "antonim"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l1-t8", type: "multiple_choice", prompt: "'soyuq baxış' — 'soyuq' necə mənadadır?", options: ["məcazi", "həqiqi", "omonim", "heca"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l1-t9", type: "multiple_choice", prompt: "'qızıl üzük' — 'qızıl' necə mənadadır?", options: ["həqiqi", "məcazi", "antonim", "sinonim"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l1-t10", type: "multiple_choice", prompt: "'qızıl əllər' — 'qızıl' necə mənadadır?", options: ["məcazi", "həqiqi", "omonim", "heca"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l1-t11", type: "multiple_choice", prompt: "'ağır yük' — 'ağır' necə mənadadır?", options: ["həqiqi", "məcazi", "sinonim", "antonim"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l1-t12", type: "multiple_choice", prompt: "'ağır söz' — 'ağır' necə mənadadır?", options: ["məcazi", "həqiqi", "omonim", "heca"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l1-t13", type: "multiple_choice", prompt: "'isti çörək' — necə mənadadır?", options: ["həqiqi", "məcazi", "antonim", "omonim"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l1-t14", type: "multiple_choice", prompt: "'isti münasibət' — necə mənadadır?", options: ["məcazi", "həqiqi", "sinonim", "heca"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l1-t15", type: "multiple_choice", prompt: "'daş ürək' ifadəsi necə mənadadır?", options: ["məcazi", "həqiqi", "omonim", "sinonim"], correctIndex: 0, xp: 15, skills: ["az.lex.meaning"] },
          ],
          bonusTasks: [
            { id: "az6-lek-l1-b1", type: "multiple_choice", prompt: "'Günəş doğdu' — 'doğdu' necə mənadadır?", options: ["məcazi", "həqiqi", "omonim", "heca"], correctIndex: 0, xp: 15, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l1-b2", type: "multiple_choice", prompt: "'açıq qapı' — 'açıq' necə mənadadır?", options: ["həqiqi", "məcazi", "antonim", "sinonim"], correctIndex: 0, xp: 15, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l1-b3", type: "multiple_choice", prompt: "'açıq ürəkli' — 'açıq' necə mənadadır?", options: ["məcazi", "həqiqi", "omonim", "heca"], correctIndex: 0, xp: 15, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l1-b4", type: "multiple_choice", prompt: "Məcazi məna nə üçün işlənir?", options: ["obraz, oxşatma", "həqiqəti demək", "saymaq", "heca ayırmaq"], correctIndex: 0, xp: 15, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l1-b5", type: "multiple_choice", prompt: "'dağın ətəyi' — 'ətək' necə mənadadır?", options: ["məcazi", "həqiqi", "omonim", "sinonim"], correctIndex: 0, xp: 15, skills: ["az.lex.meaning"] },
          ],
        },
        {
          id: "az6-lek-l2",
          title: "Sinonim və antonim",
          intro: "Mənaca yaxın (sinonim) və əks (antonim) sözlər.",
          sections: [
            { heading: "Sinonim", body: "Formaca müxtəlif, mənaca yaxın sözlərə sinonim deyilir: gözəl — qəşəng — göyçək; böyük — iri; cəsur — igid." },
            { heading: "Antonim", body: "Mənaca bir-birinin əksi olan sözlərə antonim deyilir: böyük — kiçik; isti — soyuq; ağ — qara; gündüz — gecə." },
            { heading: "Fayda", body: "Sinonimlər nitqi zənginləşdirir, təkrarın qarşısını alır. Antonimlər fikri qarşılaşdırmaqla gücləndirir." },
          ],
          tasks: [
            { id: "az6-lek-l2-t1", type: "multiple_choice", prompt: "Mənaca yaxın sözlərə nə deyilir?", options: ["sinonim", "antonim", "omonim", "heca"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l2-t2", type: "multiple_choice", prompt: "Mənaca əks sözlərə nə deyilir?", options: ["antonim", "sinonim", "omonim", "vurğu"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l2-t3", type: "multiple_choice", prompt: "'gözəl' sözünün sinonimi hansıdır?", options: ["qəşəng", "çirkin", "böyük", "soyuq"], correctIndex: 0, xp: 10, skills: ["az.lex.synonym"] },
            { id: "az6-lek-l2-t4", type: "multiple_choice", prompt: "'böyük' sözünün antonimi hansıdır?", options: ["kiçik", "iri", "nəhəng", "geniş"], correctIndex: 0, xp: 10, skills: ["az.lex.antonym"] },
            { id: "az6-lek-l2-t5", type: "multiple_choice", prompt: "'isti' sözünün antonimi hansıdır?", options: ["soyuq", "qaynar", "ilıq", "yandırıcı"], correctIndex: 0, xp: 10, skills: ["az.lex.antonym"] },
            { id: "az6-lek-l2-t6", type: "multiple_choice", prompt: "'cəsur' sözünün sinonimi hansıdır?", options: ["igid", "qorxaq", "zəif", "kiçik"], correctIndex: 0, xp: 10, skills: ["az.lex.synonym"] },
            { id: "az6-lek-l2-t7", type: "fill_blank", prompt: "'ağ' sözünün antonimini yaz.", accepted: ["qara"], xp: 10, skills: ["az.lex.antonym"] },
            { id: "az6-lek-l2-t8", type: "fill_blank", prompt: "'gündüz' sözünün antonimini yaz.", accepted: ["gecə", "gece"], xp: 10, skills: ["az.lex.antonym"] },
            { id: "az6-lek-l2-t9", type: "multiple_choice", prompt: "'sevinc' sözünün antonimi hansıdır?", options: ["kədər", "şadlıq", "gülüş", "fərəh"], correctIndex: 0, xp: 10, skills: ["az.lex.antonym"] },
            { id: "az6-lek-l2-t10", type: "multiple_choice", prompt: "'iri' sözünün sinonimi hansıdır?", options: ["böyük", "kiçik", "dar", "alçaq"], correctIndex: 0, xp: 10, skills: ["az.lex.synonym"] },
            { id: "az6-lek-l2-t11", type: "fill_blank", prompt: "'uzun' sözünün antonimini yaz.", accepted: ["qısa", "qisa"], xp: 10, skills: ["az.lex.antonym"] },
            { id: "az6-lek-l2-t12", type: "fill_blank", prompt: "'açıq' sözünün antonimini yaz.", accepted: ["bağlı", "bagli"], xp: 10, skills: ["az.lex.antonym"] },
            { id: "az6-lek-l2-t13", type: "multiple_choice", prompt: "'sürətli' sözünün antonimi hansıdır?", options: ["yavaş", "cəld", "iti", "tez"], correctIndex: 0, xp: 10, skills: ["az.lex.antonym"] },
            { id: "az6-lek-l2-t14", type: "multiple_choice", prompt: "'xoşbəxt' sözünün sinonimi hansıdır?", options: ["bəxtiyar", "bədbəxt", "kədərli", "yorğun"], correctIndex: 0, xp: 10, skills: ["az.lex.synonym"] },
            { id: "az6-lek-l2-t15", type: "fill_blank", prompt: "'dost' sözünün antonimini yaz.", accepted: ["düşmən", "düsmən", "dusmen"], xp: 15, skills: ["az.lex.antonym"] },
          ],
          bonusTasks: [
            { id: "az6-lek-l2-b1", type: "fill_blank", prompt: "'yaxşı' sözünün antonimini yaz.", accepted: ["pis"], xp: 15, skills: ["az.lex.antonym"] },
            { id: "az6-lek-l2-b2", type: "multiple_choice", prompt: "'zəngin' sözünün antonimi hansıdır?", options: ["kasıb", "varlı", "dövlətli", "böyük"], correctIndex: 0, xp: 15, skills: ["az.lex.antonym"] },
            { id: "az6-lek-l2-b3", type: "multiple_choice", prompt: "'gülmək' sözünün antonimi hansıdır?", options: ["ağlamaq", "sevinmək", "danışmaq", "baxmaq"], correctIndex: 0, xp: 15, skills: ["az.lex.antonym"] },
            { id: "az6-lek-l2-b4", type: "fill_blank", prompt: "'əvvəl' sözünün antonimini yaz.", accepted: ["sonra", "son"], xp: 15, skills: ["az.lex.antonym"] },
            { id: "az6-lek-l2-b5", type: "multiple_choice", prompt: "'hündür' sözünün sinonimi hansıdır?", options: ["uca", "alçaq", "gödək", "enli"], correctIndex: 0, xp: 15, skills: ["az.lex.synonym"] },
          ],
        },
        {
          id: "az6-leksika-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az6-lek-l3",
          title: "Omonim və çoxmənalı sözlər",
          intro: "Eyni yazılıb müxtəlif məna verən (omonim) və bir neçə mənalı sözlər.",
          sections: [
            { heading: "Omonim", body: "Eyni cür yazılıb-deyilən, lakin mənaca tamamilə fərqli sözlərə omonim deyilir: 'üz' (sifət) və 'üz' (üzmək əmri); 'yaz' (fəsil) və 'yaz' (yazmaq əmri)." },
            { heading: "Çoxmənalı söz", body: "Bir sözün bir-biri ilə əlaqəli bir neçə mənası ola bilər: 'baş' (insanın başı, dağın başı, işin başı). Mənalar arasında əlaqə var." },
            { heading: "Fərq", body: "Omonimlərin mənaları arasında əlaqə YOXDUR (təsadüfən eyni yazılır); çoxmənalı sözün mənaları arasında əlaqə VAR." },
          ],
          tasks: [
            { id: "az6-lek-l3-t1", type: "multiple_choice", prompt: "Eyni yazılıb fərqli məna verən sözlərə nə deyilir?", options: ["omonim", "sinonim", "antonim", "heca"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l3-t2", type: "multiple_choice", prompt: "'yaz' (fəsil) və 'yaz' (yazmaq) sözləri necədir?", options: ["omonim", "sinonim", "antonim", "çoxmənalı"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l3-t3", type: "multiple_choice", prompt: "Omonimlərin mənaları arasında əlaqə...?", options: ["yoxdur", "var", "həmişə var", "sinonimdir"], correctIndex: 0, xp: 10, skills: ["az.lex.homonym"] },
            { id: "az6-lek-l3-t4", type: "multiple_choice", prompt: "Çoxmənalı sözün mənaları arasında əlaqə...?", options: ["var", "yoxdur", "təsadüfidir", "əksdir"], correctIndex: 0, xp: 10, skills: ["az.lex.homonym"] },
            { id: "az6-lek-l3-t5", type: "multiple_choice", prompt: "'baş' (insan başı, dağ başı) — necə sözdür?", options: ["çoxmənalı", "omonim", "antonim", "sinonim"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l3-t6", type: "multiple_choice", prompt: "'üz' (sifət) və 'üz' (üzmək) — necədir?", options: ["omonim", "çoxmənalı", "sinonim", "antonim"], correctIndex: 0, xp: 10, skills: ["az.pos.adjective"] },
            { id: "az6-lek-l3-t7", type: "multiple_choice", prompt: "'ağız' (insanın ağzı, çayın ağzı) — necədir?", options: ["çoxmənalı", "omonim", "antonim", "sinonim"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l3-t8", type: "multiple_choice", prompt: "'at' (heyvan) və 'at' (atmaq əmri) — necədir?", options: ["omonim", "sinonim", "antonim", "çoxmənalı"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l3-t9", type: "multiple_choice", prompt: "'göz' (insanın gözü, iynənin gözü) — necədir?", options: ["çoxmənalı", "omonim", "antonim", "sinonim"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l3-t10", type: "multiple_choice", prompt: "'sağ' (istiqamət) və 'sağ' (diri) — necədir?", options: ["omonim", "çoxmənalı", "sinonim", "antonim"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l3-t11", type: "multiple_choice", prompt: "'qol' (insanın qolu, çayın qolu) — necədir?", options: ["çoxmənalı", "omonim", "antonim", "sinonim"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l3-t12", type: "multiple_choice", prompt: "'diş' (insanın dişi, daraq dişi) — necədir?", options: ["çoxmənalı", "omonim", "sinonim", "antonim"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l3-t13", type: "multiple_choice", prompt: "'gül' (çiçək) və 'gül' (gülmək əmri) — necədir?", options: ["omonim", "çoxmənalı", "sinonim", "antonim"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l3-t14", type: "multiple_choice", prompt: "'ayaq' (insanın ayağı, stolun ayağı) — necədir?", options: ["çoxmənalı", "omonim", "antonim", "sinonim"], correctIndex: 0, xp: 10, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l3-t15", type: "multiple_choice", prompt: "'daş' (daşımaq əmri) və 'daş' (qaya) — necədir?", options: ["omonim", "çoxmənalı", "sinonim", "antonim"], correctIndex: 0, xp: 15, skills: ["az.lex.meaning"] },
          ],
          bonusTasks: [
            { id: "az6-lek-l3-b1", type: "multiple_choice", prompt: "'burun' (insanın burnu, gəminin burnu) — necədir?", options: ["çoxmənalı", "omonim", "antonim", "sinonim"], correctIndex: 0, xp: 15, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l3-b2", type: "multiple_choice", prompt: "'ət' (yemək) və 'et' (etmək) omonimə oxşasa da nə fərqi var?", options: ["fərqli yazılır", "eynidir", "sinonimdir", "antonimdir"], correctIndex: 0, xp: 15, skills: ["az.lex.homonym"] },
            { id: "az6-lek-l3-b3", type: "multiple_choice", prompt: "'dil' (orqan, danışıq dili) — necədir?", options: ["çoxmənalı", "omonim", "antonim", "sinonim"], correctIndex: 0, xp: 15, skills: ["az.lex.meaning"] },
            { id: "az6-lek-l3-b4", type: "multiple_choice", prompt: "Omonim ilə çoxmənalını nə ayırır?", options: ["mənalar arası əlaqə", "yazılış", "heca sayı", "vurğu"], correctIndex: 0, xp: 15, skills: ["az.lex.homonym"] },
            { id: "az6-lek-l3-b5", type: "multiple_choice", prompt: "'yol' (cığır, həyat yolu) — necədir?", options: ["çoxmənalı", "omonim", "sinonim", "antonim"], correctIndex: 0, xp: 15, skills: ["az.lex.meaning"] },
          ],
        },
        {
          id: "az6-leksika-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        }
      ],
    },

    // ═══════════════ 3. Sözün tərkibi və söz yaradıcılığı ═══════════════
    {
      id: "az6-terkib",
      title: "Sözün tərkibi və söz yaradıcılığı",
      description:
        "Kök və şəkilçi, leksik və qrammatik şəkilçilər, düzəltmə və mürəkkəb sözlər.",
      lessons: [
        {
          id: "az6-ter-l1",
          title: "Kök və şəkilçi",
          intro: "Sözü kök və şəkilçiyə ayırmaq, şəkilçi növlərini tanımaq.",
          sections: [
            { heading: "Kök", body: "Sözün məna daşıyan, daha bölünməyən əsas hissəsinə kök deyilir: 'kitablar' sözündə kök — 'kitab'. Kök müstəqil məna bildirir." },
            { heading: "Şəkilçi", body: "Kökə qoşulub yeni söz və ya söz forması yaradan hissəyə şəkilçi deyilir: kitab-lar, gül-çü, iş-lə." },
            { heading: "İki növ şəkilçi", body: "Leksik (sözdüzəldici) şəkilçi yeni söz yaradır: iş → işçi. Qrammatik (sözdəyişdirici) şəkilçi sözün formasını dəyişir: kitab → kitablar (cəm)." },
          ],
          tasks: [
            { id: "az6-ter-l1-t1", type: "multiple_choice", prompt: "Sözün məna daşıyan əsas hissəsi necə adlanır?", options: ["kök", "şəkilçi", "heca", "vurğu"], correctIndex: 0, xp: 10, skills: ["az.phon.letters"] },
            { id: "az6-ter-l1-t2", type: "fill_blank", prompt: "'kitablar' sözünün kökünü yaz.", accepted: ["kitab"], xp: 10, skills: ["az.morph.root"] },
            { id: "az6-ter-l1-t3", type: "fill_blank", prompt: "'güllər' sözünün kökünü yaz.", accepted: ["gül", "gul"], xp: 10, skills: ["az.morph.root"] },
            { id: "az6-ter-l1-t4", type: "multiple_choice", prompt: "Kökə qoşulan hissə necə adlanır?", options: ["şəkilçi", "kök", "heca", "səs"], correctIndex: 0, xp: 10, skills: ["az.morph.root"] },
            { id: "az6-ter-l1-t5", type: "multiple_choice", prompt: "Yeni söz yaradan şəkilçi necə adlanır?", options: ["leksik (sözdüzəldici)", "qrammatik", "sait", "kök"], correctIndex: 0, xp: 10, skills: ["az.morph.root","az.morph.derivation"] },
            { id: "az6-ter-l1-t6", type: "multiple_choice", prompt: "Sözün formasını dəyişən şəkilçi necə adlanır?", options: ["qrammatik (sözdəyişdirici)", "leksik", "kök", "heca"], correctIndex: 0, xp: 10, skills: ["az.morph.root"] },
            { id: "az6-ter-l1-t7", type: "fill_blank", prompt: "'işçi' sözünün kökünü yaz.", accepted: ["iş", "is"], xp: 10, skills: ["az.morph.root"] },
            { id: "az6-ter-l1-t8", type: "multiple_choice", prompt: "'kitab-lar'-da '-lar' hansı şəkilçidir?", options: ["qrammatik (cəm)", "leksik", "kök", "sait"], correctIndex: 0, xp: 10, skills: ["az.morph.root"] },
            { id: "az6-ter-l1-t9", type: "multiple_choice", prompt: "'iş-çi'-də '-çi' hansı şəkilçidir?", options: ["leksik (yeni söz)", "qrammatik", "kök", "heca"], correctIndex: 0, xp: 10, skills: ["az.morph.root"] },
            { id: "az6-ter-l1-t10", type: "fill_blank", prompt: "'meşələr' sözünün kökünü yaz.", accepted: ["meşə", "mese", "meşe"], xp: 10, skills: ["az.morph.root"] },
            { id: "az6-ter-l1-t11", type: "multiple_choice", prompt: "Kök müstəqil məna bildirirmi?", options: ["Bəli", "Xeyr"], correctIndex: 0, xp: 10, skills: ["az.morph.root"] },
            { id: "az6-ter-l1-t12", type: "fill_blank", prompt: "'evdə' sözünün kökünü yaz.", accepted: ["ev"], xp: 10, skills: ["az.morph.root"] },
            { id: "az6-ter-l1-t13", type: "multiple_choice", prompt: "'yaz-ıçı' sözündə '-ıçı' nə yaradır?", options: ["yeni söz (yazıçı)", "cəm", "hal", "zaman"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l1-t14", type: "fill_blank", prompt: "'dostluq' sözünün kökünü yaz.", accepted: ["dost"], xp: 10, skills: ["az.morph.root"] },
            { id: "az6-ter-l1-t15", type: "multiple_choice", prompt: "'gül-lük' sözündə '-lük' hansı şəkilçidir?", options: ["leksik (yeni söz)", "qrammatik", "kök", "sait"], correctIndex: 0, xp: 15, skills: ["az.morph.root"] },
          ],
          bonusTasks: [
            { id: "az6-ter-l1-b1", type: "fill_blank", prompt: "'kitabçılıq' sözünün kökünü yaz.", accepted: ["kitab"], xp: 15, skills: ["az.morph.root"] },
            { id: "az6-ter-l1-b2", type: "multiple_choice", prompt: "Bir sözdə neçə şəkilçi ola bilər?", options: ["bir neçə", "yalnız bir", "heç", "yalnız iki"], correctIndex: 0, xp: 15, skills: ["az.morph.root"] },
            { id: "az6-ter-l1-b3", type: "multiple_choice", prompt: "'ev-lər-də' sözündə neçə şəkilçi var?", options: ["2", "1", "3", "0"], correctIndex: 0, xp: 15, skills: ["az.morph.root"] },
            { id: "az6-ter-l1-b4", type: "fill_blank", prompt: "'bağban' sözünün kökünü yaz.", accepted: ["bağ", "bag"], xp: 15, skills: ["az.morph.root"] },
            { id: "az6-ter-l1-b5", type: "multiple_choice", prompt: "Cəm, hal, mənsubiyyət şəkilçiləri hansı növdür?", options: ["qrammatik", "leksik", "kök", "sait"], correctIndex: 0, xp: 15, skills: ["az.morph.root","az.pos.noun_possess"] },
          ],
        },
        {
          id: "az6-ter-l2",
          title: "Sadə və düzəltmə sözlər",
          intro: "Yalnız kökdən ibarət (sadə) və leksik şəkilçili (düzəltmə) sözlər.",
          sections: [
            { heading: "Sadə söz", body: "Yalnız kökdən ibarət, leksik şəkilçisi olmayan sözə sadə söz deyilir: ev, kitab, gül, su, dağ." },
            { heading: "Düzəltmə söz", body: "Kökə leksik (sözdüzəldici) şəkilçi qoşulmaqla yaranan sözə düzəltmə söz deyilir: iş → işçi, gül → güllük, dost → dostluq." },
            { heading: "Diqqət", body: "Qrammatik şəkilçi (cəm, hal) sözü düzəltmə etmir: 'kitablar' sadə sözdür (kök + cəm), 'kitabça' düzəltmədir." },
          ],
          tasks: [
            { id: "az6-ter-l2-t1", type: "multiple_choice", prompt: "Yalnız kökdən ibarət söz necə adlanır?", options: ["sadə söz", "düzəltmə söz", "mürəkkəb söz", "şəkilçi"], correctIndex: 0, xp: 10, skills: ["az.morph.root"] },
            { id: "az6-ter-l2-t2", type: "multiple_choice", prompt: "Leksik şəkilçili söz necə adlanır?", options: ["düzəltmə söz", "sadə söz", "kök", "heca"], correctIndex: 0, xp: 10, skills: ["az.morph.root"] },
            { id: "az6-ter-l2-t3", type: "multiple_choice", prompt: "Hansı sadə sözdür?", options: ["ev", "işçi", "dostluq", "güllük"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l2-t4", type: "multiple_choice", prompt: "Hansı düzəltmə sözdür?", options: ["işçi", "su", "dağ", "kitab"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l2-t5", type: "multiple_choice", prompt: "'dostluq' necə sözdür?", options: ["düzəltmə", "sadə", "mürəkkəb", "kök"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l2-t6", type: "multiple_choice", prompt: "'kitab' necə sözdür?", options: ["sadə", "düzəltmə", "mürəkkəb", "şəkilçi"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l2-t7", type: "multiple_choice", prompt: "Hansı düzəltmə sözdür?", options: ["güllük", "gül", "su", "yol"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l2-t8", type: "multiple_choice", prompt: "'işçi' necə sözdür?", options: ["düzəltmə", "sadə", "mürəkkəb", "kök"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l2-t9", type: "multiple_choice", prompt: "Hansı sadə sözdür?", options: ["daş", "daşlıq", "sözlük", "təmizlik"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l2-t10", type: "multiple_choice", prompt: "'bağban' necə sözdür?", options: ["düzəltmə", "sadə", "mürəkkəb", "kök"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l2-t11", type: "multiple_choice", prompt: "Hansı düzəltmə sözdür?", options: ["duzlu", "duz", "su", "od"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l2-t12", type: "multiple_choice", prompt: "'təmizlik' necə sözdür?", options: ["düzəltmə", "sadə", "mürəkkəb", "kök"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l2-t13", type: "multiple_choice", prompt: "Hansı sadə sözdür?", options: ["dağ", "dağlıq", "meşəlik", "sözçü"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l2-t14", type: "fill_blank", prompt: "'iş' sözünə '-çi' şəkilçisi qoş, yaranan sözü yaz.", accepted: ["işçi", "isçi", "isci"], xp: 10, skills: ["az.morph.root"] },
            { id: "az6-ter-l2-t15", type: "multiple_choice", prompt: "'yazıçı' necə sözdür?", options: ["düzəltmə", "sadə", "mürəkkəb", "kök"], correctIndex: 0, xp: 15, skills: ["az.morph.derivation"] },
          ],
          bonusTasks: [
            { id: "az6-ter-l2-b1", type: "multiple_choice", prompt: "'gözlük' necə sözdür?", options: ["düzəltmə", "sadə", "mürəkkəb", "kök"], correctIndex: 0, xp: 15, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l2-b2", type: "fill_blank", prompt: "'süd' sözünə '-çü' qoş, yaranan sözü yaz.", accepted: ["südçü", "sudçu", "sudcu"], xp: 15, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l2-b3", type: "multiple_choice", prompt: "Hansı sadə sözdür?", options: ["od", "odun", "ütü", "sözlük"], correctIndex: 0, xp: 15, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l2-b4", type: "multiple_choice", prompt: "'kitabça' necə sözdür?", options: ["düzəltmə", "sadə", "mürəkkəb", "kök"], correctIndex: 0, xp: 15, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l2-b5", type: "fill_blank", prompt: "'kömək' sözünə '-çi' qoş, yaranan sözü yaz.", accepted: ["köməkçi", "komekçi", "komekci"], xp: 15, skills: ["az.morph.derivation"] },
          ],
        },
        {
          id: "az6-terkib-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az6-ter-l3",
          title: "Mürəkkəb sözlər",
          intro: "İki kökdən yaranan sözlər və onların yazılışı.",
          sections: [
            { heading: "Mürəkkəb söz", body: "İki (və ya daha çox) sözün birləşməsindən yaranan sözə mürəkkəb söz deyilir: gündoğan, əlüzyuyan, günəbaxan, dəvəquşu." },
            { heading: "Bitişik və defislə", body: "Bəzi mürəkkəb sözlər bitişik yazılır: gülüşdürmək, otbiçən. Bəziləri defislə: ala-bəzək, qırmızı-yaşıl, adda-budda." },
            { heading: "Fərq", body: "Mürəkkəb sözdə iki kök var (gün+doğan), düzəltmə sözdə isə bir kök + şəkilçi var (iş+çi)." },
          ],
          tasks: [
            { id: "az6-ter-l3-t1", type: "multiple_choice", prompt: "İki kökdən yaranan söz necə adlanır?", options: ["mürəkkəb söz", "düzəltmə söz", "sadə söz", "kök"], correctIndex: 0, xp: 10, skills: ["az.morph.root"] },
            { id: "az6-ter-l3-t2", type: "multiple_choice", prompt: "Hansı mürəkkəb sözdür?", options: ["gündoğan", "işçi", "kitab", "güllük"], correctIndex: 0, xp: 10, skills: ["az.morph.compound"] },
            { id: "az6-ter-l3-t3", type: "multiple_choice", prompt: "'günəbaxan' necə sözdür?", options: ["mürəkkəb", "sadə", "düzəltmə", "kök"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l3-t4", type: "multiple_choice", prompt: "Mürəkkəb sözdə neçə kök olur?", options: ["iki (və ya daha çox)", "bir", "heç", "yalnız üç"], correctIndex: 0, xp: 10, skills: ["az.morph.root","az.morph.compound"] },
            { id: "az6-ter-l3-t5", type: "multiple_choice", prompt: "Hansı mürəkkəb sözdür?", options: ["dəvəquşu", "quşlar", "quşçu", "quş"], correctIndex: 0, xp: 10, skills: ["az.morph.compound"] },
            { id: "az6-ter-l3-t6", type: "multiple_choice", prompt: "'otbiçən' necə sözdür?", options: ["mürəkkəb", "sadə", "düzəltmə", "kök"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l3-t7", type: "multiple_choice", prompt: "Hansı defislə yazılan mürəkkəb sözdür?", options: ["ala-bəzək", "işçi", "kitab", "güllük"], correctIndex: 0, xp: 10, skills: ["az.morph.compound"] },
            { id: "az6-ter-l3-t8", type: "multiple_choice", prompt: "'əlüzyuyan' necə sözdür?", options: ["mürəkkəb", "sadə", "düzəltmə", "kök"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l3-t9", type: "multiple_choice", prompt: "Mürəkkəb sözlə düzəltmə sözün fərqi nədir?", options: ["mürəkkəbdə iki kök var", "eyni şeydir", "fərqi yoxdur", "biri şəkilçidir"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation","az.morph.compound"] },
            { id: "az6-ter-l3-t10", type: "multiple_choice", prompt: "Hansı mürəkkəb sözdür?", options: ["boyunbağı", "kitabça", "işçi", "gül"], correctIndex: 0, xp: 10, skills: ["az.morph.compound"] },
            { id: "az6-ter-l3-t11", type: "multiple_choice", prompt: "'qırmızı-yaşıl' necə yazılır?", options: ["defislə", "bitişik", "ayrı", "böyük hərflə"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l3-t12", type: "multiple_choice", prompt: "Hansı sadə sözdür (mürəkkəb deyil)?", options: ["dağ", "dağətəyi", "günçıxan", "atçapan"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l3-t13", type: "multiple_choice", prompt: "'beşillik' — hansı sözlərdən yaranıb?", options: ["beş + il", "beş + lik", "il + lik", "yalnız beş"], correctIndex: 0, xp: 10, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l3-t14", type: "multiple_choice", prompt: "Hansı mürəkkəb sözdür?", options: ["suiçən", "sulu", "su", "sular"], correctIndex: 0, xp: 10, skills: ["az.morph.compound"] },
            { id: "az6-ter-l3-t15", type: "multiple_choice", prompt: "'ADI-budda' kimi təkrarla yaranan sözlər necə yazılır?", options: ["defislə", "bitişik", "ayrı", "böyük hərflə"], correctIndex: 0, xp: 15, skills: ["az.morph.derivation"] },
          ],
          bonusTasks: [
            { id: "az6-ter-l3-b1", type: "multiple_choice", prompt: "'Odlar Yurdu' — necə mürəkkəb addır?", options: ["ayrı yazılan", "bitişik", "defislə", "kiçik hərflə"], correctIndex: 0, xp: 15, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l3-b2", type: "multiple_choice", prompt: "'gülqönçəsi' necə sözdür?", options: ["mürəkkəb", "sadə", "düzəltmə", "kök"], correctIndex: 0, xp: 15, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l3-b3", type: "multiple_choice", prompt: "Hansı düzəltmə sözdür (mürəkkəb deyil)?", options: ["dostluq", "gündoğan", "otbiçən", "dəvəquşu"], correctIndex: 0, xp: 15, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l3-b4", type: "multiple_choice", prompt: "'ağappaq' kimi sözlər necə yazılır?", options: ["bitişik", "defislə", "ayrı", "böyük hərflə"], correctIndex: 0, xp: 15, skills: ["az.morph.derivation"] },
            { id: "az6-ter-l3-b5", type: "multiple_choice", prompt: "'Bakı' sözü necədir?", options: ["sadə", "mürəkkəb", "düzəltmə", "şəkilçi"], correctIndex: 0, xp: 15, skills: ["az.morph.derivation"] },
          ],
        },
        {
          id: "az6-terkib-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        }
      ],
    },

    // ═══════════════ 4. Nitq hissələri I ═══════════════
    {
      id: "az6-nitq1",
      title: "Nitq hissələri I: isim, sifət, say, əvəzlik",
      description:
        "İsim (hal, mənsubiyyət, cəm), sifət (dərəcələr), say (növləri), əvəzlik (növləri).",
      lessons: [
        {
          id: "az6-nit1-l1",
          title: "İsim",
          intro: "İsim, onun sualları, cəm, mənsubiyyət və hal şəkilçiləri.",
          sections: [
            { heading: "İsim nədir?", body: "Əşyanın adını bildirən, 'kim?', 'nə?', 'hara?' suallarına cavab verən nitq hissəsinə isim deyilir: uşaq, kitab, şəhər." },
            { heading: "Xüsusi və ümumi", body: "Ümumi isim eyni növ əşyaların adıdır (şəhər, çay). Xüsusi isim konkret addır və böyük hərflə yazılır: Bakı, Kür, Nizami." },
            { heading: "İsmin halları", body: "İsim 6 halda dəyişir: adlıq (kim? nə?), yiyəlik (kimin? nəyin?), yönlük (kimə? nəyə?), təsirlik (kimi? nəyi?), yerlik (kimdə? harada?), çıxışlıq (kimdən? haradan?)." },
          ],
          tasks: [
            { id: "az6-nit1-l1-t1", type: "multiple_choice", prompt: "Əşyanın adını bildirən nitq hissəsi necə adlanır?", options: ["isim", "sifət", "feil", "say"], correctIndex: 0, xp: 10, skills: ["az.phon.letters","az.pos.noun"] },
            { id: "az6-nit1-l1-t2", type: "multiple_choice", prompt: "İsim hansı suallara cavab verir?", options: ["kim? nə?", "necə? nə cür?", "nə etdi?", "neçə?"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l1-t3", type: "multiple_choice", prompt: "Hansı isimdir?", options: ["kitab", "gözəl", "oxumaq", "tez"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l1-t4", type: "multiple_choice", prompt: "Hansı xüsusi isimdir?", options: ["Bakı", "şəhər", "çay", "dağ"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l1-t5", type: "multiple_choice", prompt: "Hansı ümumi isimdir?", options: ["şəhər", "Gəncə", "Kür", "Nizami"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l1-t6", type: "numeric", prompt: "İsim neçə halda dəyişir?", answer: 6, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l1-t7", type: "multiple_choice", prompt: "'kimin? nəyin?' sualı hansı haldır?", options: ["yiyəlik", "adlıq", "yönlük", "təsirlik"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l1-t8", type: "multiple_choice", prompt: "'kimə? nəyə?' sualı hansı haldır?", options: ["yönlük", "yerlik", "çıxışlıq", "adlıq"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l1-t9", type: "multiple_choice", prompt: "'kimdə? harada?' sualı hansı haldır?", options: ["yerlik", "yönlük", "çıxışlıq", "təsirlik"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l1-t10", type: "multiple_choice", prompt: "'kimdən? haradan?' sualı hansı haldır?", options: ["çıxışlıq", "yerlik", "yönlük", "adlıq"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l1-t11", type: "multiple_choice", prompt: "'evdə' sözü hansı haldadır?", options: ["yerlik", "yönlük", "çıxışlıq", "adlıq"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l1-t12", type: "multiple_choice", prompt: "'evə' sözü hansı haldadır?", options: ["yönlük", "yerlik", "çıxışlıq", "adlıq"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l1-t13", type: "multiple_choice", prompt: "'evdən' sözü hansı haldadır?", options: ["çıxışlıq", "yerlik", "yönlük", "adlıq"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l1-t14", type: "fill_blank", prompt: "'kitab' sözünün cəm formasını yaz.", accepted: ["kitablar"], xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l1-t15", type: "multiple_choice", prompt: "'Adlıq' hal hansı suala cavab verir?", options: ["kim? nə?", "kimin?", "kimə?", "kimdə?"], correctIndex: 0, xp: 15, skills: ["az.pos.noun_case"] },
          ],
          bonusTasks: [
            { id: "az6-nit1-l1-b1", type: "multiple_choice", prompt: "'mənim kitabım' — 'kitabım' hansı şəkilçini daşıyır?", options: ["mənsubiyyət", "cəm", "hal", "leksik"], correctIndex: 0, xp: 15, skills: ["az.morph.root"] },
            { id: "az6-nit1-l1-b2", type: "multiple_choice", prompt: "'kitabı' (kimi? nəyi?) hansı haldadır?", options: ["təsirlik", "yiyəlik", "yönlük", "yerlik"], correctIndex: 0, xp: 15, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l1-b3", type: "multiple_choice", prompt: "Hansı isim mücərrəd (əşya yox, anlayış) bildirir?", options: ["sevgi", "daş", "ağac", "su"], correctIndex: 0, xp: 15, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l1-b4", type: "fill_blank", prompt: "'şəhər' sözünün yerlik halını yaz (harada?).", accepted: ["şəhərdə", "seherde", "şeherde"], xp: 15, skills: ["az.pos.noun_case"] },
            { id: "az6-nit1-l1-b5", type: "multiple_choice", prompt: "İnsan adları, şəhər adları hansı isimdir?", options: ["xüsusi", "ümumi", "mücərrəd", "konkret"], correctIndex: 0, xp: 15, skills: ["az.pos.noun"] },
          ],
        },
        {
          id: "az6-nit1-l2",
          title: "Sifət",
          intro: "Sifət, onun sualları və müqayisə dərəcələri.",
          sections: [
            { heading: "Sifət nədir?", body: "Əşyanın əlamətini, keyfiyyətini bildirən, 'necə?', 'nə cür?', 'hansı?' suallarına cavab verən nitq hissəsinə sifət deyilir: gözəl, qırmızı, böyük." },
            { heading: "Dərəcələri", body: "Adi dərəcə: gözəl. Azaltma: gözəlimtil, göyümtül. Çoxaltma: gömgöy, qıpqırmızı, əppəyaz." },
            { heading: "İşi", body: "Sifət isimlə işlənir və onu təyin edir: qırmızı alma, hündür ağac, ağıllı uşaq." },
          ],
          tasks: [
            { id: "az6-nit1-l2-t1", type: "multiple_choice", prompt: "Əşyanın əlamətini bildirən nitq hissəsi necə adlanır?", options: ["sifət", "isim", "say", "feil"], correctIndex: 0, xp: 10, skills: ["az.phon.letters"] },
            { id: "az6-nit1-l2-t2", type: "multiple_choice", prompt: "Sifət hansı suala cavab verir?", options: ["necə? nə cür?", "kim? nə?", "neçə?", "nə etdi?"], correctIndex: 0, xp: 10, skills: ["az.pos.adjective"] },
            { id: "az6-nit1-l2-t3", type: "multiple_choice", prompt: "Hansı sifətdir?", options: ["gözəl", "kitab", "oxumaq", "beş"], correctIndex: 0, xp: 10, skills: ["az.pos.adjective"] },
            { id: "az6-nit1-l2-t4", type: "multiple_choice", prompt: "'qırmızı alma'-da sifət hansıdır?", options: ["qırmızı", "alma", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, skills: ["az.pos.adjective"] },
            { id: "az6-nit1-l2-t5", type: "multiple_choice", prompt: "Hansı sifətdir?", options: ["hündür", "ağac", "getmək", "on"], correctIndex: 0, xp: 10, skills: ["az.pos.adjective"] },
            { id: "az6-nit1-l2-t6", type: "multiple_choice", prompt: "'gömgöy' hansı dərəcədədir?", options: ["çoxaltma", "azaltma", "adi", "yönlük"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l2-t7", type: "multiple_choice", prompt: "'göyümtül' hansı dərəcədədir?", options: ["azaltma", "çoxaltma", "adi", "hal"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l2-t8", type: "multiple_choice", prompt: "'gözəl' hansı dərəcədədir?", options: ["adi", "azaltma", "çoxaltma", "cəm"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l2-t9", type: "multiple_choice", prompt: "Hansı sifətdir?", options: ["ağıllı", "uşaq", "yazmaq", "üç"], correctIndex: 0, xp: 10, skills: ["az.pos.adjective"] },
            { id: "az6-nit1-l2-t10", type: "multiple_choice", prompt: "'qıpqırmızı' hansı dərəcədədir?", options: ["çoxaltma", "azaltma", "adi", "hal"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l2-t11", type: "multiple_choice", prompt: "'hündür ağac'-da sifət hansıdır?", options: ["hündür", "ağac", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, skills: ["az.pos.adjective"] },
            { id: "az6-nit1-l2-t12", type: "multiple_choice", prompt: "Sifət hansı sözlə işlənir?", options: ["isimlə", "feillə", "sayla", "əvəzliklə"], correctIndex: 0, xp: 10, skills: ["az.pos.adjective"] },
            { id: "az6-nit1-l2-t13", type: "multiple_choice", prompt: "Hansı söz sifət ola bilər?", options: ["şirin", "getmək", "kitab", "beş"], correctIndex: 0, xp: 10, skills: ["az.pos.adjective"] },
            { id: "az6-nit1-l2-t14", type: "multiple_choice", prompt: "'əppəyaz' hansı dərəcədədir?", options: ["çoxaltma", "azaltma", "adi", "cəm"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l2-t15", type: "multiple_choice", prompt: "'sağlam bədən'-də əlaməti bildirən söz hansıdır?", options: ["sağlam", "bədən", "hər ikisi", "heç biri"], correctIndex: 0, xp: 15, skills: ["az.pos.noun"] },
          ],
          bonusTasks: [
            { id: "az6-nit1-l2-b1", type: "multiple_choice", prompt: "'sarımtıl' hansı dərəcədədir?", options: ["azaltma", "çoxaltma", "adi", "hal"], correctIndex: 0, xp: 15, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l2-b2", type: "multiple_choice", prompt: "'ağappaq' hansı dərəcədədir?", options: ["çoxaltma", "azaltma", "adi", "cəm"], correctIndex: 0, xp: 15, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l2-b3", type: "fill_blank", prompt: "'göy' sifətinin çoxaltma dərəcəsini yaz (gö...).", accepted: ["gömgöy", "gomgoy"], xp: 15, skills: ["az.pos.adjective"] },
            { id: "az6-nit1-l2-b4", type: "multiple_choice", prompt: "Sifət hansı nitq hissəsini təyin edir?", options: ["ismi", "feili", "sayı", "zərfi"], correctIndex: 0, xp: 15, skills: ["az.phon.letters","az.pos.adjective","az.syn.secondary_parts"] },
            { id: "az6-nit1-l2-b5", type: "multiple_choice", prompt: "'daş körpü'-də 'daş' hansı nitq hissəsi rolundadır?", options: ["sifət (əlamət)", "isim", "say", "feil"], correctIndex: 0, xp: 15, skills: ["az.phon.letters"] },
          ],
        },
        {
          id: "az6-nitq1-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az6-nit1-l3",
          title: "Say",
          intro: "Say, onun sualları və növləri (miqdar və sıra).",
          sections: [
            { heading: "Say nədir?", body: "Əşyanın sayını, miqdarını və ya sırasını bildirən, 'neçə?', 'nə qədər?', 'neçənci?' suallarına cavab verən nitq hissəsinə say deyilir: beş, on, birinci." },
            { heading: "Miqdar sayı", body: "Əşyanın sayını bildirir (neçə? nə qədər?): iki, on, yüz. Növləri: müəyyən (beş), qeyri-müəyyən (bir neçə), kəsr (yarım)." },
            { heading: "Sıra sayı", body: "Əşyanın sırasını bildirir (neçənci?): birinci, ikinci, onuncu. '-ıncı, -inci, -uncu, -üncü' şəkilçisi ilə düzəlir." },
          ],
          tasks: [
            { id: "az6-nit1-l3-t1", type: "multiple_choice", prompt: "Əşyanın sayını bildirən nitq hissəsi necə adlanır?", options: ["say", "sifət", "isim", "feil"], correctIndex: 0, xp: 10, skills: ["az.phon.letters","az.pos.numeral"] },
            { id: "az6-nit1-l3-t2", type: "multiple_choice", prompt: "Say hansı suala cavab verir?", options: ["neçə? neçənci?", "kim? nə?", "necə?", "nə etdi?"], correctIndex: 0, xp: 10, skills: ["az.pos.numeral"] },
            { id: "az6-nit1-l3-t3", type: "multiple_choice", prompt: "Hansı saydır?", options: ["beş", "gözəl", "kitab", "getmək"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l3-t4", type: "multiple_choice", prompt: "'on kitab'-da say hansıdır?", options: ["on", "kitab", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, skills: ["az.pos.numeral"] },
            { id: "az6-nit1-l3-t5", type: "multiple_choice", prompt: "'beş' hansı say növüdür?", options: ["miqdar", "sıra", "hal", "zaman"], correctIndex: 0, xp: 10, skills: ["az.pos.numeral"] },
            { id: "az6-nit1-l3-t6", type: "multiple_choice", prompt: "'birinci' hansı say növüdür?", options: ["sıra", "miqdar", "kəsr", "hal"], correctIndex: 0, xp: 10, skills: ["az.pos.numeral"] },
            { id: "az6-nit1-l3-t7", type: "multiple_choice", prompt: "Sıra sayı hansı suala cavab verir?", options: ["neçənci?", "neçə?", "necə?", "kim?"], correctIndex: 0, xp: 10, skills: ["az.pos.numeral"] },
            { id: "az6-nit1-l3-t8", type: "multiple_choice", prompt: "Miqdar sayı hansı suala cavab verir?", options: ["neçə? nə qədər?", "neçənci?", "necə?", "hara?"], correctIndex: 0, xp: 10, skills: ["az.pos.numeral"] },
            { id: "az6-nit1-l3-t9", type: "fill_blank", prompt: "'iki' sözündən sıra sayı düzəlt (iki...).", accepted: ["ikinci"], xp: 10, skills: ["az.pos.numeral"] },
            { id: "az6-nit1-l3-t10", type: "multiple_choice", prompt: "'yarım' hansı say növüdür?", options: ["kəsr", "sıra", "sıra deyil", "miqdar"], correctIndex: 0, xp: 10, skills: ["az.pos.numeral"] },
            { id: "az6-nit1-l3-t11", type: "multiple_choice", prompt: "'bir neçə' hansı say növüdür?", options: ["qeyri-müəyyən miqdar", "sıra", "kəsr", "müəyyən"], correctIndex: 0, xp: 10, skills: ["az.pos.numeral"] },
            { id: "az6-nit1-l3-t12", type: "multiple_choice", prompt: "Hansı sıra sayıdır?", options: ["onuncu", "on", "yüz", "iki"], correctIndex: 0, xp: 10, skills: ["az.pos.numeral"] },
            { id: "az6-nit1-l3-t13", type: "multiple_choice", prompt: "Hansı miqdar sayıdır?", options: ["yüz", "birinci", "ikinci", "onuncu"], correctIndex: 0, xp: 10, skills: ["az.pos.numeral"] },
            { id: "az6-nit1-l3-t14", type: "fill_blank", prompt: "'üç' sözündən sıra sayı düzəlt.", accepted: ["üçüncü", "ucuncu"], xp: 10, skills: ["az.pos.numeral"] },
            { id: "az6-nit1-l3-t15", type: "multiple_choice", prompt: "'yeddinci sinif'-də say hansıdır?", options: ["yeddinci", "sinif", "hər ikisi", "heç biri"], correctIndex: 0, xp: 15, skills: ["az.pos.numeral"] },
          ],
          bonusTasks: [
            { id: "az6-nit1-l3-b1", type: "fill_blank", prompt: "'beş' sözündən sıra sayı düzəlt.", accepted: ["beşinci", "besinci"], xp: 15, skills: ["az.pos.numeral"] },
            { id: "az6-nit1-l3-b2", type: "multiple_choice", prompt: "'dörddə bir' hansı say növüdür?", options: ["kəsr", "sıra", "müəyyən miqdar", "qeyri-müəyyən"], correctIndex: 0, xp: 15, skills: ["az.pos.numeral"] },
            { id: "az6-nit1-l3-b3", type: "multiple_choice", prompt: "Sıra sayı düzəldən şəkilçi hansıdır?", options: ["-ıncı/-inci", "-lar/-lər", "-da/-də", "-çı/-çi"], correctIndex: 0, xp: 15, skills: ["az.morph.root","az.pos.numeral"] },
            { id: "az6-nit1-l3-b4", type: "multiple_choice", prompt: "'bir çox' hansı say növüdür?", options: ["qeyri-müəyyən", "müəyyən", "sıra", "kəsr"], correctIndex: 0, xp: 15, skills: ["az.pos.numeral"] },
            { id: "az6-nit1-l3-b5", type: "multiple_choice", prompt: "Hansı kəsr sayıdır?", options: ["yarım", "beş", "on", "birinci"], correctIndex: 0, xp: 15, skills: ["az.pos.numeral"] },
          ],
        },
        {
          id: "az6-nit1-l4",
          title: "Əvəzlik",
          intro: "İsim, sifət və ya sayın yerində işlənən əvəzliklər və onların növləri.",
          sections: [
            { heading: "Əvəzlik nədir?", body: "İsim, sifət, say və ya digər nitq hissəsinin yerində işlənən sözlərə əvəzlik deyilir: mən, sən, o, bu, hansı." },
            { heading: "Şəxs əvəzlikləri", body: "mən, sən, o (tək); biz, siz, onlar (cəm). Şəxsləri əvəz edir." },
            { heading: "Digər növlər", body: "İşarə: bu, o, həmin. Sual: kim?, nə?, hansı?, neçə? Qeyri-müəyyən: kimsə, nəsə, hər kəs. İnkar: heç kim, heç nə." },
          ],
          tasks: [
            { id: "az6-nit1-l4-t1", type: "multiple_choice", prompt: "İsim, sifət, sayın yerində işlənən söz necə adlanır?", options: ["əvəzlik", "sifət", "say", "feil"], correctIndex: 0, xp: 10, skills: ["az.pos.numeral","az.pos.adjective"] },
            { id: "az6-nit1-l4-t2", type: "multiple_choice", prompt: "Hansı şəxs əvəzliyidir?", options: ["mən", "kitab", "gözəl", "beş"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l4-t3", type: "multiple_choice", prompt: "'biz, siz, onlar' hansı əvəzlikdir?", options: ["şəxs (cəm)", "işarə", "sual", "inkar"], correctIndex: 0, xp: 10, skills: ["az.pos.pronoun"] },
            { id: "az6-nit1-l4-t4", type: "multiple_choice", prompt: "'bu, o, həmin' hansı əvəzlikdir?", options: ["işarə", "şəxs", "sual", "inkar"], correctIndex: 0, xp: 10, skills: ["az.pos.pronoun"] },
            { id: "az6-nit1-l4-t5", type: "multiple_choice", prompt: "'kim?, nə?, hansı?' hansı əvəzlikdir?", options: ["sual", "şəxs", "işarə", "inkar"], correctIndex: 0, xp: 10, skills: ["az.pos.pronoun"] },
            { id: "az6-nit1-l4-t6", type: "multiple_choice", prompt: "'heç kim, heç nə' hansı əvəzlikdir?", options: ["inkar", "sual", "işarə", "şəxs"], correctIndex: 0, xp: 10, skills: ["az.pos.pronoun"] },
            { id: "az6-nit1-l4-t7", type: "multiple_choice", prompt: "'kimsə, nəsə' hansı əvəzlikdir?", options: ["qeyri-müəyyən", "inkar", "sual", "şəxs"], correctIndex: 0, xp: 10, skills: ["az.pos.pronoun"] },
            { id: "az6-nit1-l4-t8", type: "multiple_choice", prompt: "Hansı şəxs əvəzliyidir?", options: ["sən", "bu", "kim", "heç kim"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l4-t9", type: "multiple_choice", prompt: "'o' əvəzliyi kimi əvəz edir?", options: ["III şəxsi (tək)", "I şəxsi", "II şəxsi", "cəmi"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l4-t10", type: "multiple_choice", prompt: "Hansı işarə əvəzliyidir?", options: ["həmin", "mən", "kim", "heç nə"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l4-t11", type: "multiple_choice", prompt: "Hansı sual əvəzliyidir?", options: ["hansı", "bu", "mən", "kimsə"], correctIndex: 0, xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l4-t12", type: "multiple_choice", prompt: "'hər kəs' hansı əvəzlikdir?", options: ["qeyri-müəyyən", "inkar", "sual", "şəxs"], correctIndex: 0, xp: 10, skills: ["az.pos.pronoun"] },
            { id: "az6-nit1-l4-t13", type: "fill_blank", prompt: "I şəxsin təki olan şəxs əvəzliyini yaz.", accepted: ["mən", "men"], xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l4-t14", type: "fill_blank", prompt: "II şəxsin təki olan şəxs əvəzliyini yaz.", accepted: ["sən", "sen"], xp: 10, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l4-t15", type: "multiple_choice", prompt: "'Onlar gəldi' cümləsində əvəzlik hansıdır?", options: ["onlar", "gəldi", "hər ikisi", "heç biri"], correctIndex: 0, xp: 15, skills: ["az.pos.pronoun"] },
          ],
          bonusTasks: [
            { id: "az6-nit1-l4-b1", type: "multiple_choice", prompt: "'özüm, özün' hansı əvəzlikdir?", options: ["qayıdış", "işarə", "sual", "inkar"], correctIndex: 0, xp: 15, skills: ["az.pos.pronoun"] },
            { id: "az6-nit1-l4-b2", type: "multiple_choice", prompt: "'heç bir' hansı əvəzlikdir?", options: ["inkar", "qeyri-müəyyən", "sual", "şəxs"], correctIndex: 0, xp: 15, skills: ["az.pos.pronoun"] },
            { id: "az6-nit1-l4-b3", type: "multiple_choice", prompt: "Əvəzlik nə üçün işlənir?", options: ["təkrarın qarşısını almaq", "saymaq", "əlamət bildirmək", "hərəkət bildirmək"], correctIndex: 0, xp: 15, skills: ["az.pos.pronoun"] },
            { id: "az6-nit1-l4-b4", type: "fill_blank", prompt: "III şəxsin cəmi olan şəxs əvəzliyini yaz.", accepted: ["onlar"], xp: 15, skills: ["az.pos.noun"] },
            { id: "az6-nit1-l4-b5", type: "multiple_choice", prompt: "'bu kitab'-da əvəzlik hansıdır?", options: ["bu", "kitab", "hər ikisi", "heç biri"], correctIndex: 0, xp: 15, skills: ["az.pos.pronoun"] },
          ],
        },
        {
          id: "az6-nitq1-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        }
      ],
    },

    // ═══════════════ 5. Nitq hissələri II ═══════════════
    {
      id: "az6-nitq2",
      title: "Nitq hissələri II: feil, zərf",
      description:
        "Feil (zaman, şəxs, təsdiq-inkar), zərf (növləri).",
      lessons: [
        {
          id: "az6-nit2-l1",
          title: "Feil",
          intro: "Feil, onun sualları, zamanları və təsdiq-inkar forması.",
          sections: [
            { heading: "Feil nədir?", body: "İş, hal, hərəkət bildirən, 'nə etdi?', 'nə edir?', 'nə edəcək?' suallarına cavab verən nitq hissəsinə feil deyilir: getdi, oxuyur, yazacaq." },
            { heading: "Zamanlar", body: "Keçmiş zaman: getdi, oxudu. İndiki zaman: gedir, oxuyur. Gələcək zaman: gedəcək, oxuyacaq." },
            { heading: "Təsdiq və inkar", body: "Təsdiq: gəldi. İnkar '-ma, -mə' şəkilçisi ilə: gəlmədi, oxumadı, yazmır." },
          ],
          tasks: [
            { id: "az6-nit2-l1-t1", type: "multiple_choice", prompt: "İş, hərəkət bildirən nitq hissəsi necə adlanır?", options: ["feil", "isim", "sifət", "say"], correctIndex: 0, xp: 10, skills: ["az.phon.letters","az.pos.verb"] },
            { id: "az6-nit2-l1-t2", type: "multiple_choice", prompt: "Feil hansı suala cavab verir?", options: ["nə etdi? nə edir?", "kim? nə?", "necə?", "neçə?"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az6-nit2-l1-t3", type: "multiple_choice", prompt: "Hansı feildir?", options: ["oxuyur", "kitab", "gözəl", "beş"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az6-nit2-l1-t4", type: "multiple_choice", prompt: "'getdi' hansı zamandadır?", options: ["keçmiş", "indiki", "gələcək", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az6-nit2-l1-t5", type: "multiple_choice", prompt: "'gedir' hansı zamandadır?", options: ["indiki", "keçmiş", "gələcək", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az6-nit2-l1-t6", type: "multiple_choice", prompt: "'gedəcək' hansı zamandadır?", options: ["gələcək", "keçmiş", "indiki", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az6-nit2-l1-t7", type: "multiple_choice", prompt: "İnkar şəkilçisi hansıdır?", options: ["-ma/-mə", "-lar/-lər", "-da/-də", "-çı/-çi"], correctIndex: 0, xp: 10, skills: ["az.morph.root"] },
            { id: "az6-nit2-l1-t8", type: "fill_blank", prompt: "'gəldi' feilinin inkar formasını yaz.", accepted: ["gəlmədi", "gelmedi"], xp: 10, skills: ["az.pos.verb"] },
            { id: "az6-nit2-l1-t9", type: "multiple_choice", prompt: "Hansı feildir?", options: ["yazacaq", "dəftər", "ağıllı", "on"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az6-nit2-l1-t10", type: "multiple_choice", prompt: "'oxudu' hansı zamandadır?", options: ["keçmiş", "indiki", "gələcək", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az6-nit2-l1-t11", type: "multiple_choice", prompt: "'yazır' hansı zamandadır?", options: ["indiki", "keçmiş", "gələcək", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az6-nit2-l1-t12", type: "fill_blank", prompt: "'oxudu' feilinin inkar formasını yaz.", accepted: ["oxumadı", "oxumadi"], xp: 10, skills: ["az.pos.verb"] },
            { id: "az6-nit2-l1-t13", type: "multiple_choice", prompt: "'gəlmədi' — təsdiq, yoxsa inkar?", options: ["inkar", "təsdiq", "sual", "əmr"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az6-nit2-l1-t14", type: "multiple_choice", prompt: "'yazacaq' hansı zamandadır?", options: ["gələcək", "keçmiş", "indiki", "yoxdur"], correctIndex: 0, xp: 10, skills: ["az.pos.verb"] },
            { id: "az6-nit2-l1-t15", type: "multiple_choice", prompt: "'Uşaq oyunu bitirdi' cümləsində feil hansıdır?", options: ["bitirdi", "uşaq", "oyunu", "heç biri"], correctIndex: 0, xp: 15, skills: ["az.pos.verb"] },
          ],
          bonusTasks: [
            { id: "az6-nit2-l1-b1", type: "fill_blank", prompt: "'yazır' feilinin inkar formasını yaz.", accepted: ["yazmır", "yazmir"], xp: 15, skills: ["az.pos.verb"] },
            { id: "az6-nit2-l1-b2", type: "multiple_choice", prompt: "'oxu!' hansı formadadır?", options: ["əmr", "keçmiş", "gələcək", "inkar"], correctIndex: 0, xp: 15, skills: ["az.pos.verb"] },
            { id: "az6-nit2-l1-b3", type: "multiple_choice", prompt: "'gedəcəyəm' feili hansı şəxsdədir?", options: ["I şəxs (mən)", "II şəxs", "III şəxs", "cəm"], correctIndex: 0, xp: 15, skills: ["az.pos.verb"] },
            { id: "az6-nit2-l1-b4", type: "fill_blank", prompt: "'gələcək' feilinin inkar formasını yaz.", accepted: ["gəlməyəcək", "gelmeyecek"], xp: 15, skills: ["az.pos.verb_tense"] },
            { id: "az6-nit2-l1-b5", type: "multiple_choice", prompt: "Feil hansı əlaməti daşıyır?", options: ["zaman", "hal", "dərəcə", "sıra"], correctIndex: 0, xp: 15, skills: ["az.pos.verb"] },
          ],
        },
        {
          id: "az6-nit2-l2",
          title: "Zərf",
          intro: "Feilin əlamətini bildirən zərf və onun növləri.",
          sections: [
            { heading: "Zərf nədir?", body: "İşin, hərəkətin əlamətini, tərzini, zamanını, yerini bildirən nitq hissəsinə zərf deyilir: tez, yavaş, dünən, burada." },
            { heading: "Növləri", body: "Tərz zərfi (necə?): tez, yavaş, gözəl. Zaman zərfi (nə vaxt?): dünən, bu gün, indi. Yer zərfi (harada?): burada, orada, hər yerdə. Miqdar zərfi (nə qədər?): çox, az." },
            { heading: "İşi", body: "Zərf feillə işlənir və onu izah edir: tez getdi, dünən gəldi, çox oxudu." },
          ],
          tasks: [
            { id: "az6-nit2-l2-t1", type: "multiple_choice", prompt: "İşin əlamətini bildirən nitq hissəsi necə adlanır?", options: ["zərf", "sifət", "feil", "say"], correctIndex: 0, xp: 10, skills: ["az.phon.letters"] },
            { id: "az6-nit2-l2-t2", type: "multiple_choice", prompt: "Hansı zərfdir?", options: ["tez", "kitab", "gözəl alma", "beş"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az6-nit2-l2-t3", type: "multiple_choice", prompt: "'tez getdi'-də zərf hansıdır?", options: ["tez", "getdi", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az6-nit2-l2-t4", type: "multiple_choice", prompt: "'dünən' hansı zərf növüdür?", options: ["zaman", "yer", "tərz", "miqdar"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az6-nit2-l2-t5", type: "multiple_choice", prompt: "'burada' hansı zərf növüdür?", options: ["yer", "zaman", "tərz", "miqdar"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az6-nit2-l2-t6", type: "multiple_choice", prompt: "'tez' hansı zərf növüdür?", options: ["tərz", "zaman", "yer", "miqdar"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az6-nit2-l2-t7", type: "multiple_choice", prompt: "'çox' hansı zərf növüdür?", options: ["miqdar", "yer", "zaman", "tərz"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az6-nit2-l2-t8", type: "multiple_choice", prompt: "Tərz zərfi hansı suala cavab verir?", options: ["necə?", "nə vaxt?", "harada?", "nə qədər?"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az6-nit2-l2-t9", type: "multiple_choice", prompt: "Zaman zərfi hansı suala cavab verir?", options: ["nə vaxt?", "necə?", "harada?", "kim?"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb","az.pos.verb_tense"] },
            { id: "az6-nit2-l2-t10", type: "multiple_choice", prompt: "Yer zərfi hansı suala cavab verir?", options: ["harada?", "necə?", "nə vaxt?", "neçə?"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az6-nit2-l2-t11", type: "multiple_choice", prompt: "'bu gün' hansı zərf növüdür?", options: ["zaman", "yer", "tərz", "miqdar"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az6-nit2-l2-t12", type: "multiple_choice", prompt: "'yavaş' hansı zərf növüdür?", options: ["tərz", "zaman", "yer", "miqdar"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az6-nit2-l2-t13", type: "multiple_choice", prompt: "'az' hansı zərf növüdür?", options: ["miqdar", "tərz", "yer", "zaman"], correctIndex: 0, xp: 10, skills: ["az.pos.adverb"] },
            { id: "az6-nit2-l2-t14", type: "multiple_choice", prompt: "Zərf hansı nitq hissəsi ilə işlənir?", options: ["feillə", "isimlə", "sayla", "əvəzliklə"], correctIndex: 0, xp: 10, skills: ["az.phon.letters","az.pos.adverb"] },
            { id: "az6-nit2-l2-t15", type: "multiple_choice", prompt: "'O, gözəl oxuyur' — zərf hansıdır?", options: ["gözəl", "oxuyur", "o", "heç biri"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb"] },
          ],
          bonusTasks: [
            { id: "az6-nit2-l2-b1", type: "multiple_choice", prompt: "'irəli' hansı zərf növüdür?", options: ["yer", "zaman", "tərz", "miqdar"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb"] },
            { id: "az6-nit2-l2-b2", type: "multiple_choice", prompt: "'həmişə' hansı zərf növüdür?", options: ["zaman", "yer", "tərz", "miqdar"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb"] },
            { id: "az6-nit2-l2-b3", type: "multiple_choice", prompt: "'birlikdə' hansı zərf növüdür?", options: ["tərz", "zaman", "yer", "miqdar"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb"] },
            { id: "az6-nit2-l2-b4", type: "multiple_choice", prompt: "Zərflə sifətin fərqi nədir?", options: ["zərf feili, sifət ismi izah edir", "eynidir", "fərqi yoxdur", "hər ikisi feili izah edir"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb","az.pos.adjective"] },
            { id: "az6-nit2-l2-b5", type: "multiple_choice", prompt: "'gec' hansı zərf növüdür?", options: ["zaman", "yer", "tərz", "miqdar"], correctIndex: 0, xp: 15, skills: ["az.pos.adverb"] },
          ],
        },
      ],
    },

    // ═══════════════ 6. Orfoqrafiya, durğu işarələri və mətn ═══════════════
    {
      id: "az6-orfoqrafiya",
      title: "Orfoqrafiya, durğu işarələri və mətn",
      description:
        "Düzgün yazı qaydaları, durğu işarələri və mətnin qurulması.",
      lessons: [
        {
          id: "az6-orf-l1",
          title: "Orfoqrafiya (düzgün yazı)",
          intro: "Sözlərin düzgün yazılış qaydaları.",
          sections: [
            { heading: "Orfoqrafiya nədir?", body: "Sözlərin düzgün yazılış qaydalarını öyrədən bölmə orfoqrafiyadır. Məqsəd — hamının eyni cür, düzgün yazmasıdır." },
            { heading: "Bəzi qaydalar", body: "Xüsusi isimlər böyük hərflə: Bakı, Nizami. Alınma sözlərdə ahəng qanunu pozula bilər: kitab, məktəb. Bəzi sözlər bitişik, bəziləri defislə yazılır." },
            { heading: "Diqqət", body: "Söz köçürərkən heca ilə köçürülür. Bir hərf sətirdə tək qala bilməz." },
          ],
          tasks: [
            { id: "az6-orf-l1-t1", type: "multiple_choice", prompt: "Sözlərin düzgün yazılışını öyrədən bölmə necə adlanır?", options: ["orfoqrafiya", "orfoepiya", "leksika", "fonetika"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az6-orf-l1-t2", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["Azərbaycan", "azərbaycan", "AZƏRBAYCAN", "azerbaijan"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az6-orf-l1-t3", type: "multiple_choice", prompt: "Xüsusi isimlər necə yazılır?", options: ["böyük hərflə", "kiçik hərflə", "dırnaqda", "defislə"], correctIndex: 0, xp: 10, skills: ["az.pos.noun","az.orth.capital"] },
            { id: "az6-orf-l1-t4", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["müəllim", "muellim", "müəllm", "Müəllim (cümlə ortasında)"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az6-orf-l1-t5", type: "multiple_choice", prompt: "Söz sətirdən sətrə necə köçürülür?", options: ["heca ilə", "hərf-hərf", "istənilən yerdən", "köçürülmür"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az6-orf-l1-t6", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["kitab", "kitap", "gitab", "kitabb"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az6-orf-l1-t7", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["dəftər", "deftər", "dəftar", "dəptər"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az6-orf-l1-t8", type: "multiple_choice", prompt: "İnsan adı hansı hərflə başlayır?", options: ["böyük", "kiçik", "fərqi yoxdur", "hamısı böyük"], correctIndex: 0, xp: 10, skills: ["az.phon.letters"] },
            { id: "az6-orf-l1-t9", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["şagird", "şagirt", "şaqird", "şagrid"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az6-orf-l1-t10", type: "multiple_choice", prompt: "Bir hərf sətirdə tək qala bilərmi (köçürəndə)?", options: ["Xeyr", "Bəli"], correctIndex: 0, xp: 10, skills: ["az.phon.letters"] },
            { id: "az6-orf-l1-t11", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["məktəb", "mətkəb", "məkdəb", "məktəp"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az6-orf-l1-t12", type: "multiple_choice", prompt: "Ölkə adları necə yazılır?", options: ["böyük hərflə", "kiçik hərflə", "dırnaqda", "defislə"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az6-orf-l1-t13", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["qələm", "qelem", "kələm", "gələm"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az6-orf-l1-t14", type: "multiple_choice", prompt: "Cümlə hansı hərflə başlayır?", options: ["böyük", "kiçik", "fərqi yoxdur", "rəqəmlə"], correctIndex: 0, xp: 10, skills: ["az.phon.letters"] },
            { id: "az6-orf-l1-t15", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["Nizami Gəncəvi", "nizami gəncəvi", "NİZAMİ gəncəvi", "Nizami gəncəvi"], correctIndex: 0, xp: 15, skills: ["az.orth.spelling"] },
          ],
          bonusTasks: [
            { id: "az6-orf-l1-b1", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["tələbə", "telebe", "tələba", "tələbe"], correctIndex: 0, xp: 15, skills: ["az.orth.spelling"] },
            { id: "az6-orf-l1-b2", type: "multiple_choice", prompt: "'ana dili' ifadəsi necə yazılır?", options: ["kiçik hərflə (ümumi)", "böyük hərflə", "defislə", "dırnaqda"], correctIndex: 0, xp: 15, skills: ["az.orth.spelling"] },
            { id: "az6-orf-l1-b3", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["kompüter", "kompyuter", "kompputer", "komputer"], correctIndex: 0, xp: 15, skills: ["az.orth.spelling"] },
            { id: "az6-orf-l1-b4", type: "multiple_choice", prompt: "Bayram adları (Novruz) necə yazılır?", options: ["böyük hərflə", "kiçik hərflə", "defislə", "dırnaqsız kiçik"], correctIndex: 0, xp: 15, skills: ["az.orth.spelling"] },
            { id: "az6-orf-l1-b5", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["riyaziyyat", "riaziyat", "riyazyyat", "riyaziyat"], correctIndex: 0, xp: 15, skills: ["az.orth.spelling"] },
          ],
        },
        {
          id: "az6-orf-l2",
          title: "Durğu işarələri",
          intro: "Cümlə sonunda və içində işlənən durğu işarələri.",
          sections: [
            { heading: "Cümlə sonunda", body: "Nöqtə (.) — nəqli cümlədə. Sual işarəsi (?) — sual cümləsində. Nida işarəsi (!) — nida (hiss) cümləsində." },
            { heading: "Cümlə içində", body: "Vergül (,) — həmcins üzvləri, müraciəti ayırır. İki nöqtə (:) — sadalamadan əvvəl. Tire (—) — dialoqda, izahda." },
            { heading: "Dırnaq", body: "Dırnaq («») — sitat və başqasının nitqini göstərir." },
          ],
          tasks: [
            { id: "az6-orf-l2-t1", type: "multiple_choice", prompt: "Nəqli cümlənin sonunda hansı işarə qoyulur?", options: ["nöqtə (.)", "sual (?)", "nida (!)", "vergül (,)"], correctIndex: 0, xp: 10, skills: ["az.syn.sentence_type"] },
            { id: "az6-orf-l2-t2", type: "multiple_choice", prompt: "Sual cümləsinin sonunda hansı işarə qoyulur?", options: ["sual (?)", "nöqtə (.)", "nida (!)", "tire (—)"], correctIndex: 0, xp: 10, skills: ["az.syn.sentence_type"] },
            { id: "az6-orf-l2-t3", type: "multiple_choice", prompt: "Nida (hiss) cümləsinin sonunda hansı işarə qoyulur?", options: ["nida (!)", "nöqtə (.)", "sual (?)", "vergül (,)"], correctIndex: 0, xp: 10, skills: ["az.pos.modal"] },
            { id: "az6-orf-l2-t4", type: "multiple_choice", prompt: "Həmcins üzvləri hansı işarə ayırır?", options: ["vergül (,)", "nöqtə (.)", "sual (?)", "nida (!)"], correctIndex: 0, xp: 10, skills: ["az.syn.homogeneous"] },
            { id: "az6-orf-l2-t5", type: "multiple_choice", prompt: "'Sən hara gedirsən' cümləsinin sonunda hansı işarə olmalıdır?", options: ["?", ".", "!", ","], correctIndex: 0, xp: 10, skills: ["az.syn.sentence"] },
            { id: "az6-orf-l2-t6", type: "multiple_choice", prompt: "'Nə gözəl mənzərədir' cümləsinin sonunda hansı işarə olmalıdır?", options: ["!", ".", "?", ","], correctIndex: 0, xp: 10, skills: ["az.syn.sentence"] },
            { id: "az6-orf-l2-t7", type: "multiple_choice", prompt: "'Mən məktəbə gedirəm' cümləsinin sonunda hansı işarə olmalıdır?", options: [".", "?", "!", ":"], correctIndex: 0, xp: 10, skills: ["az.syn.sentence"] },
            { id: "az6-orf-l2-t8", type: "multiple_choice", prompt: "Sadalamadan əvvəl hansı işarə qoyulur?", options: ["iki nöqtə (:)", "nöqtə (.)", "tire (—)", "sual (?)"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az6-orf-l2-t9", type: "multiple_choice", prompt: "Dialoqda replikanın əvvəlində hansı işarə qoyulur?", options: ["tire (—)", "nöqtə (.)", "vergül (,)", "sual (?)"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az6-orf-l2-t10", type: "multiple_choice", prompt: "Sitatı göstərmək üçün hansı işarə işlənir?", options: ["dırnaq («»)", "nöqtə (.)", "tire (—)", "vergül (,)"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az6-orf-l2-t11", type: "multiple_choice", prompt: "'Ay ana!' — burada hansı işarə var?", options: ["nida (!)", "nöqtə (.)", "sual (?)", "vergül (,)"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az6-orf-l2-t12", type: "multiple_choice", prompt: "Müraciəti (Ay Əli, gəl!) hansı işarə ayırır?", options: ["vergül (,)", "nöqtə (.)", "tire (—)", "iki nöqtə (:)"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az6-orf-l2-t13", type: "multiple_choice", prompt: "'Bu nədir' cümləsi hansı işarə ilə bitir?", options: ["?", ".", "!", ";"], correctIndex: 0, xp: 10, skills: ["az.syn.sentence"] },
            { id: "az6-orf-l2-t14", type: "multiple_choice", prompt: "Nəqli cümlə nə bildirir?", options: ["məlumat verir", "sual verir", "hiss bildirir", "əmr edir"], correctIndex: 0, xp: 10, skills: ["az.syn.sentence_type"] },
            { id: "az6-orf-l2-t15", type: "multiple_choice", prompt: "'Kitab, dəftər, qələm aldım' — vergüllər nəyi ayırır?", options: ["həmcins üzvləri", "cümlələri", "müraciəti", "sitatı"], correctIndex: 0, xp: 15, skills: ["az.orth.punctuation"] },
          ],
          bonusTasks: [
            { id: "az6-orf-l2-b1", type: "multiple_choice", prompt: "'Yaşasın Vətən!' cümləsi hansı işarə ilə bitir?", options: ["!", ".", "?", ","], correctIndex: 0, xp: 15, skills: ["az.syn.sentence"] },
            { id: "az6-orf-l2-b2", type: "multiple_choice", prompt: "Nöqtəli vergül (;) nə üçün işlənir?", options: ["mürəkkəb cümlə hissələrini ayırmaq", "sual", "nida", "sitat"], correctIndex: 0, xp: 15, skills: ["az.orth.punctuation"] },
            { id: "az6-orf-l2-b3", type: "multiple_choice", prompt: "'O soruşdu: — Sən kimsən?' — iki nöqtə nəyi göstərir?", options: ["birbaşa nitqi", "sualı", "sonu", "həmcinsliyi"], correctIndex: 0, xp: 15, skills: ["az.orth.punctuation"] },
            { id: "az6-orf-l2-b4", type: "multiple_choice", prompt: "Cümlə sonunda neçə əsas durğu işarəsi işlənə bilər (., ?, !)?", options: ["3", "1", "2", "4"], correctIndex: 0, xp: 15, skills: ["az.syn.sentence","az.orth.punctuation"] },
            { id: "az6-orf-l2-b5", type: "multiple_choice", prompt: "'Necə də gözəldir!' cümləsi hansı növdür?", options: ["nida", "nəqli", "sual", "əmr"], correctIndex: 0, xp: 15, skills: ["az.syn.sentence"] },
          ],
        },
        {
          id: "az6-orfoqrafiya-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az6-orf-l3",
          title: "Mətn",
          intro: "Mətnin qurulması, mövzusu, əsas fikri və hissələri.",
          sections: [
            { heading: "Mətn nədir?", body: "Bir-biri ilə məna və qrammatik cəhətdən bağlı cümlələrin ardıcıllığına mətn deyilir. Mətnin başlığı, mövzusu və əsas fikri olur." },
            { heading: "Hissələri", body: "Mətn adətən üç hissədən ibarətdir: giriş, əsas hissə və nəticə. Hər hissə abzasla ayrılır." },
            { heading: "Mövzu və əsas fikir", body: "Mövzu — mətnin nə haqqında olması. Əsas fikir — müəllifin çatdırmaq istədiyi əsas mesaj." },
          ],
          tasks: [
            { id: "az6-orf-l3-t1", type: "multiple_choice", prompt: "Məna və qrammatik cəhətdən bağlı cümlələr ardıcıllığı necə adlanır?", options: ["mətn", "cümlə", "söz", "abzas"], correctIndex: 0, xp: 10, skills: ["az.syn.sentence"] },
            { id: "az6-orf-l3-t2", type: "multiple_choice", prompt: "Mətn adətən neçə hissədən ibarətdir?", options: ["üç (giriş, əsas, nəticə)", "iki", "bir", "beş"], correctIndex: 0, xp: 10, skills: ["az.text.structure"] },
            { id: "az6-orf-l3-t3", type: "multiple_choice", prompt: "Mətnin ilk hissəsi necə adlanır?", options: ["giriş", "nəticə", "əsas hissə", "başlıq"], correctIndex: 0, xp: 10, skills: ["az.phon.letters","az.text.structure"] },
            { id: "az6-orf-l3-t4", type: "multiple_choice", prompt: "Mətnin son hissəsi necə adlanır?", options: ["nəticə", "giriş", "əsas hissə", "mövzu"], correctIndex: 0, xp: 10, skills: ["az.phon.letters","az.text.structure"] },
            { id: "az6-orf-l3-t5", type: "multiple_choice", prompt: "Mətnin 'nə haqqında olması' necə adlanır?", options: ["mövzu", "başlıq", "abzas", "cümlə"], correctIndex: 0, xp: 10, skills: ["az.text.structure"] },
            { id: "az6-orf-l3-t6", type: "multiple_choice", prompt: "Müəllifin çatdırmaq istədiyi əsas mesaj necə adlanır?", options: ["əsas fikir", "mövzu", "başlıq", "giriş"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az6-orf-l3-t7", type: "multiple_choice", prompt: "Mətnin hissələri nə ilə ayrılır?", options: ["abzasla", "vergüllə", "nöqtə ilə", "tire ilə"], correctIndex: 0, xp: 10, skills: ["az.text.structure"] },
            { id: "az6-orf-l3-t8", type: "multiple_choice", prompt: "Mətnin adı necə adlanır?", options: ["başlıq", "mövzu", "abzas", "giriş"], correctIndex: 0, xp: 10, skills: ["az.text.structure"] },
            { id: "az6-orf-l3-t9", type: "multiple_choice", prompt: "Mətn nədən ibarətdir?", options: ["bağlı cümlələrdən", "təsadüfi sözlərdən", "yalnız bir cümlədən", "rəqəmlərdən"], correctIndex: 0, xp: 10, skills: ["az.text.structure"] },
            { id: "az6-orf-l3-t10", type: "multiple_choice", prompt: "Mövzu ilə əsas fikir eynidirmi?", options: ["Xeyr", "Bəli"], correctIndex: 0, xp: 10, skills: ["az.orth.spelling"] },
            { id: "az6-orf-l3-t11", type: "multiple_choice", prompt: "Mətnin əsas məzmunu hansı hissədədir?", options: ["əsas hissədə", "girişdə", "başlıqda", "yalnız nəticədə"], correctIndex: 0, xp: 10, skills: ["az.text.structure"] },
            { id: "az6-orf-l3-t12", type: "multiple_choice", prompt: "Abzas nədir?", options: ["mətnin bir hissəsi (yeni sətir)", "durğu işarəsi", "cümlə növü", "söz"], correctIndex: 0, xp: 10, skills: ["az.text.structure"] },
            { id: "az6-orf-l3-t13", type: "multiple_choice", prompt: "Yaxşı mətnin cümlələri bir-biri ilə necə olmalıdır?", options: ["bağlı", "əlaqəsiz", "təkrar", "qarışıq"], correctIndex: 0, xp: 10, skills: ["az.syn.sentence","az.text.structure"] },
            { id: "az6-orf-l3-t14", type: "multiple_choice", prompt: "Mətndə giriş nə üçündür?", options: ["mövzunu təqdim etmək", "nəticə çıxarmaq", "sona çatmaq", "başlıq qoymaq"], correctIndex: 0, xp: 10, skills: ["az.text.structure"] },
            { id: "az6-orf-l3-t15", type: "multiple_choice", prompt: "Mətnin sonunda müəllif nə edir?", options: ["nəticə çıxarır", "mövzu açır", "giriş verir", "başlıq seçir"], correctIndex: 0, xp: 15, skills: ["az.text.structure"] },
          ],
          bonusTasks: [
            { id: "az6-orf-l3-b1", type: "multiple_choice", prompt: "Mətnin planı nə üçündür?", options: ["fikirləri ardıcıl düzmək", "durğu işarəsi qoymaq", "söz saymaq", "başlıq gizlətmək"], correctIndex: 0, xp: 15, skills: ["az.text.structure"] },
            { id: "az6-orf-l3-b2", type: "multiple_choice", prompt: "İnşa hansı yazılı işdir?", options: ["mövzu üzrə mətn yaratmaq", "sözləri köçürmək", "sual vermək", "hərf yazmaq"], correctIndex: 0, xp: 15, skills: ["az.orth.spelling"] },
            { id: "az6-orf-l3-b3", type: "multiple_choice", prompt: "Nağıl, hekayə hansı mətn növüdür?", options: ["bədii", "elmi", "rəsmi", "danışıq"], correctIndex: 0, xp: 15, skills: ["az.text.genre","az.text.structure"] },
            { id: "az6-orf-l3-b4", type: "multiple_choice", prompt: "Dərslikdəki qayda mətni hansı növdür?", options: ["elmi", "bədii", "rəsmi", "danışıq"], correctIndex: 0, xp: 15, skills: ["az.text.structure"] },
            { id: "az6-orf-l3-b5", type: "multiple_choice", prompt: "Mətnin başlığı nəyə uyğun olmalıdır?", options: ["mövzuya", "uzunluğuna", "abzas sayına", "durğu işarəsinə"], correctIndex: 0, xp: 15, skills: ["az.text.structure"] },
          ],
        },
        {
          id: "az6-orfoqrafiya-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        }
      ],
    },
  ],
};
