// İngilis dili — 2-ci sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Ədədlər 1-20 və yaş  2) Günlər və aylar  3) Yemək və içki
// 4) Oyuncaqlar və əşyalar (this/that, cəm)  5) Hərəkətlər (verbs)  6) Bədən, geyim, hava.
// 2-ci sinif üçün sadə: şəkil-söz + dinləmə + speakOptions. id prefiksi en2-*.

import type { Subject } from "../types";

export const english2: Subject = {
  slug: "ingilis-dili-2",
  name: "İngilis dili",
  grade: 2,
  icon: "E",
  color: "violet",
  units: [
    // ═══════════════ 1. Ədədlər 1-20 və yaş ═══════════════
    {
      id: "en2-numbers",
      title: "Ədədlər 1-20 və yaş",
      description: "İngiliscə 1-dən 20-yə qədər ədədlər və yaş.",
      lessons: [
        {
          id: "en2-numbers-vocab",
          title: "Numbers 11-20",
          intro: "On birdən iyirmiyə qədər İngiliscə saymaq.",
          sections: [
            { heading: "Sözlər", body: "eleven — 11, twelve — 12, thirteen — 13, fourteen — 14, fifteen — 15, sixteen — 16, seventeen — 17, eighteen — 18, nineteen — 19, twenty — 20." },
            { heading: "Yaş", body: "'How old are you?' — Neçə yaşın var? 'I am eight.' — Səkkiz yaşım var." },
          ],
          tasks: [
            { id: "en2-numbers-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'11' İngiliscə necədir?", options: ["eleven", "twelve", "ten", "twenty"], correctIndex: 0, xp: 10, explanation: "11 ingiliscə eleven olur — 11 və 12 qaydaya uymur, onları əzbərləmək lazımdır.", skills: ["en.vocab.topic"] },
            { id: "en2-numbers-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'12' İngiliscə necədir?", options: ["twelve", "eleven", "twenty", "two"], correctIndex: 0, xp: 10, explanation: "12 ingiliscə twelve olur.", skills: ["en.vocab.topic"] },
            { id: "en2-numbers-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'13' İngiliscə necədir?", options: ["thirteen", "thirty", "three", "thirty-three"], correctIndex: 0, xp: 10, explanation: "13 ingiliscə thirteen olur — three sözü dəyişib thir olur, sonuna -teen qoşulur.", skills: ["en.vocab.topic"] },
            { id: "en2-numbers-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'15' İngiliscə necədir?", options: ["fifteen", "fifty", "five", "fourteen"], correctIndex: 0, xp: 10, explanation: "15 ingiliscə fifteen olur — five sözü dəyişib fif olur, sonuna -teen qoşulur.", skills: ["en.vocab.topic"] },
            { id: "en2-numbers-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'20' İngiliscə necədir?", options: ["twenty", "twelve", "two", "ten"], correctIndex: 0, xp: 10, explanation: "20 ingiliscə twenty olur.", skills: ["en.vocab.topic"] },
            { id: "en2-numbers-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'17' İngiliscə necədir?", options: ["seventeen", "seventy", "seven", "sixteen"], correctIndex: 0, xp: 10, explanation: "17 ingiliscə seventeen olur: seven + teen.", skills: ["en.vocab.topic"] },
            { id: "en2-numbers-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'18' İngiliscə necədir?", options: ["eighteen", "eighty", "eight", "nineteen"], correctIndex: 0, xp: 10, explanation: "18 ingiliscə eighteen olur: eight + teen.", skills: ["en.vocab.topic"] },
            { id: "en2-numbers-vocab-t8", type: "multiple_choice", prompt: "'fourteen' hansı ədəddir?", options: ["14", "40", "4", "13"], correctIndex: 0, xp: 10, explanation: "Fourteen ingiliscə 14 deməkdir. -teen sonluğu 13–19 aralığını bildirir.", skills: ["en.vocab.topic"] },
            { id: "en2-numbers-vocab-t9", type: "multiple_choice", prompt: "'sixteen' hansı ədəddir?", options: ["16", "60", "6", "15"], correctIndex: 0, xp: 10, explanation: "Sixteen ingiliscə 16 deməkdir. 60 isə sixty olardı.", skills: ["en.vocab.topic"] },
            { id: "en2-numbers-vocab-t10", type: "multiple_choice", prompt: "'nineteen' hansı ədəddir?", options: ["19", "90", "9", "18"], correctIndex: 0, xp: 10, explanation: "Nineteen ingiliscə 19 deməkdir. 90 isə ninety olardı.", skills: ["en.vocab.topic"] },
            { id: "en2-numbers-vocab-t11", type: "multiple_choice", prompt: "'twenty' hansı ədəddir?", options: ["20", "12", "2", "10"], correctIndex: 0, xp: 10, explanation: "Twenty ingiliscə 20 deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en2-numbers-vocab-t12", type: "multiple_choice", speakOptions: true, prompt: "'How old are you?' nə deməkdir?", options: ["Neçə yaşın var?", "Adın nədir?", "Necəsən?", "Haralısan?"], correctIndex: 0, xp: 10, explanation: "Old = yaş. Deməli «How old are you?» — «Neçə yaşın var?» deməkdir.", skills: ["en.gram.questions"] },
            { id: "en2-numbers-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "'I am eight.' nə deməkdir?", options: ["Səkkiz yaşım var.", "Adım Aytəkindir.", "Mən yaxşıyam.", "Səkkizinci mərtəbə."], correctIndex: 0, xp: 10, explanation: "Yaşı bildirmək üçün ingiliscə «I am + ədəd» deyilir. Eight = 8, deməli «Səkkiz yaşım var».", skills: ["en.vocab.topic"] },
            { id: "en2-numbers-vocab-t14", type: "multiple_choice", prompt: "'thirteen' hansı ədəddir?", options: ["13", "30", "3", "14"], correctIndex: 0, xp: 10, explanation: "Thirteen ingiliscə 13 deməkdir. 30 isə thirty olardı.", skills: ["en.vocab.topic"] },
            { id: "en2-numbers-vocab-t15", type: "multiple_choice", prompt: "🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎 — İngiliscə neçədir? (11)", options: ["eleven", "twelve", "ten", "nine"], correctIndex: 0, xp: 15, explanation: "Almaları sayaq: 11 dənədir, 11 isə ingiliscə eleven olur.", skills: ["en.vocab.topic"] },
          ],
          bonusTasks: [
            { id: "en2-numbers-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'thirty' hansı ədəddir?", options: ["30", "13", "3", "40"], correctIndex: 0, xp: 15, explanation: "Thirty ingiliscə 30 deməkdir — -ty sonluğu onluqları bildirir.", skills: ["en.vocab.topic"] },
            { id: "en2-numbers-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'fifty' hansı ədəddir?", options: ["50", "15", "5", "40"], correctIndex: 0, xp: 15, explanation: "Fifty ingiliscə 50 deməkdir — -ty sonluğu onluqları bildirir.", skills: ["en.vocab.topic"] },
            { id: "en2-numbers-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'one hundred' hansı ədəddir?", options: ["100", "10", "1000", "1"], correctIndex: 0, xp: 15, explanation: "One hundred ingiliscə 100 deməkdir; hundred = yüz.", skills: ["en.vocab.topic"] },
            { id: "en2-numbers-vocab-b4", type: "multiple_choice", prompt: "'thirteen' və 'thirty' fərqi nədir?", options: ["13 və 30", "eynidir", "3 və 13", "30 və 3"], correctIndex: 0, xp: 15, explanation: "-teen sonluğu 13–19 arası ədədləri, -ty sonluğu isə onluqları bildirir: thirteen = 13, thirty = 30.", skills: ["en.vocab.topic"] },
            { id: "en2-numbers-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'I am ten years old.' nə deməkdir?", options: ["On yaşım var.", "On dəqiqə qaldı.", "Onuncu sinif.", "Saat on."], correctIndex: 0, xp: 15, explanation: "Years old = yaş. Ten = 10, deməli «On yaşım var».", skills: ["en.vocab.topic"] },
          ],
        },
        {
          id: "en2-numbers-listen",
          title: "Dinləmə: ədədlər",
          intro: "Ədədi dinlə və rəqəmini seç.",
          sections: [
            { heading: "Necə işləyir?", body: "Səs düyməsinə bas, İngiliscə ədədi dinlə, düzgün rəqəmi seç." },
          ],
          tasks: [
            { id: "en2-numbers-listen-t1", type: "listening", prompt: "Dinlə və rəqəmini seç.", audioText: "eleven", options: ["11", "12", "10", "20"], correctIndex: 0, xp: 10, explanation: "Səsdə «eleven» deyildi — bu, 11 deməkdir.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-numbers-listen-t2", type: "listening", prompt: "Dinlə və rəqəmini seç.", audioText: "fifteen", options: ["15", "50", "5", "14"], correctIndex: 0, xp: 10, explanation: "Səsdə «fifteen» deyildi. -teen sonluğu var, deməli 15 (50 olsaydı fifty deyilərdi).", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-numbers-listen-t3", type: "listening", prompt: "Dinlə və rəqəmini seç.", audioText: "twenty", options: ["20", "12", "2", "10"], correctIndex: 0, xp: 10, explanation: "Səsdə «twenty» deyildi — bu, 20 deməkdir.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-numbers-listen-t4", type: "listening", prompt: "Dinlə və rəqəmini seç.", audioText: "thirteen", options: ["13", "30", "3", "14"], correctIndex: 0, xp: 10, explanation: "Səsdə «thirteen» deyildi. -teen sonluğu var, deməli 13 (30 olsaydı thirty deyilərdi).", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-numbers-listen-t5", type: "listening", prompt: "Dinlə və rəqəmini seç.", audioText: "eighteen", options: ["18", "80", "8", "19"], correctIndex: 0, xp: 10, explanation: "Səsdə «eighteen» deyildi. -teen sonluğu var, deməli 18.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-numbers-listen-t6", type: "listening", prompt: "Dinlə və rəqəmini seç.", audioText: "sixteen", options: ["16", "60", "6", "15"], correctIndex: 0, xp: 10, explanation: "Səsdə «sixteen» deyildi. -teen sonluğu var, deməli 16.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-numbers-listen-t7", type: "listening", prompt: "Dinlə və rəqəmini seç.", audioText: "twelve", options: ["12", "20", "2", "11"], correctIndex: 0, xp: 10, explanation: "Səsdə «twelve» deyildi — bu, 12 deməkdir.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-numbers-listen-t8", type: "listening", prompt: "Dinlə və rəqəmini seç.", audioText: "nineteen", options: ["19", "90", "9", "18"], correctIndex: 0, xp: 10, explanation: "Səsdə «nineteen» deyildi. -teen sonluğu var, deməli 19.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-numbers-listen-t9", type: "listening", prompt: "Dinlə və rəqəmini seç.", audioText: "fourteen", options: ["14", "40", "4", "13"], correctIndex: 0, xp: 10, explanation: "Səsdə «fourteen» deyildi. -teen sonluğu var, deməli 14.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-numbers-listen-t10", type: "listening", prompt: "Dinlə və rəqəmini seç.", audioText: "seventeen", options: ["17", "70", "7", "16"], correctIndex: 0, xp: 10, explanation: "Səsdə «seventeen» deyildi. -teen sonluğu var, deməli 17.", skills: ["en.vocab.topic","en.listen"] },
          ],
          bonusTasks: [
            { id: "en2-numbers-listen-b1", type: "listening", prompt: "Dinlə və rəqəmini seç.", audioText: "thirty", options: ["30", "13", "3", "33"], correctIndex: 0, xp: 15, explanation: "Səsdə «thirty» deyildi. -ty sonluğu onluğu bildirir, deməli 30.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-numbers-listen-b2", type: "listening", prompt: "Dinlə və rəqəmini seç.", audioText: "fifty", options: ["50", "15", "5", "55"], correctIndex: 0, xp: 15, explanation: "Səsdə «fifty» deyildi. -ty sonluğu onluğu bildirir, deməli 50.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-numbers-listen-b3", type: "multiple_choice", prompt: "'thirteen' və 'thirty' arasındakı fərq nədir?", options: ["13 və 30", "Fərq yoxdur", "İkisi də 13", "İkisi də 30"], correctIndex: 0, xp: 15, explanation: "-teen sonluğu 13–19 arası, -ty sonluğu isə onluqları bildirir: thirteen = 13, thirty = 30.", skills: ["en.vocab.topic"] },
            { id: "en2-numbers-listen-b4", type: "listening", prompt: "Dinlə və rəqəmini seç.", audioText: "eighty", options: ["80", "18", "8", "88"], correctIndex: 0, xp: 15, explanation: "Səsdə «eighty» deyildi. -ty sonluğu onluğu bildirir, deməli 80.", skills: ["en.vocab.topic","en.listen"] },
          ],
        },
        {
          id: "en2-numbers-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en2-numbers-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 2. Günlər və aylar ═══════════════
    {
      id: "en2-days",
      title: "Günlər və aylar (Days & Months)",
      description: "Həftənin günləri və fəsillər.",
      lessons: [
        {
          id: "en2-days-vocab",
          title: "Days & seasons",
          intro: "Həftənin günləri və fəsilləri İngiliscə öyrənək.",
          sections: [
            { heading: "Günlər", body: "Monday — bazar ertəsi, Tuesday — çərşənbə axşamı, Wednesday — çərşənbə, Thursday — cümə axşamı, Friday — cümə, Saturday — şənbə, Sunday — bazar." },
            { heading: "Fəsillər", body: "spring — yaz, summer — yay, autumn — payız, winter — qış." },
          ],
          tasks: [
            { id: "en2-days-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'bazar ertəsi' İngiliscə necədir?", options: ["Monday", "Sunday", "Friday", "Tuesday"], correctIndex: 0, xp: 10, explanation: "«Bazar ertəsi» ingiliscə Monday olur — həftənin ilk iş günüdür.", skills: ["en.vocab.topic"] },
            { id: "en2-days-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'cümə' İngiliscə necədir?", options: ["Friday", "Monday", "Sunday", "Saturday"], correctIndex: 0, xp: 10, explanation: "«Cümə» ingiliscə Friday olur.", skills: ["en.vocab.topic"] },
            { id: "en2-days-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'şənbə' İngiliscə necədir?", options: ["Saturday", "Sunday", "Friday", "Monday"], correctIndex: 0, xp: 10, explanation: "«Şənbə» ingiliscə Saturday olur.", skills: ["en.vocab.topic"] },
            { id: "en2-days-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'bazar' İngiliscə necədir?", options: ["Sunday", "Saturday", "Monday", "Friday"], correctIndex: 0, xp: 10, explanation: "«Bazar» ingiliscə Sunday olur — sun (günəş) sözündən yaranıb.", skills: ["en.vocab.topic"] },
            { id: "en2-days-vocab-t5", type: "multiple_choice", prompt: "'Monday' nə deməkdir?", options: ["bazar ertəsi", "bazar", "cümə", "şənbə"], correctIndex: 0, xp: 10, explanation: "Monday azərbaycanca «bazar ertəsi» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en2-days-vocab-t6", type: "multiple_choice", prompt: "'Sunday' nə deməkdir?", options: ["bazar", "şənbə", "cümə", "bazar ertəsi"], correctIndex: 0, xp: 10, explanation: "Sunday azərbaycanca «bazar» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en2-days-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'yaz' (fəsil) İngiliscə necədir?", options: ["spring", "summer", "autumn", "winter"], correctIndex: 0, xp: 10, explanation: "«Yaz» fəsli ingiliscə spring olur.", skills: ["en.vocab.topic"] },
            { id: "en2-days-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "'yay' İngiliscə necədir?", options: ["summer", "spring", "winter", "autumn"], correctIndex: 0, xp: 10, explanation: "«Yay» ingiliscə summer olur.", skills: ["en.vocab.topic"] },
            { id: "en2-days-vocab-t9", type: "multiple_choice", speakOptions: true, prompt: "'payız' İngiliscə necədir?", options: ["autumn", "summer", "spring", "winter"], correctIndex: 0, xp: 10, explanation: "«Payız» ingiliscə autumn olur (Amerikada fall da deyilir).", skills: ["en.vocab.topic"] },
            { id: "en2-days-vocab-t10", type: "multiple_choice", speakOptions: true, prompt: "'qış' İngiliscə necədir?", options: ["winter", "autumn", "summer", "spring"], correctIndex: 0, xp: 10, explanation: "«Qış» ingiliscə winter olur.", skills: ["en.vocab.topic"] },
            { id: "en2-days-vocab-t11", type: "multiple_choice", prompt: "'summer' nə deməkdir?", options: ["yay", "yaz", "qış", "payız"], correctIndex: 0, xp: 10, explanation: "Summer azərbaycanca «yay» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en2-days-vocab-t12", type: "multiple_choice", prompt: "'winter' nə deməkdir?", options: ["qış", "yay", "yaz", "payız"], correctIndex: 0, xp: 10, explanation: "Winter azərbaycanca «qış» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en2-days-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "'today' nə deməkdir?", options: ["bu gün", "sabah", "dünən", "həftə"], correctIndex: 0, xp: 10, explanation: "Today azərbaycanca «bu gün» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en2-days-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'tomorrow' nə deməkdir?", options: ["sabah", "bu gün", "dünən", "indi"], correctIndex: 0, xp: 10, explanation: "Tomorrow azərbaycanca «sabah» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en2-days-vocab-t15", type: "multiple_choice", speakOptions: true, prompt: "'week' nə deməkdir?", options: ["həftə", "gün", "ay", "il"], correctIndex: 0, xp: 15, explanation: "Week azərbaycanca «həftə» deməkdir.", skills: ["en.vocab.topic"] },
          ],
          bonusTasks: [
            { id: "en2-days-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'yesterday' nə deməkdir?", options: ["dünən", "bu gün", "sabah", "indi"], correctIndex: 0, xp: 15, explanation: "Yesterday azərbaycanca «dünən» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en2-days-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'month' nə deməkdir?", options: ["ay", "həftə", "gün", "il"], correctIndex: 0, xp: 15, explanation: "Month azərbaycanca təqvim «ayı» deməkdir. Göydəki ay isə moon-dur.", skills: ["en.vocab.topic"] },
            { id: "en2-days-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'January' hansı aydır?", options: ["yanvar", "iyun", "may", "dekabr"], correctIndex: 0, xp: 15, explanation: "January ilin birinci ayıdır — azərbaycanca yanvar.", skills: ["en.vocab.topic"] },
            { id: "en2-days-vocab-b4", type: "multiple_choice", prompt: "'Wednesday' nə deməkdir?", options: ["çərşənbə", "cümə", "şənbə", "bazar"], correctIndex: 0, xp: 15, explanation: "Wednesday azərbaycanca «çərşənbə» deməkdir — həftənin ortasıdır.", skills: ["en.vocab.topic"] },
            { id: "en2-days-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'year' nə deməkdir?", options: ["il", "ay", "həftə", "gün"], correctIndex: 0, xp: 15, explanation: "Year azərbaycanca «il» deməkdir.", skills: ["en.vocab.topic"] },
          ],
        },
        {
          id: "en2-days-when",
          title: "When? Today & tomorrow",
          intro: "Vaxt bildirən sözləri öyrənək.",
          sections: [
            { heading: "Vaxt sözləri", body: "today — bu gün, tomorrow — sabah, yesterday — dünən, now — indi." },
            { heading: "Sual", body: "'What day is it today?' — Bu gün hansı gündür? 'It is Monday.' — Bazar ertəsidir." },
          ],
          tasks: [
            { id: "en2-days-when-t1", type: "multiple_choice", speakOptions: true, prompt: "'bu gün' İngiliscə necədir?", options: ["today", "tomorrow", "yesterday", "now"], correctIndex: 0, xp: 10, explanation: "«Bu gün» ingiliscə today olur.", skills: ["en.vocab.topic"] },
            { id: "en2-days-when-t2", type: "multiple_choice", speakOptions: true, prompt: "'sabah' İngiliscə necədir?", options: ["tomorrow", "today", "yesterday", "week"], correctIndex: 0, xp: 10, explanation: "«Sabah» ingiliscə tomorrow olur.", skills: ["en.vocab.topic"] },
            { id: "en2-days-when-t3", type: "multiple_choice", speakOptions: true, prompt: "'dünən' İngiliscə necədir?", options: ["yesterday", "today", "tomorrow", "later"], correctIndex: 0, xp: 10, explanation: "«Dünən» ingiliscə yesterday olur.", skills: ["en.vocab.topic"] },
            { id: "en2-days-when-t4", type: "multiple_choice", prompt: "'What day is it today?' nə deməkdir?", options: ["Bu gün hansı gündür?", "Saat neçədir?", "Neçə yaşın var?", "Adın nədir?"], correctIndex: 0, xp: 10, explanation: "Day = gün, today = bu gün. Deməli sual «Bu gün hansı gündür?» deməkdir.", skills: ["en.gram.questions"] },
            { id: "en2-days-when-t5", type: "multiple_choice", speakOptions: true, prompt: "'həftə' İngiliscə necədir?", options: ["week", "day", "month", "year"], correctIndex: 0, xp: 10, explanation: "«Həftə» ingiliscə week olur.", skills: ["en.vocab.topic"] },
            { id: "en2-days-when-t6", type: "multiple_choice", speakOptions: true, prompt: "'ay' (təqvim ayı) İngiliscə necədir?", options: ["month", "week", "moon", "year"], correctIndex: 0, xp: 10, explanation: "Təqvim «ayı» ingiliscə month olur. Moon isə göydəki aydır.", skills: ["en.vocab.topic"] },
            { id: "en2-days-when-t7", type: "multiple_choice", speakOptions: true, prompt: "'il' İngiliscə necədir?", options: ["year", "month", "week", "day"], correctIndex: 0, xp: 10, explanation: "«İl» ingiliscə year olur.", skills: ["en.vocab.topic"] },
            { id: "en2-days-when-t8", type: "multiple_choice", prompt: "'It is Monday.' nə deməkdir?", options: ["Bazar ertəsidir.", "Bazardır.", "Cümədir.", "Şənbədir."], correctIndex: 0, xp: 10, explanation: "It is = ...dır, Monday = bazar ertəsi. Deməli «Bazar ertəsidir».", skills: ["en.vocab.topic"] },
            { id: "en2-days-when-t9", type: "multiple_choice", speakOptions: true, prompt: "'indi' İngiliscə necədir?", options: ["now", "then", "soon", "late"], correctIndex: 0, xp: 10, explanation: "«İndi» ingiliscə now olur.", skills: ["en.vocab.topic"] },
            { id: "en2-days-when-t10", type: "multiple_choice", prompt: "Həftədə neçə gün var? (İngiliscə cavab)", options: ["seven", "five", "ten", "twelve"], correctIndex: 0, xp: 10, explanation: "Həftədə 7 gün var, 7 isə ingiliscə seven olur.", skills: ["en.vocab.topic"] },
          ],
          bonusTasks: [
            { id: "en2-days-when-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "tomorrow", options: ["sabah", "dünən", "bu gün", "indi"], correctIndex: 0, xp: 15, explanation: "Səsdə «tomorrow» deyildi — bu, «sabah» deməkdir.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-days-when-b2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "yesterday", options: ["dünən", "sabah", "bu gün", "həftə"], correctIndex: 0, xp: 15, explanation: "Səsdə «yesterday» deyildi — bu, «dünən» deməkdir.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-days-when-b3", type: "multiple_choice", prompt: "'See you tomorrow!' nə deməkdir?", options: ["Sabah görüşərik!", "Dünən gördüm!", "İndi gedirəm!", "Sağ ol!"], correctIndex: 0, xp: 15, explanation: "See you = görüşərik, tomorrow = sabah. Deməli «Sabah görüşərik!»", skills: ["en.vocab.topic"] },
            { id: "en2-days-when-b4", type: "multiple_choice", speakOptions: true, prompt: "'gün' İngiliscə necədir?", options: ["day", "week", "month", "year"], correctIndex: 0, xp: 15, explanation: "«Gün» ingiliscə day olur.", skills: ["en.vocab.topic"] },
          ],
        },
        {
          id: "en2-days-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en2-days-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 3. Yemək və içki ═══════════════
    {
      id: "en2-food",
      title: "Yemək və içki (Food & Drinks)",
      description: "Yemək və içkilərin İngiliscə adları.",
      lessons: [
        {
          id: "en2-food-vocab",
          title: "Food & drinks",
          intro: "Yemək və içkiləri İngiliscə öyrənək.",
          sections: [
            { heading: "Sözlər", body: "bread — çörək, milk — süd, water — su, apple — alma, egg — yumurta, meat — ət, rice — düyü, tea — çay, juice — şirə, cheese — pendir." },
          ],
          tasks: [
            { id: "en2-food-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "🍞 İngiliscə necədir?", options: ["bread", "milk", "water", "egg"], correctIndex: 0, xp: 10, explanation: "🍞 çörəkdir, «çörək» isə ingiliscə bread olur.", skills: ["en.vocab.topic"] },
            { id: "en2-food-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "🥛 İngiliscə necədir?", options: ["milk", "water", "juice", "tea"], correctIndex: 0, xp: 10, explanation: "🥛 süddür, «süd» isə ingiliscə milk olur.", skills: ["en.vocab.topic"] },
            { id: "en2-food-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "💧 (su) İngiliscə necədir?", options: ["water", "milk", "juice", "tea"], correctIndex: 0, xp: 10, explanation: "«Su» ingiliscə water olur.", skills: ["en.vocab.topic"] },
            { id: "en2-food-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "🍎 İngiliscə necədir?", options: ["apple", "egg", "meat", "rice"], correctIndex: 0, xp: 10, explanation: "🍎 almadır, «alma» isə ingiliscə apple olur.", skills: ["en.vocab.topic"] },
            { id: "en2-food-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "🥚 İngiliscə necədir?", options: ["egg", "apple", "cheese", "bread"], correctIndex: 0, xp: 10, explanation: "🥚 yumurtadır, «yumurta» isə ingiliscə egg olur.", skills: ["en.vocab.topic"] },
            { id: "en2-food-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'ət' İngiliscə necədir?", options: ["meat", "rice", "egg", "milk"], correctIndex: 0, xp: 10, explanation: "«Ət» ingiliscə meat olur. Meet = görüşmək — səsi eyni olsa da mənası fərqlidir.", skills: ["en.vocab.topic"] },
            { id: "en2-food-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'düyü' İngiliscə necədir?", options: ["rice", "meat", "bread", "egg"], correctIndex: 0, xp: 10, explanation: "«Düyü» ingiliscə rice olur.", skills: ["en.vocab.topic"] },
            { id: "en2-food-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "'çay' İngiliscə necədir?", options: ["tea", "juice", "milk", "water"], correctIndex: 0, xp: 10, explanation: "İçki olan «çay» ingiliscə tea olur.", skills: ["en.vocab.topic"] },
            { id: "en2-food-vocab-t9", type: "multiple_choice", speakOptions: true, prompt: "'şirə' İngiliscə necədir?", options: ["juice", "tea", "milk", "water"], correctIndex: 0, xp: 10, explanation: "«Şirə» ingiliscə juice olur.", skills: ["en.vocab.topic"] },
            { id: "en2-food-vocab-t10", type: "multiple_choice", prompt: "'bread' nə deməkdir?", options: ["çörək", "süd", "su", "alma"], correctIndex: 0, xp: 10, explanation: "Bread azərbaycanca «çörək» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en2-food-vocab-t11", type: "multiple_choice", prompt: "'milk' nə deməkdir?", options: ["süd", "su", "çay", "şirə"], correctIndex: 0, xp: 10, explanation: "Milk azərbaycanca «süd» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en2-food-vocab-t12", type: "multiple_choice", prompt: "'apple' nə deməkdir?", options: ["alma", "armud", "yumurta", "ət"], correctIndex: 0, xp: 10, explanation: "Apple azərbaycanca «alma» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en2-food-vocab-t13", type: "multiple_choice", prompt: "'cheese' nə deməkdir?", options: ["pendir", "süd", "çörək", "ət"], correctIndex: 0, xp: 10, explanation: "Cheese azərbaycanca «pendir» deməkdir — süddən hazırlanır, amma süd sözü milk-dir.", skills: ["en.vocab.topic"] },
            { id: "en2-food-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'I like apples.' nə deməkdir?", options: ["Almaları sevirəm.", "Alma yeyirəm.", "Almam var.", "Alma alıram."], correctIndex: 0, xp: 10, explanation: "Like = sevmək, xoşlamaq; apples = almalar. Deməli «Almaları sevirəm».", skills: ["en.vocab.topic"] },
            { id: "en2-food-vocab-t15", type: "multiple_choice", prompt: "'water' nə deməkdir?", options: ["su", "süd", "çay", "şirə"], correctIndex: 0, xp: 15, explanation: "Water azərbaycanca «su» deməkdir.", skills: ["en.vocab.topic"] },
          ],
          bonusTasks: [
            { id: "en2-food-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "🍌 İngiliscə necədir?", options: ["banana", "apple", "egg", "meat"], correctIndex: 0, xp: 15, explanation: "🍌 banandır, «banan» isə ingiliscə banana olur.", skills: ["en.vocab.topic"] },
            { id: "en2-food-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "🍕 İngiliscə necədir?", options: ["pizza", "bread", "cheese", "rice"], correctIndex: 0, xp: 15, explanation: "🍕 pizzadır — bu söz ingiliscə də eyni cür yazılır: pizza.", skills: ["en.vocab.topic"] },
            { id: "en2-food-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'I am hungry.' nə deməkdir?", options: ["Acmışam.", "Susamışam.", "Yorğunam.", "Toxam."], correctIndex: 0, xp: 15, explanation: "Hungry = ac. Deməli «I am hungry» — «Acmışam» deməkdir. Susamaq isə thirsty olardı.", skills: ["en.vocab.topic"] },
            { id: "en2-food-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'fish' (yemək) nə deməkdir?", options: ["balıq", "ət", "toyuq", "yumurta"], correctIndex: 0, xp: 15, explanation: "Yemək kimi fish azərbaycanca «balıq» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en2-food-vocab-b5", type: "multiple_choice", prompt: "'egg' nə deməkdir?", options: ["yumurta", "alma", "pendir", "çörək"], correctIndex: 0, xp: 15, explanation: "Egg azərbaycanca «yumurta» deməkdir.", skills: ["en.vocab.topic"] },
          ],
        },
        {
          id: "en2-food-listen",
          title: "Dinləmə: yemək",
          intro: "Sözü dinlə və mənasını seç.",
          sections: [
            { heading: "Necə işləyir?", body: "Səs düyməsinə bas, İngiliscə sözü dinlə, düzgün mənasını seç." },
          ],
          tasks: [
            { id: "en2-food-listen-t1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "bread", options: ["çörək", "süd", "su", "alma"], correctIndex: 0, xp: 10, explanation: "Səsdə «bread» deyildi — bu, «çörək» deməkdir.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-food-listen-t2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "milk", options: ["süd", "su", "çay", "şirə"], correctIndex: 0, xp: 10, explanation: "Səsdə «milk» deyildi — bu, «süd» deməkdir.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-food-listen-t3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "water", options: ["su", "süd", "çay", "şirə"], correctIndex: 0, xp: 10, explanation: "Səsdə «water» deyildi — bu, «su» deməkdir.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-food-listen-t4", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "apple", options: ["alma", "armud", "yumurta", "ət"], correctIndex: 0, xp: 10, explanation: "Səsdə «apple» deyildi — bu, «alma» deməkdir.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-food-listen-t5", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "egg", options: ["yumurta", "alma", "pendir", "çörək"], correctIndex: 0, xp: 10, explanation: "Səsdə «egg» deyildi — bu, «yumurta» deməkdir.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-food-listen-t6", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "meat", options: ["ət", "düyü", "yumurta", "süd"], correctIndex: 0, xp: 10, explanation: "Səsdə «meat» deyildi — bu, «ət» deməkdir.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-food-listen-t7", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "rice", options: ["düyü", "ət", "çörək", "yumurta"], correctIndex: 0, xp: 10, explanation: "Səsdə «rice» deyildi — bu, «düyü» deməkdir.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-food-listen-t8", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "tea", options: ["çay", "şirə", "süd", "su"], correctIndex: 0, xp: 10, explanation: "Səsdə «tea» deyildi — bu, içki olan «çay» deməkdir.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-food-listen-t9", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "juice", options: ["şirə", "çay", "süd", "su"], correctIndex: 0, xp: 10, explanation: "Səsdə «juice» deyildi — bu, «şirə» deməkdir.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-food-listen-t10", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "cheese", options: ["pendir", "süd", "çörək", "ət"], correctIndex: 0, xp: 10, explanation: "Səsdə «cheese» deyildi — bu, «pendir» deməkdir.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-food-listen-t11", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "banana", options: ["banan", "alma", "üzüm", "nar"], correctIndex: 0, xp: 10, explanation: "Səsdə «banana» deyildi — bu, «banan» deməkdir.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-food-listen-t12", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "fish", options: ["balıq", "ət", "toyuq", "yumurta"], correctIndex: 0, xp: 10, explanation: "Səsdə «fish» deyildi — bu, «balıq» deməkdir.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-food-listen-t13", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I like milk", options: ["Südü sevirəm", "Su içirəm", "Süd alıram", "Süd yoxdur"], correctIndex: 0, xp: 10, explanation: "Səsdə «I like milk» deyildi. Like = sevmək, milk = süd — deməli «Südü sevirəm».", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-food-listen-t14", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I want water", options: ["Su istəyirəm", "Su içdim", "Su yoxdur", "Süd istəyirəm"], correctIndex: 0, xp: 10, explanation: "Səsdə «I want water» deyildi. Want = istəmək, water = su — deməli «Su istəyirəm».", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-food-listen-t15", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The apple is red", options: ["Alma qırmızıdır", "Alma yaşıldır", "Alma böyükdür", "Alma şirindir"], correctIndex: 0, xp: 15, explanation: "Səsdə «The apple is red» deyildi. Red = qırmızı — deməli «Alma qırmızıdır».", skills: ["en.vocab.topic","en.listen"] },
          ],
          bonusTasks: [
            { id: "en2-food-listen-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I am hungry", options: ["Acmışam", "Susamışam", "Yorğunam", "Toxam"], correctIndex: 0, xp: 15, explanation: "Səsdə «I am hungry» deyildi. Hungry = ac — deməli «Acmışam».", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-food-listen-b2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Do you like tea?", options: ["Çayı sevirsən?", "Çay içdin?", "Çay var?", "Süd sevirsən?"], correctIndex: 0, xp: 15, explanation: "Səsdə «Do you like tea?» deyildi. Do you like...? = ...sevirsən?, tea = çay.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-food-listen-b3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "chicken", options: ["toyuq", "balıq", "ət", "yumurta"], correctIndex: 0, xp: 15, explanation: "Səsdə «chicken» deyildi — bu, «toyuq» deməkdir.", skills: ["en.vocab.topic","en.listen"] },
          ],
        },
        {
          id: "en2-food-like",
          title: "I like / I don't like",
          intro: "Sevdiyini və sevmədiyini demək.",
          sections: [
            { heading: "Bəyənmək", body: "'I like apples.' — Alma xoşuma gəlir. 'I don't like fish.' — Balıq xoşuma gəlmir." },
            { heading: "Sual", body: "'Do you like milk?' — Süd xoşuna gəlir? Cavab: 'Yes, I do.' / 'No, I don't.'" },
          ],
          tasks: [
            { id: "en2-food-like-t1", type: "multiple_choice", prompt: "'I like apples.' nə deməkdir?", options: ["Alma xoşuma gəlir.", "Alma xoşuma gəlmir.", "Alma alıram.", "Alma yeyirəm."], correctIndex: 0, xp: 10, explanation: "Like xoşlamaq bildirir. Deməli «I like apples» — «Alma xoşuma gəlir» deməkdir, sadəcə «yeyirəm» yox.", skills: ["en.vocab.topic"] },
            { id: "en2-food-like-t2", type: "multiple_choice", prompt: "'I don't like fish.' nə deməkdir?", options: ["Balıq xoşuma gəlmir.", "Balıq xoşuma gəlir.", "Balıq yeyirəm.", "Balıq alıram."], correctIndex: 0, xp: 10, explanation: "Don't like — like sözünün inkarıdır. Deməli «Balıq xoşuma gəlmir».", skills: ["en.vocab.topic"] },
            { id: "en2-food-like-t3", type: "multiple_choice", prompt: "'Do you like milk?' nə deməkdir?", options: ["Süd xoşuna gəlir?", "Süd içirsən?", "Süd alırsan?", "Südün var?"], correctIndex: 0, xp: 10, explanation: "Sualda do əvvələ keçib, like = xoşlamaq, milk = süd. Deməli «Süd xoşuna gəlir?»", skills: ["en.vocab.topic"] },
            { id: "en2-food-like-t4", type: "multiple_choice", prompt: "'Yes, I do.' nə deməkdir?", options: ["Bəli.", "Xeyr.", "Bilmirəm.", "Bəlkə."], correctIndex: 0, xp: 10, explanation: "«Do you like...?» sualına qısa təsdiq cavabı «Yes, I do» olur.", skills: ["en.vocab.topic"] },
            { id: "en2-food-like-t5", type: "multiple_choice", prompt: "'No, I don't.' nə deməkdir?", options: ["Xeyr.", "Bəli.", "Bilmirəm.", "Əlbəttə."], correctIndex: 0, xp: 10, explanation: "«Do you like...?» sualına qısa inkar cavabı «No, I don't» olur.", skills: ["en.vocab.topic"] },
            { id: "en2-food-like-t6", type: "multiple_choice", speakOptions: true, prompt: "'çörək' İngiliscə necədir?", options: ["bread", "milk", "water", "apple"], correctIndex: 0, xp: 10, explanation: "«Çörək» ingiliscə bread olur.", skills: ["en.vocab.topic"] },
            { id: "en2-food-like-t7", type: "multiple_choice", speakOptions: true, prompt: "'yumurta' İngiliscə necədir?", options: ["egg", "apple", "bread", "meat"], correctIndex: 0, xp: 10, explanation: "«Yumurta» ingiliscə egg olur.", skills: ["en.vocab.topic"] },
            { id: "en2-food-like-t8", type: "multiple_choice", speakOptions: true, prompt: "'ət' İngiliscə necədir?", options: ["meat", "milk", "bread", "rice"], correctIndex: 0, xp: 10, explanation: "«Ət» ingiliscə meat olur.", skills: ["en.vocab.topic"] },
            { id: "en2-food-like-t9", type: "multiple_choice", prompt: "Xoşuna gəlməyəni necə deyirsən?", options: ["I don't like...", "I like...", "I have...", "I am..."], correctIndex: 0, xp: 10, explanation: "Xoşa gəlməyəni bildirmək üçün like feili inkara çevrilir: I don't like...", skills: ["en.vocab.topic"] },
            { id: "en2-food-like-t10", type: "multiple_choice", speakOptions: true, prompt: "'düyü' İngiliscə necədir?", options: ["rice", "bread", "meat", "egg"], correctIndex: 0, xp: 10, explanation: "«Düyü» ingiliscə rice olur.", skills: ["en.vocab.topic"] },
          ],
          bonusTasks: [
            { id: "en2-food-like-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "egg", options: ["yumurta", "çörək", "süd", "ət"], correctIndex: 0, xp: 15, explanation: "Səsdə «egg» deyildi — bu, «yumurta» deməkdir.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-food-like-b2", type: "multiple_choice", prompt: "'I like bread but I don't like fish.' nə deməkdir?", options: ["Çörək xoşuma gəlir, balıq yox.", "Balıq xoşuma gəlir, çörək yox.", "İkisi də xoşuma gəlir.", "Heç biri xoşuma gəlmir."], correctIndex: 0, xp: 15, explanation: "Cümlədə iki hissə var: I like bread (çörək xoşuma gəlir) və I don't like fish (balıq xoşuma gəlmir). But = amma onları qarşılaşdırır.", skills: ["en.vocab.topic"] },
            { id: "en2-food-like-b3", type: "multiple_choice", speakOptions: true, prompt: "'meyvə' İngiliscə necədir?", options: ["fruit", "meat", "milk", "bread"], correctIndex: 0, xp: 15, explanation: "«Meyvə» ingiliscə fruit olur.", skills: ["en.vocab.topic"] },
            { id: "en2-food-like-b4", type: "multiple_choice", prompt: "'What do you like?' sualına uyğun cavab hansıdır?", options: ["I like apples.", "I am eight.", "It is Monday.", "Yes, please."], correctIndex: 0, xp: 15, explanation: "Sual nəyi xoşladığını soruşur, ona görə cavab da like sözü ilə qurulur: «I like apples».", skills: ["en.gram.questions"] },
          ],
        },
        {
          id: "en2-food-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en2-food-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 4. Oyuncaqlar və əşyalar ═══════════════
    {
      id: "en2-things",
      title: "Oyuncaqlar və əşyalar (Toys & Things)",
      description: "Oyuncaq və əşyaların adları, this/that, cəm (-s).",
      lessons: [
        {
          id: "en2-things-vocab",
          title: "Toys & this/that",
          intro: "Oyuncaqları öyrənək və 'this/that' işlədək.",
          sections: [
            { heading: "Sözlər", body: "ball — top, doll — kukla, car — maşın, kite — uçurtma, teddy bear — pəluş ayı, balloon — şar, bike — velosiped, book — kitab." },
            { heading: "this / that", body: "this — bu (yaxın), that — o (uzaq). 'This is a ball.' — Bu topdur. Cəmdə -s əlavə olunur: ball → balls." },
          ],
          tasks: [
            { id: "en2-things-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "⚽ İngiliscə necədir?", options: ["ball", "doll", "car", "kite"], correctIndex: 0, xp: 10, explanation: "⚽ topdur, «top» isə ingiliscə ball olur.", skills: ["en.gram.demonstrative"] },
            { id: "en2-things-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "🚗 İngiliscə necədir?", options: ["car", "ball", "kite", "doll"], correctIndex: 0, xp: 10, explanation: "🚗 maşındır, «maşın» isə ingiliscə car olur.", skills: ["en.gram.demonstrative"] },
            { id: "en2-things-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "🎈 İngiliscə necədir?", options: ["balloon", "ball", "kite", "doll"], correctIndex: 0, xp: 10, explanation: "🎈 şardır, «şar» isə ingiliscə balloon olur. Ball = top — sözlər oxşasa da fərqlidir.", skills: ["en.gram.demonstrative"] },
            { id: "en2-things-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'kukla' İngiliscə necədir?", options: ["doll", "ball", "car", "bike"], correctIndex: 0, xp: 10, explanation: "«Kukla» ingiliscə doll olur.", skills: ["en.gram.demonstrative"] },
            { id: "en2-things-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'velosiped' İngiliscə necədir?", options: ["bike", "car", "ball", "kite"], correctIndex: 0, xp: 10, explanation: "«Velosiped» ingiliscə bike olur.", skills: ["en.gram.demonstrative"] },
            { id: "en2-things-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'uçurtma' İngiliscə necədir?", options: ["kite", "ball", "doll", "car"], correctIndex: 0, xp: 10, explanation: "«Uçurtma» ingiliscə kite olur.", skills: ["en.gram.demonstrative"] },
            { id: "en2-things-vocab-t7", type: "multiple_choice", prompt: "'ball' nə deməkdir?", options: ["top", "maşın", "kukla", "şar"], correctIndex: 0, xp: 10, explanation: "Ball azərbaycanca «top» deməkdir. Şar isə balloon-dur.", skills: ["en.gram.demonstrative"] },
            { id: "en2-things-vocab-t8", type: "multiple_choice", prompt: "'car' nə deməkdir?", options: ["maşın", "top", "velosiped", "şar"], correctIndex: 0, xp: 10, explanation: "Car azərbaycanca «maşın» deməkdir.", skills: ["en.gram.demonstrative"] },
            { id: "en2-things-vocab-t9", type: "multiple_choice", speakOptions: true, prompt: "'this' nə deməkdir?", options: ["bu (yaxın)", "o (uzaq)", "onlar", "burada"], correctIndex: 0, xp: 10, explanation: "This yaxındakı əşyanı göstərir — azərbaycanca «bu».", skills: ["en.gram.demonstrative"] },
            { id: "en2-things-vocab-t10", type: "multiple_choice", speakOptions: true, prompt: "'that' nə deməkdir?", options: ["o (uzaq)", "bu (yaxın)", "biz", "orada"], correctIndex: 0, xp: 10, explanation: "That uzaqdakı əşyanı göstərir — azərbaycanca «o».", skills: ["en.gram.demonstrative"] },
            { id: "en2-things-vocab-t11", type: "multiple_choice", speakOptions: true, prompt: "'This is a car.' nə deməkdir?", options: ["Bu maşındır.", "O maşındır.", "Maşınlar.", "Maşın var."], correctIndex: 0, xp: 10, explanation: "This = bu, a car = maşın. Deməli «Bu maşındır». «O maşındır» olsaydı that işlənərdi.", skills: ["en.gram.demonstrative"] },
            { id: "en2-things-vocab-t12", type: "multiple_choice", speakOptions: true, prompt: "'ball' sözünün cəmi hansıdır?", options: ["balls", "balles", "ball", "balls's"], correctIndex: 0, xp: 10, explanation: "İngiliscə cəm adətən sözün sonuna -s əlavə etməklə düzəlir: ball → balls.", skills: ["en.gram.plural"] },
            { id: "en2-things-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "'car' sözünün cəmi hansıdır?", options: ["cars", "cares", "car", "carz"], correctIndex: 0, xp: 10, explanation: "İngiliscə cəm sonuna -s əlavə etməklə düzəlir: car → cars.", skills: ["en.gram.plural"] },
            { id: "en2-things-vocab-t14", type: "multiple_choice", prompt: "'balloon' nə deməkdir?", options: ["şar", "top", "kukla", "maşın"], correctIndex: 0, xp: 10, explanation: "Balloon azərbaycanca «şar» deməkdir.", skills: ["en.gram.demonstrative"] },
            { id: "en2-things-vocab-t15", type: "multiple_choice", prompt: "'teddy bear' nə deməkdir?", options: ["pəluş ayı", "kukla", "top", "maşın"], correctIndex: 0, xp: 15, explanation: "Teddy bear azərbaycanca «pəluş ayı» deməkdir — bear sözü ayı deməkdir.", skills: ["en.gram.demonstrative"] },
          ],
          bonusTasks: [
            { id: "en2-things-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'These are dolls.' nə deməkdir?", options: ["Bunlar kuklalardır.", "Bu kukladır.", "O kukladır.", "Kukla var."], correctIndex: 0, xp: 15, explanation: "These = bunlar (cəm), dolls = kuklalar. Deməli «Bunlar kuklalardır».", skills: ["en.gram.demonstrative"] },
            { id: "en2-things-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'doll' sözünün cəmi hansıdır?", options: ["dolls", "dolles", "dollies", "doll"], correctIndex: 0, xp: 15, explanation: "İngiliscə cəm sonuna -s əlavə etməklə düzəlir: doll → dolls.", skills: ["en.gram.plural"] },
            { id: "en2-things-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'I have a bike.' nə deməkdir?", options: ["Velosipedim var.", "Velosiped sürürəm.", "Velosiped istəyirəm.", "Velosiped yoxdur."], correctIndex: 0, xp: 15, explanation: "I have = mənim var, a bike = velosiped. Deməli «Velosipedim var».", skills: ["en.gram.demonstrative"] },
            { id: "en2-things-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'What is this?' nə deməkdir?", options: ["Bu nədir?", "O nədir?", "Sən kimsən?", "Bu haradadır?"], correctIndex: 0, xp: 15, explanation: "What = nə, this = bu. Deməli «Bu nədir?»", skills: ["en.gram.questions","en.gram.demonstrative"] },
            { id: "en2-things-vocab-b5", type: "multiple_choice", prompt: "'kite' nə deməkdir?", options: ["uçurtma", "şar", "top", "kukla"], correctIndex: 0, xp: 15, explanation: "Kite azərbaycanca «uçurtma» deməkdir.", skills: ["en.gram.demonstrative"] },
          ],
        },
        {
          id: "en2-things-plural",
          title: "This, that & plurals",
          intro: "Yaxın–uzaq və cəm formaları.",
          sections: [
            { heading: "This / That", body: "this — bu (yaxın), that — o (uzaq). 'This is a book.' — Bu, kitabdır." },
            { heading: "Cəm", body: "Çox əşya üçün sona -s əlavə olunur: book → books, pen → pens, toy → toys." },
          ],
          tasks: [
            { id: "en2-things-plural-t1", type: "multiple_choice", prompt: "'This is a book.' nə deməkdir?", options: ["Bu, kitabdır.", "O, kitabdır.", "Kitab budur?", "Kitabım var."], correctIndex: 0, xp: 10, explanation: "This = bu (yaxındakı), a book = kitab. Deməli «Bu, kitabdır».", skills: ["en.gram.demonstrative"] },
            { id: "en2-things-plural-t2", type: "multiple_choice", prompt: "'That is a car.' nə deməkdir?", options: ["O, maşındır.", "Bu, maşındır.", "Maşın haradadır?", "Maşınım var."], correctIndex: 0, xp: 10, explanation: "That = o (uzaqdakı), a car = maşın. Deməli «O, maşındır».", skills: ["en.gram.demonstrative"] },
            { id: "en2-things-plural-t3", type: "multiple_choice", prompt: "'book' sözünün cəmi hansıdır?", options: ["books", "bookes", "bookss", "book"], correctIndex: 0, xp: 10, explanation: "İngiliscə cəm sonuna -s əlavə etməklə düzəlir: book → books.", skills: ["en.gram.plural"] },
            { id: "en2-things-plural-t4", type: "multiple_choice", prompt: "'pen' sözünün cəmi hansıdır?", options: ["pens", "penes", "penss", "pen"], correctIndex: 0, xp: 10, explanation: "İngiliscə cəm sonuna -s əlavə etməklə düzəlir: pen → pens.", skills: ["en.gram.plural"] },
            { id: "en2-things-plural-t5", type: "multiple_choice", prompt: "Yaxındakı əşya üçün hansı söz işlənir?", options: ["this", "that", "those", "there"], correctIndex: 0, xp: 10, explanation: "Yaxındakı əşya üçün this işlənir; that isə uzaqdakı üçündür.", skills: ["en.gram.demonstrative"] },
            { id: "en2-things-plural-t6", type: "multiple_choice", prompt: "Uzaqdakı əşya üçün hansı söz işlənir?", options: ["that", "this", "these", "here"], correctIndex: 0, xp: 10, explanation: "Uzaqdakı əşya üçün that işlənir; this isə yaxındakı üçündür.", skills: ["en.gram.demonstrative"] },
            { id: "en2-things-plural-t7", type: "multiple_choice", speakOptions: true, prompt: "'oyuncaq' İngiliscə necədir?", options: ["toy", "boy", "toe", "top"], correctIndex: 0, xp: 10, explanation: "«Oyuncaq» ingiliscə toy olur. Toe = ayaq barmağı, boy = oğlan.", skills: ["en.gram.demonstrative"] },
            { id: "en2-things-plural-t8", type: "multiple_choice", prompt: "'toys' nə deməkdir?", options: ["oyuncaqlar", "oyuncaq", "oyun", "oynamaq"], correctIndex: 0, xp: 10, explanation: "Toys sözündə -s cəm şəkilçisidir, deməli «oyuncaqlar».", skills: ["en.gram.demonstrative"] },
            { id: "en2-things-plural-t9", type: "multiple_choice", prompt: "Cəm düzəltmək üçün sona nə əlavə olunur?", options: ["-s", "-es hər zaman", "-ing", "-ed"], correctIndex: 0, xp: 10, explanation: "Adətən sözün sonuna -s əlavə olunur. Yalnız bəzi sözlərdə (box, bus) -es yazılır.", skills: ["en.gram.demonstrative"] },
            { id: "en2-things-plural-t10", type: "multiple_choice", speakOptions: true, prompt: "'top' (oyun topu) İngiliscə necədir?", options: ["ball", "bell", "bull", "bill"], correctIndex: 0, xp: 10, explanation: "Oyun topu ingiliscə ball olur. Bell = zəng, bull = buğa.", skills: ["en.gram.demonstrative"] },
          ],
          bonusTasks: [
            { id: "en2-things-plural-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "ball", options: ["top", "kitab", "qələm", "kukla"], correctIndex: 0, xp: 15, explanation: "Səsdə «ball» deyildi — bu, «top» deməkdir.", skills: ["en.gram.demonstrative","en.listen"] },
            { id: "en2-things-plural-b2", type: "multiple_choice", prompt: "'These are my books.' nə deməkdir?", options: ["Bunlar mənim kitablarımdır.", "Bu, mənim kitabımdır.", "O, mənim kitabımdır.", "Kitablar haradadır?"], correctIndex: 0, xp: 15, explanation: "These = bunlar, my books = mənim kitablarım. Kitab sözü -s ilə cəmdir, deməli «Bunlar mənim kitablarımdır».", skills: ["en.gram.demonstrative"] },
            { id: "en2-things-plural-b3", type: "multiple_choice", prompt: "'box' sözünün cəmi hansıdır?", options: ["boxes", "boxs", "box", "boxen"], correctIndex: 0, xp: 15, explanation: "Sonu -x ilə bitən sözlərə -s yox, -es əlavə olunur: box → boxes.", skills: ["en.gram.plural"] },
            { id: "en2-things-plural-b4", type: "multiple_choice", speakOptions: true, prompt: "'kukla' İngiliscə necədir?", options: ["doll", "ball", "dull", "bell"], correctIndex: 0, xp: 15, explanation: "«Kukla» ingiliscə doll olur. Dull = darıxdırıcı, bell = zəng.", skills: ["en.gram.demonstrative"] },
          ],
        },
        {
          id: "en2-things-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en2-things-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 5. Hərəkətlər ═══════════════
    {
      id: "en2-actions",
      title: "Hərəkətlər (Actions)",
      description: "Feillər: run, jump, eat, read və s.",
      lessons: [
        {
          id: "en2-actions-vocab",
          title: "Action verbs",
          intro: "Hərəkət bildirən sözləri öyrənək.",
          sections: [
            { heading: "Sözlər", body: "run — qaçmaq, jump — tullanmaq, eat — yemək, drink — içmək, read — oxumaq, write — yazmaq, sit — oturmaq, stand — durmaq, play — oynamaq, sleep — yatmaq." },
          ],
          tasks: [
            { id: "en2-actions-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'qaçmaq' İngiliscə necədir?", options: ["run", "jump", "eat", "sit"], correctIndex: 0, xp: 10, explanation: "«Qaçmaq» ingiliscə run olur.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'tullanmaq' İngiliscə necədir?", options: ["jump", "run", "read", "sleep"], correctIndex: 0, xp: 10, explanation: "«Tullanmaq» ingiliscə jump olur.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'yemək' İngiliscə necədir?", options: ["eat", "drink", "run", "write"], correctIndex: 0, xp: 10, explanation: "«Yemək» ingiliscə eat olur.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'içmək' İngiliscə necədir?", options: ["drink", "eat", "read", "sit"], correctIndex: 0, xp: 10, explanation: "«İçmək» ingiliscə drink olur.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'oxumaq' İngiliscə necədir?", options: ["read", "write", "run", "play"], correctIndex: 0, xp: 10, explanation: "Kitab «oxumaq» ingiliscə read olur. Mahnı oxumaq isə sing-dir.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'yazmaq' İngiliscə necədir?", options: ["write", "read", "eat", "jump"], correctIndex: 0, xp: 10, explanation: "«Yazmaq» ingiliscə write olur.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'oturmaq' İngiliscə necədir?", options: ["sit", "stand", "run", "sleep"], correctIndex: 0, xp: 10, explanation: "«Oturmaq» ingiliscə sit olur.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "'durmaq' İngiliscə necədir?", options: ["stand", "sit", "jump", "eat"], correctIndex: 0, xp: 10, explanation: "«Durmaq, ayaq üstə olmaq» ingiliscə stand olur.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-vocab-t9", type: "multiple_choice", speakOptions: true, prompt: "'oynamaq' İngiliscə necədir?", options: ["play", "run", "read", "write"], correctIndex: 0, xp: 10, explanation: "«Oynamaq» ingiliscə play olur.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-vocab-t10", type: "multiple_choice", speakOptions: true, prompt: "'yatmaq' İngiliscə necədir?", options: ["sleep", "sit", "eat", "run"], correctIndex: 0, xp: 10, explanation: "«Yatmaq» ingiliscə sleep olur.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-vocab-t11", type: "multiple_choice", prompt: "'run' nə deməkdir?", options: ["qaçmaq", "tullanmaq", "yemək", "oxumaq"], correctIndex: 0, xp: 10, explanation: "Run azərbaycanca «qaçmaq» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-vocab-t12", type: "multiple_choice", prompt: "'eat' nə deməkdir?", options: ["yemək", "içmək", "qaçmaq", "yazmaq"], correctIndex: 0, xp: 10, explanation: "Eat azərbaycanca «yemək» deməkdir. İçmək isə drink-dir.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-vocab-t13", type: "multiple_choice", prompt: "'read' nə deməkdir?", options: ["oxumaq", "yazmaq", "yatmaq", "oynamaq"], correctIndex: 0, xp: 10, explanation: "Read azərbaycanca «oxumaq» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'I can run.' nə deməkdir?", options: ["Qaça bilirəm.", "Qaçıram.", "Qaçdım.", "Qaçacağam."], correctIndex: 0, xp: 10, explanation: "Can bacarıq bildirir. Deməli «I can run» — «Qaça bilirəm» deməkdir, sadəcə «qaçıram» yox.", skills: ["en.gram.can"] },
            { id: "en2-actions-vocab-t15", type: "multiple_choice", prompt: "'sleep' nə deməkdir?", options: ["yatmaq", "oturmaq", "durmaq", "yemək"], correctIndex: 0, xp: 15, explanation: "Sleep azərbaycanca «yatmaq» deməkdir.", skills: ["en.vocab.topic"] },
          ],
          bonusTasks: [
            { id: "en2-actions-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'swim' nə deməkdir?", options: ["üzmək", "qaçmaq", "tullanmaq", "uçmaq"], correctIndex: 0, xp: 15, explanation: "Swim azərbaycanca «üzmək» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'sing' nə deməkdir?", options: ["oxumaq (mahnı)", "rəqs etmək", "danışmaq", "gülmək"], correctIndex: 0, xp: 15, explanation: "Sing mahnı «oxumaq» deməkdir. Kitab oxumaq isə read-dir.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'dance' nə deməkdir?", options: ["rəqs etmək", "oxumaq", "qaçmaq", "tullanmaq"], correctIndex: 0, xp: 15, explanation: "Dance azərbaycanca «rəqs etmək» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'Stand up!' nə deməkdir?", options: ["Ayağa qalx!", "Otur!", "Qaç!", "Yat!"], correctIndex: 0, xp: 15, explanation: "Stand = durmaq, up = yuxarı. Birlikdə «Ayağa qalx!» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'Sit down!' nə deməkdir?", options: ["Otur!", "Ayağa qalx!", "Qaç!", "Oxu!"], correctIndex: 0, xp: 15, explanation: "Sit = oturmaq, down = aşağı. Birlikdə «Otur!» deməkdir.", skills: ["en.vocab.topic"] },
          ],
        },
        {
          id: "en2-actions-can",
          title: "Can & can't",
          intro: "Bacarmaq və bacarmamaq.",
          sections: [
            { heading: "Can", body: "'I can swim.' — Mən üzə bilirəm. 'I can't fly.' — Mən uça bilmirəm." },
            { heading: "Sual", body: "'Can you sing?' — Oxuya bilirsən? Cavab: 'Yes, I can.' / 'No, I can't.'" },
          ],
          tasks: [
            { id: "en2-actions-can-t1", type: "multiple_choice", prompt: "'I can swim.' nə deməkdir?", options: ["Mən üzə bilirəm.", "Mən üzürəm.", "Mən üzmürəm.", "Mən üzəcəyəm."], correctIndex: 0, xp: 10, explanation: "Can bacarıq bildirir, swim = üzmək. Deməli «Mən üzə bilirəm».", skills: ["en.gram.can"] },
            { id: "en2-actions-can-t2", type: "multiple_choice", prompt: "'I can't fly.' nə deməkdir?", options: ["Mən uça bilmirəm.", "Mən uçuram.", "Mən uçacağam.", "Mən uçdum."], correctIndex: 0, xp: 10, explanation: "Can't — can sözünün inkarıdır, fly = uçmaq. Deməli «Mən uça bilmirəm».", skills: ["en.gram.can"] },
            { id: "en2-actions-can-t3", type: "multiple_choice", prompt: "'Can you sing?' nə deməkdir?", options: ["Oxuya bilirsən?", "Oxuyursan?", "Oxudun?", "Oxuyacaqsan?"], correctIndex: 0, xp: 10, explanation: "Sualda can əvvələ keçib, sing = oxumaq. Deməli «Oxuya bilirsən?»", skills: ["en.gram.can"] },
            { id: "en2-actions-can-t4", type: "multiple_choice", speakOptions: true, prompt: "'qaçmaq' İngiliscə necədir?", options: ["run", "walk", "jump", "swim"], correctIndex: 0, xp: 10, explanation: "«Qaçmaq» ingiliscə run olur. Walk = yerimək.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-can-t5", type: "multiple_choice", speakOptions: true, prompt: "'tullanmaq' İngiliscə necədir?", options: ["jump", "run", "walk", "fly"], correctIndex: 0, xp: 10, explanation: "«Tullanmaq» ingiliscə jump olur.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-can-t6", type: "multiple_choice", speakOptions: true, prompt: "'oxumaq' (mahnı) İngiliscə necədir?", options: ["sing", "read", "write", "speak"], correctIndex: 0, xp: 10, explanation: "Mahnı «oxumaq» ingiliscə sing olur. Read isə kitab oxumaqdır.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-can-t7", type: "multiple_choice", speakOptions: true, prompt: "'rəsm çəkmək' İngiliscə necədir?", options: ["draw", "write", "read", "play"], correctIndex: 0, xp: 10, explanation: "«Rəsm çəkmək» ingiliscə draw olur.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-can-t8", type: "multiple_choice", prompt: "'Yes, I can.' nə deməkdir?", options: ["Bəli, bacarıram.", "Xeyr, bacarmıram.", "Bilmirəm.", "Bəlkə."], correctIndex: 0, xp: 10, explanation: "Can suala təsdiq cavabı «Yes, I can» olur — bacarığı bildirir.", skills: ["en.gram.can"] },
            { id: "en2-actions-can-t9", type: "multiple_choice", speakOptions: true, prompt: "'yazmaq' İngiliscə necədir?", options: ["write", "read", "draw", "sing"], correctIndex: 0, xp: 10, explanation: "«Yazmaq» ingiliscə write olur.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-can-t10", type: "multiple_choice", prompt: "Bacarmadığını necə deyirsən?", options: ["I can't...", "I can...", "I am...", "I have..."], correctIndex: 0, xp: 10, explanation: "Bacarmamağı bildirmək üçün can sözü inkara çevrilir: can't.", skills: ["en.vocab.topic"] },
          ],
          bonusTasks: [
            { id: "en2-actions-can-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "jump", options: ["tullanmaq", "qaçmaq", "üzmək", "oxumaq"], correctIndex: 0, xp: 15, explanation: "Səsdə «jump» deyildi — bu, «tullanmaq» deməkdir.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-actions-can-b2", type: "multiple_choice", prompt: "'She can read but she can't write.' nə deməkdir?", options: ["O, oxuya bilir, amma yaza bilmir.", "O, yaza bilir, amma oxuya bilmir.", "O, hər ikisini bacarır.", "O, heç birini bacarmır."], correctIndex: 0, xp: 15, explanation: "Cümlədə can read (oxuya bilir) və can't write (yaza bilmir) var. But = amma sözü onları qarşılaşdırır.", skills: ["en.gram.can"] },
            { id: "en2-actions-can-b3", type: "multiple_choice", speakOptions: true, prompt: "'rəqs etmək' İngiliscə necədir?", options: ["dance", "sing", "jump", "run"], correctIndex: 0, xp: 15, explanation: "«Rəqs etmək» ingiliscə dance olur.", skills: ["en.vocab.topic"] },
            { id: "en2-actions-can-b4", type: "multiple_choice", prompt: "'Can' sözündən sonra feil hansı formada olur?", options: ["Sadə forma: can swim", "can swims", "can swimming", "can to swim"], correctIndex: 0, xp: 15, explanation: "Can-dan sonra feil dəyişmir — nə -s, nə -ing, nə də to qoşulur: can swim.", skills: ["en.gram.can"] },
          ],
        },
        {
          id: "en2-actions-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en2-actions-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 6. Bədən, geyim və hava ═══════════════
    {
      id: "en2-body",
      title: "Bədən, geyim və hava (Body, Clothes, Weather)",
      description: "Bədən üzvləri, geyimlər və hava sözləri.",
      lessons: [
        {
          id: "en2-body-vocab",
          title: "Body, clothes & weather",
          intro: "Bədən, geyim və hava sözlərini öyrənək.",
          sections: [
            { heading: "Bədən", body: "head — baş, hand — əl, leg — ayaq, eye — göz, ear — qulaq, nose — burun, mouth — ağız, hair — saç." },
            { heading: "Geyim və hava", body: "shirt — köynək, shoes — ayaqqabı, hat — papaq, coat — palto. Hava: sunny — günəşli, rainy — yağışlı, cold — soyuq, hot — isti." },
          ],
          tasks: [
            { id: "en2-body-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'baş' İngiliscə necədir?", options: ["head", "hand", "leg", "eye"], correctIndex: 0, xp: 10, explanation: "«Baş» ingiliscə head olur.", skills: ["en.vocab.topic"] },
            { id: "en2-body-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'əl' İngiliscə necədir?", options: ["hand", "head", "leg", "ear"], correctIndex: 0, xp: 10, explanation: "«Əl» ingiliscə hand olur.", skills: ["en.vocab.topic"] },
            { id: "en2-body-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'ayaq' İngiliscə necədir?", options: ["leg", "hand", "head", "eye"], correctIndex: 0, xp: 10, explanation: "«Ayaq» ingiliscə leg olur.", skills: ["en.vocab.topic"] },
            { id: "en2-body-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'göz' İngiliscə necədir?", options: ["eye", "ear", "nose", "mouth"], correctIndex: 0, xp: 10, explanation: "«Göz» ingiliscə eye olur.", skills: ["en.vocab.topic"] },
            { id: "en2-body-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'qulaq' İngiliscə necədir?", options: ["ear", "eye", "nose", "hair"], correctIndex: 0, xp: 10, explanation: "«Qulaq» ingiliscə ear olur.", skills: ["en.vocab.topic"] },
            { id: "en2-body-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'burun' İngiliscə necədir?", options: ["nose", "mouth", "ear", "eye"], correctIndex: 0, xp: 10, explanation: "«Burun» ingiliscə nose olur.", skills: ["en.vocab.topic"] },
            { id: "en2-body-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'ağız' İngiliscə necədir?", options: ["mouth", "nose", "ear", "hair"], correctIndex: 0, xp: 10, explanation: "«Ağız» ingiliscə mouth olur.", skills: ["en.vocab.topic"] },
            { id: "en2-body-vocab-t8", type: "multiple_choice", prompt: "'head' nə deməkdir?", options: ["baş", "əl", "ayaq", "göz"], correctIndex: 0, xp: 10, explanation: "Head azərbaycanca «baş» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en2-body-vocab-t9", type: "multiple_choice", prompt: "'hand' nə deməkdir?", options: ["əl", "baş", "ayaq", "qulaq"], correctIndex: 0, xp: 10, explanation: "Hand azərbaycanca «əl» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en2-body-vocab-t10", type: "multiple_choice", speakOptions: true, prompt: "'köynək' İngiliscə necədir?", options: ["shirt", "shoes", "hat", "coat"], correctIndex: 0, xp: 10, explanation: "«Köynək» ingiliscə shirt olur.", skills: ["en.vocab.topic"] },
            { id: "en2-body-vocab-t11", type: "multiple_choice", speakOptions: true, prompt: "'ayaqqabı' İngiliscə necədir?", options: ["shoes", "shirt", "hat", "coat"], correctIndex: 0, xp: 10, explanation: "«Ayaqqabı» ingiliscə shoes olur — cüt olduğu üçün cəm işlənir.", skills: ["en.vocab.topic"] },
            { id: "en2-body-vocab-t12", type: "multiple_choice", speakOptions: true, prompt: "'papaq' İngiliscə necədir?", options: ["hat", "coat", "shirt", "shoes"], correctIndex: 0, xp: 10, explanation: "«Papaq» ingiliscə hat olur.", skills: ["en.vocab.topic"] },
            { id: "en2-body-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "'günəşli' İngiliscə necədir?", options: ["sunny", "rainy", "cold", "hot"], correctIndex: 0, xp: 10, explanation: "«Günəşli» ingiliscə sunny olur — sun (günəş) sözünə -ny qoşulub.", skills: ["en.vocab.topic"] },
            { id: "en2-body-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'yağışlı' İngiliscə necədir?", options: ["rainy", "sunny", "cold", "hot"], correctIndex: 0, xp: 10, explanation: "«Yağışlı» ingiliscə rainy olur — rain (yağış) sözünə -y qoşulub.", skills: ["en.vocab.topic"] },
            { id: "en2-body-vocab-t15", type: "multiple_choice", speakOptions: true, prompt: "'soyuq' İngiliscə necədir?", options: ["cold", "hot", "sunny", "rainy"], correctIndex: 0, xp: 15, explanation: "«Soyuq» ingiliscə cold olur.", skills: ["en.vocab.topic"] },
          ],
          bonusTasks: [
            { id: "en2-body-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'isti' (hava) İngiliscə necədir?", options: ["hot", "cold", "rainy", "sunny"], correctIndex: 0, xp: 15, explanation: "Hava üçün «isti» ingiliscə hot olur.", skills: ["en.vocab.topic"] },
            { id: "en2-body-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'It is sunny.' nə deməkdir?", options: ["Hava günəşlidir.", "Hava yağışlıdır.", "Soyuqdur.", "İstidir."], correctIndex: 0, xp: 15, explanation: "It is hava haqqında deyiləndə «hava ...dır» mənası verir. Sunny = günəşli, deməli «Hava günəşlidir».", skills: ["en.vocab.topic"] },
            { id: "en2-body-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'hair' nə deməkdir?", options: ["saç", "baş", "qulaq", "göz"], correctIndex: 0, xp: 15, explanation: "Hair azərbaycanca «saç» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en2-body-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'coat' nə deməkdir?", options: ["palto", "köynək", "papaq", "ayaqqabı"], correctIndex: 0, xp: 15, explanation: "Coat azərbaycanca «palto» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en2-body-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'It is cold today.' nə deməkdir?", options: ["Bu gün soyuqdur.", "Bu gün istidir.", "Bu gün günəşlidir.", "Bu gün yağışlıdır."], correctIndex: 0, xp: 15, explanation: "Cold = soyuq, today = bu gün. Deməli «Bu gün soyuqdur».", skills: ["en.vocab.topic"] },
          ],
        },
        {
          id: "en2-body-weather",
          title: "Weather & clothes",
          intro: "Hava və geyim sözləri.",
          sections: [
            { heading: "Hava", body: "sunny — günəşli, rainy — yağışlı, windy — küləkli, snowy — qarlı, hot — isti, cold — soyuq." },
            { heading: "Sual", body: "'What's the weather like?' — Hava necədir? 'It is sunny.' — Günəşlidir." },
          ],
          tasks: [
            { id: "en2-body-weather-t1", type: "multiple_choice", speakOptions: true, prompt: "'günəşli' İngiliscə necədir?", options: ["sunny", "rainy", "windy", "cloudy"], correctIndex: 0, xp: 10, explanation: "«Günəşli» ingiliscə sunny olur.", skills: ["en.vocab.topic"] },
            { id: "en2-body-weather-t2", type: "multiple_choice", speakOptions: true, prompt: "'yağışlı' İngiliscə necədir?", options: ["rainy", "sunny", "snowy", "windy"], correctIndex: 0, xp: 10, explanation: "«Yağışlı» ingiliscə rainy olur.", skills: ["en.vocab.topic"] },
            { id: "en2-body-weather-t3", type: "multiple_choice", speakOptions: true, prompt: "'soyuq' İngiliscə necədir?", options: ["cold", "hot", "warm", "cool"], correctIndex: 0, xp: 10, explanation: "«Soyuq» ingiliscə cold olur. Cool = sərin, warm = ilıq.", skills: ["en.vocab.topic"] },
            { id: "en2-body-weather-t4", type: "multiple_choice", speakOptions: true, prompt: "'isti' İngiliscə necədir?", options: ["hot", "cold", "cool", "wet"], correctIndex: 0, xp: 10, explanation: "«İsti» ingiliscə hot olur.", skills: ["en.vocab.topic"] },
            { id: "en2-body-weather-t5", type: "multiple_choice", prompt: "'It is snowy.' nə deməkdir?", options: ["Qarlıdır.", "Yağışlıdır.", "Günəşlidir.", "Küləklidir."], correctIndex: 0, xp: 10, explanation: "Snow = qar, snowy = qarlı. Deməli «Qarlıdır».", skills: ["en.vocab.topic"] },
            { id: "en2-body-weather-t6", type: "multiple_choice", speakOptions: true, prompt: "'palto' İngiliscə necədir?", options: ["coat", "hat", "shoe", "sock"], correctIndex: 0, xp: 10, explanation: "«Palto» ingiliscə coat olur.", skills: ["en.vocab.topic"] },
            { id: "en2-body-weather-t7", type: "multiple_choice", speakOptions: true, prompt: "'papaq' İngiliscə necədir?", options: ["hat", "coat", "shoe", "shirt"], correctIndex: 0, xp: 10, explanation: "«Papaq» ingiliscə hat olur.", skills: ["en.vocab.topic"] },
            { id: "en2-body-weather-t8", type: "multiple_choice", speakOptions: true, prompt: "'ayaqqabı' İngiliscə necədir?", options: ["shoes", "socks", "hats", "coats"], correctIndex: 0, xp: 10, explanation: "«Ayaqqabı» ingiliscə shoes olur — cüt olduğu üçün cəm işlənir.", skills: ["en.vocab.topic"] },
            { id: "en2-body-weather-t9", type: "multiple_choice", prompt: "Soyuq havada nə geyinirik?", options: ["a coat", "shorts", "a swimsuit", "sandals"], correctIndex: 0, xp: 10, explanation: "Palto qalın və isti geyimdir, ona görə soyuqda a coat geyinirik. Shorts və sandals isti hava üçündür.", skills: ["en.vocab.topic"] },
            { id: "en2-body-weather-t10", type: "multiple_choice", prompt: "'What's the weather like?' nə deməkdir?", options: ["Hava necədir?", "Saat neçədir?", "Hansı gündür?", "Necəsən?"], correctIndex: 0, xp: 10, explanation: "Weather = hava. Bu, havanın necə olduğunu soruşan hazır ifadədir: «Hava necədir?»", skills: ["en.gram.questions"] },
          ],
          bonusTasks: [
            { id: "en2-body-weather-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "windy", options: ["küləkli", "günəşli", "yağışlı", "qarlı"], correctIndex: 0, xp: 15, explanation: "Səsdə «windy» deyildi. Wind = külək, deməli «küləkli».", skills: ["en.vocab.topic","en.listen"] },
            { id: "en2-body-weather-b2", type: "multiple_choice", prompt: "'It is hot. I wear a T-shirt.' nə deməkdir?", options: ["İstidir. Mən köynək geyinirəm.", "Soyuqdur. Palto geyinirəm.", "Yağış yağır.", "Qar yağır."], correctIndex: 0, xp: 15, explanation: "Hot = isti, wear = geyinmək, T-shirt = köynək. Deməli «İstidir. Mən köynək geyinirəm».", skills: ["en.vocab.topic"] },
            { id: "en2-body-weather-b3", type: "multiple_choice", speakOptions: true, prompt: "'corab' İngiliscə necədir?", options: ["socks", "shoes", "hats", "coats"], correctIndex: 0, xp: 15, explanation: "«Corab» ingiliscə socks olur — cüt olduğu üçün cəm işlənir.", skills: ["en.vocab.topic"] },
            { id: "en2-body-weather-b4", type: "multiple_choice", speakOptions: true, prompt: "'buludlu' İngiliscə necədir?", options: ["cloudy", "sunny", "rainy", "snowy"], correctIndex: 0, xp: 15, explanation: "Cloud = bulud, cloudy = buludlu.", skills: ["en.vocab.topic"] },
          ],
        },
        {
          id: "en2-body-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en2-body-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
  ],
};
