// İngilis dili — 3-cü sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Present Simple (I/you/we/they)  2) Have got  3) Can/can't
// 4) Sözönləri (in/on/under)  5) Gündəlik rejim və saat  6) Peşələr və şəhər.
// 3-cü sinif üçün sadə: qısa qrammatika + şəkil-söz + dinləmə. id prefiksi en3-*.

import type { Subject } from "../types";

export const english3: Subject = {
  slug: "ingilis-dili-3",
  name: "İngilis dili",
  grade: 3,
  icon: "E",
  color: "violet",
  units: [
    // ═══════════════ 1. Present Simple ═══════════════
    {
      id: "en3-present",
      title: "Present Simple (I like, you play)",
      description: "İndiki sadə zaman: I/you/we/they + feil.",
      lessons: [
        {
          id: "en3-present-rule",
          title: "Qayda: Present Simple",
          intro: "Adət və gündəlik işlər üçün: I play, you like, we go.",
          sections: [
            { heading: "Necə işləyir?", body: "Hər gün olan işlər üçün: I play football. You like apples. We go to school. Feil dəyişmir (I/you/we/they ilə)." },
            { heading: "İnkar", body: "don't əlavə olunur: I don't like fish. We don't play." },
          ],
          tasks: [
            { id: "en3-present-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'Mən futbol oynayıram.' İngiliscə hansıdır?", options: ["I play football.", "I football play.", "Play I football.", "I playing football."], correctIndex: 0, xp: 10, explanation: "İngiliscə söz sırası belədir: kim (I) + nə edir (play) + nəyi (football).", skills: ["en.gram.present_simple"] },
            { id: "en3-present-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'I ___ apples.' (sevirəm)", options: ["like", "likes", "liking", "liked"], correctIndex: 0, xp: 10, explanation: "«I» ilə feil dəyişmir, əsas formada qalır: like. -s yalnız he/she/it ilə əlavə olunur.", skills: ["en.gram.present_simple"] },
            { id: "en3-present-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'We ___ to school.' (gedirik)", options: ["go", "goes", "going", "went"], correctIndex: 0, xp: 10, explanation: "«We» ilə feil dəyişmir: go. Goes yalnız he/she/it ilə işlənir.", skills: ["en.gram.present_simple"] },
            { id: "en3-present-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "'They ___ English.' (öyrənirlər)", options: ["learn", "learns", "learning", "learned"], correctIndex: 0, xp: 10, explanation: "«They» ilə feil dəyişmir: learn.", skills: ["en.gram.present_simple"] },
            { id: "en3-present-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "'You ___ TV.' (baxırsan)", options: ["watch", "watches", "watching", "watched"], correctIndex: 0, xp: 10, explanation: "«You» ilə feil dəyişmir: watch.", skills: ["en.gram.present_simple"] },
            { id: "en3-present-rule-t6", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'I ___ like fish.'", options: ["don't", "doesn't", "not", "no"], correctIndex: 0, xp: 10, explanation: "«I» ilə inkar don't ilə düzəlir. Doesn't yalnız he/she/it ilə işlənir.", skills: ["en.gram.present_simple"] },
            { id: "en3-present-rule-t7", type: "multiple_choice", speakOptions: true, prompt: "'I ___ milk every day.' (içirəm)", options: ["drink", "drinks", "drinking", "drank"], correctIndex: 0, xp: 10, explanation: "«I» ilə feil əsas formada qalır: drink.", skills: ["en.gram.present_perfect"] },
            { id: "en3-present-rule-t8", type: "multiple_choice", prompt: "'I like cats.' nə deməkdir?", options: ["Pişikləri sevirəm.", "Pişiyim var.", "Pişik gördüm.", "Pişik istəyirəm."], correctIndex: 0, xp: 10, explanation: "Like = sevmək, cats = pişiklər. Deməli «Pişikləri sevirəm».", skills: ["en.gram.present_simple"] },
            { id: "en3-present-rule-t9", type: "multiple_choice", speakOptions: true, prompt: "'We ___ in Baku.' (yaşayırıq)", options: ["live", "lives", "living", "lived"], correctIndex: 0, xp: 10, explanation: "«We» ilə feil dəyişmir: live.", skills: ["en.gram.prepositions"] },
            { id: "en3-present-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "'They ___ football.' (oynayırlar)", options: ["play", "plays", "playing", "played"], correctIndex: 0, xp: 10, explanation: "«They» ilə feil dəyişmir: play.", skills: ["en.gram.present_simple"] },
            { id: "en3-present-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'We ___ watch TV.'", options: ["don't", "doesn't", "not", "isn't"], correctIndex: 0, xp: 10, explanation: "«We» ilə inkar don't ilə düzəlir.", skills: ["en.gram.present_simple"] },
            { id: "en3-present-rule-t12", type: "multiple_choice", prompt: "'You go to school.' nə deməkdir?", options: ["Sən məktəbə gedirsən.", "Məktəbə get.", "Məktəbə getdin.", "Məktəb böyükdür."], correctIndex: 0, xp: 10, explanation: "You = sən, go to school = məktəbə gedirsən. İş indi, hər gün təkrarlanır.", skills: ["en.gram.present_simple"] },
            { id: "en3-present-rule-t13", type: "multiple_choice", speakOptions: true, prompt: "'I ___ books.' (oxuyuram)", options: ["read", "reads", "reading", "readed"], correctIndex: 0, xp: 10, explanation: "«I» ilə feil əsas formada qalır: read.", skills: ["en.gram.present_simple"] },
            { id: "en3-present-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "'We ___ music.' (sevirik)", options: ["like", "likes", "liking", "liked"], correctIndex: 0, xp: 10, explanation: "«We» ilə feil dəyişmir: like.", skills: ["en.gram.present_simple"] },
            { id: "en3-present-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'I ___ juice.' (içmirəm — inkar)", options: ["don't drink", "doesn't drink", "not drink", "drink not"], correctIndex: 0, xp: 15, explanation: "İnkar don't + feilin əsas forması ilə düzəlir: don't drink.", skills: ["en.gram.present_simple"] },
          ],
          bonusTasks: [
            { id: "en3-present-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "'They don't like fish.' nə deməkdir?", options: ["Balığı sevmirlər.", "Balığı sevirlər.", "Balıq yoxdur.", "Balıq istəyirlər."], correctIndex: 0, xp: 15, explanation: "Don't like = sevmirlər, fish = balıq. Deməli «Balığı sevmirlər».", skills: ["en.gram.present_simple"] },
            { id: "en3-present-rule-b2", type: "multiple_choice", speakOptions: true, prompt: "'I ___ my teeth every morning.' (təmizləyirəm)", options: ["brush", "brushes", "brushing", "brushed"], correctIndex: 0, xp: 15, explanation: "«I» ilə feil əsas formada qalır: brush.", skills: ["en.gram.present_perfect"] },
            { id: "en3-present-rule-b3", type: "multiple_choice", speakOptions: true, prompt: "'We ___ breakfast at 8.' (yeyirik)", options: ["have", "has", "having", "had"], correctIndex: 0, xp: 15, explanation: "«We» ilə have işlənir; has yalnız he/she/it üçündür.", skills: ["en.gram.present_simple"] },
            { id: "en3-present-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "'Do you like ice cream?' nə deməkdir?", options: ["Dondurmanı sevirsən?", "Dondurma var?", "Dondurma istəyirsən?", "Dondurma yedin?"], correctIndex: 0, xp: 15, explanation: "Do you like...? = ...sevirsən?, ice cream = dondurma.", skills: ["en.gram.present_simple"] },
            { id: "en3-present-rule-b5", type: "multiple_choice", speakOptions: true, prompt: "'I ___ football, I like basketball.' (inkar)", options: ["don't play", "doesn't play", "not play", "play not"], correctIndex: 0, xp: 15, explanation: "«I» ilə inkar don't + əsas forma ilə düzəlir: don't play.", skills: ["en.gram.present_simple"] },
          ],
        },
        {
          id: "en3-present-listen",
          title: "Dinləmə: Present Simple",
          intro: "Cümləni dinlə və mənasını seç.",
          sections: [
            { heading: "Necə işləyir?", body: "Səs düyməsinə bas, cümləni dinlə, düzgün mənasını seç." },
          ],
          tasks: [
            { id: "en3-present-listen-t1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I play football.", options: ["Futbol oynayıram.", "Futbol oynadım.", "Futbolu sevirəm.", "Futbol oynamıram."], correctIndex: 0, xp: 10, explanation: "Səsdə «I play football» deyildi. Play = oynamaq — deməli «Futbol oynayıram».", skills: ["en.gram.present_simple","en.listen"] },
            { id: "en3-present-listen-t2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I like apples.", options: ["Almaları sevirəm.", "Alma yeyirəm.", "Almam var.", "Alma istəyirəm."], correctIndex: 0, xp: 10, explanation: "Səsdə «I like apples» deyildi. Like = sevmək — deməli «Almaları sevirəm».", skills: ["en.gram.present_simple","en.listen"] },
            { id: "en3-present-listen-t3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "We go to school.", options: ["Məktəbə gedirik.", "Məktəbə getdik.", "Məktəbdəyik.", "Məktəb böyükdür."], correctIndex: 0, xp: 10, explanation: "Səsdə «We go to school» deyildi. Go = getmək — deməli «Məktəbə gedirik».", skills: ["en.gram.present_simple","en.listen"] },
            { id: "en3-present-listen-t4", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "They learn English.", options: ["İngiliscə öyrənirlər.", "İngiliscə bilirlər.", "İngiliscə danışırlar.", "İngiliscə öyrəndilər."], correctIndex: 0, xp: 10, explanation: "Səsdə «They learn English» deyildi. Learn = öyrənmək; danışmaq isə speak olardı.", skills: ["en.gram.present_simple","en.listen"] },
            { id: "en3-present-listen-t5", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I drink milk.", options: ["Süd içirəm.", "Su içirəm.", "Süd sevirəm.", "Süd aldım."], correctIndex: 0, xp: 10, explanation: "Səsdə «I drink milk» deyildi. Drink = içmək, milk = süd.", skills: ["en.gram.present_simple","en.listen"] },
            { id: "en3-present-listen-t6", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "You watch TV.", options: ["Televizora baxırsan.", "Televizor aldın.", "Televizora bax.", "Televizor böyükdür."], correctIndex: 0, xp: 10, explanation: "Səsdə «You watch TV» deyildi. Watch = baxmaq.", skills: ["en.gram.present_simple","en.listen"] },
            { id: "en3-present-listen-t7", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "We live in Baku.", options: ["Bakıda yaşayırıq.", "Bakıya gedirik.", "Bakı gözəldir.", "Bakıda idik."], correctIndex: 0, xp: 10, explanation: "Səsdə «We live in Baku» deyildi. Live = yaşamaq; getmək isə go olardı.", skills: ["en.gram.present_simple","en.listen"] },
            { id: "en3-present-listen-t8", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I don't like fish.", options: ["Balığı sevmirəm.", "Balığı sevirəm.", "Balıq yeyirəm.", "Balıq yoxdur."], correctIndex: 0, xp: 10, explanation: "Səsdə «I don't like fish» deyildi. Don't inkar bildirir — deməli «Balığı sevmirəm».", skills: ["en.gram.present_simple","en.listen"] },
            { id: "en3-present-listen-t9", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "They play in the park.", options: ["Parkda oynayırlar.", "Parka gedirlər.", "Park böyükdür.", "Parkda idilər."], correctIndex: 0, xp: 10, explanation: "Səsdə «They play in the park» deyildi. Play = oynamaq, park = park.", skills: ["en.gram.present_simple","en.listen"] },
            { id: "en3-present-listen-t10", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I read books.", options: ["Kitab oxuyuram.", "Kitab alıram.", "Kitabım var.", "Kitab yazıram."], correctIndex: 0, xp: 10, explanation: "Səsdə «I read books» deyildi. Read = oxumaq; yazmaq isə write olardı.", skills: ["en.gram.present_simple","en.listen"] },
            { id: "en3-present-listen-t11", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "We like music.", options: ["Musiqini sevirik.", "Musiqi çalırıq.", "Musiqi dinləyirik.", "Musiqi yoxdur."], correctIndex: 0, xp: 10, explanation: "Səsdə «We like music» deyildi. Like = sevmək; dinləmək isə listen olardı.", skills: ["en.gram.present_simple","en.listen"] },
            { id: "en3-present-listen-t12", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "You have breakfast.", options: ["Səhər yeməyi yeyirsən.", "Səhər yeməyi bişirdin.", "Səhər yeməyin var.", "Səhər durursan."], correctIndex: 0, xp: 10, explanation: "Səsdə «You have breakfast» deyildi. Have breakfast = səhər yeməyi yemək.", skills: ["en.gram.present_simple","en.listen"] },
            { id: "en3-present-listen-t13", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I don't watch TV.", options: ["Televizora baxmıram.", "Televizora baxıram.", "Televizor yoxdur.", "Televizora baxdım."], correctIndex: 0, xp: 10, explanation: "Səsdə «I don't watch TV» deyildi. Don't inkar bildirir — deməli «Televizora baxmıram».", skills: ["en.gram.present_simple","en.listen"] },
            { id: "en3-present-listen-t14", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "They go home.", options: ["Evə gedirlər.", "Evdədirlər.", "Evə getdilər.", "Ev böyükdür."], correctIndex: 0, xp: 10, explanation: "Səsdə «They go home» deyildi. Go home = evə getmək.", skills: ["en.gram.present_simple","en.listen"] },
            { id: "en3-present-listen-t15", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "We like ice cream.", options: ["Dondurmanı sevirik.", "Dondurma yeyirik.", "Dondurma aldıq.", "Dondurma yoxdur."], correctIndex: 0, xp: 15, explanation: "Səsdə «We like ice cream» deyildi. Like = sevmək; yemək isə eat olardı.", skills: ["en.gram.present_simple","en.listen"] },
          ],
          bonusTasks: [
            { id: "en3-present-listen-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I brush my teeth every day.", options: ["Hər gün dişlərimi təmizləyirəm.", "Dişlərim ağrıyır.", "Diş fırçam var.", "Dişimi çəkdirdim."], correctIndex: 0, xp: 15, explanation: "Səsdə «I brush my teeth every day» deyildi. Brush teeth = diş təmizləmək, every day = hər gün.", skills: ["en.gram.present_simple","en.listen"] },
            { id: "en3-present-listen-b2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Do you like cats?", options: ["Pişikləri sevirsən?", "Pişiyin var?", "Pişik gördün?", "Pişik istəyirsən?"], correctIndex: 0, xp: 15, explanation: "Səsdə «Do you like cats?» deyildi. Do you like...? = ...sevirsən?", skills: ["en.gram.present_simple","en.listen"] },
            { id: "en3-present-listen-b3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "We don't eat meat.", options: ["Ət yemirik.", "Ət yeyirik.", "Ət aldıq.", "Ət yoxdur."], correctIndex: 0, xp: 15, explanation: "Səsdə «We don't eat meat» deyildi. Don't inkar bildirir, meat = ət.", skills: ["en.gram.present_simple","en.listen"] },
          ],
        },
        {
          id: "en3-present-he",
          title: "He / She / It — sona -s",
          intro: "Üçüncü şəxs tək formada feilə -s əlavə olunur.",
          sections: [
            { heading: "Qayda", body: "I play — He plays. You read — She reads. We go — It goes. Yalnız he/she/it ilə feilə -s qoşulur." },
            { heading: "İnkar", body: "He doesn't play. — O oynamır. (does not = doesn't)" },
          ],
          tasks: [
            { id: "en3-present-he-t1", type: "multiple_choice", prompt: "'He ______ football.' — düzgün forma hansıdır?", options: ["plays", "play", "playing", "played"], correctIndex: 0, xp: 10, explanation: "He — üçüncü şəxs təkdir, ona görə feilə -s əlavə olunur: plays.", skills: ["en.gram.present_simple"] },
            { id: "en3-present-he-t2", type: "multiple_choice", prompt: "'She ______ a book.' — düzgün forma hansıdır?", options: ["reads", "read", "reading", "readed"], correctIndex: 0, xp: 10, explanation: "She — üçüncü şəxs təkdir, ona görə feilə -s əlavə olunur: reads.", skills: ["en.gram.present_simple"] },
            { id: "en3-present-he-t3", type: "multiple_choice", prompt: "'They ______ to school.' — düzgün forma hansıdır?", options: ["go", "goes", "going", "gone"], correctIndex: 0, xp: 10, explanation: "They cəmdir, ona görə feil dəyişmir: go.", skills: ["en.gram.present_simple"] },
            { id: "en3-present-he-t4", type: "multiple_choice", prompt: "'It ______ every day.' (rain)", options: ["rains", "rain", "raining", "rained"], correctIndex: 0, xp: 10, explanation: "It — üçüncü şəxs təkdir, ona görə feilə -s əlavə olunur: rains.", skills: ["en.gram.present_perfect"] },
            { id: "en3-present-he-t5", type: "multiple_choice", prompt: "Feilə -s nə vaxt əlavə olunur?", options: ["he / she / it ilə", "I ilə", "we ilə", "they ilə"], correctIndex: 0, xp: 10, explanation: "-s yalnız üçüncü şəxs təkdə, yəni he, she, it ilə əlavə olunur.", skills: ["en.gram.present_simple"] },
            { id: "en3-present-he-t6", type: "multiple_choice", prompt: "'He doesn't play.' nə deməkdir?", options: ["O oynamır.", "O oynayır.", "Onlar oynamır.", "Mən oynamıram."], correctIndex: 0, xp: 10, explanation: "He ilə inkar doesn't ilə düzəlir. Deməli «O oynamır».", skills: ["en.gram.present_simple"] },
            { id: "en3-present-he-t7", type: "multiple_choice", prompt: "'I ______ English.' — düzgün forma hansıdır?", options: ["speak", "speaks", "speaking", "spoke"], correctIndex: 0, xp: 10, explanation: "«I» üçüncü şəxs deyil, ona görə feil dəyişmir: speak.", skills: ["en.gram.present_simple"] },
            { id: "en3-present-he-t8", type: "multiple_choice", prompt: "'Does he like tea?' sualına inkar cavab hansıdır?", options: ["No, he doesn't.", "No, he don't.", "No, he isn't.", "No, he not."], correctIndex: 0, xp: 10, explanation: "He ilə inkar doesn't ilə düzəlir: «No, he doesn't».", skills: ["en.gram.present_simple"] },
            { id: "en3-present-he-t9", type: "multiple_choice", prompt: "'We ______ TV in the evening.' (watch)", options: ["watch", "watches", "watching", "watched"], correctIndex: 0, xp: 10, explanation: "We cəmdir, ona görə feil dəyişmir: watch.", skills: ["en.gram.prepositions"] },
            { id: "en3-present-he-t10", type: "multiple_choice", speakOptions: true, prompt: "'gedir' (he) İngiliscə necədir?", options: ["goes", "go", "going", "went"], correctIndex: 0, xp: 10, explanation: "He ilə go feili -es alır: goes. Sonu -o ilə bitən feillərə -es qoşulur.", skills: ["en.gram.present_simple"] },
          ],
          bonusTasks: [
            { id: "en3-present-he-b1", type: "multiple_choice", prompt: "'She ______ her homework every day.' (do)", options: ["does", "do", "doing", "done"], correctIndex: 0, xp: 15, explanation: "She — üçüncü şəxs təkdir; do feili -es alır: does.", skills: ["en.gram.present_perfect"] },
            { id: "en3-present-he-b2", type: "multiple_choice", prompt: "'My brother ______ in Baku.' (live)", options: ["lives", "live", "living", "lived"], correctIndex: 0, xp: 15, explanation: "«My brother» he kimidir, yəni üçüncü şəxs təkdir: lives.", skills: ["en.gram.prepositions"] },
            { id: "en3-present-he-b3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "He plays football.", options: ["O, futbol oynayır.", "Onlar futbol oynayır.", "Mən futbol oynayıram.", "O, futbol oynamır."], correctIndex: 0, xp: 15, explanation: "Səsdə «He plays football» deyildi. Plays sözündəki -s göstərir ki, iş görən bir nəfərdir — «O».", skills: ["en.gram.present_simple","en.listen"] },
            { id: "en3-present-he-b4", type: "multiple_choice", prompt: "'-es' hansı feillərə əlavə olunur?", options: ["go, do, watch kimi feillərə", "Bütün feillərə", "Heç birinə", "Yalnız 'be' feilinə"], correctIndex: 0, xp: 15, explanation: "Sonu -o, -ch, -sh, -s, -x ilə bitən feillərə -s yox, -es qoşulur: goes, watches, does.", skills: ["en.gram.present_simple"] },
          ],
        },
        {
          id: "en3-present-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en3-present-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 2. Have got ═══════════════
    {
      id: "en3-havegot",
      title: "Have got (məndə var)",
      description: "Sahiblik: I have got, you have got, he/she has got.",
      lessons: [
        {
          id: "en3-havegot-rule",
          title: "Qayda: have got / has got",
          intro: "Nəyəsə sahib olmaq: I have got a dog. She has got a cat.",
          sections: [
            { heading: "have / has got", body: "I/you/we/they → have got. he/she/it → has got. 'I have got a bike.' — Velosipedim var. 'She has got a doll.' — Onun kuklası var." },
            { heading: "İnkar", body: "haven't got / hasn't got: I haven't got a cat." },
          ],
          tasks: [
            { id: "en3-havegot-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'I ___ got a dog.' (məndə var)", options: ["have", "has", "am", "is"], correctIndex: 0, xp: 10, explanation: "«I» ilə have işlənir; has yalnız he/she/it üçündür.", skills: ["en.gram.have"] },
            { id: "en3-havegot-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'She ___ got a cat.' (onda var)", options: ["has", "have", "is", "are"], correctIndex: 0, xp: 10, explanation: "«She» üçüncü şəxs təkdir, ona görə has işlənir.", skills: ["en.gram.have"] },
            { id: "en3-havegot-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'He ___ got a ball.'", options: ["has", "have", "is", "are"], correctIndex: 0, xp: 10, explanation: "«He» üçüncü şəxs təkdir, ona görə has işlənir.", skills: ["en.gram.have"] },
            { id: "en3-havegot-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "'We ___ got books.'", options: ["have", "has", "is", "are"], correctIndex: 0, xp: 10, explanation: "«We» cəmdir, ona görə have işlənir.", skills: ["en.gram.have"] },
            { id: "en3-havegot-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "'They ___ got a car.'", options: ["have", "has", "is", "am"], correctIndex: 0, xp: 10, explanation: "«They» cəmdir, ona görə have işlənir.", skills: ["en.gram.have"] },
            { id: "en3-havegot-rule-t6", type: "multiple_choice", prompt: "'I have got a bike.' nə deməkdir?", options: ["Velosipedim var.", "Velosiped istəyirəm.", "Velosiped sürürəm.", "Velosiped aldım."], correctIndex: 0, xp: 10, explanation: "Have got sahiblik bildirir. Deməli «Velosipedim var», sürmək və ya almaq yox.", skills: ["en.gram.have"] },
            { id: "en3-havegot-rule-t7", type: "multiple_choice", prompt: "'She has got a doll.' nə deməkdir?", options: ["Onun kuklası var.", "O kukla aldı.", "Kukla istəyir.", "Kukla oynayır."], correctIndex: 0, xp: 10, explanation: "Has got sahiblik bildirir, doll = kukla. Deməli «Onun kuklası var».", skills: ["en.gram.have"] },
            { id: "en3-havegot-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'it' (pişik) üçün: 'It ___ got blue eyes.'", options: ["has", "have", "is", "are"], correctIndex: 0, xp: 10, explanation: "«It» üçüncü şəxs təkdir, ona görə has işlənir.", skills: ["en.gram.have"] },
            { id: "en3-havegot-rule-t9", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'I ___ got a cat.'", options: ["haven't", "hasn't", "don't", "isn't"], correctIndex: 0, xp: 10, explanation: "«I» ilə inkar haven't ilə düzəlir (have + not).", skills: ["en.gram.have"] },
            { id: "en3-havegot-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'She ___ got a bike.'", options: ["hasn't", "haven't", "don't", "isn't"], correctIndex: 0, xp: 10, explanation: "«She» üçüncü şəxs təkdir, ona görə inkar hasn't olur (has + not).", skills: ["en.gram.have"] },
            { id: "en3-havegot-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "'My brother ___ got a red car.'", options: ["has", "have", "is", "are"], correctIndex: 0, xp: 10, explanation: "«My brother» he kimidir, yəni üçüncü şəxs təkdir: has.", skills: ["en.gram.have"] },
            { id: "en3-havegot-rule-t12", type: "multiple_choice", speakOptions: true, prompt: "'You ___ got a nice bag.'", options: ["have", "has", "is", "am"], correctIndex: 0, xp: 10, explanation: "«You» ilə həmişə have işlənir, tək və ya cəm olmasından asılı olmayaraq.", skills: ["en.gram.have"] },
            { id: "en3-havegot-rule-t13", type: "multiple_choice", prompt: "'We have got two cats.' nə deməkdir?", options: ["İki pişiyimiz var.", "İki pişik gördük.", "Pişik istəyirik.", "Pişiklər gəldi."], correctIndex: 0, xp: 10, explanation: "Have got sahiblik bildirir, two cats = iki pişik.", skills: ["en.gram.have"] },
            { id: "en3-havegot-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "'The dog ___ got a long tail.'", options: ["has", "have", "is", "are"], correctIndex: 0, xp: 10, explanation: "«The dog» it kimidir, yəni üçüncü şəxs təkdir: has.", skills: ["en.gram.have"] },
            { id: "en3-havegot-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'My friends ___ got new bikes.'", options: ["have", "has", "is", "am"], correctIndex: 0, xp: 15, explanation: "«My friends» cəmdir, ona görə have işlənir.", skills: ["en.gram.have"] },
          ],
          bonusTasks: [
            { id: "en3-havegot-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "Sual: '___ you got a pen?'", options: ["Have", "Has", "Do", "Are"], correctIndex: 0, xp: 15, explanation: "«You» ilə have işlənir, sualda isə əvvələ keçir: Have you got...?", skills: ["en.gram.have"] },
            { id: "en3-havegot-rule-b2", type: "multiple_choice", speakOptions: true, prompt: "Sual: '___ she got a sister?'", options: ["Has", "Have", "Do", "Is"], correctIndex: 0, xp: 15, explanation: "«She» üçüncü şəxs təkdir, ona görə sualda has əvvələ keçir: Has she got...?", skills: ["en.gram.have"] },
            { id: "en3-havegot-rule-b3", type: "multiple_choice", prompt: "'He hasn't got a phone.' nə deməkdir?", options: ["Onun telefonu yoxdur.", "Onun telefonu var.", "Telefon istəyir.", "Telefon aldı."], correctIndex: 0, xp: 15, explanation: "Hasn't = has not, yəni inkardır. Deməli «Onun telefonu yoxdur».", skills: ["en.gram.have"] },
            { id: "en3-havegot-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "'I have got two ___.' (bacı — cəm)", options: ["sisters", "sister", "sisteres", "sisters's"], correctIndex: 0, xp: 15, explanation: "Two sözü çoxluq bildirir, ona görə isim cəm olmalıdır: sisters.", skills: ["en.gram.have"] },
            { id: "en3-havegot-rule-b5", type: "multiple_choice", speakOptions: true, prompt: "'She has got long ___.' (saç)", options: ["hair", "hairs", "a hair", "hairy"], correctIndex: 0, xp: 15, explanation: "Hair sözü baş tükünün hamısını bildirir və cəm işlənmir — «hairs» ayrı-ayrı tüklər deməkdir.", skills: ["en.gram.have"] },
          ],
        },
        {
          id: "en3-havegot-q",
          title: "Have got — sual və inkar",
          intro: "Nəyisə var/yox demək.",
          sections: [
            { heading: "Sual", body: "'Have you got a pen?' — Qələmin var? Cavab: 'Yes, I have.' / 'No, I haven't.'" },
            { heading: "İnkar", body: "'I haven't got a car.' — Maşınım yoxdur. 'He hasn't got a dog.' — Onun iti yoxdur." },
          ],
          tasks: [
            { id: "en3-havegot-q-t1", type: "multiple_choice", prompt: "'Have you got a pen?' nə deməkdir?", options: ["Qələmin var?", "Qələm alırsan?", "Qələm verirsən?", "Qələm haradadır?"], correctIndex: 0, xp: 10, explanation: "Have you got...? = ...var?, pen = qələm.", skills: ["en.gram.have"] },
            { id: "en3-havegot-q-t2", type: "multiple_choice", prompt: "'I haven't got a car.' nə deməkdir?", options: ["Maşınım yoxdur.", "Maşınım var.", "Maşın alıram.", "Maşın sürürəm."], correctIndex: 0, xp: 10, explanation: "Haven't got inkardır, car = maşın. Deməli «Maşınım yoxdur».", skills: ["en.gram.have"] },
            { id: "en3-havegot-q-t3", type: "multiple_choice", prompt: "'He ______ got a dog.' — inkar forma hansıdır?", options: ["hasn't", "haven't", "not has", "don't"], correctIndex: 0, xp: 10, explanation: "«He» üçüncü şəxs təkdir, ona görə inkar hasn't olur.", skills: ["en.gram.have"] },
            { id: "en3-havegot-q-t4", type: "multiple_choice", prompt: "'Yes, I have.' nə deməkdir?", options: ["Bəli, var.", "Xeyr, yoxdur.", "Bilmirəm.", "Bəlkə."], correctIndex: 0, xp: 10, explanation: "«Have you got...?» sualına qısa təsdiq cavabı «Yes, I have» olur.", skills: ["en.gram.have"] },
            { id: "en3-havegot-q-t5", type: "multiple_choice", prompt: "'She ______ got two sisters.' — düzgün forma hansıdır?", options: ["has", "have", "haves", "having"], correctIndex: 0, xp: 10, explanation: "«She» üçüncü şəxs təkdir, ona görə has işlənir.", skills: ["en.gram.have"] },
            { id: "en3-havegot-q-t6", type: "multiple_choice", prompt: "'They ______ got a big house.' — düzgün forma hansıdır?", options: ["have", "has", "haves", "having"], correctIndex: 0, xp: 10, explanation: "«They» cəmdir, ona görə have işlənir.", skills: ["en.gram.have"] },
            { id: "en3-havegot-q-t7", type: "multiple_choice", prompt: "'Has he got a bike?' sualına müsbət cavab hansıdır?", options: ["Yes, he has.", "Yes, he have.", "Yes, he is.", "Yes, he does."], correctIndex: 0, xp: 10, explanation: "Sual has ilə qurulub, ona görə cavab da has ilə verilir: «Yes, he has».", skills: ["en.gram.have"] },
            { id: "en3-havegot-q-t8", type: "multiple_choice", prompt: "'have got' nə bildirir?", options: ["Sahiblik", "Hərəkət", "Yer", "Zaman"], correctIndex: 0, xp: 10, explanation: "Have got nəyinsə kiməsə aid olduğunu, yəni sahibliyi bildirir.", skills: ["en.gram.have"] },
            { id: "en3-havegot-q-t9", type: "multiple_choice", prompt: "'I have got a brother.' nə deməkdir?", options: ["Qardaşım var.", "Qardaşım yoxdur.", "Qardaşam.", "Qardaşımı görürəm."], correctIndex: 0, xp: 10, explanation: "Have got sahiblik bildirir, brother = qardaş.", skills: ["en.gram.have"] },
            { id: "en3-havegot-q-t10", type: "multiple_choice", prompt: "'we' ilə hansı forma işlənir?", options: ["have got", "has got", "haves got", "having got"], correctIndex: 0, xp: 10, explanation: "«We» cəmdir, ona görə have got işlənir.", skills: ["en.gram.have"] },
          ],
          bonusTasks: [
            { id: "en3-havegot-q-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I have got a cat.", options: ["Pişiyim var.", "Pişiyim yoxdur.", "Pişik görürəm.", "Pişik istəyirəm."], correctIndex: 0, xp: 15, explanation: "Səsdə «I have got a cat» deyildi. Have got sahiblik bildirir — deməli «Pişiyim var».", skills: ["en.gram.have","en.listen"] },
            { id: "en3-havegot-q-b2", type: "multiple_choice", prompt: "'Has your sister got a phone?' cümləsində 'has' niyə işlənib?", options: ["Çünki 'sister' — he/she/it kimidir", "Səhvdir", "Çünki sualdır", "Çünki keçmişdir"], correctIndex: 0, xp: 15, explanation: "«Sister» bir nəfəri bildirir, yəni üçüncü şəxs təkdir — he/she/it kimi has tələb edir.", skills: ["en.gram.have"] },
            { id: "en3-havegot-q-b3", type: "multiple_choice", prompt: "'haven't got' hansı sözlərin qısaldılmasıdır?", options: ["have not got", "has not got", "had not got", "having not got"], correctIndex: 0, xp: 15, explanation: "Haven't sözü have not birləşməsinin qısa formasıdır.", skills: ["en.gram.have"] },
            { id: "en3-havegot-q-b4", type: "multiple_choice", prompt: "'I have got' əvəzinə danışıqda nə deyilir?", options: ["I've got", "I has got", "I got have", "I am got"], correctIndex: 0, xp: 15, explanation: "Danışıqda have sözü qısalır və əvəzliyə birləşir: I have got → I've got.", skills: ["en.gram.have"] },
          ],
        },
        {
          id: "en3-havegot-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en3-havegot-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 3. Can / can't ═══════════════
    {
      id: "en3-can",
      title: "Can / can't (bacarıq)",
      description: "Bacarıq bildirmək: I can swim. I can't fly.",
      lessons: [
        {
          id: "en3-can-rule",
          title: "Qayda: can / can't",
          intro: "can — bacarmaq. can + feil (əsas forma).",
          sections: [
            { heading: "can", body: "Bacarıq bildirir: I can swim. She can run. can-dan sonra feil sadə formada gəlir (bütün şəxslərdə eyni)." },
            { heading: "can't", body: "İnkar: cannot / can't. I can't fly. He can't drive." },
          ],
          tasks: [
            { id: "en3-can-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'I ___ swim.' (üzə bilirəm)", options: ["can", "cans", "am", "do"], correctIndex: 0, xp: 10, explanation: "Bacarıq can sözü ilə bildirilir; ondan sonra feil dəyişmir.", skills: ["en.gram.can"] },
            { id: "en3-can-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'She ___ run fast.'", options: ["can", "cans", "is", "does"], correctIndex: 0, xp: 10, explanation: "Can şəxsə görə dəyişmir — she ilə də sadəcə can işlənir, «cans» yoxdur.", skills: ["en.gram.can"] },
            { id: "en3-can-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "can-dan sonra feil hansı formada gəlir?", options: ["əsas forma (swim)", "V-ing (swimming)", "V2 (swam)", "to + V"], correctIndex: 0, xp: 10, explanation: "Can-dan sonra feil əsas formada qalır: nə to, nə -s, nə də -ing əlavə olunmur.", skills: ["en.gram.can"] },
            { id: "en3-can-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'I ___ fly.'", options: ["can't", "don't", "isn't", "not can"], correctIndex: 0, xp: 10, explanation: "Can sözünün inkarı can't-dır.", skills: ["en.gram.can"] },
            { id: "en3-can-rule-t5", type: "multiple_choice", prompt: "'I can swim.' nə deməkdir?", options: ["Üzə bilirəm.", "Üzürəm.", "Üzdüm.", "Üzmək istəyirəm."], correctIndex: 0, xp: 10, explanation: "Can bacarıq bildirir. Deməli «Üzə bilirəm», sadəcə «üzürəm» yox.", skills: ["en.gram.can"] },
            { id: "en3-can-rule-t6", type: "multiple_choice", prompt: "'He can't drive.' nə deməkdir?", options: ["O sürə bilmir.", "O sürür.", "O sürdü.", "O maşın aldı."], correctIndex: 0, xp: 10, explanation: "Can't bacarmamağı bildirir, drive = sürmək.", skills: ["en.gram.can"] },
            { id: "en3-can-rule-t7", type: "multiple_choice", speakOptions: true, prompt: "'Birds ___ fly.'", options: ["can", "cans", "are", "do"], correctIndex: 0, xp: 10, explanation: "Quşlar uça bilir; bacarıq can ilə bildirilir və cəmdə də dəyişmir.", skills: ["en.gram.can"] },
            { id: "en3-can-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'Fish ___ walk.' (bacarmır)", options: ["can't", "don't", "aren't", "not"], correctIndex: 0, xp: 10, explanation: "Balıq yeriyə bilmir — bacarmamaq can't ilə bildirilir.", skills: ["en.gram.can"] },
            { id: "en3-can-rule-t9", type: "multiple_choice", speakOptions: true, prompt: "'We ___ sing.'", options: ["can", "cans", "are", "do"], correctIndex: 0, xp: 10, explanation: "Bacarıq can ilə bildirilir; can şəxsə görə dəyişmir.", skills: ["en.gram.can"] },
            { id: "en3-can-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "'I can ___.' (oxumaq — kitab)", options: ["read", "reads", "reading", "to read"], correctIndex: 0, xp: 10, explanation: "Can-dan sonra feil əsas formada gəlir: read.", skills: ["en.gram.can"] },
            { id: "en3-can-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "Sual: '___ you swim?'", options: ["Can", "Do", "Are", "Is"], correctIndex: 0, xp: 10, explanation: "Bacarıq sualında can əvvələ keçir: Can you swim?", skills: ["en.gram.can"] },
            { id: "en3-can-rule-t12", type: "multiple_choice", prompt: "'Can you help me?' nə deməkdir?", options: ["Mənə kömək edə bilərsən?", "Mənə kömək et.", "Kömək etdin?", "Kömək istəyirsən?"], correctIndex: 0, xp: 10, explanation: "Can burada nəzakətli xahiş bildirir, help = kömək etmək.", skills: ["en.gram.can"] },
            { id: "en3-can-rule-t13", type: "multiple_choice", speakOptions: true, prompt: "'A cat ___ climb trees.'", options: ["can", "cans", "is", "does"], correctIndex: 0, xp: 10, explanation: "Bacarıq can ilə bildirilir; «a cat» üçün də sadəcə can işlənir.", skills: ["en.gram.can"] },
            { id: "en3-can-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "'I ___ speak English.' (bacarıram)", options: ["can", "am", "do", "have"], correctIndex: 0, xp: 10, explanation: "Dil bilmək bacarıqdır, ona görə can işlənir.", skills: ["en.gram.can"] },
            { id: "en3-can-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'She ___ ride a bike.' (bacarır)", options: ["can", "cans", "is", "does"], correctIndex: 0, xp: 15, explanation: "Bacarıq can ilə bildirilir; she ilə də dəyişmir.", skills: ["en.gram.can"] },
          ],
          bonusTasks: [
            { id: "en3-can-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "'Penguins can't ___.' (uçmaq)", options: ["fly", "flies", "flying", "flew"], correctIndex: 0, xp: 15, explanation: "Can't-dan sonra feil əsas formada gəlir: fly.", skills: ["en.gram.can"] },
            { id: "en3-can-rule-b2", type: "multiple_choice", prompt: "'I can jump but I can't fly.' nə deməkdir?", options: ["Tullana bilirəm, amma uça bilmirəm.", "Uça bilirəm.", "Tullanmıram.", "Uçuram."], correctIndex: 0, xp: 15, explanation: "Cümlədə iki hissə var: can jump (tullana bilirəm) və can't fly (uça bilmirəm). But = amma.", skills: ["en.gram.can"] },
            { id: "en3-can-rule-b3", type: "multiple_choice", speakOptions: true, prompt: "'Can dogs swim?' — Yes, they ___.", options: ["can", "do", "are", "have"], correctIndex: 0, xp: 15, explanation: "Sual can ilə qurulub, ona görə cavab da can ilə verilir: «Yes, they can».", skills: ["en.gram.can"] },
            { id: "en3-can-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "'I can ___ a picture.' (çəkmək)", options: ["draw", "draws", "drawing", "drew"], correctIndex: 0, xp: 15, explanation: "Can-dan sonra feil əsas formada gəlir: draw = rəsm çəkmək.", skills: ["en.gram.can"] },
            { id: "en3-can-rule-b5", type: "multiple_choice", prompt: "'Can I go out?' nə deməkdir?", options: ["Çölə çıxa bilərəm?", "Çölə çıxdım.", "Çölə çıx.", "Çöldəyəm."], correctIndex: 0, xp: 15, explanation: "Can burada icazə istəmək üçün işlənir: «Çölə çıxa bilərəm?»", skills: ["en.gram.can"] },
          ],
        },
        {
          id: "en3-can-ability",
          title: "Can — bacarıq və icazə",
          intro: "İki mənası var: bacarmaq və icazə istəmək.",
          sections: [
            { heading: "Bacarıq", body: "'I can swim.' — Üzə bilirəm. 'She can't drive.' — O, sürə bilmir." },
            { heading: "İcazə", body: "'Can I go out?' — Çölə çıxa bilərəm? 'Can you help me?' — Mənə kömək edə bilərsən?" },
          ],
          tasks: [
            { id: "en3-can-ability-t1", type: "multiple_choice", prompt: "'Can I go out?' nə deməkdir?", options: ["Çölə çıxa bilərəm?", "Çölə çıxıram.", "Çölə çıxdım.", "Çölə çıxma!"], correctIndex: 0, xp: 10, explanation: "Can burada icazə istəyir, go out = çölə çıxmaq.", skills: ["en.gram.can"] },
            { id: "en3-can-ability-t2", type: "multiple_choice", prompt: "'Can you help me?' nə deməkdir?", options: ["Mənə kömək edə bilərsən?", "Mənə kömək etdin.", "Mən sənə kömək edirəm.", "Kömək lazımdır."], correctIndex: 0, xp: 10, explanation: "Can burada nəzakətli xahiş bildirir, help me = mənə kömək etmək.", skills: ["en.gram.can"] },
            { id: "en3-can-ability-t3", type: "multiple_choice", prompt: "'She can't drive.' nə deməkdir?", options: ["O, sürə bilmir.", "O, sürür.", "O, sürəcək.", "O, sürdü."], correctIndex: 0, xp: 10, explanation: "Can't bacarmamağı bildirir, drive = sürmək.", skills: ["en.gram.can"] },
            { id: "en3-can-ability-t4", type: "multiple_choice", prompt: "'can' sözündən sonra feil necə olur?", options: ["Sadə forma: can swim", "can swims", "can swimming", "can to swim"], correctIndex: 0, xp: 10, explanation: "Can-dan sonra feil dəyişmir — nə -s, nə -ing, nə də to qoşulur.", skills: ["en.gram.can"] },
            { id: "en3-can-ability-t5", type: "multiple_choice", prompt: "'can't' hansı sözlərin qısaldılmasıdır?", options: ["cannot", "can not to", "can no", "could not"], correctIndex: 0, xp: 10, explanation: "Can't sözü cannot birləşməsinin qısa formasıdır.", skills: ["en.gram.can"] },
            { id: "en3-can-ability-t6", type: "multiple_choice", speakOptions: true, prompt: "'üzmək' İngiliscə necədir?", options: ["swim", "sing", "sit", "see"], correctIndex: 0, xp: 10, explanation: "«Üzmək» ingiliscə swim olur. Sing = mahnı oxumaq, sit = oturmaq.", skills: ["en.gram.can"] },
            { id: "en3-can-ability-t7", type: "multiple_choice", prompt: "'Can he play the piano?' sualına müsbət cavab hansıdır?", options: ["Yes, he can.", "Yes, he does.", "Yes, he is.", "Yes, he has."], correctIndex: 0, xp: 10, explanation: "Sual can ilə qurulub, ona görə cavab da can ilə verilir: «Yes, he can».", skills: ["en.gram.can"] },
            { id: "en3-can-ability-t8", type: "multiple_choice", prompt: "'can' hansı iki mənanı bildirir?", options: ["Bacarıq və icazə", "Zaman və yer", "Say və rəng", "Ad və hərəkət"], correctIndex: 0, xp: 10, explanation: "Can həm bacarığı (I can swim), həm də icazəni (Can I go out?) bildirir.", skills: ["en.gram.can"] },
            { id: "en3-can-ability-t9", type: "multiple_choice", prompt: "'We can speak English.' nə deməkdir?", options: ["Biz İngiliscə danışa bilirik.", "Biz İngiliscə danışırıq.", "Biz İngiliscə danışdıq.", "Biz İngiliscə öyrənirik."], correctIndex: 0, xp: 10, explanation: "Can bacarıq bildirir — sadəcə danışmaq yox, danışa bilmək.", skills: ["en.gram.can"] },
            { id: "en3-can-ability-t10", type: "multiple_choice", prompt: "'I can't see.' nə deməkdir?", options: ["Görə bilmirəm.", "Görürəm.", "Gördüm.", "Görəcəyəm."], correctIndex: 0, xp: 10, explanation: "Can't bacarmamağı bildirir, see = görmək.", skills: ["en.gram.can"] },
          ],
          bonusTasks: [
            { id: "en3-can-ability-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Can you swim?", options: ["Üzə bilirsən?", "Üzürsən?", "Üzdün?", "Üzəcəksən?"], correctIndex: 0, xp: 15, explanation: "Səsdə «Can you swim?» deyildi. Can bacarıq soruşur — deməli «Üzə bilirsən?»", skills: ["en.gram.can","en.listen"] },
            { id: "en3-can-ability-b2", type: "multiple_choice", prompt: "'Could' sözü 'can'-in hansı formasıdır?", options: ["Keçmiş / nəzakətli forma", "Gələcək", "Cəm", "İnkar"], correctIndex: 0, xp: 15, explanation: "Could can sözünün keçmiş formasıdır və nəzakətli xahişdə də işlənir: «Could you help me?»", skills: ["en.gram.can","en.gram.prepositions"] },
            { id: "en3-can-ability-b3", type: "multiple_choice", prompt: "'Can I have some water, please?' cümləsi nə bildirir?", options: ["Nəzakətli xahiş", "Əmr", "Şikayət", "Sual-cavab"], correctIndex: 0, xp: 15, explanation: "Can I have...? + please birləşməsi nəzakətli xahişdir, əmr deyil.", skills: ["en.gram.quantifiers","en.gram.can"] },
            { id: "en3-can-ability-b4", type: "multiple_choice", prompt: "'can' feili şəxsə görə dəyişirmi?", options: ["Xeyr: I can, he can", "Bəli: he cans", "Yalnız cəmdə", "Yalnız sualda"], correctIndex: 0, xp: 15, explanation: "Can bütün şəxslərdə eyni qalır: I can, you can, he can — «cans» forması yoxdur.", skills: ["en.gram.can"] },
          ],
        },
        {
          id: "en3-can-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en3-can-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 4. Sözönləri ═══════════════
    {
      id: "en3-prep",
      title: "Sözönləri (in / on / under)",
      description: "Yer bildirən sözönləri: in, on, under, next to.",
      lessons: [
        {
          id: "en3-prep-vocab",
          title: "Prepositions of place",
          intro: "Əşyanın harada olduğunu bildirən sözlər.",
          sections: [
            { heading: "Sözönləri", body: "in — içində, on — üstündə, under — altında, next to — yanında, behind — arxasında, in front of — qarşısında." },
          ],
          tasks: [
            { id: "en3-prep-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'in' nə deməkdir?", options: ["içində", "üstündə", "altında", "yanında"], correctIndex: 0, xp: 10, explanation: "In sözü nəyinsə bir şeyin daxilində olduğunu bildirir — «içində».", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'on' nə deməkdir?", options: ["üstündə", "içində", "altında", "arxasında"], correctIndex: 0, xp: 10, explanation: "On sözü səthin üzərində olmağı bildirir — «üstündə».", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'under' nə deməkdir?", options: ["altında", "üstündə", "içində", "yanında"], correctIndex: 0, xp: 10, explanation: "Under sözü aşağıda olmağı bildirir — «altında».", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'next to' nə deməkdir?", options: ["yanında", "altında", "üstündə", "içində"], correctIndex: 0, xp: 10, explanation: "Next to sözü yan-yana olmağı bildirir — «yanında».", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'The book is ___ the table.' (üstündə)", options: ["on", "in", "under", "next"], correctIndex: 0, xp: 10, explanation: "Kitab masanın səthinin üzərindədir, ona görə on işlənir.", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'The cat is ___ the box.' (içində)", options: ["in", "on", "under", "next to"], correctIndex: 0, xp: 10, explanation: "Pişik qutunun daxilindədir, ona görə in işlənir.", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'The ball is ___ the chair.' (altında)", options: ["under", "on", "in", "next to"], correctIndex: 0, xp: 10, explanation: "Top stulun aşağısındadır, ona görə under işlənir.", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "'The pen is ___ the book.' (yanında)", options: ["next to", "in", "under", "on"], correctIndex: 0, xp: 10, explanation: "Qələm kitabın yanındadır, ona görə next to işlənir.", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-vocab-t9", type: "multiple_choice", prompt: "'The apple is on the table.' nə deməkdir?", options: ["Alma masanın üstündədir.", "Alma masanın altındadır.", "Alma qutudadır.", "Alma yoxdur."], correctIndex: 0, xp: 10, explanation: "On = üstündə, table = masa. Deməli «Alma masanın üstündədir».", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-vocab-t10", type: "multiple_choice", prompt: "'The dog is under the bed.' nə deməkdir?", options: ["İt çarpayının altındadır.", "İt çarpayının üstündədir.", "İt qutudadır.", "İt qaçır."], correctIndex: 0, xp: 10, explanation: "Under = altında, bed = çarpayı. Deməli «İt çarpayının altındadır».", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-vocab-t11", type: "multiple_choice", speakOptions: true, prompt: "'behind' nə deməkdir?", options: ["arxasında", "qarşısında", "içində", "üstündə"], correctIndex: 0, xp: 10, explanation: "Behind sözü arxa tərəfdə olmağı bildirir — «arxasında».", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-vocab-t12", type: "multiple_choice", speakOptions: true, prompt: "'in front of' nə deməkdir?", options: ["qarşısında", "arxasında", "altında", "içində"], correctIndex: 0, xp: 10, explanation: "In front of sözü ön tərəfdə olmağı bildirir — «qarşısında».", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "'The keys are ___ my bag.' (içində)", options: ["in", "on", "under", "next to"], correctIndex: 0, xp: 10, explanation: "Açarlar çantanın daxilindədir, ona görə in işlənir.", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'The picture is ___ the wall.' (üstündə/divarda)", options: ["on", "in", "under", "behind"], correctIndex: 0, xp: 10, explanation: "İngiliscə divardan asılan şeylər üçün on işlənir: on the wall.", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-vocab-t15", type: "multiple_choice", prompt: "'The cat is in the box.' nə deməkdir?", options: ["Pişik qutunun içindədir.", "Pişik qutunun üstündədir.", "Pişik qutunun altındadır.", "Pişik yoxdur."], correctIndex: 0, xp: 15, explanation: "In = içində, box = qutu. Deməli «Pişik qutunun içindədir».", skills: ["en.gram.prepositions"] },
          ],
          bonusTasks: [
            { id: "en3-prep-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'The car is ___ the house.' (qarşısında)", options: ["in front of", "in", "under", "on"], correctIndex: 0, xp: 15, explanation: "Maşın evin ön tərəfindədir, ona görə in front of işlənir.", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'The boy is ___ the tree.' (arxasında)", options: ["behind", "on", "in", "under"], correctIndex: 0, xp: 15, explanation: "Oğlan ağacın arxa tərəfindədir, ona görə behind işlənir.", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'between' nə deməkdir?", options: ["arasında", "yanında", "arxasında", "içində"], correctIndex: 0, xp: 15, explanation: "Between sözü iki şeyin ortasında olmağı bildirir — «arasında».", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-vocab-b4", type: "multiple_choice", prompt: "'Where is the ball?' nə deməkdir?", options: ["Top haradadır?", "Top nədir?", "Top kimindir?", "Top böyükdür?"], correctIndex: 0, xp: 15, explanation: "Where = harada. Deməli sual topun yerini soruşur.", skills: ["en.gram.questions"] },
            { id: "en3-prep-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'The shoes are ___ the bed.' (altında)", options: ["under", "on", "in", "next to"], correctIndex: 0, xp: 15, explanation: "Ayaqqabılar çarpayının aşağısındadır, ona görə under işlənir.", skills: ["en.gram.prepositions"] },
          ],
        },
        {
          id: "en3-prep-where",
          title: "Where is it?",
          intro: "Sözönlərini sualda işlədək.",
          sections: [
            { heading: "Sual", body: "'Where is the ball?' — Top haradadır? 'It is under the table.' — Masanın altındadır." },
            { heading: "Daha çox sözönü", body: "in — içində, on — üstündə, under — altında, next to — yanında, behind — arxasında, in front of — qarşısında." },
          ],
          tasks: [
            { id: "en3-prep-where-t1", type: "multiple_choice", prompt: "'Where is the ball?' nə deməkdir?", options: ["Top haradadır?", "Top nədir?", "Top kimindir?", "Top necədir?"], correctIndex: 0, xp: 10, explanation: "Where = harada. Deməli sual topun yerini soruşur.", skills: ["en.gram.questions"] },
            { id: "en3-prep-where-t2", type: "multiple_choice", prompt: "'The cat is under the chair.' nə deməkdir?", options: ["Pişik stulun altındadır.", "Pişik stulun üstündədir.", "Pişik stulun yanındadır.", "Pişik stuldadır."], correctIndex: 0, xp: 10, explanation: "Under = altında, chair = stul. Deməli «Pişik stulun altındadır».", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-where-t3", type: "multiple_choice", speakOptions: true, prompt: "'yanında' İngiliscə necədir?", options: ["next to", "under", "behind", "in"], correctIndex: 0, xp: 10, explanation: "«Yanında» ingiliscə next to olur.", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-where-t4", type: "multiple_choice", speakOptions: true, prompt: "'arxasında' İngiliscə necədir?", options: ["behind", "in front of", "next to", "on"], correctIndex: 0, xp: 10, explanation: "«Arxasında» ingiliscə behind olur.", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-where-t5", type: "multiple_choice", speakOptions: true, prompt: "'qarşısında' İngiliscə necədir?", options: ["in front of", "behind", "under", "in"], correctIndex: 0, xp: 10, explanation: "«Qarşısında» ingiliscə in front of olur.", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-where-t6", type: "multiple_choice", prompt: "'The book is on the table.' nə deməkdir?", options: ["Kitab masanın üstündədir.", "Kitab masanın altındadır.", "Kitab masadadır.", "Kitab masanın yanındadır."], correctIndex: 0, xp: 10, explanation: "On = üstündə, table = masa. Deməli «Kitab masanın üstündədir».", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-where-t7", type: "multiple_choice", prompt: "'in the box' nə deməkdir?", options: ["qutunun içində", "qutunun üstündə", "qutunun altında", "qutunun yanında"], correctIndex: 0, xp: 10, explanation: "In = içində, box = qutu.", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-where-t8", type: "multiple_choice", prompt: "Sual sözü 'where' nəyi soruşur?", options: ["Yeri", "Vaxtı", "Səbəbi", "Adı"], correctIndex: 0, xp: 10, explanation: "Where sual sözü əşyanın harada olduğunu, yəni yerini soruşur.", skills: ["en.gram.questions"] },
            { id: "en3-prep-where-t9", type: "multiple_choice", speakOptions: true, prompt: "'altında' İngiliscə necədir?", options: ["under", "over", "on", "in"], correctIndex: 0, xp: 10, explanation: "«Altında» ingiliscə under olur. Over isə yuxarıda, toxunmadan deməkdir.", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-where-t10", type: "multiple_choice", prompt: "'It is between the chairs.' nə deməkdir?", options: ["Stulların arasındadır.", "Stulun altındadır.", "Stulun üstündədir.", "Stulun yanındadır."], correctIndex: 0, xp: 10, explanation: "Between = arasında, chairs = stullar (cəm). Deməli «Stulların arasındadır».", skills: ["en.gram.prepositions"] },
          ],
          bonusTasks: [
            { id: "en3-prep-where-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The pen is on the desk.", options: ["Qələm masanın üstündədir.", "Qələm masanın altındadır.", "Qələm çantadadır.", "Qələm yerdədir."], correctIndex: 0, xp: 15, explanation: "Səsdə «The pen is on the desk» deyildi. On = üstündə, desk = masa.", skills: ["en.gram.prepositions","en.listen"] },
            { id: "en3-prep-where-b2", type: "multiple_choice", prompt: "'Where are my shoes?' — 'are' niyə işlənib?", options: ["Çünki 'shoes' cəmdir", "Səhvdir", "Çünki sualdır", "Çünki keçmişdir"], correctIndex: 0, xp: 15, explanation: "Shoes sözü -s ilə bitir və cəmdir, cəm isimlə isə is yox, are işlənir.", skills: ["en.gram.questions"] },
            { id: "en3-prep-where-b3", type: "multiple_choice", speakOptions: true, prompt: "'arasında' İngiliscə necədir?", options: ["between", "behind", "beside", "below"], correctIndex: 0, xp: 15, explanation: "«Arasında» ingiliscə between olur. Behind = arxasında, beside = yanında.", skills: ["en.gram.prepositions"] },
            { id: "en3-prep-where-b4", type: "multiple_choice", prompt: "'The dog is in front of the house.' nə deməkdir?", options: ["İt evin qarşısındadır.", "İt evin arxasındadır.", "İt evdədir.", "İt evin altındadır."], correctIndex: 0, xp: 15, explanation: "In front of = qarşısında, house = ev. Behind olsaydı «arxasında» olardı.", skills: ["en.gram.prepositions"] },
          ],
        },
        {
          id: "en3-prep-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en3-prep-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 5. Gündəlik rejim və saat ═══════════════
    {
      id: "en3-routine",
      title: "Gündəlik rejim və saat",
      description: "Gündəlik işlər və saatın deyilməsi.",
      lessons: [
        {
          id: "en3-routine-vocab",
          title: "Daily routines & time",
          intro: "Gündəlik işlər və saat sözləri.",
          sections: [
            { heading: "Rejim", body: "get up — durmaq, have breakfast — səhər yeməyi yemək, go to school — məktəbə getmək, do homework — ev tapşırığı etmək, go to bed — yatmağa getmək." },
            { heading: "Saat", body: "'What time is it?' — Saat neçədir? 'It is seven o'clock.' — Saat yeddidir." },
          ],
          tasks: [
            { id: "en3-routine-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'get up' nə deməkdir?", options: ["durmaq (yuxudan)", "yatmaq", "yemək", "getmək"], correctIndex: 0, xp: 10, explanation: "Get up yuxudan qalxmağı bildirir — «durmaq».", skills: ["en.vocab.topic"] },
            { id: "en3-routine-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'have breakfast' nə deməkdir?", options: ["səhər yeməyi yemək", "nahar etmək", "yatmaq", "durmaq"], correctIndex: 0, xp: 10, explanation: "Breakfast = səhər yeməyi; have breakfast onu yemək deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en3-routine-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'go to school' nə deməkdir?", options: ["məktəbə getmək", "evə getmək", "yatmaq", "oynamaq"], correctIndex: 0, xp: 10, explanation: "Go = getmək, school = məktəb.", skills: ["en.vocab.topic"] },
            { id: "en3-routine-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'do homework' nə deməkdir?", options: ["ev tapşırığı etmək", "ev təmizləmək", "oynamaq", "yatmaq"], correctIndex: 0, xp: 10, explanation: "Homework = ev tapşırığı; do homework onu yerinə yetirmək deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en3-routine-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'go to bed' nə deməkdir?", options: ["yatmağa getmək", "durmaq", "yemək", "gəzmək"], correctIndex: 0, xp: 10, explanation: "Bed = çarpayı; go to bed yatmağa getmək deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en3-routine-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'What time is it?' nə deməkdir?", options: ["Saat neçədir?", "Nə vaxt gəlirsən?", "Necəsən?", "Haradadır?"], correctIndex: 0, xp: 10, explanation: "Time = vaxt, saat. Deməli sual «Saat neçədir?» deməkdir.", skills: ["en.gram.questions"] },
            { id: "en3-routine-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'It is seven o'clock.' nə deməkdir?", options: ["Saat yeddidir.", "Saat altıdır.", "Yeddi dəqiqə.", "Yeddinci gün."], correctIndex: 0, xp: 10, explanation: "O'clock tam saatı bildirir, seven = 7. Deməli «Saat yeddidir».", skills: ["en.vocab.topic"] },
            { id: "en3-routine-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "'morning' nə deməkdir?", options: ["səhər", "axşam", "gecə", "günorta"], correctIndex: 0, xp: 10, explanation: "Morning azərbaycanca «səhər» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en3-routine-vocab-t9", type: "multiple_choice", speakOptions: true, prompt: "'evening' nə deməkdir?", options: ["axşam", "səhər", "gecə", "günorta"], correctIndex: 0, xp: 10, explanation: "Evening azərbaycanca «axşam» deməkdir. Night isə gecədir.", skills: ["en.vocab.topic"] },
            { id: "en3-routine-vocab-t10", type: "multiple_choice", speakOptions: true, prompt: "'night' nə deməkdir?", options: ["gecə", "səhər", "axşam", "gündüz"], correctIndex: 0, xp: 10, explanation: "Night azərbaycanca «gecə» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en3-routine-vocab-t11", type: "multiple_choice", speakOptions: true, prompt: "'I get up at 7.' nə deməkdir?", options: ["Saat 7-də dururam.", "Saat 7-də yatıram.", "Saat 7-də yeyirəm.", "Saat 7-də gəlirəm."], correctIndex: 0, xp: 10, explanation: "Get up = durmaq, at 7 = saat 7-də.", skills: ["en.vocab.topic"] },
            { id: "en3-routine-vocab-t12", type: "multiple_choice", speakOptions: true, prompt: "'have lunch' nə deməkdir?", options: ["nahar etmək", "səhər yeməyi", "şam etmək", "yatmaq"], correctIndex: 0, xp: 10, explanation: "Lunch = nahar; have lunch nahar etmək deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en3-routine-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "'have dinner' nə deməkdir?", options: ["şam etmək", "nahar etmək", "səhər yeməyi", "durmaq"], correctIndex: 0, xp: 10, explanation: "Dinner = şam yeməyi; have dinner şam etmək deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en3-routine-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'It is nine o'clock.' saat neçədir?", options: ["9", "8", "10", "7"], correctIndex: 0, xp: 10, explanation: "Nine = 9, o'clock isə tam saatı bildirir.", skills: ["en.vocab.topic"] },
            { id: "en3-routine-vocab-t15", type: "multiple_choice", speakOptions: true, prompt: "'wash my face' nə deməkdir?", options: ["üzümü yumaq", "dişimi təmizləmək", "saçımı daramaq", "əlimi yumaq"], correctIndex: 0, xp: 15, explanation: "Wash = yumaq, face = üz.", skills: ["en.vocab.topic"] },
          ],
          bonusTasks: [
            { id: "en3-routine-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'I go to bed at ten.' nə deməkdir?", options: ["Saat 10-da yatıram.", "Saat 10-da dururam.", "Saat 10-da yeyirəm.", "Saat 10-da oxuyuram."], correctIndex: 0, xp: 15, explanation: "Go to bed = yatmağa getmək, at ten = saat 10-da.", skills: ["en.vocab.topic"] },
            { id: "en3-routine-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'It is half past six.' nə deməkdir?", options: ["Saat 6:30", "Saat altı", "Saat yeddi", "Saat 5:30"], correctIndex: 0, xp: 15, explanation: "Half = yarım, past = keçib. «Half past six» altını yarım saat keçib deməkdir, yəni 6:30.", skills: ["en.vocab.topic"] },
            { id: "en3-routine-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'afternoon' nə deməkdir?", options: ["günorta/nahardan sonra", "səhər", "gecə", "axşam"], correctIndex: 0, xp: 15, explanation: "Afternoon nahardan sonrakı vaxtı bildirir — «günorta».", skills: ["en.vocab.topic"] },
            { id: "en3-routine-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'I do my homework in the evening.' nə deməkdir?", options: ["Ev tapşırığımı axşam edirəm.", "Səhər ev tapşırığı edirəm.", "Ev tapşırığı yoxdur.", "Ev tapşırığını bitirdim."], correctIndex: 0, xp: 15, explanation: "Do homework = ev tapşırığı etmək, in the evening = axşam.", skills: ["en.gram.prepositions"] },
            { id: "en3-routine-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'get dressed' nə deməkdir?", options: ["geyinmək", "soyunmaq", "yumaq", "yatmaq"], correctIndex: 0, xp: 15, explanation: "Get dressed paltar geyinməyi bildirir.", skills: ["en.vocab.topic"] },
          ],
        },
        {
          id: "en3-routine-time",
          title: "What time is it?",
          intro: "Saatı İngiliscə demək.",
          sections: [
            { heading: "Saat", body: "'What time is it?' — Saat neçədir? 'It is seven o'clock.' — Saat yeddidir." },
            { heading: "Yarım və rüb", body: "half past seven — yeddi yarım (7:30), quarter past seven — yeddini on beş keçir (7:15)." },
          ],
          tasks: [
            { id: "en3-routine-time-t1", type: "multiple_choice", prompt: "'What time is it?' nə deməkdir?", options: ["Saat neçədir?", "Hansı gündür?", "Neçə yaşın var?", "Harada?"], correctIndex: 0, xp: 10, explanation: "Time = vaxt, saat. Deməli sual «Saat neçədir?» deməkdir.", skills: ["en.gram.questions"] },
            { id: "en3-routine-time-t2", type: "multiple_choice", prompt: "'It is seven o'clock.' nə deməkdir?", options: ["Saat yeddidir.", "Saat yeddi yarımdır.", "Yeddi yaşım var.", "Yeddinci gündür."], correctIndex: 0, xp: 10, explanation: "O'clock tam saatı bildirir, seven = 7.", skills: ["en.vocab.topic"] },
            { id: "en3-routine-time-t3", type: "multiple_choice", prompt: "'half past seven' saat neçədir?", options: ["7:30", "7:00", "7:15", "6:30"], correctIndex: 0, xp: 10, explanation: "Half past = yarım saat keçib. Deməli 7:30.", skills: ["en.vocab.topic"] },
            { id: "en3-routine-time-t4", type: "multiple_choice", prompt: "'quarter past seven' saat neçədir?", options: ["7:15", "7:45", "7:30", "7:00"], correctIndex: 0, xp: 10, explanation: "Quarter = rüb, yəni 15 dəqiqə. Quarter past seven — yeddini 15 dəqiqə keçib: 7:15.", skills: ["en.vocab.topic"] },
            { id: "en3-routine-time-t5", type: "multiple_choice", speakOptions: true, prompt: "'səhər' İngiliscə necədir?", options: ["morning", "evening", "night", "afternoon"], correctIndex: 0, xp: 10, explanation: "«Səhər» ingiliscə morning olur.", skills: ["en.vocab.topic"] },
            { id: "en3-routine-time-t6", type: "multiple_choice", speakOptions: true, prompt: "'axşam' İngiliscə necədir?", options: ["evening", "morning", "noon", "day"], correctIndex: 0, xp: 10, explanation: "«Axşam» ingiliscə evening olur. Night isə gecədir.", skills: ["en.vocab.topic"] },
            { id: "en3-routine-time-t7", type: "multiple_choice", prompt: "'I get up at seven.' nə deməkdir?", options: ["Saat yeddidə qalxıram.", "Saat yeddidə yatıram.", "Yeddi saat yatıram.", "Yeddi yaşım var."], correctIndex: 0, xp: 10, explanation: "Get up = qalxmaq, at seven = saat yeddidə. Yatmaq isə go to bed olardı.", skills: ["en.vocab.topic"] },
            { id: "en3-routine-time-t8", type: "multiple_choice", speakOptions: true, prompt: "'yatmaq' İngiliscə necədir?", options: ["sleep", "wake", "eat", "play"], correctIndex: 0, xp: 10, explanation: "«Yatmaq» ingiliscə sleep olur. Wake = oyanmaq.", skills: ["en.vocab.topic"] },
            { id: "en3-routine-time-t9", type: "multiple_choice", prompt: "'in the morning' nə deməkdir?", options: ["səhər", "axşam", "gecə", "günorta"], correctIndex: 0, xp: 10, explanation: "In the morning gündüzün ilk hissəsini, yəni səhəri bildirir.", skills: ["en.gram.prepositions"] },
            { id: "en3-routine-time-t10", type: "multiple_choice", speakOptions: true, prompt: "'nahar' İngiliscə necədir?", options: ["lunch", "breakfast", "dinner", "supper"], correctIndex: 0, xp: 10, explanation: "«Nahar» ingiliscə lunch olur. Breakfast səhər yeməyi, dinner isə şamdır.", skills: ["en.vocab.topic"] },
          ],
          bonusTasks: [
            { id: "en3-routine-time-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "It is nine o'clock.", options: ["Saat doqquzdur.", "Saat on birdir.", "Doqquz yaşım var.", "Doqquzuncu gündür."], correctIndex: 0, xp: 15, explanation: "Səsdə «It is nine o'clock» deyildi. Nine = 9, o'clock = tam saat.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en3-routine-time-b2", type: "multiple_choice", prompt: "'I have breakfast at 8.' nə deməkdir?", options: ["Saat 8-də səhər yeməyi yeyirəm.", "Saat 8-də nahar edirəm.", "8 saat yeyirəm.", "8 dəfə yeyirəm."], correctIndex: 0, xp: 15, explanation: "Have breakfast = səhər yeməyi yemək, at 8 = saat 8-də.", skills: ["en.vocab.topic"] },
            { id: "en3-routine-time-b3", type: "multiple_choice", speakOptions: true, prompt: "'səhər yeməyi' İngiliscə necədir?", options: ["breakfast", "lunch", "dinner", "snack"], correctIndex: 0, xp: 15, explanation: "«Səhər yeməyi» ingiliscə breakfast olur.", skills: ["en.vocab.topic"] },
            { id: "en3-routine-time-b4", type: "multiple_choice", prompt: "'at night' nə deməkdir?", options: ["gecə", "səhər", "günorta", "axşam"], correctIndex: 0, xp: 15, explanation: "At night gecə vaxtını bildirir.", skills: ["en.vocab.topic"] },
          ],
        },
        {
          id: "en3-routine-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en3-routine-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 6. Peşələr və şəhər ═══════════════
    {
      id: "en3-jobs",
      title: "Peşələr və şəhər (Jobs & Places)",
      description: "Peşələr və şəhərdəki yerlərin adları.",
      lessons: [
        {
          id: "en3-jobs-vocab",
          title: "Jobs & places",
          intro: "Peşələri və yerləri öyrənək.",
          sections: [
            { heading: "Peşələr", body: "teacher — müəllim, doctor — həkim, driver — sürücü, cook — aşpaz, farmer — fermer, nurse — tibb bacısı, police officer — polis, pilot — pilot." },
            { heading: "Yerlər", body: "school — məktəb, hospital — xəstəxana, shop — mağaza, park — park, zoo — heyvanxana, library — kitabxana." },
          ],
          tasks: [
            { id: "en3-jobs-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'müəllim' İngiliscə necədir?", options: ["teacher", "doctor", "driver", "cook"], correctIndex: 0, xp: 10, explanation: "«Müəllim» ingiliscə teacher olur — teach (öyrətmək) sözündən yaranıb.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'həkim' İngiliscə necədir?", options: ["doctor", "teacher", "nurse", "farmer"], correctIndex: 0, xp: 10, explanation: "«Həkim» ingiliscə doctor olur.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'sürücü' İngiliscə necədir?", options: ["driver", "pilot", "cook", "farmer"], correctIndex: 0, xp: 10, explanation: "«Sürücü» ingiliscə driver olur — drive (sürmək) sözündən yaranıb.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'aşpaz' İngiliscə necədir?", options: ["cook", "driver", "doctor", "nurse"], correctIndex: 0, xp: 10, explanation: "«Aşpaz» ingiliscə cook olur — bu söz həm də «bişirmək» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'fermer' İngiliscə necədir?", options: ["farmer", "cook", "pilot", "teacher"], correctIndex: 0, xp: 10, explanation: "«Fermer» ingiliscə farmer olur — farm (təsərrüfat) sözündən yaranıb.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'pilot' İngiliscə necədir?", options: ["pilot", "driver", "police officer", "cook"], correctIndex: 0, xp: 10, explanation: "«Pilot» sözü ingiliscə də eyni cür yazılır: pilot.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-vocab-t7", type: "multiple_choice", prompt: "'doctor' nə deməkdir?", options: ["həkim", "müəllim", "sürücü", "aşpaz"], correctIndex: 0, xp: 10, explanation: "Doctor azərbaycanca «həkim» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-vocab-t8", type: "multiple_choice", prompt: "'teacher' nə deməkdir?", options: ["müəllim", "həkim", "polis", "pilot"], correctIndex: 0, xp: 10, explanation: "Teacher azərbaycanca «müəllim» deməkdir.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-vocab-t9", type: "multiple_choice", speakOptions: true, prompt: "'məktəb' İngiliscə necədir?", options: ["school", "hospital", "shop", "park"], correctIndex: 0, xp: 10, explanation: "«Məktəb» ingiliscə school olur.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-vocab-t10", type: "multiple_choice", speakOptions: true, prompt: "'xəstəxana' İngiliscə necədir?", options: ["hospital", "school", "shop", "zoo"], correctIndex: 0, xp: 10, explanation: "«Xəstəxana» ingiliscə hospital olur.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-vocab-t11", type: "multiple_choice", speakOptions: true, prompt: "'mağaza' İngiliscə necədir?", options: ["shop", "park", "school", "library"], correctIndex: 0, xp: 10, explanation: "«Mağaza» ingiliscə shop olur.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-vocab-t12", type: "multiple_choice", speakOptions: true, prompt: "'kitabxana' İngiliscə necədir?", options: ["library", "shop", "zoo", "park"], correctIndex: 0, xp: 10, explanation: "«Kitabxana» ingiliscə library olur.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "'heyvanxana' İngiliscə necədir?", options: ["zoo", "park", "shop", "hospital"], correctIndex: 0, xp: 10, explanation: "«Heyvanxana» ingiliscə zoo olur.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'A ___ works in a hospital.' (həkim)", options: ["doctor", "teacher", "farmer", "cook"], correctIndex: 0, xp: 10, explanation: "Hospital = xəstəxana; orada xəstələri müalicə edən doctor işləyir.", skills: ["en.gram.prepositions"] },
            { id: "en3-jobs-vocab-t15", type: "multiple_choice", speakOptions: true, prompt: "'A ___ teaches children.' (müəllim)", options: ["teacher", "doctor", "driver", "pilot"], correctIndex: 0, xp: 15, explanation: "Teach = öyrətmək, children = uşaqlar. Uşaqlara dərs deyən teacher-dir.", skills: ["en.vocab.topic"] },
          ],
          bonusTasks: [
            { id: "en3-jobs-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'A ___ flies a plane.' (pilot)", options: ["pilot", "driver", "cook", "farmer"], correctIndex: 0, xp: 15, explanation: "Fly = uçurmaq, plane = təyyarə. Təyyarəni uçuran pilot-dur.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'nurse' nə deməkdir?", options: ["tibb bacısı", "həkim", "müəllim", "aşpaz"], correctIndex: 0, xp: 15, explanation: "Nurse azərbaycanca «tibb bacısı» deməkdir — həkimə kömək edir.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'A ___ cooks food.' (aşpaz)", options: ["cook", "farmer", "driver", "pilot"], correctIndex: 0, xp: 15, explanation: "Cook food = yemək bişirmək; bunu edən də cook adlanır.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'We borrow books from the ___.'", options: ["library", "shop", "zoo", "park"], correctIndex: 0, xp: 15, explanation: "Borrow books = kitab götürmək. Kitabları müvəqqəti verən yer library-dir.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'police officer' nə deməkdir?", options: ["polis", "əsgər", "sürücü", "pilot"], correctIndex: 0, xp: 15, explanation: "Police officer azərbaycanca «polis» deməkdir.", skills: ["en.vocab.topic"] },
          ],
        },
        {
          id: "en3-jobs-city",
          title: "Places in the city",
          intro: "Şəhərdəki yerlərin adları.",
          sections: [
            { heading: "Yerlər", body: "school — məktəb, hospital — xəstəxana, shop — mağaza, park — park, library — kitabxana, bank — bank." },
            { heading: "Kim harada işləyir?", body: "A teacher works at a school. A doctor works at a hospital." },
          ],
          tasks: [
            { id: "en3-jobs-city-t1", type: "multiple_choice", speakOptions: true, prompt: "'xəstəxana' İngiliscə necədir?", options: ["hospital", "school", "shop", "park"], correctIndex: 0, xp: 10, explanation: "«Xəstəxana» ingiliscə hospital olur.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-city-t2", type: "multiple_choice", speakOptions: true, prompt: "'kitabxana' İngiliscə necədir?", options: ["library", "bookshop", "school", "office"], correctIndex: 0, xp: 10, explanation: "«Kitabxana» ingiliscə library olur. Bookshop isə kitab satılan mağazadır.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-city-t3", type: "multiple_choice", speakOptions: true, prompt: "'mağaza' İngiliscə necədir?", options: ["shop", "school", "stop", "ship"], correctIndex: 0, xp: 10, explanation: "«Mağaza» ingiliscə shop olur. Ship = gəmi, stop = dayanacaq.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-city-t4", type: "multiple_choice", prompt: "'A doctor works at a ______.' — düzgün söz hansıdır?", options: ["hospital", "school", "shop", "bank"], correctIndex: 0, xp: 10, explanation: "Həkim xəstələri müalicə edir, bu isə xəstəxanada — hospital-da olur.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-city-t5", type: "multiple_choice", prompt: "'A teacher works at a ______.' — düzgün söz hansıdır?", options: ["school", "hospital", "bank", "park"], correctIndex: 0, xp: 10, explanation: "Müəllim uşaqlara dərs deyir, bu isə məktəbdə — school-da olur.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-city-t6", type: "multiple_choice", speakOptions: true, prompt: "'park' İngiliscə necədir?", options: ["park", "pork", "part", "path"], correctIndex: 0, xp: 10, explanation: "«Park» sözü ingiliscə də eyni cür yazılır: park. Part = hissə, pork = donuz əti.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-city-t7", type: "multiple_choice", prompt: "'Where do you buy bread?' — cavab hansıdır?", options: ["At a shop.", "At a school.", "At a hospital.", "At a park."], correctIndex: 0, xp: 10, explanation: "Buy bread = çörək almaq. Çörək mağazadan alınır: at a shop.", skills: ["en.gram.questions"] },
            { id: "en3-jobs-city-t8", type: "multiple_choice", speakOptions: true, prompt: "'küçə' İngiliscə necədir?", options: ["street", "school", "strong", "spring"], correctIndex: 0, xp: 10, explanation: "«Küçə» ingiliscə street olur. School = məktəb, strong = güclü.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-city-t9", type: "multiple_choice", prompt: "'bank' sözü nə deməkdir?", options: ["bank", "sahil", "skamya", "kitab"], correctIndex: 0, xp: 10, explanation: "Bank ingiliscə də pul saxlanılan idarəni bildirir — azərbaycanca «bank».", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-city-t10", type: "multiple_choice", speakOptions: true, prompt: "'muzey' İngiliscə necədir?", options: ["museum", "music", "mission", "market"], correctIndex: 0, xp: 10, explanation: "«Muzey» ingiliscə museum olur. Music = musiqi, market = bazar.", skills: ["en.vocab.topic"] },
          ],
          bonusTasks: [
            { id: "en3-jobs-city-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "She works at a hospital.", options: ["O, xəstəxanada işləyir.", "O, məktəbdə işləyir.", "O, xəstədir.", "O, xəstəxanaya gedir."], correctIndex: 0, xp: 15, explanation: "Səsdə «She works at a hospital» deyildi. Work = işləmək, hospital = xəstəxana.", skills: ["en.vocab.topic","en.listen"] },
            { id: "en3-jobs-city-b2", type: "multiple_choice", prompt: "'A firefighter works at a fire station.' nə deməkdir?", options: ["Yanğınsöndürən yanğın stansiyasında işləyir.", "Həkim xəstəxanada işləyir.", "Müəllim məktəbdə işləyir.", "Polis idarədə işləyir."], correctIndex: 0, xp: 15, explanation: "Firefighter = yanğınsöndürən, fire station = yanğın stansiyası, works at = işləyir.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-city-b3", type: "multiple_choice", speakOptions: true, prompt: "'aptek' İngiliscə necədir?", options: ["pharmacy", "factory", "gallery", "bakery"], correctIndex: 0, xp: 15, explanation: "«Aptek» ingiliscə pharmacy olur. Bakery = çörəkxana, factory = fabrik.", skills: ["en.vocab.topic"] },
            { id: "en3-jobs-city-b4", type: "multiple_choice", prompt: "'What does your father do?' nə soruşur?", options: ["Peşəsini", "Adını", "Yaşını", "Ünvanını"], correctIndex: 0, xp: 15, explanation: "«What does ... do?» sualı adamın nə iş gördüyünü, yəni peşəsini soruşur.", skills: ["en.gram.questions"] },
          ],
        },
        {
          id: "en3-jobs-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en3-jobs-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
  ],
};
