// İngilis dili — 4-cü sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Present Continuous  2) Past Simple (was/were)  3) Past Simple (-ed)
// 4) There is / there are  5) Comparatives  6) Sual sözləri və lüğət.
// 4-cü sinif üçün: qısa qrammatika + şəkil-söz + dinləmə. id prefiksi en4-*.

import type { Subject } from "../types";

export const english4: Subject = {
  slug: "ingilis-dili-4",
  name: "İngilis dili",
  grade: 4,
  icon: "E",
  color: "violet",
  units: [
    // ═══════════════ 1. Present Continuous ═══════════════
    {
      id: "en4-continuous",
      title: "Present Continuous (indi baş verən)",
      description: "İndi baş verən iş: am/is/are + V-ing.",
      lessons: [
        {
          id: "en4-continuous-rule",
          title: "Qayda: Present Continuous",
          intro: "İndi baş verən iş: I am playing. She is reading.",
          sections: [
            { heading: "Necə düzəlir?", body: "am/is/are + feil-ing. I am playing. You/we/they are playing. He/she/it is playing." },
            { heading: "İndi", body: "Bu, indi (danışıq anında) baş verən işdir: 'Look! The baby is sleeping.'" },
          ],
          tasks: [
            { id: "en4-continuous-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'I ___ playing.' (indi)", options: ["am", "is", "are", "be"], correctIndex: 0, xp: 10, explanation: "«I» ilə həmişə am işlənir: I am playing." },
            { id: "en4-continuous-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'She ___ reading.'", options: ["is", "am", "are", "be"], correctIndex: 0, xp: 10, explanation: "«She» üçüncü şəxs təkdir, ona görə is işlənir." },
            { id: "en4-continuous-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'They ___ running.'", options: ["are", "is", "am", "be"], correctIndex: 0, xp: 10, explanation: "«They» cəmdir, ona görə are işlənir." },
            { id: "en4-continuous-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "Present Continuous necə düzəlir?", options: ["am/is/are + V-ing", "V + s", "was + V", "will + V"], correctIndex: 0, xp: 10, explanation: "Present Continuous iki hissədən qurulur: am/is/are köməkçi feili + əsas feilin -ing forması." },
            { id: "en4-continuous-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "'He is ___.' (play)", options: ["playing", "plays", "played", "play"], correctIndex: 0, xp: 10, explanation: "Is-dən sonra feil -ing formasında gəlir: is playing." },
            { id: "en4-continuous-rule-t6", type: "multiple_choice", speakOptions: true, prompt: "'We ___ eating.'", options: ["are", "is", "am", "be"], correctIndex: 0, xp: 10, explanation: "«We» cəmdir, ona görə are işlənir." },
            { id: "en4-continuous-rule-t7", type: "multiple_choice", prompt: "'I am reading.' nə deməkdir?", options: ["Oxuyuram (indi).", "Oxudum.", "Oxuyacağam.", "Oxumağı sevirəm."], correctIndex: 0, xp: 10, explanation: "Am + reading indi davam edən işi bildirir — «indi oxuyuram», ümumiyyətlə sevmək yox." },
            { id: "en4-continuous-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'You ___ writing.'", options: ["are", "is", "am", "be"], correctIndex: 0, xp: 10, explanation: "«You» ilə həmişə are işlənir, tək və ya cəm olmasından asılı olmayaraq." },
            { id: "en4-continuous-rule-t9", type: "fill_blank", prompt: "'run' feilinə -ing əlavə et (samit ikiqat).", accepted: ["running"], xp: 10, explanation: "Qısa saitdən sonra tək samitlə bitən feildə son samit ikiqat yazılır: run → running." },
            { id: "en4-continuous-rule-t10", type: "fill_blank", prompt: "'read' feilinə -ing əlavə et.", accepted: ["reading"], xp: 10, explanation: "Read sözü iki saitlə bitir, samit ikiqatlanmır: read → reading." },
            { id: "en4-continuous-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "'The cat ___ sleeping.'", options: ["is", "am", "are", "be"], correctIndex: 0, xp: 10, explanation: "«The cat» it kimidir, yəni üçüncü şəxs təkdir: is." },
            { id: "en4-continuous-rule-t12", type: "multiple_choice", speakOptions: true, prompt: "'Look! It ___ raining.'", options: ["is", "am", "are", "be"], correctIndex: 0, xp: 10, explanation: "«It» üçüncü şəxs təkdir, ona görə is işlənir. «Look!» sözü işin elə indi olduğunu göstərir." },
            { id: "en4-continuous-rule-t13", type: "multiple_choice", prompt: "'She is cooking.' nə deməkdir?", options: ["O bişirir (indi).", "O bişirdi.", "O bişirəcək.", "O bişirməyi sevir."], correctIndex: 0, xp: 10, explanation: "Is + cooking indi davam edən işi bildirir — «indi bişirir»." },
            { id: "en4-continuous-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "'I am ___.' (write)", options: ["writing", "writes", "wrote", "write"], correctIndex: 0, xp: 10, explanation: "Am-dan sonra feil -ing formasında gəlir. Write sözünün sonundakı -e düşür: writing." },
            { id: "en4-continuous-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'The children ___ playing.'", options: ["are", "is", "am", "be"], correctIndex: 0, xp: 15, explanation: "«The children» cəmdir, ona görə are işlənir." },
          ],
          bonusTasks: [
            { id: "en4-continuous-rule-b1", type: "fill_blank", prompt: "'swim' feilinə -ing əlavə et (samit ikiqat).", accepted: ["swimming"], xp: 15, explanation: "Qısa saitdən sonra tək samitlə bitən feildə son samit ikiqat yazılır: swim → swimming." },
            { id: "en4-continuous-rule-b2", type: "fill_blank", prompt: "'make' feilinə -ing əlavə et (e düşür).", accepted: ["making"], xp: 15, explanation: "Sonu səssiz -e ilə bitən feildə -e düşür: make → making." },
            { id: "en4-continuous-rule-b3", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'I ___ playing.' (deyiləm)", options: ["am not", "isn't", "aren't", "not"], correctIndex: 0, xp: 15, explanation: "İnkar üçün köməkçi feilin yanına not qoyulur: am not playing." },
            { id: "en4-continuous-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "Sual: 'What ___ you doing?'", options: ["are", "is", "am", "do"], correctIndex: 0, xp: 15, explanation: "«You» ilə are işlənir, sualda isə əvvələ keçir: What are you doing?" },
            { id: "en4-continuous-rule-b5", type: "multiple_choice", prompt: "'They are watching TV.' nə deməkdir?", options: ["Onlar televizora baxır (indi).", "Baxdılar.", "Baxacaqlar.", "Televizoru sevirlər."], correctIndex: 0, xp: 15, explanation: "Are + watching indi davam edən işi bildirir." },
          ],
        },
        {
          id: "en4-continuous-listen",
          title: "Dinləmə: Present Continuous",
          intro: "Cümləni dinlə və mənasını seç.",
          sections: [
            { heading: "Necə işləyir?", body: "Səs düyməsinə bas, cümləni dinlə, düzgün mənasını seç." },
          ],
          tasks: [
            { id: "en4-continuous-listen-t1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I am playing football.", options: ["Futbol oynayıram (indi).", "Futbol oynadım.", "Futbolu sevirəm.", "Futbol oynayacağam."], correctIndex: 0, xp: 10, explanation: "Səsdə «I am playing football» deyildi. Am + -ing işin elə indi getdiyini bildirir." },
            { id: "en4-continuous-listen-t2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "She is reading a book.", options: ["O kitab oxuyur (indi).", "O kitab oxudu.", "O kitab aldı.", "O kitabı sevir."], correctIndex: 0, xp: 10, explanation: "Səsdə «She is reading a book» deyildi. Is + -ing işin indi getdiyini bildirir." },
            { id: "en4-continuous-listen-t3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The baby is sleeping.", options: ["Körpə yatır.", "Körpə yatdı.", "Körpə oyaqdır.", "Körpə ağlayır."], correctIndex: 0, xp: 10, explanation: "Səsdə «The baby is sleeping» deyildi. Sleeping = yatır." },
            { id: "en4-continuous-listen-t4", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "They are running.", options: ["Onlar qaçır.", "Onlar qaçdı.", "Onlar oturur.", "Onlar dayanır."], correctIndex: 0, xp: 10, explanation: "Səsdə «They are running» deyildi. Are + -ing indi davam edən işi bildirir." },
            { id: "en4-continuous-listen-t5", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "It is raining.", options: ["Yağış yağır.", "Yağış yağdı.", "Hava aydındır.", "Qar yağır."], correctIndex: 0, xp: 10, explanation: "Səsdə «It is raining» deyildi. Rain = yağış, -ing isə işin indi getdiyini bildirir." },
            { id: "en4-continuous-listen-t6", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "We are eating lunch.", options: ["Nahar edirik (indi).", "Nahar etdik.", "Nahar edəcəyik.", "Ac deyilik."], correctIndex: 0, xp: 10, explanation: "Səsdə «We are eating lunch» deyildi. Lunch = nahar, are + -ing isə indini bildirir." },
            { id: "en4-continuous-listen-t7", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "He is writing a letter.", options: ["O məktub yazır (indi).", "O məktub yazdı.", "O məktub oxudu.", "O məktub aldı."], correctIndex: 0, xp: 10, explanation: "Səsdə «He is writing a letter» deyildi. Write = yazmaq, letter = məktub." },
            { id: "en4-continuous-listen-t8", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The dog is barking.", options: ["İt hürür.", "İt hürdü.", "İt yatır.", "İt qaçır."], correctIndex: 0, xp: 10, explanation: "Səsdə «The dog is barking» deyildi. Bark = hürmək." },
            { id: "en4-continuous-listen-t9", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I am doing my homework.", options: ["Ev tapşırığımı edirəm (indi).", "Ev tapşırığımı etdim.", "Ev tapşırığım var.", "Ev tapşırığı yoxdur."], correctIndex: 0, xp: 10, explanation: "Səsdə «I am doing my homework» deyildi. Am + -ing işin elə indi getdiyini bildirir." },
            { id: "en4-continuous-listen-t10", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "She is singing a song.", options: ["O mahnı oxuyur (indi).", "O mahnı oxudu.", "O rəqs edir.", "O dinləyir."], correctIndex: 0, xp: 10, explanation: "Səsdə «She is singing a song» deyildi. Sing = mahnı oxumaq." },
            { id: "en4-continuous-listen-t11", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The children are playing.", options: ["Uşaqlar oynayır (indi).", "Uşaqlar oynadı.", "Uşaqlar yatır.", "Uşaqlar oxuyur."], correctIndex: 0, xp: 10, explanation: "Səsdə «The children are playing» deyildi. Are + -ing indini bildirir." },
            { id: "en4-continuous-listen-t12", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "My mother is cooking.", options: ["Anam bişirir (indi).", "Anam bişirdi.", "Anam gəldi.", "Anam işləyir."], correctIndex: 0, xp: 10, explanation: "Səsdə «My mother is cooking» deyildi. Cook = bişirmək." },
            { id: "en4-continuous-listen-t13", type: "listening", prompt: "Dinlə və sualın mənasını seç.", audioText: "What are you doing?", options: ["Nə edirsən (indi)?", "Nə etdin?", "Nə edəcəksən?", "Necəsən?"], correctIndex: 0, xp: 10, explanation: "Səsdə «What are you doing?» deyildi. Are + -ing sualı indi nə etdiyini soruşur." },
            { id: "en4-continuous-listen-t14", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The birds are flying.", options: ["Quşlar uçur.", "Quşlar uçdu.", "Quşlar oxuyur.", "Quşlar yuvadadır."], correctIndex: 0, xp: 10, explanation: "Səsdə «The birds are flying» deyildi. Fly = uçmaq." },
            { id: "en4-continuous-listen-t15", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I am not sleeping.", options: ["Yatmıram.", "Yatıram.", "Yatdım.", "Yorğunam."], correctIndex: 0, xp: 15, explanation: "Səsdə «I am not sleeping» deyildi. Not inkar bildirir — deməli «Yatmıram»." },
          ],
          bonusTasks: [
            { id: "en4-continuous-listen-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The sun is shining.", options: ["Günəş parlayır.", "Günəş batdı.", "Hava soyuqdur.", "Yağış yağır."], correctIndex: 0, xp: 15, explanation: "Səsdə «The sun is shining» deyildi. Sun = günəş, shine = parlamaq." },
            { id: "en4-continuous-listen-b2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "We are watching a film.", options: ["Film baxırıq (indi).", "Film baxdıq.", "Film baxacağıq.", "Filmi sevirik."], correctIndex: 0, xp: 15, explanation: "Səsdə «We are watching a film» deyildi. Are + -ing işin indi getdiyini bildirir." },
            { id: "en4-continuous-listen-b3", type: "listening", prompt: "Dinlə və sualın mənasını seç.", audioText: "Where are you going?", options: ["Hara gedirsən (indi)?", "Hara getdin?", "Hara gedəcəksən?", "Haradasan?"], correctIndex: 0, xp: 15, explanation: "Səsdə «Where are you going?» deyildi. Where = hara, are + -ing isə indini bildirir." },
          ],
        },
        {
          id: "en4-continuous-q",
          title: "Present Continuous — sual və inkar",
          intro: "İndi baş verən işi soruşmaq və inkar etmək.",
          sections: [
            { heading: "Sual", body: "'What are you doing?' — Nə edirsən? 'Is she reading?' — O oxuyur?" },
            { heading: "İnkar", body: "'I am not sleeping.' — Yatmıram. 'They aren't playing.' — Onlar oynamırlar." },
          ],
          tasks: [
            { id: "en4-continuous-q-t1", type: "multiple_choice", prompt: "'What are you doing?' nə deməkdir?", options: ["Nə edirsən?", "Nə etdin?", "Nə edəcəksən?", "Harada?"], correctIndex: 0, xp: 10, explanation: "What = nə, are you doing = edirsən (indi)." },
            { id: "en4-continuous-q-t2", type: "multiple_choice", prompt: "'I am not sleeping.' nə deməkdir?", options: ["Yatmıram.", "Yatıram.", "Yatdım.", "Yatacağam."], correctIndex: 0, xp: 10, explanation: "Am not inkar bildirir, sleeping = yatmaq." },
            { id: "en4-continuous-q-t3", type: "multiple_choice", prompt: "'Is she reading?' sualına müsbət cavab hansıdır?", options: ["Yes, she is.", "Yes, she does.", "Yes, she has.", "Yes, she can."], correctIndex: 0, xp: 10, explanation: "Sual is ilə qurulub, ona görə cavab da is ilə verilir: «Yes, she is»." },
            { id: "en4-continuous-q-t4", type: "multiple_choice", prompt: "'They ______ playing.' — inkar forma hansıdır?", options: ["aren't", "isn't", "don't", "not"], correctIndex: 0, xp: 10, explanation: "«They» cəmdir, ona görə are işlənir; inkarı aren't olur (are + not)." },
            { id: "en4-continuous-q-t5", type: "multiple_choice", prompt: "'He is running.' nə deməkdir?", options: ["O qaçır (indi).", "O qaçdı.", "O qaçacaq.", "O qaça bilir."], correctIndex: 0, xp: 10, explanation: "Is + running indi davam edən işi bildirir — bacarıq və ya keçmiş yox." },
            { id: "en4-continuous-q-t6", type: "multiple_choice", prompt: "Present Continuous nə bildirir?", options: ["İndi baş verən işi", "Hər gün olan işi", "Keçmiş işi", "Gələcək planı"], correctIndex: 0, xp: 10, explanation: "Present Continuous danışıq anında davam edən işi bildirir: «Look! It is raining»." },
            { id: "en4-continuous-q-t7", type: "multiple_choice", prompt: "'We ______ watching TV.' — düzgün forma hansıdır?", options: ["are", "is", "am", "be"], correctIndex: 0, xp: 10, explanation: "«We» cəmdir, ona görə are işlənir." },
            { id: "en4-continuous-q-t8", type: "multiple_choice", prompt: "'-ing' şəkilçisi nəyə əlavə olunur?", options: ["Feilə", "İsmə", "Sifətə", "Sayı"], correctIndex: 0, xp: 10, explanation: "-ing əsas feilə qoşulur və işin davam etdiyini bildirir: play → playing." },
            { id: "en4-continuous-q-t9", type: "multiple_choice", speakOptions: true, prompt: "'yazır (indi)' İngiliscə necədir?", options: ["is writing", "writes", "wrote", "will write"], correctIndex: 0, xp: 10, explanation: "İndi davam edən iş üçün is + -ing işlənir: is writing. Writes hər dəfə olan işi bildirir." },
            { id: "en4-continuous-q-t10", type: "multiple_choice", prompt: "'Are they eating?' nə deməkdir?", options: ["Onlar yeyirlər?", "Onlar yedilər?", "Onlar yeyəcəklər?", "Onlar acdırlar?"], correctIndex: 0, xp: 10, explanation: "Sualda are əvvələ keçib, eating = yeyirlər (indi)." },
          ],
          bonusTasks: [
            { id: "en4-continuous-q-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "She is cooking.", options: ["O, yemək bişirir.", "O, yemək yeyir.", "O, bişirdi.", "O, bişirəcək."], correctIndex: 0, xp: 15, explanation: "Səsdə «She is cooking» deyildi. Cook = yemək bişirmək." },
            { id: "en4-continuous-q-b2", type: "multiple_choice", prompt: "'I play' və 'I am playing' arasındakı fərq nədir?", options: ["Biri həmişə, digəri indi", "Fərq yoxdur", "Biri keçmişdir", "Biri gələcəkdir"], correctIndex: 0, xp: 15, explanation: "«I play» adət və ya təkrarlanan işi bildirir, «I am playing» isə elə indi baş verəni." },
            { id: "en4-continuous-q-b3", type: "multiple_choice", prompt: "'run' feilinin -ing forması hansıdır?", options: ["running", "runing", "runnning", "runs"], correctIndex: 0, xp: 15, explanation: "Qısa saitdən sonra tək samitlə bitdiyi üçün son samit ikiqat yazılır: running." },
            { id: "en4-continuous-q-b4", type: "multiple_choice", prompt: "'write' feilinin -ing forması hansıdır?", options: ["writing", "writeing", "writting", "writes"], correctIndex: 0, xp: 15, explanation: "Sonu səssiz -e ilə bitdiyi üçün -e düşür: write → writing." },
          ],
        },
        {
          id: "en4-continuous-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en4-continuous-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 2. Past Simple (was/were) ═══════════════
    {
      id: "en4-was",
      title: "Past Simple: was / were",
      description: "Keçmişdə vəziyyət: was (tək), were (cəm).",
      lessons: [
        {
          id: "en4-was-rule",
          title: "Qayda: was / were",
          intro: "'am/is' → was, 'are' → were. I was happy. They were here.",
          sections: [
            { heading: "was / were", body: "I/he/she/it → was. you/we/they → were. 'I was at home.' — Evdə idim. 'They were happy.' — Onlar xoşbəxt idi." },
            { heading: "İnkar", body: "wasn't / weren't: I wasn't tired. They weren't there." },
          ],
          tasks: [
            { id: "en4-was-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'I ___ at home.' (idim)", options: ["was", "were", "am", "is"], correctIndex: 0, xp: 10, explanation: "«I» ilə was işlənir. Were isə you, we, they üçündür." },
            { id: "en4-was-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'They ___ happy.' (idilər)", options: ["were", "was", "are", "is"], correctIndex: 0, xp: 10, explanation: "«They» cəmdir, ona görə were işlənir." },
            { id: "en4-was-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'She ___ tired.' (idi)", options: ["was", "were", "is", "are"], correctIndex: 0, xp: 10, explanation: "«She» üçüncü şəxs təkdir, ona görə was işlənir." },
            { id: "en4-was-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "'We ___ at school.' (idik)", options: ["were", "was", "are", "is"], correctIndex: 0, xp: 10, explanation: "«We» cəmdir, ona görə were işlənir." },
            { id: "en4-was-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "'am/is' keçmişdə nəyə çevrilir?", options: ["was", "were", "will", "be"], correctIndex: 0, xp: 10, explanation: "Am və is keçmiş zamanda was olur: I am → I was." },
            { id: "en4-was-rule-t6", type: "multiple_choice", speakOptions: true, prompt: "'are' keçmişdə nəyə çevrilir?", options: ["were", "was", "will", "be"], correctIndex: 0, xp: 10, explanation: "Are keçmiş zamanda were olur: they are → they were." },
            { id: "en4-was-rule-t7", type: "multiple_choice", prompt: "'I was happy.' nə deməkdir?", options: ["Xoşbəxt idim.", "Xoşbəxtəm.", "Xoşbəxt olacağam.", "Xoşbəxt deyiləm."], correctIndex: 0, xp: 10, explanation: "Was keçmiş zamanı bildirir — «idim», indi deyil." },
            { id: "en4-was-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'He ___ a good boy.'", options: ["was", "were", "are", "am"], correctIndex: 0, xp: 10, explanation: "«He» üçüncü şəxs təkdir, ona görə was işlənir." },
            { id: "en4-was-rule-t9", type: "multiple_choice", speakOptions: true, prompt: "'You ___ late.' (gecikmişdin)", options: ["were", "was", "are", "is"], correctIndex: 0, xp: 10, explanation: "«You» ilə həmişə were işlənir, tək olsa belə." },
            { id: "en4-was-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'I ___ tired.' (yorğun deyildim)", options: ["wasn't", "weren't", "am not", "isn't"], correctIndex: 0, xp: 10, explanation: "«I» ilə was işlənir, inkarı wasn't olur (was + not)." },
            { id: "en4-was-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'They ___ here.' (yox idilər)", options: ["weren't", "wasn't", "aren't", "isn't"], correctIndex: 0, xp: 10, explanation: "«They» ilə were işlənir, inkarı weren't olur (were + not)." },
            { id: "en4-was-rule-t12", type: "multiple_choice", prompt: "'They were at the park.' nə deməkdir?", options: ["Parkda idilər.", "Parkdadırlar.", "Parka gedəcəklər.", "Parkı sevirlər."], correctIndex: 0, xp: 10, explanation: "Were keçmiş zamanı bildirir — «idilər», indi deyil." },
            { id: "en4-was-rule-t13", type: "multiple_choice", speakOptions: true, prompt: "'It ___ cold yesterday.'", options: ["was", "were", "is", "are"], correctIndex: 0, xp: 10, explanation: "«It» üçüncü şəxs təkdir, ona görə was işlənir. Yesterday = dünən." },
            { id: "en4-was-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "'The books ___ on the table.'", options: ["were", "was", "are", "is"], correctIndex: 0, xp: 10, explanation: "«The books» cəmdir, ona görə were işlənir." },
            { id: "en4-was-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'My friends ___ at the party.'", options: ["were", "was", "are", "am"], correctIndex: 0, xp: 15, explanation: "«My friends» cəmdir, ona görə were işlənir." },
          ],
          bonusTasks: [
            { id: "en4-was-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "Sual: '___ you at home?'", options: ["Were", "Was", "Are", "Do"], correctIndex: 0, xp: 15, explanation: "«You» ilə were işlənir, sualda isə əvvələ keçir: Were you...?" },
            { id: "en4-was-rule-b2", type: "multiple_choice", speakOptions: true, prompt: "Sual: '___ she happy?'", options: ["Was", "Were", "Is", "Did"], correctIndex: 0, xp: 15, explanation: "«She» üçüncü şəxs təkdir, ona görə sualda was əvvələ keçir: Was she...?" },
            { id: "en4-was-rule-b3", type: "multiple_choice", prompt: "'It wasn't easy.' nə deməkdir?", options: ["Asan deyildi.", "Asandır.", "Asan olacaq.", "Çətindir."], correctIndex: 0, xp: 15, explanation: "Wasn't = was not, yəni keçmişdə inkar. Deməli «Asan deyildi»." },
            { id: "en4-was-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "'There ___ many people.' (çoxlu adam var idi)", options: ["were", "was", "are", "is"], correctIndex: 0, xp: 15, explanation: "«Many people» cəmdir, ona görə were işlənir: there were." },
            { id: "en4-was-rule-b5", type: "multiple_choice", speakOptions: true, prompt: "'There ___ a cat in the garden.' (bir pişik var idi)", options: ["was", "were", "is", "are"], correctIndex: 0, xp: 15, explanation: "«A cat» təkdir, ona görə was işlənir: there was." },
          ],
        },
        {
          id: "en4-was-q",
          title: "Was / were — sual və inkar",
          intro: "Keçmişdə harada və necə idin?",
          sections: [
            { heading: "Sual", body: "'Where were you yesterday?' — Dünən harada idin? 'Was he at home?' — O evdə idi?" },
            { heading: "İnkar", body: "'I wasn't tired.' — Yorğun deyildim. 'They weren't here.' — Onlar burada deyildilər." },
          ],
          tasks: [
            { id: "en4-was-q-t1", type: "multiple_choice", prompt: "'Where were you yesterday?' nə deməkdir?", options: ["Dünən harada idin?", "Dünən nə etdin?", "Sabah haradasan?", "İndi haradasan?"], correctIndex: 0, xp: 10, explanation: "Where = harada, were you = idin, yesterday = dünən." },
            { id: "en4-was-q-t2", type: "multiple_choice", prompt: "'I wasn't tired.' nə deməkdir?", options: ["Yorğun deyildim.", "Yorğunam.", "Yorğun olacağam.", "Yoruldum."], correctIndex: 0, xp: 10, explanation: "Wasn't = was not, yəni keçmişdə inkar. Deməli «Yorğun deyildim»." },
            { id: "en4-was-q-t3", type: "multiple_choice", prompt: "'Was he at home?' sualına müsbət cavab hansıdır?", options: ["Yes, he was.", "Yes, he is.", "Yes, he did.", "Yes, he were."], correctIndex: 0, xp: 10, explanation: "Sual was ilə qurulub, ona görə cavab da was ilə verilir: «Yes, he was»." },
            { id: "en4-was-q-t4", type: "multiple_choice", prompt: "'They ______ here.' — inkar forma hansıdır?", options: ["weren't", "wasn't", "aren't", "don't"], correctIndex: 0, xp: 10, explanation: "«They» cəmdir, ona görə were işlənir; inkarı weren't olur." },
            { id: "en4-was-q-t5", type: "multiple_choice", prompt: "'I' ilə hansı forma işlənir?", options: ["was", "were", "are", "is"], correctIndex: 0, xp: 10, explanation: "«I» tək olduğu üçün was işlənir — bu, qaydadan istisnadır, çünki you ilə were gəlir." },
            { id: "en4-was-q-t6", type: "multiple_choice", prompt: "'They' ilə hansı forma işlənir?", options: ["were", "was", "is", "am"], correctIndex: 0, xp: 10, explanation: "«They» cəmdir, ona görə were işlənir." },
            { id: "en4-was-q-t7", type: "multiple_choice", prompt: "'She was happy.' nə deməkdir?", options: ["O şad idi.", "O şaddır.", "O şad olacaq.", "O şad deyil."], correctIndex: 0, xp: 10, explanation: "Was keçmiş zamanı bildirir — «idi», indi deyil." },
            { id: "en4-was-q-t8", type: "multiple_choice", prompt: "'wasn't' hansı sözlərin qısaldılmasıdır?", options: ["was not", "were not", "is not", "will not"], correctIndex: 0, xp: 10, explanation: "Wasn't sözü was not birləşməsinin qısa formasıdır." },
            { id: "en4-was-q-t9", type: "multiple_choice", speakOptions: true, prompt: "'idi (o)' İngiliscə necədir?", options: ["was", "were", "is", "are"], correctIndex: 0, xp: 10, explanation: "Üçüncü şəxs tək üçün keçmişdə was işlənir." },
            { id: "en4-was-q-t10", type: "multiple_choice", prompt: "'Were you at school?' nə deməkdir?", options: ["Məktəbdə idin?", "Məktəbdəsən?", "Məktəbə gedəcəksən?", "Məktəbi sevirsən?"], correctIndex: 0, xp: 10, explanation: "Were you = idin, at school = məktəbdə. Sual keçmişə aiddir." },
          ],
          bonusTasks: [
            { id: "en4-was-q-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I was at home.", options: ["Evdə idim.", "Evdəyəm.", "Evə gedirəm.", "Evə getdim."], correctIndex: 0, xp: 15, explanation: "Səsdə «I was at home» deyildi. Was keçmiş zamanı bildirir — «idim»." },
            { id: "en4-was-q-b2", type: "multiple_choice", prompt: "'was' və 'were' arasındakı fərq nədir?", options: ["Şəxsə görə seçilir", "Zamana görə", "Mənaya görə", "Fərq yoxdur"], correctIndex: 0, xp: 15, explanation: "Hər ikisi keçmişi bildirir, sadəcə şəxsə görə seçilir: I/he/she/it → was; you/we/they → were." },
            { id: "en4-was-q-b3", type: "multiple_choice", prompt: "'We ______ in Baku last year.' — düzgün forma hansıdır?", options: ["were", "was", "are", "is"], correctIndex: 0, xp: 15, explanation: "«We» cəmdir, ona görə were işlənir. Last year = keçən il, yəni keçmişdir." },
            { id: "en4-was-q-b4", type: "multiple_choice", prompt: "'There was a park here.' nə deməkdir?", options: ["Burada park var idi.", "Burada park var.", "Burada park olacaq.", "Burada park yoxdur."], correctIndex: 0, xp: 15, explanation: "There was keçmişdə nəyinsə mövcud olduğunu bildirir — «var idi»." },
          ],
        },
        {
          id: "en4-was-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en4-was-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 3. Past Simple (-ed) ═══════════════
    {
      id: "en4-past",
      title: "Past Simple (-ed feillər)",
      description: "Keçmiş sadə zaman: qaydalı feillərə -ed əlavə olunur.",
      lessons: [
        {
          id: "en4-past-rule",
          title: "Qayda: Past Simple",
          intro: "Qaydalı feillər: play → played, watch → watched. Qeyri-qaydalı: go → went.",
          sections: [
            { heading: "Qaydalı feillər", body: "Feilə -ed əlavə olunur: play → played, watch → watched, help → helped. 'I played football yesterday.'" },
            { heading: "Qeyri-qaydalı feillər", body: "Bəziləri dəyişir: go → went, see → saw, eat → ate, have → had." },
          ],
          tasks: [
            { id: "en4-past-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'play' feilinin keçmiş forması?", options: ["played", "playd", "plaied", "playing"], correctIndex: 0, xp: 10, explanation: "Play qaydalı feildir, keçmişdə sonuna -ed qoşulur: played." },
            { id: "en4-past-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'watch' feilinin keçmiş forması?", options: ["watched", "watchd", "watch", "watching"], correctIndex: 0, xp: 10, explanation: "Watch qaydalı feildir: watch + ed = watched." },
            { id: "en4-past-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'help' feilinin keçmiş forması?", options: ["helped", "helpd", "holp", "helping"], correctIndex: 0, xp: 10, explanation: "Help qaydalı feildir: help + ed = helped." },
            { id: "en4-past-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "Qaydalı feillərə keçmişdə hansı şəkilçi əlavə olunur?", options: ["-ed", "-ing", "-s", "-er"], correctIndex: 0, xp: 10, explanation: "Qaydalı feillərin keçmiş forması sonuna -ed əlavə etməklə düzəlir." },
            { id: "en4-past-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "'go' feilinin keçmiş forması?", options: ["went", "goed", "gone", "going"], correctIndex: 0, xp: 10, explanation: "Go qaydasız feildir — sonuna -ed qoşulmur, forma tamam dəyişir: went." },
            { id: "en4-past-rule-t6", type: "multiple_choice", speakOptions: true, prompt: "'see' feilinin keçmiş forması?", options: ["saw", "seed", "seen", "sawing"], correctIndex: 0, xp: 10, explanation: "See qaydasız feildir: see → saw." },
            { id: "en4-past-rule-t7", type: "multiple_choice", speakOptions: true, prompt: "'eat' feilinin keçmiş forması?", options: ["ate", "eated", "eaten", "eating"], correctIndex: 0, xp: 10, explanation: "Eat qaydasız feildir: eat → ate." },
            { id: "en4-past-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'have' feilinin keçmiş forması?", options: ["had", "haved", "has", "having"], correctIndex: 0, xp: 10, explanation: "Have qaydasız feildir: have → had." },
            { id: "en4-past-rule-t9", type: "multiple_choice", prompt: "'I played football.' nə deməkdir?", options: ["Futbol oynadım.", "Futbol oynayıram.", "Futbol oynayacağam.", "Futbolu sevirəm."], correctIndex: 0, xp: 10, explanation: "Played keçmiş formadır — iş artıq baş verib." },
            { id: "en4-past-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "'We ___ TV yesterday.' (baxdıq)", options: ["watched", "watch", "watching", "watches"], correctIndex: 0, xp: 10, explanation: "Yesterday = dünən, yəni keçmiş. Watch qaydalı feildir: watched." },
            { id: "en4-past-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "'She ___ to school.' (getdi)", options: ["went", "goed", "go", "going"], correctIndex: 0, xp: 10, explanation: "Go qaydasız feildir, keçmişdə went olur." },
            { id: "en4-past-rule-t12", type: "fill_blank", prompt: "'open' feilinin keçmiş formasını yaz.", accepted: ["opened"], xp: 10, explanation: "Open qaydalı feildir: open + ed = opened." },
            { id: "en4-past-rule-t13", type: "fill_blank", prompt: "'clean' feilinin keçmiş formasını yaz.", accepted: ["cleaned"], xp: 10, explanation: "Clean qaydalı feildir: clean + ed = cleaned." },
            { id: "en4-past-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'I ___ play.' (oynamadım)", options: ["didn't", "wasn't", "don't", "not"], correctIndex: 0, xp: 10, explanation: "Keçmiş zamanda inkar didn't ilə düzəlir; ondan sonra feil əsas formada qalır." },
            { id: "en4-past-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'They ___ a film.' (baxdılar)", options: ["watched", "watch", "watching", "watches"], correctIndex: 0, xp: 15, explanation: "Watch qaydalı feildir, keçmişdə watched olur." },
          ],
          bonusTasks: [
            { id: "en4-past-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "'study' feilinin keçmiş forması?", options: ["studied", "studyed", "studed", "studying"], correctIndex: 0, xp: 15, explanation: "Sonu samit + y ilə bitən feildə y hərfi i-yə çevrilir: study → studied." },
            { id: "en4-past-rule-b2", type: "multiple_choice", speakOptions: true, prompt: "'drink' feilinin keçmiş forması?", options: ["drank", "drinked", "drunk", "drinking"], correctIndex: 0, xp: 15, explanation: "Drink qaydasız feildir: drink → drank." },
            { id: "en4-past-rule-b3", type: "multiple_choice", prompt: "'She didn't come.' nə deməkdir?", options: ["O gəlmədi.", "O gəldi.", "O gəlir.", "O gələcək."], correctIndex: 0, xp: 15, explanation: "Didn't keçmişdə inkar bildirir, come = gəlmək." },
            { id: "en4-past-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "Sual: '___ you play football?' (oynadın?)", options: ["Did", "Do", "Was", "Are"], correctIndex: 0, xp: 15, explanation: "Keçmiş zaman sualı did ilə qurulur; ondan sonra feil əsas formada qalır." },
            { id: "en4-past-rule-b5", type: "fill_blank", prompt: "'want' feilinin keçmiş formasını yaz.", accepted: ["wanted"], xp: 15, explanation: "Want qaydalı feildir: want + ed = wanted." },
          ],
        },
        {
          id: "en4-past-irregular",
          title: "Qaydasız feillər",
          intro: "Bəzi feillər -ed almır.",
          sections: [
            { heading: "Qaydasız", body: "go → went, see → saw, eat → ate, come → came, do → did, have → had, make → made, take → took." },
            { heading: "İnkar və sual", body: "İnkarda və sualda feil ƏSAS formaya qayıdır: 'I didn't go.' 'Did you go?'" },
          ],
          tasks: [
            { id: "en4-past-irregular-t1", type: "multiple_choice", prompt: "'go' feilinin keçmiş forması hansıdır?", options: ["went", "goed", "gone", "going"], correctIndex: 0, xp: 10, explanation: "Go qaydasız feildir: go → went. «Gone» isə üçüncü formadır." },
            { id: "en4-past-irregular-t2", type: "multiple_choice", prompt: "'see' feilinin keçmiş forması hansıdır?", options: ["saw", "seed", "seen", "seeing"], correctIndex: 0, xp: 10, explanation: "See qaydasız feildir: see → saw. «Seen» isə üçüncü formadır." },
            { id: "en4-past-irregular-t3", type: "multiple_choice", prompt: "'eat' feilinin keçmiş forması hansıdır?", options: ["ate", "eated", "eaten", "eating"], correctIndex: 0, xp: 10, explanation: "Eat qaydasız feildir: eat → ate. «Eaten» isə üçüncü formadır." },
            { id: "en4-past-irregular-t4", type: "multiple_choice", prompt: "'come' feilinin keçmiş forması hansıdır?", options: ["came", "comed", "come", "coming"], correctIndex: 0, xp: 10, explanation: "Come qaydasız feildir: come → came." },
            { id: "en4-past-irregular-t5", type: "multiple_choice", prompt: "'I didn't ______ there.' — düzgün forma hansıdır?", options: ["go", "went", "gone", "going"], correctIndex: 0, xp: 10, explanation: "Didn't özü artıq keçmişi bildirir, ona görə feil əsas formada qalır: didn't go." },
            { id: "en4-past-irregular-t6", type: "multiple_choice", prompt: "'Did you ______ the film?' — düzgün forma hansıdır?", options: ["see", "saw", "seen", "seeing"], correctIndex: 0, xp: 10, explanation: "Did özü artıq keçmişi bildirir, ona görə feil əsas formada qalır: Did you see...?" },
            { id: "en4-past-irregular-t7", type: "multiple_choice", prompt: "'have' feilinin keçmiş forması hansıdır?", options: ["had", "haved", "has", "having"], correctIndex: 0, xp: 10, explanation: "Have qaydasız feildir: have → had." },
            { id: "en4-past-irregular-t8", type: "multiple_choice", prompt: "'make' feilinin keçmiş forması hansıdır?", options: ["made", "maked", "make", "making"], correctIndex: 0, xp: 10, explanation: "Make qaydasız feildir: make → made." },
            { id: "en4-past-irregular-t9", type: "multiple_choice", prompt: "İnkarda feil hansı formada olur?", options: ["Əsas forma", "Keçmiş forma", "-ing forma", "-ed forma"], correctIndex: 0, xp: 10, explanation: "Didn't keçmişi bildirdiyi üçün feil ikinci dəfə keçmişə çevrilmir — əsas formada qalır." },
            { id: "en4-past-irregular-t10", type: "multiple_choice", prompt: "'take' feilinin keçmiş forması hansıdır?", options: ["took", "taked", "taken", "taking"], correctIndex: 0, xp: 10, explanation: "Take qaydasız feildir: take → took. «Taken» isə üçüncü formadır." },
          ],
          bonusTasks: [
            { id: "en4-past-irregular-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I went to school.", options: ["Məktəbə getdim.", "Məktəbə gedirəm.", "Məktəbə gedəcəyəm.", "Məktəbdəyəm."], correctIndex: 0, xp: 15, explanation: "Səsdə «I went to school» deyildi. Went keçmiş formadır — «getdim»." },
            { id: "en4-past-irregular-b2", type: "multiple_choice", prompt: "'Did she go?' sualına inkar cavab hansıdır?", options: ["No, she didn't.", "No, she doesn't.", "No, she wasn't.", "No, she don't."], correctIndex: 0, xp: 15, explanation: "Sual did ilə qurulub, ona görə inkar cavab da didn't ilə verilir." },
            { id: "en4-past-irregular-b3", type: "multiple_choice", prompt: "'write' feilinin keçmiş forması hansıdır?", options: ["wrote", "writed", "written", "writing"], correctIndex: 0, xp: 15, explanation: "Write qaydasız feildir: write → wrote. «Written» isə üçüncü formadır." },
            { id: "en4-past-irregular-b4", type: "multiple_choice", prompt: "Qaydasız feilləri necə öyrənmək olar?", options: ["Əzbərləməklə", "Qayda tətbiq etməklə", "-ed əlavə etməklə", "Öyrənmək olmur"], correctIndex: 0, xp: 15, explanation: "Qaydasız feillərin forması qaydaya tabe olmur, ona görə hər biri ayrıca yadda saxlanılır." },
          ],
        },
        {
          id: "en4-past-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en4-past-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 4. There is / there are ═══════════════
    {
      id: "en4-there",
      title: "There is / there are (var)",
      description: "Bir şeyin mövcudluğunu bildirmək: There is a book. There are books.",
      lessons: [
        {
          id: "en4-there-rule",
          title: "Qayda: there is / there are",
          intro: "There is (tək), There are (cəm).",
          sections: [
            { heading: "there is / are", body: "There is + tək isim: There is a cat. (Bir pişik var.) There are + cəm isim: There are three cats. (Üç pişik var.)" },
            { heading: "İnkar", body: "There isn't / There aren't: There isn't a dog. There aren't any books." },
          ],
          tasks: [
            { id: "en4-there-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'There ___ a book on the table.' (tək)", options: ["is", "are", "am", "be"], correctIndex: 0, xp: 10, explanation: "«A book» təkdir, ona görə there is işlənir." },
            { id: "en4-there-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'There ___ three cats.' (cəm)", options: ["are", "is", "am", "be"], correctIndex: 0, xp: 10, explanation: "«Three cats» cəmdir, ona görə there are işlənir." },
            { id: "en4-there-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "Tək isimlə hansı işlənir?", options: ["there is", "there are", "there am", "there be"], correctIndex: 0, xp: 10, explanation: "Tək isimlə there is işlənir: there is a book." },
            { id: "en4-there-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "Cəm isimlə hansı işlənir?", options: ["there are", "there is", "there am", "there be"], correctIndex: 0, xp: 10, explanation: "Cəm isimlə there are işlənir: there are books." },
            { id: "en4-there-rule-t5", type: "multiple_choice", prompt: "'There is a dog.' nə deməkdir?", options: ["Bir it var.", "İt yoxdur.", "İtlər var.", "İt gəldi."], correctIndex: 0, xp: 10, explanation: "There is nəyinsə mövcud olduğunu bildirir — «var»." },
            { id: "en4-there-rule-t6", type: "multiple_choice", prompt: "'There are five apples.' nə deməkdir?", options: ["Beş alma var.", "Bir alma var.", "Alma yoxdur.", "Alma aldım."], correctIndex: 0, xp: 10, explanation: "There are cəmdə mövcudluğu bildirir, five apples = beş alma." },
            { id: "en4-there-rule-t7", type: "multiple_choice", speakOptions: true, prompt: "'There ___ many students.'", options: ["are", "is", "am", "be"], correctIndex: 0, xp: 10, explanation: "«Many students» cəmdir, ona görə are işlənir." },
            { id: "en4-there-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'There ___ a pen in my bag.'", options: ["is", "are", "am", "be"], correctIndex: 0, xp: 10, explanation: "«A pen» təkdir, ona görə is işlənir." },
            { id: "en4-there-rule-t9", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'There ___ a cat.' (yoxdur)", options: ["isn't", "aren't", "am not", "not"], correctIndex: 0, xp: 10, explanation: "«A cat» təkdir, ona görə inkar isn't olur (is + not)." },
            { id: "en4-there-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'There ___ any books.' (yoxdur, cəm)", options: ["aren't", "isn't", "am not", "not"], correctIndex: 0, xp: 10, explanation: "«Books» cəmdir, ona görə inkar aren't olur (are + not)." },
            { id: "en4-there-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "'There ___ two windows.'", options: ["are", "is", "am", "be"], correctIndex: 0, xp: 10, explanation: "«Two windows» cəmdir, ona görə are işlənir." },
            { id: "en4-there-rule-t12", type: "multiple_choice", speakOptions: true, prompt: "'There ___ a school near my house.'", options: ["is", "are", "am", "be"], correctIndex: 0, xp: 10, explanation: "«A school» təkdir, ona görə is işlənir." },
            { id: "en4-there-rule-t13", type: "multiple_choice", prompt: "'There are books on the shelf.' nə deməkdir?", options: ["Rəfdə kitablar var.", "Rəfdə kitab yoxdur.", "Rəf boşdur.", "Kitab aldım."], correctIndex: 0, xp: 10, explanation: "There are cəmdə mövcudluğu bildirir, shelf = rəf." },
            { id: "en4-there-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "'There ___ a big tree in the garden.'", options: ["is", "are", "am", "be"], correctIndex: 0, xp: 10, explanation: "«A big tree» təkdir, ona görə is işlənir." },
            { id: "en4-there-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'There ___ four seasons.'", options: ["are", "is", "am", "be"], correctIndex: 0, xp: 15, explanation: "«Four seasons» cəmdir, ona görə are işlənir." },
          ],
          bonusTasks: [
            { id: "en4-there-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "Sual: '___ there a park here?'", options: ["Is", "Are", "Am", "Do"], correctIndex: 0, xp: 15, explanation: "«A park» təkdir, ona görə sualda is əvvələ keçir: Is there...?" },
            { id: "en4-there-rule-b2", type: "multiple_choice", speakOptions: true, prompt: "Sual: '___ there any apples?'", options: ["Are", "Is", "Am", "Do"], correctIndex: 0, xp: 15, explanation: "«Apples» cəmdir, ona görə sualda are əvvələ keçir: Are there...?" },
            { id: "en4-there-rule-b3", type: "multiple_choice", prompt: "'There isn't any milk.' nə deməkdir?", options: ["Heç süd yoxdur.", "Süd var.", "Çoxlu süd var.", "Süd aldım."], correctIndex: 0, xp: 15, explanation: "Isn't inkar, any isə «heç» mənası verir — deməli «Heç süd yoxdur»." },
            { id: "en4-there-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "'There ___ some water in the glass.'", options: ["is", "are", "am", "be"], correctIndex: 0, xp: 15, explanation: "Water sayıla bilməyən isimdir, ona görə tək kimi qəbul olunur və is işlənir." },
            { id: "en4-there-rule-b5", type: "multiple_choice", speakOptions: true, prompt: "'There ___ a lot of people.'", options: ["are", "is", "am", "be"], correctIndex: 0, xp: 15, explanation: "«A lot of people» çoxluq bildirir və cəmdir, ona görə are işlənir." },
          ],
        },
        {
          id: "en4-there-q",
          title: "There is / there are — sual və inkar",
          intro: "Nə var, nə yoxdur?",
          sections: [
            { heading: "Sual", body: "'Is there a park?' — Park var? 'Are there any shops?' — Mağazalar var?" },
            { heading: "İnkar", body: "'There isn't a cinema.' — Kinoteatr yoxdur. 'There aren't any trees.' — Ağac yoxdur." },
          ],
          tasks: [
            { id: "en4-there-q-t1", type: "multiple_choice", prompt: "'Is there a park?' nə deməkdir?", options: ["Park var?", "Park haradadır?", "Parka gedirsən?", "Park gözəldir?"], correctIndex: 0, xp: 10, explanation: "Is there...? nəyinsə olub-olmadığını soruşur — «var?»" },
            { id: "en4-there-q-t2", type: "multiple_choice", prompt: "'There isn't a cinema.' nə deməkdir?", options: ["Kinoteatr yoxdur.", "Kinoteatr var.", "Kinoteatra gedirəm.", "Kinoteatr uzaqdır."], correctIndex: 0, xp: 10, explanation: "There isn't nəyinsə olmadığını bildirir — «yoxdur»." },
            { id: "en4-there-q-t3", type: "multiple_choice", prompt: "'There ______ two books.' — düzgün forma hansıdır?", options: ["are", "is", "am", "be"], correctIndex: 0, xp: 10, explanation: "«Two books» cəmdir, ona görə are işlənir." },
            { id: "en4-there-q-t4", type: "multiple_choice", prompt: "'There ______ a cat.' — düzgün forma hansıdır?", options: ["is", "are", "am", "be"], correctIndex: 0, xp: 10, explanation: "«A cat» təkdir, ona görə is işlənir." },
            { id: "en4-there-q-t5", type: "multiple_choice", prompt: "'Are there any shops?' sualına müsbət cavab hansıdır?", options: ["Yes, there are.", "Yes, there is.", "Yes, they are.", "Yes, it is."], correctIndex: 0, xp: 10, explanation: "Sual are ilə qurulub, ona görə cavab da are ilə verilir: «Yes, there are»." },
            { id: "en4-there-q-t6", type: "multiple_choice", prompt: "Tək isimlə hansı forma işlənir?", options: ["there is", "there are", "there am", "there be"], correctIndex: 0, xp: 10, explanation: "Tək isimlə there is işlənir." },
            { id: "en4-there-q-t7", type: "multiple_choice", prompt: "'There are five chairs.' nə deməkdir?", options: ["Beş stul var.", "Beş stul yoxdur.", "Stullar beşdir?", "Stul lazımdır."], correctIndex: 0, xp: 10, explanation: "There are cəmdə mövcudluğu bildirir, chairs = stullar." },
            { id: "en4-there-q-t8", type: "multiple_choice", prompt: "'any' sözü daha çox harada işlənir?", options: ["Sual və inkarda", "Yalnız təsdiqdə", "Heç yerdə", "Yalnız cəmdə"], correctIndex: 0, xp: 10, explanation: "Any «heç, bir qədər» mənası verir və əsasən sual ilə inkarda işlənir. Təsdiqdə some işlənir." },
            { id: "en4-there-q-t9", type: "multiple_choice", speakOptions: true, prompt: "'körpü' İngiliscə necədir?", options: ["bridge", "bird", "brick", "branch"], correctIndex: 0, xp: 10, explanation: "«Körpü» ingiliscə bridge olur. Bird = quş, brick = kərpic." },
            { id: "en4-there-q-t10", type: "multiple_choice", prompt: "'There aren't any trees.' nə deməkdir?", options: ["Heç bir ağac yoxdur.", "Ağaclar var.", "Ağac əkirəm.", "Ağac böyükdür."], correctIndex: 0, xp: 10, explanation: "Aren't inkar, any isə «heç» mənası verir — deməli «Heç bir ağac yoxdur»." },
          ],
          bonusTasks: [
            { id: "en4-there-q-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "There is a book on the table.", options: ["Masanın üstündə kitab var.", "Masanın üstündə kitab yoxdur.", "Kitab masadadır?", "Kitabı masaya qoy."], correctIndex: 0, xp: 15, explanation: "Səsdə «There is a book on the table» deyildi. There is = var, on the table = masanın üstündə." },
            { id: "en4-there-q-b2", type: "multiple_choice", prompt: "'How many students are there?' nə soruşur?", options: ["Neçə şagird var?", "Şagirdlər haradadır?", "Şagirdlər kimdir?", "Şagird nədir?"], correctIndex: 0, xp: 15, explanation: "How many = neçə, are there = var. Deməli sual şagirdlərin sayını soruşur." },
            { id: "en4-there-q-b3", type: "multiple_choice", prompt: "'There is some water.' — niyə 'is' işlənib?", options: ["Çünki 'water' sayıla bilməyəndir", "Səhvdir", "Çünki cəmdir", "Çünki sualdır"], correctIndex: 0, xp: 15, explanation: "Water sayıla bilməyən isimdir — «one water, two waters» deyilmir, ona görə tək kimi qəbul olunur." },
            { id: "en4-there-q-b4", type: "multiple_choice", prompt: "'There were many people.' hansı zamandadır?", options: ["Keçmiş", "İndiki", "Gələcək", "Zamansız"], correctIndex: 0, xp: 15, explanation: "Were sözü are-ın keçmiş formasıdır — deməli cümlə keçmiş zamandadır." },
          ],
        },
        {
          id: "en4-there-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en4-there-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 5. Comparatives ═══════════════
    {
      id: "en4-comp",
      title: "Müqayisə (bigger, taller)",
      description: "Sifətlərin müqayisə dərəcəsi: -er + than.",
      lessons: [
        {
          id: "en4-comp-rule",
          title: "Qayda: comparatives",
          intro: "Qısa sifət + -er + than: taller than, bigger than.",
          sections: [
            { heading: "Qayda", body: "Qısa sifətə -er əlavə olunur: tall → taller, big → bigger, small → smaller. Müqayisədə 'than' işlənir: 'Ali is taller than Tom.'" },
          ],
          tasks: [
            { id: "en4-comp-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'tall' sözünün müqayisə forması?", options: ["taller", "tallest", "more tall", "talest"], correctIndex: 0, xp: 10, explanation: "Qısa sifətlərdə müqayisə sonuna -er əlavə etməklə düzəlir: tall → taller." },
            { id: "en4-comp-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'small' sözünün müqayisə forması?", options: ["smaller", "smallest", "more small", "smalest"], correctIndex: 0, xp: 10, explanation: "Qısa sifətə -er qoşulur: small → smaller." },
            { id: "en4-comp-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'big' sözünün müqayisə forması?", options: ["bigger", "biger", "more big", "biggest"], correctIndex: 0, xp: 10, explanation: "Qısa saitdən sonra tək samitlə bitən sifətdə son samit ikiqat yazılır: big → bigger." },
            { id: "en4-comp-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "'old' sözünün müqayisə forması?", options: ["older", "oldest", "more old", "olderer"], correctIndex: 0, xp: 10, explanation: "Qısa sifətə -er qoşulur: old → older." },
            { id: "en4-comp-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "Müqayisədə hansı söz işlənir?", options: ["than", "then", "that", "as"], correctIndex: 0, xp: 10, explanation: "Müqayisə edilən iki şeyi than sözü bağlayır: taller than Tom." },
            { id: "en4-comp-rule-t6", type: "multiple_choice", speakOptions: true, prompt: "'Ali is ___ than Tom.' (uca)", options: ["taller", "tall", "tallest", "more tall"], correctIndex: 0, xp: 10, explanation: "Than sözü müqayisə olduğunu göstərir, ona görə sifət -er formasında olmalıdır: taller." },
            { id: "en4-comp-rule-t7", type: "multiple_choice", speakOptions: true, prompt: "'An elephant is ___ than a cat.' (böyük)", options: ["bigger", "big", "biggest", "more big"], correctIndex: 0, xp: 10, explanation: "Than müqayisə bildirir, big qısa sifətdir və samiti ikiqatlanır: bigger." },
            { id: "en4-comp-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'fast' sözünün müqayisə forması?", options: ["faster", "fastest", "more fast", "fasterer"], correctIndex: 0, xp: 10, explanation: "Qısa sifətə -er qoşulur: fast → faster." },
            { id: "en4-comp-rule-t9", type: "multiple_choice", prompt: "'A car is faster than a bike.' nə deməkdir?", options: ["Maşın velosipeddən sürətlidir.", "Velosiped sürətlidir.", "Maşın yavaşdır.", "İkisi eynidir."], correctIndex: 0, xp: 10, explanation: "Faster than = ...dan sürətlidir. Deməli müqayisədə maşın üstündür." },
            { id: "en4-comp-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "'young' sözünün müqayisə forması?", options: ["younger", "youngest", "more young", "youngerer"], correctIndex: 0, xp: 10, explanation: "Qısa sifətə -er qoşulur: young → younger." },
            { id: "en4-comp-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "'long' sözünün müqayisə forması?", options: ["longer", "longest", "more long", "longerer"], correctIndex: 0, xp: 10, explanation: "Qısa sifətə -er qoşulur: long → longer." },
            { id: "en4-comp-rule-t12", type: "multiple_choice", speakOptions: true, prompt: "'short' sözünün müqayisə forması?", options: ["shorter", "shortest", "more short", "shorterer"], correctIndex: 0, xp: 10, explanation: "Qısa sifətə -er qoşulur: short → shorter." },
            { id: "en4-comp-rule-t13", type: "multiple_choice", prompt: "'Winter is colder than summer.' nə deməkdir?", options: ["Qış yaydan soyuqdur.", "Yay soyuqdur.", "Qış istidir.", "İkisi eynidir."], correctIndex: 0, xp: 10, explanation: "Colder than = ...dan soyuqdur. Deməli qış yaydan soyuqdur." },
            { id: "en4-comp-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "'This box is ___ than that one.' (ağır)", options: ["heavier", "heavy", "heaviest", "more heavy"], correctIndex: 0, xp: 10, explanation: "Sonu samit + y ilə bitən sifətdə y hərfi i-yə çevrilir: heavy → heavier." },
            { id: "en4-comp-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'My bag is ___ than yours.' (kiçik)", options: ["smaller", "small", "smallest", "more small"], correctIndex: 0, xp: 15, explanation: "Than müqayisə bildirir, ona görə sifət -er formasında olmalıdır: smaller." },
          ],
          bonusTasks: [
            { id: "en4-comp-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "'good' sözünün müqayisə forması (qeyri-qaydalı)?", options: ["better", "gooder", "more good", "best"], correctIndex: 0, xp: 15, explanation: "Good qaydasız sifətdir — «gooder» yoxdur, müqayisə forması better-dir." },
            { id: "en4-comp-rule-b2", type: "multiple_choice", speakOptions: true, prompt: "'happy' sözünün müqayisə forması?", options: ["happier", "happyer", "more happy", "happiest"], correctIndex: 0, xp: 15, explanation: "Sonu samit + y ilə bitən sifətdə y hərfi i-yə çevrilir: happy → happier." },
            { id: "en4-comp-rule-b3", type: "multiple_choice", prompt: "'A mouse is smaller than a cat.' nə deməkdir?", options: ["Siçan pişikdən kiçikdir.", "Pişik kiçikdir.", "Siçan böyükdür.", "İkisi eynidir."], correctIndex: 0, xp: 15, explanation: "Smaller than = ...dan kiçikdir. Deməli siçan pişikdən kiçikdir." },
            { id: "en4-comp-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "'nice' sözünün müqayisə forması?", options: ["nicer", "niceer", "more nice", "nicest"], correctIndex: 0, xp: 15, explanation: "Sonu -e ilə bitən sifətə yalnız -r qoşulur: nice → nicer." },
            { id: "en4-comp-rule-b5", type: "multiple_choice", speakOptions: true, prompt: "'hot' sözünün müqayisə forması?", options: ["hotter", "hoter", "more hot", "hottest"], correctIndex: 0, xp: 15, explanation: "Qısa saitdən sonra tək samitlə bitdiyi üçün son samit ikiqat yazılır: hot → hotter." },
          ],
        },
        {
          id: "en4-comp-super",
          title: "Superlatives — ən üstün dərəcə",
          intro: "Ən böyük, ən yaxşı, ən maraqlı.",
          sections: [
            { heading: "Qayda", body: "Qısa sifətlərə -est: big → the biggest, tall → the tallest. Uzun sifətlərə most: interesting → the most interesting." },
            { heading: "Qaydasız", body: "good → better → the best. bad → worse → the worst." },
          ],
          tasks: [
            { id: "en4-comp-super-t1", type: "multiple_choice", prompt: "'big' sifətinin üstünlük dərəcəsi hansıdır?", options: ["the biggest", "the bigest", "the most big", "biger"], correctIndex: 0, xp: 10, explanation: "Üstünlük dərəcəsi the + sifət + -est ilə düzəlir; big sözündə samit ikiqatlanır: the biggest." },
            { id: "en4-comp-super-t2", type: "multiple_choice", prompt: "'tall' sifətinin üstünlük dərəcəsi hansıdır?", options: ["the tallest", "the most tall", "the taller", "tallest more"], correctIndex: 0, xp: 10, explanation: "Üstünlük dərəcəsi the + sifət + -est ilə düzəlir: the tallest." },
            { id: "en4-comp-super-t3", type: "multiple_choice", prompt: "'good' sifətinin üstünlük dərəcəsi hansıdır?", options: ["the best", "the goodest", "the most good", "the better"], correctIndex: 0, xp: 10, explanation: "Good qaydasız sifətdir: good → better → the best." },
            { id: "en4-comp-super-t4", type: "multiple_choice", prompt: "'bad' sifətinin üstünlük dərəcəsi hansıdır?", options: ["the worst", "the baddest", "the most bad", "the worse"], correctIndex: 0, xp: 10, explanation: "Bad qaydasız sifətdir: bad → worse → the worst." },
            { id: "en4-comp-super-t5", type: "multiple_choice", prompt: "'interesting' sifətinin üstünlük dərəcəsi hansıdır?", options: ["the most interesting", "the interestingest", "the interestinger", "most interesting"], correctIndex: 0, xp: 10, explanation: "Interesting uzun sifətdir, ona görə -est yox, the most işlənir." },
            { id: "en4-comp-super-t6", type: "multiple_choice", prompt: "Uzun sifətlərdə hansı söz işlənir?", options: ["most", "more", "the -est", "very"], correctIndex: 0, xp: 10, explanation: "Uzun sifətlərə -est qoşulmur — onların qarşısına most gətirilir: the most beautiful." },
            { id: "en4-comp-super-t7", type: "multiple_choice", prompt: "'This is the biggest city.' nə deməkdir?", options: ["Bu, ən böyük şəhərdir.", "Bu, böyük şəhərdir.", "Bu şəhər böyükdür.", "Bu şəhər daha böyükdür."], correctIndex: 0, xp: 10, explanation: "The biggest üstünlük dərəcəsidir — «ən böyük», sadəcə «daha böyük» yox." },
            { id: "en4-comp-super-t8", type: "multiple_choice", prompt: "Üstünlük dərəcəsindən əvvəl hansı söz gəlir?", options: ["the", "a", "an", "some"], correctIndex: 0, xp: 10, explanation: "Üstünlük dərəcəsi konkret bir şeyi seçdiyi üçün qarşısına the artiklı qoyulur." },
            { id: "en4-comp-super-t9", type: "multiple_choice", prompt: "'small' sifətinin müqayisə dərəcəsi hansıdır?", options: ["smaller", "more small", "smallest", "the small"], correctIndex: 0, xp: 10, explanation: "Müqayisə dərəcəsi -er ilə düzəlir: smaller. The smallest isə üstünlükdür." },
            { id: "en4-comp-super-t10", type: "multiple_choice", prompt: "'happy' sifətinin üstünlük dərəcəsi hansıdır?", options: ["the happiest", "the happyest", "the most happy", "the happier"], correctIndex: 0, xp: 10, explanation: "Sonu samit + y ilə bitdiyi üçün y hərfi i-yə çevrilir: happy → the happiest." },
          ],
          bonusTasks: [
            { id: "en4-comp-super-b1", type: "multiple_choice", prompt: "'Ali is taller than Nihad.' nə deməkdir?", options: ["Əli Nihaddan hündürdür.", "Əli ən hündürdür.", "Nihad hündürdür.", "İkisi eynidir."], correctIndex: 0, xp: 15, explanation: "Taller than = ...dan hündürdür. Bu, müqayisədir, «ən hündür» deyil." },
            { id: "en4-comp-super-b2", type: "multiple_choice", prompt: "'than' sözü nə üçündür?", options: ["Müqayisə üçün", "Sual üçün", "İnkar üçün", "Sadalama üçün"], correctIndex: 0, xp: 15, explanation: "Than iki şeyi qarşılaşdırır və müqayisə dərəcəsi ilə birlikdə işlənir." },
            { id: "en4-comp-super-b3", type: "multiple_choice", prompt: "'far' sifətinin müqayisə forması hansıdır?", options: ["farther / further", "farer", "more far", "the farest"], correctIndex: 0, xp: 15, explanation: "Far qaydasız sifətdir: müqayisə forması farther və ya further olur." },
            { id: "en4-comp-super-b4", type: "multiple_choice", prompt: "'This book is more interesting than that one.' nə deməkdir?", options: ["Bu kitab o birindən maraqlıdır.", "Bu kitab ən maraqlıdır.", "O kitab maraqlıdır.", "İkisi eynidir."], correctIndex: 0, xp: 15, explanation: "More interesting than = ...dan maraqlıdır. Uzun sifət olduğu üçün more işlənir." },
          ],
        },
        {
          id: "en4-comp-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en4-comp-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 6. Sual sözləri və lüğət ═══════════════
    {
      id: "en4-questions",
      title: "Sual sözləri və lüğət",
      description: "Sual sözləri (what/where/when/who) və tematik lüğət.",
      lessons: [
        {
          id: "en4-questions-vocab",
          title: "Question words & vocab",
          intro: "Sual sözlərini və yeni sözləri öyrənək.",
          sections: [
            { heading: "Sual sözləri", body: "what — nə, where — harada, when — nə vaxt, who — kim, how — necə, why — niyə, how many — neçə." },
            { heading: "Lüğət", body: "hobby — hobbi, sport — idman, weekend — həftəsonu, holiday — bayram/tətil, friend — dost." },
          ],
          tasks: [
            { id: "en4-questions-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'what' nə deməkdir?", options: ["nə", "harada", "kim", "nə vaxt"], correctIndex: 0, xp: 10, explanation: "What azərbaycanca «nə» deməkdir." },
            { id: "en4-questions-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'where' nə deməkdir?", options: ["harada", "nə", "kim", "necə"], correctIndex: 0, xp: 10, explanation: "Where azərbaycanca «harada» deməkdir." },
            { id: "en4-questions-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'when' nə deməkdir?", options: ["nə vaxt", "harada", "kim", "niyə"], correctIndex: 0, xp: 10, explanation: "When azərbaycanca «nə vaxt» deməkdir." },
            { id: "en4-questions-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'who' nə deməkdir?", options: ["kim", "nə", "harada", "necə"], correctIndex: 0, xp: 10, explanation: "Who azərbaycanca «kim» deməkdir." },
            { id: "en4-questions-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'how' nə deməkdir?", options: ["necə", "nə", "kim", "niyə"], correctIndex: 0, xp: 10, explanation: "How azərbaycanca «necə» deməkdir." },
            { id: "en4-questions-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'why' nə deməkdir?", options: ["niyə", "necə", "kim", "harada"], correctIndex: 0, xp: 10, explanation: "Why azərbaycanca «niyə» deməkdir." },
            { id: "en4-questions-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'___ is your name?' (nə)", options: ["What", "Where", "Who", "When"], correctIndex: 0, xp: 10, explanation: "Sual adı soruşur, «nə» isə ingiliscə what-dır." },
            { id: "en4-questions-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "'___ do you live?' (harada)", options: ["Where", "What", "Who", "When"], correctIndex: 0, xp: 10, explanation: "Sual yeri soruşur, «harada» isə ingiliscə where-dir." },
            { id: "en4-questions-vocab-t9", type: "multiple_choice", speakOptions: true, prompt: "'___ is your teacher?' (kim)", options: ["Who", "What", "Where", "How"], correctIndex: 0, xp: 10, explanation: "Sual şəxsi soruşur, «kim» isə ingiliscə who-dur." },
            { id: "en4-questions-vocab-t10", type: "multiple_choice", speakOptions: true, prompt: "'how many' nə deməkdir?", options: ["neçə", "necə", "nə vaxt", "niyə"], correctIndex: 0, xp: 10, explanation: "How many sayıla bilən şeylərin sayını soruşur — «neçə»." },
            { id: "en4-questions-vocab-t11", type: "multiple_choice", speakOptions: true, prompt: "'hobby' nə deməkdir?", options: ["hobbi/məşğuliyyət", "idman", "bayram", "dost"], correctIndex: 0, xp: 10, explanation: "Hobby azərbaycanca «hobbi, sevimli məşğuliyyət» deməkdir." },
            { id: "en4-questions-vocab-t12", type: "multiple_choice", speakOptions: true, prompt: "'weekend' nə deməkdir?", options: ["həftəsonu", "bayram", "gün", "ay"], correctIndex: 0, xp: 10, explanation: "Week = həftə, end = son. Birlikdə «həftəsonu» deməkdir." },
            { id: "en4-questions-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "'friend' nə deməkdir?", options: ["dost", "müəllim", "qonşu", "qardaş"], correctIndex: 0, xp: 10, explanation: "Friend azərbaycanca «dost» deməkdir." },
            { id: "en4-questions-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'holiday' nə deməkdir?", options: ["bayram/tətil", "iş günü", "səhər", "gecə"], correctIndex: 0, xp: 10, explanation: "Holiday azərbaycanca «bayram, tətil» deməkdir." },
            { id: "en4-questions-vocab-t15", type: "multiple_choice", speakOptions: true, prompt: "'sport' nə deməkdir?", options: ["idman", "hobbi", "oyun", "musiqi"], correctIndex: 0, xp: 15, explanation: "Sport azərbaycanca «idman» deməkdir." },
          ],
          bonusTasks: [
            { id: "en4-questions-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'___ are you sad?' (niyə)", options: ["Why", "What", "Who", "Where"], correctIndex: 0, xp: 15, explanation: "Sual səbəbi soruşur, «niyə» isə ingiliscə why-dır." },
            { id: "en4-questions-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'___ many books do you have?' (neçə)", options: ["How", "What", "Who", "When"], correctIndex: 0, xp: 15, explanation: "Sayı soruşmaq üçün how many işlənir, ona görə boşluğa How gəlir." },
            { id: "en4-questions-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'What is your favourite ___?' (hobbi)", options: ["hobby", "friend", "weekend", "holiday"], correctIndex: 0, xp: 15, explanation: "Favourite = sevimli. Sual sevimli məşğuliyyəti soruşur, bu isə hobby-dir." },
            { id: "en4-questions-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'which' nə deməkdir?", options: ["hansı", "kim", "nə vaxt", "niyə"], correctIndex: 0, xp: 15, explanation: "Which azərbaycanca «hansı» deməkdir — verilmiş variantlardan seçim soruşur." },
            { id: "en4-questions-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'On the ___ I play with friends.' (həftəsonu)", options: ["weekend", "hobby", "sport", "holiday"], correctIndex: 0, xp: 15, explanation: "Dostlarla oynanılan vaxt həftəsonudur, bu isə ingiliscə weekend-dir." },
          ],
        },
        {
          id: "en4-questions-wh",
          title: "Wh- sual sözləri",
          intro: "Kim, nə, harada, nə vaxt, niyə, necə.",
          sections: [
            { heading: "Sual sözləri", body: "who — kim, what — nə, where — harada, when — nə vaxt, why — niyə, how — necə, whose — kimin." },
            { heading: "Cavab", body: "'Why?' sualına 'Because...' ilə cavab verilir: 'Why are you happy?' — 'Because it is my birthday.'" },
          ],
          tasks: [
            { id: "en4-questions-wh-t1", type: "multiple_choice", speakOptions: true, prompt: "'kim' İngiliscə necədir?", options: ["who", "what", "where", "when"], correctIndex: 0, xp: 10, explanation: "«Kim» ingiliscə who olur." },
            { id: "en4-questions-wh-t2", type: "multiple_choice", speakOptions: true, prompt: "'harada' İngiliscə necədir?", options: ["where", "when", "what", "why"], correctIndex: 0, xp: 10, explanation: "«Harada» ingiliscə where olur." },
            { id: "en4-questions-wh-t3", type: "multiple_choice", speakOptions: true, prompt: "'nə vaxt' İngiliscə necədir?", options: ["when", "where", "who", "how"], correctIndex: 0, xp: 10, explanation: "«Nə vaxt» ingiliscə when olur." },
            { id: "en4-questions-wh-t4", type: "multiple_choice", speakOptions: true, prompt: "'niyə' İngiliscə necədir?", options: ["why", "how", "what", "who"], correctIndex: 0, xp: 10, explanation: "«Niyə» ingiliscə why olur." },
            { id: "en4-questions-wh-t5", type: "multiple_choice", speakOptions: true, prompt: "'necə' İngiliscə necədir?", options: ["how", "why", "who", "when"], correctIndex: 0, xp: 10, explanation: "«Necə» ingiliscə how olur." },
            { id: "en4-questions-wh-t6", type: "multiple_choice", prompt: "'Why?' sualına hansı sözlə cavab verilir?", options: ["Because", "And", "But", "So"], correctIndex: 0, xp: 10, explanation: "Why səbəbi soruşur, səbəb isə because sözü ilə bildirilir: «Because I am tired»." },
            { id: "en4-questions-wh-t7", type: "multiple_choice", prompt: "'Whose bag is this?' nə soruşur?", options: ["Sahibini", "Rəngini", "Yerini", "Qiymətini"], correctIndex: 0, xp: 10, explanation: "Whose = kimin. Deməli sual çantanın sahibini soruşur." },
            { id: "en4-questions-wh-t8", type: "multiple_choice", prompt: "'How old are you?' nə soruşur?", options: ["Yaşı", "Adı", "Boyu", "Ünvanı"], correctIndex: 0, xp: 10, explanation: "Old = yaş. Deməli «How old are you?» yaşı soruşur." },
            { id: "en4-questions-wh-t9", type: "multiple_choice", prompt: "'What time is it?' nə soruşur?", options: ["Saatı", "Yeri", "Adı", "Səbəbi"], correctIndex: 0, xp: 10, explanation: "Time = vaxt, saat. Deməli sual saatı soruşur." },
            { id: "en4-questions-wh-t10", type: "multiple_choice", prompt: "'How many?' nə soruşur?", options: ["Sayı", "Rəngi", "Yeri", "Vaxtı"], correctIndex: 0, xp: 10, explanation: "How many sayıla bilən şeylərin sayını soruşur." },
          ],
          bonusTasks: [
            { id: "en4-questions-wh-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Where do you live?", options: ["Harada yaşayırsan?", "Nə vaxt gəlirsən?", "Kimsən?", "Necəsən?"], correctIndex: 0, xp: 15, explanation: "Səsdə «Where do you live?» deyildi. Where = harada, live = yaşamaq." },
            { id: "en4-questions-wh-b2", type: "multiple_choice", prompt: "'How much?' hansı isimlərlə işlənir?", options: ["Sayıla bilməyən", "Sayıla bilən", "Yalnız cəm", "Yalnız tək"], correctIndex: 0, xp: 15, explanation: "How much sayıla bilməyən isimlərlə işlənir: how much water. Sayıla bilənlərlə isə how many." },
            { id: "en4-questions-wh-b3", type: "multiple_choice", prompt: "'Which one do you want?' nə soruşur?", options: ["Hansını istədiyini", "Nə istədiyini", "Niyə istədiyini", "Nə vaxt istədiyini"], correctIndex: 0, xp: 15, explanation: "Which verilmiş variantlardan seçim soruşur — «hansını»." },
            { id: "en4-questions-wh-b4", type: "multiple_choice", prompt: "Wh- sualına 'Yes/No' ilə cavab vermək olar?", options: ["Xeyr, məlumat lazımdır", "Bəli, həmişə", "Yalnız 'who' ilə", "Yalnız 'why' ilə"], correctIndex: 0, xp: 15, explanation: "Wh- sualları konkret məlumat istəyir (yer, vaxt, səbəb), ona görə «bəli/xeyr» cavabı kifayət etmir." },
          ],
        },
        {
          id: "en4-questions-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en4-questions-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
  ],
};
