// İngilis dili — 1-ci sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Salamlaşma  2) Ədədlər 1-10  3) Rənglər  4) Heyvanlar  5) Ailə  6) Məktəb və bədən.
// 1-ci sinif üçün suallar ÇOX SADƏ: şəkil-söz tanıma (emoji) + dinləmə. Oxu/qrammatika YOX.
// id prefiksi en1-*. speakOptions ilə uşaq İngiliscə sözü eşidir.

import type { Subject } from "../types";

export const english1: Subject = {
  slug: "ingilis-dili-1",
  name: "İngilis dili",
  grade: 1,
  icon: "E",
  color: "violet",
  units: [
    // ═══════════════ 1. Salamlaşma ═══════════════
    {
      id: "en1-hello",
      title: "Salamlaşma və tanışlıq",
      description: "Salam sözləri, dinləmə və məşq.",
      lessons: [
        {
          id: "en1-greetings-vocab",
          title: "Salam sözləri",
          intro: "İngiliscə salamlaşmağı öyrənək.",
          sections: [
            { heading: "Sözlər", body: "hello — salam, goodbye — sağ ol/əlvida, thank you — təşəkkür, please — zəhmət olmasa, yes — bəli, no — xeyr." },
          ],
          tasks: [
            { id: "en1-greetings-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'salam' İngiliscə necədir?", options: ["hello", "goodbye", "thank you", "please"], correctIndex: 0, xp: 10, explanation: "«Salam» ingiliscə hello olur — görüşəndə deyilən sözdür." },
            { id: "en1-greetings-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'sağ ol / əlvida' İngiliscə necədir?", options: ["goodbye", "hello", "yes", "no"], correctIndex: 0, xp: 10, explanation: "«Sağ ol / əlvida» ingiliscə goodbye olur — ayrılarkən deyilir." },
            { id: "en1-greetings-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'təşəkkür' İngiliscə necədir?", options: ["thank you", "please", "hello", "no"], correctIndex: 0, xp: 10, explanation: "«Təşəkkür» ingiliscə thank you olur — iki sözdən ibarətdir." },
            { id: "en1-greetings-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'bəli' İngiliscə necədir?", options: ["yes", "no", "hello", "please"], correctIndex: 0, xp: 10, explanation: "«Bəli» ingiliscə yes olur." },
            { id: "en1-greetings-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'xeyr' İngiliscə necədir?", options: ["no", "yes", "goodbye", "please"], correctIndex: 0, xp: 10, explanation: "«Xeyr» ingiliscə no olur." },
            { id: "en1-greetings-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'zəhmət olmasa' İngiliscə necədir?", options: ["please", "thank you", "hello", "yes"], correctIndex: 0, xp: 10, explanation: "«Zəhmət olmasa» ingiliscə please olur — xahiş edərkən işlədilir." },
            { id: "en1-greetings-vocab-t7", type: "multiple_choice", prompt: "'hello' nə deməkdir?", options: ["salam", "sağ ol", "təşəkkür", "xeyr"], correctIndex: 0, xp: 10, explanation: "Hello görüşmə sözüdür, azərbaycanca «salam» deməkdir." },
            { id: "en1-greetings-vocab-t8", type: "multiple_choice", prompt: "'thank you' nə deməkdir?", options: ["təşəkkür", "salam", "bəli", "xeyr"], correctIndex: 0, xp: 10, explanation: "Thank you minnətdarlıq bildirir, azərbaycanca «təşəkkür» deməkdir." },
            { id: "en1-greetings-vocab-t9", type: "multiple_choice", prompt: "'yes' nə deməkdir?", options: ["bəli", "xeyr", "salam", "sağ ol"], correctIndex: 0, xp: 10, explanation: "Yes təsdiq sözüdür, azərbaycanca «bəli» deməkdir." },
            { id: "en1-greetings-vocab-t10", type: "multiple_choice", prompt: "'no' nə deməkdir?", options: ["xeyr", "bəli", "salam", "təşəkkür"], correctIndex: 0, xp: 10, explanation: "No inkar sözüdür, azərbaycanca «xeyr» deməkdir." },
            { id: "en1-greetings-vocab-t11", type: "multiple_choice", prompt: "'goodbye' nə deməkdir?", options: ["sağ ol / əlvida", "salam", "bəli", "zəhmət olmasa"], correctIndex: 0, xp: 10, explanation: "Goodbye vidalaşma sözüdür, azərbaycanca «sağ ol, əlvida» deməkdir." },
            { id: "en1-greetings-vocab-t12", type: "multiple_choice", prompt: "'please' nə deməkdir?", options: ["zəhmət olmasa", "təşəkkür", "salam", "xeyr"], correctIndex: 0, xp: 10, explanation: "Please xahişi nəzakətli edir, azərbaycanca «zəhmət olmasa» deməkdir." },
            { id: "en1-greetings-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "Kimsə sənə kömək etdi. Nə deyərsən?", options: ["thank you", "goodbye", "no", "hello"], correctIndex: 0, xp: 10, explanation: "Köməyə görə minnətdarlıq bildiririk — ingiliscə bu, thank you olur." },
            { id: "en1-greetings-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "Səhər dostunu görəndə nə deyərsən?", options: ["hello", "goodbye", "no", "thank you"], correctIndex: 0, xp: 10, explanation: "Dostu görəndə salamlaşırıq — ingiliscə hello deyirik." },
            { id: "en1-greetings-vocab-t15", type: "multiple_choice", speakOptions: true, prompt: "Evə gedəndə nə deyərsən?", options: ["goodbye", "hello", "yes", "please"], correctIndex: 0, xp: 15, explanation: "Ayrılarkən vidalaşırıq — ingiliscə goodbye deyirik." },
          ],
          bonusTasks: [
            { id: "en1-greetings-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'good morning' nə deməkdir?", options: ["sabahın xeyir", "gecən xeyrə", "sağ ol", "salam"], correctIndex: 0, xp: 15, explanation: "Good = yaxşı, morning = səhər. Birlikdə «sabahın xeyir» deməkdir." },
            { id: "en1-greetings-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'good night' nə deməkdir?", options: ["gecən xeyrə", "sabahın xeyir", "salam", "təşəkkür"], correctIndex: 0, xp: 15, explanation: "Good = yaxşı, night = gecə. Birlikdə «gecən xeyrə» deməkdir." },
            { id: "en1-greetings-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'sorry' nə deməkdir?", options: ["üzr istəyirəm", "təşəkkür", "salam", "bəli"], correctIndex: 0, xp: 15, explanation: "Sorry üzr istəyəndə deyilir, azərbaycanca «üzr istəyirəm» deməkdir." },
            { id: "en1-greetings-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'What is your name?' nə deməkdir?", options: ["Adın nədir?", "Neçə yaşın var?", "Necəsən?", "Salam"], correctIndex: 0, xp: 15, explanation: "Name = ad. Deməli «What is your name?» — «Adın nədir?» deməkdir." },
            { id: "en1-greetings-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'How are you?' nə deməkdir?", options: ["Necəsən?", "Adın nədir?", "Sağ ol", "Salam"], correctIndex: 0, xp: 15, explanation: "How = necə. Deməli «How are you?» — «Necəsən?» deməkdir." },
          ],
        },
        {
          id: "en1-greetings-listen",
          title: "Dinləmə: salamlar",
          intro: "Sözü dinlə və mənasını seç.",
          sections: [
            { heading: "Necə işləyir?", body: "Səs düyməsinə bas, İngiliscə sözü dinlə, düzgün mənasını seç." },
          ],
          tasks: [
            { id: "en1-greetings-listen-t1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Hello", options: ["Salam", "Sağ ol", "Təşəkkür", "Xeyr"], correctIndex: 0, xp: 10, explanation: "Səsdə «Hello» deyildi — bu, «salam» deməkdir." },
            { id: "en1-greetings-listen-t2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Goodbye", options: ["Sağ ol / əlvida", "Salam", "Bəli", "Zəhmət olmasa"], correctIndex: 0, xp: 10, explanation: "Səsdə «Goodbye» deyildi — bu, «sağ ol, əlvida» deməkdir." },
            { id: "en1-greetings-listen-t3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Thank you", options: ["Təşəkkür", "Salam", "Xeyr", "Bəli"], correctIndex: 0, xp: 10, explanation: "Səsdə «Thank you» deyildi — bu, «təşəkkür» deməkdir." },
            { id: "en1-greetings-listen-t4", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Yes", options: ["Bəli", "Xeyr", "Salam", "Sağ ol"], correctIndex: 0, xp: 10, explanation: "Səsdə «Yes» deyildi — bu, «bəli» deməkdir." },
            { id: "en1-greetings-listen-t5", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "No", options: ["Xeyr", "Bəli", "Salam", "Təşəkkür"], correctIndex: 0, xp: 10, explanation: "Səsdə «No» deyildi — bu, «xeyr» deməkdir." },
            { id: "en1-greetings-listen-t6", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Please", options: ["Zəhmət olmasa", "Təşəkkür", "Salam", "Xeyr"], correctIndex: 0, xp: 10, explanation: "Səsdə «Please» deyildi — bu, «zəhmət olmasa» deməkdir." },
            { id: "en1-greetings-listen-t7", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Good morning", options: ["Sabahın xeyir", "Gecən xeyrə", "Salam", "Sağ ol"], correctIndex: 0, xp: 10, explanation: "Səsdə «Good morning» deyildi. Morning = səhər, deməli «sabahın xeyir»." },
            { id: "en1-greetings-listen-t8", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Good night", options: ["Gecən xeyrə", "Sabahın xeyir", "Salam", "Təşəkkür"], correctIndex: 0, xp: 10, explanation: "Səsdə «Good night» deyildi. Night = gecə, deməli «gecən xeyrə»." },
            { id: "en1-greetings-listen-t9", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Sorry", options: ["Üzr istəyirəm", "Təşəkkür", "Salam", "Bəli"], correctIndex: 0, xp: 10, explanation: "Səsdə «Sorry» deyildi — bu, «üzr istəyirəm» deməkdir." },
            { id: "en1-greetings-listen-t10", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Welcome", options: ["Xoş gəldin", "Sağ ol", "Salam", "Xeyr"], correctIndex: 0, xp: 10, explanation: "Səsdə «Welcome» deyildi — bu, «xoş gəldin» deməkdir." },
            { id: "en1-greetings-listen-t11", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Hi", options: ["Salam", "Sağ ol", "Bəli", "Xeyr"], correctIndex: 0, xp: 10, explanation: "Səsdə «Hi» deyildi — bu, hello kimi «salam» deməkdir, sadəcə daha qısa və dostyanadır." },
            { id: "en1-greetings-listen-t12", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "See you", options: ["Görüşərik", "Salam", "Təşəkkür", "Bəli"], correctIndex: 0, xp: 10, explanation: "Səsdə «See you» deyildi — hərfən «səni görərəm», yəni «görüşərik» deməkdir." },
            { id: "en1-greetings-listen-t13", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "My name is Ali", options: ["Mənim adım Alidir", "Sənin adın nədir", "Salam Ali", "Sağ ol Ali"], correctIndex: 0, xp: 10, explanation: "Səsdə «My name is Ali» deyildi. My = mənim, name = ad — deməli «Mənim adım Alidir»." },
            { id: "en1-greetings-listen-t14", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "How are you?", options: ["Necəsən?", "Adın nədir?", "Salam", "Sağ ol"], correctIndex: 0, xp: 10, explanation: "Səsdə «How are you?» deyildi — bu, «Necəsən?» deməkdir." },
            { id: "en1-greetings-listen-t15", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I am fine", options: ["Mən yaxşıyam", "Mən pisəm", "Salam", "Sağ ol"], correctIndex: 0, xp: 15, explanation: "Səsdə «I am fine» deyildi. Fine = yaxşı, deməli «Mən yaxşıyam»." },
          ],
          bonusTasks: [
            { id: "en1-greetings-listen-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Nice to meet you", options: ["Tanış olmağıma şadam", "Sağ ol", "Salam", "Necəsən"], correctIndex: 0, xp: 15, explanation: "Səsdə «Nice to meet you» deyildi — tanış olanda deyilir, «tanış olmağıma şadam» deməkdir." },
            { id: "en1-greetings-listen-b2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Good afternoon", options: ["Günortan xeyir", "Gecən xeyrə", "Sabahın xeyir", "Salam"], correctIndex: 0, xp: 15, explanation: "Səsdə «Good afternoon» deyildi. Afternoon = günorta, deməli «günortan xeyir»." },
            { id: "en1-greetings-listen-b3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "You are welcome", options: ["Dəyməz / buyur", "Sağ ol", "Salam", "Xeyr"], correctIndex: 0, xp: 15, explanation: "Səsdə «You are welcome» deyildi — «thank you»-ya cavabdır, «dəyməz, buyur» deməkdir." },
          ],
        },
        {
          id: "en1-hello-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en1-hello-mesq",
          title: "Məşq",
          intro: "Salam sözlərini birlikdə məşq edək!",
          sections: [
            { heading: "Yadına salaq", body: "Hello — Salam · Good morning — Sabahın xeyir · Goodbye — Sağ ol/Əlvida · Thank you — Təşəkkür · My name is... — Mənim adım..." },
          ],
          tasks: [
            { id: "en1-hello-mesq-t1", type: "multiple_choice", prompt: "'Hello' nə deməkdir?", options: ["Salam", "Sağ ol", "Təşəkkür", "Xeyr"], correctIndex: 0, xp: 10, explanation: "Hello görüşmə sözüdür — azərbaycanca «salam»." },
            { id: "en1-hello-mesq-t2", type: "multiple_choice", prompt: "'Goodbye' nə deməkdir?", options: ["Əlvida", "Salam", "Bəli", "Zəhmət olmasa"], correctIndex: 0, xp: 10, explanation: "Goodbye vidalaşma sözüdür — azərbaycanca «əlvida»." },
            { id: "en1-hello-mesq-t3", type: "multiple_choice", prompt: "'Thank you' nə deməkdir?", options: ["Təşəkkür edirəm", "Salam", "Əlvida", "Bağışlayın"], correctIndex: 0, xp: 10, explanation: "Thank you minnətdarlıq bildirir — azərbaycanca «təşəkkür edirəm»." },
            { id: "en1-hello-mesq-t4", type: "multiple_choice", speakOptions: true, prompt: "Səhər necə salamlaşırsan?", options: ["Good morning", "Good night", "Goodbye", "Thank you"], correctIndex: 0, xp: 10, explanation: "Morning = səhər. Səhər salamlaşarkən «Good morning» deyilir." },
            { id: "en1-hello-mesq-t5", type: "multiple_choice", speakOptions: true, prompt: "Gecə yatmağa gedəndə nə deyirsən?", options: ["Good night", "Good morning", "Hello", "Please"], correctIndex: 0, xp: 10, explanation: "Night = gecə. Yatmağa gedəndə «Good night» deyilir." },
            { id: "en1-hello-mesq-t6", type: "multiple_choice", prompt: "'What is your name?' nə soruşur?", options: ["Adını", "Yaşını", "Rəngini", "Evini"], correctIndex: 0, xp: 10, explanation: "Cümlədəki name sözü «ad» deməkdir — deməli bu sual adı soruşur." },
            { id: "en1-hello-mesq-t7", type: "multiple_choice", speakOptions: true, prompt: "«Mənim adım Ayan» — ingiliscə necə deyilir?", options: ["My name is Ayan", "Your name is Ayan", "I am name Ayan", "Name my Ayan"], correctIndex: 0, xp: 10, explanation: "Sözlərin sırası belədir: My (mənim) + name (adım) + is (dır) + Ayan. Digər variantlarda sıra pozulub." },
            { id: "en1-hello-mesq-t8", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Hello, my name is Tom.", options: ["Salam, mənim adım Tomdur.", "Sağ ol, Tom.", "Tom haradadır?", "Salam Tom, necəsən?"], correctIndex: 0, xp: 10, explanation: "Səsdə «Hello, my name is Tom.» deyildi — yəni «Salam, mənim adım Tomdur»." },
            { id: "en1-hello-mesq-t9", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Good morning!", options: ["Sabahın xeyir!", "Gecən xeyrə!", "Sağ ol!", "Salam!"], correctIndex: 0, xp: 10, explanation: "Səsdə «Good morning!» deyildi — bu, «Sabahın xeyir!» deməkdir." },
            { id: "en1-hello-mesq-t10", type: "multiple_choice", prompt: "'Please' nə deməkdir?", options: ["Zəhmət olmasa", "Təşəkkür", "Salam", "Bağışla"], correctIndex: 0, xp: 10, explanation: "Please xahişi nəzakətli edir — azərbaycanca «zəhmət olmasa»." },
          ],
          bonusTasks: [
            { id: "en1-hello-mesq-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "How are you?", options: ["Necəsən?", "Adın nədir?", "Haradasan?", "Neçə yaşın var?"], correctIndex: 0, xp: 15, explanation: "Səsdə «How are you?» deyildi — bu, «Necəsən?» deməkdir." },
            { id: "en1-hello-mesq-b2", type: "multiple_choice", speakOptions: true, prompt: "«Necəsən?» sualına cavab hansıdır?", options: ["I am fine", "My name is Ali", "Good morning", "Thank you"], correctIndex: 0, xp: 15, explanation: "«How are you?» halımızı soruşur. Fine = yaxşı, ona görə cavab «I am fine» olur." },
            { id: "en1-hello-mesq-b3", type: "fill_blank", prompt: "'Salam' — ingiliscə yaz (bir söz).", accepted: ["hello", "Hello", "hi", "Hi"], xp: 15, explanation: "«Salam» ingiliscə hello olur; qısa formada hi da deyilir." },
            { id: "en1-hello-mesq-b4", type: "multiple_choice", speakOptions: true, prompt: "Ayrılanda nə deyirsən?", options: ["Goodbye", "Hello", "Good morning", "Please"], correctIndex: 0, xp: 15, explanation: "Ayrılarkən vidalaşırıq — ingiliscə goodbye deyirik." },
            { id: "en1-hello-mesq-b5", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Thank you very much.", options: ["Çox sağ ol.", "Salam.", "Zəhmət olmasa.", "Görüşərik."], correctIndex: 0, xp: 15, explanation: "Səsdə «Thank you very much.» deyildi. Very much = çox, deməli «Çox sağ ol»." },
          ],
        },
        {
          id: "en1-hello-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    {
      id: "en1-numcolor",
      title: "Ədədlər və rənglər",
      description: "1-10 ədədləri, rənglər və məşq.",
      lessons: [
        {
          id: "en1-numbers-vocab",
          title: "Numbers 1-10",
          intro: "İngiliscə saymağı öyrənək.",
          sections: [
            { heading: "Sözlər", body: "one — 1, two — 2, three — 3, four — 4, five — 5, six — 6, seven — 7, eight — 8, nine — 9, ten — 10." },
          ],
          tasks: [
            { id: "en1-numbers-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'1' İngiliscə necədir?", options: ["one", "two", "three", "ten"], correctIndex: 0, xp: 10, explanation: "1 ingiliscə one olur." },
            { id: "en1-numbers-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'2' İngiliscə necədir?", options: ["two", "three", "one", "four"], correctIndex: 0, xp: 10, explanation: "2 ingiliscə two olur (oxunuşu «tu»)." },
            { id: "en1-numbers-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'3' İngiliscə necədir?", options: ["three", "two", "five", "six"], correctIndex: 0, xp: 10, explanation: "3 ingiliscə three olur." },
            { id: "en1-numbers-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'4' İngiliscə necədir?", options: ["four", "five", "one", "nine"], correctIndex: 0, xp: 10, explanation: "4 ingiliscə four olur." },
            { id: "en1-numbers-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'5' İngiliscə necədir?", options: ["five", "four", "six", "two"], correctIndex: 0, xp: 10, explanation: "5 ingiliscə five olur." },
            { id: "en1-numbers-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'6' İngiliscə necədir?", options: ["six", "seven", "five", "eight"], correctIndex: 0, xp: 10, explanation: "6 ingiliscə six olur." },
            { id: "en1-numbers-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'7' İngiliscə necədir?", options: ["seven", "six", "eight", "nine"], correctIndex: 0, xp: 10, explanation: "7 ingiliscə seven olur." },
            { id: "en1-numbers-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "'8' İngiliscə necədir?", options: ["eight", "nine", "seven", "ten"], correctIndex: 0, xp: 10, explanation: "8 ingiliscə eight olur (oxunuşu «eyt»)." },
            { id: "en1-numbers-vocab-t9", type: "multiple_choice", speakOptions: true, prompt: "'9' İngiliscə necədir?", options: ["nine", "eight", "ten", "six"], correctIndex: 0, xp: 10, explanation: "9 ingiliscə nine olur." },
            { id: "en1-numbers-vocab-t10", type: "multiple_choice", speakOptions: true, prompt: "'10' İngiliscə necədir?", options: ["ten", "nine", "one", "two"], correctIndex: 0, xp: 10, explanation: "10 ingiliscə ten olur." },
            { id: "en1-numbers-vocab-t11", type: "multiple_choice", prompt: "'three' hansı ədəddir?", options: ["3", "2", "4", "5"], correctIndex: 0, xp: 10, explanation: "Three ingiliscə 3 deməkdir." },
            { id: "en1-numbers-vocab-t12", type: "multiple_choice", prompt: "'seven' hansı ədəddir?", options: ["7", "6", "8", "9"], correctIndex: 0, xp: 10, explanation: "Seven ingiliscə 7 deməkdir." },
            { id: "en1-numbers-vocab-t13", type: "multiple_choice", prompt: "'ten' hansı ədəddir?", options: ["10", "1", "9", "2"], correctIndex: 0, xp: 10, explanation: "Ten ingiliscə 10 deməkdir." },
            { id: "en1-numbers-vocab-t14", type: "multiple_choice", prompt: "🍎🍎 — İngiliscə neçədir?", options: ["two", "one", "three", "four"], correctIndex: 0, xp: 10, explanation: "Şəkildə iki alma var, 2 isə ingiliscə two olur." },
            { id: "en1-numbers-vocab-t15", type: "multiple_choice", prompt: "⭐⭐⭐⭐⭐ — İngiliscə neçədir?", options: ["five", "four", "six", "three"], correctIndex: 0, xp: 15, explanation: "Ulduzları sayaq: 5 dənədir, 5 isə ingiliscə five olur." },
          ],
          bonusTasks: [
            { id: "en1-numbers-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'one' + 'one' = ?", options: ["two", "one", "three", "four"], correctIndex: 0, xp: 15, explanation: "One = 1. Deməli 1 + 1 = 2, 2 isə ingiliscə two olur." },
            { id: "en1-numbers-vocab-b2", type: "multiple_choice", prompt: "🐟🐟🐟 — İngiliscə neçədir?", options: ["three", "two", "four", "five"], correctIndex: 0, xp: 15, explanation: "Şəkildə üç balıq var, 3 isə ingiliscə three olur." },
            { id: "en1-numbers-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'eleven' hansı ədəddir?", options: ["11", "1", "12", "10"], correctIndex: 0, xp: 15, explanation: "Eleven ingiliscə 11 deməkdir." },
            { id: "en1-numbers-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'twelve' hansı ədəddir?", options: ["12", "2", "20", "10"], correctIndex: 0, xp: 15, explanation: "Twelve ingiliscə 12 deməkdir." },
            { id: "en1-numbers-vocab-b5", type: "multiple_choice", prompt: "'nine' hansı ədəddir?", options: ["9", "8", "7", "10"], correctIndex: 0, xp: 15, explanation: "Nine ingiliscə 9 deməkdir." },
          ],
        },
        {
          id: "en1-colors-vocab",
          title: "Colours",
          intro: "Rəngləri İngiliscə öyrənək.",
          sections: [
            { heading: "Sözlər", body: "red — qırmızı, blue — mavi, green — yaşıl, yellow — sarı, black — qara, white — ağ, orange — narıncı, pink — çəhrayı." },
          ],
          tasks: [
            { id: "en1-colors-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'qırmızı' İngiliscə necədir?", options: ["red", "blue", "green", "black"], correctIndex: 0, xp: 10, explanation: "«Qırmızı» ingiliscə red olur." },
            { id: "en1-colors-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'mavi' İngiliscə necədir?", options: ["blue", "red", "yellow", "white"], correctIndex: 0, xp: 10, explanation: "«Mavi» ingiliscə blue olur." },
            { id: "en1-colors-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'yaşıl' İngiliscə necədir?", options: ["green", "blue", "red", "pink"], correctIndex: 0, xp: 10, explanation: "«Yaşıl» ingiliscə green olur." },
            { id: "en1-colors-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'sarı' İngiliscə necədir?", options: ["yellow", "green", "orange", "white"], correctIndex: 0, xp: 10, explanation: "«Sarı» ingiliscə yellow olur." },
            { id: "en1-colors-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'qara' İngiliscə necədir?", options: ["black", "white", "blue", "red"], correctIndex: 0, xp: 10, explanation: "«Qara» ingiliscə black olur." },
            { id: "en1-colors-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'ağ' İngiliscə necədir?", options: ["white", "black", "green", "yellow"], correctIndex: 0, xp: 10, explanation: "«Ağ» ingiliscə white olur." },
            { id: "en1-colors-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'narıncı' İngiliscə necədir?", options: ["orange", "pink", "red", "yellow"], correctIndex: 0, xp: 10, explanation: "«Narıncı» ingiliscə orange olur — bu söz həm də portağal deməkdir." },
            { id: "en1-colors-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "'çəhrayı' İngiliscə necədir?", options: ["pink", "orange", "red", "blue"], correctIndex: 0, xp: 10, explanation: "«Çəhrayı» ingiliscə pink olur." },
            { id: "en1-colors-vocab-t9", type: "multiple_choice", prompt: "'red' nə rəngdir?", options: ["qırmızı", "mavi", "yaşıl", "sarı"], correctIndex: 0, xp: 10, explanation: "Red azərbaycanca «qırmızı» deməkdir." },
            { id: "en1-colors-vocab-t10", type: "multiple_choice", prompt: "'green' nə rəngdir?", options: ["yaşıl", "qırmızı", "qara", "ağ"], correctIndex: 0, xp: 10, explanation: "Green azərbaycanca «yaşıl» deməkdir." },
            { id: "en1-colors-vocab-t11", type: "multiple_choice", prompt: "'yellow' nə rəngdir?", options: ["sarı", "mavi", "narıncı", "çəhrayı"], correctIndex: 0, xp: 10, explanation: "Yellow azərbaycanca «sarı» deməkdir." },
            { id: "en1-colors-vocab-t12", type: "multiple_choice", prompt: "🍎 (alma) çox vaxt hansı rəngdədir?", options: ["red", "blue", "black", "white"], correctIndex: 0, xp: 10, explanation: "Alma adətən qırmızı olur, «qırmızı» isə ingiliscə red-dir." },
            { id: "en1-colors-vocab-t13", type: "multiple_choice", prompt: "🌿 (ot) hansı rəngdədir?", options: ["green", "red", "yellow", "pink"], correctIndex: 0, xp: 10, explanation: "Ot yaşıldır, «yaşıl» isə ingiliscə green-dir." },
            { id: "en1-colors-vocab-t14", type: "multiple_choice", prompt: "☀️ (günəş) çox vaxt hansı rəngdədir?", options: ["yellow", "blue", "black", "green"], correctIndex: 0, xp: 10, explanation: "Günəş sarı görünür, «sarı» isə ingiliscə yellow-dur." },
            { id: "en1-colors-vocab-t15", type: "multiple_choice", prompt: "'blue' nə rəngdir?", options: ["mavi", "qırmızı", "sarı", "qara"], correctIndex: 0, xp: 15, explanation: "Blue azərbaycanca «mavi» deməkdir." },
          ],
          bonusTasks: [
            { id: "en1-colors-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'brown' nə rəngdir?", options: ["qəhvəyi", "mavi", "sarı", "yaşıl"], correctIndex: 0, xp: 15, explanation: "Brown azərbaycanca «qəhvəyi» deməkdir." },
            { id: "en1-colors-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'purple' nə rəngdir?", options: ["bənövşəyi", "narıncı", "qırmızı", "ağ"], correctIndex: 0, xp: 15, explanation: "Purple azərbaycanca «bənövşəyi» deməkdir." },
            { id: "en1-colors-vocab-b3", type: "multiple_choice", prompt: "❄️ (qar) hansı rəngdədir?", options: ["white", "black", "red", "green"], correctIndex: 0, xp: 15, explanation: "Qar ağdır, «ağ» isə ingiliscə white-dır." },
            { id: "en1-colors-vocab-b4", type: "multiple_choice", prompt: "🌊 (dəniz) çox vaxt hansı rəngdədir?", options: ["blue", "red", "yellow", "pink"], correctIndex: 0, xp: 15, explanation: "Dəniz mavi görünür, «mavi» isə ingiliscə blue-dur." },
            { id: "en1-colors-vocab-b5", type: "multiple_choice", prompt: "'orange' nə rəngdir?", options: ["narıncı", "yaşıl", "mavi", "qara"], correctIndex: 0, xp: 15, explanation: "Orange azərbaycanca «narıncı» deməkdir." },
          ],
        },
        {
          id: "en1-numcolor-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en1-numcolor-mesq",
          title: "Məşq",
          intro: "Ədədləri və rəngləri birlikdə məşq edək!",
          sections: [
            { heading: "Yadına salaq", body: "one, two, three, four, five, six, seven, eight, nine, ten · red (qırmızı), blue (mavi), green (yaşıl), yellow (sarı), black (qara), white (ağ)" },
          ],
          tasks: [
            { id: "en1-numcolor-mesq-t1", type: "multiple_choice", speakOptions: true, prompt: "3 — ingiliscə necədir?", options: ["three", "two", "four", "five"], correctIndex: 0, xp: 10, explanation: "3 ingiliscə three olur." },
            { id: "en1-numcolor-mesq-t2", type: "multiple_choice", speakOptions: true, prompt: "7 — ingiliscə necədir?", options: ["seven", "six", "eight", "nine"], correctIndex: 0, xp: 10, explanation: "7 ingiliscə seven olur." },
            { id: "en1-numcolor-mesq-t3", type: "multiple_choice", prompt: "'ten' neçədir?", options: ["10", "2", "9", "3"], correctIndex: 0, xp: 10, explanation: "Ten ingiliscə 10 deməkdir." },
            { id: "en1-numcolor-mesq-t4", type: "multiple_choice", prompt: "'red' nə rəngdir?", options: ["qırmızı", "mavi", "yaşıl", "sarı"], correctIndex: 0, xp: 10, explanation: "Red azərbaycanca «qırmızı» deməkdir." },
            { id: "en1-numcolor-mesq-t5", type: "multiple_choice", prompt: "'blue' nə rəngdir?", options: ["mavi", "qırmızı", "qara", "ağ"], correctIndex: 0, xp: 10, explanation: "Blue azərbaycanca «mavi» deməkdir." },
            { id: "en1-numcolor-mesq-t6", type: "multiple_choice", speakOptions: true, prompt: "Yarpaq hansı rəngdədir?", options: ["green", "red", "black", "white"], correctIndex: 0, xp: 10, explanation: "Yarpaq yaşıldır, «yaşıl» isə ingiliscə green-dir." },
            { id: "en1-numcolor-mesq-t7", type: "multiple_choice", speakOptions: true, prompt: "Günəş hansı rəngdədir?", options: ["yellow", "blue", "green", "black"], correctIndex: 0, xp: 10, explanation: "Günəş sarı görünür, «sarı» isə ingiliscə yellow-dur." },
            { id: "en1-numcolor-mesq-t8", type: "listening", prompt: "Dinlə: neçədir?", audioText: "five", options: ["5", "4", "9", "1"], correctIndex: 0, xp: 10, explanation: "Səsdə «five» deyildi — bu, 5 deməkdir." },
            { id: "en1-numcolor-mesq-t9", type: "listening", prompt: "Dinlə və rəngi seç.", audioText: "This is a red apple.", options: ["Qırmızı alma", "Yaşıl alma", "Sarı alma", "Mavi alma"], correctIndex: 0, xp: 10, explanation: "Səsdə «This is a red apple.» deyildi. Red = qırmızı, apple = alma — deməli qırmızı alma." },
            { id: "en1-numcolor-mesq-t10", type: "fill_blank", prompt: "'iki' — ingiliscə yaz (bir söz).", accepted: ["two", "Two"], xp: 10, explanation: "«İki» ingiliscə two kimi yazılır." },
          ],
          bonusTasks: [
            { id: "en1-numcolor-mesq-b1", type: "multiple_choice", speakOptions: true, prompt: "one + two = ?", options: ["three", "two", "four", "five"], correctIndex: 0, xp: 15, explanation: "One = 1, two = 2. Deməli 1 + 2 = 3, 3 isə ingiliscə three olur." },
            { id: "en1-numcolor-mesq-b2", type: "listening", prompt: "Dinlə: neçə pişik?", audioText: "I have three cats.", options: ["3", "2", "4", "1"], correctIndex: 0, xp: 15, explanation: "Səsdə «I have three cats.» deyildi. Three = 3, cats = pişiklər — deməli 3 pişik." },
            { id: "en1-numcolor-mesq-b3", type: "fill_blank", prompt: "'qara' — ingiliscə yaz (bir söz).", accepted: ["black", "Black"], xp: 15, explanation: "«Qara» ingiliscə black kimi yazılır." },
            { id: "en1-numcolor-mesq-b4", type: "multiple_choice", prompt: "Qar hansı rəngdədir?", options: ["white", "black", "red", "green"], correctIndex: 0, xp: 15, explanation: "Qar ağdır, «ağ» isə ingiliscə white-dır." },
            { id: "en1-numcolor-mesq-b5", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The sky is blue.", options: ["Göy mavidir.", "Göy yaşıldır.", "Dəniz mavidir.", "Göy qaradır."], correctIndex: 0, xp: 15, explanation: "Səsdə «The sky is blue.» deyildi. Sky = göy, blue = mavi — deməli «Göy mavidir»." },
          ],
        },
        {
          id: "en1-numcolor-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    {
      id: "en1-animals",
      title: "Heyvanlar",
      description: "Heyvan adları, dinləmə və məşq.",
      lessons: [
        {
          id: "en1-animals-vocab",
          title: "Animals",
          intro: "Heyvanları İngiliscə öyrənək.",
          sections: [
            { heading: "Sözlər", body: "cat — pişik, dog — it, fish — balıq, bird — quş, cow — inək, horse — at, sheep — qoyun, lion — şir, bear — ayı, rabbit — dovşan." },
          ],
          tasks: [
            { id: "en1-animals-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "🐱 İngiliscə necədir?", options: ["cat", "dog", "fish", "bird"], correctIndex: 0, xp: 10, explanation: "🐱 pişikdir, «pişik» isə ingiliscə cat olur." },
            { id: "en1-animals-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "🐶 İngiliscə necədir?", options: ["dog", "cat", "cow", "horse"], correctIndex: 0, xp: 10, explanation: "🐶 itdir, «it» isə ingiliscə dog olur." },
            { id: "en1-animals-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "🐟 İngiliscə necədir?", options: ["fish", "bird", "cat", "lion"], correctIndex: 0, xp: 10, explanation: "🐟 balıqdır, «balıq» isə ingiliscə fish olur." },
            { id: "en1-animals-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "🐦 İngiliscə necədir?", options: ["bird", "fish", "dog", "bear"], correctIndex: 0, xp: 10, explanation: "🐦 quşdur, «quş» isə ingiliscə bird olur." },
            { id: "en1-animals-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "🐮 İngiliscə necədir?", options: ["cow", "horse", "sheep", "cat"], correctIndex: 0, xp: 10, explanation: "🐮 inəkdir, «inək» isə ingiliscə cow olur." },
            { id: "en1-animals-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "🐴 İngiliscə necədir?", options: ["horse", "cow", "dog", "lion"], correctIndex: 0, xp: 10, explanation: "🐴 atdır, «at» isə ingiliscə horse olur." },
            { id: "en1-animals-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "🦁 İngiliscə necədir?", options: ["lion", "bear", "cat", "dog"], correctIndex: 0, xp: 10, explanation: "🦁 şirdir, «şir» isə ingiliscə lion olur." },
            { id: "en1-animals-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "🐻 İngiliscə necədir?", options: ["bear", "lion", "rabbit", "cow"], correctIndex: 0, xp: 10, explanation: "🐻 ayıdır, «ayı» isə ingiliscə bear olur." },
            { id: "en1-animals-vocab-t9", type: "multiple_choice", speakOptions: true, prompt: "🐰 İngiliscə necədir?", options: ["rabbit", "bear", "cat", "fish"], correctIndex: 0, xp: 10, explanation: "🐰 dovşandır, «dovşan» isə ingiliscə rabbit olur." },
            { id: "en1-animals-vocab-t10", type: "multiple_choice", prompt: "'cat' nə deməkdir?", options: ["pişik", "it", "quş", "balıq"], correctIndex: 0, xp: 10, explanation: "Cat azərbaycanca «pişik» deməkdir." },
            { id: "en1-animals-vocab-t11", type: "multiple_choice", prompt: "'dog' nə deməkdir?", options: ["it", "pişik", "inək", "at"], correctIndex: 0, xp: 10, explanation: "Dog azərbaycanca «it» deməkdir." },
            { id: "en1-animals-vocab-t12", type: "multiple_choice", prompt: "'fish' nə deməkdir?", options: ["balıq", "quş", "pişik", "şir"], correctIndex: 0, xp: 10, explanation: "Fish azərbaycanca «balıq» deməkdir." },
            { id: "en1-animals-vocab-t13", type: "multiple_choice", prompt: "'lion' nə deməkdir?", options: ["şir", "ayı", "it", "at"], correctIndex: 0, xp: 10, explanation: "Lion azərbaycanca «şir» deməkdir." },
            { id: "en1-animals-vocab-t14", type: "multiple_choice", prompt: "'sheep' nə deməkdir?", options: ["qoyun", "inək", "at", "dovşan"], correctIndex: 0, xp: 10, explanation: "Sheep azərbaycanca «qoyun» deməkdir." },
            { id: "en1-animals-vocab-t15", type: "multiple_choice", prompt: "'bird' nə deməkdir?", options: ["quş", "balıq", "pişik", "ayı"], correctIndex: 0, xp: 15, explanation: "Bird azərbaycanca «quş» deməkdir." },
          ],
          bonusTasks: [
            { id: "en1-animals-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "🐘 İngiliscə necədir?", options: ["elephant", "lion", "bear", "horse"], correctIndex: 0, xp: 15, explanation: "🐘 fildir, «fil» isə ingiliscə elephant olur." },
            { id: "en1-animals-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "🐒 İngiliscə necədir?", options: ["monkey", "bear", "cat", "dog"], correctIndex: 0, xp: 15, explanation: "🐒 meymundur, «meymun» isə ingiliscə monkey olur." },
            { id: "en1-animals-vocab-b3", type: "multiple_choice", prompt: "'elephant' nə deməkdir?", options: ["fil", "şir", "ayı", "at"], correctIndex: 0, xp: 15, explanation: "Elephant azərbaycanca «fil» deməkdir." },
            { id: "en1-animals-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "🐭 İngiliscə necədir?", options: ["mouse", "cat", "rabbit", "bird"], correctIndex: 0, xp: 15, explanation: "🐭 siçandır, «siçan» isə ingiliscə mouse olur." },
            { id: "en1-animals-vocab-b5", type: "multiple_choice", prompt: "'horse' nə deməkdir?", options: ["at", "inək", "qoyun", "it"], correctIndex: 0, xp: 15, explanation: "Horse azərbaycanca «at» deməkdir." },
          ],
        },
        {
          id: "en1-animals-listen",
          title: "Dinləmə: heyvanlar",
          intro: "Sözü dinlə və mənasını seç.",
          sections: [
            { heading: "Necə işləyir?", body: "Səs düyməsinə bas, İngiliscə heyvan adını dinlə, düzgün mənasını seç." },
          ],
          tasks: [
            { id: "en1-animals-listen-t1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "cat", options: ["pişik", "it", "balıq", "quş"], correctIndex: 0, xp: 10, explanation: "Səsdə «cat» deyildi — bu, «pişik» deməkdir." },
            { id: "en1-animals-listen-t2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "dog", options: ["it", "pişik", "inək", "at"], correctIndex: 0, xp: 10, explanation: "Səsdə «dog» deyildi — bu, «it» deməkdir." },
            { id: "en1-animals-listen-t3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "fish", options: ["balıq", "quş", "şir", "ayı"], correctIndex: 0, xp: 10, explanation: "Səsdə «fish» deyildi — bu, «balıq» deməkdir." },
            { id: "en1-animals-listen-t4", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "bird", options: ["quş", "balıq", "pişik", "at"], correctIndex: 0, xp: 10, explanation: "Səsdə «bird» deyildi — bu, «quş» deməkdir." },
            { id: "en1-animals-listen-t5", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "cow", options: ["inək", "at", "qoyun", "it"], correctIndex: 0, xp: 10, explanation: "Səsdə «cow» deyildi — bu, «inək» deməkdir." },
            { id: "en1-animals-listen-t6", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "horse", options: ["at", "inək", "şir", "dovşan"], correctIndex: 0, xp: 10, explanation: "Səsdə «horse» deyildi — bu, «at» deməkdir." },
            { id: "en1-animals-listen-t7", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "lion", options: ["şir", "ayı", "pişik", "it"], correctIndex: 0, xp: 10, explanation: "Səsdə «lion» deyildi — bu, «şir» deməkdir." },
            { id: "en1-animals-listen-t8", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "bear", options: ["ayı", "şir", "dovşan", "inək"], correctIndex: 0, xp: 10, explanation: "Səsdə «bear» deyildi — bu, «ayı» deməkdir." },
            { id: "en1-animals-listen-t9", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "rabbit", options: ["dovşan", "ayı", "pişik", "quş"], correctIndex: 0, xp: 10, explanation: "Səsdə «rabbit» deyildi — bu, «dovşan» deməkdir." },
            { id: "en1-animals-listen-t10", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "sheep", options: ["qoyun", "inək", "at", "it"], correctIndex: 0, xp: 10, explanation: "Səsdə «sheep» deyildi — bu, «qoyun» deməkdir." },
            { id: "en1-animals-listen-t11", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "elephant", options: ["fil", "şir", "ayı", "at"], correctIndex: 0, xp: 10, explanation: "Səsdə «elephant» deyildi — bu, «fil» deməkdir." },
            { id: "en1-animals-listen-t12", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "monkey", options: ["meymun", "ayı", "pişik", "it"], correctIndex: 0, xp: 10, explanation: "Səsdə «monkey» deyildi — bu, «meymun» deməkdir." },
            { id: "en1-animals-listen-t13", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "mouse", options: ["siçan", "pişik", "quş", "balıq"], correctIndex: 0, xp: 10, explanation: "Səsdə «mouse» deyildi — bu, «siçan» deməkdir." },
            { id: "en1-animals-listen-t14", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "duck", options: ["ördək", "quş", "balıq", "toyuq"], correctIndex: 0, xp: 10, explanation: "Səsdə «duck» deyildi — bu, «ördək» deməkdir." },
            { id: "en1-animals-listen-t15", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The cat is small", options: ["Pişik kiçikdir", "Pişik böyükdür", "İt kiçikdir", "Pişik qaçır"], correctIndex: 0, xp: 15, explanation: "Səsdə «The cat is small» deyildi. Cat = pişik, small = kiçik — deməli «Pişik kiçikdir»." },
          ],
          bonusTasks: [
            { id: "en1-animals-listen-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The dog is big", options: ["İt böyükdür", "İt kiçikdir", "Pişik böyükdür", "İt qaçır"], correctIndex: 0, xp: 15, explanation: "Səsdə «The dog is big» deyildi. Dog = it, big = böyük — deməli «İt böyükdür»." },
            { id: "en1-animals-listen-b2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I have a cat", options: ["Mənim pişiyim var", "Mənim itim var", "Pişik gəldi", "Pişik yoxdur"], correctIndex: 0, xp: 15, explanation: "Səsdə «I have a cat» deyildi. Have = var, cat = pişik — deməli «Mənim pişiyim var»." },
            { id: "en1-animals-listen-b3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "chicken", options: ["toyuq", "ördək", "quş", "qaz"], correctIndex: 0, xp: 15, explanation: "Səsdə «chicken» deyildi — bu, «toyuq» deməkdir." },
          ],
        },
        {
          id: "en1-animals-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en1-animals-mesq",
          title: "Məşq",
          intro: "Heyvan adlarını məşq edək!",
          sections: [
            { heading: "Yadına salaq", body: "cat — pişik · dog — it · bird — quş · fish — balıq · cow — inək · horse — at · sheep — qoyun · rabbit — dovşan" },
          ],
          tasks: [
            { id: "en1-animals-mesq-t1", type: "multiple_choice", prompt: "'cat' nə deməkdir?", options: ["pişik", "it", "quş", "balıq"], correctIndex: 0, xp: 10, explanation: "Cat azərbaycanca «pişik» deməkdir." },
            { id: "en1-animals-mesq-t2", type: "multiple_choice", prompt: "'dog' nə deməkdir?", options: ["it", "pişik", "at", "inək"], correctIndex: 0, xp: 10, explanation: "Dog azərbaycanca «it» deməkdir." },
            { id: "en1-animals-mesq-t3", type: "multiple_choice", prompt: "'bird' nə deməkdir?", options: ["quş", "balıq", "dovşan", "qoyun"], correctIndex: 0, xp: 10, explanation: "Bird azərbaycanca «quş» deməkdir." },
            { id: "en1-animals-mesq-t4", type: "multiple_choice", prompt: "'fish' nə deməkdir?", options: ["balıq", "quş", "pişik", "at"], correctIndex: 0, xp: 10, explanation: "Fish azərbaycanca «balıq» deməkdir." },
            { id: "en1-animals-mesq-t5", type: "multiple_choice", speakOptions: true, prompt: "Süd verən heyvan hansıdır?", options: ["cow", "cat", "bird", "fish"], correctIndex: 0, xp: 10, explanation: "Süd verən heyvan inəkdir, «inək» isə ingiliscə cow olur." },
            { id: "en1-animals-mesq-t6", type: "multiple_choice", speakOptions: true, prompt: "Suda yaşayan heyvan hansıdır?", options: ["fish", "horse", "sheep", "dog"], correctIndex: 0, xp: 10, explanation: "Suda yaşayan heyvan balıqdır, «balıq» isə ingiliscə fish olur." },
            { id: "en1-animals-mesq-t7", type: "multiple_choice", speakOptions: true, prompt: "Uzun qulaqlı heyvan hansıdır?", options: ["rabbit", "cow", "fish", "bird"], correctIndex: 0, xp: 10, explanation: "Uzun qulaqlı heyvan dovşandır, «dovşan» isə ingiliscə rabbit olur." },
            { id: "en1-animals-mesq-t8", type: "listening", prompt: "Dinlə və heyvanı seç.", audioText: "I have a big dog.", options: ["it", "pişik", "quş", "at"], correctIndex: 0, xp: 10, explanation: "Səsdə «I have a big dog.» deyildi. Dog = it — deməli söhbət itdən gedir." },
            { id: "en1-animals-mesq-t9", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The cat is sleeping.", options: ["Pişik yatır.", "İt yatır.", "Pişik oynayır.", "Pişik yeyir."], correctIndex: 0, xp: 10, explanation: "Səsdə «The cat is sleeping.» deyildi. Cat = pişik, sleeping = yatır — deməli «Pişik yatır»." },
            { id: "en1-animals-mesq-t10", type: "fill_blank", prompt: "'quş' — ingiliscə yaz (bir söz).", accepted: ["bird", "Bird"], xp: 10, explanation: "«Quş» ingiliscə bird kimi yazılır." },
          ],
          bonusTasks: [
            { id: "en1-animals-mesq-b1", type: "multiple_choice", speakOptions: true, prompt: "Hansı heyvan uça bilir?", options: ["bird", "fish", "cow", "sheep"], correctIndex: 0, xp: 15, explanation: "Qanadı olan və uça bilən heyvan quşdur, «quş» isə ingiliscə bird olur." },
            { id: "en1-animals-mesq-b2", type: "listening", prompt: "Dinlə: neçə pişik?", audioText: "There are two cats.", options: ["2", "1", "3", "4"], correctIndex: 0, xp: 15, explanation: "Səsdə «There are two cats.» deyildi. Two = 2, cats = pişiklər — deməli 2 pişik." },
            { id: "en1-animals-mesq-b3", type: "fill_blank", prompt: "'balıq' — ingiliscə yaz (bir söz).", accepted: ["fish", "Fish"], xp: 15, explanation: "«Balıq» ingiliscə fish kimi yazılır." },
            { id: "en1-animals-mesq-b4", type: "multiple_choice", prompt: "«I like animals» nə deməkdir?", options: ["Mən heyvanları sevirəm.", "Heyvanlar məni sevir.", "Heyvanım var.", "Heyvanlar böyükdür."], correctIndex: 0, xp: 15, explanation: "Like = sevmək, animals = heyvanlar. Deməli «Mən heyvanları sevirəm»." },
            { id: "en1-animals-mesq-b5", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The dog is running.", options: ["İt qaçır.", "Pişik qaçır.", "İt yatır.", "İtlər qaçır."], correctIndex: 0, xp: 15, explanation: "Səsdə «The dog is running.» deyildi. Dog = it, running = qaçır — deməli «İt qaçır»." },
          ],
        },
        {
          id: "en1-animals-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    {
      id: "en1-famschool",
      title: "Ailə və məktəb",
      description: "Ailə üzvləri, məktəb əşyaları və məşq.",
      lessons: [
        {
          id: "en1-family-vocab",
          title: "Family",
          intro: "Ailə üzvlərini İngiliscə öyrənək.",
          sections: [
            { heading: "Sözlər", body: "mother — ana, father — ata, sister — bacı, brother — qardaş, grandmother — nənə, grandfather — baba, baby — körpə, family — ailə." },
          ],
          tasks: [
            { id: "en1-family-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'ana' İngiliscə necədir?", options: ["mother", "father", "sister", "brother"], correctIndex: 0, xp: 10, explanation: "«Ana» ingiliscə mother olur." },
            { id: "en1-family-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'ata' İngiliscə necədir?", options: ["father", "mother", "brother", "baby"], correctIndex: 0, xp: 10, explanation: "«Ata» ingiliscə father olur." },
            { id: "en1-family-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'bacı' İngiliscə necədir?", options: ["sister", "brother", "mother", "baby"], correctIndex: 0, xp: 10, explanation: "«Bacı» ingiliscə sister olur." },
            { id: "en1-family-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'qardaş' İngiliscə necədir?", options: ["brother", "sister", "father", "family"], correctIndex: 0, xp: 10, explanation: "«Qardaş» ingiliscə brother olur." },
            { id: "en1-family-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'nənə' İngiliscə necədir?", options: ["grandmother", "grandfather", "mother", "sister"], correctIndex: 0, xp: 10, explanation: "«Nənə» ingiliscə grandmother olur — grand + mother, yəni ananın anası." },
            { id: "en1-family-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'baba' İngiliscə necədir?", options: ["grandfather", "grandmother", "father", "brother"], correctIndex: 0, xp: 10, explanation: "«Baba» ingiliscə grandfather olur — grand + father, yəni atanın atası." },
            { id: "en1-family-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'körpə' İngiliscə necədir?", options: ["baby", "sister", "brother", "mother"], correctIndex: 0, xp: 10, explanation: "«Körpə» ingiliscə baby olur." },
            { id: "en1-family-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "'ailə' İngiliscə necədir?", options: ["family", "mother", "father", "baby"], correctIndex: 0, xp: 10, explanation: "«Ailə» ingiliscə family olur." },
            { id: "en1-family-vocab-t9", type: "multiple_choice", prompt: "'mother' nə deməkdir?", options: ["ana", "ata", "bacı", "qardaş"], correctIndex: 0, xp: 10, explanation: "Mother azərbaycanca «ana» deməkdir." },
            { id: "en1-family-vocab-t10", type: "multiple_choice", prompt: "'father' nə deməkdir?", options: ["ata", "ana", "baba", "körpə"], correctIndex: 0, xp: 10, explanation: "Father azərbaycanca «ata» deməkdir." },
            { id: "en1-family-vocab-t11", type: "multiple_choice", prompt: "'sister' nə deməkdir?", options: ["bacı", "qardaş", "ana", "nənə"], correctIndex: 0, xp: 10, explanation: "Sister azərbaycanca «bacı» deməkdir." },
            { id: "en1-family-vocab-t12", type: "multiple_choice", prompt: "'brother' nə deməkdir?", options: ["qardaş", "bacı", "ata", "baba"], correctIndex: 0, xp: 10, explanation: "Brother azərbaycanca «qardaş» deməkdir." },
            { id: "en1-family-vocab-t13", type: "multiple_choice", prompt: "'grandmother' nə deməkdir?", options: ["nənə", "baba", "ana", "bacı"], correctIndex: 0, xp: 10, explanation: "Grandmother azərbaycanca «nənə» deməkdir." },
            { id: "en1-family-vocab-t14", type: "multiple_choice", prompt: "'family' nə deməkdir?", options: ["ailə", "ana", "körpə", "qardaş"], correctIndex: 0, xp: 10, explanation: "Family azərbaycanca «ailə» deməkdir." },
            { id: "en1-family-vocab-t15", type: "multiple_choice", prompt: "'grandfather' nə deməkdir?", options: ["baba", "nənə", "ata", "qardaş"], correctIndex: 0, xp: 15, explanation: "Grandfather azərbaycanca «baba» deməkdir." },
          ],
          bonusTasks: [
            { id: "en1-family-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'This is my mother.' nə deməkdir?", options: ["Bu mənim anamdır.", "Bu mənim atamdır.", "Bu mənim bacımdır.", "Bu ailəmdir."], correctIndex: 0, xp: 15, explanation: "This is = budur, my = mənim, mother = ana. Deməli «Bu mənim anamdır»." },
            { id: "en1-family-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'I love my family.' nə deməkdir?", options: ["Ailəmi sevirəm.", "Anamı sevirəm.", "Ailəm böyükdür.", "Bu ailəmdir."], correctIndex: 0, xp: 15, explanation: "Love = sevmək, family = ailə. Deməli «Ailəmi sevirəm»." },
            { id: "en1-family-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'aunt' nə deməkdir?", options: ["xala/bibi", "əmi/dayı", "nənə", "baba"], correctIndex: 0, xp: 15, explanation: "Aunt azərbaycanca «xala» və ya «bibi» deməkdir — ingiliscə hər ikisi eyni sözlə ifadə olunur." },
            { id: "en1-family-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'uncle' nə deməkdir?", options: ["əmi/dayı", "xala/bibi", "baba", "qardaş"], correctIndex: 0, xp: 15, explanation: "Uncle azərbaycanca «əmi» və ya «dayı» deməkdir — ingiliscə hər ikisi eyni sözlə ifadə olunur." },
            { id: "en1-family-vocab-b5", type: "multiple_choice", prompt: "'baby' nə deməkdir?", options: ["körpə", "bacı", "ana", "nənə"], correctIndex: 0, xp: 15, explanation: "Baby azərbaycanca «körpə» deməkdir." },
          ],
        },
        {
          id: "en1-school-vocab",
          title: "School things",
          intro: "Məktəb əşyalarını İngiliscə öyrənək.",
          sections: [
            { heading: "Sözlər", body: "book — kitab, pen — qələm, pencil — karandaş, bag — çanta, desk — parta, teacher — müəllim, school — məktəb, chair — stul." },
          ],
          tasks: [
            { id: "en1-school-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'kitab' İngiliscə necədir?", options: ["book", "pen", "bag", "desk"], correctIndex: 0, xp: 10, explanation: "«Kitab» ingiliscə book olur." },
            { id: "en1-school-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'qələm' İngiliscə necədir?", options: ["pen", "book", "chair", "school"], correctIndex: 0, xp: 10, explanation: "«Qələm» ingiliscə pen olur." },
            { id: "en1-school-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'karandaş' İngiliscə necədir?", options: ["pencil", "pen", "bag", "book"], correctIndex: 0, xp: 10, explanation: "«Karandaş» ingiliscə pencil olur — pen sözünə oxşayır, amma fərqlidir." },
            { id: "en1-school-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'çanta' İngiliscə necədir?", options: ["bag", "book", "desk", "pen"], correctIndex: 0, xp: 10, explanation: "«Çanta» ingiliscə bag olur." },
            { id: "en1-school-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'müəllim' İngiliscə necədir?", options: ["teacher", "school", "book", "chair"], correctIndex: 0, xp: 10, explanation: "«Müəllim» ingiliscə teacher olur — teach (öyrətmək) sözündən yaranıb." },
            { id: "en1-school-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'məktəb' İngiliscə necədir?", options: ["school", "teacher", "desk", "bag"], correctIndex: 0, xp: 10, explanation: "«Məktəb» ingiliscə school olur." },
            { id: "en1-school-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'stul' İngiliscə necədir?", options: ["chair", "desk", "book", "pen"], correctIndex: 0, xp: 10, explanation: "«Stul» ingiliscə chair olur." },
            { id: "en1-school-vocab-t8", type: "multiple_choice", prompt: "'book' nə deməkdir?", options: ["kitab", "qələm", "çanta", "parta"], correctIndex: 0, xp: 10, explanation: "Book azərbaycanca «kitab» deməkdir." },
            { id: "en1-school-vocab-t9", type: "multiple_choice", prompt: "'pen' nə deməkdir?", options: ["qələm", "kitab", "stul", "məktəb"], correctIndex: 0, xp: 10, explanation: "Pen azərbaycanca «qələm» deməkdir." },
            { id: "en1-school-vocab-t10", type: "multiple_choice", prompt: "'teacher' nə deməkdir?", options: ["müəllim", "şagird", "kitab", "məktəb"], correctIndex: 0, xp: 10, explanation: "Teacher azərbaycanca «müəllim» deməkdir." },
            { id: "en1-school-vocab-t11", type: "multiple_choice", prompt: "'bag' nə deməkdir?", options: ["çanta", "kitab", "qələm", "stul"], correctIndex: 0, xp: 10, explanation: "Bag azərbaycanca «çanta» deməkdir." },
            { id: "en1-school-vocab-t12", type: "multiple_choice", speakOptions: true, prompt: "'baş' (bədən) İngiliscə necədir?", options: ["head", "hand", "eye", "foot"], correctIndex: 0, xp: 10, explanation: "«Baş» ingiliscə head olur." },
            { id: "en1-school-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "'əl' İngiliscə necədir?", options: ["hand", "head", "leg", "eye"], correctIndex: 0, xp: 10, explanation: "«Əl» ingiliscə hand olur." },
            { id: "en1-school-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'göz' İngiliscə necədir?", options: ["eye", "ear", "nose", "hand"], correctIndex: 0, xp: 10, explanation: "«Göz» ingiliscə eye olur." },
            { id: "en1-school-vocab-t15", type: "multiple_choice", prompt: "'school' nə deməkdir?", options: ["məktəb", "müəllim", "kitab", "çanta"], correctIndex: 0, xp: 15, explanation: "School azərbaycanca «məktəb» deməkdir." },
          ],
          bonusTasks: [
            { id: "en1-school-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'ayaq' İngiliscə necədir?", options: ["leg / foot", "hand", "head", "eye"], correctIndex: 0, xp: 15, explanation: "«Ayaq» ingiliscə leg (bütöv ayaq) və ya foot (pəncə) olur." },
            { id: "en1-school-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'burun' İngiliscə necədir?", options: ["nose", "ear", "eye", "mouth"], correctIndex: 0, xp: 15, explanation: "«Burun» ingiliscə nose olur." },
            { id: "en1-school-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'ağız' İngiliscə necədir?", options: ["mouth", "nose", "ear", "hand"], correctIndex: 0, xp: 15, explanation: "«Ağız» ingiliscə mouth olur." },
            { id: "en1-school-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'qulaq' İngiliscə necədir?", options: ["ear", "eye", "nose", "head"], correctIndex: 0, xp: 15, explanation: "«Qulaq» ingiliscə ear olur." },
            { id: "en1-school-vocab-b5", type: "multiple_choice", prompt: "'pencil' nə deməkdir?", options: ["karandaş", "qələm", "kitab", "çanta"], correctIndex: 0, xp: 15, explanation: "Pencil azərbaycanca «karandaş» deməkdir; qələm isə pen-dir." },
          ],
        },
        {
          id: "en1-famschool-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en1-famschool-mesq",
          title: "Məşq",
          intro: "Ailə və məktəb sözlərini məşq edək!",
          sections: [
            { heading: "Yadına salaq", body: "mother — ana · father — ata · sister — bacı · brother — qardaş · book — kitab · pen — qələm · bag — çanta · desk — parta" },
          ],
          tasks: [
            { id: "en1-famschool-mesq-t1", type: "multiple_choice", prompt: "'mother' nə deməkdir?", options: ["ana", "ata", "bacı", "qardaş"], correctIndex: 0, xp: 10, explanation: "Mother azərbaycanca «ana» deməkdir." },
            { id: "en1-famschool-mesq-t2", type: "multiple_choice", prompt: "'father' nə deməkdir?", options: ["ata", "ana", "baba", "qardaş"], correctIndex: 0, xp: 10, explanation: "Father azərbaycanca «ata» deməkdir." },
            { id: "en1-famschool-mesq-t3", type: "multiple_choice", prompt: "'sister' nə deməkdir?", options: ["bacı", "qardaş", "ana", "nənə"], correctIndex: 0, xp: 10, explanation: "Sister azərbaycanca «bacı» deməkdir." },
            { id: "en1-famschool-mesq-t4", type: "multiple_choice", prompt: "'book' nə deməkdir?", options: ["kitab", "qələm", "çanta", "parta"], correctIndex: 0, xp: 10, explanation: "Book azərbaycanca «kitab» deməkdir." },
            { id: "en1-famschool-mesq-t5", type: "multiple_choice", prompt: "'pen' nə deməkdir?", options: ["qələm", "kitab", "stul", "çanta"], correctIndex: 0, xp: 10, explanation: "Pen azərbaycanca «qələm» deməkdir." },
            { id: "en1-famschool-mesq-t6", type: "multiple_choice", speakOptions: true, prompt: "Məktəbə nə ilə kitab aparırsan?", options: ["bag", "pen", "desk", "book"], correctIndex: 0, xp: 10, explanation: "Kitabları çantada aparırıq, «çanta» isə ingiliscə bag olur." },
            { id: "en1-famschool-mesq-t7", type: "multiple_choice", speakOptions: true, prompt: "Sinifdə hansı əşyanın arxasında oturursan?", options: ["desk", "bag", "pen", "book"], correctIndex: 0, xp: 10, explanation: "Sinifdə partanın arxasında oturur və yazırıq; «parta» ingiliscə desk olur." },
            { id: "en1-famschool-mesq-t8", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "This is my mother.", options: ["Bu mənim anamdır.", "Bu mənim atamdır.", "Bu mənim bacımdır.", "Bu anadır."], correctIndex: 0, xp: 10, explanation: "Səsdə «This is my mother.» deyildi. My = mənim, mother = ana — deməli «Bu mənim anamdır»." },
            { id: "en1-famschool-mesq-t9", type: "listening", prompt: "Dinlə və əşyanı seç.", audioText: "I have a red pen.", options: ["qələm", "kitab", "çanta", "parta"], correctIndex: 0, xp: 10, explanation: "Səsdə «I have a red pen.» deyildi. Pen = qələm — deməli söhbət qələmdən gedir." },
            { id: "en1-famschool-mesq-t10", type: "fill_blank", prompt: "'kitab' — ingiliscə yaz (bir söz).", accepted: ["book", "Book"], xp: 10, explanation: "«Kitab» ingiliscə book kimi yazılır." },
          ],
          bonusTasks: [
            { id: "en1-famschool-mesq-b1", type: "multiple_choice", speakOptions: true, prompt: "«Bu mənim qardaşımdır» — ingiliscə hansıdır?", options: ["This is my brother", "This is my sister", "This my brother", "My brother is this"], correctIndex: 0, xp: 15, explanation: "Sözlərin sırası belədir: This is (budur) + my (mənim) + brother (qardaş). Digər variantlarda ya söz əskikdir, ya sıra pozulub." },
            { id: "en1-famschool-mesq-b2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "My father is a teacher.", options: ["Atam müəllimdir.", "Anam müəllimdir.", "Atam həkimdir.", "Müəllim atamdır."], correctIndex: 0, xp: 15, explanation: "Səsdə «My father is a teacher.» deyildi. Father = ata, teacher = müəllim — deməli «Atam müəllimdir»." },
            { id: "en1-famschool-mesq-b3", type: "fill_blank", prompt: "'çanta' — ingiliscə yaz (bir söz).", accepted: ["bag", "Bag"], xp: 15, explanation: "«Çanta» ingiliscə bag kimi yazılır." },
            { id: "en1-famschool-mesq-b4", type: "multiple_choice", prompt: "«I love my family» nə deməkdir?", options: ["Ailəmi sevirəm.", "Ailəm məni sevir.", "Ailəm böyükdür.", "Ailəmlə yaşayıram."], correctIndex: 0, xp: 15, explanation: "Love = sevmək, family = ailə. Deməli «Ailəmi sevirəm»." },
            { id: "en1-famschool-mesq-b5", type: "listening", prompt: "Dinlə: neçə kitab?", audioText: "I have four books.", options: ["4", "3", "5", "2"], correctIndex: 0, xp: 15, explanation: "Səsdə «I have four books.» deyildi. Four = 4 — deməli 4 kitab." },
          ],
        },
        {
          id: "en1-famschool-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    {
      id: "en1-body",
      title: "Bədən və geyim (Body & Clothes)",
      description: "Bədən üzvləri və geyim sözləri.",
      lessons: [
        {
          id: "en1-body-vocab",
          title: "Body parts",
          intro: "Bədən üzvlərinin adları.",
          sections: [
            { heading: "Sözlər", body: "head — baş, hand — əl, foot — ayaq, eye — göz, ear — qulaq, nose — burun, mouth — ağız, hair — saç." },
            { heading: "Cəm", body: "İki üzv olanda cəm işlənir: eyes, ears, hands, feet." },
          ],
          tasks: [
            { id: "en1-body-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'baş' İngiliscə necədir?", options: ["head", "hand", "hair", "heart"], correctIndex: 0, xp: 10, explanation: "«Baş» ingiliscə head olur. Hair = saç, hand = əl — onlarla qarışdırma." },
            { id: "en1-body-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'əl' İngiliscə necədir?", options: ["hand", "head", "leg", "foot"], correctIndex: 0, xp: 10, explanation: "«Əl» ingiliscə hand olur. Leg və foot isə ayaqdır." },
            { id: "en1-body-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'göz' İngiliscə necədir?", options: ["eye", "ear", "arm", "eye brow"], correctIndex: 0, xp: 10, explanation: "«Göz» ingiliscə eye olur. Ear = qulaq, arm = qol." },
            { id: "en1-body-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'qulaq' İngiliscə necədir?", options: ["ear", "eye", "arm", "hair"], correctIndex: 0, xp: 10, explanation: "«Qulaq» ingiliscə ear olur. Eye = göz, hair = saç." },
            { id: "en1-body-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'burun' İngiliscə necədir?", options: ["nose", "mouth", "neck", "knee"], correctIndex: 0, xp: 10, explanation: "«Burun» ingiliscə nose olur. Mouth = ağız, neck = boyun." },
            { id: "en1-body-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'ağız' İngiliscə necədir?", options: ["mouth", "nose", "mouse", "month"], correctIndex: 0, xp: 10, explanation: "«Ağız» ingiliscə mouth olur. Mouse = siçan, month = ay — yazılışı oxşasa da, mənası tamam fərqlidir." },
            { id: "en1-body-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'ayaq' İngiliscə necədir?", options: ["foot", "hand", "food", "fort"], correctIndex: 0, xp: 10, explanation: "«Ayaq» ingiliscə foot olur. Food = yemək — bir hərf fərqlə tam başqa sözdür." },
            { id: "en1-body-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "'saç' İngiliscə necədir?", options: ["hair", "hand", "here", "hear"], correctIndex: 0, xp: 10, explanation: "«Saç» ingiliscə hair olur. Hear = eşitmək, hand = əl." },
            { id: "en1-body-vocab-t9", type: "multiple_choice", prompt: "'two eyes' nə deməkdir?", options: ["iki göz", "bir göz", "iki qulaq", "iki əl"], correctIndex: 0, xp: 10, explanation: "Two = iki, eyes = gözlər. Deməli «iki göz»." },
            { id: "en1-body-vocab-t10", type: "multiple_choice", prompt: "'foot' sözünün cəmi hansıdır?", options: ["feet", "foots", "footes", "foot"], correctIndex: 0, xp: 10, explanation: "Foot sözünün cəmi qaydasızdır: sonuna -s əlavə olunmur, söz tamam dəyişir — feet." },
          ],
          bonusTasks: [
            { id: "en1-body-vocab-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "hand", options: ["əl", "baş", "ayaq", "göz"], correctIndex: 0, xp: 15, explanation: "Səsdə «hand» deyildi — bu, «əl» deməkdir." },
            { id: "en1-body-vocab-b2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "nose", options: ["burun", "ağız", "qulaq", "göz"], correctIndex: 0, xp: 15, explanation: "Səsdə «nose» deyildi — bu, «burun» deməkdir." },
            { id: "en1-body-vocab-b3", type: "multiple_choice", prompt: "'I have two hands.' nə deməkdir?", options: ["İki əlim var.", "İki ayağım var.", "Bir əlim var.", "Əlim yoxdur."], correctIndex: 0, xp: 15, explanation: "I have = mənim var, two = iki, hands = əllər. Deməli «İki əlim var»." },
            { id: "en1-body-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'diş' İngiliscə necədir?", options: ["tooth", "tongue", "toe", "top"], correctIndex: 0, xp: 15, explanation: "«Diş» ingiliscə tooth olur. Toe = ayaq barmağı, tongue = dil." },
          ],
        },
        {
          id: "en1-body-clothes",
          title: "Clothes",
          intro: "Geyim adları.",
          sections: [
            { heading: "Sözlər", body: "hat — papaq, shirt — köynək, shoes — ayaqqabı, socks — corab, coat — palto, dress — paltar." },
            { heading: "Cümlə", body: "'I am wearing a hat.' — Papaq geyinmişəm." },
          ],
          tasks: [
            { id: "en1-body-clothes-t1", type: "multiple_choice", speakOptions: true, prompt: "'papaq' İngiliscə necədir?", options: ["hat", "hut", "hot", "hand"], correctIndex: 0, xp: 10, explanation: "«Papaq» ingiliscə hat olur. Hot = isti, hut = daxma — səsi oxşasa da mənası fərqlidir." },
            { id: "en1-body-clothes-t2", type: "multiple_choice", speakOptions: true, prompt: "'köynək' İngiliscə necədir?", options: ["shirt", "short", "shoe", "skirt"], correctIndex: 0, xp: 10, explanation: "«Köynək» ingiliscə shirt olur. Skirt = yubka — cəmi bir hərf fərqlidir." },
            { id: "en1-body-clothes-t3", type: "multiple_choice", speakOptions: true, prompt: "'ayaqqabı' İngiliscə necədir?", options: ["shoes", "socks", "shirts", "shorts"], correctIndex: 0, xp: 10, explanation: "«Ayaqqabı» ingiliscə shoes olur — ayaqqabı cüt olduğu üçün həmişə cəm işlənir." },
            { id: "en1-body-clothes-t4", type: "multiple_choice", speakOptions: true, prompt: "'corab' İngiliscə necədir?", options: ["socks", "shoes", "rocks", "sacks"], correctIndex: 0, xp: 10, explanation: "«Corab» ingiliscə socks olur — corab da cüt olduğu üçün cəm işlənir." },
            { id: "en1-body-clothes-t5", type: "multiple_choice", speakOptions: true, prompt: "'palto' İngiliscə necədir?", options: ["coat", "cat", "cup", "cap"], correctIndex: 0, xp: 10, explanation: "«Palto» ingiliscə coat olur. Cap = kepka, cat = pişik." },
            { id: "en1-body-clothes-t6", type: "multiple_choice", prompt: "'I am wearing a hat.' nə deməkdir?", options: ["Papaq geyinmişəm.", "Papaq alıram.", "Papağım var.", "Papaq gözəldir."], correctIndex: 0, xp: 10, explanation: "I am wearing = geyinmişəm, a hat = papaq. Deməli «Papaq geyinmişəm»." },
            { id: "en1-body-clothes-t7", type: "multiple_choice", prompt: "Soyuq havada nə geyinirik?", options: ["a coat", "shorts", "sandals", "a swimsuit"], correctIndex: 0, xp: 10, explanation: "Palto qalın və isti geyimdir, ona görə soyuq havada a coat geyinirik. Shorts və sandals isti hava üçündür." },
            { id: "en1-body-clothes-t8", type: "multiple_choice", speakOptions: true, prompt: "'don / paltar' İngiliscə necədir?", options: ["dress", "press", "address", "desk"], correctIndex: 0, xp: 10, explanation: "«Don, paltar» ingiliscə dress olur. Desk = parta, address = ünvan." },
            { id: "en1-body-clothes-t9", type: "multiple_choice", prompt: "'shoes' sözü tək, yoxsa cəmdir?", options: ["Cəm", "Tək", "İkisi də", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "Shoes sözü -s ilə bitir və ayaqqabı cüt olduğu üçün cəmdir." },
            { id: "en1-body-clothes-t10", type: "multiple_choice", speakOptions: true, prompt: "'şalvar' İngiliscə necədir?", options: ["trousers", "towels", "tigers", "tables"], correctIndex: 0, xp: 10, explanation: "«Şalvar» ingiliscə trousers olur — iki balağı olduğu üçün cəm işlənir." },
          ],
          bonusTasks: [
            { id: "en1-body-clothes-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "shoes", options: ["ayaqqabı", "corab", "papaq", "köynək"], correctIndex: 0, xp: 15, explanation: "Səsdə «shoes» deyildi — bu, «ayaqqabı» deməkdir." },
            { id: "en1-body-clothes-b2", type: "multiple_choice", prompt: "'Put on your coat!' nə deməkdir?", options: ["Paltonu gey!", "Paltonu çıxart!", "Palto al!", "Palto gözəldir!"], correctIndex: 0, xp: 15, explanation: "Put on = geyin, your coat = paltonu. Deməli «Paltonu gey!». Çıxartmaq isə take off olardı." },
            { id: "en1-body-clothes-b3", type: "multiple_choice", speakOptions: true, prompt: "'əlcək' İngiliscə necədir?", options: ["gloves", "globes", "glasses", "grapes"], correctIndex: 0, xp: 15, explanation: "«Əlcək» ingiliscə gloves olur — əlcək cüt olduğu üçün cəm işlənir. Glasses = eynək." },
            { id: "en1-body-clothes-b4", type: "multiple_choice", prompt: "'What are you wearing?' nə soruşur?", options: ["Nə geyinmisən?", "Nə edirsən?", "Necəsən?", "Haradasan?"], correctIndex: 0, xp: 15, explanation: "Wearing = geyinmək. Deməli «What are you wearing?» — «Nə geyinmisən?» deməkdir." },
          ],
        },
        {
          id: "en1-body-listen",
          title: "Dinləmə: bədən və geyim",
          intro: "Sözü dinlə və mənasını seç.",
          sections: [
            { heading: "Necə işləyir?", body: "Səs düyməsinə bas, İngiliscə sözü dinlə, düzgün mənasını seç." },
          ],
          tasks: [
            { id: "en1-body-listen-t1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "head", options: ["baş", "əl", "ayaq", "göz"], correctIndex: 0, xp: 10, explanation: "Səsdə «head» deyildi — bu, «baş» deməkdir." },
            { id: "en1-body-listen-t2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "eye", options: ["göz", "qulaq", "burun", "ağız"], correctIndex: 0, xp: 10, explanation: "Səsdə «eye» deyildi — bu, «göz» deməkdir." },
            { id: "en1-body-listen-t3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "ear", options: ["qulaq", "göz", "saç", "əl"], correctIndex: 0, xp: 10, explanation: "Səsdə «ear» deyildi — bu, «qulaq» deməkdir." },
            { id: "en1-body-listen-t4", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "hat", options: ["papaq", "köynək", "corab", "palto"], correctIndex: 0, xp: 10, explanation: "Səsdə «hat» deyildi — bu, «papaq» deməkdir." },
            { id: "en1-body-listen-t5", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "socks", options: ["corab", "ayaqqabı", "papaq", "şalvar"], correctIndex: 0, xp: 10, explanation: "Səsdə «socks» deyildi — bu, «corab» deməkdir." },
            { id: "en1-body-listen-t6", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "coat", options: ["palto", "köynək", "papaq", "corab"], correctIndex: 0, xp: 10, explanation: "Səsdə «coat» deyildi — bu, «palto» deməkdir." },
            { id: "en1-body-listen-t7", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "mouth", options: ["ağız", "burun", "qulaq", "göz"], correctIndex: 0, xp: 10, explanation: "Səsdə «mouth» deyildi — bu, «ağız» deməkdir." },
            { id: "en1-body-listen-t8", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "hair", options: ["saç", "əl", "baş", "diş"], correctIndex: 0, xp: 10, explanation: "Səsdə «hair» deyildi — bu, «saç» deməkdir." },
            { id: "en1-body-listen-t9", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "foot", options: ["ayaq", "əl", "baş", "göz"], correctIndex: 0, xp: 10, explanation: "Səsdə «foot» deyildi — bu, «ayaq» deməkdir." },
            { id: "en1-body-listen-t10", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "shirt", options: ["köynək", "şalvar", "papaq", "ayaqqabı"], correctIndex: 0, xp: 10, explanation: "Səsdə «shirt» deyildi — bu, «köynək» deməkdir." },
          ],
          bonusTasks: [
            { id: "en1-body-listen-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "dress", options: ["paltar", "palto", "papaq", "corab"], correctIndex: 0, xp: 15, explanation: "Səsdə «dress» deyildi — bu, «paltar, don» deməkdir." },
            { id: "en1-body-listen-b2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "tooth", options: ["diş", "dil", "dodaq", "barmaq"], correctIndex: 0, xp: 15, explanation: "Səsdə «tooth» deyildi — bu, «diş» deməkdir." },
            { id: "en1-body-listen-b3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "gloves", options: ["əlcək", "corab", "papaq", "köynək"], correctIndex: 0, xp: 15, explanation: "Səsdə «gloves» deyildi — bu, «əlcək» deməkdir." },
            { id: "en1-body-listen-b4", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "trousers", options: ["şalvar", "köynək", "palto", "ayaqqabı"], correctIndex: 0, xp: 15, explanation: "Səsdə «trousers» deyildi — bu, «şalvar» deməkdir." },
          ],
        },
        {
          id: "en1-body-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en1-body-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    {
      id: "en1-food",
      title: "Yemək və meyvələr (Food & Fruits)",
      description: "Yemək, içki və meyvə adları.",
      lessons: [
        {
          id: "en1-food-fruit",
          title: "Fruits",
          intro: "Meyvə adları.",
          sections: [
            { heading: "Sözlər", body: "apple — alma, banana — banan, orange — portağal, grape — üzüm, pear — armud, melon — yemiş." },
            { heading: "Cümlə", body: "'I like apples.' — Alma xoşuma gəlir." },
          ],
          tasks: [
            { id: "en1-food-fruit-t1", type: "multiple_choice", speakOptions: true, prompt: "'alma' İngiliscə necədir?", options: ["apple", "orange", "banana", "pear"], correctIndex: 0, xp: 10, explanation: "«Alma» ingiliscə apple olur." },
            { id: "en1-food-fruit-t2", type: "multiple_choice", speakOptions: true, prompt: "'banan' İngiliscə necədir?", options: ["banana", "bandana", "balloon", "button"], correctIndex: 0, xp: 10, explanation: "«Banan» ingiliscə banana olur — sonunda əlavə -a var." },
            { id: "en1-food-fruit-t3", type: "multiple_choice", speakOptions: true, prompt: "'portağal' İngiliscə necədir?", options: ["orange", "apple", "onion", "olive"], correctIndex: 0, xp: 10, explanation: "«Portağal» ingiliscə orange olur — bu söz həm də narıncı rəngi bildirir. Onion = soğan." },
            { id: "en1-food-fruit-t4", type: "multiple_choice", speakOptions: true, prompt: "'üzüm' İngiliscə necədir?", options: ["grape", "grass", "great", "green"], correctIndex: 0, xp: 10, explanation: "«Üzüm» ingiliscə grape olur. Green = yaşıl, grass = ot." },
            { id: "en1-food-fruit-t5", type: "multiple_choice", speakOptions: true, prompt: "'armud' İngiliscə necədir?", options: ["pear", "peach", "pea", "pen"], correctIndex: 0, xp: 10, explanation: "«Armud» ingiliscə pear olur. Peach = şaftalı, pea = noxud." },
            { id: "en1-food-fruit-t6", type: "multiple_choice", prompt: "'I like apples.' nə deməkdir?", options: ["Alma xoşuma gəlir.", "Alma alıram.", "Alma yeyirəm.", "Almam var."], correctIndex: 0, xp: 10, explanation: "I like = xoşuma gəlir, apples = almalar. Deməli «Alma xoşuma gəlir»." },
            { id: "en1-food-fruit-t7", type: "multiple_choice", speakOptions: true, prompt: "'qarpız' İngiliscə necədir?", options: ["watermelon", "waterfall", "wall", "water"], correctIndex: 0, xp: 10, explanation: "«Qarpız» ingiliscə watermelon olur — water (su) + melon (yemiş), çünki suyu çoxdur." },
            { id: "en1-food-fruit-t8", type: "multiple_choice", speakOptions: true, prompt: "'çiyələk' İngiliscə necədir?", options: ["strawberry", "blueberry", "blackberry", "cherry"], correctIndex: 0, xp: 10, explanation: "«Çiyələk» ingiliscə strawberry olur. Cherry = gilas, blueberry = qaragilə." },
            { id: "en1-food-fruit-t9", type: "multiple_choice", prompt: "'fruit' nə deməkdir?", options: ["meyvə", "tərəvəz", "yemək", "içki"], correctIndex: 0, xp: 10, explanation: "Fruit azərbaycanca «meyvə» deməkdir. Tərəvəz isə vegetable-dır." },
            { id: "en1-food-fruit-t10", type: "multiple_choice", speakOptions: true, prompt: "'limon' İngiliscə necədir?", options: ["lemon", "melon", "lamp", "lion"], correctIndex: 0, xp: 10, explanation: "«Limon» ingiliscə lemon olur. Melon = yemiş — hərfləri oxşasa da fərqli meyvədir." },
          ],
          bonusTasks: [
            { id: "en1-food-fruit-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "apple", options: ["alma", "armud", "banan", "üzüm"], correctIndex: 0, xp: 15, explanation: "Səsdə «apple» deyildi — bu, «alma» deməkdir." },
            { id: "en1-food-fruit-b2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "banana", options: ["banan", "alma", "portağal", "üzüm"], correctIndex: 0, xp: 15, explanation: "Səsdə «banana» deyildi — bu, «banan» deməkdir." },
            { id: "en1-food-fruit-b3", type: "multiple_choice", prompt: "'Do you like grapes?' nə soruşur?", options: ["Üzüm xoşuna gəlir?", "Üzüm alırsan?", "Üzüm haradadır?", "Üzüm neçəyədir?"], correctIndex: 0, xp: 15, explanation: "Do you like...? = ...xoşuna gəlir?, grapes = üzüm. Deməli «Üzüm xoşuna gəlir?»" },
            { id: "en1-food-fruit-b4", type: "multiple_choice", speakOptions: true, prompt: "'gilas' İngiliscə necədir?", options: ["cherry", "berry", "curry", "carry"], correctIndex: 0, xp: 15, explanation: "«Gilas» ingiliscə cherry olur. Berry = giləmeyvə, carry = daşımaq." },
          ],
        },
        {
          id: "en1-food-drink",
          title: "Food & drinks",
          intro: "Yemək və içki adları.",
          sections: [
            { heading: "Sözlər", body: "bread — çörək, milk — süd, water — su, egg — yumurta, cheese — pendir, tea — çay." },
            { heading: "Cümlə", body: "'I want water, please.' — Su istəyirəm, zəhmət olmasa." },
          ],
          tasks: [
            { id: "en1-food-drink-t1", type: "multiple_choice", speakOptions: true, prompt: "'çörək' İngiliscə necədir?", options: ["bread", "break", "bird", "board"], correctIndex: 0, xp: 10, explanation: "«Çörək» ingiliscə bread olur. Break = qırmaq, bird = quş." },
            { id: "en1-food-drink-t2", type: "multiple_choice", speakOptions: true, prompt: "'süd' İngiliscə necədir?", options: ["milk", "silk", "mild", "meal"], correctIndex: 0, xp: 10, explanation: "«Süd» ingiliscə milk olur. Silk = ipək, meal = yemək." },
            { id: "en1-food-drink-t3", type: "multiple_choice", speakOptions: true, prompt: "'su' İngiliscə necədir?", options: ["water", "winter", "wetter", "waiter"], correctIndex: 0, xp: 10, explanation: "«Su» ingiliscə water olur. Winter = qış, waiter = ofisiant." },
            { id: "en1-food-drink-t4", type: "multiple_choice", speakOptions: true, prompt: "'yumurta' İngiliscə necədir?", options: ["egg", "leg", "edge", "eagle"], correctIndex: 0, xp: 10, explanation: "«Yumurta» ingiliscə egg olur. Leg = ayaq, eagle = qartal." },
            { id: "en1-food-drink-t5", type: "multiple_choice", speakOptions: true, prompt: "'pendir' İngiliscə necədir?", options: ["cheese", "chess", "cheer", "choose"], correctIndex: 0, xp: 10, explanation: "«Pendir» ingiliscə cheese olur. Chess = şahmat, choose = seçmək." },
            { id: "en1-food-drink-t6", type: "multiple_choice", speakOptions: true, prompt: "'çay' (içki) İngiliscə necədir?", options: ["tea", "tree", "toe", "tie"], correctIndex: 0, xp: 10, explanation: "İçki olan «çay» ingiliscə tea olur. Tree = ağac, tie = qalstuk." },
            { id: "en1-food-drink-t7", type: "multiple_choice", prompt: "'I want water, please.' nə deməkdir?", options: ["Su istəyirəm, zəhmət olmasa.", "Su içirəm.", "Su gətirdim.", "Su soyuqdur."], correctIndex: 0, xp: 10, explanation: "I want = istəyirəm, water = su, please = zəhmət olmasa. Deməli «Su istəyirəm, zəhmət olmasa»." },
            { id: "en1-food-drink-t8", type: "multiple_choice", prompt: "'breakfast' nə deməkdir?", options: ["səhər yeməyi", "nahar", "şam yeməyi", "qəlyanaltı"], correctIndex: 0, xp: 10, explanation: "Breakfast azərbaycanca «səhər yeməyi» deməkdir. Nahar = lunch, şam = dinner." },
            { id: "en1-food-drink-t9", type: "multiple_choice", speakOptions: true, prompt: "'şirə' İngiliscə necədir?", options: ["juice", "ice", "jam", "joy"], correctIndex: 0, xp: 10, explanation: "«Şirə» ingiliscə juice olur. Ice = buz, jam = mürəbbə." },
            { id: "en1-food-drink-t10", type: "multiple_choice", prompt: "'Thank you.' nə deməkdir?", options: ["Sağ ol.", "Zəhmət olmasa.", "Salam.", "Sağ ol, xudahafiz."], correctIndex: 0, xp: 10, explanation: "Thank you minnətdarlıq bildirir — azərbaycanca «sağ ol»." },
          ],
          bonusTasks: [
            { id: "en1-food-drink-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "milk", options: ["süd", "su", "çay", "şirə"], correctIndex: 0, xp: 15, explanation: "Səsdə «milk» deyildi — bu, «süd» deməkdir." },
            { id: "en1-food-drink-b2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "bread", options: ["çörək", "pendir", "yumurta", "süd"], correctIndex: 0, xp: 15, explanation: "Səsdə «bread» deyildi — bu, «çörək» deməkdir." },
            { id: "en1-food-drink-b3", type: "multiple_choice", prompt: "Nəzakətli xahiş üçün hansı söz işlənir?", options: ["please", "sorry", "hello", "bye"], correctIndex: 0, xp: 15, explanation: "Please xahişi nəzakətli edir. Sorry üzr, hello salam, bye isə vidalaşma sözüdür." },
            { id: "en1-food-drink-b4", type: "multiple_choice", speakOptions: true, prompt: "'düyü' İngiliscə necədir?", options: ["rice", "race", "rise", "nice"], correctIndex: 0, xp: 15, explanation: "«Düyü» ingiliscə rice olur. Nice = gözəl, race = yarış." },
          ],
        },
        {
          id: "en1-food-listen",
          title: "Dinləmə: yemək və meyvə",
          intro: "Sözü dinlə və mənasını seç.",
          sections: [
            { heading: "Necə işləyir?", body: "Səs düyməsinə bas, İngiliscə sözü dinlə, düzgün mənasını seç." },
          ],
          tasks: [
            { id: "en1-food-listen-t1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "water", options: ["su", "süd", "çay", "şirə"], correctIndex: 0, xp: 10, explanation: "Səsdə «water» deyildi — bu, «su» deməkdir." },
            { id: "en1-food-listen-t2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "egg", options: ["yumurta", "pendir", "çörək", "süd"], correctIndex: 0, xp: 10, explanation: "Səsdə «egg» deyildi — bu, «yumurta» deməkdir." },
            { id: "en1-food-listen-t3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "orange", options: ["portağal", "alma", "banan", "armud"], correctIndex: 0, xp: 10, explanation: "Səsdə «orange» deyildi — bu, «portağal» deməkdir." },
            { id: "en1-food-listen-t4", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "cheese", options: ["pendir", "çörək", "yumurta", "süd"], correctIndex: 0, xp: 10, explanation: "Səsdə «cheese» deyildi — bu, «pendir» deməkdir." },
            { id: "en1-food-listen-t5", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "grape", options: ["üzüm", "alma", "armud", "banan"], correctIndex: 0, xp: 10, explanation: "Səsdə «grape» deyildi — bu, «üzüm» deməkdir." },
            { id: "en1-food-listen-t6", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "tea", options: ["çay", "su", "süd", "şirə"], correctIndex: 0, xp: 10, explanation: "Səsdə «tea» deyildi — bu, içki olan «çay» deməkdir." },
            { id: "en1-food-listen-t7", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "pear", options: ["armud", "alma", "üzüm", "portağal"], correctIndex: 0, xp: 10, explanation: "Səsdə «pear» deyildi — bu, «armud» deməkdir." },
            { id: "en1-food-listen-t8", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "juice", options: ["şirə", "su", "süd", "çay"], correctIndex: 0, xp: 10, explanation: "Səsdə «juice» deyildi — bu, «şirə» deməkdir." },
            { id: "en1-food-listen-t9", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "rice", options: ["düyü", "çörək", "ət", "balıq"], correctIndex: 0, xp: 10, explanation: "Səsdə «rice» deyildi — bu, «düyü» deməkdir." },
            { id: "en1-food-listen-t10", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "lemon", options: ["limon", "yemiş", "alma", "banan"], correctIndex: 0, xp: 10, explanation: "Səsdə «lemon» deyildi — bu, «limon» deməkdir." },
          ],
          bonusTasks: [
            { id: "en1-food-listen-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "watermelon", options: ["qarpız", "yemiş", "üzüm", "armud"], correctIndex: 0, xp: 15, explanation: "Səsdə «watermelon» deyildi — bu, «qarpız» deməkdir." },
            { id: "en1-food-listen-b2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "strawberry", options: ["çiyələk", "gilas", "üzüm", "alma"], correctIndex: 0, xp: 15, explanation: "Səsdə «strawberry» deyildi — bu, «çiyələk» deməkdir." },
            { id: "en1-food-listen-b3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "breakfast", options: ["səhər yeməyi", "nahar", "şam", "qəlyanaltı"], correctIndex: 0, xp: 15, explanation: "Səsdə «breakfast» deyildi — bu, «səhər yeməyi» deməkdir." },
            { id: "en1-food-listen-b4", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "cherry", options: ["gilas", "çiyələk", "alma", "armud"], correctIndex: 0, xp: 15, explanation: "Səsdə «cherry» deyildi — bu, «gilas» deməkdir." },
          ],
        },
        {
          id: "en1-food-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en1-food-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
  ],
};
