// İngilis dili — 7-ci sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Past Simple vs Past Continuous  2) Past Perfect  3) Passive Voice
// 4) First Conditional  5) Modal verbs  6) Reported speech + tematik lüğət.
// Hər bölmə 3 dərs (rule/listen/write). Hər dərs 15 əsas + bonus. id prefiksi en7-*.

import type { Subject } from "../types";

export const english7: Subject = {
  slug: "ingilis-dili-7",
  name: "İngilis dili",
  grade: 7,
  icon: "E",
  color: "violet",
  units: [
    // ═══════════════ 1. Past Simple vs Past Continuous ═══════════════
    {
      id: "en7-past",
      title: "Past Simple vs Past Continuous",
      description: "Keçmiş sadə (bitmiş iş) və keçmiş davamedici (davam edən iş) zamanların müqayisəsi.",
      lessons: [
        {
          id: "en7-past-rule",
          title: "Qayda: Past Simple / Continuous",
          intro: "Past Simple bitmiş işi (V2), Past Continuous keçmişdə davam edən işi (was/were + V-ing) bildirir.",
          sections: [
            { heading: "Past Simple", body: "Keçmişdə bitmiş iş: I played, she went. Qaydalı feillərə -ed əlavə olunur (work → worked), qeyri-qaydalılar dəyişir (go → went, see → saw)." },
            { heading: "Past Continuous", body: "Keçmişdə müəyyən anda davam edən iş: was/were + V-ing. I was reading. They were playing. 'while' ilə işlənir." },
            { heading: "Birgə", body: "Uzun davam edən işi (Past Continuous) qısa iş (Past Simple) kəsir: I was sleeping when he called. (yatırdım — zəng etdi)." },
          ],
          tasks: [
            { id: "en7-past-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'I ___ football yesterday.' (play)", options: ["played", "was playing", "play", "playing"], correctIndex: 0, xp: 10 },
            { id: "en7-past-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'She ___ TV at 8 o'clock.' (davam edirdi — watch)", options: ["was watching", "watched", "watches", "watch"], correctIndex: 0, xp: 10 },
            { id: "en7-past-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'go' feilinin Past Simple forması?", options: ["went", "goed", "gone", "going"], correctIndex: 0, xp: 10 },
            { id: "en7-past-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "'They ___ when I arrived.' (davam edirdilər — study)", options: ["were studying", "studied", "study", "studies"], correctIndex: 0, xp: 10 },
            { id: "en7-past-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "Past Continuous necə düzəlir?", options: ["was/were + V-ing", "did + V", "V2", "have + V3"], correctIndex: 0, xp: 10 },
            { id: "en7-past-rule-t6", type: "multiple_choice", speakOptions: true, prompt: "'We ___ dinner when the phone rang.' (davam — have)", options: ["were having", "had", "have", "has"], correctIndex: 0, xp: 10 },
            { id: "en7-past-rule-t7", type: "multiple_choice", speakOptions: true, prompt: "'see' feilinin Past Simple forması?", options: ["saw", "seed", "seen", "sees"], correctIndex: 0, xp: 10 },
            { id: "en7-past-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'I ___ a book yesterday.' (bitmiş — read/V2)", options: ["read", "was reading", "reads", "reading"], correctIndex: 0, xp: 10 },
            { id: "en7-past-rule-t9", type: "multiple_choice", speakOptions: true, prompt: "'He was sleeping ___ I called.' (nə vaxt)", options: ["when", "while", "during", "since"], correctIndex: 0, xp: 10 },
            { id: "en7-past-rule-t10", type: "fill_blank", prompt: "'work' feilinin Past Simple formasını yaz.", accepted: ["worked"], xp: 10 },
            { id: "en7-past-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "'I' və 'she' ilə Past Continuous köməkçi feili?", options: ["was", "were", "did", "had"], correctIndex: 0, xp: 10 },
            { id: "en7-past-rule-t12", type: "multiple_choice", speakOptions: true, prompt: "'we', 'they', 'you' ilə Past Continuous köməkçi feili?", options: ["were", "was", "did", "has"], correctIndex: 0, xp: 10 },
            { id: "en7-past-rule-t13", type: "multiple_choice", speakOptions: true, prompt: "'What ___ you doing at 9pm?' (davam edən sual)", options: ["were", "was", "did", "are"], correctIndex: 0, xp: 10 },
            { id: "en7-past-rule-t14", type: "fill_blank", prompt: "'have' feilinin Past Simple formasını yaz.", accepted: ["had"], xp: 10 },
            { id: "en7-past-rule-t15", type: "multiple_choice", prompt: "Uzun işi qısa iş kəsir. Qısa iş hansı zamandadır?", options: ["Past Simple", "Past Continuous", "Present Simple", "Future"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en7-past-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "'While I ___, it started to rain.' (walk — davam)", options: ["was walking", "walked", "walk", "walks"], correctIndex: 0, xp: 15 },
            { id: "en7-past-rule-b2", type: "multiple_choice", speakOptions: true, prompt: "'take' feilinin Past Simple forması?", options: ["took", "taked", "taken", "takes"], correctIndex: 0, xp: 15 },
            { id: "en7-past-rule-b3", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'I ___ go to school yesterday.'", options: ["didn't", "wasn't", "don't", "haven't"], correctIndex: 0, xp: 15 },
            { id: "en7-past-rule-b4", type: "fill_blank", prompt: "'buy' feilinin Past Simple formasını yaz.", accepted: ["bought"], xp: 15 },
            { id: "en7-past-rule-b5", type: "multiple_choice", speakOptions: true, prompt: "'They ___ playing when the teacher came.' (davam)", options: ["were", "was", "did", "have"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en7-past-listen",
          title: "Dinləmə: Past tenses",
          intro: "Cümləni dinlə və mənasını seç.",
          sections: [
            { heading: "Necə işləyir?", body: "Səs düyməsinə bas, cümləni dinlə, düzgün Azərbaycanca tərcüməni seç." },
          ],
          tasks: [
            { id: "en7-past-listen-t1", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I played football yesterday.", options: ["Dünən futbol oynadım.", "Dünən futbol oynayırdım.", "Futbol oynayıram.", "Futbol oynayacağam."], correctIndex: 0, xp: 10 },
            { id: "en7-past-listen-t2", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "She was watching TV.", options: ["O televizora baxırdı.", "O televizora baxdı.", "O televizora baxır.", "O televizora baxacaq."], correctIndex: 0, xp: 10 },
            { id: "en7-past-listen-t3", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "They were studying when I arrived.", options: ["Mən çatanda onlar oxuyurdular.", "Mən çatanda onlar getdilər.", "Onlar oxudular.", "Onlar oxuyur."], correctIndex: 0, xp: 10 },
            { id: "en7-past-listen-t4", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "We had dinner at seven.", options: ["Biz yeddidə şam etdik.", "Biz şam edirdik.", "Biz şam edirik.", "Biz şam edəcəyik."], correctIndex: 0, xp: 10 },
            { id: "en7-past-listen-t5", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "It was raining all day.", options: ["Bütün gün yağış yağırdı.", "Bütün gün yağış yağdı.", "Yağış yağır.", "Yağış yağacaq."], correctIndex: 0, xp: 10 },
            { id: "en7-past-listen-t6", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I saw him yesterday.", options: ["Onu dünən gördüm.", "Onu görürəm.", "Onu görürdüm.", "Onu görəcəyəm."], correctIndex: 0, xp: 10 },
            { id: "en7-past-listen-t7", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "He was cooking when I came.", options: ["Mən gələndə o yemək bişirirdi.", "Mən gələndə o getdi.", "O yemək bişirdi.", "O yemək bişirir."], correctIndex: 0, xp: 10 },
            { id: "en7-past-listen-t8", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "She wrote a letter.", options: ["O məktub yazdı.", "O məktub yazırdı.", "O məktub yazır.", "O məktub oxudu."], correctIndex: 0, xp: 10 },
            { id: "en7-past-listen-t9", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "The children were playing outside.", options: ["Uşaqlar çöldə oynayırdılar.", "Uşaqlar çöldə oynadılar.", "Uşaqlar oynayır.", "Uşaqlar evdədir."], correctIndex: 0, xp: 10 },
            { id: "en7-past-listen-t10", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I went to the market.", options: ["Bazara getdim.", "Bazara gedirdim.", "Bazara gedirəm.", "Bazara gedəcəyəm."], correctIndex: 0, xp: 10 },
            { id: "en7-past-listen-t11", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "We were waiting for the bus.", options: ["Biz avtobusu gözləyirdik.", "Biz avtobusu gözlədik.", "Biz avtobusu gözləyirik.", "Avtobus gəldi."], correctIndex: 0, xp: 10 },
            { id: "en7-past-listen-t12", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "He didn't come to school.", options: ["O məktəbə gəlmədi.", "O məktəbə gəldi.", "O məktəbdədir.", "O gəlir."], correctIndex: 0, xp: 10 },
            { id: "en7-past-listen-t13", type: "listening", prompt: "Dinlə və sualın mənasını seç.", audioText: "What were you doing?", options: ["Nə edirdin?", "Nə etdin?", "Nə edirsən?", "Nə edəcəksən?"], correctIndex: 0, xp: 10 },
            { id: "en7-past-listen-t14", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I was reading when she called.", options: ["O zəng edəndə oxuyurdum.", "O zəng edəndə oxudum.", "Kitab oxuyuram.", "O zəng etdi."], correctIndex: 0, xp: 10 },
            { id: "en7-past-listen-t15", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "They arrived late.", options: ["Onlar gec çatdılar.", "Onlar gec çatırdılar.", "Onlar çatır.", "Onlar çatacaq."], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en7-past-listen-b1", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I was doing my homework all evening.", options: ["Bütün axşam ev tapşırığı edirdim.", "Ev tapşırığı etdim.", "Ev tapşırığı edirəm.", "Ev tapşırığım yoxdur."], correctIndex: 0, xp: 15 },
            { id: "en7-past-listen-b2", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "She was singing while cooking.", options: ["O bişirərkən oxuyurdu.", "O oxudu.", "O bişirdi.", "O oxuyur."], correctIndex: 0, xp: 15 },
            { id: "en7-past-listen-b3", type: "listening", prompt: "Dinlə və sualın mənasını seç.", audioText: "Where did you go last weekend?", options: ["Keçən həftəsonu hara getdin?", "Hara gedirsən?", "Hara gedəcəksən?", "Harada idin?"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en7-past-write",
          title: "Cümlə qur: Past tenses",
          intro: "Sözləri düzgün sıraya düz və keçmiş zaman cümləsi qur.",
          sections: [
            { heading: "Necə işləyir?", body: "Sözlərə sıra ilə bas. Past Simple: kim + V2. Past Continuous: kim + was/were + V-ing." },
          ],
          tasks: [
            { id: "en7-past-write-t1", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "played", "football"], answer: "I played football", translation: "Futbol oynadım.", xp: 10 },
            { id: "en7-past-write-t2", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["She", "was", "watching", "TV"], answer: "She was watching TV", translation: "O televizora baxırdı.", xp: 10 },
            { id: "en7-past-write-t3", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["We", "went", "to", "the", "park"], answer: "We went to the park", translation: "Parka getdik.", xp: 10 },
            { id: "en7-past-write-t4", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["They", "were", "playing", "outside"], answer: "They were playing outside", translation: "Onlar çöldə oynayırdılar.", xp: 10 },
            { id: "en7-past-write-t5", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "saw", "him", "yesterday"], answer: "I saw him yesterday", translation: "Onu dünən gördüm.", xp: 10 },
            { id: "en7-past-write-t6", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["He", "was", "cooking", "dinner"], answer: "He was cooking dinner", translation: "O şam bişirirdi.", xp: 10 },
            { id: "en7-past-write-t7", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["It", "was", "raining"], answer: "It was raining", translation: "Yağış yağırdı.", xp: 10 },
            { id: "en7-past-write-t8", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["She", "wrote", "a", "letter"], answer: "She wrote a letter", translation: "O məktub yazdı.", xp: 10 },
            { id: "en7-past-write-t9", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "was", "reading", "a", "book"], answer: "I was reading a book", translation: "Kitab oxuyurdum.", xp: 10 },
            { id: "en7-past-write-t10", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["We", "were", "waiting", "for", "the", "bus"], answer: "We were waiting for the bus", translation: "Avtobusu gözləyirdik.", xp: 10 },
            { id: "en7-past-write-t11", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["He", "didn't", "come"], answer: "He didn't come", translation: "O gəlmədi.", xp: 10 },
            { id: "en7-past-write-t12", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["They", "arrived", "late"], answer: "They arrived late", translation: "Onlar gec çatdılar.", xp: 10 },
            { id: "en7-past-write-t13", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "was", "sleeping", "when", "he", "called"], answer: "I was sleeping when he called", translation: "O zəng edəndə yatırdım.", xp: 10 },
            { id: "en7-past-write-t14", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["What", "did", "you", "do"], answer: "What did you do", translation: "Nə etdin?", xp: 10 },
            { id: "en7-past-write-t15", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["The", "children", "were", "sleeping"], answer: "The children were sleeping", translation: "Uşaqlar yatırdılar.", xp: 15 },
          ],
          bonusTasks: [
            { id: "en7-past-write-b1", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["While", "I", "was", "walking", "it", "rained"], answer: "While I was walking it rained", translation: "Mən gəzərkən yağış yağdı.", xp: 15 },
            { id: "en7-past-write-b2", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["She", "was", "singing", "beautifully"], answer: "She was singing beautifully", translation: "O gözəl oxuyurdu.", xp: 15 },
            { id: "en7-past-write-b3", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["We", "didn't", "watch", "the", "film"], answer: "We didn't watch the film", translation: "Filmə baxmadıq.", xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 2. Past Perfect ═══════════════
    {
      id: "en7-pastperf",
      title: "Past Perfect",
      description: "Keçmişdə başqa keçmiş işdən əvvəl bitmiş işi bildirən zaman (had + V3).",
      lessons: [
        {
          id: "en7-pastperf-rule",
          title: "Qayda: Past Perfect",
          intro: "had + V3. Keçmişdə iki işdən əvvəl olanı bildirir: When I arrived, the train had left.",
          sections: [
            { heading: "Necə düzəlir?", body: "had + feilin III forması (V3): I had finished, she had gone. Bütün şəxslərdə 'had' işlənir." },
            { heading: "Nə vaxt işlənir?", body: "Keçmişdə iki iş olub — birincisi (əvvəl bitən) Past Perfect, ikincisi Past Simple: The film had started when we arrived. (biz çatanda film başlamışdı)." },
          ],
          tasks: [
            { id: "en7-pastperf-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "Past Perfect necə düzəlir?", options: ["had + V3", "have + V3", "was + V-ing", "did + V"], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'When I arrived, the train ___.' (əvvəl getmişdi — leave)", options: ["had left", "left", "was leaving", "leaves"], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'She ___ finished before he came.' (əvvəl)", options: ["had", "have", "was", "did"], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "Past Perfect-də hansı köməkçi feil bütün şəxslərdə işlənir?", options: ["had", "has", "have", "was"], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "'eat' feilinin III forması?", options: ["eaten", "ate", "eating", "eats"], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-rule-t6", type: "multiple_choice", speakOptions: true, prompt: "'They ___ already eaten when I arrived.'", options: ["had", "have", "was", "did"], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-rule-t7", type: "multiple_choice", speakOptions: true, prompt: "'go' feilinin III forması?", options: ["gone", "went", "going", "goes"], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'The film ___ started when we came in.' (əvvəl başlamışdı)", options: ["had", "have", "was", "did"], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-rule-t9", type: "fill_blank", prompt: "'write' feilinin III (V3) formasını yaz.", accepted: ["written"], xp: 10 },
            { id: "en7-pastperf-rule-t10", type: "fill_blank", prompt: "'do' feilinin III (V3) formasını yaz.", accepted: ["done"], xp: 10 },
            { id: "en7-pastperf-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "İki keçmiş işdən əvvəl bitəni hansı zaman bildirir?", options: ["Past Perfect", "Past Simple", "Past Continuous", "Present Perfect"], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-rule-t12", type: "multiple_choice", speakOptions: true, prompt: "'I ___ never seen snow before that day.'", options: ["had", "have", "was", "did"], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-rule-t13", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'She ___ not finished her work.'", options: ["had", "have", "was", "did"], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-rule-t14", type: "fill_blank", prompt: "'see' feilinin III (V3) formasını yaz.", accepted: ["seen"], xp: 10 },
            { id: "en7-pastperf-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'By 9 o'clock, they ___ gone home.'", options: ["had", "have", "was", "did"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en7-pastperf-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "'After she ___ left, I called.' (əvvəl)", options: ["had", "have", "was", "did"], correctIndex: 0, xp: 15 },
            { id: "en7-pastperf-rule-b2", type: "fill_blank", prompt: "'break' feilinin III (V3) formasını yaz.", accepted: ["broken"], xp: 15 },
            { id: "en7-pastperf-rule-b3", type: "multiple_choice", speakOptions: true, prompt: "Sual: '___ you finished before he arrived?'", options: ["Had", "Have", "Did", "Was"], correctIndex: 0, xp: 15 },
            { id: "en7-pastperf-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "'I couldn't enter because I ___ lost my key.'", options: ["had", "have", "was", "did"], correctIndex: 0, xp: 15 },
            { id: "en7-pastperf-rule-b5", type: "fill_blank", prompt: "'take' feilinin III (V3) formasını yaz.", accepted: ["taken"], xp: 15 },
          ],
        },
        {
          id: "en7-pastperf-listen",
          title: "Dinləmə: Past Perfect",
          intro: "Cümləni dinlə və mənasını seç.",
          sections: [
            { heading: "Necə işləyir?", body: "Səs düyməsinə bas, cümləni dinlə, düzgün Azərbaycanca tərcüməni seç." },
          ],
          tasks: [
            { id: "en7-pastperf-listen-t1", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "The train had left when I arrived.", options: ["Mən çatanda qatar getmişdi.", "Mən çatanda qatar getdi.", "Qatar gedir.", "Qatar gələcək."], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-listen-t2", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "She had finished her homework.", options: ["O ev tapşırığını bitirmişdi.", "O ev tapşırığını bitirir.", "O ev tapşırığı edir.", "O bitirəcək."], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-listen-t3", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "They had already eaten.", options: ["Onlar artıq yemişdilər.", "Onlar indi yeyir.", "Onlar yeyəcək.", "Onlar yemədi."], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-listen-t4", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "The film had started when we came.", options: ["Biz gələndə film başlamışdı.", "Biz gələndə film başladı.", "Film başlayır.", "Film bitdi."], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-listen-t5", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I had never seen the sea before.", options: ["Əvvəllər heç dənizi görməmişdim.", "Dənizi görürəm.", "Dənizi gördüm.", "Dənizi görəcəyəm."], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-listen-t6", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "He had lost his keys.", options: ["O açarlarını itirmişdi.", "O açarlarını itirir.", "O açar tapdı.", "O açar aldı."], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-listen-t7", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "We had done our work before lunch.", options: ["Nahara qədər işimizi görmüşdük.", "Nahardan sonra işlədik.", "İşləyirik.", "İşləmədik."], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-listen-t8", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "She had written the letter.", options: ["O məktubu yazmışdı.", "O məktub yazır.", "O məktub oxudu.", "O məktub yazacaq."], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-listen-t9", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "By ten, they had gone home.", options: ["Ona qədər onlar evə getmişdilər.", "Onlar evdə idi.", "Onlar gedir.", "Onlar gələcək."], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-listen-t10", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I had read that book before.", options: ["O kitabı əvvəl oxumuşdum.", "O kitabı oxuyuram.", "O kitabı alıram.", "O kitabı görmədim."], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-listen-t11", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "The shop had closed.", options: ["Mağaza bağlanmışdı.", "Mağaza açıqdır.", "Mağaza açılır.", "Mağaza bağlanır."], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-listen-t12", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "He had already left.", options: ["O artıq getmişdi.", "O indi gedir.", "O qaldı.", "O gələcək."], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-listen-t13", type: "listening", prompt: "Dinlə və sualın mənasını seç.", audioText: "Had you finished before he came?", options: ["O gəlməzdən əvvəl bitirmişdin?", "Bitirdin?", "Bitirirsən?", "Bitirəcəksən?"], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-listen-t14", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "We had met before.", options: ["Biz əvvəl görüşmüşdük.", "Biz görüşürük.", "Biz görüşdük.", "Biz görüşəcəyik."], correctIndex: 0, xp: 10 },
            { id: "en7-pastperf-listen-t15", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "She had cooked dinner before we arrived.", options: ["Biz çatmazdan əvvəl o şam bişirmişdi.", "O şam bişirdi.", "O şam bişirir.", "O şam bişirəcək."], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en7-pastperf-listen-b1", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I couldn't get in because I had forgotten my key.", options: ["Açarımı unutduğum üçün girə bilmədim.", "Açarımı tapdım.", "Açarım var.", "Girdim."], correctIndex: 0, xp: 15 },
            { id: "en7-pastperf-listen-b2", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "After they had eaten, they went out.", options: ["Yedikdən sonra çölə çıxdılar.", "Çölə çıxıb yedilər.", "Yeyirlər.", "Çıxmadılar."], correctIndex: 0, xp: 15 },
            { id: "en7-pastperf-listen-b3", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "The game had ended by then.", options: ["O vaxta qədər oyun bitmişdi.", "Oyun başladı.", "Oyun gedir.", "Oyun bitir."], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en7-pastperf-write",
          title: "Cümlə qur: Past Perfect",
          intro: "Sözləri düzgün sıraya düz və Past Perfect cümləsi qur.",
          sections: [
            { heading: "Necə işləyir?", body: "Sözlərə sıra ilə bas. had + V3: I had finished." },
          ],
          tasks: [
            { id: "en7-pastperf-write-t1", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "had", "finished", "my", "work"], answer: "I had finished my work", translation: "İşimi bitirmişdim.", xp: 10 },
            { id: "en7-pastperf-write-t2", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["The", "train", "had", "left"], answer: "The train had left", translation: "Qatar getmişdi.", xp: 10 },
            { id: "en7-pastperf-write-t3", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["They", "had", "already", "eaten"], answer: "They had already eaten", translation: "Onlar artıq yemişdilər.", xp: 10 },
            { id: "en7-pastperf-write-t4", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["She", "had", "written", "a", "letter"], answer: "She had written a letter", translation: "O məktub yazmışdı.", xp: 10 },
            { id: "en7-pastperf-write-t5", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["He", "had", "lost", "his", "keys"], answer: "He had lost his keys", translation: "O açarlarını itirmişdi.", xp: 10 },
            { id: "en7-pastperf-write-t6", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["We", "had", "met", "before"], answer: "We had met before", translation: "Biz əvvəl görüşmüşdük.", xp: 10 },
            { id: "en7-pastperf-write-t7", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["The", "film", "had", "started"], answer: "The film had started", translation: "Film başlamışdı.", xp: 10 },
            { id: "en7-pastperf-write-t8", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "had", "seen", "it", "before"], answer: "I had seen it before", translation: "Onu əvvəl görmüşdüm.", xp: 10 },
            { id: "en7-pastperf-write-t9", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["They", "had", "gone", "home"], answer: "They had gone home", translation: "Onlar evə getmişdilər.", xp: 10 },
            { id: "en7-pastperf-write-t10", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["She", "had", "done", "her", "homework"], answer: "She had done her homework", translation: "O ev tapşırığını etmişdi.", xp: 10 },
            { id: "en7-pastperf-write-t11", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["The", "shop", "had", "closed"], answer: "The shop had closed", translation: "Mağaza bağlanmışdı.", xp: 10 },
            { id: "en7-pastperf-write-t12", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["He", "had", "already", "left"], answer: "He had already left", translation: "O artıq getmişdi.", xp: 10 },
            { id: "en7-pastperf-write-t13", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "had", "read", "that", "book"], answer: "I had read that book", translation: "O kitabı oxumuşdum.", xp: 10 },
            { id: "en7-pastperf-write-t14", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["We", "had", "cooked", "dinner"], answer: "We had cooked dinner", translation: "Şam bişirmişdik.", xp: 10 },
            { id: "en7-pastperf-write-t15", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["She", "had", "gone", "when", "I", "called"], answer: "She had gone when I called", translation: "Zəng edəndə o getmişdi.", xp: 15 },
          ],
          bonusTasks: [
            { id: "en7-pastperf-write-b1", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["After", "he", "had", "eaten", "he", "left"], answer: "After he had eaten he left", translation: "Yedikdən sonra getdi.", xp: 15 },
            { id: "en7-pastperf-write-b2", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "had", "never", "seen", "snow"], answer: "I had never seen snow", translation: "Heç qar görməmişdim.", xp: 15 },
            { id: "en7-pastperf-write-b3", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["They", "had", "finished", "before", "noon"], answer: "They had finished before noon", translation: "Günortadan əvvəl bitirmişdilər.", xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 3. Passive Voice ═══════════════
    {
      id: "en7-passive",
      title: "Passive Voice (Məchul növ)",
      description: "İşi kimin gördüyü deyil, işin özü əsas olduqda: be + V3 (is/was + V3).",
      lessons: [
        {
          id: "en7-passive-rule",
          title: "Qayda: Passive Voice",
          intro: "be + V3. Present: is/are + V3. Past: was/were + V3. 'The house was built.'",
          sections: [
            { heading: "Passive nədir?", body: "İşi görən deyil, işin obyekti önə çıxır. Active: They build houses. Passive: Houses are built. Düstur: be + feilin III forması (V3)." },
            { heading: "Present / Past passive", body: "Present Simple passive: is/are + V3 (Coffee is made here). Past Simple passive: was/were + V3 (The bridge was built in 1990)." },
            { heading: "'by' ilə icraçı", body: "İcraçını göstərmək lazım olsa 'by' işlənir: The book was written by him." },
          ],
          tasks: [
            { id: "en7-passive-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "Passive Voice necə düzəlir?", options: ["be + V3", "have + V3", "do + V", "was + V-ing"], correctIndex: 0, xp: 10 },
            { id: "en7-passive-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'The house ___ built in 1990.' (past passive)", options: ["was", "is", "did", "has"], correctIndex: 0, xp: 10 },
            { id: "en7-passive-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'Coffee ___ made here.' (present passive)", options: ["is", "was", "did", "has"], correctIndex: 0, xp: 10 },
            { id: "en7-passive-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "'The books ___ sold quickly.' (past passive, cəm)", options: ["were", "was", "is", "did"], correctIndex: 0, xp: 10 },
            { id: "en7-passive-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "'build' feilinin III forması?", options: ["built", "builded", "building", "builds"], correctIndex: 0, xp: 10 },
            { id: "en7-passive-rule-t6", type: "multiple_choice", speakOptions: true, prompt: "'The letter was written ___ Ali.' (icraçı)", options: ["by", "with", "from", "of"], correctIndex: 0, xp: 10 },
            { id: "en7-passive-rule-t7", type: "multiple_choice", speakOptions: true, prompt: "Active: 'They clean the room.' Passive: 'The room ___ cleaned.'", options: ["is", "are", "was", "did"], correctIndex: 0, xp: 10 },
            { id: "en7-passive-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'English ___ spoken here.' (present passive)", options: ["is", "was", "did", "has"], correctIndex: 0, xp: 10 },
            { id: "en7-passive-rule-t9", type: "fill_blank", prompt: "'make' feilinin III (V3) formasını yaz.", accepted: ["made"], xp: 10 },
            { id: "en7-passive-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "'The car ___ repaired yesterday.' (past passive)", options: ["was", "is", "are", "did"], correctIndex: 0, xp: 10 },
            { id: "en7-passive-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "'These cars ___ made in Japan.' (present passive, cəm)", options: ["are", "is", "was", "did"], correctIndex: 0, xp: 10 },
            { id: "en7-passive-rule-t12", type: "fill_blank", prompt: "'write' feilinin III (V3) formasını yaz.", accepted: ["written"], xp: 10 },
            { id: "en7-passive-rule-t13", type: "multiple_choice", speakOptions: true, prompt: "Passive-də hansı önə çıxır?", options: ["işin obyekti", "işi görən", "zaman", "yer"], correctIndex: 0, xp: 10 },
            { id: "en7-passive-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "'The window ___ broken.' (past passive)", options: ["was", "did", "has", "is doing"], correctIndex: 0, xp: 10 },
            { id: "en7-passive-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'The homework ___ done every day.' (present passive)", options: ["is", "was", "did", "were"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en7-passive-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "Active: 'Shakespeare wrote Hamlet.' Passive: 'Hamlet ___ written by Shakespeare.'", options: ["was", "is", "were", "did"], correctIndex: 0, xp: 15 },
            { id: "en7-passive-rule-b2", type: "fill_blank", prompt: "'take' feilinin III (V3) formasını yaz.", accepted: ["taken"], xp: 15 },
            { id: "en7-passive-rule-b3", type: "multiple_choice", speakOptions: true, prompt: "'Rice ___ grown in many countries.' (present passive)", options: ["is", "was", "did", "has"], correctIndex: 0, xp: 15 },
            { id: "en7-passive-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'The work ___ not finished yesterday.'", options: ["was", "did", "does", "is doing"], correctIndex: 0, xp: 15 },
            { id: "en7-passive-rule-b5", type: "fill_blank", prompt: "'give' feilinin III (V3) formasını yaz.", accepted: ["given"], xp: 15 },
          ],
        },
        {
          id: "en7-passive-listen",
          title: "Dinləmə: Passive Voice",
          intro: "Cümləni dinlə və mənasını seç.",
          sections: [
            { heading: "Necə işləyir?", body: "Səs düyməsinə bas, cümləni dinlə, düzgün Azərbaycanca tərcüməni seç." },
          ],
          tasks: [
            { id: "en7-passive-listen-t1", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "The house was built in 1990.", options: ["Ev 1990-cı ildə tikilib.", "Ev tikirlər.", "Evi tikəcəklər.", "Ev satıldı."], correctIndex: 0, xp: 10 },
            { id: "en7-passive-listen-t2", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "Coffee is made here.", options: ["Burada qəhvə hazırlanır.", "Qəhvə içirəm.", "Qəhvə aldım.", "Qəhvə bitdi."], correctIndex: 0, xp: 10 },
            { id: "en7-passive-listen-t3", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "English is spoken here.", options: ["Burada İngiliscə danışılır.", "İngiliscə danışıram.", "İngiliscə öyrənirəm.", "İngiliscə çətindir."], correctIndex: 0, xp: 10 },
            { id: "en7-passive-listen-t4", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "The car was repaired.", options: ["Maşın təmir olundu.", "Maşını təmir edirəm.", "Maşın sınıb.", "Maşın yenidir."], correctIndex: 0, xp: 10 },
            { id: "en7-passive-listen-t5", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "These cars are made in Japan.", options: ["Bu maşınlar Yaponiyada istehsal olunur.", "Maşın aldım.", "Maşın sürürəm.", "Maşınlar bahalıdır."], correctIndex: 0, xp: 10 },
            { id: "en7-passive-listen-t6", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "The letter was written by Ali.", options: ["Məktub Ali tərəfindən yazıldı.", "Ali məktub oxudu.", "Məktub gəldi.", "Ali yazır."], correctIndex: 0, xp: 10 },
            { id: "en7-passive-listen-t7", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "The room is cleaned every day.", options: ["Otaq hər gün təmizlənir.", "Otağı təmizləyirəm.", "Otaq təmizdir.", "Otaq böyükdür."], correctIndex: 0, xp: 10 },
            { id: "en7-passive-listen-t8", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "The window was broken.", options: ["Pəncərə sındırıldı.", "Pəncərəni sındırdım.", "Pəncərə açıqdır.", "Pəncərə təmizdir."], correctIndex: 0, xp: 10 },
            { id: "en7-passive-listen-t9", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "Rice is grown in many countries.", options: ["Düyü bir çox ölkədə becərilir.", "Düyü yeyirəm.", "Düyü aldım.", "Düyü bahalıdır."], correctIndex: 0, xp: 10 },
            { id: "en7-passive-listen-t10", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "The books were sold.", options: ["Kitablar satıldı.", "Kitab aldım.", "Kitab oxuyuram.", "Kitablar bahalıdır."], correctIndex: 0, xp: 10 },
            { id: "en7-passive-listen-t11", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "This song is loved by everyone.", options: ["Bu mahnını hamı sevir.", "Mahnı oxuyuram.", "Mahnı yenidir.", "Mahnı bitdi."], correctIndex: 0, xp: 10 },
            { id: "en7-passive-listen-t12", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "The bridge was built last year.", options: ["Körpü keçən il tikildi.", "Körpü tikilir.", "Körpü uzundur.", "Körpü təmir olunur."], correctIndex: 0, xp: 10 },
            { id: "en7-passive-listen-t13", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "Dinner is served at eight.", options: ["Şam yeməyi səkkizdə verilir.", "Şam etdim.", "Şam bişirirəm.", "Şam hazırdır."], correctIndex: 0, xp: 10 },
            { id: "en7-passive-listen-t14", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "The work was finished on time.", options: ["İş vaxtında bitirildi.", "İş bitmədi.", "İşləyirəm.", "İş çətindir."], correctIndex: 0, xp: 10 },
            { id: "en7-passive-listen-t15", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "The pictures were taken by a photographer.", options: ["Şəkillər fotoqraf tərəfindən çəkildi.", "Şəkil çəkdim.", "Şəkillər gözəldir.", "Fotoqraf gəldi."], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en7-passive-listen-b1", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "Hamlet was written by Shakespeare.", options: ["Hamlet Şekspir tərəfindən yazılıb.", "Şekspir oxudu.", "Hamlet gəldi.", "Şekspir yazır."], correctIndex: 0, xp: 15 },
            { id: "en7-passive-listen-b2", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "The homework is done every day.", options: ["Ev tapşırığı hər gün edilir.", "Ev tapşırığı etdim.", "Ev tapşırığım var.", "Ev tapşırığı çətindir."], correctIndex: 0, xp: 15 },
            { id: "en7-passive-listen-b3", type: "listening", prompt: "Dinlə və sualın mənasını seç.", audioText: "When was this school built?", options: ["Bu məktəb nə vaxt tikilib?", "Məktəb haradadır?", "Məktəb böyükdür?", "Məktəbə gedirsən?"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en7-passive-write",
          title: "Cümlə qur: Passive Voice",
          intro: "Sözləri düzgün sıraya düz və məchul növ cümləsi qur.",
          sections: [
            { heading: "Necə işləyir?", body: "Sözlərə sıra ilə bas. Passive: obyekt + be + V3 (+ by icraçı)." },
          ],
          tasks: [
            { id: "en7-passive-write-t1", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["The", "house", "was", "built"], answer: "The house was built", translation: "Ev tikildi.", xp: 10 },
            { id: "en7-passive-write-t2", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["Coffee", "is", "made", "here"], answer: "Coffee is made here", translation: "Burada qəhvə hazırlanır.", xp: 10 },
            { id: "en7-passive-write-t3", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["English", "is", "spoken", "here"], answer: "English is spoken here", translation: "Burada İngiliscə danışılır.", xp: 10 },
            { id: "en7-passive-write-t4", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["The", "car", "was", "repaired"], answer: "The car was repaired", translation: "Maşın təmir olundu.", xp: 10 },
            { id: "en7-passive-write-t5", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["These", "cars", "are", "made", "in", "Japan"], answer: "These cars are made in Japan", translation: "Bu maşınlar Yaponiyada istehsal olunur.", xp: 10 },
            { id: "en7-passive-write-t6", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["The", "letter", "was", "written", "by", "Ali"], answer: "The letter was written by Ali", translation: "Məktub Ali tərəfindən yazıldı.", xp: 10 },
            { id: "en7-passive-write-t7", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["The", "room", "is", "cleaned", "every", "day"], answer: "The room is cleaned every day", translation: "Otaq hər gün təmizlənir.", xp: 10 },
            { id: "en7-passive-write-t8", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["The", "window", "was", "broken"], answer: "The window was broken", translation: "Pəncərə sındırıldı.", xp: 10 },
            { id: "en7-passive-write-t9", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["The", "books", "were", "sold"], answer: "The books were sold", translation: "Kitablar satıldı.", xp: 10 },
            { id: "en7-passive-write-t10", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["The", "bridge", "was", "built", "last", "year"], answer: "The bridge was built last year", translation: "Körpü keçən il tikildi.", xp: 10 },
            { id: "en7-passive-write-t11", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["Dinner", "is", "served", "at", "eight"], answer: "Dinner is served at eight", translation: "Şam səkkizdə verilir.", xp: 10 },
            { id: "en7-passive-write-t12", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["Rice", "is", "grown", "here"], answer: "Rice is grown here", translation: "Burada düyü becərilir.", xp: 10 },
            { id: "en7-passive-write-t13", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["The", "work", "was", "finished"], answer: "The work was finished", translation: "İş bitirildi.", xp: 10 },
            { id: "en7-passive-write-t14", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["This", "song", "is", "loved"], answer: "This song is loved", translation: "Bu mahnı sevilir.", xp: 10 },
            { id: "en7-passive-write-t15", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["The", "photos", "were", "taken", "yesterday"], answer: "The photos were taken yesterday", translation: "Şəkillər dünən çəkildi.", xp: 15 },
          ],
          bonusTasks: [
            { id: "en7-passive-write-b1", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["Hamlet", "was", "written", "by", "Shakespeare"], answer: "Hamlet was written by Shakespeare", translation: "Hamlet Şekspir tərəfindən yazılıb.", xp: 15 },
            { id: "en7-passive-write-b2", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["The", "homework", "is", "done", "every", "day"], answer: "The homework is done every day", translation: "Ev tapşırığı hər gün edilir.", xp: 15 },
            { id: "en7-passive-write-b3", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["The", "cake", "was", "eaten"], answer: "The cake was eaten", translation: "Tort yeyildi.", xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 4. First Conditional ═══════════════
    {
      id: "en7-cond",
      title: "First Conditional (Şərt cümlələri)",
      description: "Real gələcək şərt: If + Present Simple, ... will + V. 'If it rains, we will stay home.'",
      lessons: [
        {
          id: "en7-cond-rule",
          title: "Qayda: First Conditional",
          intro: "If + Present Simple, will + feil. Gələcəkdə mümkün/real şərt.",
          sections: [
            { heading: "Quruluş", body: "If + Present Simple (şərt), will + feil (nəticə): If it rains, we will stay home. Şərt hissəsində gələcək olsa da Present Simple işlənir (will YOX)." },
            { heading: "Yer dəyişmə", body: "İki hissənin yeri dəyişə bilər: We will stay home if it rains. Əvvəldə if olsa vergül qoyulur, sonda olsa yox." },
          ],
          tasks: [
            { id: "en7-cond-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "First Conditional quruluşu?", options: ["If + Present, will + V", "If + will, Present", "If + past, would", "If + V-ing, will"], correctIndex: 0, xp: 10 },
            { id: "en7-cond-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'If it ___, we will stay home.' (rain)", options: ["rains", "will rain", "rained", "raining"], correctIndex: 0, xp: 10 },
            { id: "en7-cond-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'If you study, you ___ pass.' (nəticə)", options: ["will", "would", "are", "did"], correctIndex: 0, xp: 10 },
            { id: "en7-cond-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "Şərt hissəsində (if...) hansı zaman işlənir?", options: ["Present Simple", "will + V", "Past Simple", "Present Continuous"], correctIndex: 0, xp: 10 },
            { id: "en7-cond-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "'If she ___ time, she will help.' (have)", options: ["has", "will have", "had", "having"], correctIndex: 0, xp: 10 },
            { id: "en7-cond-rule-t6", type: "multiple_choice", speakOptions: true, prompt: "'If we ___ now, we will catch the bus.' (leave)", options: ["leave", "will leave", "left", "leaving"], correctIndex: 0, xp: 10 },
            { id: "en7-cond-rule-t7", type: "multiple_choice", speakOptions: true, prompt: "'I ___ call you if I finish early.' (nəticə)", options: ["will", "would", "am", "did"], correctIndex: 0, xp: 10 },
            { id: "en7-cond-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'If it ___ hot, we will go swimming.' (be)", options: ["is", "will be", "was", "being"], correctIndex: 0, xp: 10 },
            { id: "en7-cond-rule-t9", type: "multiple_choice", speakOptions: true, prompt: "First Conditional nəyi bildirir?", options: ["real gələcək şərt", "keçmiş şərt", "qeyri-real şərt", "adət"], correctIndex: 0, xp: 10 },
            { id: "en7-cond-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "'If you heat ice, it ___.' (melt — ümumi həqiqət)", options: ["melts", "will melt", "melted", "melting"], correctIndex: 0, xp: 10 },
            { id: "en7-cond-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "'If he ___ hard, he will succeed.' (work)", options: ["works", "will work", "worked", "working"], correctIndex: 0, xp: 10 },
            { id: "en7-cond-rule-t12", type: "multiple_choice", speakOptions: true, prompt: "İf cümlə əvvəldə olanda hansı işarə qoyulur?", options: ["vergül (,)", "nöqtə (.)", "sual (?)", "heç bir"], correctIndex: 0, xp: 10 },
            { id: "en7-cond-rule-t13", type: "fill_blank", prompt: "Boşluğu doldur: 'If I ___ (see) him, I will tell him.' (Present Simple)", accepted: ["see"], xp: 10 },
            { id: "en7-cond-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "'We will be late if we ___ hurry.' (not)", options: ["don't", "won't", "didn't", "aren't"], correctIndex: 0, xp: 10 },
            { id: "en7-cond-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'If they ___, we will win.' (help)", options: ["help", "will help", "helped", "helping"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en7-cond-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "'If you don't hurry, you ___ miss the train.'", options: ["will", "would", "are", "did"], correctIndex: 0, xp: 15 },
            { id: "en7-cond-rule-b2", type: "fill_blank", prompt: "'If it rains, I ___ (stay) home.' (will + feil, tam yaz: 'will stay')", accepted: ["will stay"], xp: 15 },
            { id: "en7-cond-rule-b3", type: "multiple_choice", speakOptions: true, prompt: "'What will you do if it ___?' (rain)", options: ["rains", "will rain", "rained", "raining"], correctIndex: 0, xp: 15 },
            { id: "en7-cond-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "'If she calls, I ___ answer.'", options: ["will", "would", "am", "did"], correctIndex: 0, xp: 15 },
            { id: "en7-cond-rule-b5", type: "multiple_choice", speakOptions: true, prompt: "'You will be tired if you ___ sleep.' (not)", options: ["don't", "won't", "didn't", "aren't"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en7-cond-listen",
          title: "Dinləmə: First Conditional",
          intro: "Cümləni dinlə və mənasını seç.",
          sections: [
            { heading: "Necə işləyir?", body: "Səs düyməsinə bas, cümləni dinlə, düzgün Azərbaycanca tərcüməni seç." },
          ],
          tasks: [
            { id: "en7-cond-listen-t1", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "If it rains, we will stay home.", options: ["Yağış yağsa, evdə qalarıq.", "Yağış yağdı.", "Evdəyik.", "Yağış yağmır."], correctIndex: 0, xp: 10 },
            { id: "en7-cond-listen-t2", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "If you study, you will pass.", options: ["Oxusan, keçəcəksən.", "Oxudun.", "Keçdin.", "Oxumursan."], correctIndex: 0, xp: 10 },
            { id: "en7-cond-listen-t3", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "If we leave now, we will catch the bus.", options: ["İndi çıxsaq, avtobusa çatarıq.", "Avtobusa çatdıq.", "İndi çıxdıq.", "Avtobus getdi."], correctIndex: 0, xp: 10 },
            { id: "en7-cond-listen-t4", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "If she has time, she will help.", options: ["Vaxtı olsa, kömək edəcək.", "O kömək etdi.", "Vaxtı var.", "Kömək etmir."], correctIndex: 0, xp: 10 },
            { id: "en7-cond-listen-t5", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I will call you if I finish early.", options: ["Tez bitirsəm, sənə zəng edəcəyəm.", "Zəng etdim.", "Bitirdim.", "Zəng etmirəm."], correctIndex: 0, xp: 10 },
            { id: "en7-cond-listen-t6", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "If it is hot, we will go swimming.", options: ["İsti olsa, üzməyə gedəcəyik.", "İstidir.", "Üzdük.", "Getmirik."], correctIndex: 0, xp: 10 },
            { id: "en7-cond-listen-t7", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "If you don't hurry, you will be late.", options: ["Tələsməsən, gecikəcəksən.", "Gecikdin.", "Tələsdin.", "Vaxtında gəldin."], correctIndex: 0, xp: 10 },
            { id: "en7-cond-listen-t8", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "If he works hard, he will succeed.", options: ["Çox çalışsa, uğur qazanacaq.", "O çalışdı.", "Uğur qazandı.", "Çalışmır."], correctIndex: 0, xp: 10 },
            { id: "en7-cond-listen-t9", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "If they help, we will win.", options: ["Kömək etsələr, udacağıq.", "Kömək etdilər.", "Udduq.", "Kömək etmirlər."], correctIndex: 0, xp: 10 },
            { id: "en7-cond-listen-t10", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "If you heat ice, it melts.", options: ["Buzu qızdırsan, əriyir.", "Buz əridi.", "Buz soyuqdur.", "Buz var."], correctIndex: 0, xp: 10 },
            { id: "en7-cond-listen-t11", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "We will have a picnic if the weather is nice.", options: ["Hava yaxşı olsa, piknik edəcəyik.", "Piknik etdik.", "Hava yaxşıdır.", "Piknik yoxdur."], correctIndex: 0, xp: 10 },
            { id: "en7-cond-listen-t12", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "If I see him, I will tell him.", options: ["Onu görsəm, deyəcəyəm.", "Onu gördüm.", "Ona dedim.", "Onu görmürəm."], correctIndex: 0, xp: 10 },
            { id: "en7-cond-listen-t13", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "She will be happy if you come.", options: ["Sən gəlsən, o sevinəcək.", "O sevindi.", "Sən gəldin.", "O gəlmir."], correctIndex: 0, xp: 10 },
            { id: "en7-cond-listen-t14", type: "listening", prompt: "Dinlə və sualın mənasını seç.", audioText: "What will you do if it rains?", options: ["Yağış yağsa, nə edəcəksən?", "Yağış yağdı?", "Nə etdin?", "Hava necədir?"], correctIndex: 0, xp: 10 },
            { id: "en7-cond-listen-t15", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "If you eat well, you will be healthy.", options: ["Yaxşı yesən, sağlam olacaqsan.", "Yaxşı yedin.", "Sağlamsan.", "Yemirsən."], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en7-cond-listen-b1", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "If we don't leave now, we will miss the flight.", options: ["İndi çıxmasaq, uçuşu qaçıracağıq.", "Uçuşu qaçırdıq.", "İndi çıxdıq.", "Uçuş getdi."], correctIndex: 0, xp: 15 },
            { id: "en7-cond-listen-b2", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "If she practices, she will improve.", options: ["Məşq etsə, inkişaf edəcək.", "O məşq etdi.", "İnkişaf etdi.", "Məşq etmir."], correctIndex: 0, xp: 15 },
            { id: "en7-cond-listen-b3", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "You will pass if you work hard.", options: ["Çox çalışsan, keçəcəksən.", "Keçdin.", "Çalışdın.", "Çalışmırsan."], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en7-cond-write",
          title: "Cümlə qur: First Conditional",
          intro: "Sözləri düzgün sıraya düz və şərt cümləsi qur.",
          sections: [
            { heading: "Necə işləyir?", body: "Sözlərə sıra ilə bas. If + Present Simple, will + feil." },
          ],
          tasks: [
            { id: "en7-cond-write-t1", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["If", "it", "rains", "we", "will", "stay", "home"], answer: "If it rains we will stay home", translation: "Yağış yağsa, evdə qalarıq.", xp: 10 },
            { id: "en7-cond-write-t2", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["If", "you", "study", "you", "will", "pass"], answer: "If you study you will pass", translation: "Oxusan, keçəcəksən.", xp: 10 },
            { id: "en7-cond-write-t3", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "will", "call", "you", "if", "I", "am", "free"], answer: "I will call you if I am free", translation: "Boş olsam, sənə zəng edəcəyəm.", xp: 10 },
            { id: "en7-cond-write-t4", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["If", "she", "has", "time", "she", "will", "help"], answer: "If she has time she will help", translation: "Vaxtı olsa, kömək edəcək.", xp: 10 },
            { id: "en7-cond-write-t5", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["If", "we", "leave", "now", "we", "will", "arrive", "early"], answer: "If we leave now we will arrive early", translation: "İndi çıxsaq, tez çatarıq.", xp: 10 },
            { id: "en7-cond-write-t6", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["If", "it", "is", "sunny", "we", "will", "go", "out"], answer: "If it is sunny we will go out", translation: "Günəşli olsa, çölə çıxacağıq.", xp: 10 },
            { id: "en7-cond-write-t7", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["If", "you", "help", "me", "I", "will", "thank", "you"], answer: "If you help me I will thank you", translation: "Mənə kömək etsən, təşəkkür edəcəyəm.", xp: 10 },
            { id: "en7-cond-write-t8", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["She", "will", "be", "happy", "if", "you", "come"], answer: "She will be happy if you come", translation: "Sən gəlsən, o sevinəcək.", xp: 10 },
            { id: "en7-cond-write-t9", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["If", "he", "works", "hard", "he", "will", "succeed"], answer: "If he works hard he will succeed", translation: "Çox çalışsa, uğur qazanacaq.", xp: 10 },
            { id: "en7-cond-write-t10", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["If", "they", "win", "they", "will", "celebrate"], answer: "If they win they will celebrate", translation: "Udsalar, qeyd edəcəklər.", xp: 10 },
            { id: "en7-cond-write-t11", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["We", "will", "be", "late", "if", "we", "wait"], answer: "We will be late if we wait", translation: "Gözləsək, gecikəcəyik.", xp: 10 },
            { id: "en7-cond-write-t12", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["If", "I", "see", "her", "I", "will", "ask"], answer: "If I see her I will ask", translation: "Onu görsəm, soruşacağam.", xp: 10 },
            { id: "en7-cond-write-t13", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["If", "you", "eat", "well", "you", "will", "be", "healthy"], answer: "If you eat well you will be healthy", translation: "Yaxşı yesən, sağlam olacaqsan.", xp: 10 },
            { id: "en7-cond-write-t14", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["If", "it", "snows", "we", "will", "make", "a", "snowman"], answer: "If it snows we will make a snowman", translation: "Qar yağsa, qardan adam düzəldəcəyik.", xp: 10 },
            { id: "en7-cond-write-t15", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["If", "she", "practices", "she", "will", "improve"], answer: "If she practices she will improve", translation: "Məşq etsə, inkişaf edəcək.", xp: 15 },
          ],
          bonusTasks: [
            { id: "en7-cond-write-b1", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["If", "we", "don't", "hurry", "we", "will", "be", "late"], answer: "If we don't hurry we will be late", translation: "Tələsməsək, gecikəcəyik.", xp: 15 },
            { id: "en7-cond-write-b2", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["What", "will", "you", "do", "if", "it", "rains"], answer: "What will you do if it rains", translation: "Yağış yağsa, nə edəcəksən?", xp: 15 },
            { id: "en7-cond-write-b3", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["If", "you", "come", "early", "we", "will", "have", "time"], answer: "If you come early we will have time", translation: "Tez gəlsən, vaxtımız olacaq.", xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 5. Modal verbs ═══════════════
    {
      id: "en7-modal",
      title: "Modal verbs (must, have to, should, might)",
      description: "Zərurət, məsləhət, ehtimal və qadağa bildirən modal feillər.",
      lessons: [
        {
          id: "en7-modal-rule",
          title: "Qayda: modal verbs",
          intro: "must (vacib), have to (məcbur), should (məsləhət), might (ehtimal), mustn't (qadağa). Modaldan sonra feilin əsas forması.",
          sections: [
            { heading: "must / have to", body: "must — daxili zərurət/vaciblik (I must study). have to — xarici məcburiyyət (I have to work). Modaldan sonra feil sadə formada gəlir (to YOX): must go, can swim." },
            { heading: "should", body: "should — məsləhət, tövsiyə: You should see a doctor. (həkimə getməlisən — məsləhət)." },
            { heading: "might / mustn't", body: "might — zəif ehtimal (It might rain). mustn't — qadağa (You mustn't smoke here)." },
          ],
          tasks: [
            { id: "en7-modal-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'You ___ see a doctor.' (məsləhət)", options: ["should", "must", "might", "have"], correctIndex: 0, xp: 10 },
            { id: "en7-modal-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'I ___ study for the exam.' (vacib)", options: ["must", "might", "should not", "can't"], correctIndex: 0, xp: 10 },
            { id: "en7-modal-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'It ___ rain later.' (zəif ehtimal)", options: ["might", "must", "should", "have to"], correctIndex: 0, xp: 10 },
            { id: "en7-modal-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "'You ___ smoke here.' (qadağa)", options: ["mustn't", "should", "might", "have to"], correctIndex: 0, xp: 10 },
            { id: "en7-modal-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "Modal feildən sonra feil hansı formada gəlir?", options: ["sadə forma (to yox)", "V-ing", "V2", "to + V"], correctIndex: 0, xp: 10 },
            { id: "en7-modal-rule-t6", type: "multiple_choice", speakOptions: true, prompt: "'I ___ to work every day.' (xarici məcburiyyət)", options: ["have", "must", "should", "might"], correctIndex: 0, xp: 10 },
            { id: "en7-modal-rule-t7", type: "multiple_choice", speakOptions: true, prompt: "'She ___ speak three languages.' (bacarıq)", options: ["can", "must", "should", "might"], correctIndex: 0, xp: 10 },
            { id: "en7-modal-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'You ___ eat more vegetables.' (məsləhət)", options: ["should", "might", "mustn't", "can't"], correctIndex: 0, xp: 10 },
            { id: "en7-modal-rule-t9", type: "multiple_choice", speakOptions: true, prompt: "'must' hansı məna verir?", options: ["zərurət/vaciblik", "ehtimal", "qadağa", "bacarıq"], correctIndex: 0, xp: 10 },
            { id: "en7-modal-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "'should' hansı məna verir?", options: ["məsləhət", "qadağa", "bacarıq", "icazə"], correctIndex: 0, xp: 10 },
            { id: "en7-modal-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "'We ___ be late. Let's hurry.' (məsləhət, inkar)", options: ["shouldn't", "mustn't", "can't", "might not"], correctIndex: 0, xp: 10 },
            { id: "en7-modal-rule-t12", type: "multiple_choice", speakOptions: true, prompt: "'He ___ come, but I'm not sure.' (ehtimal)", options: ["might", "must", "should", "has to"], correctIndex: 0, xp: 10 },
            { id: "en7-modal-rule-t13", type: "multiple_choice", speakOptions: true, prompt: "'You ___ do your homework.' (vacib)", options: ["must", "might", "mustn't", "shouldn't"], correctIndex: 0, xp: 10 },
            { id: "en7-modal-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "'mustn't' hansı məna verir?", options: ["qadağa", "məsləhət", "ehtimal", "bacarıq"], correctIndex: 0, xp: 10 },
            { id: "en7-modal-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'You ___ be tired after the trip.' (ehtimal — güman)", options: ["must", "should", "mustn't", "can't"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en7-modal-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "'Students ___ wear a uniform.' (qayda-məcburiyyət)", options: ["have to", "might", "should not", "can't"], correctIndex: 0, xp: 15 },
            { id: "en7-modal-rule-b2", type: "multiple_choice", speakOptions: true, prompt: "'You ___ touch that. It's dangerous.' (qadağa)", options: ["mustn't", "should", "might", "have to"], correctIndex: 0, xp: 15 },
            { id: "en7-modal-rule-b3", type: "multiple_choice", speakOptions: true, prompt: "'It's cloudy. It ___ rain.' (ehtimal)", options: ["might", "must", "should", "has to"], correctIndex: 0, xp: 15 },
            { id: "en7-modal-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "'You look ill. You ___ rest.' (məsləhət)", options: ["should", "mustn't", "might", "can't"], correctIndex: 0, xp: 15 },
            { id: "en7-modal-rule-b5", type: "multiple_choice", speakOptions: true, prompt: "'have to' və 'must' arasında fərq nədir?", options: ["have to xarici, must daxili zərurət", "heç fərq yox", "have to qadağadır", "must ehtimaldır"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en7-modal-listen",
          title: "Dinləmə: modal verbs",
          intro: "Cümləni dinlə və mənasını seç.",
          sections: [
            { heading: "Necə işləyir?", body: "Səs düyməsinə bas, cümləni dinlə, düzgün Azərbaycanca tərcüməni seç." },
          ],
          tasks: [
            { id: "en7-modal-listen-t1", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "You should see a doctor.", options: ["Həkimə getməlisən.", "Həkim gəldi.", "Həkimə getdin.", "Həkim yaxşıdır."], correctIndex: 0, xp: 10 },
            { id: "en7-modal-listen-t2", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I must study tonight.", options: ["Bu gecə oxumalıyam.", "Oxudum.", "Oxumaq istəmirəm.", "Oxuyuram."], correctIndex: 0, xp: 10 },
            { id: "en7-modal-listen-t3", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "It might rain later.", options: ["Sonra yağış yağa bilər.", "Yağış yağdı.", "Yağış yağır.", "Yağış yağmayacaq."], correctIndex: 0, xp: 10 },
            { id: "en7-modal-listen-t4", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "You mustn't smoke here.", options: ["Burada siqaret çəkmək olmaz.", "Burada siqaret çək.", "Siqaret çəkirsən.", "Siqaret bahalıdır."], correctIndex: 0, xp: 10 },
            { id: "en7-modal-listen-t5", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I have to work tomorrow.", options: ["Sabah işləməliyəm.", "İşlədim.", "İşləmirəm.", "İş yaxşıdır."], correctIndex: 0, xp: 10 },
            { id: "en7-modal-listen-t6", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "You should eat more fruit.", options: ["Daha çox meyvə yeməlisən.", "Meyvə yedin.", "Meyvə var.", "Meyvə şirindir."], correctIndex: 0, xp: 10 },
            { id: "en7-modal-listen-t7", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "She can speak French.", options: ["O fransızca danışa bilir.", "O fransızca danışdı.", "O fransız dilini sevir.", "O danışmır."], correctIndex: 0, xp: 10 },
            { id: "en7-modal-listen-t8", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "We shouldn't be late.", options: ["Gecikməməliyik.", "Gecikdik.", "Vaxtında gəldik.", "Gecdir."], correctIndex: 0, xp: 10 },
            { id: "en7-modal-listen-t9", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "He might come to the party.", options: ["O şənliyə gələ bilər.", "O gəldi.", "O gəlmir.", "Şənlik var."], correctIndex: 0, xp: 10 },
            { id: "en7-modal-listen-t10", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "You must do your homework.", options: ["Ev tapşırığını etməlisən.", "Ev tapşırığı etdin.", "Ev tapşırığı yoxdur.", "Ev tapşırığı çətindir."], correctIndex: 0, xp: 10 },
            { id: "en7-modal-listen-t11", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "Students have to wear a uniform.", options: ["Şagirdlər forma geyinməlidir.", "Şagirdlər gəldi.", "Forma gözəldir.", "Şagirdlər oxuyur."], correctIndex: 0, xp: 10 },
            { id: "en7-modal-listen-t12", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "You shouldn't eat too much sugar.", options: ["Çox şəkər yeməməlisən.", "Şəkər yedin.", "Şəkər şirindir.", "Şəkər var."], correctIndex: 0, xp: 10 },
            { id: "en7-modal-listen-t13", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "You mustn't touch that.", options: ["Ona toxunmaq olmaz.", "Ona toxun.", "Ona toxundum.", "O təhlükəlidir."], correctIndex: 0, xp: 10 },
            { id: "en7-modal-listen-t14", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I should call my mother.", options: ["Anama zəng etməliyəm.", "Anama zəng etdim.", "Anam zəng etdi.", "Anam evdədir."], correctIndex: 0, xp: 10 },
            { id: "en7-modal-listen-t15", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "It might be cold tomorrow.", options: ["Sabah soyuq ola bilər.", "Bu gün soyuqdur.", "Sabah istidir.", "Soyuq oldu."], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en7-modal-listen-b1", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "You must be tired after such a long trip.", options: ["Belə uzun səfərdən sonra yorğun olmalısan.", "Yorğun deyilsən.", "Səfər qısa idi.", "Yatdın."], correctIndex: 0, xp: 15 },
            { id: "en7-modal-listen-b2", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "You don't have to come if you're busy.", options: ["Məşğulsansa, gəlməyə bilərsən.", "Gəlməlisən.", "Gəlmə.", "Gəldin."], correctIndex: 0, xp: 15 },
            { id: "en7-modal-listen-b3", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "We might go to the beach this weekend.", options: ["Bu həftəsonu çimərliyə gedə bilərik.", "Çimərliyə getdik.", "Çimərlik gözəldir.", "Getmirik."], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en7-modal-write",
          title: "Cümlə qur: modal verbs",
          intro: "Sözləri düzgün sıraya düz və modal feilli cümlə qur.",
          sections: [
            { heading: "Necə işləyir?", body: "Sözlərə sıra ilə bas. kim + modal + feil (sadə forma)." },
          ],
          tasks: [
            { id: "en7-modal-write-t1", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["You", "should", "see", "a", "doctor"], answer: "You should see a doctor", translation: "Həkimə getməlisən.", xp: 10 },
            { id: "en7-modal-write-t2", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "must", "study", "tonight"], answer: "I must study tonight", translation: "Bu gecə oxumalıyam.", xp: 10 },
            { id: "en7-modal-write-t3", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["It", "might", "rain", "later"], answer: "It might rain later", translation: "Sonra yağış yağa bilər.", xp: 10 },
            { id: "en7-modal-write-t4", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["You", "mustn't", "smoke", "here"], answer: "You mustn't smoke here", translation: "Burada siqaret çəkmək olmaz.", xp: 10 },
            { id: "en7-modal-write-t5", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "have", "to", "work", "tomorrow"], answer: "I have to work tomorrow", translation: "Sabah işləməliyəm.", xp: 10 },
            { id: "en7-modal-write-t6", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["You", "should", "eat", "more", "fruit"], answer: "You should eat more fruit", translation: "Daha çox meyvə yeməlisən.", xp: 10 },
            { id: "en7-modal-write-t7", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["She", "can", "speak", "French"], answer: "She can speak French", translation: "O fransızca danışa bilir.", xp: 10 },
            { id: "en7-modal-write-t8", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["We", "shouldn't", "be", "late"], answer: "We shouldn't be late", translation: "Gecikməməliyik.", xp: 10 },
            { id: "en7-modal-write-t9", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["He", "might", "come", "later"], answer: "He might come later", translation: "O sonra gələ bilər.", xp: 10 },
            { id: "en7-modal-write-t10", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["You", "must", "do", "your", "homework"], answer: "You must do your homework", translation: "Ev tapşırığını etməlisən.", xp: 10 },
            { id: "en7-modal-write-t11", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["Students", "have", "to", "wear", "a", "uniform"], answer: "Students have to wear a uniform", translation: "Şagirdlər forma geyinməlidir.", xp: 10 },
            { id: "en7-modal-write-t12", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["You", "shouldn't", "eat", "too", "much", "sugar"], answer: "You shouldn't eat too much sugar", translation: "Çox şəkər yeməməlisən.", xp: 10 },
            { id: "en7-modal-write-t13", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "should", "call", "my", "mother"], answer: "I should call my mother", translation: "Anama zəng etməliyəm.", xp: 10 },
            { id: "en7-modal-write-t14", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["It", "might", "be", "cold"], answer: "It might be cold", translation: "Soyuq ola bilər.", xp: 10 },
            { id: "en7-modal-write-t15", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["You", "must", "be", "careful"], answer: "You must be careful", translation: "Diqqətli olmalısan.", xp: 15 },
          ],
          bonusTasks: [
            { id: "en7-modal-write-b1", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["You", "don't", "have", "to", "come"], answer: "You don't have to come", translation: "Gəlməyə bilərsən.", xp: 15 },
            { id: "en7-modal-write-b2", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["We", "might", "go", "to", "the", "beach"], answer: "We might go to the beach", translation: "Çimərliyə gedə bilərik.", xp: 15 },
            { id: "en7-modal-write-b3", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["You", "mustn't", "be", "rude"], answer: "You mustn't be rude", translation: "Kobud olmaq olmaz.", xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 6. Reported speech və tematik lüğət ═══════════════
    {
      id: "en7-reported",
      title: "Reported speech və tematik lüğət",
      description: "Dolayı nitqin əsasları (say/tell) və tematik lüğət (Environment & School).",
      lessons: [
        {
          id: "en7-reported-rule",
          title: "Qayda: Reported speech",
          intro: "Birbaşa nitqi dolayı çatdırmaq. Zaman bir addım geriyə çəkilir: is → was, will → would.",
          sections: [
            { heading: "Say / Tell", body: "Dolayı nitqdə 'said' və ya 'told' işlənir. tell-dən sonra şəxs gəlir (He told me...), say-dən sonra gəlmir (He said that...)." },
            { heading: "Zamanın geriyə çəkilməsi", body: "Birbaşa → dolayı: am/is → was, are → were, do/does → did, will → would, can → could. 'I am tired' → He said he was tired." },
          ],
          tasks: [
            { id: "en7-reported-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "Direct: 'I am tired.' Reported: 'He said he ___ tired.'", options: ["was", "is", "are", "were"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'will' dolayı nitqdə nəyə çevrilir?", options: ["would", "will", "was", "can"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'can' dolayı nitqdə nəyə çevrilir?", options: ["could", "can", "will", "would"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "'tell' feilindən sonra nə gəlir?", options: ["şəxs (me, him...)", "heç nə", "that dərhal", "to"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "Direct: 'She is happy.' Reported: 'He said she ___ happy.'", options: ["was", "is", "were", "are"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-rule-t6", type: "multiple_choice", speakOptions: true, prompt: "Direct: 'They are here.' Reported: 'He said they ___ here.'", options: ["were", "are", "was", "is"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-rule-t7", type: "multiple_choice", speakOptions: true, prompt: "Direct: 'I will come.' Reported: 'She said she ___ come.'", options: ["would", "will", "was", "can"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'He ___ me that he was busy.' (şəxs var)", options: ["told", "said", "say", "tells"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-rule-t9", type: "multiple_choice", speakOptions: true, prompt: "'She ___ that she liked it.' (şəxs yoxdur)", options: ["said", "told", "told me that", "say"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "Direct: 'I do my homework.' Reported: 'He said he ___ his homework.'", options: ["did", "does", "do", "was doing"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "Dolayı nitqdə zaman necə dəyişir?", options: ["bir addım geriyə çəkilir", "dəyişmir", "gələcəyə keçir", "yox olur"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-rule-t12", type: "multiple_choice", speakOptions: true, prompt: "Direct: 'I can swim.' Reported: 'He said he ___ swim.'", options: ["could", "can", "would", "was"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-rule-t13", type: "multiple_choice", speakOptions: true, prompt: "Direct: 'We are ready.' Reported: 'They said they ___ ready.'", options: ["were", "are", "was", "is"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "'say' və 'tell' fərqi nədir?", options: ["tell-dən sonra şəxs gəlir", "heç fərq yox", "say-dən sonra şəxs gəlir", "tell keçmişdir"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "Direct: 'It is raining.' Reported: 'She said it ___ raining.'", options: ["was", "is", "were", "are"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en7-reported-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "Direct: 'I have finished.' Reported: 'He said he ___ finished.'", options: ["had", "have", "has", "was"], correctIndex: 0, xp: 15 },
            { id: "en7-reported-rule-b2", type: "multiple_choice", speakOptions: true, prompt: "Direct: 'I like coffee.' Reported: 'She said she ___ coffee.'", options: ["liked", "likes", "like", "was liking"], correctIndex: 0, xp: 15 },
            { id: "en7-reported-rule-b3", type: "multiple_choice", speakOptions: true, prompt: "'He told ___ that he was tired.'", options: ["me", "that", "to me that", "—"], correctIndex: 0, xp: 15 },
            { id: "en7-reported-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "Direct: 'I will help you.' Reported: 'He said he ___ help me.'", options: ["would", "will", "could", "was"], correctIndex: 0, xp: 15 },
            { id: "en7-reported-rule-b5", type: "multiple_choice", speakOptions: true, prompt: "Direct: 'They live here.' Reported: 'She said they ___ there.'", options: ["lived", "live", "lives", "were living"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en7-reported-vocab",
          title: "Lüğət: Environment & School",
          intro: "Ətraf mühit və məktəb mövzusunda sözlər.",
          sections: [
            { heading: "Environment", body: "environment — ətraf mühit, pollution — çirklənmə, recycle — təkrar emal, plant — əkmək, litter — zibil, save — qorumaq/qənaət etmək, planet — planet." },
            { heading: "School", body: "subject — fənn, timetable — cədvəl, break — tənəffüs, homework — ev tapşırığı, exam — imtahan, grade/mark — qiymət, term — semestr." },
          ],
          tasks: [
            { id: "en7-reported-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'environment' nə deməkdir?", options: ["ətraf mühit", "hava", "su", "planet"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'pollution' nə deməkdir?", options: ["çirklənmə", "təmizlik", "əkin", "zibil"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'recycle' nə deməkdir?", options: ["təkrar emal etmək", "atmaq", "yandırmaq", "almaq"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'litter' nə deməkdir?", options: ["zibil", "ağac", "su", "hava"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'subject' (məktəbdə) nə deməkdir?", options: ["fənn", "sinif", "müəllim", "kitab"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'timetable' nə deməkdir?", options: ["dərs cədvəli", "imtahan", "qiymət", "tənəffüs"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'break' (məktəbdə) nə deməkdir?", options: ["tənəffüs", "dərs", "imtahan", "cədvəl"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "'exam' nə deməkdir?", options: ["imtahan", "tənəffüs", "fənn", "qiymət"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-vocab-t9", type: "multiple_choice", speakOptions: true, prompt: "'ətraf mühit' İngiliscə necədir?", options: ["environment", "pollution", "planet", "nature"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-vocab-t10", type: "multiple_choice", speakOptions: true, prompt: "'imtahan' İngiliscə necədir?", options: ["exam", "subject", "grade", "term"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-vocab-t11", type: "fill_blank", prompt: "'ev tapşırığı' — İngiliscə (bir söz) yaz.", accepted: ["homework"], xp: 10 },
            { id: "en7-reported-vocab-t12", type: "fill_blank", prompt: "'planet' sözünü İngiliscə yaz.", accepted: ["planet"], xp: 10 },
            { id: "en7-reported-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "'We must ___ water.' (qənaət et)", options: ["save", "waste", "pollute", "drop"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'plant a tree' nə deməkdir?", options: ["ağac əkmək", "ağac kəsmək", "ağaca baxmaq", "ağac almaq"], correctIndex: 0, xp: 10 },
            { id: "en7-reported-vocab-t15", type: "multiple_choice", speakOptions: true, prompt: "'grade/mark' (məktəbdə) nə deməkdir?", options: ["qiymət", "fənn", "cədvəl", "tənəffüs"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en7-reported-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'Don't ___ in the park.' (zibil atma)", options: ["litter", "recycle", "plant", "save"], correctIndex: 0, xp: 15 },
            { id: "en7-reported-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'term' (məktəbdə) nə deməkdir?", options: ["semestr", "imtahan", "fənn", "qiymət"], correctIndex: 0, xp: 15 },
            { id: "en7-reported-vocab-b3", type: "fill_blank", prompt: "'çirklənmə' — İngiliscə yaz.", accepted: ["pollution"], xp: 15 },
            { id: "en7-reported-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'We should ___ paper and plastic.' (təkrar emal)", options: ["recycle", "litter", "waste", "throw"], correctIndex: 0, xp: 15 },
            { id: "en7-reported-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'Maths is my favourite ___.'", options: ["subject", "break", "exam", "term"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en7-reported-write",
          title: "Cümlə qur: reported & vocab",
          intro: "Sözləri düzgün sıraya düz və dolayı nitq/mövzu cümləsi qur.",
          sections: [
            { heading: "Necə işləyir?", body: "Sözlərə sıra ilə bas. Reported: He said (that) + geri çəkilmiş zaman." },
          ],
          tasks: [
            { id: "en7-reported-write-t1", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["He", "said", "he", "was", "tired"], answer: "He said he was tired", translation: "O yorğun olduğunu dedi.", xp: 10 },
            { id: "en7-reported-write-t2", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["She", "told", "me", "she", "was", "happy"], answer: "She told me she was happy", translation: "O mənə xoşbəxt olduğunu dedi.", xp: 10 },
            { id: "en7-reported-write-t3", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["He", "said", "he", "would", "come"], answer: "He said he would come", translation: "O gələcəyini dedi.", xp: 10 },
            { id: "en7-reported-write-t4", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["We", "must", "save", "water"], answer: "We must save water", translation: "Suya qənaət etməliyik.", xp: 10 },
            { id: "en7-reported-write-t5", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["We", "should", "recycle", "plastic"], answer: "We should recycle plastic", translation: "Plastiki təkrar emal etməliyik.", xp: 10 },
            { id: "en7-reported-write-t6", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["She", "said", "she", "liked", "the", "book"], answer: "She said she liked the book", translation: "O kitabı bəyəndiyini dedi.", xp: 10 },
            { id: "en7-reported-write-t7", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["Don't", "litter", "in", "the", "park"], answer: "Don't litter in the park", translation: "Parkda zibil atma.", xp: 10 },
            { id: "en7-reported-write-t8", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["He", "told", "me", "he", "could", "swim"], answer: "He told me he could swim", translation: "O mənə üzə bildiyini dedi.", xp: 10 },
            { id: "en7-reported-write-t9", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["Maths", "is", "my", "favourite", "subject"], answer: "Maths is my favourite subject", translation: "Riyaziyyat sevimli fənnimdir.", xp: 10 },
            { id: "en7-reported-write-t10", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["We", "should", "plant", "trees"], answer: "We should plant trees", translation: "Ağac əkməliyik.", xp: 10 },
            { id: "en7-reported-write-t11", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["She", "said", "she", "was", "busy"], answer: "She said she was busy", translation: "O məşğul olduğunu dedi.", xp: 10 },
            { id: "en7-reported-write-t12", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["The", "exam", "was", "difficult"], answer: "The exam was difficult", translation: "İmtahan çətin idi.", xp: 10 },
            { id: "en7-reported-write-t13", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["He", "said", "they", "were", "ready"], answer: "He said they were ready", translation: "O onların hazır olduğunu dedi.", xp: 10 },
            { id: "en7-reported-write-t14", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["Pollution", "is", "a", "big", "problem"], answer: "Pollution is a big problem", translation: "Çirklənmə böyük problemdir.", xp: 10 },
            { id: "en7-reported-write-t15", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["She", "told", "me", "she", "would", "help"], answer: "She told me she would help", translation: "O mənə kömək edəcəyini dedi.", xp: 15 },
          ],
          bonusTasks: [
            { id: "en7-reported-write-b1", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["We", "must", "protect", "the", "environment"], answer: "We must protect the environment", translation: "Ətraf mühiti qorumalıyıq.", xp: 15 },
            { id: "en7-reported-write-b2", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["He", "said", "he", "had", "finished"], answer: "He said he had finished", translation: "O bitirdiyini dedi.", xp: 15 },
            { id: "en7-reported-write-b3", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["We", "have", "a", "break", "at", "eleven"], answer: "We have a break at eleven", translation: "Saat on birdə tənəffüsümüz var.", xp: 15 },
          ],
        },
      ],
    },
  ],
};
