// Riyaziyyat — 1-ci sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Ədədlər 0-10 və sayma  2) 10 dairəsində toplama  3) 10 dairəsində çıxma
// 4) Ədədlər 11-20  5) 20 dairəsində toplama və çıxma  6) Müqayisə, fiqurlar, məsələlər.
// 1-ci sinif üçün suallar ÇOX SADƏdir (qısa mətn, rəqəm cavablar). id prefiksi ry1-*.

import type { Subject } from "../types";

export const math1: Subject = {
  slug: "riyaziyyat-1",
  name: "Riyaziyyat",
  grade: 1,
  icon: "R",
  color: "sky",
  units: [
    // ═══════════════ 1. Ədədlər 0-10 və sayma ═══════════════
    {
      id: "ry1-eded10",
      title: "Ədədlər 0-10",
      description: "10-a qədər sayma, müqayisə və məşq.",
      lessons: [
        {
          id: "ry1-sayma-l1",
          title: "1-dən 10-a sayma",
          intro: "Ədədləri sıra ilə saymağı öyrənək.",
          sections: [
            { heading: "Sayma", body: "Bir, iki, üç, dörd, beş, altı, yeddi, səkkiz, doqquz, on. Rəqəmlərlə: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10." },
            { heading: "Növbəti ədəd", body: "Hər ədəddən sonra gələn ədəd 1 böyükdür: 3-dən sonra 4 gəlir." },
          ],
          tasks: [
            { id: "ry1-sayma-l1-t1", type: "numeric", prompt: "1-dən sonra hansı ədəd gəlir?", answer: 2, xp: 10, explanation: "«Sonra gələn» 1 çox deməkdir: 1 + 1 = 2.", skills: ["number.count"] },
            { id: "ry1-sayma-l1-t2", type: "numeric", prompt: "2-dən sonra hansı ədəd gəlir?", answer: 3, xp: 10, explanation: "1 artırırıq: 2 + 1 = 3.", skills: ["number.count"] },
            { id: "ry1-sayma-l1-t3", type: "numeric", prompt: "3-dən sonra hansı ədəd gəlir?", answer: 4, xp: 10, explanation: "1 artırırıq: 3 + 1 = 4.", skills: ["number.count"] },
            { id: "ry1-sayma-l1-t4", type: "numeric", prompt: "4-dən sonra hansı ədəd gəlir?", answer: 5, xp: 10, explanation: "1 artırırıq: 4 + 1 = 5.", skills: ["number.count"] },
            { id: "ry1-sayma-l1-t5", type: "numeric", prompt: "5-dən sonra hansı ədəd gəlir?", answer: 6, xp: 10, explanation: "1 artırırıq: 5 + 1 = 6.", skills: ["number.count"] },
            { id: "ry1-sayma-l1-t6", type: "numeric", prompt: "6-dan sonra hansı ədəd gəlir?", answer: 7, xp: 10, explanation: "1 artırırıq: 6 + 1 = 7.", skills: ["number.count"] },
            { id: "ry1-sayma-l1-t7", type: "numeric", prompt: "7-dən sonra hansı ədəd gəlir?", answer: 8, xp: 10, explanation: "1 artırırıq: 7 + 1 = 8.", skills: ["number.count"] },
            { id: "ry1-sayma-l1-t8", type: "numeric", prompt: "8-dən sonra hansı ədəd gəlir?", answer: 9, xp: 10, explanation: "1 artırırıq: 8 + 1 = 9.", skills: ["number.count"] },
            { id: "ry1-sayma-l1-t9", type: "numeric", prompt: "9-dan sonra hansı ədəd gəlir?", answer: 10, xp: 10, explanation: "1 artırırıq: 9 + 1 = 10. Bu, iki rəqəmlə yazılan ilk ədəddir.", skills: ["number.count"] },
            { id: "ry1-sayma-l1-t10", type: "multiple_choice", prompt: "'beş' ədədi rəqəmlə necə yazılır?", options: ["5", "4", "6", "3"], correctIndex: 0, xp: 10, explanation: "Barmaqla sayaq: bir, iki, üç, dörd, beş. «Beş» 5 rəqəmi ilə yazılır.", skills: ["number.place_value"] },
            { id: "ry1-sayma-l1-t11", type: "multiple_choice", prompt: "'yeddi' ədədi rəqəmlə necə yazılır?", options: ["7", "8", "6", "9"], correctIndex: 0, xp: 10, explanation: "Sayaq: bir, iki, üç, dörd, beş, altı, yeddi. «Yeddi» 7 rəqəmi ilə yazılır.", skills: ["number.place_value"] },
            { id: "ry1-sayma-l1-t12", type: "multiple_choice", prompt: "🍎🍎🍎 — neçə alma var?", options: ["3", "2", "4", "5"], correctIndex: 0, xp: 10, explanation: "Almaları bir-bir sayırıq: 1, 2, 3. Cəmi 3 alma var.", skills: ["number.count"] },
            { id: "ry1-sayma-l1-t13", type: "multiple_choice", prompt: "⭐⭐⭐⭐⭐ — neçə ulduz var?", options: ["5", "4", "6", "3"], correctIndex: 0, xp: 10, explanation: "Ulduzları bir-bir sayırıq: 1, 2, 3, 4, 5. Cəmi 5 ulduz var.", skills: ["number.count"] },
            { id: "ry1-sayma-l1-t14", type: "numeric", prompt: "Ən kiçik birrəqəmli ədəd (0-dan başqa) hansıdır?", answer: 1, xp: 10, explanation: "0-dan sonra gələn ilk ədəd 1-dir, ona görə 0 sayılmasa ən kiçiyi 1-dir.", skills: ["number.count"] },
            { id: "ry1-sayma-l1-t15", type: "numeric", prompt: "Ən böyük birrəqəmli ədəd hansıdır?", answer: 9, xp: 15, explanation: "Birrəqəmli ədədlər 0-dan 9-a qədərdir. 10 artıq iki rəqəmlə yazılır, ona görə ən böyüyü 9-dur.", skills: ["number.count"] },
          ],
          bonusTasks: [
            { id: "ry1-sayma-l1-b1", type: "multiple_choice", prompt: "🐟🐟🐟🐟 — neçə balıq var?", options: ["4", "3", "5", "6"], correctIndex: 0, xp: 15, explanation: "Balıqları sayırıq: 1, 2, 3, 4. Cəmi 4 balıq var.", skills: ["number.count"] },
            { id: "ry1-sayma-l1-b2", type: "numeric", prompt: "10-dan əvvəl gələn ədəd hansıdır?", answer: 9, xp: 15, explanation: "«Əvvəl gələn» 1 az deməkdir: 10 − 1 = 9.", skills: ["number.count"] },
            { id: "ry1-sayma-l1-b3", type: "multiple_choice", prompt: "'on' ədədi rəqəmlə necə yazılır?", options: ["10", "1", "100", "0"], correctIndex: 0, xp: 15, explanation: "«On» bir rəqəmlə yazılmır: əvvəl 1, sonra 0 → 10.", skills: ["number.place_value"] },
            { id: "ry1-sayma-l1-b4", type: "numeric", prompt: "6-dan əvvəl gələn ədəd hansıdır?", answer: 5, xp: 15, explanation: "«Əvvəl gələn» 1 az deməkdir: 6 − 1 = 5.", skills: ["number.count"] },
            { id: "ry1-sayma-l1-b5", type: "multiple_choice", prompt: "🎈🎈 — neçə şar var?", options: ["2", "1", "3", "4"], correctIndex: 0, xp: 15, explanation: "Şarları sayırıq: 1, 2. Cəmi 2 şar var.", skills: ["number.count"] },
          ],
        },
        {
          id: "ry1-sayma-l2",
          title: "Ədədləri müqayisə et",
          intro: "Hansı ədəd böyük, hansı kiçikdir?",
          sections: [
            { heading: "Böyük və kiçik", body: "Sayma sırasında sonra gələn ədəd böyükdür: 7 > 3. Əvvəl gələn kiçikdir: 3 < 7." },
          ],
          tasks: [
            { id: "ry1-sayma-l2-t1", type: "multiple_choice", prompt: "Hansı ədəd böyükdür?", options: ["7", "3", "hər ikisi bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "Sayarkən 7 daha gec gəlir, deməli 3-dən böyükdür: 3 < 7.", skills: ["number.compare"] },
            { id: "ry1-sayma-l2-t2", type: "multiple_choice", prompt: "Hansı ədəd böyükdür?", options: ["9", "5", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "Sayarkən 9 daha gec gəlir, deməli 5-dən böyükdür: 5 < 9.", skills: ["number.compare"] },
            { id: "ry1-sayma-l2-t3", type: "multiple_choice", prompt: "Hansı ədəd kiçikdir?", options: ["2", "8", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "Sayarkən 2 daha tez gəlir, deməli 8-dən kiçikdir: 2 < 8.", skills: ["number.compare"] },
            { id: "ry1-sayma-l2-t4", type: "multiple_choice", prompt: "Hansı ədəd böyükdür?", options: ["10", "6", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "10 sayarkən ən sonda gəlir, ona görə 6-dan böyükdür: 6 < 10.", skills: ["number.compare"] },
            { id: "ry1-sayma-l2-t5", type: "multiple_choice", prompt: "Hansı ədəd kiçikdir?", options: ["1", "4", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "1 sayarkən 4-dən əvvəl gəlir, deməli daha kiçikdir: 1 < 4.", skills: ["number.compare"] },
            { id: "ry1-sayma-l2-t6", type: "multiple_choice", prompt: "4 və 4 — hansı böyükdür?", options: ["bərabərdir", "birinci", "ikinci", "heç biri"], correctIndex: 0, xp: 10, explanation: "Hər iki ədəd eynidir — biri o birindən böyük deyil. Bu halda «bərabərdir» deyirik: 4 = 4.", skills: ["number.compare"] },
            { id: "ry1-sayma-l2-t7", type: "multiple_choice", prompt: "Hansı ədəd böyükdür?", options: ["8", "7", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "8 sayarkən 7-dən sonra gəlir, deməli böyükdür: 7 < 8.", skills: ["number.compare"] },
            { id: "ry1-sayma-l2-t8", type: "numeric", prompt: "3 və 6 ədədlərindən böyüyü hansıdır?", answer: 6, xp: 10, explanation: "Sayarkən 6 daha gec gəlir: 3 < 6. Böyüyü 6-dır.", skills: ["number.compare"] },
            { id: "ry1-sayma-l2-t9", type: "numeric", prompt: "2 və 9 ədədlərindən kiçiyi hansıdır?", answer: 2, xp: 10, explanation: "Sayarkən 2 daha tez gəlir: 2 < 9. Kiçiyi 2-dir.", skills: ["number.compare"] },
            { id: "ry1-sayma-l2-t10", type: "numeric", prompt: "5 və 8 ədədlərindən böyüyü hansıdır?", answer: 8, xp: 10, explanation: "Sayarkən 8 daha gec gəlir: 5 < 8. Böyüyü 8-dir.", skills: ["number.compare"] },
            { id: "ry1-sayma-l2-t11", type: "numeric", prompt: "10 və 7 ədədlərindən böyüyü hansıdır?", answer: 10, xp: 10, explanation: "10 iki rəqəmlidir və 7-dən sonra gəlir: 7 < 10. Böyüyü 10-dur.", skills: ["number.compare"] },
            { id: "ry1-sayma-l2-t12", type: "numeric", prompt: "1 və 4 ədədlərindən kiçiyi hansıdır?", answer: 1, xp: 10, explanation: "Sayarkən 1 daha tez gəlir: 1 < 4. Kiçiyi 1-dir.", skills: ["number.compare"] },
            { id: "ry1-sayma-l2-t13", type: "multiple_choice", prompt: "Hansı işarə '7 böyükdür 3' üçün düzgündür?", options: [">", "<", "=", "+"], correctIndex: 0, xp: 10, explanation: "«Böyükdür» işarəsi > -dir və onun açıq ağzı həmişə BÖYÜK ədədə baxır: 7 > 3.", skills: ["number.compare"] },
            { id: "ry1-sayma-l2-t14", type: "multiple_choice", prompt: "Hansı işarə '2 kiçikdir 5' üçün düzgündür?", options: ["<", ">", "=", "−"], correctIndex: 0, xp: 10, explanation: "«Kiçikdir» işarəsi < -dir; açıq ağzı böyük ədədə — 5-ə baxır: 2 < 5.", skills: ["number.compare"] },
            { id: "ry1-sayma-l2-t15", type: "numeric", prompt: "6 və 9 ədədlərindən böyüyü hansıdır?", answer: 9, xp: 15, explanation: "Sayarkən 9 daha gec gəlir: 6 < 9. Böyüyü 9-dur.", skills: ["number.compare"] },
          ],
          bonusTasks: [
            { id: "ry1-sayma-l2-b1", type: "numeric", prompt: "1, 5, 3 ədədlərindən ən böyüyü hansıdır?", answer: 5, xp: 15, explanation: "Üçünü sayma sırasına düzək: 1, 3, 5. Ən sonda gələn 5 ən böyüyüdür.", skills: ["number.compare"] },
            { id: "ry1-sayma-l2-b2", type: "numeric", prompt: "8, 2, 4 ədədlərindən ən kiçiyi hansıdır?", answer: 2, xp: 15, explanation: "Sıraya düzək: 2, 4, 8. Ən əvvəldə gələn 2 ən kiçiyidir.", skills: ["number.compare"] },
            { id: "ry1-sayma-l2-b3", type: "numeric", prompt: "7, 10, 6 ədədlərindən ən böyüyü hansıdır?", answer: 10, xp: 15, explanation: "Sıraya düzək: 6, 7, 10. Ən sonda gələn 10 ən böyüyüdür.", skills: ["number.compare"] },
            { id: "ry1-sayma-l2-b4", type: "multiple_choice", prompt: "Hansı işarə '5 = 5' üçün düzgündür?", options: ["=", ">", "<", "+"], correctIndex: 0, xp: 15, explanation: "İki ədəd eyni olanda «bərabərdir» işarəsini — = — yazırıq: 5 = 5.", skills: ["number.compare"] },
            { id: "ry1-sayma-l2-b5", type: "numeric", prompt: "3, 9, 1, 5 ədədlərindən ən böyüyü hansıdır?", answer: 9, xp: 15, explanation: "Sıraya düzək: 1, 3, 5, 9. Ən sonda gələn 9 ən böyüyüdür.", skills: ["number.compare"] },
          ],
        },
        {
          id: "ry1-eded10-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry1-eded10-mesq",
          title: "Məşq",
          intro: "10-a qədər ədədləri birlikdə məşq edək!",
          sections: [
            { heading: "Yadına salaq", body: "Sayma: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10. Böyük ədəd sağda, kiçik ədəd solda olur." },
          ],
          tasks: [
            { id: "ry1-eded10-mesq-t1", type: "numeric", prompt: "5-dən sonra hansı ədəd gəlir?", answer: 6, xp: 10, explanation: "«Sonra gələn» 1 çox deməkdir: 5 + 1 = 6.", skills: ["number.count"] },
            { id: "ry1-eded10-mesq-t2", type: "numeric", prompt: "8-dən əvvəl hansı ədəd gəlir?", answer: 7, xp: 10, explanation: "«Əvvəl gələn» 1 az deməkdir: 8 − 1 = 7.", skills: ["number.count"] },
            { id: "ry1-eded10-mesq-t3", type: "numeric", prompt: "🐤🐤🐤🐤 — neçə cücə var?", answer: 4, xp: 10, explanation: "Cücələri bir-bir sayırıq: 1, 2, 3, 4. Cəmi 4 cücə var.", skills: ["number.count"] },
            { id: "ry1-eded10-mesq-t4", type: "numeric", prompt: "🌸🌸🌸🌸🌸🌸 — neçə gül var?", answer: 6, xp: 10, explanation: "Gülləri bir-bir sayırıq: 1, 2, 3, 4, 5, 6. Cəmi 6 gül var.", skills: ["number.count"] },
            { id: "ry1-eded10-mesq-t5", type: "multiple_choice", prompt: "Hansı daha böyükdür?", options: ["9", "4", "2", "0"], correctIndex: 0, xp: 10, explanation: "Variantları sıraya düzsək: 0, 2, 4, 9. Ən sonda gələn 9 ən böyüyüdür.", skills: ["number.compare"] },
            { id: "ry1-eded10-mesq-t6", type: "multiple_choice", prompt: "Hansı daha kiçikdir?", options: ["1", "5", "8", "10"], correctIndex: 0, xp: 10, explanation: "Variantları sıraya düzsək: 1, 5, 8, 10. Ən əvvəldə gələn 1 ən kiçiyidir.", skills: ["number.compare"] },
            { id: "ry1-eded10-mesq-t7", type: "numeric", prompt: "10-dan əvvəl hansı ədəd gəlir?", answer: 9, xp: 10, explanation: "«Əvvəl gələn» 1 az deməkdir: 10 − 1 = 9.", skills: ["number.count"] },
            { id: "ry1-eded10-mesq-t8", type: "multiple_choice", prompt: "'üç' ədədi rəqəmlə necə yazılır?", options: ["3", "5", "2", "8"], correctIndex: 0, xp: 10, explanation: "Sayaq: bir, iki, üç. «Üç» 3 rəqəmi ilə yazılır.", skills: ["number.place_value"] },
            { id: "ry1-eded10-mesq-t9", type: "numeric", prompt: "Ən böyük birrəqəmli ədəd hansıdır?", answer: 9, xp: 10, explanation: "Birrəqəmli ədədlər 0-dan 9-a qədərdir; 10 iki rəqəmlidir. Ona görə ən böyüyü 9-dur.", skills: ["number.count"] },
            { id: "ry1-eded10-mesq-t10", type: "multiple_choice", prompt: "6 və 3 — hansı böyükdür?", options: ["6", "3", "bərabərdir", "bilinmir"], correctIndex: 0, xp: 10, explanation: "Sayarkən 6 daha gec gəlir: 3 < 6. Böyüyü 6-dır.", skills: ["number.compare"] },
          ],
          bonusTasks: [
            { id: "ry1-eded10-mesq-b1", type: "numeric", prompt: "2, 4, 6, ... — növbəti ədəd?", answer: 8, xp: 15, explanation: "Hər dəfə 2 artır: 2, 4, 6 — deməli növbəti 6 + 2 = 8.", skills: ["number.sequence"] },
            { id: "ry1-eded10-mesq-b2", type: "numeric", prompt: "10, 9, 8, ... — növbəti ədəd?", answer: 7, xp: 15, explanation: "Hər dəfə 1 azalır: 10, 9, 8 — deməli növbəti 8 − 1 = 7.", skills: ["number.sequence"] },
            { id: "ry1-eded10-mesq-b3", type: "multiple_choice", prompt: "Hansı sıra düzgündür?", options: ["1, 2, 3, 4", "4, 2, 1, 3", "2, 1, 4, 3", "3, 4, 2, 1"], correctIndex: 0, xp: 15, explanation: "Düzgün sıra kiçikdən böyüyə doğrudur: 1, 2, 3, 4. Digərlərində ədədlər qarışıqdır.", skills: ["number.count"] },
            { id: "ry1-eded10-mesq-b4", type: "numeric", prompt: "🍏🍏🍏 və 🍏🍏 — cəmi neçə alma?", answer: 5, xp: 15, explanation: "Əvvəl 3 alma, sonra 2 alma var. Hamısını birlikdə sayırıq: 3 + 2 = 5.", skills: ["number.count"] },
            { id: "ry1-eded10-mesq-b5", type: "numeric", prompt: "0-dan 5-ə qədər neçə ədəd var? (0 da daxil)", answer: 6, xp: 15, explanation: "0 da sayılır: 0, 1, 2, 3, 4, 5 — bunlar 6 ədəddir. Ona görə cavab 5 yox, 6-dır.", skills: ["number.count"] },
          ],
        },
        {
          id: "ry1-eded10-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    {
      id: "ry1-hesab10",
      title: "10 dairəsində toplama və çıxma",
      description: "10-a qədər toplama, çıxma və məşq.",
      lessons: [
        {
          id: "ry1-toplama-l1",
          title: "Kiçik ədədləri topla",
          intro: "Toplama — birləşdirmək deməkdir. 2 + 3 = 5.",
          sections: [
            { heading: "Toplama", body: "İki qrupu birləşdirəndə toplama edirik: 🍎🍎 + 🍎🍎🍎 = 5 alma. Yəni 2 + 3 = 5." },
          ],
          tasks: [
            { id: "ry1-toplama-l1-t1", type: "numeric", prompt: "1 + 1 = ?", answer: 2, xp: 10, explanation: "1-dən başlayıb 1 addım irəli sayırıq: 2. Deməli 1 + 1 = 2.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l1-t2", type: "numeric", prompt: "2 + 1 = ?", answer: 3, xp: 10, explanation: "2-dən başlayıb 1 addım irəli sayırıq: 3. Deməli 2 + 1 = 3.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l1-t3", type: "numeric", prompt: "2 + 2 = ?", answer: 4, xp: 10, explanation: "2-dən başlayıb 2 addım irəli sayırıq: 3, 4. Deməli 2 + 2 = 4.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l1-t4", type: "numeric", prompt: "3 + 1 = ?", answer: 4, xp: 10, explanation: "3-dən başlayıb 1 addım irəli sayırıq: 4. Deməli 3 + 1 = 4.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l1-t5", type: "numeric", prompt: "2 + 3 = ?", answer: 5, xp: 10, explanation: "2-dən başlayıb 3 addım irəli sayırıq: 3, 4, 5. Deməli 2 + 3 = 5.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l1-t6", type: "numeric", prompt: "3 + 2 = ?", answer: 5, xp: 10, explanation: "3-dən başlayıb 2 addım irəli sayırıq: 4, 5. Deməli 3 + 2 = 5.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l1-t7", type: "numeric", prompt: "1 + 4 = ?", answer: 5, xp: 10, explanation: "1-dən başlayıb 4 addım irəli sayırıq: 2, 3, 4, 5. Deməli 1 + 4 = 5.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l1-t8", type: "numeric", prompt: "3 + 3 = ?", answer: 6, xp: 10, explanation: "3-dən başlayıb 3 addım irəli sayırıq: 4, 5, 6. Deməli 3 + 3 = 6.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l1-t9", type: "numeric", prompt: "4 + 2 = ?", answer: 6, xp: 10, explanation: "4-dən başlayıb 2 addım irəli sayırıq: 5, 6. Deməli 4 + 2 = 6.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l1-t10", type: "numeric", prompt: "5 + 1 = ?", answer: 6, xp: 10, explanation: "5-dən başlayıb 1 addım irəli sayırıq: 6. Deməli 5 + 1 = 6.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l1-t11", type: "numeric", prompt: "0 + 4 = ?", answer: 4, xp: 10, explanation: "Sıfırın üstünə 4 əlavə etsək, elə 4 qalır: 0 + 4 = 4.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l1-t12", type: "numeric", prompt: "2 + 0 = ?", answer: 2, xp: 10, explanation: "Sıfır əlavə etmək heç nə əlavə etməmək deməkdir — ədəd dəyişmir: 2 + 0 = 2.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l1-t13", type: "multiple_choice", prompt: "🍎🍎 + 🍎 = ?", options: ["3", "2", "4", "1"], correctIndex: 0, xp: 10, explanation: "Əvvəl 2 alma var, üstünə 1 alma gəlir. Hamısını sayırıq: 1, 2, 3. Deməli 3.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l1-t14", type: "multiple_choice", prompt: "⭐⭐⭐ + ⭐⭐ = ?", options: ["5", "4", "6", "3"], correctIndex: 0, xp: 10, explanation: "Əvvəl 3 ulduz, sonra 2 ulduz. Hamısını sayırıq: 1, 2, 3, 4, 5. Deməli 5.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l1-t15", type: "numeric", prompt: "4 + 1 = ?", answer: 5, xp: 15, explanation: "4-dən başlayıb 1 addım irəli sayırıq: 5. Deməli 4 + 1 = 5.", skills: ["arith.add.basic"] },
          ],
          bonusTasks: [
            { id: "ry1-toplama-l1-b1", type: "numeric", prompt: "3 + 0 = ?", answer: 3, xp: 15, explanation: "Sıfır əlavə etmək heç nə əlavə etməmək deməkdir — ədəd dəyişmir: 3 + 0 = 3.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l1-b2", type: "numeric", prompt: "1 + 1 + 1 = ?", answer: 3, xp: 15, explanation: "Soldan başlayırıq: əvvəl 1 + 1 = 2, sonra 2 + 1 = 3.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l1-b3", type: "numeric", prompt: "2 + 2 + 1 = ?", answer: 5, xp: 15, explanation: "Soldan başlayırıq: əvvəl 2 + 2 = 4, sonra 4 + 1 = 5.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l1-b4", type: "multiple_choice", prompt: "🐟🐟🐟 + 🐟 = ?", options: ["4", "3", "5", "2"], correctIndex: 0, xp: 15, explanation: "Əvvəl 3 balıq, üstünə 1 balıq gəlir: 3-dən sonra 4. Deməli 4.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l1-b5", type: "numeric", prompt: "0 + 0 = ?", answer: 0, xp: 15, explanation: "Sıfır əlavə etmək heç nə əlavə etməmək deməkdir — ədəd dəyişmir: 0 + 0 = 0.", skills: ["arith.add.basic"] },
          ],
        },
        {
          id: "ry1-toplama-l2",
          title: "10-a qədər topla",
          intro: "Cəmi 10-a qədər olan toplamalar.",
          sections: [
            { heading: "Böyük cəm", body: "Ədədləri topla, cəm 10-a qədər ola bilər: 6 + 4 = 10, 7 + 2 = 9." },
          ],
          tasks: [
            { id: "ry1-toplama-l2-t1", type: "numeric", prompt: "5 + 2 = ?", answer: 7, xp: 10, explanation: "5-dən başlayıb 2 addım irəli sayırıq: 6, 7. Deməli 5 + 2 = 7.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l2-t2", type: "numeric", prompt: "4 + 3 = ?", answer: 7, xp: 10, explanation: "4-dən başlayıb 3 addım irəli sayırıq: 5, 6, 7. Deməli 4 + 3 = 7.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l2-t3", type: "numeric", prompt: "6 + 2 = ?", answer: 8, xp: 10, explanation: "6-dən başlayıb 2 addım irəli sayırıq: 7, 8. Deməli 6 + 2 = 8.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l2-t4", type: "numeric", prompt: "5 + 3 = ?", answer: 8, xp: 10, explanation: "5-dən başlayıb 3 addım irəli sayırıq: 6, 7, 8. Deməli 5 + 3 = 8.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l2-t5", type: "numeric", prompt: "4 + 4 = ?", answer: 8, xp: 10, explanation: "4-dən başlayıb 4 addım irəli sayırıq: 5, 6, 7, 8. Deməli 4 + 4 = 8.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l2-t6", type: "numeric", prompt: "7 + 2 = ?", answer: 9, xp: 10, explanation: "7-dən başlayıb 2 addım irəli sayırıq: 8, 9. Deməli 7 + 2 = 9.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l2-t7", type: "numeric", prompt: "6 + 3 = ?", answer: 9, xp: 10, explanation: "6-dən başlayıb 3 addım irəli sayırıq: 7, 8, 9. Deməli 6 + 3 = 9.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l2-t8", type: "numeric", prompt: "5 + 4 = ?", answer: 9, xp: 10, explanation: "5-dən başlayıb 4 addım irəli sayırıq: 6, 7, 8, 9. Deməli 5 + 4 = 9.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l2-t9", type: "numeric", prompt: "5 + 5 = ?", answer: 10, xp: 10, explanation: "5-dən başlayıb 5 addım irəli sayırıq: 6, 7, 8, 9, 10. Deməli 5 + 5 = 10.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l2-t10", type: "numeric", prompt: "6 + 4 = ?", answer: 10, xp: 10, explanation: "6-dən başlayıb 4 addım irəli sayırıq: 7, 8, 9, 10. Deməli 6 + 4 = 10.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l2-t11", type: "numeric", prompt: "7 + 3 = ?", answer: 10, xp: 10, explanation: "7-dən başlayıb 3 addım irəli sayırıq: 8, 9, 10. Deməli 7 + 3 = 10.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l2-t12", type: "numeric", prompt: "8 + 2 = ?", answer: 10, xp: 10, explanation: "8-dən başlayıb 2 addım irəli sayırıq: 9, 10. Deməli 8 + 2 = 10.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l2-t13", type: "numeric", prompt: "9 + 1 = ?", answer: 10, xp: 10, explanation: "9-dən başlayıb 1 addım irəli sayırıq: 10. Deməli 9 + 1 = 10.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l2-t14", type: "numeric", prompt: "8 + 1 = ?", answer: 9, xp: 10, explanation: "8-dən başlayıb 1 addım irəli sayırıq: 9. Deməli 8 + 1 = 9.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l2-t15", type: "numeric", prompt: "7 + 1 = ?", answer: 8, xp: 15, explanation: "7-dən başlayıb 1 addım irəli sayırıq: 8. Deməli 7 + 1 = 8.", skills: ["arith.add.basic"] },
          ],
          bonusTasks: [
            { id: "ry1-toplama-l2-b1", type: "numeric", prompt: "3 + 3 + 4 = ?", answer: 10, xp: 15, explanation: "Soldan başlayırıq: əvvəl 3 + 3 = 6, sonra 6 + 4 = 10.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l2-b2", type: "numeric", prompt: "2 + 4 + 4 = ?", answer: 10, xp: 15, explanation: "Soldan başlayırıq: əvvəl 2 + 4 = 6, sonra 6 + 4 = 10.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l2-b3", type: "multiple_choice", prompt: "6-ya nə əlavə etsək 10 alınar?", options: ["4", "3", "5", "2"], correctIndex: 0, xp: 15, explanation: "10 olmaq üçün 6-nın üstünə nə lazımdır? 6-dan 10-a qədər sayaq: 7, 8, 9, 10 — bu 4 addımdır. Deməli 4.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l2-b4", type: "multiple_choice", prompt: "7-yə nə əlavə etsək 10 alınar?", options: ["3", "2", "4", "1"], correctIndex: 0, xp: 15, explanation: "7-dən 10-a qədər sayaq: 8, 9, 10 — bu 3 addımdır. Deməli 3.", skills: ["arith.add.basic"] },
            { id: "ry1-toplama-l2-b5", type: "numeric", prompt: "5 + 2 + 3 = ?", answer: 10, xp: 15, explanation: "Soldan başlayırıq: əvvəl 5 + 2 = 7, sonra 7 + 3 = 10.", skills: ["arith.add.basic"] },
          ],
        },
        {
          id: "ry1-cixma-l1",
          title: "Kiçik çıxma",
          intro: "Çıxma — azaltmaq deməkdir. 5 − 2 = 3.",
          sections: [
            { heading: "Çıxma", body: "Bir qrupdan bir neçəsini götürəndə çıxma edirik: 🍎🍎🍎🍎🍎 -dən 2 alma götürsək 3 qalır. Yəni 5 − 2 = 3." },
          ],
          tasks: [
            { id: "ry1-cixma-l1-t1", type: "numeric", prompt: "2 − 1 = ?", answer: 1, xp: 10, explanation: "2-dən başlayıb 1 addım geri sayırıq: 1. Deməli 2 − 1 = 1.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l1-t2", type: "numeric", prompt: "3 − 1 = ?", answer: 2, xp: 10, explanation: "3-dən başlayıb 1 addım geri sayırıq: 2. Deməli 3 − 1 = 2.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l1-t3", type: "numeric", prompt: "3 − 2 = ?", answer: 1, xp: 10, explanation: "3-dən başlayıb 2 addım geri sayırıq: 2, 1. Deməli 3 − 2 = 1.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l1-t4", type: "numeric", prompt: "4 − 1 = ?", answer: 3, xp: 10, explanation: "4-dən başlayıb 1 addım geri sayırıq: 3. Deməli 4 − 1 = 3.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l1-t5", type: "numeric", prompt: "4 − 2 = ?", answer: 2, xp: 10, explanation: "4-dən başlayıb 2 addım geri sayırıq: 3, 2. Deməli 4 − 2 = 2.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l1-t6", type: "numeric", prompt: "5 − 2 = ?", answer: 3, xp: 10, explanation: "5-dən başlayıb 2 addım geri sayırıq: 4, 3. Deməli 5 − 2 = 3.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l1-t7", type: "numeric", prompt: "5 − 3 = ?", answer: 2, xp: 10, explanation: "5-dən başlayıb 3 addım geri sayırıq: 4, 3, 2. Deməli 5 − 3 = 2.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l1-t8", type: "numeric", prompt: "5 − 1 = ?", answer: 4, xp: 10, explanation: "5-dən başlayıb 1 addım geri sayırıq: 4. Deməli 5 − 1 = 4.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l1-t9", type: "numeric", prompt: "6 − 2 = ?", answer: 4, xp: 10, explanation: "6-dən başlayıb 2 addım geri sayırıq: 5, 4. Deməli 6 − 2 = 4.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l1-t10", type: "numeric", prompt: "6 − 3 = ?", answer: 3, xp: 10, explanation: "6-dən başlayıb 3 addım geri sayırıq: 5, 4, 3. Deməli 6 − 3 = 3.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l1-t11", type: "numeric", prompt: "4 − 4 = ?", answer: 0, xp: 10, explanation: "Nə qədər var idisə, hamısını götürdük — heç nə qalmır: 4 − 4 = 0.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l1-t12", type: "numeric", prompt: "3 − 0 = ?", answer: 3, xp: 10, explanation: "Heç nə götürmürük, ona görə ədəd dəyişmir: 3 − 0 = 3.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l1-t13", type: "multiple_choice", prompt: "⭐⭐⭐⭐ -dən 1 götürsək neçə qalır?", options: ["3", "4", "2", "5"], correctIndex: 0, xp: 10, explanation: "4 ulduzdan 1-ni götürürük: 4-dən 1 addım geri — 3. Deməli 3 qalır.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l1-t14", type: "multiple_choice", prompt: "🍎🍎🍎🍎🍎 -dən 2 götürsək neçə qalır?", options: ["3", "2", "4", "5"], correctIndex: 0, xp: 10, explanation: "5 almadan 2-ni götürürük: 5-dən geri sayırıq — 4, 3. Deməli 3 qalır.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l1-t15", type: "numeric", prompt: "6 − 1 = ?", answer: 5, xp: 15, explanation: "6-dən başlayıb 1 addım geri sayırıq: 5. Deməli 6 − 1 = 5.", skills: ["arith.sub.basic"] },
          ],
          bonusTasks: [
            { id: "ry1-cixma-l1-b1", type: "numeric", prompt: "5 − 5 = ?", answer: 0, xp: 15, explanation: "Nə qədər var idisə, hamısını götürdük — heç nə qalmır: 5 − 5 = 0.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l1-b2", type: "numeric", prompt: "6 − 4 = ?", answer: 2, xp: 15, explanation: "6-dən başlayıb 4 addım geri sayırıq: 5, 4, 3, 2. Deməli 6 − 4 = 2.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l1-b3", type: "numeric", prompt: "6 − 5 = ?", answer: 1, xp: 15, explanation: "6-dən başlayıb 5 addım geri sayırıq: 5, 4, 3, 2, 1. Deməli 6 − 5 = 1.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l1-b4", type: "numeric", prompt: "4 − 3 = ?", answer: 1, xp: 15, explanation: "4-dən başlayıb 3 addım geri sayırıq: 3, 2, 1. Deməli 4 − 3 = 1.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l1-b5", type: "numeric", prompt: "5 − 0 = ?", answer: 5, xp: 15, explanation: "Heç nə götürmürük, ona görə ədəd dəyişmir: 5 − 0 = 5.", skills: ["arith.sub.basic"] },
          ],
        },
        {
          id: "ry1-cixma-l2",
          title: "10-dan çıxma",
          intro: "Böyük ədədlərdən çıxma.",
          sections: [
            { heading: "10-dan çıx", body: "10-dan çıxma: 10 − 4 = 6, 10 − 7 = 3. 8, 9-dan da çıx: 9 − 3 = 6." },
          ],
          tasks: [
            { id: "ry1-cixma-l2-t1", type: "numeric", prompt: "7 − 2 = ?", answer: 5, xp: 10, explanation: "7-dən başlayıb 2 addım geri sayırıq: 6, 5. Deməli 7 − 2 = 5.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l2-t2", type: "numeric", prompt: "7 − 3 = ?", answer: 4, xp: 10, explanation: "7-dən başlayıb 3 addım geri sayırıq: 6, 5, 4. Deməli 7 − 3 = 4.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l2-t3", type: "numeric", prompt: "8 − 2 = ?", answer: 6, xp: 10, explanation: "8-dən başlayıb 2 addım geri sayırıq: 7, 6. Deməli 8 − 2 = 6.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l2-t4", type: "numeric", prompt: "8 − 4 = ?", answer: 4, xp: 10, explanation: "8-dən başlayıb 4 addım geri sayırıq: 7, 6, 5, 4. Deməli 8 − 4 = 4.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l2-t5", type: "numeric", prompt: "9 − 3 = ?", answer: 6, xp: 10, explanation: "9-dən başlayıb 3 addım geri sayırıq: 8, 7, 6. Deməli 9 − 3 = 6.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l2-t6", type: "numeric", prompt: "9 − 5 = ?", answer: 4, xp: 10, explanation: "9-dən başlayıb 5 addım geri sayırıq: 8, 7, 6, 5, 4. Deməli 9 − 5 = 4.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l2-t7", type: "numeric", prompt: "10 − 1 = ?", answer: 9, xp: 10, explanation: "10-dən başlayıb 1 addım geri sayırıq: 9. Deməli 10 − 1 = 9.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l2-t8", type: "numeric", prompt: "10 − 2 = ?", answer: 8, xp: 10, explanation: "10-dən başlayıb 2 addım geri sayırıq: 9, 8. Deməli 10 − 2 = 8.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l2-t9", type: "numeric", prompt: "10 − 5 = ?", answer: 5, xp: 10, explanation: "10-dən başlayıb 5 addım geri sayırıq: 9, 8, 7, 6, 5. Deməli 10 − 5 = 5.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l2-t10", type: "numeric", prompt: "10 − 4 = ?", answer: 6, xp: 10, explanation: "10-dən başlayıb 4 addım geri sayırıq: 9, 8, 7, 6. Deməli 10 − 4 = 6.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l2-t11", type: "numeric", prompt: "10 − 7 = ?", answer: 3, xp: 10, explanation: "10-dən başlayıb 7 addım geri sayırıq: 9, 8, 7, 6, 5, 4, 3. Deməli 10 − 7 = 3.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l2-t12", type: "numeric", prompt: "10 − 10 = ?", answer: 0, xp: 10, explanation: "Nə qədər var idisə, hamısını götürdük — heç nə qalmır: 10 − 10 = 0.", skills: ["arith.sub.no_borrow"] },
            { id: "ry1-cixma-l2-t13", type: "numeric", prompt: "8 − 3 = ?", answer: 5, xp: 10, explanation: "8-dən başlayıb 3 addım geri sayırıq: 7, 6, 5. Deməli 8 − 3 = 5.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l2-t14", type: "numeric", prompt: "9 − 4 = ?", answer: 5, xp: 10, explanation: "9-dən başlayıb 4 addım geri sayırıq: 8, 7, 6, 5. Deməli 9 − 4 = 5.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l2-t15", type: "numeric", prompt: "10 − 6 = ?", answer: 4, xp: 15, explanation: "10-dən başlayıb 6 addım geri sayırıq: 9, 8, 7, 6, 5, 4. Deməli 10 − 6 = 4.", skills: ["arith.sub.basic"] },
          ],
          bonusTasks: [
            { id: "ry1-cixma-l2-b1", type: "numeric", prompt: "10 − 8 = ?", answer: 2, xp: 15, explanation: "10-dən başlayıb 8 addım geri sayırıq: 9, 8, 7, 6, 5, 4, 3, 2. Deməli 10 − 8 = 2.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l2-b2", type: "numeric", prompt: "9 − 9 = ?", answer: 0, xp: 15, explanation: "Nə qədər var idisə, hamısını götürdük — heç nə qalmır: 9 − 9 = 0.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l2-b3", type: "multiple_choice", prompt: "10-dan nə çıxsaq 3 qalar?", options: ["7", "6", "8", "5"], correctIndex: 0, xp: 15, explanation: "10-dan nə çıxsa 3 qalır? 3-dən 10-a qədər sayaq: 4, 5, 6, 7, 8, 9, 10 — bu 7 addımdır. Deməli 7.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l2-b4", type: "numeric", prompt: "8 − 6 = ?", answer: 2, xp: 15, explanation: "8-dən başlayıb 6 addım geri sayırıq: 7, 6, 5, 4, 3, 2. Deməli 8 − 6 = 2.", skills: ["arith.sub.basic"] },
            { id: "ry1-cixma-l2-b5", type: "numeric", prompt: "10 − 3 = ?", answer: 7, xp: 15, explanation: "10-dən başlayıb 3 addım geri sayırıq: 9, 8, 7. Deməli 10 − 3 = 7.", skills: ["arith.sub.basic"] },
          ],
        },
        {
          id: "ry1-hesab10-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry1-hesab10-mesq",
          title: "Məşq",
          intro: "Toplama və çıxmanı birlikdə məşq edək!",
          sections: [
            { heading: "Yadına salaq", body: "Toplama (+) artırır: 3 + 2 = 5. Çıxma (−) azaldır: 5 − 2 = 3." },
          ],
          tasks: [
            { id: "ry1-hesab10-mesq-t1", type: "numeric", prompt: "4 + 3 = ?", answer: 7, xp: 10, explanation: "4-dən başlayıb 3 addım irəli sayırıq: 5, 6, 7. Deməli 4 + 3 = 7.", skills: ["arith.add.basic"] },
            { id: "ry1-hesab10-mesq-t2", type: "numeric", prompt: "6 + 2 = ?", answer: 8, xp: 10, explanation: "6-dən başlayıb 2 addım irəli sayırıq: 7, 8. Deməli 6 + 2 = 8.", skills: ["arith.add.basic"] },
            { id: "ry1-hesab10-mesq-t3", type: "numeric", prompt: "9 − 4 = ?", answer: 5, xp: 10, explanation: "9-dən başlayıb 4 addım geri sayırıq: 8, 7, 6, 5. Deməli 9 − 4 = 5.", skills: ["arith.sub.basic"] },
            { id: "ry1-hesab10-mesq-t4", type: "numeric", prompt: "7 − 3 = ?", answer: 4, xp: 10, explanation: "7-dən başlayıb 3 addım geri sayırıq: 6, 5, 4. Deməli 7 − 3 = 4.", skills: ["arith.sub.basic"] },
            { id: "ry1-hesab10-mesq-t5", type: "numeric", prompt: "5 + 5 = ?", answer: 10, xp: 10, explanation: "5-dən başlayıb 5 addım irəli sayırıq: 6, 7, 8, 9, 10. Deməli 5 + 5 = 10.", skills: ["arith.add.basic"] },
            { id: "ry1-hesab10-mesq-t6", type: "numeric", prompt: "10 − 6 = ?", answer: 4, xp: 10, explanation: "10-dən başlayıb 6 addım geri sayırıq: 9, 8, 7, 6, 5, 4. Deməli 10 − 6 = 4.", skills: ["arith.sub.basic"] },
            { id: "ry1-hesab10-mesq-t7", type: "numeric", prompt: "Nərgizin 3 şarı var idi, 2 şar da aldı. İndi neçə şarı var?", answer: 5, xp: 10, explanation: "Əvvəl 3 şar var idi, üstünə 2 şar gəldi: 3-dən 2 addım irəli — 4, 5. Deməli 5 şarı var.", skills: ["problem.one_step","arith.add.basic"] },
            { id: "ry1-hesab10-mesq-t8", type: "numeric", prompt: "Budaqda 8 quş var idi, 3-ü uçdu. Neçə quş qaldı?", answer: 5, xp: 10, explanation: "8 quşdan 3-ü uçdu, yəni azaldı: 8-dən 3 addım geri — 7, 6, 5. Deməli 5 quş qaldı.", skills: ["problem.one_step","arith.sub.basic"] },
            { id: "ry1-hesab10-mesq-t9", type: "numeric", prompt: "2 + 2 + 2 = ?", answer: 6, xp: 10, explanation: "Soldan başlayırıq: əvvəl 2 + 2 = 4, sonra 4 + 2 = 6.", skills: ["arith.add.basic"] },
            { id: "ry1-hesab10-mesq-t10", type: "numeric", prompt: "10 − 5 = ?", answer: 5, xp: 10, explanation: "10-dən başlayıb 5 addım geri sayırıq: 9, 8, 7, 6, 5. Deməli 10 − 5 = 5.", skills: ["arith.sub.basic"] },
          ],
          bonusTasks: [
            { id: "ry1-hesab10-mesq-b1", type: "numeric", prompt: "3 + ? = 9", answer: 6, xp: 15, explanation: "3-ün üstünə nə gəlsə 9 olar? 3-dən 9-a qədər sayaq: 4, 5, 6, 7, 8, 9 — bu 6 addımdır. Deməli 6.", skills: ["arith.inverse"] },
            { id: "ry1-hesab10-mesq-b2", type: "numeric", prompt: "? − 4 = 3", answer: 7, xp: 15, explanation: "Nədən 4 çıxsa 3 qalar? Geri yox, İRƏLİ düşünürük: 3 + 4 = 7. Yoxlayaq: 7 − 4 = 3. ✓", skills: ["arith.inverse"] },
            { id: "ry1-hesab10-mesq-b3", type: "numeric", prompt: "Anar 4 konfet yedi, 4 konfeti də qaldı. Əvvəlcə neçə konfeti var idi?", answer: 8, xp: 15, explanation: "Yeyilən 4, qalan 4 — əvvəlcə hamısı birlikdə var idi: 4 + 4 = 8 konfet.", skills: ["problem.one_step","arith.add.basic"] },
            { id: "ry1-hesab10-mesq-b4", type: "numeric", prompt: "6 + 4 − 2 = ?", answer: 8, xp: 15, explanation: "Soldan başlayırıq: əvvəl 6 + 4 = 10, sonra 10 − 2 = 8.", skills: ["arith.add.basic"] },
            { id: "ry1-hesab10-mesq-b5", type: "numeric", prompt: "10 − 3 − 3 = ?", answer: 4, xp: 15, explanation: "Soldan başlayırıq: əvvəl 10 − 3 = 7, sonra 7 − 3 = 4.", skills: ["arith.sub.basic"] },
          ],
        },
        {
          id: "ry1-hesab10-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    {
      id: "ry1-eded20",
      title: "Ədədlər 11-20",
      description: "11-20 arası ədədlər, toplama və çıxma.",
      lessons: [
        {
          id: "ry1-onluq-l1",
          title: "11-dən 20-yə sayma",
          intro: "On birdən iyirmiyə qədər sayaq.",
          sections: [
            { heading: "Sayma", body: "11, 12, 13, 14, 15, 16, 17, 18, 19, 20. Bu ədədlər 'on' və bir rəqəmdən ibarətdir: on bir = 11, on beş = 15." },
          ],
          tasks: [
            { id: "ry1-onluq-l1-t1", type: "numeric", prompt: "11-dən sonra hansı ədəd gəlir?", answer: 12, xp: 10, explanation: "«Sonra gələn» 1 çox deməkdir: 11 + 1 = 12.", skills: ["number.count"] },
            { id: "ry1-onluq-l1-t2", type: "numeric", prompt: "12-dən sonra hansı ədəd gəlir?", answer: 13, xp: 10, explanation: "«Sonra gələn» 1 çox deməkdir: 12 + 1 = 13.", skills: ["number.count"] },
            { id: "ry1-onluq-l1-t3", type: "numeric", prompt: "14-dən sonra hansı ədəd gəlir?", answer: 15, xp: 10, explanation: "«Sonra gələn» 1 çox deməkdir: 14 + 1 = 15.", skills: ["number.count"] },
            { id: "ry1-onluq-l1-t4", type: "numeric", prompt: "15-dən sonra hansı ədəd gəlir?", answer: 16, xp: 10, explanation: "«Sonra gələn» 1 çox deməkdir: 15 + 1 = 16.", skills: ["number.count"] },
            { id: "ry1-onluq-l1-t5", type: "numeric", prompt: "19-dan sonra hansı ədəd gəlir?", answer: 20, xp: 10, explanation: "«Sonra gələn» 1 çox deməkdir: 19 + 1 = 20.", skills: ["number.count"] },
            { id: "ry1-onluq-l1-t6", type: "multiple_choice", prompt: "'on bir' ədədi rəqəmlə necə yazılır?", options: ["11", "10", "12", "1"], correctIndex: 0, xp: 10, explanation: "«On bir» = 1 onluq + 1 tək. Əvvəl onluğu, sonra təki yazırıq → 11.", skills: ["number.place_value"] },
            { id: "ry1-onluq-l1-t7", type: "multiple_choice", prompt: "'on beş' ədədi rəqəmlə necə yazılır?", options: ["15", "50", "14", "16"], correctIndex: 0, xp: 10, explanation: "«On beş» = 1 onluq + 5 tək → 15. (50 isə «əlli» olardı.)", skills: ["number.place_value"] },
            { id: "ry1-onluq-l1-t8", type: "multiple_choice", prompt: "'iyirmi' ədədi rəqəmlə necə yazılır?", options: ["20", "12", "2", "200"], correctIndex: 0, xp: 10, explanation: "«İyirmi» iki tam onluqdur: 2 onluq və 0 tək → 20.", skills: ["number.place_value"] },
            { id: "ry1-onluq-l1-t9", type: "numeric", prompt: "13-dən əvvəl gələn ədəd hansıdır?", answer: 12, xp: 10, explanation: "«Əvvəl gələn» 1 az deməkdir: 13 − 1 = 12.", skills: ["number.count"] },
            { id: "ry1-onluq-l1-t10", type: "numeric", prompt: "16-dan əvvəl gələn ədəd hansıdır?", answer: 15, xp: 10, explanation: "«Əvvəl gələn» 1 az deməkdir: 16 − 1 = 15.", skills: ["number.count"] },
            { id: "ry1-onluq-l1-t11", type: "numeric", prompt: "20-dən əvvəl gələn ədəd hansıdır?", answer: 19, xp: 10, explanation: "«Əvvəl gələn» 1 az deməkdir: 20 − 1 = 19.", skills: ["number.count"] },
            { id: "ry1-onluq-l1-t12", type: "multiple_choice", prompt: "13 və 17 ədədlərindən böyüyü hansıdır?", options: ["17", "13", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "Hər ikisi 1 onluqdur, ona görə təklərə baxırıq: 7 > 3. Deməli 17 böyükdür.", skills: ["number.compare"] },
            { id: "ry1-onluq-l1-t13", type: "multiple_choice", prompt: "11 və 15 ədədlərindən kiçiyi hansıdır?", options: ["11", "15", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "Hər ikisi 1 onluqdur, təklərə baxırıq: 1 < 5. Deməli 11 kiçikdir.", skills: ["number.compare"] },
            { id: "ry1-onluq-l1-t14", type: "numeric", prompt: "17-dən sonra hansı ədəd gəlir?", answer: 18, xp: 10, explanation: "«Sonra gələn» 1 çox deməkdir: 17 + 1 = 18.", skills: ["number.count"] },
            { id: "ry1-onluq-l1-t15", type: "numeric", prompt: "10-dan sonra hansı ədəd gəlir?", answer: 11, xp: 15, explanation: "«Sonra gələn» 1 çox deməkdir: 10 + 1 = 11.", skills: ["number.count"] },
          ],
          bonusTasks: [
            { id: "ry1-onluq-l1-b1", type: "numeric", prompt: "14, 18, 12 ədədlərindən ən böyüyü hansıdır?", answer: 18, xp: 15, explanation: "Üçü də 1 onluqdur, təklərə baxırıq: 8 > 4 > 2. Ən böyüyü 18-dir.", skills: ["number.compare"] },
            { id: "ry1-onluq-l1-b2", type: "numeric", prompt: "16, 11, 19 ədədlərindən ən kiçiyi hansıdır?", answer: 11, xp: 15, explanation: "Üçü də 1 onluqdur, təklərə baxırıq: 1 < 6 < 9. Ən kiçiyi 11-dir.", skills: ["number.compare"] },
            { id: "ry1-onluq-l1-b3", type: "multiple_choice", prompt: "15 ədədi neçə onluq və neçə təkdən ibarətdir?", options: ["1 onluq 5 tək", "5 onluq 1 tək", "15 tək", "2 onluq"], correctIndex: 0, xp: 15, explanation: "15-i onluq və təkə ayırırıq: 10 + 5. Yəni 1 onluq və 5 tək.", skills: ["number.place_value"] },
            { id: "ry1-onluq-l1-b4", type: "numeric", prompt: "18-dən əvvəl gələn ədəd hansıdır?", answer: 17, xp: 15, explanation: "«Əvvəl gələn» 1 az deməkdir: 18 − 1 = 17.", skills: ["number.count"] },
            { id: "ry1-onluq-l1-b5", type: "numeric", prompt: "12 və 20 arasında 15-dən 1 böyük ədəd hansıdır?", answer: 16, xp: 15, explanation: "«15-dən 1 böyük» deməkdir 15 + 1 = 16. 16 isə 12 ilə 20 arasındadır. ✓", skills: ["number.count"] },
          ],
        },
        {
          id: "ry1-yirmi-l1",
          title: "10-dan yuxarı toplama",
          intro: "10-a bir neçə əlavə edək.",
          sections: [
            { heading: "10 + tək", body: "10 + 3 = 13, 10 + 5 = 15. Onluğa təkləri əlavə edirik." },
          ],
          tasks: [
            { id: "ry1-yirmi-l1-t1", type: "numeric", prompt: "10 + 1 = ?", answer: 11, xp: 10, explanation: "10 bir tam onluqdur. Üstünə 1 tək gəlir, onluq yerində qalır: 10 + 1 = 11.", skills: ["arith.add.no_carry"] },
            { id: "ry1-yirmi-l1-t2", type: "numeric", prompt: "10 + 2 = ?", answer: 12, xp: 10, explanation: "10 bir tam onluqdur. Üstünə 2 tək gəlir, onluq yerində qalır: 10 + 2 = 12.", skills: ["arith.add.no_carry"] },
            { id: "ry1-yirmi-l1-t3", type: "numeric", prompt: "10 + 3 = ?", answer: 13, xp: 10, explanation: "10 bir tam onluqdur. Üstünə 3 tək gəlir, onluq yerində qalır: 10 + 3 = 13.", skills: ["arith.add.no_carry"] },
            { id: "ry1-yirmi-l1-t4", type: "numeric", prompt: "10 + 5 = ?", answer: 15, xp: 10, explanation: "10 bir tam onluqdur. Üstünə 5 tək gəlir, onluq yerində qalır: 10 + 5 = 15.", skills: ["arith.add.no_carry"] },
            { id: "ry1-yirmi-l1-t5", type: "numeric", prompt: "10 + 7 = ?", answer: 17, xp: 10, explanation: "10 bir tam onluqdur. Üstünə 7 tək gəlir, onluq yerində qalır: 10 + 7 = 17.", skills: ["arith.add.no_carry"] },
            { id: "ry1-yirmi-l1-t6", type: "numeric", prompt: "10 + 9 = ?", answer: 19, xp: 10, explanation: "10 bir tam onluqdur. Üstünə 9 tək gəlir, onluq yerində qalır: 10 + 9 = 19.", skills: ["arith.add.no_carry"] },
            { id: "ry1-yirmi-l1-t7", type: "numeric", prompt: "11 + 2 = ?", answer: 13, xp: 10, explanation: "11 = 1 onluq + 1 tək. Onluğa toxunmuruq, təkləri toplayırıq: 1 + 2 = 3. Deməli 13.", skills: ["arith.add.no_carry"] },
            { id: "ry1-yirmi-l1-t8", type: "numeric", prompt: "12 + 3 = ?", answer: 15, xp: 10, explanation: "12 = 1 onluq + 2 tək. Onluğa toxunmuruq, təkləri toplayırıq: 2 + 3 = 5. Deməli 15.", skills: ["arith.add.no_carry"] },
            { id: "ry1-yirmi-l1-t9", type: "numeric", prompt: "13 + 2 = ?", answer: 15, xp: 10, explanation: "13 = 1 onluq + 3 tək. Onluğa toxunmuruq, təkləri toplayırıq: 3 + 2 = 5. Deməli 15.", skills: ["arith.add.no_carry"] },
            { id: "ry1-yirmi-l1-t10", type: "numeric", prompt: "14 + 3 = ?", answer: 17, xp: 10, explanation: "14 = 1 onluq + 4 tək. Onluğa toxunmuruq, təkləri toplayırıq: 4 + 3 = 7. Deməli 17.", skills: ["arith.add.no_carry"] },
            { id: "ry1-yirmi-l1-t11", type: "numeric", prompt: "15 + 4 = ?", answer: 19, xp: 10, explanation: "15 = 1 onluq + 5 tək. Onluğa toxunmuruq, təkləri toplayırıq: 5 + 4 = 9. Deməli 19.", skills: ["arith.add.no_carry"] },
            { id: "ry1-yirmi-l1-t12", type: "numeric", prompt: "16 + 2 = ?", answer: 18, xp: 10, explanation: "16 = 1 onluq + 6 tək. Onluğa toxunmuruq, təkləri toplayırıq: 6 + 2 = 8. Deməli 18.", skills: ["arith.add.no_carry"] },
            { id: "ry1-yirmi-l1-t13", type: "numeric", prompt: "18 + 2 = ?", answer: 20, xp: 10, explanation: "18 = 1 onluq + 8 tək. Onluğa toxunmuruq, təkləri toplayırıq: 8 + 2 = 10. Deməli 20.", skills: ["arith.add.carry"] },
            { id: "ry1-yirmi-l1-t14", type: "numeric", prompt: "10 + 10 = ?", answer: 20, xp: 10, explanation: "10 + 10 iki tam onluq deməkdir, iki onluq isə 20-dir.", skills: ["arith.add.no_carry"] },
            { id: "ry1-yirmi-l1-t15", type: "numeric", prompt: "17 + 2 = ?", answer: 19, xp: 15, explanation: "17 = 1 onluq + 7 tək. Onluğa toxunmuruq, təkləri toplayırıq: 7 + 2 = 9. Deməli 19.", skills: ["arith.add.no_carry"] },
          ],
          bonusTasks: [
            { id: "ry1-yirmi-l1-b1", type: "numeric", prompt: "11 + 5 = ?", answer: 16, xp: 15, explanation: "11 = 1 onluq + 1 tək. Onluğa toxunmuruq, təkləri toplayırıq: 1 + 5 = 6. Deməli 16.", skills: ["arith.add.no_carry"] },
            { id: "ry1-yirmi-l1-b2", type: "numeric", prompt: "13 + 4 = ?", answer: 17, xp: 15, explanation: "13 = 1 onluq + 3 tək. Onluğa toxunmuruq, təkləri toplayırıq: 3 + 4 = 7. Deməli 17.", skills: ["arith.add.no_carry"] },
            { id: "ry1-yirmi-l1-b3", type: "numeric", prompt: "15 + 5 = ?", answer: 20, xp: 15, explanation: "15 = 1 onluq + 5 tək. Onluğa toxunmuruq, təkləri toplayırıq: 5 + 5 = 10. Deməli 20.", skills: ["arith.add.carry"] },
            { id: "ry1-yirmi-l1-b4", type: "numeric", prompt: "12 + 6 = ?", answer: 18, xp: 15, explanation: "12 = 1 onluq + 2 tək. Onluğa toxunmuruq, təkləri toplayırıq: 2 + 6 = 8. Deməli 18.", skills: ["arith.add.no_carry"] },
            { id: "ry1-yirmi-l1-b5", type: "numeric", prompt: "16 + 3 = ?", answer: 19, xp: 15, explanation: "16 = 1 onluq + 6 tək. Onluğa toxunmuruq, təkləri toplayırıq: 6 + 3 = 9. Deməli 19.", skills: ["arith.add.no_carry"] },
          ],
        },
        {
          id: "ry1-yirmi-l2",
          title: "20 dairəsində çıxma",
          intro: "20-yə qədər ədədlərdən çıxaq.",
          sections: [
            { heading: "Çıxma", body: "13 − 3 = 10, 15 − 5 = 10, 20 − 10 = 10. Əvvəlcə təkləri çıxırıq." },
          ],
          tasks: [
            { id: "ry1-yirmi-l2-t1", type: "numeric", prompt: "12 − 2 = ?", answer: 10, xp: 10, explanation: "12 = 1 onluq + 2 tək. Bütün 2 təki götürəndə təmiz onluq qalır: 12 − 2 = 10.", skills: ["arith.sub.basic"] },
            { id: "ry1-yirmi-l2-t2", type: "numeric", prompt: "13 − 3 = ?", answer: 10, xp: 10, explanation: "13 = 1 onluq + 3 tək. Bütün 3 təki götürəndə təmiz onluq qalır: 13 − 3 = 10.", skills: ["arith.sub.basic"] },
            { id: "ry1-yirmi-l2-t3", type: "numeric", prompt: "15 − 5 = ?", answer: 10, xp: 10, explanation: "15 = 1 onluq + 5 tək. Bütün 5 təki götürəndə təmiz onluq qalır: 15 − 5 = 10.", skills: ["arith.sub.basic"] },
            { id: "ry1-yirmi-l2-t4", type: "numeric", prompt: "11 − 1 = ?", answer: 10, xp: 10, explanation: "11 = 1 onluq + 1 tək. Bütün 1 təki götürəndə təmiz onluq qalır: 11 − 1 = 10.", skills: ["arith.sub.basic"] },
            { id: "ry1-yirmi-l2-t5", type: "numeric", prompt: "14 − 2 = ?", answer: 12, xp: 10, explanation: "14 = 1 onluq + 4 tək. Onluğa toxunmuruq, təklərdən çıxırıq: 4 − 2 = 2. Deməli 12.", skills: ["arith.sub.basic"] },
            { id: "ry1-yirmi-l2-t6", type: "numeric", prompt: "16 − 3 = ?", answer: 13, xp: 10, explanation: "16 = 1 onluq + 6 tək. Onluğa toxunmuruq, təklərdən çıxırıq: 6 − 3 = 3. Deməli 13.", skills: ["arith.sub.basic"] },
            { id: "ry1-yirmi-l2-t7", type: "numeric", prompt: "18 − 4 = ?", answer: 14, xp: 10, explanation: "18 = 1 onluq + 8 tək. Onluğa toxunmuruq, təklərdən çıxırıq: 8 − 4 = 4. Deməli 14.", skills: ["arith.sub.basic"] },
            { id: "ry1-yirmi-l2-t8", type: "numeric", prompt: "19 − 5 = ?", answer: 14, xp: 10, explanation: "19 = 1 onluq + 9 tək. Onluğa toxunmuruq, təklərdən çıxırıq: 9 − 5 = 4. Deməli 14.", skills: ["arith.sub.basic"] },
            { id: "ry1-yirmi-l2-t9", type: "numeric", prompt: "20 − 10 = ?", answer: 10, xp: 10, explanation: "20 iki onluqdur. Bir onluğu (10) götürəndə bir onluq qalır: 20 − 10 = 10.", skills: ["arith.sub.no_borrow"] },
            { id: "ry1-yirmi-l2-t10", type: "numeric", prompt: "17 − 2 = ?", answer: 15, xp: 10, explanation: "17 = 1 onluq + 7 tək. Onluğa toxunmuruq, təklərdən çıxırıq: 7 − 2 = 5. Deməli 15.", skills: ["arith.sub.basic"] },
            { id: "ry1-yirmi-l2-t11", type: "numeric", prompt: "20 − 5 = ?", answer: 15, xp: 10, explanation: "20 = 1 onluq + 10 tək. Onluğa toxunmuruq, təklərdən çıxırıq: 10 − 5 = 5. Deməli 15.", skills: ["arith.sub.basic"] },
            { id: "ry1-yirmi-l2-t12", type: "numeric", prompt: "15 − 3 = ?", answer: 12, xp: 10, explanation: "15 = 1 onluq + 5 tək. Onluğa toxunmuruq, təklərdən çıxırıq: 5 − 3 = 2. Deməli 12.", skills: ["arith.sub.basic"] },
            { id: "ry1-yirmi-l2-t13", type: "numeric", prompt: "13 − 1 = ?", answer: 12, xp: 10, explanation: "13 = 1 onluq + 3 tək. Onluğa toxunmuruq, təklərdən çıxırıq: 3 − 1 = 2. Deməli 12.", skills: ["arith.sub.basic"] },
            { id: "ry1-yirmi-l2-t14", type: "numeric", prompt: "20 − 1 = ?", answer: 19, xp: 10, explanation: "20 = 1 onluq + 10 tək. Onluğa toxunmuruq, təklərdən çıxırıq: 10 − 1 = 9. Deməli 19.", skills: ["arith.sub.basic"] },
            { id: "ry1-yirmi-l2-t15", type: "numeric", prompt: "16 − 6 = ?", answer: 10, xp: 15, explanation: "16 = 1 onluq + 6 tək. Bütün 6 təki götürəndə təmiz onluq qalır: 16 − 6 = 10.", skills: ["arith.sub.basic"] },
          ],
          bonusTasks: [
            { id: "ry1-yirmi-l2-b1", type: "numeric", prompt: "18 − 8 = ?", answer: 10, xp: 15, explanation: "18 = 1 onluq + 8 tək. Bütün 8 təki götürəndə təmiz onluq qalır: 18 − 8 = 10.", skills: ["arith.sub.basic"] },
            { id: "ry1-yirmi-l2-b2", type: "numeric", prompt: "20 − 3 = ?", answer: 17, xp: 15, explanation: "20 = 1 onluq + 10 tək. Onluğa toxunmuruq, təklərdən çıxırıq: 10 − 3 = 7. Deməli 17.", skills: ["arith.sub.basic"] },
            { id: "ry1-yirmi-l2-b3", type: "numeric", prompt: "17 − 4 = ?", answer: 13, xp: 15, explanation: "17 = 1 onluq + 7 tək. Onluğa toxunmuruq, təklərdən çıxırıq: 7 − 4 = 3. Deməli 13.", skills: ["arith.sub.basic"] },
            { id: "ry1-yirmi-l2-b4", type: "numeric", prompt: "19 − 9 = ?", answer: 10, xp: 15, explanation: "19 = 1 onluq + 9 tək. Bütün 9 təki götürəndə təmiz onluq qalır: 19 − 9 = 10.", skills: ["arith.sub.basic"] },
            { id: "ry1-yirmi-l2-b5", type: "numeric", prompt: "14 − 4 = ?", answer: 10, xp: 15, explanation: "14 = 1 onluq + 4 tək. Bütün 4 təki götürəndə təmiz onluq qalır: 14 − 4 = 10.", skills: ["arith.sub.basic"] },
          ],
        },
        {
          id: "ry1-eded20-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry1-eded20-mesq",
          title: "Məşq",
          intro: "20-yə qədər ədədləri məşq edək!",
          sections: [
            { heading: "Yadına salaq", body: "11, 12, 13 ... 20. Onluqdan sonra: 10 + 3 = 13. Ədədin birinci rəqəmi onluğu, ikincisi təkliyi göstərir." },
          ],
          tasks: [
            { id: "ry1-eded20-mesq-t1", type: "numeric", prompt: "13-dən sonra hansı ədəd gəlir?", answer: 14, xp: 10, explanation: "«Sonra gələn» 1 çox deməkdir: 13 + 1 = 14.", skills: ["number.count"] },
            { id: "ry1-eded20-mesq-t2", type: "numeric", prompt: "17-dən əvvəl hansı ədəd gəlir?", answer: 16, xp: 10, explanation: "«Əvvəl gələn» 1 az deməkdir: 17 − 1 = 16.", skills: ["number.count"] },
            { id: "ry1-eded20-mesq-t3", type: "numeric", prompt: "10 + 5 = ?", answer: 15, xp: 10, explanation: "10 bir tam onluqdur. Üstünə 5 tək gəlir, onluq yerində qalır: 10 + 5 = 15.", skills: ["arith.add.no_carry"] },
            { id: "ry1-eded20-mesq-t4", type: "numeric", prompt: "10 + 8 = ?", answer: 18, xp: 10, explanation: "10 bir tam onluqdur. Üstünə 8 tək gəlir, onluq yerində qalır: 10 + 8 = 18.", skills: ["arith.add.no_carry"] },
            { id: "ry1-eded20-mesq-t5", type: "numeric", prompt: "12 + 3 = ?", answer: 15, xp: 10, explanation: "12 = 1 onluq + 2 tək. Onluğa toxunmuruq, təkləri toplayırıq: 2 + 3 = 5. Deməli 15.", skills: ["arith.add.no_carry"] },
            { id: "ry1-eded20-mesq-t6", type: "numeric", prompt: "16 − 4 = ?", answer: 12, xp: 10, explanation: "16 = 1 onluq + 6 tək. Onluğa toxunmuruq, təklərdən çıxırıq: 6 − 4 = 2. Deməli 12.", skills: ["arith.sub.basic"] },
            { id: "ry1-eded20-mesq-t7", type: "numeric", prompt: "20 − 10 = ?", answer: 10, xp: 10, explanation: "20 iki onluqdur. Bir onluğu götürəndə bir onluq qalır: 20 − 10 = 10.", skills: ["arith.sub.no_borrow"] },
            { id: "ry1-eded20-mesq-t8", type: "multiple_choice", prompt: "Hansı daha böyükdür?", options: ["18", "15", "12", "11"], correctIndex: 0, xp: 10, explanation: "Dördü də 1 onluqdur, ona görə təklərə baxırıq: 8 > 5 > 2 > 1. Ən böyüyü 18-dir.", skills: ["number.compare"] },
            { id: "ry1-eded20-mesq-t9", type: "numeric", prompt: "19-dan sonra hansı ədəd gəlir?", answer: 20, xp: 10, explanation: "«Sonra gələn» 1 çox deməkdir: 19 + 1 = 20.", skills: ["number.count"] },
            { id: "ry1-eded20-mesq-t10", type: "numeric", prompt: "14 + 5 = ?", answer: 19, xp: 10, explanation: "14 = 1 onluq + 4 tək. Onluğa toxunmuruq, təkləri toplayırıq: 4 + 5 = 9. Deməli 19.", skills: ["arith.add.no_carry"] },
          ],
          bonusTasks: [
            { id: "ry1-eded20-mesq-b1", type: "numeric", prompt: "11, 13, 15, ... — növbəti ədəd?", answer: 17, xp: 15, explanation: "Hər dəfə 2 artır: 11, 13, 15 — deməli növbəti 15 + 2 = 17.", skills: ["number.sequence"] },
            { id: "ry1-eded20-mesq-b2", type: "numeric", prompt: "10 + ? = 17", answer: 7, xp: 15, explanation: "10-un üstünə nə gəlsə 17 olar? 17 = 1 onluq + 7 tək, onluq artıq var. Deməli 7.", skills: ["arith.inverse"] },
            { id: "ry1-eded20-mesq-b3", type: "numeric", prompt: "Sinifdə 12 oğlan, 6 qız var. Cəmi neçə şagird var?", answer: 18, xp: 15, explanation: "«Cəmi» sözü toplama deməkdir: 12 + 6. Onluğa toxunmuruq, təkləri toplayırıq: 2 + 6 = 8 → 18 şagird.", skills: ["problem.one_step","arith.add.basic"] },
            { id: "ry1-eded20-mesq-b4", type: "numeric", prompt: "20 − 5 − 5 = ?", answer: 10, xp: 15, explanation: "Soldan başlayırıq: əvvəl 20 − 5 = 15, sonra 15 − 5 = 10.", skills: ["arith.sub.basic"] },
            { id: "ry1-eded20-mesq-b5", type: "numeric", prompt: "15 ədədində neçə onluq var?", answer: 1, xp: 15, explanation: "15 = 10 + 5, yəni bir tam onluq və 5 tək. Onluqların sayı 1-dir.", skills: ["number.place_value"] },
          ],
        },
        {
          id: "ry1-eded20-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    {
      id: "ry1-fiqur",
      title: "Fiqurlar və məsələlər",
      description: "Həndəsi fiqurlar və sadə mətn məsələləri.",
      lessons: [
        {
          id: "ry1-fiqur-l1",
          title: "Həndəsi fiqurlar",
          intro: "Dairə, kvadrat, üçbucaq, düzbucaqlını tanıyaq.",
          sections: [
            { heading: "Fiqurlar", body: "Dairə — dəyirmi (top kimi). Kvadrat — 4 bərabər tərəf. Üçbucaq — 3 tərəf. Düzbucaqlı — 4 tərəf (2-si uzun)." },
          ],
          tasks: [
            { id: "ry1-fiqur-l1-t1", type: "multiple_choice", prompt: "Üçbucağın neçə tərəfi var?", options: ["3", "4", "2", "5"], correctIndex: 0, xp: 10, explanation: "Üçbucağın adı «üç»dən gəlir — onun 3 tərəfi və 3 küncü var.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-l1-t2", type: "multiple_choice", prompt: "Kvadratın neçə tərəfi var?", options: ["4", "3", "5", "2"], correctIndex: 0, xp: 10, explanation: "Kvadratın 4 tərəfi var və hamısı bərabər uzunluqdadır.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-l1-t3", type: "multiple_choice", prompt: "Dəyirmi (top kimi) fiqur necə adlanır?", options: ["dairə", "kvadrat", "üçbucaq", "düzbucaqlı"], correctIndex: 0, xp: 10, explanation: "Küncü olmayan, hər tərəfi eyni cür əyri olan fiqur dairədir.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-l1-t4", type: "multiple_choice", prompt: "🔺 hansı fiqurdur?", options: ["üçbucaq", "kvadrat", "dairə", "düzbucaqlı"], correctIndex: 0, xp: 10, explanation: "🔺 fiqurunun 3 tərəfi və 3 küncü var — bu, üçbucaqdır.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-l1-t5", type: "multiple_choice", prompt: "⬛ hansı fiqurdur?", options: ["kvadrat", "dairə", "üçbucaq", "xətt"], correctIndex: 0, xp: 10, explanation: "⬛ fiqurunun 4 bərabər tərəfi var — bu, kvadratdır.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-l1-t6", type: "multiple_choice", prompt: "🔵 hansı fiqurdur?", options: ["dairə", "kvadrat", "üçbucaq", "düzbucaqlı"], correctIndex: 0, xp: 10, explanation: "🔵 fiqurunun heç bir küncü yoxdur, tam yumrudur — bu, dairədir.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-l1-t7", type: "multiple_choice", prompt: "Dairənin neçə küncü var?", options: ["0 (küncü yoxdur)", "3", "4", "1"], correctIndex: 0, xp: 10, explanation: "Dairə tam yumrudur, heç yerdə sınmır — ona görə küncü yoxdur, yəni 0.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-l1-t8", type: "multiple_choice", prompt: "Kvadratın neçə küncü var?", options: ["4", "3", "2", "0"], correctIndex: 0, xp: 10, explanation: "Kvadratın 4 tərəfi var; hər iki tərəfin birləşdiyi yerdə künc yaranır → 4 künc.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-l1-t9", type: "multiple_choice", prompt: "Üçbucağın neçə küncü var?", options: ["3", "4", "2", "0"], correctIndex: 0, xp: 10, explanation: "Üçbucağın 3 tərəfi var, hər birləşmə yerində bir künc → 3 künc.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-l1-t10", type: "multiple_choice", prompt: "Top hansı fiqura oxşayır?", options: ["dairə", "kvadrat", "üçbucaq", "düzbucaqlı"], correctIndex: 0, xp: 10, explanation: "Top hər tərəfdən yumrudur, küncü yoxdur — dairəyə oxşayır.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-l1-t11", type: "multiple_choice", prompt: "Kitab hansı fiqura oxşayır?", options: ["düzbucaqlı", "dairə", "üçbucaq", "top"], correctIndex: 0, xp: 10, explanation: "Kitabın 4 tərəfi var, amma uzun tərəfləri qısa tərəflərdən böyükdür — bu, düzbucaqlıdır.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-l1-t12", type: "multiple_choice", prompt: "Düzbucaqlının neçə tərəfi var?", options: ["4", "3", "5", "2"], correctIndex: 0, xp: 10, explanation: "Düzbucaqlının da 4 tərəfi var, sadəcə hamısı bərabər deyil.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-l1-t13", type: "numeric", prompt: "Kvadratın neçə tərəfi var? (rəqəmlə)", answer: 4, xp: 10, explanation: "Kvadratın tərəfləri: yuxarı, aşağı, sol, sağ — cəmi 4.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-l1-t14", type: "numeric", prompt: "Üçbucağın neçə küncü var? (rəqəmlə)", answer: 3, xp: 10, explanation: "Üçbucağın 3 tərəfi var, ona görə künclərinin sayı da 3-dür.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-l1-t15", type: "multiple_choice", prompt: "Hansı fiqurun bütün tərəfləri bərabərdir?", options: ["kvadrat", "düzbucaqlı", "dairə", "xətt"], correctIndex: 0, xp: 15, explanation: "Kvadratın dörd tərəfi də eyni uzunluqdadır. Düzbucaqlıda isə uzun və qısa tərəflər var.", skills: ["geom.shapes"] },
          ],
          bonusTasks: [
            { id: "ry1-fiqur-l1-b1", type: "numeric", prompt: "Bir üçbucaq və bir kvadratın tərəflərinin cəmi neçədir? (3 + 4)", answer: 7, xp: 15, explanation: "Üçbucaqda 3, kvadratda 4 tərəf var: 3 + 4 = 7.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-l1-b2", type: "multiple_choice", prompt: "Günəş hansı fiqura oxşayır?", options: ["dairə", "kvadrat", "üçbucaq", "düzbucaqlı"], correctIndex: 0, xp: 15, explanation: "Günəş yumru görünür, küncü yoxdur — dairəyə oxşayır.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-l1-b3", type: "numeric", prompt: "İki üçbucağın tərəflərinin cəmi neçədir? (3 + 3)", answer: 6, xp: 15, explanation: "Hər üçbucaqda 3 tərəf var, iki üçbucaqda: 3 + 3 = 6.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-l1-b4", type: "multiple_choice", prompt: "Dam (ev üstü) çox vaxt hansı fiqura oxşayır?", options: ["üçbucaq", "dairə", "kvadrat", "düzbucaqlı"], correctIndex: 0, xp: 15, explanation: "Damın iki maili tərəfi yuxarıda birləşir və üç tərəfli fiqur yaradır — üçbucaq.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-l1-b5", type: "numeric", prompt: "İki kvadratın tərəflərinin cəmi neçədir? (4 + 4)", answer: 8, xp: 15, explanation: "Hər kvadratda 4 tərəf var, iki kvadratda: 4 + 4 = 8.", skills: ["geom.shapes"] },
          ],
        },
        {
          id: "ry1-fiqur-l2",
          title: "Sadə mətn məsələləri",
          intro: "Kiçik məsələləri toplama və çıxma ilə həll edək.",
          sections: [
            { heading: "Məsələ", body: "Diqqətlə oxu, sonra topla və ya çıx. Məs.: 'Aylının 3 alması var, 2 də aldı. Neçə alması oldu?' → 3 + 2 = 5." },
          ],
          tasks: [
            { id: "ry1-fiqur-l2-t1", type: "numeric", prompt: "Aylının 3 alması var, 2 də aldı. Neçə alması oldu?", answer: 5, xp: 10, explanation: "«Də aldı» artım deməkdir, ona görə toplayırıq: 3 + 2 = 5.", skills: ["problem.one_step","arith.add.basic"] },
            { id: "ry1-fiqur-l2-t2", type: "numeric", prompt: "Budaqda 5 quş var idi, 2-si uçdu. Neçə quş qaldı?", answer: 3, xp: 10, explanation: "«Uçdu» azalma deməkdir, ona görə çıxırıq: 5 − 2 = 3.", skills: ["problem.one_step","arith.sub.basic"] },
            { id: "ry1-fiqur-l2-t3", type: "numeric", prompt: "Nərminin 4 şarı var, 1-i partladı. Neçə şar qaldı?", answer: 3, xp: 10, explanation: "«Partladı» azalma deməkdir: 4 − 1 = 3.", skills: ["problem.one_step","arith.sub.basic"] },
            { id: "ry1-fiqur-l2-t4", type: "numeric", prompt: "Səbətdə 2 armud var, 3 də əlavə etdik. Neçə armud oldu?", answer: 5, xp: 10, explanation: "«Əlavə etdik» artım deməkdir: 2 + 3 = 5.", skills: ["problem.one_step","arith.add.basic"] },
            { id: "ry1-fiqur-l2-t5", type: "numeric", prompt: "Elçinin 6 karandaşı var, 2-sini dostuna verdi. Neçə qaldı?", answer: 4, xp: 10, explanation: "«Verdi» azalma deməkdir: 6 − 2 = 4.", skills: ["problem.one_step","arith.sub.basic"] },
            { id: "ry1-fiqur-l2-t6", type: "numeric", prompt: "Bağçada 4 gül var idi, 4 də açdı. Neçə gül oldu?", answer: 8, xp: 10, explanation: "«Də açdı» yeni güllər deməkdir: 4 + 4 = 8.", skills: ["problem.one_step","arith.add.basic"] },
            { id: "ry1-fiqur-l2-t7", type: "numeric", prompt: "Rəfdə 7 kitab var idi, 3-nü götürdük. Neçə kitab qaldı?", answer: 4, xp: 10, explanation: "«Götürdük» azalma deməkdir: 7 − 3 = 4.", skills: ["problem.one_step","arith.sub.basic"] },
            { id: "ry1-fiqur-l2-t8", type: "numeric", prompt: "Leylanın 5 konfeti var, 3 də aldı. Neçə konfeti oldu?", answer: 8, xp: 10, explanation: "«Də aldı» artım deməkdir: 5 + 3 = 8.", skills: ["problem.one_step","arith.add.basic"] },
            { id: "ry1-fiqur-l2-t9", type: "numeric", prompt: "Hovuzda 6 balıq var idi, 2 də əlavə etdik. Neçə balıq oldu?", answer: 8, xp: 10, explanation: "«Əlavə etdik» artım deməkdir: 6 + 2 = 8.", skills: ["problem.one_step","arith.add.basic"] },
            { id: "ry1-fiqur-l2-t10", type: "numeric", prompt: "Sinifdə 10 uşaq var idi, 4-ü evə getdi. Neçə uşaq qaldı?", answer: 6, xp: 10, explanation: "«Evə getdi» azalma deməkdir: 10 − 4 = 6.", skills: ["problem.one_step","arith.sub.basic"] },
            { id: "ry1-fiqur-l2-t11", type: "numeric", prompt: "Anarın 2 maşını var, atası 2 də aldı. Neçə maşını oldu?", answer: 4, xp: 10, explanation: "«Də aldı» artım deməkdir: 2 + 2 = 4.", skills: ["problem.one_step","arith.add.basic"] },
            { id: "ry1-fiqur-l2-t12", type: "numeric", prompt: "Ağacda 8 alma var idi, 5-i düşdü. Neçə alma qaldı?", answer: 3, xp: 10, explanation: "«Düşdü» azalma deməkdir: 8 − 5 = 3.", skills: ["problem.one_step","arith.sub.basic"] },
            { id: "ry1-fiqur-l2-t13", type: "numeric", prompt: "Zərifənin 3 dəftəri var, 4 də aldı. Neçə dəftəri oldu?", answer: 7, xp: 10, explanation: "«Də aldı» artım deməkdir: 3 + 4 = 7.", skills: ["problem.one_step","arith.add.basic"] },
            { id: "ry1-fiqur-l2-t14", type: "numeric", prompt: "Qutuda 9 top var idi, 3-nü çıxartdıq. Neçə top qaldı?", answer: 6, xp: 10, explanation: "«Çıxartdıq» azalma deməkdir: 9 − 3 = 6.", skills: ["problem.one_step","arith.sub.basic"] },
            { id: "ry1-fiqur-l2-t15", type: "numeric", prompt: "Kaminin 5 balonu var, 5 də aldı. Neçə balonu oldu?", answer: 10, xp: 15, explanation: "«Də aldı» artım deməkdir: 5 + 5 = 10.", skills: ["problem.one_step","arith.add.basic"] },
          ],
          bonusTasks: [
            { id: "ry1-fiqur-l2-b1", type: "numeric", prompt: "Bağda 10 armud var idi, 6-sını yığdıq. Neçə armud qaldı?", answer: 4, xp: 15, explanation: "«Yığdıq» azalma deməkdir: 10 − 6 = 4.", skills: ["problem.one_step","arith.sub.basic"] },
            { id: "ry1-fiqur-l2-b2", type: "numeric", prompt: "Tünelin 7 daşı var, 3 də əlavə etdi, sonra 2-sini götürdü. Neçə daş qaldı?", answer: 8, xp: 15, explanation: "İki addım var: əvvəl 7 + 3 = 10, sonra 10 − 2 = 8.", skills: ["problem.multi_step","arith.add.basic"] },
            { id: "ry1-fiqur-l2-b3", type: "numeric", prompt: "İki dostun hərəsində 5 stiker var. Cəmi neçə stiker var?", answer: 10, xp: 15, explanation: "Hər dostda 5 stiker var, iki dostda: 5 + 5 = 10.", skills: ["problem.one_step"] },
            { id: "ry1-fiqur-l2-b4", type: "numeric", prompt: "Nənənin 12 yumurtası var idi, 2-si sındı. Neçə yumurta qaldı?", answer: 10, xp: 15, explanation: "«Sındı» azalma deməkdir: 12 − 2 = 10.", skills: ["problem.one_step","arith.sub.basic"] },
            { id: "ry1-fiqur-l2-b5", type: "numeric", prompt: "Meşədə 8 dovşan var idi, 4 də gəldi. Neçə dovşan oldu?", answer: 12, xp: 15, explanation: "«Də gəldi» artım deməkdir: 8 + 4 = 12.", skills: ["problem.one_step","arith.add.basic"] },
          ],
        },
        {
          id: "ry1-fiqur-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry1-fiqur-mesq",
          title: "Məşq",
          intro: "Fiqurları tanı və məsələləri həll et!",
          sections: [
            { heading: "Yadına salaq", body: "Kvadrat — 4 bərabər tərəf. Üçbucaq — 3 tərəf. Dairə — tərəfi yoxdur. Düzbucaqlı — 4 tərəf, qarşı tərəflər bərabər." },
          ],
          tasks: [
            { id: "ry1-fiqur-mesq-t1", type: "numeric", prompt: "Üçbucağın neçə tərəfi var?", answer: 3, xp: 10, explanation: "Üçbucağın adı «üç»dən gəlir: 3 tərəf.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-mesq-t2", type: "numeric", prompt: "Kvadratın neçə tərəfi var?", answer: 4, xp: 10, explanation: "Kvadratın 4 bərabər tərəfi var.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-mesq-t3", type: "multiple_choice", prompt: "Hansı fiqurun küncü yoxdur?", options: ["Dairə", "Kvadrat", "Üçbucaq", "Düzbucaqlı"], correctIndex: 0, xp: 10, explanation: "Dairə tam yumrudur, heç yerdə sınmır — ona görə küncü yoxdur.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-mesq-t4", type: "multiple_choice", prompt: "Top hansı fiqura oxşayır?", options: ["Dairə", "Kvadrat", "Üçbucaq", "Düzbucaqlı"], correctIndex: 0, xp: 10, explanation: "Top hər tərəfdən yumrudur — dairəyə oxşayır.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-mesq-t5", type: "numeric", prompt: "Leyla 5 kitab oxudu, Aysel 3 kitab. Cəmi neçə kitab oxudular?", answer: 8, xp: 10, explanation: "«Cəmi» toplama deməkdir: 5 + 3 = 8.", skills: ["problem.one_step","arith.add.basic"] },
            { id: "ry1-fiqur-mesq-t6", type: "numeric", prompt: "Ağacda 9 alma var idi, 4-ü düşdü. Neçə alma qaldı?", answer: 5, xp: 10, explanation: "«Düşdü» azalma deməkdir: 9 − 4 = 5.", skills: ["problem.one_step","arith.sub.basic"] },
            { id: "ry1-fiqur-mesq-t7", type: "numeric", prompt: "Kvadratın bir tərəfi 2 sm-dir. Bütün tərəflərin cəmi neçə sm-dir?", answer: 8, xp: 10, explanation: "Kvadratın 4 tərəfi var və hamısı bərabərdir: 2 + 2 + 2 + 2 = 8 sm.", skills: ["geom.shapes","measure.convert"] },
            { id: "ry1-fiqur-mesq-t8", type: "multiple_choice", prompt: "Pəncərə adətən hansı fiqura oxşayır?", options: ["Düzbucaqlı", "Dairə", "Üçbucaq", "Ulduz"], correctIndex: 0, xp: 10, explanation: "Pəncərənin 4 tərəfi var, uzun və qısa tərəfləri fərqlidir — düzbucaqlı.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-mesq-t9", type: "numeric", prompt: "Tuncay 7 şəkil çəkdi, 2-ni dostuna verdi. Neçə şəkli qaldı?", answer: 5, xp: 10, explanation: "«Verdi» azalma deməkdir: 7 − 2 = 5.", skills: ["problem.one_step","arith.sub.basic"] },
            { id: "ry1-fiqur-mesq-t10", type: "numeric", prompt: "İki üçbucağın cəmi neçə tərəfi var?", answer: 6, xp: 10, explanation: "Hər üçbucaqda 3 tərəf: 3 + 3 = 6.", skills: ["geom.shapes"] },
          ],
          bonusTasks: [
            { id: "ry1-fiqur-mesq-b1", type: "numeric", prompt: "Bir kvadrat və bir üçbucağın cəmi neçə tərəfi var?", answer: 7, xp: 15, explanation: "Kvadratda 4, üçbucaqda 3 tərəf var: 4 + 3 = 7.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-mesq-b2", type: "numeric", prompt: "Anarın 6 maşını var idi, 3 maşın da aldı, sonra 2-ni bağışladı. İndi neçə maşını var?", answer: 7, xp: 15, explanation: "İki addım: əvvəl 6 + 3 = 9, sonra 9 − 2 = 7.", skills: ["problem.multi_step","arith.add.basic"] },
            { id: "ry1-fiqur-mesq-b3", type: "multiple_choice", prompt: "Hansı fiqurun bütün tərəfləri bərabərdir?", options: ["Kvadrat", "Düzbucaqlı", "Dairə", "Heç biri"], correctIndex: 0, xp: 15, explanation: "Yalnız kvadratın dörd tərəfi də eyni uzunluqdadır.", skills: ["geom.shapes"] },
            { id: "ry1-fiqur-mesq-b4", type: "numeric", prompt: "Səbətdə 10 armud var idi. Səhər 3, axşam 2 armud yedik. Neçə armud qaldı?", answer: 5, xp: 15, explanation: "Səhər və axşam yeyilənləri toplayırıq: 3 + 2 = 5. Sonra 10 − 5 = 5 armud qalır.", skills: ["problem.multi_step","arith.add.basic"] },
            { id: "ry1-fiqur-mesq-b5", type: "numeric", prompt: "Üç dairənin cəmi neçə küncü var?", answer: 0, xp: 15, explanation: "Dairənin küncü yoxdur, yəni 0. Üç dairədə də: 0 + 0 + 0 = 0.", skills: ["geom.shapes"] },
          ],
        },
        {
          id: "ry1-fiqur-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    {
      id: "ry1-olcme",
      title: "Ölçmə və müqayisə",
      description: "Uzun-qısa, ağır-yüngül, çox-az — əşyaları müqayisə etmək.",
      lessons: [
        {
          id: "ry1-olcme-l1",
          title: "Uzun və qısa",
          intro: "Hansı uzundur, hansı qısa?",
          sections: [
            { heading: "Müqayisə", body: "İki əşyanı yan-yana qoyub baxırıq: qələm karandaşdan uzundur." },
            { heading: "Sözlər", body: "uzun — qısa, hündür — alçaq, geniş — dar." },
          ],
          tasks: [
            { id: "ry1-olcme-l1-t1", type: "multiple_choice", prompt: "Hansı adətən daha UZUNDUR?", options: ["Qatar", "Avtobus", "Velosiped", "Kitab"], correctIndex: 0, xp: 10, explanation: "Qatar bir neçə vaqondan ibarətdir, ona görə variantların ən uzunudur.", skills: ["measure.compare"] },
            { id: "ry1-olcme-l1-t2", type: "multiple_choice", prompt: "Hansı adətən daha QISADIR?", options: ["Karandaş", "Ağac", "Küçə", "Çay"], correctIndex: 0, xp: 10, explanation: "Karandaş ovcumuza sığır — çay, ağac və küçədən qat-qat qısadır.", skills: ["measure.compare"] },
            { id: "ry1-olcme-l1-t3", type: "multiple_choice", prompt: "'uzun' sözünün əksi hansıdır?", options: ["qısa", "hündür", "geniş", "böyük"], correctIndex: 0, xp: 10, explanation: "Uzun bir şey qısaldıqca «qısa» olur — bu iki söz bir-birinin əksidir.", skills: ["measure.compare"] },
            { id: "ry1-olcme-l1-t4", type: "multiple_choice", prompt: "Hansı daha HÜNDÜRDÜR?", options: ["Ağac", "Ot", "Gül", "Daş"], correctIndex: 0, xp: 10, explanation: "Ağac ot, daş və güldən yuxarı uzanır — ən hündürüdür.", skills: ["measure.compare"] },
            { id: "ry1-olcme-l1-t5", type: "multiple_choice", prompt: "'hündür' sözünün əksi hansıdır?", options: ["alçaq", "uzun", "geniş", "böyük"], correctIndex: 0, xp: 10, explanation: "Hündür yuxarı, alçaq aşağı deməkdir — bunlar bir-birinin əksidir.", skills: ["measure.compare"] },
            { id: "ry1-olcme-l1-t6", type: "numeric", prompt: "3 sm və 7 sm — hansı daha uzundur? (rəqəmi yaz)", answer: 7, xp: 10, explanation: "Hər ikisi santimetrlə ölçülüb, ona görə sadəcə ədədləri müqayisə edirik: 7 > 3.", skills: ["measure.compare"] },
            { id: "ry1-olcme-l1-t7", type: "multiple_choice", prompt: "Hansı daha GENİŞDİR?", options: ["Yol", "Cığır", "İp", "Tel"], correctIndex: 0, xp: 10, explanation: "Yol maşınların yan-yana keçməsi üçün açılır — tel, ip və cığırdan genişdir.", skills: ["measure.compare"] },
            { id: "ry1-olcme-l1-t8", type: "numeric", prompt: "5 sm və 2 sm — hansı daha qısadır? (rəqəmi yaz)", answer: 2, xp: 10, explanation: "Ədədləri müqayisə edirik: 2 < 5, ona görə 2 sm daha qısadır.", skills: ["measure.compare"] },
            { id: "ry1-olcme-l1-t9", type: "multiple_choice", prompt: "Uzunluğu nə ilə ölçürük?", options: ["Xətkeşlə", "Tərəzi ilə", "Saatla", "Stəkanla"], correctIndex: 0, xp: 10, explanation: "Xətkeşin üstündə santimetr bölgüləri var — uzunluq onunla ölçülür.", skills: ["measure.compare"] },
            { id: "ry1-olcme-l1-t10", type: "multiple_choice", prompt: "Hansı daha BÖYÜKDÜR?", options: ["Fil", "Pişik", "Siçan", "Qarışqa"], correctIndex: 0, xp: 10, explanation: "Fil siçan, pişik və qarışqadan qat-qat böyükdür.", skills: ["number.compare"] },
          ],
          bonusTasks: [
            { id: "ry1-olcme-l1-b1", type: "numeric", prompt: "4 sm, 9 sm, 6 sm — ən uzunu neçə sm-dir?", answer: 9, xp: 15, explanation: "Üç ədədi müqayisə edirik: 4 < 6 < 9. Ən uzunu 9 sm-dir.", skills: ["measure.convert","measure.compare"] },
            { id: "ry1-olcme-l1-b2", type: "multiple_choice", prompt: "Bir metr neçə santimetrdir?", options: ["100", "10", "50", "1000"], correctIndex: 0, xp: 15, explanation: "Metr santimetrdən böyük vahiddir: 1 m = 100 sm.", skills: ["measure.convert"] },
            { id: "ry1-olcme-l1-b3", type: "multiple_choice", prompt: "Hansı sıra kiçikdən böyüyə düzülüb?", options: ["qarışqa, pişik, fil", "fil, pişik, qarışqa", "pişik, qarışqa, fil", "fil, qarışqa, pişik"], correctIndex: 0, xp: 15, explanation: "Qarışqa ən kiçik, fil ən böyükdür; pişik ortadadır — qarışqa, pişik, fil.", skills: ["measure.compare"] },
            { id: "ry1-olcme-l1-b4", type: "numeric", prompt: "10 sm-dən 3 sm qısa neçə sm-dir?", answer: 7, xp: 15, explanation: "«3 sm qısa» çıxma deməkdir: 10 − 3 = 7 sm.", skills: ["measure.convert","measure.compare"] },
          ],
        },
        {
          id: "ry1-olcme-l2",
          title: "Ağır və yüngül",
          intro: "Hansı ağırdır?",
          sections: [
            { heading: "Çəki", body: "Ağır əşyanı qaldırmaq çətindir. Daş yüngül deyil, lələk yüngüldür." },
            { heading: "Ölçmək", body: "Çəkini TƏRƏZİ ilə ölçürük. Vahid — qram və kiloqram." },
          ],
          tasks: [
            { id: "ry1-olcme-l2-t1", type: "multiple_choice", prompt: "Hansı daha AĞIRDIR?", options: ["Daş", "Lələk", "Kağız", "Yarpaq"], correctIndex: 0, xp: 10, explanation: "Daş kağız, lələk və yarpaqdan sıxdır — əlimizdə daha ağır gəlir.", skills: ["measure.compare"] },
            { id: "ry1-olcme-l2-t2", type: "multiple_choice", prompt: "Hansı daha YÜNGÜLDÜR?", options: ["Lələk", "Kitab", "Kərpic", "Su qabı"], correctIndex: 0, xp: 10, explanation: "Lələk havada belə uçur — variantların ən yüngülüdür.", skills: ["measure.compare"] },
            { id: "ry1-olcme-l2-t3", type: "multiple_choice", prompt: "Çəkini nə ilə ölçürük?", options: ["Tərəzi ilə", "Xətkeşlə", "Saatla", "Termometrlə"], correctIndex: 0, xp: 10, explanation: "Tərəzi iki tərəfi tarazlayır və çəkini göstərir.", skills: ["measure.compare"] },
            { id: "ry1-olcme-l2-t4", type: "numeric", prompt: "1 kiloqram neçə qramdır?", answer: 1000, xp: 10, explanation: "Kiloqram qramdan böyük vahiddir: 1 kq = 1000 q.", skills: ["measure.convert"] },
            { id: "ry1-olcme-l2-t5", type: "multiple_choice", prompt: "'ağır' sözünün əksi hansıdır?", options: ["yüngül", "böyük", "uzun", "dolu"], correctIndex: 0, xp: 10, explanation: "Ağır çox çəkir, yüngül az — bunlar bir-birinin əksidir.", skills: ["measure.compare"] },
            { id: "ry1-olcme-l2-t6", type: "multiple_choice", prompt: "Hansı daha ağırdır: 1 kq pambıq, yoxsa 1 kq dəmir?", options: ["Bərabərdir", "Dəmir", "Pambıq", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "Hər ikisi 1 kiloqramdır, yəni çəkiləri eynidir. Pambıq sadəcə çox yer tutur, amma ağır demək deyil.", skills: ["measure.compare","problem.one_step"] },
            { id: "ry1-olcme-l2-t7", type: "multiple_choice", prompt: "Hansı ən ağırdır?", options: ["Avtomobil", "Velosiped", "Top", "Qələm"], correctIndex: 0, xp: 10, explanation: "Avtomobil metaldan qurulub və insanları daşıyır — top, qələm və velosipeddən ağırdır.", skills: ["measure.compare"] },
            { id: "ry1-olcme-l2-t8", type: "numeric", prompt: "2 kiloqram neçə qramdır?", answer: 2000, xp: 10, explanation: "1 kq = 1000 q, ona görə 2 kq = 2 × 1000 = 2000 q.", skills: ["measure.convert"] },
            { id: "ry1-olcme-l2-t9", type: "multiple_choice", prompt: "Çəki vahidi hansıdır?", options: ["Kiloqram", "Metr", "Saat", "Litr"], correctIndex: 0, xp: 10, explanation: "Litr mayeni, metr uzunluğu, saat vaxtı ölçür. Çəki vahidi kiloqramdır.", skills: ["measure.compare"] },
            { id: "ry1-olcme-l2-t10", type: "multiple_choice", prompt: "Boş çanta ilə dolu çanta — hansı ağırdır?", options: ["Dolu", "Boş", "Bərabər", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "Dolu çantada çantanın özü ilə birlikdə əşyalar da var, ona görə daha ağırdır.", skills: ["measure.compare"] },
          ],
          bonusTasks: [
            { id: "ry1-olcme-l2-b1", type: "numeric", prompt: "500 qram + 500 qram neçə kiloqramdır?", answer: 1, xp: 15, explanation: "500 + 500 = 1000 qram, 1000 qram isə 1 kiloqramdır.", skills: ["measure.convert"] },
            { id: "ry1-olcme-l2-b2", type: "multiple_choice", prompt: "Maye nə ilə ölçülür?", options: ["Litrlə", "Kiloqramla", "Metrlə", "Saatla"], correctIndex: 0, xp: 15, explanation: "Maye qabın formasını alır, ona görə tutumla — litrlə ölçülür.", skills: ["measure.units"] },
            { id: "ry1-olcme-l2-b3", type: "numeric", prompt: "3 kq − 1 kq = ? (kq ilə)", answer: 2, xp: 15, explanation: "Hər ikisi kiloqramdır, sadəcə çıxırıq: 3 − 1 = 2 kq.", skills: ["arith.sub.basic"] },
            { id: "ry1-olcme-l2-b4", type: "multiple_choice", prompt: "Hansı sıra yüngüldən ağıra düzülüb?", options: ["lələk, kitab, daş", "daş, kitab, lələk", "kitab, lələk, daş", "daş, lələk, kitab"], correctIndex: 0, xp: 15, explanation: "Lələk ən yüngül, daş ən ağırdır; kitab ortadadır — lələk, kitab, daş.", skills: ["measure.compare"] },
          ],
        },
        {
          id: "ry1-olcme-l3",
          title: "Çox və az",
          intro: "Hansı qrupda daha çox var?",
          sections: [
            { heading: "Saymaqla", body: "İki qrupu sayıb müqayisə edirik: 5 alma 3 armuddan çoxdur." },
            { heading: "İşarələr", body: "> böyükdür, < kiçikdir, = bərabərdir." },
          ],
          tasks: [
            { id: "ry1-olcme-l3-t1", type: "numeric", prompt: "5 alma və 3 armud — neçə alma çoxdur?", answer: 2, xp: 10, explanation: "«Neçə çoxdur» fərq deməkdir: 5 − 3 = 2 alma çoxdur.", skills: ["number.compare"] },
            { id: "ry1-olcme-l3-t2", type: "multiple_choice", prompt: "7 və 4 — hansı çoxdur?", options: ["7", "4", "Bərabərdir", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "Sayarkən 7 daha gec gəlir: 4 < 7. Çoxu 7-dir.", skills: ["number.compare"] },
            { id: "ry1-olcme-l3-t3", type: "multiple_choice", prompt: "2 və 9 — hansı azdır?", options: ["2", "9", "Bərabərdir", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "Sayarkən 2 daha tez gəlir: 2 < 9. Azı 2-dir.", skills: ["number.compare"] },
            { id: "ry1-olcme-l3-t4", type: "numeric", prompt: "6 və 6 — fərq neçədir?", answer: 0, xp: 10, explanation: "İki ədəd eynidir, aralarında heç bir fərq yoxdur: 6 − 6 = 0.", skills: ["number.compare"] },
            { id: "ry1-olcme-l3-t5", type: "multiple_choice", prompt: "8 ... 5 — hansı işarə düzgündür?", options: [">", "<", "=", "Heç biri"], correctIndex: 0, xp: 10, explanation: "8 böyükdür, ona görə > işarəsi qoyulur; açıq ağzı böyük ədədə baxır: 8 > 5.", skills: ["number.compare"] },
            { id: "ry1-olcme-l3-t6", type: "multiple_choice", prompt: "3 ... 3 — hansı işarə düzgündür?", options: ["=", ">", "<", "Heç biri"], correctIndex: 0, xp: 10, explanation: "Hər iki ədəd eynidir, ona görə bərabərlik işarəsi qoyulur: 3 = 3.", skills: ["number.compare"] },
            { id: "ry1-olcme-l3-t7", type: "numeric", prompt: "9 quşdan 4-ü uçdu. Neçə quş qaldı?", answer: 5, xp: 10, explanation: "«Uçdu» azalma deməkdir: 9 − 4 = 5.", skills: ["number.compare"] },
            { id: "ry1-olcme-l3-t8", type: "numeric", prompt: "4 və 7 — fərq neçədir?", answer: 3, xp: 10, explanation: "Fərq böyükdən kiçiyi çıxmaqla tapılır: 7 − 4 = 3.", skills: ["number.compare"] },
            { id: "ry1-olcme-l3-t9", type: "multiple_choice", prompt: "'çox' sözünün əksi hansıdır?", options: ["az", "böyük", "uzun", "ağır"], correctIndex: 0, xp: 10, explanation: "Çox böyük sayı, az kiçik sayı bildirir — bunlar bir-birinin əksidir.", skills: ["number.compare"] },
            { id: "ry1-olcme-l3-t10", type: "numeric", prompt: "10 və 3 — hansı böyükdür? (rəqəmi yaz)", answer: 10, xp: 10, explanation: "10 iki rəqəmlidir və 3-dən sonra gəlir: 3 < 10. Böyüyü 10-dur.", skills: ["number.compare"] },
          ],
          bonusTasks: [
            { id: "ry1-olcme-l3-b1", type: "numeric", prompt: "Səbətdə 8 alma var idi, 3-ü yeyildi, sonra 2 əlavə olundu. Neçə alma var?", answer: 7, xp: 15, explanation: "İki addım: əvvəl 8 − 3 = 5, sonra 5 + 2 = 7.", skills: ["problem.multi_step","arith.sub.basic"] },
            { id: "ry1-olcme-l3-b2", type: "multiple_choice", prompt: "1, 5, 3, 9 — ən böyüyü hansıdır?", options: ["9", "5", "3", "1"], correctIndex: 0, xp: 15, explanation: "Sıraya düzək: 1, 3, 5, 9. Ən sonda gələn 9 ən böyüyüdür.", skills: ["number.compare"] },
            { id: "ry1-olcme-l3-b3", type: "numeric", prompt: "7-dən neçə az 4-dür?", answer: 3, xp: 15, explanation: "«Neçə az» fərq deməkdir: 7 − 4 = 3.", skills: ["number.compare"] },
            { id: "ry1-olcme-l3-b4", type: "multiple_choice", prompt: "Hansı sıra böyükdən kiçiyə düzülüb?", options: ["9, 6, 3", "3, 6, 9", "6, 3, 9", "3, 9, 6"], correctIndex: 0, xp: 15, explanation: "Böyükdən kiçiyə düzülmüş sıra hər addımda azalmalıdır: 9 > 6 > 3. ✓", skills: ["number.compare"] },
          ],
        },
        {
          id: "ry1-olcme-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry1-olcme-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    {
      id: "ry1-zaman",
      title: "Zaman və pul",
      description: "Gün, həftə, saat və qəpik-manatı tanımaq.",
      lessons: [
        {
          id: "ry1-zaman-l1",
          title: "Gün və həftə",
          intro: "Səhər, günorta, axşam, gecə.",
          sections: [
            { heading: "Gün hissələri", body: "Səhər qalxırıq, günorta nahar edirik, axşam evə qayıdırıq, gecə yatırıq." },
            { heading: "Həftə", body: "Həftədə 7 gün var: bazar, bazar ertəsi, çərşənbə axşamı, çərşənbə, cümə axşamı, cümə, şənbə." },
          ],
          tasks: [
            { id: "ry1-zaman-l1-t1", type: "numeric", prompt: "Həftədə neçə gün var?", answer: 7, xp: 10, explanation: "Bazar ertəsindən bazara qədər sayırıq — həftədə 7 gün var.", skills: ["measure.time"] },
            { id: "ry1-zaman-l1-t2", type: "multiple_choice", prompt: "Nə vaxt yatırıq?", options: ["Gecə", "Səhər", "Günorta", "Həmişə"], correctIndex: 0, xp: 10, explanation: "Gecə hava qaralır və insanlar dincəlir — yuxu vaxtıdır.", skills: ["measure.time"] },
            { id: "ry1-zaman-l1-t3", type: "multiple_choice", prompt: "Nə vaxt məktəbə gedirik?", options: ["Səhər", "Gecə", "Gecə yarısı", "Heç vaxt"], correctIndex: 0, xp: 10, explanation: "Dərslər günün əvvəlində başlayır, ona görə məktəbə səhər gedirik.", skills: ["measure.time"] },
            { id: "ry1-zaman-l1-t4", type: "multiple_choice", prompt: "Bazar ertəsindən sonra hansı gün gəlir?", options: ["Çərşənbə axşamı", "Bazar", "Cümə", "Şənbə"], correctIndex: 0, xp: 10, explanation: "Həftə sırası: bazar ertəsi, çərşənbə axşamı, çərşənbə… Deməli sonra çərşənbə axşamı gəlir.", skills: ["measure.time"] },
            { id: "ry1-zaman-l1-t5", type: "numeric", prompt: "Bir ildə neçə ay var?", answer: 12, xp: 10, explanation: "Yanvardan dekabra qədər sayırıq — bir ildə 12 ay var.", skills: ["measure.time"] },
            { id: "ry1-zaman-l1-t6", type: "multiple_choice", prompt: "Günün ilk hissəsi hansıdır?", options: ["Səhər", "Axşam", "Gecə", "Günorta"], correctIndex: 0, xp: 10, explanation: "Gün səhərlə başlayır, sonra günorta, axşam və gecə gəlir.", skills: ["measure.time"] },
            { id: "ry1-zaman-l1-t7", type: "numeric", prompt: "İki həftədə neçə gün var?", answer: 14, xp: 10, explanation: "Bir həftədə 7 gün var, iki həftədə: 7 + 7 = 14 gün.", skills: ["measure.time"] },
            { id: "ry1-zaman-l1-t8", type: "multiple_choice", prompt: "Nahar nə vaxt edilir?", options: ["Günorta", "Gecə", "Səhər tezdən", "Gecə yarısı"], correctIndex: 0, xp: 10, explanation: "Nahar günün ortasında — günorta yeyilir.", skills: ["measure.time"] },
            { id: "ry1-zaman-l1-t9", type: "multiple_choice", prompt: "Fəsillər neçədir?", options: ["4", "2", "3", "12"], correctIndex: 0, xp: 10, explanation: "Qış, yaz, yay, payız — cəmi 4 fəsil var.", skills: ["measure.time"] },
            { id: "ry1-zaman-l1-t10", type: "numeric", prompt: "Bir gündə neçə saat var?", answer: 24, xp: 10, explanation: "Gündüz və gecə birlikdə 24 saat edir.", skills: ["measure.time"] },
          ],
          bonusTasks: [
            { id: "ry1-zaman-l1-b1", type: "numeric", prompt: "3 həftədə neçə gün var?", answer: 21, xp: 15, explanation: "Hər həftədə 7 gün var: 7 + 7 + 7 = 21 gün.", skills: ["measure.time"] },
            { id: "ry1-zaman-l1-b2", type: "multiple_choice", prompt: "Hansı fəsildə qar yağır?", options: ["Qış", "Yay", "Yaz", "Payız"], correctIndex: 0, xp: 15, explanation: "Qışda hava soyuyur və yağış qara çevrilir.", skills: ["measure.time","measure.compare"] },
            { id: "ry1-zaman-l1-b3", type: "numeric", prompt: "Həftənin 5 iş günü var. Neçə istirahət günü qalır?", answer: 2, xp: 15, explanation: "Həftədə 7 gün var, 5-i iş günüdür: 7 − 5 = 2 istirahət günü.", skills: ["measure.time"] },
            { id: "ry1-zaman-l1-b4", type: "multiple_choice", prompt: "Yaz fəslindən sonra hansı fəsil gəlir?", options: ["Yay", "Qış", "Payız", "Yaz"], correctIndex: 0, xp: 15, explanation: "Fəsillərin sırası: qış, yaz, yay, payız. Yazdan sonra yay gəlir.", skills: ["measure.time"] },
          ],
        },
        {
          id: "ry1-zaman-l2",
          title: "Saatı tanı",
          intro: "Qısa əqrəb saatı göstərir.",
          sections: [
            { heading: "Əqrəblər", body: "Saatda iki əqrəb var: QISA əqrəb saatı, UZUN əqrəb dəqiqəni göstərir." },
            { heading: "Tam saat", body: "Uzun əqrəb 12-nin üstündədirsə, saat tamdır: 3 tamam, 7 tamam." },
          ],
          tasks: [
            { id: "ry1-zaman-l2-t1", type: "multiple_choice", prompt: "Qısa əqrəb nəyi göstərir?", options: ["Saatı", "Dəqiqəni", "Saniyəni", "Günü"], correctIndex: 0, xp: 10, explanation: "Qısa əqrəb yavaş hərəkət edir və saatı göstərir.", skills: ["measure.time","measure.compare"] },
            { id: "ry1-zaman-l2-t2", type: "multiple_choice", prompt: "Uzun əqrəb nəyi göstərir?", options: ["Dəqiqəni", "Saatı", "Günü", "Ayı"], correctIndex: 0, xp: 10, explanation: "Uzun əqrəb sürətli hərəkət edir və dəqiqələri göstərir.", skills: ["measure.time","measure.compare"] },
            { id: "ry1-zaman-l2-t3", type: "numeric", prompt: "Saat 3-dür. 2 saatdan sonra saat neçə olacaq?", answer: 5, xp: 10, explanation: "Saatın üstünə vaxt əlavə edirik: 3 + 2 = 5.", skills: ["measure.time","problem.one_step","arith.add.basic"] },
            { id: "ry1-zaman-l2-t4", type: "numeric", prompt: "Saat 8-dir. 1 saat əvvəl saat neçə idi?", answer: 7, xp: 10, explanation: "«Əvvəl» geri getmək deməkdir: 8 − 1 = 7.", skills: ["measure.time","problem.one_step","arith.sub.basic"] },
            { id: "ry1-zaman-l2-t5", type: "numeric", prompt: "Bir saatda neçə dəqiqə var?", answer: 60, xp: 10, explanation: "Saat 60 dəqiqəyə bölünür.", skills: ["measure.time"] },
            { id: "ry1-zaman-l2-t6", type: "multiple_choice", prompt: "Uzun əqrəb 12-nin üstündədirsə saat necədir?", options: ["Tamdır", "Yarımdır", "Rübdür", "Bilinmir"], correctIndex: 0, xp: 10, explanation: "Uzun əqrəb 12-də olanda dəqiqə 0-dır, yəni saat tam olur.", skills: ["measure.time","measure.compare"] },
            { id: "ry1-zaman-l2-t7", type: "numeric", prompt: "Saat 10-dur. 3 saatdan sonra saat neçə olacaq?", answer: 13, xp: 10, explanation: "Saatın üstünə əlavə edirik: 10 + 3 = 13 (yəni günorta 1-dir).", skills: ["measure.time","problem.one_step","arith.add.no_carry"] },
            { id: "ry1-zaman-l2-t8", type: "numeric", prompt: "Saat 6-dır. 2 saat əvvəl saat neçə idi?", answer: 4, xp: 10, explanation: "«Əvvəl» geri getmək deməkdir: 6 − 2 = 4.", skills: ["measure.time","problem.one_step","arith.sub.basic"] },
            { id: "ry1-zaman-l2-t9", type: "multiple_choice", prompt: "Saatda neçə əqrəb var (əsas)?", options: ["2", "1", "3", "4"], correctIndex: 0, xp: 10, explanation: "Saatda əsas iki əqrəb var: qısa (saat) və uzun (dəqiqə).", skills: ["measure.time"] },
            { id: "ry1-zaman-l2-t10", type: "numeric", prompt: "Yarım saat neçə dəqiqədir?", answer: 30, xp: 10, explanation: "Bir saat 60 dəqiqədir, yarısı isə: 60 : 2 = 30 dəqiqə.", skills: ["measure.time"] },
          ],
          bonusTasks: [
            { id: "ry1-zaman-l2-b1", type: "numeric", prompt: "Dərs saat 9-da başladı, 1 saat çəkdi. Saat neçədə bitdi?", answer: 10, xp: 15, explanation: "Başlama vaxtına müddəti əlavə edirik: 9 + 1 = 10.", skills: ["measure.time","problem.one_step","arith.add.basic"] },
            { id: "ry1-zaman-l2-b2", type: "numeric", prompt: "Səhər 7-dən axşam 7-yə qədər neçə saat keçir?", answer: 12, xp: 15, explanation: "7-dən 12-yə 5 saat, 12-dən 7-yə daha 7 saat: 5 + 7 = 12 saat.", skills: ["measure.time","problem.one_step","arith.add.basic"] },
            { id: "ry1-zaman-l2-b3", type: "multiple_choice", prompt: "Gecə yarısı saat neçədir?", options: ["12", "6", "3", "9"], correctIndex: 0, xp: 15, explanation: "Gecə yarısı gün dəyişir və saat 12-ni göstərir.", skills: ["measure.time"] },
            { id: "ry1-zaman-l2-b4", type: "numeric", prompt: "2 saat neçə dəqiqədir?", answer: 120, xp: 15, explanation: "Bir saat 60 dəqiqədir: 60 + 60 = 120 dəqiqə.", skills: ["measure.time"] },
          ],
        },
        {
          id: "ry1-zaman-l3",
          title: "Pulu tanı",
          intro: "Qəpik və manat.",
          sections: [
            { heading: "Pulumuz", body: "Azərbaycanın pulu MANATDIR. Bir manatda 100 qəpik var." },
            { heading: "Alış-veriş", body: "Alanda pul veririk, artıq qalarsa qalıq alırıq." },
          ],
          tasks: [
            { id: "ry1-zaman-l3-t1", type: "numeric", prompt: "1 manat neçə qəpikdir?", answer: 100, xp: 10, explanation: "Manat qəpiklərə bölünür: 1 manat = 100 qəpik.", skills: ["measure.money"] },
            { id: "ry1-zaman-l3-t2", type: "multiple_choice", prompt: "Azərbaycanın pulu necə adlanır?", options: ["Manat", "Dollar", "Avro", "Rubl"], correctIndex: 0, xp: 10, explanation: "Azərbaycanın milli pul vahidi manatdır.", skills: ["measure.money"] },
            { id: "ry1-zaman-l3-t3", type: "numeric", prompt: "50 qəpik + 50 qəpik neçə manatdır?", answer: 1, xp: 10, explanation: "50 + 50 = 100 qəpik, 100 qəpik isə 1 manatdır.", skills: ["measure.money"] },
            { id: "ry1-zaman-l3-t4", type: "numeric", prompt: "2 manat neçə qəpikdir?", answer: 200, xp: 10, explanation: "1 manat 100 qəpikdir: 2 × 100 = 200 qəpik.", skills: ["measure.money"] },
            { id: "ry1-zaman-l3-t5", type: "numeric", prompt: "Çörək 1 manatdır. 2 manat verdin, neçə manat qalıq?", answer: 1, xp: 10, explanation: "Verdiyimizdən qiyməti çıxırıq: 2 − 1 = 1 manat qalıq.", skills: ["measure.money","problem.one_step","arith.sub.basic"] },
            { id: "ry1-zaman-l3-t6", type: "numeric", prompt: "20 qəpik + 30 qəpik neçə qəpikdir?", answer: 50, xp: 10, explanation: "Hər ikisi qəpikdir, ona görə sadəcə toplayırıq: 20 + 30 = 50 qəpik.", skills: ["measure.money"] },
            { id: "ry1-zaman-l3-t7", type: "multiple_choice", prompt: "Hansı daha çoxdur: 1 manat, yoxsa 50 qəpik?", options: ["1 manat", "50 qəpik", "Bərabərdir", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "1 manat 100 qəpikdir, 100 isə 50-dən çoxdur.", skills: ["measure.money","problem.one_step"] },
            { id: "ry1-zaman-l3-t8", type: "numeric", prompt: "3 manat + 2 manat = ? (manat)", answer: 5, xp: 10, explanation: "Hər ikisi manatdır, ona görə toplayırıq: 3 + 2 = 5 manat.", skills: ["measure.money"] },
            { id: "ry1-zaman-l3-t9", type: "multiple_choice", prompt: "Pul nə üçün lazımdır?", options: ["Lazım olanı almaq üçün", "Oynamaq üçün", "Rəsm çəkmək üçün", "Heç nə üçün"], correctIndex: 0, xp: 10, explanation: "Pul mübadilə vasitəsidir — onunla lazım olan şeyləri alırıq.", skills: ["measure.money"] },
            { id: "ry1-zaman-l3-t10", type: "numeric", prompt: "5 manatdan 2 manat xərclədin. Neçə manat qaldı?", answer: 3, xp: 10, explanation: "Xərclənən pulu çıxırıq: 5 − 2 = 3 manat qaldı.", skills: ["measure.money","problem.one_step","arith.sub.basic"] },
          ],
          bonusTasks: [
            { id: "ry1-zaman-l3-b1", type: "numeric", prompt: "10 qəpiklik 10 ədəd sikkə neçə manat edir?", answer: 1, xp: 15, explanation: "Hər sikkə 10 qəpikdir: 10 × 10 = 100 qəpik, yəni 1 manat.", skills: ["measure.money","problem.one_step","arith.mul.multi_digit"] },
            { id: "ry1-zaman-l3-b2", type: "numeric", prompt: "Şirniyyat 80 qəpikdir. 1 manat verdin, neçə qəpik qalıq?", answer: 20, xp: 15, explanation: "1 manat = 100 qəpik. Qalıq: 100 − 80 = 20 qəpik.", skills: ["measure.money","problem.one_step","arith.sub.borrow"] },
            { id: "ry1-zaman-l3-b3", type: "numeric", prompt: "2 manat 50 qəpik neçə qəpikdir?", answer: 250, xp: 15, explanation: "2 manat = 200 qəpik, üstünə 50 qəpik: 200 + 50 = 250 qəpik.", skills: ["measure.money"] },
            { id: "ry1-zaman-l3-b4", type: "multiple_choice", prompt: "Pulu haradan qazanırıq?", options: ["İşləməklə", "Oyundan", "Yuxudan", "Heç yerdən"], correctIndex: 0, xp: 15, explanation: "Pul görülən işin qarşılığında verilir — insanlar onu işləməklə qazanır.", skills: ["measure.money"] },
          ],
        },
        {
          id: "ry1-zaman-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry1-zaman-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
  ],
};
