// Riyaziyyat — 4-cü sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Böyük ədədlər  2) Çoxrəqəmli vurma  3) Çoxrəqəmli bölmə
// 4) Kəsrlər  5) Onluq kəsrlər və ölçmə  6) Sahə, əməllər sırası və məsələlər.
// 4-cü sinif üçün (rəqəm cavablar). id prefiksi ry4-*.

import type { Subject } from "../types";

export const math4: Subject = {
  slug: "riyaziyyat-4",
  name: "Riyaziyyat",
  grade: 4,
  icon: "R",
  color: "sky",
  units: [
    // ═══════════════ 1. Böyük ədədlər ═══════════════
    {
      id: "ry4-boyuk",
      title: "Böyük ədədlər",
      description: "Minlik, on minlik və milyona qədər ədədləri oxumaq, yazmaq, müqayisə etmək.",
      lessons: [
        {
          id: "ry4-boyuk-l1",
          title: "Minliklər və böyük ədədlər",
          intro: "Dördrəqəmli və daha böyük ədədlər.",
          sections: [
            { heading: "Mərtəbələr", body: "Böyük ədədlər minlik, yüzlük, onluq, təklikdən ibarətdir. 3456 = 3 minlik + 4 yüzlük + 5 onluq + 6 təklik." },
            { heading: "Böyük ədədlər", body: "1000 — min, 10 000 — on min, 100 000 — yüz min, 1 000 000 — milyon." },
          ],
          tasks: [
            { id: "ry4-boyuk-l1-t1", type: "numeric", prompt: "3456 ədədində neçə minlik var?", answer: 3, xp: 10, explanation: "3456 = 3000 + 400 + 50 + 6. Minliklərin sayı 3-dir." },
            { id: "ry4-boyuk-l1-t2", type: "numeric", prompt: "3456 ədədində neçə yüzlük var?", answer: 4, xp: 10, explanation: "3456 = 3000 + 400 + 50 + 6. Yüzlüklərin sayı 34-dir." },
            { id: "ry4-boyuk-l1-t3", type: "numeric", prompt: "2 minlik + 3 yüzlük + 0 onluq + 5 təklik = ?", answer: 2305, xp: 10, explanation: "Hər mərtəbəni ayrıca yazıb toplayırıq: 2000 + 300 + 0 + 5 = 2305." },
            { id: "ry4-boyuk-l1-t4", type: "numeric", prompt: "5 minlik = ?", answer: 5000, xp: 10, explanation: "1 minlik 1000-dir, ona görə 5 minlik = 5 × 1000 = 5000." },
            { id: "ry4-boyuk-l1-t5", type: "numeric", prompt: "'on min' rəqəmlə necə yazılır?", answer: 10000, xp: 10, explanation: "«On min» 10 dənə minlik deməkdir: 10 × 1000 = 10 000." },
            { id: "ry4-boyuk-l1-t6", type: "numeric", prompt: "'yüz min' rəqəmlə necə yazılır?", answer: 100000, xp: 10, explanation: "«Yüz min» 100 dənə minlik deməkdir: 100 × 1000 = 100 000." },
            { id: "ry4-boyuk-l1-t7", type: "numeric", prompt: "'bir milyon' rəqəmlə necə yazılır?", answer: 1000000, xp: 10, explanation: "«Bir milyon» 1000 dənə minlik deməkdir: 1000 × 1000 = 1 000 000." },
            { id: "ry4-boyuk-l1-t8", type: "numeric", prompt: "9999-dan sonra hansı ədəd gəlir?", answer: 10000, xp: 10, explanation: "«Sonra gələn» 1 çox deməkdir: 9999 + 1 = 10000." },
            { id: "ry4-boyuk-l1-t9", type: "multiple_choice", prompt: "3456 və 3465 ədədlərindən böyüyü hansıdır?", options: ["3465", "3456", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "Onluqlara baxırıq: 346 onluq 345 onluqdan çoxdur, deməli 3465 böyükdür." },
            { id: "ry4-boyuk-l1-t10", type: "multiple_choice", prompt: "12000 və 9999 ədədlərindən böyüyü hansıdır?", options: ["12000", "9999", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "Onluqlara baxırıq: 1200 onluq 999 onluqdan çoxdur, deməli 12000 böyükdür." },
            { id: "ry4-boyuk-l1-t11", type: "numeric", prompt: "'iki min beş yüz' rəqəmlə necə yazılır?", answer: 2500, xp: 10, explanation: "«İki min» 2000, «beş yüz» 500 deməkdir: 2000 + 500 = 2500." },
            { id: "ry4-boyuk-l1-t12", type: "numeric", prompt: "1 milyon neçə mindir?", answer: 1000, xp: 10, explanation: "1 milyon = 1 000 000, 1 min isə 1000-dir: 1 000 000 : 1000 = 1000 min." },
            { id: "ry4-boyuk-l1-t13", type: "numeric", prompt: "7000-dən əvvəl gələn ədəd hansıdır?", answer: 6999, xp: 10, explanation: "«Əvvəl gələn» 1 az deməkdir: 7000 − 1 = 6999." },
            { id: "ry4-boyuk-l1-t14", type: "numeric", prompt: "4 minlik + 0 yüzlük + 0 onluq + 0 təklik = ?", answer: 4000, xp: 10, explanation: "Yalnız minliklər var, qalan mərtəbələr sıfırdır: 4 × 1000 = 4000." },
            { id: "ry4-boyuk-l1-t15", type: "numeric", prompt: "'altı min üç yüz' rəqəmlə necə yazılır?", answer: 6300, xp: 15, explanation: "«Altı min» 6000, «üç yüz» 300 deməkdir: 6000 + 300 = 6300." },
          ],
          bonusTasks: [
            { id: "ry4-boyuk-l1-b1", type: "numeric", prompt: "1 on minlik neçə təklikdir?", answer: 10000, xp: 15, explanation: "1 on minlik 10 minlik deməkdir: 10 × 1000 = 10 000 təklik." },
            { id: "ry4-boyuk-l1-b2", type: "numeric", prompt: "'səksən beş min' rəqəmlə necə yazılır?", answer: 85000, xp: 15, explanation: "«Səksən beş min» 85 dənə minlik deməkdir: 85 × 1000 = 85 000." },
            { id: "ry4-boyuk-l1-b3", type: "multiple_choice", prompt: "45678, 45876, 45687 — ən böyüyü hansıdır?", options: ["45876", "45687", "45678", "heç biri"], correctIndex: 0, xp: 15, explanation: "İlk üç rəqəm eynidir (456). Dördüncü rəqəmə baxırıq: 7, 8, 6. Ən böyüyü 8-dir, deməli 45876." },
            { id: "ry4-boyuk-l1-b4", type: "numeric", prompt: "999 999-dan sonra hansı ədəd gəlir?", answer: 1000000, xp: 15, explanation: "«Sonra gələn» 1 çox deməkdir: 999 999 + 1 = 1 000 000." },
            { id: "ry4-boyuk-l1-b5", type: "numeric", prompt: "3 minlik + 3 təklik = ?", answer: 3003, xp: 15, explanation: "Yüzlük və onluq yoxdur, ona görə onların yerinə sıfır yazılır: 3000 + 3 = 3003." },
          ],
        },
        {
          id: "ry4-boyuk-l2",
          title: "Yuvarlaqlaşdırma",
          intro: "Böyük ədədləri təxmini demək.",
          sections: [
            { heading: "Qayda", body: "Onluğa yuvarlaqlaşdırarkən sonuncu rəqəmə bax: 5 və ya böyükdürsə yuxarı, kiçikdirsə aşağı. 47 → 50, 43 → 40." },
            { heading: "Nə üçün?", body: "Təxmini hesab sürətli qərar verməyə kömək edir: 198 + 302 ≈ 200 + 300 = 500." },
          ],
          tasks: [
            { id: "ry4-boyuk-l2-t1", type: "numeric", prompt: "47 ədədini onluğa yuvarlaqlaşdır.", answer: 50, xp: 10, explanation: "Onluğa yuvarlaqlaşdırarkən ondan sonrakı rəqəmə baxırıq: 7. 5-dən kiçik deyil, ona görə yuxarı qalxırıq: 47 → 50." },
            { id: "ry4-boyuk-l2-t2", type: "numeric", prompt: "43 ədədini onluğa yuvarlaqlaşdır.", answer: 40, xp: 10, explanation: "Onluğa yuvarlaqlaşdırarkən ondan sonrakı rəqəmə baxırıq: 3. 5-dən kiçikdir, ona görə aşağı qalırıq: 43 → 40." },
            { id: "ry4-boyuk-l2-t3", type: "numeric", prompt: "356 ədədini yüzlüyə yuvarlaqlaşdır.", answer: 400, xp: 10, explanation: "Yüzlüyə yuvarlaqlaşdırarkən ondan sonrakı rəqəmə baxırıq: 5. 5-dən kiçik deyil, ona görə yuxarı qalxırıq: 356 → 400." },
            { id: "ry4-boyuk-l2-t4", type: "numeric", prompt: "1240 ədədini yüzlüyə yuvarlaqlaşdır.", answer: 1200, xp: 10, explanation: "Yüzlüyə yuvarlaqlaşdırarkən ondan sonrakı rəqəmə baxırıq: 4. 5-dən kiçikdir, ona görə aşağı qalırıq: 1240 → 1200." },
            { id: "ry4-boyuk-l2-t5", type: "numeric", prompt: "85 ədədini onluğa yuvarlaqlaşdır.", answer: 90, xp: 10, explanation: "Onluğa yuvarlaqlaşdırarkən ondan sonrakı rəqəmə baxırıq: 5. 5-dən kiçik deyil, ona görə yuxarı qalxırıq: 85 → 90." },
            { id: "ry4-boyuk-l2-t6", type: "numeric", prompt: "2500 ədədini minliyə yuvarlaqlaşdır.", answer: 3000, xp: 10, explanation: "Minliyə yuvarlaqlaşdırarkən ondan sonrakı rəqəmə baxırıq: 5. 5-dən kiçik deyil, ona görə yuxarı qalxırıq: 2500 → 3000." },
            { id: "ry4-boyuk-l2-t7", type: "multiple_choice", prompt: "Yuvarlaqlaşdırarkən hansı rəqəmə baxırıq?", options: ["Sonrakı mərtəbənin rəqəminə", "Birinci rəqəmə", "Bütün rəqəmlərə", "Heç birinə"], correctIndex: 0, xp: 10, explanation: "Yuvarlaqlaşdırdığımız mərtəbədən dərhal sonrakı rəqəm həll edir: 5-dən kiçikdirsə aşağı, deyilsə yuxarı." },
            { id: "ry4-boyuk-l2-t8", type: "numeric", prompt: "198 + 302 ifadəsinin təxmini nəticəsi nədir? (yüzlüklə)", answer: 500, xp: 10, explanation: "Hər iki ədədi yüzlüyə yuvarlaqlaşdırırıq: 198 → 200, 302 → 300. Təxmini nəticə: 200 + 300 = 500." },
            { id: "ry4-boyuk-l2-t9", type: "numeric", prompt: "7842 ədədini minliyə yuvarlaqlaşdır.", answer: 8000, xp: 10, explanation: "Minliyə yuvarlaqlaşdırarkən ondan sonrakı rəqəmə baxırıq: 8. 5-dən kiçik deyil, ona görə yuxarı qalxırıq: 7842 → 8000." },
            { id: "ry4-boyuk-l2-t10", type: "numeric", prompt: "64 ədədini onluğa yuvarlaqlaşdır.", answer: 60, xp: 10, explanation: "Onluğa yuvarlaqlaşdırarkən ondan sonrakı rəqəmə baxırıq: 4. 5-dən kiçikdir, ona görə aşağı qalırıq: 64 → 60." },
          ],
          bonusTasks: [
            { id: "ry4-boyuk-l2-b1", type: "numeric", prompt: "4 999 ədədini minliyə yuvarlaqlaşdır.", answer: 5000, xp: 15, explanation: "Minliyə yuvarlaqlaşdırarkən ondan sonrakı rəqəmə baxırıq: 9. 5-dən kiçik deyil, ona görə yuxarı qalxırıq: 4999 → 5000." },
            { id: "ry4-boyuk-l2-b2", type: "numeric", prompt: "12 345 ədədini yüzlüyə yuvarlaqlaşdır.", answer: 12300, xp: 15, explanation: "Yüzlüyə yuvarlaqlaşdırarkən ondan sonrakı rəqəmə baxırıq: 4. 5-dən kiçikdir, ona görə aşağı qalırıq: 12345 → 12300." },
            { id: "ry4-boyuk-l2-b3", type: "multiple_choice", prompt: "Niyə yuvarlaqlaşdırma faydalıdır?", options: ["Tez təxmini hesab üçün", "Cavabı dəqiqləşdirmək üçün", "Yazını uzatmaq üçün", "Faydası yoxdur"], correctIndex: 0, xp: 15, explanation: "Yuvarlaqlaşdırılmış ədədlərlə hesab dəftərsiz, ağızdan aparıla bilir — cavabın təxminən nə qədər olacağını dərhal görürük." },
            { id: "ry4-boyuk-l2-b4", type: "numeric", prompt: "999 ədədini yüzlüyə yuvarlaqlaşdır.", answer: 1000, xp: 15, explanation: "Yüzlüyə yuvarlaqlaşdırarkən ondan sonrakı rəqəmə baxırıq: 9. 5-dən kiçik deyil, ona görə yuxarı qalxırıq: 999 → 1000." },
          ],
        },
        {
          id: "ry4-boyuk-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry4-boyuk-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 2. Çoxrəqəmli vurma ═══════════════
    {
      id: "ry4-vurma",
      title: "Çoxrəqəmli vurma",
      description: "İkirəqəmli ədədləri birrəqəmli və ikirəqəmli ədədlərə vurmaq.",
      lessons: [
        {
          id: "ry4-vurma-l1",
          title: "Vurma",
          intro: "Böyük ədədləri vururuq.",
          sections: [
            { heading: "Vurma", body: "23 × 3 = 69. 10 × 10 = 100. 12 × 12 = 144. Mərtəbələri ayrı-ayrı vurub toplayırıq." },
          ],
          tasks: [
            { id: "ry4-vurma-l1-t1", type: "numeric", prompt: "12 × 3 = ?", answer: 36, xp: 10, explanation: "12 ədədini mərtəbələrə ayırırıq: 10 + 2. Hər hissəni vururuq: 10 × 3 = 30, 2 × 3 = 6. Cəmi: 30 + 6 = 36." },
            { id: "ry4-vurma-l1-t2", type: "numeric", prompt: "23 × 3 = ?", answer: 69, xp: 10, explanation: "23 ədədini mərtəbələrə ayırırıq: 20 + 3. Hər hissəni vururuq: 20 × 3 = 60, 3 × 3 = 9. Cəmi: 60 + 9 = 69." },
            { id: "ry4-vurma-l1-t3", type: "numeric", prompt: "14 × 2 = ?", answer: 28, xp: 10, explanation: "14 ədədini mərtəbələrə ayırırıq: 10 + 4. Hər hissəni vururuq: 10 × 2 = 20, 4 × 2 = 8. Cəmi: 20 + 8 = 28." },
            { id: "ry4-vurma-l1-t4", type: "numeric", prompt: "25 × 4 = ?", answer: 100, xp: 10, explanation: "25 ədədini mərtəbələrə ayırırıq: 20 + 5. Hər hissəni vururuq: 20 × 4 = 80, 5 × 4 = 20. Cəmi: 80 + 20 = 100." },
            { id: "ry4-vurma-l1-t5", type: "numeric", prompt: "10 × 10 = ?", answer: 100, xp: 10, explanation: "10 × 10 = 100." },
            { id: "ry4-vurma-l1-t6", type: "numeric", prompt: "20 × 5 = ?", answer: 100, xp: 10, explanation: "20 × 5 — 20-ni 5 dəfə toplamaq deməkdir: 20 + 20 + 20 + 20 + 20 = 100." },
            { id: "ry4-vurma-l1-t7", type: "numeric", prompt: "11 × 11 = ?", answer: 121, xp: 10, explanation: "11 vuruğunu mərtəbələrə ayırırıq: 10 + 1. 11 × 10 = 110, 11 × 1 = 11. Cəmi: 110 + 11 = 121." },
            { id: "ry4-vurma-l1-t8", type: "numeric", prompt: "12 × 12 = ?", answer: 144, xp: 10, explanation: "12 vuruğunu mərtəbələrə ayırırıq: 10 + 2. 12 × 10 = 120, 12 × 2 = 24. Cəmi: 120 + 24 = 144." },
            { id: "ry4-vurma-l1-t9", type: "numeric", prompt: "30 × 3 = ?", answer: 90, xp: 10, explanation: "30 × 3 — 30-u 3 dəfə toplamaq deməkdir: 30 + 30 + 30 = 90." },
            { id: "ry4-vurma-l1-t10", type: "numeric", prompt: "15 × 4 = ?", answer: 60, xp: 10, explanation: "15 ədədini mərtəbələrə ayırırıq: 10 + 5. Hər hissəni vururuq: 10 × 4 = 40, 5 × 4 = 20. Cəmi: 40 + 20 = 60." },
            { id: "ry4-vurma-l1-t11", type: "numeric", prompt: "100 × 5 = ?", answer: 500, xp: 10, explanation: "100 × 5 — 100-ü 5 dəfə toplamaq deməkdir: 100 + 100 + 100 + 100 + 100 = 500." },
            { id: "ry4-vurma-l1-t12", type: "numeric", prompt: "21 × 4 = ?", answer: 84, xp: 10, explanation: "21 ədədini mərtəbələrə ayırırıq: 20 + 1. Hər hissəni vururuq: 20 × 4 = 80, 1 × 4 = 4. Cəmi: 80 + 4 = 84." },
            { id: "ry4-vurma-l1-t13", type: "numeric", prompt: "13 × 5 = ?", answer: 65, xp: 10, explanation: "13 ədədini mərtəbələrə ayırırıq: 10 + 3. Hər hissəni vururuq: 10 × 5 = 50, 3 × 5 = 15. Cəmi: 50 + 15 = 65." },
            { id: "ry4-vurma-l1-t14", type: "numeric", prompt: "40 × 6 = ?", answer: 240, xp: 10, explanation: "40 × 6 = 240." },
            { id: "ry4-vurma-l1-t15", type: "numeric", prompt: "24 × 3 = ?", answer: 72, xp: 15, explanation: "24 ədədini mərtəbələrə ayırırıq: 20 + 4. Hər hissəni vururuq: 20 × 3 = 60, 4 × 3 = 12. Cəmi: 60 + 12 = 72." },
          ],
          bonusTasks: [
            { id: "ry4-vurma-l1-b1", type: "numeric", prompt: "123 × 2 = ?", answer: 246, xp: 15, explanation: "123 ədədini mərtəbələrə ayırırıq: 100 + 20 + 3. Hər hissəni vururuq: 100 × 2 = 200, 20 × 2 = 40, 3 × 2 = 6. Cəmi: 200 + 40 + 6 = 246." },
            { id: "ry4-vurma-l1-b2", type: "numeric", prompt: "15 × 12 = ?", answer: 180, xp: 15, explanation: "12 vuruğunu mərtəbələrə ayırırıq: 10 + 2. 15 × 10 = 150, 15 × 2 = 30. Cəmi: 150 + 30 = 180." },
            { id: "ry4-vurma-l1-b3", type: "numeric", prompt: "25 × 8 = ?", answer: 200, xp: 15, explanation: "25 ədədini mərtəbələrə ayırırıq: 20 + 5. Hər hissəni vururuq: 20 × 8 = 160, 5 × 8 = 40. Cəmi: 160 + 40 = 200." },
            { id: "ry4-vurma-l1-b4", type: "numeric", prompt: "100 × 100 = ?", answer: 10000, xp: 15, explanation: "100 × 100 = 10000." },
            { id: "ry4-vurma-l1-b5", type: "numeric", prompt: "32 × 3 = ?", answer: 96, xp: 15, explanation: "32 ədədini mərtəbələrə ayırırıq: 30 + 2. Hər hissəni vururuq: 30 × 3 = 90, 2 × 3 = 6. Cəmi: 90 + 6 = 96." },
          ],
        },
        {
          id: "ry4-vurma-l2",
          title: "İkirəqəmliyə vurma",
          intro: "Sütun üsulu ilə iki mərtəbəli vurma.",
          sections: [
            { heading: "Addımlar", body: "23 × 14: əvvəl 23 × 4 = 92, sonra 23 × 10 = 230. Cəm: 92 + 230 = 322." },
            { heading: "Yoxlama", body: "Nəticəni təxmin et: 23 ≈ 20, 14 ≈ 10 → təxmini 200. Cavab 322 — məntiqlidir." },
          ],
          tasks: [
            { id: "ry4-vurma-l2-t1", type: "numeric", prompt: "23 × 14 = ?", answer: 322, xp: 10, explanation: "14 vuruğunu mərtəbələrə ayırırıq: 10 + 4. 23 × 10 = 230, 23 × 4 = 92. Cəmi: 230 + 92 = 322." },
            { id: "ry4-vurma-l2-t2", type: "numeric", prompt: "31 × 12 = ?", answer: 372, xp: 10, explanation: "12 vuruğunu mərtəbələrə ayırırıq: 10 + 2. 31 × 10 = 310, 31 × 2 = 62. Cəmi: 310 + 62 = 372." },
            { id: "ry4-vurma-l2-t3", type: "numeric", prompt: "45 × 20 = ?", answer: 900, xp: 10, explanation: "45 × 20 = 900." },
            { id: "ry4-vurma-l2-t4", type: "numeric", prompt: "16 × 15 = ?", answer: 240, xp: 10, explanation: "15 vuruğunu mərtəbələrə ayırırıq: 10 + 5. 16 × 10 = 160, 16 × 5 = 80. Cəmi: 160 + 80 = 240." },
            { id: "ry4-vurma-l2-t5", type: "numeric", prompt: "24 × 11 = ?", answer: 264, xp: 10, explanation: "11 vuruğunu mərtəbələrə ayırırıq: 10 + 1. 24 × 10 = 240, 24 × 1 = 24. Cəmi: 240 + 24 = 264." },
            { id: "ry4-vurma-l2-t6", type: "numeric", prompt: "52 × 13 = ?", answer: 676, xp: 10, explanation: "13 vuruğunu mərtəbələrə ayırırıq: 10 + 3. 52 × 10 = 520, 52 × 3 = 156. Cəmi: 520 + 156 = 676." },
            { id: "ry4-vurma-l2-t7", type: "numeric", prompt: "18 × 12 = ?", answer: 216, xp: 10, explanation: "12 vuruğunu mərtəbələrə ayırırıq: 10 + 2. 18 × 10 = 180, 18 × 2 = 36. Cəmi: 180 + 36 = 216." },
            { id: "ry4-vurma-l2-t8", type: "numeric", prompt: "100 × 25 = ?", answer: 2500, xp: 10, explanation: "25 vuruğunu mərtəbələrə ayırırıq: 20 + 5. 100 × 20 = 2000, 100 × 5 = 500. Cəmi: 2000 + 500 = 2500." },
            { id: "ry4-vurma-l2-t9", type: "numeric", prompt: "34 × 10 = ?", answer: 340, xp: 10, explanation: "34 × 10 = 340." },
            { id: "ry4-vurma-l2-t10", type: "numeric", prompt: "27 × 21 = ?", answer: 567, xp: 10, explanation: "21 vuruğunu mərtəbələrə ayırırıq: 20 + 1. 27 × 20 = 540, 27 × 1 = 27. Cəmi: 540 + 27 = 567." },
          ],
          bonusTasks: [
            { id: "ry4-vurma-l2-b1", type: "numeric", prompt: "Kinoteatrda 24 sıra var, hər sırada 18 oturacaq. Neçə oturacaq var?", answer: 432, xp: 15, explanation: "Hər sıradakı 18 oturacaq 24 dəfə təkrarlanır: 24 × 18. 18 × 20 = 360, 18 × 4 = 72; cəmi 360 + 72 = 432." },
            { id: "ry4-vurma-l2-b2", type: "numeric", prompt: "125 × 8 = ?", answer: 1000, xp: 15, explanation: "125 ədədini mərtəbələrə ayırırıq: 100 + 20 + 5. Hər hissəni vururuq: 100 × 8 = 800, 20 × 8 = 160, 5 × 8 = 40. Cəmi: 800 + 160 + 40 = 1000." },
            { id: "ry4-vurma-l2-b3", type: "numeric", prompt: "36 × 25 = ?", answer: 900, xp: 15, explanation: "25 vuruğunu mərtəbələrə ayırırıq: 20 + 5. 36 × 20 = 720, 36 × 5 = 180. Cəmi: 720 + 180 = 900." },
            { id: "ry4-vurma-l2-b4", type: "numeric", prompt: "19 × 19 = ?", answer: 361, xp: 15, explanation: "19 vuruğunu mərtəbələrə ayırırıq: 10 + 9. 19 × 10 = 190, 19 × 9 = 171. Cəmi: 190 + 171 = 361." },
          ],
        },
        {
          id: "ry4-vurma-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry4-vurma-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 3. Çoxrəqəmli bölmə ═══════════════
    {
      id: "ry4-bolme",
      title: "Çoxrəqəmli bölmə",
      description: "İkirəqəmli və üçrəqəmli ədədləri bölmək, qalıqlı bölmə.",
      lessons: [
        {
          id: "ry4-bolme-l1",
          title: "Bölmə",
          intro: "Böyük ədədləri bölürük.",
          sections: [
            { heading: "Bölmə", body: "48 ÷ 4 = 12. 100 ÷ 5 = 20. Bölünən ÷ bölən = qismət. Qalıqlı bölmə: 13 ÷ 4 = 3 (qalıq 1)." },
          ],
          tasks: [
            { id: "ry4-bolme-l1-t1", type: "numeric", prompt: "48 ÷ 4 = ?", answer: 12, xp: 10, explanation: "Hissə-hissə bölürük: 4 × 10 = 40, 4 × 2 = 8. Bu hissələrin cəmi 40 + 8 = 48, deməli qismət 10 + 2 = 12-dir." },
            { id: "ry4-bolme-l1-t2", type: "numeric", prompt: "60 ÷ 5 = ?", answer: 12, xp: 10, explanation: "Hissə-hissə bölürük: 5 × 10 = 50, 5 × 2 = 10. Bu hissələrin cəmi 50 + 10 = 60, deməli qismət 10 + 2 = 12-dir." },
            { id: "ry4-bolme-l1-t3", type: "numeric", prompt: "100 ÷ 5 = ?", answer: 20, xp: 10, explanation: "100-ü 5 bərabər hissəyə bölürük. Hər hissəyə 20 düşür, çünki 5 × 20 = 100." },
            { id: "ry4-bolme-l1-t4", type: "numeric", prompt: "84 ÷ 4 = ?", answer: 21, xp: 10, explanation: "Hissə-hissə bölürük: 4 × 20 = 80, 4 × 1 = 4. Bu hissələrin cəmi 80 + 4 = 84, deməli qismət 20 + 1 = 21-dir." },
            { id: "ry4-bolme-l1-t5", type: "numeric", prompt: "90 ÷ 3 = ?", answer: 30, xp: 10, explanation: "90-ı 3 bərabər hissəyə bölürük. Hər hissəyə 30 düşür, çünki 3 × 30 = 90." },
            { id: "ry4-bolme-l1-t6", type: "numeric", prompt: "72 ÷ 6 = ?", answer: 12, xp: 10, explanation: "Hissə-hissə bölürük: 6 × 10 = 60, 6 × 2 = 12. Bu hissələrin cəmi 60 + 12 = 72, deməli qismət 10 + 2 = 12-dir." },
            { id: "ry4-bolme-l1-t7", type: "numeric", prompt: "144 ÷ 12 = ?", answer: 12, xp: 10, explanation: "Hissə-hissə bölürük: 12 × 10 = 120, 12 × 2 = 24. Bu hissələrin cəmi 120 + 24 = 144, deməli qismət 10 + 2 = 12-dir." },
            { id: "ry4-bolme-l1-t8", type: "numeric", prompt: "200 ÷ 4 = ?", answer: 50, xp: 10, explanation: "200-ü 4 bərabər hissəyə bölürük. Hər hissəyə 50 düşür, çünki 4 × 50 = 200." },
            { id: "ry4-bolme-l1-t9", type: "numeric", prompt: "55 ÷ 5 = ?", answer: 11, xp: 10, explanation: "Hissə-hissə bölürük: 5 × 10 = 50, 5 × 1 = 5. Bu hissələrin cəmi 50 + 5 = 55, deməli qismət 10 + 1 = 11-dir." },
            { id: "ry4-bolme-l1-t10", type: "numeric", prompt: "96 ÷ 8 = ?", answer: 12, xp: 10, explanation: "Hissə-hissə bölürük: 8 × 10 = 80, 8 × 2 = 16. Bu hissələrin cəmi 80 + 16 = 96, deməli qismət 10 + 2 = 12-dir." },
            { id: "ry4-bolme-l1-t11", type: "numeric", prompt: "13 ÷ 4 bölməsində qalıq neçədir?", answer: 1, xp: 10, explanation: "4-ün 13-ə sığan ən böyük misli 12-dir (4 × 3). Qalıq: 13 − 12 = 1." },
            { id: "ry4-bolme-l1-t12", type: "numeric", prompt: "17 ÷ 5 bölməsində qalıq neçədir?", answer: 2, xp: 10, explanation: "5-in 17-yə sığan ən böyük misli 15-dir (5 × 3). Qalıq: 17 − 15 = 2." },
            { id: "ry4-bolme-l1-t13", type: "numeric", prompt: "300 ÷ 3 = ?", answer: 100, xp: 10, explanation: "300-ü 3 bərabər hissəyə bölürük. Hər hissəyə 100 düşür, çünki 3 × 100 = 300." },
            { id: "ry4-bolme-l1-t14", type: "numeric", prompt: "63 ÷ 3 = ?", answer: 21, xp: 10, explanation: "Hissə-hissə bölürük: 3 × 20 = 60, 3 × 1 = 3. Bu hissələrin cəmi 60 + 3 = 63, deməli qismət 20 + 1 = 21-dir." },
            { id: "ry4-bolme-l1-t15", type: "numeric", prompt: "120 ÷ 4 = ?", answer: 30, xp: 15, explanation: "120-ni 4 bərabər hissəyə bölürük. Hər hissəyə 30 düşür, çünki 4 × 30 = 120." },
          ],
          bonusTasks: [
            { id: "ry4-bolme-l1-b1", type: "numeric", prompt: "500 ÷ 5 = ?", answer: 100, xp: 15, explanation: "500-ü 5 bərabər hissəyə bölürük. Hər hissəyə 100 düşür, çünki 5 × 100 = 500." },
            { id: "ry4-bolme-l1-b2", type: "numeric", prompt: "25 ÷ 4 bölməsində qalıq neçədir?", answer: 1, xp: 15, explanation: "4-ün 25-ə sığan ən böyük misli 24-dür (4 × 6). Qalıq: 25 − 24 = 1." },
            { id: "ry4-bolme-l1-b3", type: "numeric", prompt: "168 ÷ 8 = ?", answer: 21, xp: 15, explanation: "Hissə-hissə bölürük: 8 × 20 = 160, 8 × 1 = 8. Bu hissələrin cəmi 160 + 8 = 168, deməli qismət 20 + 1 = 21-dir." },
            { id: "ry4-bolme-l1-b4", type: "numeric", prompt: "1000 ÷ 10 = ?", answer: 100, xp: 15, explanation: "1000-i 10 bərabər hissəyə bölürük. Hər hissəyə 100 düşür, çünki 10 × 100 = 1000." },
            { id: "ry4-bolme-l1-b5", type: "numeric", prompt: "132 ÷ 11 = ?", answer: 12, xp: 15, explanation: "Hissə-hissə bölürük: 11 × 10 = 110, 11 × 2 = 22. Bu hissələrin cəmi 110 + 22 = 132, deməli qismət 10 + 2 = 12-dir." },
          ],
        },
        {
          id: "ry4-bolme-l2",
          title: "İkirəqəmliyə bölmə",
          intro: "Böyük ədədləri addım-addım bölmək.",
          sections: [
            { heading: "Üsul", body: "144 ÷ 12: 12 × 10 = 120, qalıq 24. 12 × 2 = 24, qalıq 0. Deməli 144 ÷ 12 = 12." },
            { heading: "Yoxlama", body: "Nəticəni bölənə vur: 12 × 12 = 144. ✓" },
          ],
          tasks: [
            { id: "ry4-bolme-l2-t1", type: "numeric", prompt: "144 ÷ 12 = ?", answer: 12, xp: 10, explanation: "Hissə-hissə bölürük: 12 × 10 = 120, 12 × 2 = 24. Bu hissələrin cəmi 120 + 24 = 144, deməli qismət 10 + 2 = 12-dir." },
            { id: "ry4-bolme-l2-t2", type: "numeric", prompt: "240 ÷ 20 = ?", answer: 12, xp: 10, explanation: "Hissə-hissə bölürük: 20 × 10 = 200, 20 × 2 = 40. Bu hissələrin cəmi 200 + 40 = 240, deməli qismət 10 + 2 = 12-dir." },
            { id: "ry4-bolme-l2-t3", type: "numeric", prompt: "198 ÷ 11 = ?", answer: 18, xp: 10, explanation: "Hissə-hissə bölürük: 11 × 10 = 110, 11 × 8 = 88. Bu hissələrin cəmi 110 + 88 = 198, deməli qismət 10 + 8 = 18-dir." },
            { id: "ry4-bolme-l2-t4", type: "numeric", prompt: "375 ÷ 25 = ?", answer: 15, xp: 10, explanation: "Hissə-hissə bölürük: 25 × 10 = 250, 25 × 5 = 125. Bu hissələrin cəmi 250 + 125 = 375, deməli qismət 10 + 5 = 15-dir." },
            { id: "ry4-bolme-l2-t5", type: "numeric", prompt: "480 ÷ 16 = ?", answer: 30, xp: 10, explanation: "480-i 16 bərabər hissəyə bölürük. Hər hissəyə 30 düşür, çünki 16 × 30 = 480." },
            { id: "ry4-bolme-l2-t6", type: "numeric", prompt: "169 ÷ 13 = ?", answer: 13, xp: 10, explanation: "Hissə-hissə bölürük: 13 × 10 = 130, 13 × 3 = 39. Bu hissələrin cəmi 130 + 39 = 169, deməli qismət 10 + 3 = 13-dir." },
            { id: "ry4-bolme-l2-t7", type: "numeric", prompt: "600 ÷ 24 = ?", answer: 25, xp: 10, explanation: "Hissə-hissə bölürük: 24 × 20 = 480, 24 × 5 = 120. Bu hissələrin cəmi 480 + 120 = 600, deməli qismət 20 + 5 = 25-dir." },
            { id: "ry4-bolme-l2-t8", type: "numeric", prompt: "840 ÷ 40 = ?", answer: 21, xp: 10, explanation: "Hissə-hissə bölürük: 40 × 20 = 800, 40 × 1 = 40. Bu hissələrin cəmi 800 + 40 = 840, deməli qismət 20 + 1 = 21-dir." },
            { id: "ry4-bolme-l2-t9", type: "multiple_choice", prompt: "Bölmənin nəticəsini necə yoxlayırıq?", options: ["Bölənə vururuq", "Bölənə bölürük", "Toplayırıq", "Çıxırıq"], correctIndex: 0, xp: 10, explanation: "Qismətlə böləni vursaq, bölünən alınmalıdır — ona görə bölmə vurma ilə yoxlanır." },
            { id: "ry4-bolme-l2-t10", type: "numeric", prompt: "252 ÷ 14 = ?", answer: 18, xp: 10, explanation: "Hissə-hissə bölürük: 14 × 10 = 140, 14 × 8 = 112. Bu hissələrin cəmi 140 + 112 = 252, deməli qismət 10 + 8 = 18-dir." },
          ],
          bonusTasks: [
            { id: "ry4-bolme-l2-b1", type: "numeric", prompt: "288 şəkil 24 albomda bərabər yerləşdi. Hər albomda neçə şəkil var?", answer: 12, xp: 15, explanation: "288 şəkli 24 alboma bərabər paylayırıq: 24 × 10 = 240, qalan 48 üçün 24 × 2 = 48. Deməli 10 + 2 = 12 şəkil." },
            { id: "ry4-bolme-l2-b2", type: "numeric", prompt: "1000 ÷ 25 = ?", answer: 40, xp: 15, explanation: "1000-i 25 bərabər hissəyə bölürük. Hər hissəyə 40 düşür, çünki 25 × 40 = 1000." },
            { id: "ry4-bolme-l2-b3", type: "numeric", prompt: "756 ÷ 21 = ?", answer: 36, xp: 15, explanation: "Hissə-hissə bölürük: 21 × 30 = 630, 21 × 6 = 126. Bu hissələrin cəmi 630 + 126 = 756, deməli qismət 30 + 6 = 36-dir." },
            { id: "ry4-bolme-l2-b4", type: "numeric", prompt: "945 ÷ 35 = ?", answer: 27, xp: 15, explanation: "Hissə-hissə bölürük: 35 × 20 = 700, 35 × 7 = 245. Bu hissələrin cəmi 700 + 245 = 945, deməli qismət 20 + 7 = 27-dir." },
          ],
        },
        {
          id: "ry4-bolme-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry4-bolme-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 4. Kəsrlər ═══════════════
    {
      id: "ry4-kesr",
      title: "Kəsrlər",
      description: "Kəsrlərin müqayisəsi və eyni məxrəcli kəsrlərin toplanması-çıxılması.",
      lessons: [
        {
          id: "ry4-kesr-l1",
          title: "Kəsrlərlə əməllər",
          intro: "Kəsrləri müqayisə edək, toplayaq, çıxaq.",
          sections: [
            { heading: "Müqayisə", body: "Eyni məxrəcli kəsrlərdən sürəti böyük olan böyükdür: 3/5 > 2/5. Sürət eynidirsə, məxrəci kiçik olan böyükdür: 1/2 > 1/4." },
            { heading: "Toplama və çıxma", body: "Eyni məxrəcli kəsrlərdə sürətlər toplanır/çıxılır, məxrəc dəyişmir: 1/5 + 2/5 = 3/5. 4/7 − 1/7 = 3/7." },
          ],
          tasks: [
            { id: "ry4-kesr-l1-t1", type: "multiple_choice", prompt: "3/5 və 2/5 kəsrlərindən böyüyü hansıdır?", options: ["3/5", "2/5", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "Məxrəclər eynidir (5), ona görə saylara baxırıq: 3 > 2. Deməli 3/5 böyükdür." },
            { id: "ry4-kesr-l1-t2", type: "multiple_choice", prompt: "1/2 və 1/4 kəsrlərindən böyüyü hansıdır?", options: ["1/2", "1/4", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "Sayları eynidir, məxrəclərə baxırıq: bütöv 2 hissəyə bölünəndə hər pay 4 hissəyə bölünəndəkindən böyük olur." },
            { id: "ry4-kesr-l1-t3", type: "multiple_choice", prompt: "1/5 + 2/5 = ?", options: ["3/5", "3/10", "2/5", "3/25"], correctIndex: 0, xp: 10, explanation: "Məxrəclər eynidir (5), ona görə yalnız sayları toplayırıq: 1 + 2 = 3. Məxrəc dəyişmir: 3/5." },
            { id: "ry4-kesr-l1-t4", type: "multiple_choice", prompt: "4/7 − 1/7 = ?", options: ["3/7", "3/14", "5/7", "3/0"], correctIndex: 0, xp: 10, explanation: "Məxrəclər eynidir (7), ona görə yalnız sayları çıxırıq: 4 − 1 = 3. Məxrəc dəyişmir: 3/7." },
            { id: "ry4-kesr-l1-t5", type: "multiple_choice", prompt: "2/6 + 3/6 = ?", options: ["5/6", "5/12", "6/6", "5/36"], correctIndex: 0, xp: 10, explanation: "Məxrəclər eynidir (6), ona görə yalnız sayları toplayırıq: 2 + 3 = 5. Məxrəc dəyişmir: 5/6." },
            { id: "ry4-kesr-l1-t6", type: "multiple_choice", prompt: "5/8 − 2/8 = ?", options: ["3/8", "3/16", "7/8", "3/0"], correctIndex: 0, xp: 10, explanation: "Məxrəclər eynidir (8), ona görə yalnız sayları çıxırıq: 5 − 2 = 3. Məxrəc dəyişmir: 3/8." },
            { id: "ry4-kesr-l1-t7", type: "multiple_choice", prompt: "1/3 + 1/3 = ?", options: ["2/3", "2/6", "1/3", "2/9"], correctIndex: 0, xp: 10, explanation: "Məxrəclər eynidir (3), ona görə yalnız sayları toplayırıq: 1 + 1 = 2. Məxrəc dəyişmir: 2/3." },
            { id: "ry4-kesr-l1-t8", type: "multiple_choice", prompt: "Hansı kəsr daha böyükdür: 1/3 yoxsa 1/6?", options: ["1/3", "1/6", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "Sayları eynidir, məxrəclərə baxırıq: 3 < 6, yəni bütöv az hissəyə bölünüb — pay daha böyükdür." },
            { id: "ry4-kesr-l1-t9", type: "multiple_choice", prompt: "3/4 və 1/4 kəsrlərindən böyüyü hansıdır?", options: ["3/4", "1/4", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "Məxrəclər eynidir (4), ona görə saylara baxırıq: 3 > 1." },
            { id: "ry4-kesr-l1-t10", type: "multiple_choice", prompt: "2/9 + 4/9 = ?", options: ["6/9", "6/18", "8/9", "6/81"], correctIndex: 0, xp: 10, explanation: "Məxrəclər eynidir (9), ona görə yalnız sayları toplayırıq: 2 + 4 = 6. Məxrəc dəyişmir: 6/9." },
            { id: "ry4-kesr-l1-t11", type: "multiple_choice", prompt: "7/10 − 3/10 = ?", options: ["4/10", "4/20", "10/10", "4/0"], correctIndex: 0, xp: 10, explanation: "Məxrəclər eynidir (10), ona görə yalnız sayları çıxırıq: 7 − 3 = 4. Məxrəc dəyişmir: 4/10." },
            { id: "ry4-kesr-l1-t12", type: "multiple_choice", prompt: "2/4 + 2/4 = ? (bütöv)", options: ["1 (bütöv)", "4/8", "2/4", "4/16"], correctIndex: 0, xp: 10, explanation: "Məxrəclər eynidir (4), ona görə yalnız sayları toplayırıq: 2 + 2 = 4. Məxrəc dəyişmir: 4/4." },
            { id: "ry4-kesr-l1-t13", type: "multiple_choice", prompt: "Eyni məxrəcli kəsrləri toplayanda nə edirik?", options: ["sürətləri toplayırıq", "məxrəcləri toplayırıq", "hər ikisini toplayırıq", "vururuq"], correctIndex: 0, xp: 10, explanation: "Hissələrin ölçüsü (məxrəc) eynidir, ona görə sadəcə neçə hissə olduğunu, yəni sayları toplayırıq." },
            { id: "ry4-kesr-l1-t14", type: "multiple_choice", prompt: "6/8 − 4/8 = ?", options: ["2/8", "2/16", "10/8", "2/0"], correctIndex: 0, xp: 10, explanation: "Məxrəclər eynidir (8), ona görə yalnız sayları çıxırıq: 6 − 4 = 2. Məxrəc dəyişmir: 2/8." },
            { id: "ry4-kesr-l1-t15", type: "multiple_choice", prompt: "1/6 + 4/6 = ?", options: ["5/6", "5/12", "5/36", "6/6"], correctIndex: 0, xp: 15, explanation: "Məxrəclər eynidir (6), ona görə yalnız sayları toplayırıq: 1 + 4 = 5. Məxrəc dəyişmir: 5/6." },
          ],
          bonusTasks: [
            { id: "ry4-kesr-l1-b1", type: "multiple_choice", prompt: "3/10 + 7/10 = ? (bütöv)", options: ["1 (bütöv)", "10/20", "10/100", "3/7"], correctIndex: 0, xp: 15, explanation: "Məxrəclər eynidir (10), ona görə yalnız sayları toplayırıq: 3 + 7 = 10. Məxrəc dəyişmir: 10/10." },
            { id: "ry4-kesr-l1-b2", type: "numeric", prompt: "12 almanın 1/4-i neçədir?", answer: 3, xp: 15, explanation: "1/4 dörddə bir deməkdir, ona görə 4-ə bölürük: 12 : 4 = 3." },
            { id: "ry4-kesr-l1-b3", type: "numeric", prompt: "20 konfetin 3/4-ü neçədir? (20:4×3)", answer: 15, xp: 15, explanation: "Əvvəl bir hissəni tapırıq: 20 : 4 = 5. Sonra üç hissəni: 5 × 3 = 15." },
            { id: "ry4-kesr-l1-b4", type: "multiple_choice", prompt: "1/2 kəsri hansı kəsrə bərabərdir?", options: ["2/4", "1/4", "3/4", "2/3"], correctIndex: 0, xp: 15, explanation: "Say və məxrəci eyni ədədə vursaq, kəsrin qiyməti dəyişmir: 1/2 = (1×2)/(2×2) = 2/4." },
            { id: "ry4-kesr-l1-b5", type: "multiple_choice", prompt: "5/9 − 5/9 = ?", options: ["0", "1", "5/9", "10/9"], correctIndex: 0, xp: 15, explanation: "Məxrəclər eynidir (9), ona görə yalnız sayları çıxırıq: 5 − 5 = 0. Məxrəc dəyişmir: 0/9." },
          ],
        },
        {
          id: "ry4-kesr-l2",
          title: "Kəsrləri toplamaq və çıxmaq",
          intro: "Məxrəclər eynidirsə asandır.",
          sections: [
            { heading: "Eyni məxrəc", body: "Yalnız sayları toplayırıq, məxrəc dəyişmir: 2/7 + 3/7 = 5/7." },
            { heading: "Sadələşdirmə", body: "4/8 kəsrini həm sayı, həm məxrəci 4-ə bölsək 1/2 alınır — bu, sadələşdirmədir." },
          ],
          tasks: [
            { id: "ry4-kesr-l2-t1", type: "multiple_choice", prompt: "2/7 + 3/7 = ?", options: ["5/7", "5/14", "6/7", "1/7"], correctIndex: 0, xp: 10, explanation: "Məxrəclər eynidir (7), ona görə yalnız sayları toplayırıq: 2 + 3 = 5. Məxrəc dəyişmir: 5/7." },
            { id: "ry4-kesr-l2-t2", type: "multiple_choice", prompt: "5/9 − 2/9 = ?", options: ["3/9", "3/18", "7/9", "2/9"], correctIndex: 0, xp: 10, explanation: "Məxrəclər eynidir (9), ona görə yalnız sayları çıxırıq: 5 − 2 = 3. Məxrəc dəyişmir: 3/9." },
            { id: "ry4-kesr-l2-t3", type: "multiple_choice", prompt: "4/8 kəsrini sadələşdir.", options: ["1/2", "1/4", "2/4", "4/8"], correctIndex: 0, xp: 10, explanation: "Say və məxrəcin hər ikisi 4-ə bölünür: 4:4 = 1, 8:4 = 2. Deməli 1/2." },
            { id: "ry4-kesr-l2-t4", type: "multiple_choice", prompt: "3/6 kəsrini sadələşdir.", options: ["1/2", "1/3", "2/3", "3/6"], correctIndex: 0, xp: 10, explanation: "Say və məxrəcin hər ikisi 3-ə bölünür: 3:3 = 1, 6:3 = 2. Deməli 1/2." },
            { id: "ry4-kesr-l2-t5", type: "multiple_choice", prompt: "1/5 + 2/5 = ?", options: ["3/5", "3/10", "2/5", "1/10"], correctIndex: 0, xp: 10, explanation: "Məxrəclər eynidir (5), ona görə yalnız sayları toplayırıq: 1 + 2 = 3. Məxrəc dəyişmir: 3/5." },
            { id: "ry4-kesr-l2-t6", type: "multiple_choice", prompt: "Eyni məxrəcli kəsrləri toplayanda məxrəc necə olur?", options: ["Dəyişmir", "Toplanır", "Vurulur", "Bölünür"], correctIndex: 0, xp: 10, explanation: "Məxrəc hissənin ölçüsünü göstərir; hissələrin ölçüsü dəyişmədiyi üçün məxrəc də olduğu kimi qalır." },
            { id: "ry4-kesr-l2-t7", type: "multiple_choice", prompt: "6/8 − 2/8 = ?", options: ["4/8", "4/16", "8/8", "2/8"], correctIndex: 0, xp: 10, explanation: "Məxrəclər eynidir (8), ona görə yalnız sayları çıxırıq: 6 − 2 = 4. Məxrəc dəyişmir: 4/8." },
            { id: "ry4-kesr-l2-t8", type: "numeric", prompt: "Bir tortun 3/8-i yeyildi. Neçə səkkizdə bir hissə qaldı? (say ilə)", answer: 5, xp: 10, explanation: "Tort 8 hissəyə bölünüb, 3-ü yeyilib: 8 − 3 = 5 hissə qaldı." },
            { id: "ry4-kesr-l2-t9", type: "multiple_choice", prompt: "2/10 kəsrini sadələşdir.", options: ["1/5", "1/10", "2/5", "1/2"], correctIndex: 0, xp: 10, explanation: "Say və məxrəcin hər ikisi 2-yə bölünür: 2:2 = 1, 10:2 = 5. Deməli 1/5." },
            { id: "ry4-kesr-l2-t10", type: "multiple_choice", prompt: "7/7 kəsri neçəyə bərabərdir?", options: ["1", "0", "7", "1/7"], correctIndex: 0, xp: 10, explanation: "Sayla məxrəc bərabər olanda bütün hissələr götürülüb, yəni tam bütöv alınır: 7/7 = 1." },
          ],
          bonusTasks: [
            { id: "ry4-kesr-l2-b1", type: "multiple_choice", prompt: "1/4 + 1/4 + 1/4 = ?", options: ["3/4", "1/12", "3/12", "1/4"], correctIndex: 0, xp: 15, explanation: "Məxrəclər eynidir (4), sayları toplayırıq: 1 + 1 + 1 = 3. Nəticə 3/4." },
            { id: "ry4-kesr-l2-b2", type: "multiple_choice", prompt: "9/12 kəsrini sadələşdir.", options: ["3/4", "1/3", "2/3", "9/12"], correctIndex: 0, xp: 15, explanation: "Say və məxrəcin hər ikisi 3-ə bölünür: 9:3 = 3, 12:3 = 4. Deməli 3/4." },
            { id: "ry4-kesr-l2-b3", type: "numeric", prompt: "Bir pizzanın 2/6-sını yedim, 3/6-sını qardaşım yedi. Neçə altıda bir hissə qaldı?", answer: 1, xp: 15, explanation: "Yeyilən hissələri toplayırıq: 2 + 3 = 5. Bütöv 6 hissədir: 6 − 5 = 1 hissə qaldı." },
            { id: "ry4-kesr-l2-b4", type: "multiple_choice", prompt: "5/5 − 2/5 = ?", options: ["3/5", "3/10", "7/5", "2/5"], correctIndex: 0, xp: 15, explanation: "Məxrəclər eynidir (5), ona görə yalnız sayları çıxırıq: 5 − 2 = 3. Məxrəc dəyişmir: 3/5." },
          ],
        },
        {
          id: "ry4-kesr-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry4-kesr-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 5. Onluq kəsrlər və ölçmə ═══════════════
    {
      id: "ry4-onluq",
      title: "Onluq kəsrlər və ölçmə",
      description: "Onluq kəsrlərlə tanışlıq və ölçü vahidləri.",
      lessons: [
        {
          id: "ry4-onluq-l1",
          title: "Onluq kəsrlər",
          intro: "Vergüllü ədədlər: 0.5, 1.5, 2.25.",
          sections: [
            { heading: "Onluq kəsr", body: "Vergüldən sonrakı hissə bütövün hissəsidir. 0.5 = yarım = 1/2. 0.25 = dörddə bir = 1/4. 1.5 = bir tam yarım." },
            { heading: "Ölçmə", body: "1 m = 100 sm, 1 km = 1000 m, 1 kq = 1000 q, 1 litr, 1 saat = 60 dəq." },
          ],
          tasks: [
            { id: "ry4-onluq-l1-t1", type: "numeric", prompt: "0.5 + 0.5 = ? (onluq)", answer: 1, xp: 10, explanation: "Hər ikisini onda bir kimi sayırıq: 0,5 = 5 onda bir, 0,5 = 5 onda bir. 5 + 5 = 10 onda bir, yəni 1,0." },
            { id: "ry4-onluq-l1-t2", type: "numeric", prompt: "1.5 + 0.5 = ? (onluq)", answer: 2, xp: 10, explanation: "Hər ikisini onda bir kimi sayırıq: 1,5 = 15 onda bir, 0,5 = 5 onda bir. 15 + 5 = 20 onda bir, yəni 2,0." },
            { id: "ry4-onluq-l1-t3", type: "numeric", prompt: "0.25 + 0.25 = ? (onluq)", answer: 0.5, tolerance: 0.001, xp: 10, explanation: "Hər ikisini yüzdə bir kimi sayırıq: 0,25 = 25 yüzdə bir, 0,25 = 25 yüzdə bir. 25 + 25 = 50 yüzdə bir, yəni 0,50." },
            { id: "ry4-onluq-l1-t4", type: "multiple_choice", prompt: "0.5 hansı kəsrə bərabərdir?", options: ["1/2", "1/4", "1/5", "1/10"], correctIndex: 0, xp: 10, explanation: "0,5 yarım deməkdir — bütövün iki bərabər hissəsindən biri, yəni 1/2." },
            { id: "ry4-onluq-l1-t5", type: "multiple_choice", prompt: "0.25 hansı kəsrə bərabərdir?", options: ["1/4", "1/2", "1/5", "2/5"], correctIndex: 0, xp: 10, explanation: "0,25 bütövün dörddə biridir: 0,25 × 4 = 1. Deməli 1/4." },
            { id: "ry4-onluq-l1-t6", type: "numeric", prompt: "2.5 + 2.5 = ? (onluq)", answer: 5, xp: 10, explanation: "Hər ikisini onda bir kimi sayırıq: 2,5 = 25 onda bir, 2,5 = 25 onda bir. 25 + 25 = 50 onda bir, yəni 5,0." },
            { id: "ry4-onluq-l1-t7", type: "numeric", prompt: "1 m neçə sm-dir?", answer: 100, xp: 10, explanation: "1 m = 100 sm, deməli 1 × 100 = 100 sm." },
            { id: "ry4-onluq-l1-t8", type: "numeric", prompt: "1 km neçə metrdir?", answer: 1000, xp: 10, explanation: "1 km = 1000 m, deməli 1 × 1000 = 1000 m." },
            { id: "ry4-onluq-l1-t9", type: "numeric", prompt: "1 kq neçə qramdır?", answer: 1000, xp: 10, explanation: "1 kq = 1000 q, deməli 1 × 1000 = 1000 q." },
            { id: "ry4-onluq-l1-t10", type: "numeric", prompt: "2 km neçə metrdir?", answer: 2000, xp: 10, explanation: "1 km = 1000 m, deməli 2 × 1000 = 2000 m." },
            { id: "ry4-onluq-l1-t11", type: "numeric", prompt: "1.0 − 0.5 = ? (onluq)", answer: 0.5, tolerance: 0.001, xp: 10, explanation: "Hər ikisini onda bir kimi sayırıq: 1,0 = 10 onda bir, 0,5 = 5 onda bir. 10 − 5 = 5 onda bir, yəni 0,5." },
            { id: "ry4-onluq-l1-t12", type: "multiple_choice", prompt: "0.5 və 0.25 ədədlərindən böyüyü hansıdır?", options: ["0.5", "0.25", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "Onda birlər mərtəbəsinə baxırıq: 0,5-də 5, 0,25-də isə 2. 5 > 2, deməli 0,5 böyükdür." },
            { id: "ry4-onluq-l1-t13", type: "numeric", prompt: "3 saat neçə dəqiqədir?", answer: 180, xp: 10, explanation: "1 saat = 60 dəqiqə, deməli 3 × 60 = 180 dəqiqə." },
            { id: "ry4-onluq-l1-t14", type: "numeric", prompt: "500 q + 500 q neçə kq-dır?", answer: 1, xp: 10, explanation: "500 + 500 = 1000 qram, 1000 qram isə 1 kiloqramdır." },
            { id: "ry4-onluq-l1-t15", type: "numeric", prompt: "1.5 + 1.5 = ? (onluq)", answer: 3, xp: 15, explanation: "Hər ikisini onda bir kimi sayırıq: 1,5 = 15 onda bir, 1,5 = 15 onda bir. 15 + 15 = 30 onda bir, yəni 3,0." },
          ],
          bonusTasks: [
            { id: "ry4-onluq-l1-b1", type: "numeric", prompt: "2.75 + 0.25 = ? (onluq)", answer: 3, xp: 15, explanation: "Hər ikisini yüzdə bir kimi sayırıq: 2,75 = 275 yüzdə bir, 0,25 = 25 yüzdə bir. 275 + 25 = 300 yüzdə bir, yəni 3,00." },
            { id: "ry4-onluq-l1-b2", type: "numeric", prompt: "5 km neçə metrdir?", answer: 5000, xp: 15, explanation: "1 km = 1000 m, deməli 5 × 1000 = 5000 m." },
            { id: "ry4-onluq-l1-b3", type: "multiple_choice", prompt: "0.1 hansı kəsrə bərabərdir?", options: ["1/10", "1/2", "1/4", "1/100"], correctIndex: 0, xp: 15, explanation: "0,1 bütövün onda biridir: 0,1 × 10 = 1. Deməli 1/10." },
            { id: "ry4-onluq-l1-b4", type: "numeric", prompt: "3.5 − 1.5 = ? (onluq)", answer: 2, xp: 15, explanation: "Hər ikisini onda bir kimi sayırıq: 3,5 = 35 onda bir, 1,5 = 15 onda bir. 35 − 15 = 20 onda bir, yəni 2,0." },
            { id: "ry4-onluq-l1-b5", type: "numeric", prompt: "2 kq 500 q neçə qramdır?", answer: 2500, xp: 15, explanation: "2 kq = 2 × 1000 = 2000 q. Üstünə 500 q: 2000 + 500 = 2500 q." },
          ],
        },
        {
          id: "ry4-onluq-l2",
          title: "Onluq kəsrlərlə əməllər",
          intro: "Vergüllər alt-alta düşməlidir.",
          sections: [
            { heading: "Toplama-çıxma", body: "Vergülləri düz alt-alta yaz, sonra adi kimi topla: 2,5 + 1,3 = 3,8." },
            { heading: "Ölçmə ilə əlaqə", body: "1 m = 100 sm, deməli 1,5 m = 150 sm. 1 kq = 1000 q, deməli 2,5 kq = 2500 q." },
          ],
          tasks: [
            { id: "ry4-onluq-l2-t1", type: "numeric", prompt: "2,5 + 1,3 = ? (nəticəni onda bir ilə yaz, məs. 3.8)", answer: 3.8, xp: 10, explanation: "Hər ikisini onda bir kimi sayırıq: 2,5 = 25 onda bir, 1,3 = 13 onda bir. 25 + 13 = 38 onda bir, yəni 3,8." },
            { id: "ry4-onluq-l2-t2", type: "numeric", prompt: "5,7 − 2,4 = ?", answer: 3.3, xp: 10, explanation: "Hər ikisini onda bir kimi sayırıq: 5,7 = 57 onda bir, 2,4 = 24 onda bir. 57 − 24 = 33 onda bir, yəni 3,3." },
            { id: "ry4-onluq-l2-t3", type: "numeric", prompt: "0,5 + 0,5 = ?", answer: 1, xp: 10, explanation: "Hər ikisini onda bir kimi sayırıq: 0,5 = 5 onda bir, 0,5 = 5 onda bir. 5 + 5 = 10 onda bir, yəni 1,0." },
            { id: "ry4-onluq-l2-t4", type: "numeric", prompt: "1,5 metr neçə santimetrdir?", answer: 150, xp: 10, explanation: "1 m = 100 sm. Deməli 1,5 m = 1,5 × 100 = 150 sm." },
            { id: "ry4-onluq-l2-t5", type: "numeric", prompt: "2,5 kiloqram neçə qramdır?", answer: 2500, xp: 10, explanation: "1 kq = 1000 q. Deməli 2,5 kq = 2,5 × 1000 = 2500 q." },
            { id: "ry4-onluq-l2-t6", type: "numeric", prompt: "3,2 + 4,8 = ?", answer: 8, xp: 10, explanation: "Hər ikisini onda bir kimi sayırıq: 3,2 = 32 onda bir, 4,8 = 48 onda bir. 32 + 48 = 80 onda bir, yəni 8,0." },
            { id: "ry4-onluq-l2-t7", type: "numeric", prompt: "10 − 2,5 = ?", answer: 7.5, xp: 10, explanation: "Hər ikisini onda bir kimi sayırıq: 10 = 100 onda bir, 2,5 = 25 onda bir. 100 − 25 = 75 onda bir, yəni 7,5." },
            { id: "ry4-onluq-l2-t8", type: "multiple_choice", prompt: "Onluq kəsrləri toplayanda nəyə diqqət edirik?", options: ["Vergüllər alt-alta düşməlidir", "Rəqəmlərin sayına", "Böyüklüyünə", "Heç nəyə"], correctIndex: 0, xp: 10, explanation: "Vergüllər alt-alta düşməlidir ki, tam hissə tam hissə ilə, onda bir onda birlə toplansın." },
            { id: "ry4-onluq-l2-t9", type: "numeric", prompt: "0,25 metr neçə santimetrdir?", answer: 25, xp: 10, explanation: "1 m = 100 sm. Deməli 0,25 m = 0,25 × 100 = 25 sm." },
            { id: "ry4-onluq-l2-t10", type: "numeric", prompt: "1,75 + 0,25 = ?", answer: 2, xp: 10, explanation: "Hər ikisini yüzdə bir kimi sayırıq: 1,75 = 175 yüzdə bir, 0,25 = 25 yüzdə bir. 175 + 25 = 200 yüzdə bir, yəni 2,00." },
          ],
          bonusTasks: [
            { id: "ry4-onluq-l2-b1", type: "numeric", prompt: "4,6 − 1,85 = ?", answer: 2.75, xp: 15, explanation: "Hər ikisini yüzdə bir kimi sayırıq: 4,6 = 460 yüzdə bir, 1,85 = 185 yüzdə bir. 460 − 185 = 275 yüzdə bir, yəni 2,75." },
            { id: "ry4-onluq-l2-b2", type: "numeric", prompt: "0,5 kq + 750 q neçə qramdır?", answer: 1250, xp: 15, explanation: "Əvvəl eyni vahidə gətiririk: 0,5 kq = 500 q. Sonra toplayırıq: 500 + 750 = 1250 q." },
            { id: "ry4-onluq-l2-b3", type: "numeric", prompt: "12,5 ÷ 5 = ?", answer: 2.5, xp: 15, explanation: "12,5-i 125 onda bir kimi sayırıq: 125 : 5 = 25 onda bir, yəni 2,5." },
            { id: "ry4-onluq-l2-b4", type: "numeric", prompt: "2,5 × 4 = ?", answer: 10, xp: 15, explanation: "2,5-i 25 onda bir kimi sayırıq: 25 × 4 = 100 onda bir, yəni 10." },
          ],
        },
        {
          id: "ry4-onluq-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry4-onluq-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 6. Sahə, əməllər sırası və məsələlər ═══════════════
    {
      id: "ry4-sahe",
      title: "Sahə, əməllər sırası və məsələlər",
      description: "Düzbucaqlının sahəsi, əməllərin sırası və mətn məsələləri.",
      lessons: [
        {
          id: "ry4-sahe-l1",
          title: "Sahə və əməllər sırası",
          intro: "Sahə hesablamaq və əməllərin düzgün sırası.",
          sections: [
            { heading: "Sahə", body: "Düzbucaqlının sahəsi = uzunluq × en. Kvadratın sahəsi = tərəf × tərəf. Sahə kvadrat vahidlərlə (kv.sm, kv.m) ölçülür." },
            { heading: "Əməllər sırası", body: "Əvvəlcə mötərizə, sonra vurma və bölmə, sonra toplama və çıxma: 2 + 3 × 4 = 2 + 12 = 14." },
          ],
          tasks: [
            { id: "ry4-sahe-l1-t1", type: "numeric", prompt: "Düzbucaqlının uzunluğu 5, eni 3-dür. Sahəsi? (5×3)", answer: 15, xp: 10, explanation: "Sahə uzunluqla enin hasilidir: 5 × 3 = 15." },
            { id: "ry4-sahe-l1-t2", type: "numeric", prompt: "Kvadratın tərəfi 4-dür. Sahəsi? (4×4)", answer: 16, xp: 10, explanation: "Kvadratda uzunluqla en eynidir: 4 × 4 = 16." },
            { id: "ry4-sahe-l1-t3", type: "numeric", prompt: "Düzbucaqlının uzunluğu 6, eni 4-dür. Sahəsi?", answer: 24, xp: 10, explanation: "Sahə uzunluqla enin hasilidir: 6 × 4 = 24." },
            { id: "ry4-sahe-l1-t4", type: "numeric", prompt: "Kvadratın tərəfi 5-dir. Sahəsi?", answer: 25, xp: 10, explanation: "Kvadratda uzunluqla en eynidir: 5 × 5 = 25." },
            { id: "ry4-sahe-l1-t5", type: "numeric", prompt: "2 + 3 × 4 = ?", answer: 14, xp: 10, explanation: "Əvvəl vurma/bölmə, sonra toplama/çıxma. Əvvəl vurma: 3 × 4 = 12, sonra toplama: 2 + 12 = 14." },
            { id: "ry4-sahe-l1-t6", type: "numeric", prompt: "10 − 2 × 3 = ?", answer: 4, xp: 10, explanation: "Əvvəl vurma/bölmə, sonra toplama/çıxma. Əvvəl vurma: 2 × 3 = 6, sonra çıxma: 10 − 6 = 4." },
            { id: "ry4-sahe-l1-t7", type: "numeric", prompt: "(2 + 3) × 4 = ?", answer: 20, xp: 10, explanation: "Mötərizə birinci, sonra vurma/bölmə, ən sonda toplama/çıxma. Əvvəl mötərizə: 2 + 3 = 5, sonra vurma: 5 × 4 = 20." },
            { id: "ry4-sahe-l1-t8", type: "numeric", prompt: "12 ÷ 4 + 5 = ?", answer: 8, xp: 10, explanation: "Əvvəl vurma/bölmə, sonra toplama/çıxma. Əvvəl bölmə: 12 : 4 = 3, sonra toplama: 3 + 5 = 8." },
            { id: "ry4-sahe-l1-t9", type: "numeric", prompt: "6 + 6 ÷ 2 = ?", answer: 9, xp: 10, explanation: "Əvvəl vurma/bölmə, sonra toplama/çıxma. Əvvəl bölmə: 6 : 2 = 3, sonra toplama: 6 + 3 = 9." },
            { id: "ry4-sahe-l1-t10", type: "numeric", prompt: "Düzbucaqlının uzunluğu 10, eni 2-dir. Sahəsi?", answer: 20, xp: 10, explanation: "Sahə uzunluqla enin hasilidir: 10 × 2 = 20." },
            { id: "ry4-sahe-l1-t11", type: "numeric", prompt: "3 × 3 + 1 = ?", answer: 10, xp: 10, explanation: "Əvvəl vurma/bölmə, sonra toplama/çıxma. Əvvəl vurma: 3 × 3 = 9, sonra toplama: 9 + 1 = 10." },
            { id: "ry4-sahe-l1-t12", type: "numeric", prompt: "20 − 4 × 2 = ?", answer: 12, xp: 10, explanation: "Əvvəl vurma/bölmə, sonra toplama/çıxma. Əvvəl vurma: 4 × 2 = 8, sonra çıxma: 20 − 8 = 12." },
            { id: "ry4-sahe-l1-t13", type: "numeric", prompt: "Kvadratın tərəfi 10-dur. Sahəsi?", answer: 100, xp: 10, explanation: "Kvadratda uzunluqla en eynidir: 10 × 10 = 100." },
            { id: "ry4-sahe-l1-t14", type: "numeric", prompt: "(10 − 4) × 2 = ?", answer: 12, xp: 10, explanation: "Mötərizə birinci, sonra vurma/bölmə, ən sonda toplama/çıxma. Əvvəl mötərizə: 10 − 4 = 6, sonra vurma: 6 × 2 = 12." },
            { id: "ry4-sahe-l1-t15", type: "numeric", prompt: "5 × 2 + 3 × 2 = ?", answer: 16, xp: 15, explanation: "Əvvəl vurma/bölmə, sonra toplama/çıxma. Əvvəl vurma: 5 × 2 = 10, sonra vurma: 3 × 2 = 6, sonra toplama: 10 + 6 = 16." },
          ],
          bonusTasks: [
            { id: "ry4-sahe-l1-b1", type: "numeric", prompt: "Sahəsi 24, eni 4 olan düzbucaqlının uzunluğu? (24÷4)", answer: 6, xp: 15, explanation: "Sahə = uzunluq × en. Uzunluğu tapmaq üçün sahəni enə bölürük: 24 : 4 = 6." },
            { id: "ry4-sahe-l1-b2", type: "numeric", prompt: "2 × (3 + 4) − 5 = ?", answer: 9, xp: 15, explanation: "Mötərizə birinci, sonra vurma/bölmə, ən sonda toplama/çıxma. Əvvəl mötərizə: 3 + 4 = 7, sonra vurma: 2 × 7 = 14, sonra çıxma: 14 − 5 = 9." },
            { id: "ry4-sahe-l1-b3", type: "numeric", prompt: "100 − 5 × 10 = ?", answer: 50, xp: 15, explanation: "Əvvəl vurma/bölmə, sonra toplama/çıxma. Əvvəl vurma: 5 × 10 = 50, sonra çıxma: 100 − 50 = 50." },
            { id: "ry4-sahe-l1-b4", type: "numeric", prompt: "Kvadratın sahəsi 49-dur. Tərəfi neçədir?", answer: 7, xp: 15, explanation: "Kvadratın sahəsi tərəfin özünə vurulmasıdır. Hansı ədədin kvadratı 49-dur? 7 × 7 = 49, deməli tərəf 7-dir." },
            { id: "ry4-sahe-l1-b5", type: "numeric", prompt: "36 ÷ (2 + 4) = ?", answer: 6, xp: 15, explanation: "Mötərizə birinci, sonra vurma/bölmə, ən sonda toplama/çıxma. Əvvəl mötərizə: 2 + 4 = 6, sonra bölmə: 36 : 6 = 6." },
          ],
        },
        {
          id: "ry4-sahe-l2",
          title: "Mətn məsələləri",
          intro: "Çoxaddımlı məsələlər.",
          sections: [
            { heading: "Məsələ", body: "Diqqətlə oxu, addımları düşün, hesabla." },
          ],
          tasks: [
            { id: "ry4-sahe-l2-t1", type: "numeric", prompt: "Hər qutuda 12 alma var. 5 qutuda neçə alma var?", answer: 60, xp: 10, explanation: "Hər qutudakı 12 alma 5 dəfə təkrarlanır: 5 × 12 = 60." },
            { id: "ry4-sahe-l2-t2", type: "numeric", prompt: "144 kitab 12 rəfə bərabər yerləşdi. Hər rəfdə neçə kitab var?", answer: 12, xp: 10, explanation: "144 kitabı 12 rəfə bərabər paylayırıq: 144 : 12 = 12." },
            { id: "ry4-sahe-l2-t3", type: "numeric", prompt: "Mağazada 1500 manat var idi, 650 manat xərcləndi. Neçə manat qaldı?", answer: 850, xp: 10, explanation: "«Xərcləndi» azalma deməkdir: 1500 − 650 = 850 manat qaldı." },
            { id: "ry4-sahe-l2-t4", type: "numeric", prompt: "Hər gün 15 səhifə oxuyuram. 6 gündə neçə səhifə oxuyuram?", answer: 90, xp: 10, explanation: "Hər günkü 15 səhifə 6 dəfə təkrarlanır: 6 × 15 = 90." },
            { id: "ry4-sahe-l2-t5", type: "numeric", prompt: "3 dost hərəsi 25 manat topladı. Cəmi neçə manat var?", answer: 75, xp: 10, explanation: "Hər dostun 25 manatı 3 dəfə təkrarlanır: 3 × 25 = 75 manat." },
            { id: "ry4-sahe-l2-t6", type: "numeric", prompt: "200 konfet 8 uşağa bərabər paylandı. Hər biri neçə alır? (200÷8)", answer: 25, xp: 10, explanation: "200 konfeti 8 uşağa bərabər paylayırıq: 200 : 8 = 25." },
            { id: "ry4-sahe-l2-t7", type: "numeric", prompt: "Bağda 340 ağac var idi, 160 da əkildi. Neçə ağac oldu?", answer: 500, xp: 10, explanation: "«Əkildi» artım deməkdir: 340 + 160 = 500 ağac." },
            { id: "ry4-sahe-l2-t8", type: "numeric", prompt: "Hər avtobusda 45 sərnişin var. 3 avtobusda neçə sərnişin var?", answer: 135, xp: 10, explanation: "Hər avtobusdakı 45 sərnişin 3 dəfə təkrarlanır: 3 × 45 = 135." },
            { id: "ry4-sahe-l2-t9", type: "numeric", prompt: "Bir qutuda 6 şüşə, hər şüşədə 2 litr su var. Cəmi neçə litr su var?", answer: 12, xp: 10, explanation: "Hər şüşədəki 2 litr 6 dəfə təkrarlanır: 6 × 2 = 12 litr." },
            { id: "ry4-sahe-l2-t10", type: "numeric", prompt: "500 manatlıq telefona 20% (100 manat) endirim edildi. Yeni qiymət?", answer: 400, xp: 10, explanation: "Endirim qiymətdən çıxılır: 500 − 100 = 400 manat." },
            { id: "ry4-sahe-l2-t11", type: "numeric", prompt: "Sinifdə 32 şagird var, yarısı qızdır. Neçə qız var?", answer: 16, xp: 10, explanation: "«Yarısı» 2-yə bölmək deməkdir: 32 : 2 = 16 qız." },
            { id: "ry4-sahe-l2-t12", type: "numeric", prompt: "Bir həftədə 7 gün. 12 həftədə neçə gün var? (7×12)", answer: 84, xp: 10, explanation: "Hər həftədəki 7 gün 12 dəfə təkrarlanır: 12 × 7 = 84 gün." },
            { id: "ry4-sahe-l2-t13", type: "numeric", prompt: "Hər paketdə 25 stiker var. 4 paketdə neçə stiker var?", answer: 100, xp: 10, explanation: "Hər paketdəki 25 stiker 4 dəfə təkrarlanır: 4 × 25 = 100." },
            { id: "ry4-sahe-l2-t14", type: "numeric", prompt: "1000 səhifəlik kitabın 350 səhifəsini oxudum. Neçə səhifə qaldı?", answer: 650, xp: 10, explanation: "Oxunanı ümumi saydan çıxırıq: 1000 − 350 = 650 səhifə qaldı." },
            { id: "ry4-sahe-l2-t15", type: "numeric", prompt: "6 qutu, hər qutuda 4 sıra, hər sırada 5 alma. Cəmi neçə alma? (6×4×5)", answer: 120, xp: 15, explanation: "Addım-addım: bir qutuda 4 × 5 = 20 alma var. 6 qutuda isə 6 × 20 = 120 alma." },
          ],
          bonusTasks: [
            { id: "ry4-sahe-l2-b1", type: "numeric", prompt: "Bağçanın uzunluğu 20 m, eni 10 m-dir. Sahəsi neçə kv.m-dir?", answer: 200, xp: 15, explanation: "Sahə uzunluqla enin hasilidir: 20 × 10 = 200 kv.m." },
            { id: "ry4-sahe-l2-b2", type: "numeric", prompt: "240 manat 4 nəfərə bərabər bölündü, sonra hər biri 10 manat xərclədi. Hər birində neçə manat qaldı?", answer: 50, xp: 15, explanation: "Əvvəl bölürük: 240 : 4 = 60 manat. Sonra xərci çıxırıq: 60 − 10 = 50 manat." },
            { id: "ry4-sahe-l2-b3", type: "numeric", prompt: "Hər gün 20 dəqiqə oxuyuram. 1 həftədə (7 gün) neçə dəqiqə oxuyuram?", answer: 140, xp: 15, explanation: "Hər günkü 20 dəqiqə 7 dəfə təkrarlanır: 7 × 20 = 140 dəqiqə." },
            { id: "ry4-sahe-l2-b4", type: "numeric", prompt: "3 qutuda hərəsi 24 yumurta var. 2 yumurta sındı. Neçə yumurta qaldı?", answer: 70, xp: 15, explanation: "Əvvəl hamısını sayırıq: 3 × 24 = 72. Sonra sınanları çıxırıq: 72 − 2 = 70 yumurta." },
            { id: "ry4-sahe-l2-b5", type: "numeric", prompt: "Kvadrat meydançanın tərəfi 15 m-dir. Perimetri neçə metrdir? (4×15)", answer: 60, xp: 15, explanation: "Perimetr tərəflərin cəmidir. Kvadratın 4 bərabər tərəfi var: 4 × 15 = 60 m." },
          ],
        },
        {
          id: "ry4-sahe-l3",
          title: "Əməllər sırası",
          intro: "Hansı əməl əvvəl gəlir?",
          sections: [
            { heading: "Qayda", body: "Əvvəl mötərizə, sonra vurma və bölmə (soldan sağa), ən sonda toplama və çıxma." },
            { heading: "Nümunə", body: "2 + 3 × 4 = 2 + 12 = 14 (14, 20 deyil!). Amma (2 + 3) × 4 = 5 × 4 = 20." },
          ],
          tasks: [
            { id: "ry4-sahe-l3-t1", type: "numeric", prompt: "2 + 3 × 4 = ?", answer: 14, xp: 10, explanation: "Əvvəl vurma/bölmə, sonra toplama/çıxma. Əvvəl vurma: 3 × 4 = 12, sonra toplama: 2 + 12 = 14." },
            { id: "ry4-sahe-l3-t2", type: "numeric", prompt: "(2 + 3) × 4 = ?", answer: 20, xp: 10, explanation: "Mötərizə birinci, sonra vurma/bölmə, ən sonda toplama/çıxma. Əvvəl mötərizə: 2 + 3 = 5, sonra vurma: 5 × 4 = 20." },
            { id: "ry4-sahe-l3-t3", type: "numeric", prompt: "10 − 2 × 3 = ?", answer: 4, xp: 10, explanation: "Əvvəl vurma/bölmə, sonra toplama/çıxma. Əvvəl vurma: 2 × 3 = 6, sonra çıxma: 10 − 6 = 4." },
            { id: "ry4-sahe-l3-t4", type: "numeric", prompt: "20 ÷ 4 + 3 = ?", answer: 8, xp: 10, explanation: "Əvvəl vurma/bölmə, sonra toplama/çıxma. Əvvəl bölmə: 20 : 4 = 5, sonra toplama: 5 + 3 = 8." },
            { id: "ry4-sahe-l3-t5", type: "numeric", prompt: "6 + 6 ÷ 2 = ?", answer: 9, xp: 10, explanation: "Əvvəl vurma/bölmə, sonra toplama/çıxma. Əvvəl bölmə: 6 : 2 = 3, sonra toplama: 6 + 3 = 9." },
            { id: "ry4-sahe-l3-t6", type: "numeric", prompt: "(10 − 4) ÷ 3 = ?", answer: 2, xp: 10, explanation: "Mötərizə birinci, sonra vurma/bölmə, ən sonda toplama/çıxma. Əvvəl mötərizə: 10 − 4 = 6, sonra bölmə: 6 : 3 = 2." },
            { id: "ry4-sahe-l3-t7", type: "multiple_choice", prompt: "Hansı əməl birinci yerinə yetirilir?", options: ["Mötərizə", "Toplama", "Çıxma", "Fərqi yoxdur"], correctIndex: 0, xp: 10, explanation: "Mötərizə hesablamanı qruplaşdırır, ona görə həmişə birinci yerinə yetirilir." },
            { id: "ry4-sahe-l3-t8", type: "numeric", prompt: "5 × 2 + 3 × 3 = ?", answer: 19, xp: 10, explanation: "Əvvəl vurma/bölmə, sonra toplama/çıxma. Əvvəl vurma: 5 × 2 = 10, sonra vurma: 3 × 3 = 9, sonra toplama: 10 + 9 = 19." },
            { id: "ry4-sahe-l3-t9", type: "numeric", prompt: "100 ÷ 10 ÷ 2 = ?", answer: 5, xp: 10, explanation: "Əvvəl vurma/bölmə, sonra toplama/çıxma. Əvvəl bölmə: 100 : 10 = 10, sonra bölmə: 10 : 2 = 5." },
            { id: "ry4-sahe-l3-t10", type: "numeric", prompt: "(8 + 2) × (5 − 3) = ?", answer: 20, xp: 10, explanation: "Mötərizə birinci, sonra vurma/bölmə, ən sonda toplama/çıxma. Əvvəl mötərizə: 8 + 2 = 10, sonra mötərizə: 5 − 3 = 2, sonra vurma: 10 × 2 = 20." },
          ],
          bonusTasks: [
            { id: "ry4-sahe-l3-b1", type: "numeric", prompt: "3 + 4 × 5 − 6 = ?", answer: 17, xp: 15, explanation: "Əvvəl vurma/bölmə, sonra toplama/çıxma. Əvvəl vurma: 4 × 5 = 20, sonra toplama: 3 + 20 = 23, sonra çıxma: 23 − 6 = 17." },
            { id: "ry4-sahe-l3-b2", type: "numeric", prompt: "(12 ÷ 4 + 2) × 3 = ?", answer: 15, xp: 15, explanation: "Mötərizə birinci, sonra vurma/bölmə, ən sonda toplama/çıxma. Əvvəl mötərizə: 12 : 4 = 3, sonra mötərizə: 3 + 2 = 5, sonra vurma: 5 × 3 = 15." },
            { id: "ry4-sahe-l3-b3", type: "multiple_choice", prompt: "2 + 3 × 4 ifadəsində niyə 20 alınmır?", options: ["Çünki vurma toplamadan əvvəl gəlir", "Çünki səhv yazılıb", "Çünki mötərizə var", "20 doğrudur"], correctIndex: 0, xp: 15, explanation: "20 almaq üçün əvvəl 2 + 3 = 5, sonra 5 × 4 edilməlidir. Amma mötərizə olmadığı üçün vurma birinci gəlir: 3 × 4 = 12, sonra 2 + 12 = 14." },
            { id: "ry4-sahe-l3-b4", type: "numeric", prompt: "50 − (10 + 5) × 2 = ?", answer: 20, xp: 15, explanation: "Mötərizə birinci, sonra vurma/bölmə, ən sonda toplama/çıxma. Əvvəl mötərizə: 10 + 5 = 15, sonra vurma: 15 × 2 = 30, sonra çıxma: 50 − 30 = 20." },
          ],
        },
        {
          id: "ry4-sahe-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry4-sahe-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
  ],
};
