// Riyaziyyat — 3-cü sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Ədədlər 1000-ə qədər  2) Toplama və çıxma  3) Vurma cədvəli
// 4) Bölmə  5) Kəsrlər  6) Həndəsə, ölçmə və məsələlər.
// 3-cü sinif üçün sadə (rəqəm cavablar). id prefiksi ry3-*.

import type { Subject } from "../types";

export const math3: Subject = {
  slug: "riyaziyyat-3",
  name: "Riyaziyyat",
  grade: 3,
  icon: "R",
  color: "sky",
  units: [
    // ═══════════════ 1. Ədədlər 1000-ə qədər ═══════════════
    {
      id: "ry3-min",
      title: "Ədədlər 1000-ə qədər",
      description: "Üçrəqəmli ədədləri oxumaq, yazmaq, mərtəbələrə ayırmaq və müqayisə etmək.",
      lessons: [
        {
          id: "ry3-min-l1",
          title: "Üçrəqəmli ədədlər",
          intro: "Yüzlük, onluq və təkliklər.",
          sections: [
            { heading: "Mərtəbələr", body: "Üçrəqəmli ədəd yüzlük, onluq və təklikdən ibarətdir. 345 = 3 yüzlük + 4 onluq + 5 təklik." },
            { heading: "Sıra", body: "Ən kiçik üçrəqəmli ədəd 100, ən böyüyü 999-dur. 999-dan sonra 1000 gəlir." },
          ],
          tasks: [
            { id: "ry3-min-l1-t1", type: "numeric", prompt: "345 ədədində neçə yüzlük var?", answer: 3, xp: 10, explanation: "345-də soldan birinci rəqəm — 3 — yüzlüklər mərtəbəsindədir. Deməli 3 yüzlük var.", skills: ["number.place_value"] },
            { id: "ry3-min-l1-t2", type: "numeric", prompt: "345 ədədində neçə onluq var?", answer: 4, xp: 10, explanation: "345-də ortadakı rəqəm — 4 — onluqlar mərtəbəsindədir. Deməli 4 onluq var.", skills: ["number.place_value"] },
            { id: "ry3-min-l1-t3", type: "numeric", prompt: "345 ədədində neçə təklik var?", answer: 5, xp: 10, explanation: "345-də sondakı rəqəm — 5 — təkliklər mərtəbəsindədir. Deməli 5 təklik var.", skills: ["number.place_value"] },
            { id: "ry3-min-l1-t4", type: "numeric", prompt: "2 yüzlük + 5 onluq + 3 təklik = ?", answer: 253, xp: 10, explanation: "2 yüzlük = 200, 5 onluq = 50, 3 təklik = 3. Cəmi: 200 + 50 + 3 = 253.", skills: ["number.place_value"] },
            { id: "ry3-min-l1-t5", type: "numeric", prompt: "5 yüzlük = ?", answer: 500, xp: 10, explanation: "Bir yüzlük 100-dür, ona görə 5 yüzlük = 5 × 100 = 500.", skills: ["number.place_value"] },
            { id: "ry3-min-l1-t6", type: "numeric", prompt: "Ən kiçik üçrəqəmli ədəd hansıdır?", answer: 100, xp: 10, explanation: "99 hələ ikirəqəmlidir. Ondan sonra gələn 100 üç rəqəmli olan ilk ədəddir.", skills: ["number.place_value"] },
            { id: "ry3-min-l1-t7", type: "numeric", prompt: "Ən böyük üçrəqəmli ədəd hansıdır?", answer: 999, xp: 10, explanation: "Hər üç mərtəbədə ən böyük rəqəm 9-dur → 999. Növbəti ədəd 1000 artıq dördrəqəmlidir.", skills: ["number.place_value"] },
            { id: "ry3-min-l1-t8", type: "numeric", prompt: "999-dan sonra hansı ədəd gəlir?", answer: 1000, xp: 10, explanation: "999-un bütün rəqəmləri 9-dur; 1 əlavə edəndə mərtəbələr aşır və 1000 alınır.", skills: ["number.count"] },
            { id: "ry3-min-l1-t9", type: "numeric", prompt: "300-dən əvvəl gələn ədəd hansıdır?", answer: 299, xp: 10, explanation: "«Əvvəl gələn» 1 az deməkdir: 300 − 1 = 299.", skills: ["number.count"] },
            { id: "ry3-min-l1-t10", type: "multiple_choice", prompt: "456 və 465 ədədlərindən böyüyü hansıdır?", options: ["465", "456", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "Yüzlüklər eynidir (hər ikisində 4), ona görə onluqlara baxırıq: 465-də 6, 456-da 5. 6 > 5 → 465 böyükdür.", skills: ["number.compare"] },
            { id: "ry3-min-l1-t11", type: "multiple_choice", prompt: "700 və 699 ədədlərindən böyüyü hansıdır?", options: ["700", "699", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "Yüzlüklərə baxırıq: 700-də 7, 699-da 6. 7 > 6 → 700 böyükdür. Rəqəmlərin sayı yox, mərtəbə həll edir.", skills: ["number.compare"] },
            { id: "ry3-min-l1-t12", type: "numeric", prompt: "'beş yüz altmış' ədədi rəqəmlə necə yazılır?", answer: 560, xp: 10, explanation: "«Beş yüz» = 500, «altmış» = 60. Təklik deyilmədiyi üçün sona 0 yazılır: 560.", skills: ["number.place_value"] },
            { id: "ry3-min-l1-t13", type: "numeric", prompt: "4 yüzlük + 0 onluq + 7 təklik = ?", answer: 407, xp: 10, explanation: "4 yüzlük = 400, 7 təklik = 7. Onluq olmadığı üçün ortaya 0 yazılır: 407.", skills: ["number.place_value"] },
            { id: "ry3-min-l1-t14", type: "numeric", prompt: "1 yüzlük neçə təklikdir?", answer: 100, xp: 10, explanation: "Bir yüzlük 10 onluqdur, hər onluq isə 10 təklik: 10 × 10 = 100 təklik.", skills: ["number.place_value"] },
            { id: "ry3-min-l1-t15", type: "numeric", prompt: "'doqquz yüz' ədədi rəqəmlə necə yazılır?", answer: 900, xp: 15, explanation: "«Doqquz yüz» = 9 yüzlük. Onluq və təklik deyilmədiyi üçün onların yerinə 0 yazılır: 900.", skills: ["number.place_value"] },
          ],
          bonusTasks: [
            { id: "ry3-min-l1-b1", type: "numeric", prompt: "6 yüzlük + 6 onluq + 6 təklik = ?", answer: 666, xp: 15, explanation: "6 yüzlük = 600, 6 onluq = 60, 6 təklik = 6. Cəmi: 600 + 60 + 6 = 666.", skills: ["number.place_value"] },
            { id: "ry3-min-l1-b2", type: "numeric", prompt: "1000 ədədində neçə yüzlük var?", answer: 10, xp: 15, explanation: "1000-in içində 100 on dəfə var: 10 × 100 = 1000. Deməli 10 yüzlük.", skills: ["number.place_value"] },
            { id: "ry3-min-l1-b3", type: "multiple_choice", prompt: "234, 243, 324 — ən böyüyü hansıdır?", options: ["324", "243", "234", "heç biri"], correctIndex: 0, xp: 15, explanation: "Yüzlüklərə baxırıq: 324-də 3, digər ikisində 2. 3 > 2 → 324 ən böyüyüdür.", skills: ["number.compare"] },
            { id: "ry3-min-l1-b4", type: "numeric", prompt: "'yeddi yüz doqquz' ədədi rəqəmlə necə yazılır?", answer: 709, xp: 15, explanation: "«Yeddi yüz» = 700, «doqquz» = 9 təklik. Onluq deyilmədiyi üçün ortaya 0 yazılır: 709.", skills: ["number.place_value"] },
            { id: "ry3-min-l1-b5", type: "numeric", prompt: "500-dən sonra gələn 3-cü ədəd hansıdır?", answer: 503, xp: 15, explanation: "500-dən sonra 501, 502, 503 gəlir — üçüncüsü 503-dür.", skills: ["number.place_value"] },
          ],
        },
        {
          id: "ry3-min-l2",
          title: "Mərtəbələr və müqayisə",
          intro: "Yüzlük, onluq, təklik — hər rəqəmin öz yeri var.",
          sections: [
            { heading: "Mərtəbələr", body: "472 ədədində 4 — yüzlük, 7 — onluq, 2 təklikdir. Yəni 472 = 400 + 70 + 2." },
            { heading: "Müqayisə", body: "Üçrəqəmli ədədləri müqayisə edərkən əvvəl YÜZLÜKLƏRƏ bax, sonra onluqlara, sonra təkliklərə." },
          ],
          tasks: [
            { id: "ry3-min-l2-t1", type: "numeric", prompt: "472 ədədində yüzlüklərin sayı neçədir?", answer: 4, xp: 10, explanation: "472-də soldan birinci rəqəm 4-dür, o da yüzlüklər mərtəbəsindədir.", skills: ["number.place_value"] },
            { id: "ry3-min-l2-t2", type: "numeric", prompt: "305 ədədində onluqların sayı neçədir?", answer: 0, xp: 10, explanation: "305-də ortadakı rəqəm 0-dır — onluq yoxdur, ona görə sayı 0-dır.", skills: ["number.place_value"] },
            { id: "ry3-min-l2-t3", type: "numeric", prompt: "286 ədədində təkliklərin sayı neçədir?", answer: 6, xp: 10, explanation: "286-da sondakı rəqəm 6-dır, o da təkliklər mərtəbəsindədir.", skills: ["number.place_value"] },
            { id: "ry3-min-l2-t4", type: "multiple_choice", prompt: "Hansı daha böyükdür: 439 yoxsa 493?", options: ["493", "439", "Bərabərdir", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "Yüzlüklər eynidir (hər ikisində 4). Onluqlara baxırıq: 493-də 9, 439-da 3. 9 > 3 → 493 böyükdür.", skills: ["number.compare"] },
            { id: "ry3-min-l2-t5", type: "multiple_choice", prompt: "Hansı daha kiçikdir: 700 yoxsa 698?", options: ["698", "700", "Bərabərdir", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "Yüzlüklərə baxırıq: 698-də 6, 700-də 7. 6 < 7 → 698 kiçikdir.", skills: ["number.compare"] },
            { id: "ry3-min-l2-t6", type: "numeric", prompt: "600 + 40 + 3 = ?", answer: 643, xp: 10, explanation: "Bu, mərtəbələrin açılışıdır: 600 + 40 = 640, üstünə 3 → 643.", skills: ["arith.add.no_carry"] },
            { id: "ry3-min-l2-t7", type: "numeric", prompt: "Üçrəqəmli ən böyük ədəd hansıdır?", answer: 999, xp: 10, explanation: "Üç mərtəbənin hər birinə ən böyük rəqəmi — 9 — yazırıq: 999.", skills: ["number.place_value"] },
            { id: "ry3-min-l2-t8", type: "numeric", prompt: "Üçrəqəmli ən kiçik ədəd hansıdır?", answer: 100, xp: 10, explanation: "Yüzlüklər mərtəbəsi ən azı 1 olmalıdır (0 olsa ədəd üçrəqəmli olmaz), qalanları 0 → 100.", skills: ["number.place_value"] },
            { id: "ry3-min-l2-t9", type: "multiple_choice", prompt: "Müqayisədə əvvəl hansı mərtəbəyə baxırıq?", options: ["Yüzlüklərə", "Təkliklərə", "Onluqlara", "Fərqi yoxdur"], correctIndex: 0, xp: 10, explanation: "Müqayisə ən böyük mərtəbədən başlayır — üçrəqəmli ədəddə bu, yüzlüklərdir. Yüzlüklər bərabər olsa, onluqlara keçirik.", skills: ["number.place_value","number.count","number.compare"] },
            { id: "ry3-min-l2-t10", type: "numeric", prompt: "Ən böyük mərtəbəsi 8, qalan rəqəmləri 0 olan üçrəqəmli ədəd hansıdır?", answer: 800, xp: 10, explanation: "Ən böyük mərtəbə yüzlüklərdir: ora 8, onluq və təkliyə 0 yazılır → 800.", skills: ["number.place_value"] },
          ],
          bonusTasks: [
            { id: "ry3-min-l2-b1", type: "numeric", prompt: "527 ədədini 500 + 20 + ? şəklində yazsaq, sual yerinə nə gəlir?", answer: 7, xp: 15, explanation: "527 = 500 + 20 + 7. Yüzlük və onluq artıq yazılıb, qalan təklik 7-dir.", skills: ["arith.inverse","problem.one_step"] },
            { id: "ry3-min-l2-b2", type: "numeric", prompt: "999-dan sonra hansı ədəd gəlir?", answer: 1000, xp: 15, explanation: "999-un bütün rəqəmləri 9-dur; 1 əlavə edəndə mərtəbələr aşır və 1000 alınır.", skills: ["number.count"] },
            { id: "ry3-min-l2-b3", type: "numeric", prompt: "350, 305, 335 — ən böyüyünü yaz.", answer: 350, xp: 15, explanation: "Yüzlüklər üçündə də 3-dür, ona görə onluqlara baxırıq: 5 > 3 > 0. Ən böyüyü 350.", skills: ["number.compare"] },
            { id: "ry3-min-l2-b4", type: "numeric", prompt: "1000 − 1 = ?", answer: 999, xp: 15, explanation: "1000-dən 1 çıxanda bir mərtəbə aşağı düşürük və ən böyük üçrəqəmli ədəd — 999 alınır.", skills: ["arith.sub.borrow"] },
          ],
        },
        {
          id: "ry3-min-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry3-min-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 2. Toplama və çıxma ═══════════════
    {
      id: "ry3-toplama",
      title: "1000 dairəsində toplama və çıxma",
      description: "Üçrəqəmli ədədləri toplamaq və çıxmaq.",
      lessons: [
        {
          id: "ry3-toplama-l1",
          title: "Toplama və çıxma",
          intro: "Mərtəbələrə görə toplayıb çıxırıq.",
          sections: [
            { heading: "Toplama", body: "200 + 300 = 500. 234 + 145 = 379 (təkliklər, onluqlar, yüzlüklər)." },
            { heading: "Çıxma", body: "500 − 200 = 300. 379 − 145 = 234." },
          ],
          tasks: [
            { id: "ry3-toplama-l1-t1", type: "numeric", prompt: "200 + 300 = ?", answer: 500, xp: 10, explanation: "200 + 300 = 500.", skills: ["arith.add.no_carry"] },
            { id: "ry3-toplama-l1-t2", type: "numeric", prompt: "400 + 500 = ?", answer: 900, xp: 10, explanation: "400 + 500 = 900.", skills: ["arith.add.no_carry"] },
            { id: "ry3-toplama-l1-t3", type: "numeric", prompt: "234 + 145 = ?", answer: 379, xp: 10, explanation: "145 ədədini mərtəbələrə ayırırıq: 100 + 40 + 5. Ardıcıl toplayırıq: 234 + 100 = 334, 334 + 40 = 374, 374 + 5 = 379.", skills: ["arith.add.no_carry"] },
            { id: "ry3-toplama-l1-t4", type: "numeric", prompt: "312 + 256 = ?", answer: 568, xp: 10, explanation: "256 ədədini mərtəbələrə ayırırıq: 200 + 50 + 6. Ardıcıl toplayırıq: 312 + 200 = 512, 512 + 50 = 562, 562 + 6 = 568.", skills: ["arith.add.no_carry"] },
            { id: "ry3-toplama-l1-t5", type: "numeric", prompt: "500 − 200 = ?", answer: 300, xp: 10, explanation: "500 − 200 = 300.", skills: ["arith.sub.no_borrow"] },
            { id: "ry3-toplama-l1-t6", type: "numeric", prompt: "900 − 400 = ?", answer: 500, xp: 10, explanation: "900 − 400 = 500.", skills: ["arith.sub.no_borrow"] },
            { id: "ry3-toplama-l1-t7", type: "numeric", prompt: "379 − 145 = ?", answer: 234, xp: 10, explanation: "145 ədədini mərtəbələrə ayırırıq: 100 + 40 + 5. Ardıcıl çıxırıq: 379 − 100 = 279, 279 − 40 = 239, 239 − 5 = 234.", skills: ["arith.sub.no_borrow"] },
            { id: "ry3-toplama-l1-t8", type: "numeric", prompt: "568 − 256 = ?", answer: 312, xp: 10, explanation: "256 ədədini mərtəbələrə ayırırıq: 200 + 50 + 6. Ardıcıl çıxırıq: 568 − 200 = 368, 368 − 50 = 318, 318 − 6 = 312.", skills: ["arith.sub.no_borrow"] },
            { id: "ry3-toplama-l1-t9", type: "numeric", prompt: "150 + 150 = ?", answer: 300, xp: 10, explanation: "150 ədədini mərtəbələrə ayırırıq: 100 + 50. Ardıcıl toplayırıq: 150 + 100 = 250, 250 + 50 = 300.", skills: ["arith.add.carry"] },
            { id: "ry3-toplama-l1-t10", type: "numeric", prompt: "600 + 250 = ?", answer: 850, xp: 10, explanation: "250 ədədini mərtəbələrə ayırırıq: 200 + 50. Ardıcıl toplayırıq: 600 + 200 = 800, 800 + 50 = 850.", skills: ["arith.add.no_carry"] },
            { id: "ry3-toplama-l1-t11", type: "numeric", prompt: "750 − 300 = ?", answer: 450, xp: 10, explanation: "750 − 300 = 450.", skills: ["arith.sub.no_borrow"] },
            { id: "ry3-toplama-l1-t12", type: "numeric", prompt: "125 + 125 = ?", answer: 250, xp: 10, explanation: "125 ədədini mərtəbələrə ayırırıq: 100 + 20 + 5. Ardıcıl toplayırıq: 125 + 100 = 225, 225 + 20 = 245, 245 + 5 = 250.", skills: ["arith.add.carry"] },
            { id: "ry3-toplama-l1-t13", type: "numeric", prompt: "1000 − 500 = ?", answer: 500, xp: 10, explanation: "1000 − 500 = 500.", skills: ["arith.sub.borrow"] },
            { id: "ry3-toplama-l1-t14", type: "numeric", prompt: "430 + 270 = ?", answer: 700, xp: 10, explanation: "270 ədədini mərtəbələrə ayırırıq: 200 + 70. Ardıcıl toplayırıq: 430 + 200 = 630, 630 + 70 = 700.", skills: ["arith.add.carry"] },
            { id: "ry3-toplama-l1-t15", type: "numeric", prompt: "820 − 420 = ?", answer: 400, xp: 15, explanation: "420 ədədini mərtəbələrə ayırırıq: 400 + 20. Ardıcıl çıxırıq: 820 − 400 = 420, 420 − 20 = 400.", skills: ["arith.sub.no_borrow"] },
          ],
          bonusTasks: [
            { id: "ry3-toplama-l1-b1", type: "numeric", prompt: "345 + 278 = ?", answer: 623, xp: 15, explanation: "278 ədədini mərtəbələrə ayırırıq: 200 + 70 + 8. Ardıcıl toplayırıq: 345 + 200 = 545, 545 + 70 = 615, 615 + 8 = 623.", skills: ["arith.add.carry"] },
            { id: "ry3-toplama-l1-b2", type: "numeric", prompt: "700 − 265 = ?", answer: 435, xp: 15, explanation: "265 ədədini mərtəbələrə ayırırıq: 200 + 60 + 5. Ardıcıl çıxırıq: 700 − 200 = 500, 500 − 60 = 440, 440 − 5 = 435.", skills: ["arith.sub.borrow"] },
            { id: "ry3-toplama-l1-b3", type: "numeric", prompt: "456 + 544 = ?", answer: 1000, xp: 15, explanation: "544 ədədini mərtəbələrə ayırırıq: 500 + 40 + 4. Ardıcıl toplayırıq: 456 + 500 = 956, 956 + 40 = 996, 996 + 4 = 1000.", skills: ["arith.add.carry"] },
            { id: "ry3-toplama-l1-b4", type: "numeric", prompt: "1000 − 375 = ?", answer: 625, xp: 15, explanation: "375 ədədini mərtəbələrə ayırırıq: 300 + 70 + 5. Ardıcıl çıxırıq: 1000 − 300 = 700, 700 − 70 = 630, 630 − 5 = 625.", skills: ["arith.sub.borrow"] },
            { id: "ry3-toplama-l1-b5", type: "numeric", prompt: "289 + 311 = ?", answer: 600, xp: 15, explanation: "311 ədədini mərtəbələrə ayırırıq: 300 + 10 + 1. Ardıcıl toplayırıq: 289 + 300 = 589, 589 + 10 = 599, 599 + 1 = 600.", skills: ["arith.add.carry"] },
          ],
        },
        {
          id: "ry3-toplama-l2",
          title: "Üçrəqəmli toplama və çıxma",
          intro: "Sütun üsulu ilə addım-addım.",
          sections: [
            { heading: "Sütun üsulu", body: "Ədədləri mərtəbələrinə görə alt-alta yaz: təkliklər təkliklərin altında. Sağdan sola topla." },
            { heading: "Keçid", body: "Bir mərtəbənin cəmi 10-u keçirsə, bir vahid növbəti mərtəbəyə keçir." },
          ],
          tasks: [
            { id: "ry3-toplama-l2-t1", type: "numeric", prompt: "234 + 125 = ?", answer: 359, xp: 10, explanation: "125 ədədini mərtəbələrə ayırırıq: 100 + 20 + 5. Ardıcıl toplayırıq: 234 + 100 = 334, 334 + 20 = 354, 354 + 5 = 359.", skills: ["arith.add.no_carry"] },
            { id: "ry3-toplama-l2-t2", type: "numeric", prompt: "456 + 237 = ?", answer: 693, xp: 10, explanation: "237 ədədini mərtəbələrə ayırırıq: 200 + 30 + 7. Ardıcıl toplayırıq: 456 + 200 = 656, 656 + 30 = 686, 686 + 7 = 693.", skills: ["arith.add.carry"] },
            { id: "ry3-toplama-l2-t3", type: "numeric", prompt: "508 + 396 = ?", answer: 904, xp: 10, explanation: "396 ədədini mərtəbələrə ayırırıq: 300 + 90 + 6. Ardıcıl toplayırıq: 508 + 300 = 808, 808 + 90 = 898, 898 + 6 = 904.", skills: ["arith.add.carry"] },
            { id: "ry3-toplama-l2-t4", type: "numeric", prompt: "742 − 318 = ?", answer: 424, xp: 10, explanation: "318 ədədini mərtəbələrə ayırırıq: 300 + 10 + 8. Ardıcıl çıxırıq: 742 − 300 = 442, 442 − 10 = 432, 432 − 8 = 424.", skills: ["arith.sub.borrow"] },
            { id: "ry3-toplama-l2-t5", type: "numeric", prompt: "600 − 245 = ?", answer: 355, xp: 10, explanation: "245 ədədini mərtəbələrə ayırırıq: 200 + 40 + 5. Ardıcıl çıxırıq: 600 − 200 = 400, 400 − 40 = 360, 360 − 5 = 355.", skills: ["arith.sub.borrow"] },
            { id: "ry3-toplama-l2-t6", type: "numeric", prompt: "135 + 264 = ?", answer: 399, xp: 10, explanation: "264 ədədini mərtəbələrə ayırırıq: 200 + 60 + 4. Ardıcıl toplayırıq: 135 + 200 = 335, 335 + 60 = 395, 395 + 4 = 399.", skills: ["arith.add.no_carry"] },
            { id: "ry3-toplama-l2-t7", type: "numeric", prompt: "900 − 450 = ?", answer: 450, xp: 10, explanation: "450 ədədini mərtəbələrə ayırırıq: 400 + 50. Ardıcıl çıxırıq: 900 − 400 = 500, 500 − 50 = 450.", skills: ["arith.sub.borrow"] },
            { id: "ry3-toplama-l2-t8", type: "numeric", prompt: "318 + 482 = ?", answer: 800, xp: 10, explanation: "482 ədədini mərtəbələrə ayırırıq: 400 + 80 + 2. Ardıcıl toplayırıq: 318 + 400 = 718, 718 + 80 = 798, 798 + 2 = 800.", skills: ["arith.add.carry"] },
            { id: "ry3-toplama-l2-t9", type: "multiple_choice", prompt: "Sütun üsulunda hansı tərəfdən başlayırıq?", options: ["Sağdan (təkliklərdən)", "Soldan", "Ortadan", "Fərqi yoxdur"], correctIndex: 0, xp: 10, explanation: "Təkliklərdən başlayırıq, çünki keçən onluq soldakı mərtəbəyə əlavə olunmalıdır. Soldan başlasaq, bu keçidi əvvəlcədən bilməzdik.", skills: ["geom.shapes"] },
            { id: "ry3-toplama-l2-t10", type: "numeric", prompt: "871 − 259 = ?", answer: 612, xp: 10, explanation: "259 ədədini mərtəbələrə ayırırıq: 200 + 50 + 9. Ardıcıl çıxırıq: 871 − 200 = 671, 671 − 50 = 621, 621 − 9 = 612.", skills: ["arith.sub.borrow"] },
          ],
          bonusTasks: [
            { id: "ry3-toplama-l2-b1", type: "numeric", prompt: "Mağazada 345 kitab var idi, 178-i satıldı. Neçə kitab qaldı?", answer: 167, xp: 15, explanation: "«Satıldı» azalma deməkdir: 345 − 178 = 167 kitab qaldı.", skills: ["problem.one_step","arith.sub.borrow"] },
            { id: "ry3-toplama-l2-b2", type: "numeric", prompt: "256 + 174 + 120 = ?", answer: 550, xp: 15, explanation: "Soldan sağa toplayırıq: əvvəl 256 + 174 = 430, sonra 430 + 120 = 550.", skills: ["arith.add.no_carry"] },
            { id: "ry3-toplama-l2-b3", type: "numeric", prompt: "? + 250 = 700 — buraya hansı ədəd gəlir?", answer: 450, xp: 15, explanation: "Naməlum toplananı tapmaq üçün cəmdən məlum toplananı çıxırıq: 700 − 250 = 450.", skills: ["arith.inverse"] },
            { id: "ry3-toplama-l2-b4", type: "numeric", prompt: "1000 − 375 = ?", answer: 625, xp: 15, explanation: "375 ədədini mərtəbələrə ayırırıq: 300 + 70 + 5. Ardıcıl çıxırıq: 1000 − 300 = 700, 700 − 70 = 630, 630 − 5 = 625.", skills: ["arith.sub.borrow"] },
          ],
        },
        {
          id: "ry3-toplama-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry3-toplama-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 3. Vurma cədvəli ═══════════════
    {
      id: "ry3-vurma",
      title: "Vurma cədvəli (1-9)",
      description: "Vurma cədvəlini tam öyrənmək (2-dən 9-a qədər).",
      lessons: [
        {
          id: "ry3-vurma-l1",
          title: "Vurma cədvəli",
          intro: "Bütün vurma cədvəlini məşq edək.",
          sections: [
            { heading: "6, 7, 8, 9 cədvəli", body: "6 × 7 = 42, 7 × 8 = 56, 8 × 9 = 72, 9 × 9 = 81. Cədvəli yadda saxlamaq vacibdir." },
          ],
          tasks: [
            { id: "ry3-vurma-l1-t1", type: "numeric", prompt: "6 × 6 = ?", answer: 36, xp: 10, explanation: "6 × 6 = 6 × 5 + 6 × 1 = 30 + 6 = 36.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l1-t2", type: "numeric", prompt: "6 × 7 = ?", answer: 42, xp: 10, explanation: "6 × 7 = 7 × 5 + 7 × 1 = 35 + 7 = 42.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l1-t3", type: "numeric", prompt: "7 × 7 = ?", answer: 49, xp: 10, explanation: "7 × 7 = 7 × 5 + 7 × 2 = 35 + 14 = 49.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l1-t4", type: "numeric", prompt: "7 × 8 = ?", answer: 56, xp: 10, explanation: "7 × 8 = 8 × 5 + 8 × 2 = 40 + 16 = 56.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l1-t5", type: "numeric", prompt: "8 × 8 = ?", answer: 64, xp: 10, explanation: "8 × 8 = 8 × 5 + 8 × 3 = 40 + 24 = 64.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l1-t6", type: "numeric", prompt: "8 × 9 = ?", answer: 72, xp: 10, explanation: "8 × 9 = 9 × 5 + 9 × 3 = 45 + 27 = 72.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l1-t7", type: "numeric", prompt: "9 × 9 = ?", answer: 81, xp: 10, explanation: "9 × 9 = 9 × 5 + 9 × 4 = 45 + 36 = 81.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l1-t8", type: "numeric", prompt: "6 × 8 = ?", answer: 48, xp: 10, explanation: "6 × 8 = 8 × 5 + 8 × 1 = 40 + 8 = 48.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l1-t9", type: "numeric", prompt: "7 × 9 = ?", answer: 63, xp: 10, explanation: "7 × 9 = 9 × 5 + 9 × 2 = 45 + 18 = 63.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l1-t10", type: "numeric", prompt: "9 × 6 = ?", answer: 54, xp: 10, explanation: "9 × 6 = 9 × 5 + 9 × 1 = 45 + 9 = 54.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l1-t11", type: "numeric", prompt: "8 × 7 = ?", answer: 56, xp: 10, explanation: "8 × 7 = 8 × 5 + 8 × 2 = 40 + 16 = 56.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l1-t12", type: "numeric", prompt: "5 × 9 = ?", answer: 45, xp: 10, explanation: "5 × 9 — 9-u 5 dəfə toplamaq deməkdir: 9 + 9 + 9 + 9 + 9 = 45.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l1-t13", type: "numeric", prompt: "4 × 8 = ?", answer: 32, xp: 10, explanation: "4 × 8 — 8-i 4 dəfə toplamaq deməkdir: 8 + 8 + 8 + 8 = 32.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l1-t14", type: "numeric", prompt: "9 × 3 = ?", answer: 27, xp: 10, explanation: "9 × 3 — 9-u 3 dəfə toplamaq deməkdir: 9 + 9 + 9 = 27.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l1-t15", type: "numeric", prompt: "6 × 9 = ?", answer: 54, xp: 15, explanation: "6 × 9 = 9 × 5 + 9 × 1 = 45 + 9 = 54.", skills: ["arith.mul.tables"] },
          ],
          bonusTasks: [
            { id: "ry3-vurma-l1-b1", type: "numeric", prompt: "10 × 7 = ?", answer: 70, xp: 15, explanation: "10 × 7 = 70.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l1-b2", type: "numeric", prompt: "Hər qutuda 8 alma var. 7 qutuda neçə alma var?", answer: 56, xp: 15, explanation: "Hər qutudakı 8 alma 7 dəfə təkrarlanır: 7 × 8 = 56.", skills: ["problem.one_step","arith.mul.tables"] },
            { id: "ry3-vurma-l1-b3", type: "numeric", prompt: "9 × 8 = ?", answer: 72, xp: 15, explanation: "9 × 8 = 9 × 5 + 9 × 3 = 45 + 27 = 72.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l1-b4", type: "numeric", prompt: "12 × 3 = ?", answer: 36, xp: 15, explanation: "12 ədədini mərtəbələrə ayırırıq: 10 + 2. Hər hissəni vururuq: 10 × 3 = 30, 2 × 3 = 6. Cəmi: 30 + 6 = 36.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l1-b5", type: "numeric", prompt: "7 × 6 = ?", answer: 42, xp: 15, explanation: "7 × 6 = 7 × 5 + 7 × 1 = 35 + 7 = 42.", skills: ["arith.mul.tables"] },
          ],
        },
        {
          id: "ry3-vurma-l2",
          title: "6, 7, 8, 9 cədvəlləri",
          intro: "Vurma cədvəlini sona çatdıraq.",
          sections: [
            { heading: "Böyük cədvəllər", body: "6 × 7 = 42, 7 × 8 = 56, 8 × 9 = 72, 9 × 9 = 81. Bunları əzbərləmək hesabı çox sürətləndirir." },
            { heading: "9-un sirri", body: "9-a vurulan nəticənin rəqəmləri cəmi həmişə 9 verir: 9 × 4 = 36 → 3 + 6 = 9." },
          ],
          tasks: [
            { id: "ry3-vurma-l2-t1", type: "numeric", prompt: "6 × 7 = ?", answer: 42, xp: 10, explanation: "6 × 7 = 7 × 5 + 7 × 1 = 35 + 7 = 42.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l2-t2", type: "numeric", prompt: "7 × 8 = ?", answer: 56, xp: 10, explanation: "7 × 8 = 8 × 5 + 8 × 2 = 40 + 16 = 56.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l2-t3", type: "numeric", prompt: "8 × 9 = ?", answer: 72, xp: 10, explanation: "8 × 9 = 9 × 5 + 9 × 3 = 45 + 27 = 72.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l2-t4", type: "numeric", prompt: "9 × 9 = ?", answer: 81, xp: 10, explanation: "9 × 9 = 9 × 5 + 9 × 4 = 45 + 36 = 81.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l2-t5", type: "numeric", prompt: "6 × 8 = ?", answer: 48, xp: 10, explanation: "6 × 8 = 8 × 5 + 8 × 1 = 40 + 8 = 48.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l2-t6", type: "numeric", prompt: "7 × 7 = ?", answer: 49, xp: 10, explanation: "7 × 7 = 7 × 5 + 7 × 2 = 35 + 14 = 49.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l2-t7", type: "numeric", prompt: "9 × 6 = ?", answer: 54, xp: 10, explanation: "9 × 6 = 9 × 5 + 9 × 1 = 45 + 9 = 54.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l2-t8", type: "numeric", prompt: "8 × 8 = ?", answer: 64, xp: 10, explanation: "8 × 8 = 8 × 5 + 8 × 3 = 40 + 24 = 64.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l2-t9", type: "numeric", prompt: "7 × 9 = ?", answer: 63, xp: 10, explanation: "7 × 9 = 9 × 5 + 9 × 2 = 45 + 18 = 63.", skills: ["arith.mul.tables"] },
            { id: "ry3-vurma-l2-t10", type: "numeric", prompt: "6 × 6 = ?", answer: 36, xp: 10, explanation: "6 × 6 = 6 × 5 + 6 × 1 = 30 + 6 = 36.", skills: ["arith.mul.tables"] },
          ],
          bonusTasks: [
            { id: "ry3-vurma-l2-b1", type: "numeric", prompt: "Hər qutuda 8 karandaş var. 7 qutuda neçə karandaş var?", answer: 56, xp: 15, explanation: "Hər qutudakı 8 karandaş 7 dəfə təkrarlanır: 7 × 8 = 56.", skills: ["problem.one_step","arith.mul.tables"] },
            { id: "ry3-vurma-l2-b2", type: "numeric", prompt: "9 × 4 + 6 = ?", answer: 42, xp: 15, explanation: "Əvvəl vurma: 9 × 4 = 36. Sonra toplama: 36 + 6 = 42.", skills: ["arith.order_of_ops"] },
            { id: "ry3-vurma-l2-b3", type: "numeric", prompt: "6 × ? = 54 — buraya hansı ədəd gəlir?", answer: 9, xp: 15, explanation: "Naməlum vuruğu tapmaq üçün hasili məlum vuruğa bölürük: 54 : 6 = 9.", skills: ["arith.inverse"] },
            { id: "ry3-vurma-l2-b4", type: "numeric", prompt: "7 × 6 × 2 = ?", answer: 84, xp: 15, explanation: "Soldan sağa vururuq: əvvəl 7 × 6 = 42, sonra 42 × 2 = 84.", skills: ["arith.mul.tables"] },
          ],
        },
        {
          id: "ry3-vurma-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry3-vurma-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 4. Bölmə ═══════════════
    {
      id: "ry3-bolme",
      title: "Bölmə",
      description: "Vurma cədvəlinə əsaslanan bölmə və qalıqlı bölmə.",
      lessons: [
        {
          id: "ry3-bolme-l1",
          title: "Bölmə",
          intro: "Bölmə vurmanın əksidir: 42 ÷ 6 = 7, çünki 6 × 7 = 42.",
          sections: [
            { heading: "Bölmə", body: "56 ÷ 8 = 7 (çünki 8 × 7 = 56). Vurma cədvəlini bilsək, bölməni asan edərik." },
          ],
          tasks: [
            { id: "ry3-bolme-l1-t1", type: "numeric", prompt: "42 ÷ 6 = ?", answer: 7, xp: 10, explanation: "42-ni 6 bərabər hissəyə bölürük. Hər hissəyə 7 düşür, çünki 6 × 7 = 42.", skills: ["arith.div.tables"] },
            { id: "ry3-bolme-l1-t2", type: "numeric", prompt: "56 ÷ 8 = ?", answer: 7, xp: 10, explanation: "56-nı 8 bərabər hissəyə bölürük. Hər hissəyə 7 düşür, çünki 8 × 7 = 56.", skills: ["arith.div.tables"] },
            { id: "ry3-bolme-l1-t3", type: "numeric", prompt: "72 ÷ 9 = ?", answer: 8, xp: 10, explanation: "72-ni 9 bərabər hissəyə bölürük. Hər hissəyə 8 düşür, çünki 9 × 8 = 72.", skills: ["arith.div.tables"] },
            { id: "ry3-bolme-l1-t4", type: "numeric", prompt: "63 ÷ 7 = ?", answer: 9, xp: 10, explanation: "63-ü 7 bərabər hissəyə bölürük. Hər hissəyə 9 düşür, çünki 7 × 9 = 63.", skills: ["arith.div.tables"] },
            { id: "ry3-bolme-l1-t5", type: "numeric", prompt: "81 ÷ 9 = ?", answer: 9, xp: 10, explanation: "81-i 9 bərabər hissəyə bölürük. Hər hissəyə 9 düşür, çünki 9 × 9 = 81.", skills: ["arith.div.tables"] },
            { id: "ry3-bolme-l1-t6", type: "numeric", prompt: "48 ÷ 6 = ?", answer: 8, xp: 10, explanation: "48-i 6 bərabər hissəyə bölürük. Hər hissəyə 8 düşür, çünki 6 × 8 = 48.", skills: ["arith.div.tables"] },
            { id: "ry3-bolme-l1-t7", type: "numeric", prompt: "64 ÷ 8 = ?", answer: 8, xp: 10, explanation: "64-ü 8 bərabər hissəyə bölürük. Hər hissəyə 8 düşür, çünki 8 × 8 = 64.", skills: ["arith.div.tables"] },
            { id: "ry3-bolme-l1-t8", type: "numeric", prompt: "45 ÷ 5 = ?", answer: 9, xp: 10, explanation: "45-i 5 bərabər hissəyə bölürük. Hər hissəyə 9 düşür, çünki 5 × 9 = 45.", skills: ["arith.div.tables"] },
            { id: "ry3-bolme-l1-t9", type: "numeric", prompt: "36 ÷ 6 = ?", answer: 6, xp: 10, explanation: "36-nı 6 bərabər hissəyə bölürük. Hər hissəyə 6 düşür, çünki 6 × 6 = 36.", skills: ["arith.div.tables"] },
            { id: "ry3-bolme-l1-t10", type: "numeric", prompt: "54 ÷ 9 = ?", answer: 6, xp: 10, explanation: "54-ü 9 bərabər hissəyə bölürük. Hər hissəyə 6 düşür, çünki 9 × 6 = 54.", skills: ["arith.div.tables"] },
            { id: "ry3-bolme-l1-t11", type: "numeric", prompt: "49 ÷ 7 = ?", answer: 7, xp: 10, explanation: "49-u 7 bərabər hissəyə bölürük. Hər hissəyə 7 düşür, çünki 7 × 7 = 49.", skills: ["arith.div.tables"] },
            { id: "ry3-bolme-l1-t12", type: "numeric", prompt: "32 ÷ 4 = ?", answer: 8, xp: 10, explanation: "32-ni 4 bərabər hissəyə bölürük. Hər hissəyə 8 düşür, çünki 4 × 8 = 32.", skills: ["arith.div.tables"] },
            { id: "ry3-bolme-l1-t13", type: "numeric", prompt: "27 ÷ 3 = ?", answer: 9, xp: 10, explanation: "27-ni 3 bərabər hissəyə bölürük. Hər hissəyə 9 düşür, çünki 3 × 9 = 27.", skills: ["arith.div.tables"] },
            { id: "ry3-bolme-l1-t14", type: "numeric", prompt: "56 ÷ 7 = ?", answer: 8, xp: 10, explanation: "56-nı 7 bərabər hissəyə bölürük. Hər hissəyə 8 düşür, çünki 7 × 8 = 56.", skills: ["arith.div.tables"] },
            { id: "ry3-bolme-l1-t15", type: "numeric", prompt: "63 ÷ 9 = ?", answer: 7, xp: 15, explanation: "63-ü 9 bərabər hissəyə bölürük. Hər hissəyə 7 düşür, çünki 9 × 7 = 63.", skills: ["arith.div.tables"] },
          ],
          bonusTasks: [
            { id: "ry3-bolme-l1-b1", type: "numeric", prompt: "100 ÷ 10 = ?", answer: 10, xp: 15, explanation: "100-ü 10 bərabər hissəyə bölürük. Hər hissəyə 10 düşür, çünki 10 × 10 = 100.", skills: ["arith.div.multi_digit"] },
            { id: "ry3-bolme-l1-b2", type: "numeric", prompt: "72 alma 8 səbətə bərabər paylandı. Hər səbətdə neçə alma var?", answer: 9, xp: 15, explanation: "72 almanı 8 səbətə bərabər paylayırıq: 72 : 8 = 9, çünki 8 × 9 = 72.", skills: ["problem.one_step","arith.div.tables"] },
            { id: "ry3-bolme-l1-b3", type: "numeric", prompt: "13 ÷ 4 bölməsində qalıq neçədir? (13 = 4×3 + 1)", answer: 1, xp: 15, explanation: "4-ün 13-ə sığan ən böyük misli 12-dir (4 × 3). Qalan hissə isə qalıqdır: 13 − 12 = 1.", skills: ["arith.div.remainder"] },
            { id: "ry3-bolme-l1-b4", type: "numeric", prompt: "90 ÷ 9 = ?", answer: 10, xp: 15, explanation: "90-ı 9 bərabər hissəyə bölürük. Hər hissəyə 10 düşür, çünki 9 × 10 = 90.", skills: ["arith.div.tables"] },
            { id: "ry3-bolme-l1-b5", type: "numeric", prompt: "48 ÷ 8 = ?", answer: 6, xp: 15, explanation: "48-i 8 bərabər hissəyə bölürük. Hər hissəyə 6 düşür, çünki 8 × 6 = 48.", skills: ["arith.div.tables"] },
          ],
        },
        {
          id: "ry3-bolme-l2",
          title: "Qalıqlı bölmə",
          intro: "Həmişə bərabər bölünmür — qalıq olur.",
          sections: [
            { heading: "Qalıq nədir?", body: "17 ÷ 5 = 3 (qalıq 2), çünki 5 × 3 = 15, 17 − 15 = 2. Qalıq həmişə bölöndən KİÇİK olur." },
            { heading: "Yoxlama", body: "Bölünən = bölən × qismət + qalıq. Yəni 5 × 3 + 2 = 17. ✓" },
          ],
          tasks: [
            { id: "ry3-bolme-l2-t1", type: "numeric", prompt: "17 ÷ 5 = ? (tam hissə)", answer: 3, xp: 10, explanation: "5-in 17-yə sığan ən böyük misli 15-dir (5 × 3), deməli tam hissə 3-dür.", skills: ["arith.div.tables"] },
            { id: "ry3-bolme-l2-t2", type: "numeric", prompt: "17 ÷ 5 əməlində qalıq neçədir?", answer: 2, xp: 10, explanation: "5 × 3 = 15, 17-dən artıq qalan hissə qalıqdır: 17 − 15 = 2.", skills: ["arith.div.remainder"] },
            { id: "ry3-bolme-l2-t3", type: "numeric", prompt: "23 ÷ 4 = ? (tam hissə)", answer: 5, xp: 10, explanation: "4-ün 23-ə sığan ən böyük misli 20-dir (4 × 5), deməli tam hissə 5-dir.", skills: ["arith.div.tables"] },
            { id: "ry3-bolme-l2-t4", type: "numeric", prompt: "23 ÷ 4 əməlində qalıq neçədir?", answer: 3, xp: 10, explanation: "4 × 5 = 20, qalan hissə qalıqdır: 23 − 20 = 3.", skills: ["arith.div.remainder"] },
            { id: "ry3-bolme-l2-t5", type: "numeric", prompt: "30 ÷ 7 = ? (tam hissə)", answer: 4, xp: 10, explanation: "7-nin 30-a sığan ən böyük misli 28-dir (7 × 4), deməli tam hissə 4-dür.", skills: ["arith.div.tables"] },
            { id: "ry3-bolme-l2-t6", type: "numeric", prompt: "30 ÷ 7 əməlində qalıq neçədir?", answer: 2, xp: 10, explanation: "7 × 4 = 28, qalan hissə qalıqdır: 30 − 28 = 2.", skills: ["arith.div.remainder"] },
            { id: "ry3-bolme-l2-t7", type: "multiple_choice", prompt: "Qalıq necə olmalıdır?", options: ["Böləndən kiçik", "Böləndən böyük", "Bölənə bərabər", "Fərqi yoxdur"], correctIndex: 0, xp: 10, explanation: "Qalıq böləndən böyük olsaydı, ondan bir dəfə də ayırmaq olardı. Ona görə qalıq həmişə böləndən kiçikdir.", skills: ["arith.div.remainder"] },
            { id: "ry3-bolme-l2-t8", type: "numeric", prompt: "45 ÷ 6 əməlində qalıq neçədir?", answer: 3, xp: 10, explanation: "6-nın 45-ə sığan ən böyük misli 42-dir (6 × 7). Qalıq: 45 − 42 = 3.", skills: ["arith.div.remainder"] },
            { id: "ry3-bolme-l2-t9", type: "numeric", prompt: "40 ÷ 8 əməlində qalıq neçədir?", answer: 0, xp: 10, explanation: "8 × 5 = 40, yəni 40 tam bölünür. Artıq heç nə qalmır: qalıq 0-dır.", skills: ["arith.div.remainder"] },
            { id: "ry3-bolme-l2-t10", type: "numeric", prompt: "19 ÷ 3 = ? (tam hissə)", answer: 6, xp: 10, explanation: "3-ün 19-a sığan ən böyük misli 18-dir (3 × 6), deməli tam hissə 6-dır.", skills: ["arith.div.tables"] },
          ],
          bonusTasks: [
            { id: "ry3-bolme-l2-b1", type: "numeric", prompt: "25 şirniyyatı 4 uşağa bərabər payladıq. Neçə şirniyyat qaldı?", answer: 1, xp: 15, explanation: "4-ün 25-ə sığan ən böyük misli 24-dür (4 × 6), yəni hər uşağa 6 şirniyyat düşür. Qalıq: 25 − 24 = 1.", skills: ["problem.one_step","arith.sub.no_borrow"] },
            { id: "ry3-bolme-l2-b2", type: "numeric", prompt: "50 ÷ 9 əməlində qalıq neçədir?", answer: 5, xp: 15, explanation: "9-un 50-yə sığan ən böyük misli 45-dir (9 × 5). Qalıq: 50 − 45 = 5.", skills: ["arith.div.remainder"] },
            { id: "ry3-bolme-l2-b3", type: "multiple_choice", prompt: "Qalıq 0 olanda nə deyirik?", options: ["Tam bölünür", "Bölünmür", "Səhvdir", "Qalıq var"], correctIndex: 0, xp: 15, explanation: "Qalıq 0-dırsa, heç nə artıq qalmayıb — deməli ədəd tam bölünür.", skills: ["arith.div.remainder"] },
            { id: "ry3-bolme-l2-b4", type: "numeric", prompt: "6 × 7 + 4 = ? (bölünəni tap)", answer: 46, xp: 15, explanation: "Bölünən qismətlə bölənin hasilinə qalığı əlavə etməklə tapılır: 6 × 7 + 4 = 42 + 4 = 46.", skills: ["arith.order_of_ops"] },
          ],
        },
        {
          id: "ry3-bolme-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry3-bolme-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 5. Kəsrlər ═══════════════
    {
      id: "ry3-kesr",
      title: "Kəsrlər",
      description: "Bütövün hissələri: 1/2, 1/3, 1/4 kəsrləri.",
      lessons: [
        {
          id: "ry3-kesr-l1",
          title: "Sadə kəsrlər",
          intro: "Bütövü bərabər hissələrə bölmək.",
          sections: [
            { heading: "Kəsr nədir?", body: "Bütövü bərabər hissələrə bölürük. 1/2 — yarı, 1/3 — üçdə bir, 1/4 — dörddə bir. Alt ədəd (məxrəc) neçə hissəyə böldüyümüzü, üst ədəd (sürət) neçə hissə götürdüyümüzü göstərir." },
          ],
          tasks: [
            { id: "ry3-kesr-l1-t1", type: "multiple_choice", prompt: "1/2 kəsri nə deməkdir?", options: ["yarı", "üçdə bir", "dörddə bir", "bütöv"], correctIndex: 0, xp: 10, explanation: "1/2-də bütöv 2 bərabər hissəyə bölünür və bir hissə götürülür — bu, yarı deməkdir.", skills: ["fraction.concept"] },
            { id: "ry3-kesr-l1-t2", type: "multiple_choice", prompt: "1/4 kəsri nə deməkdir?", options: ["dörddə bir", "yarı", "üçdə bir", "bütöv"], correctIndex: 0, xp: 10, explanation: "1/4-də bütöv 4 bərabər hissəyə bölünür və bir hissə götürülür — bu, dörddə bir deməkdir.", skills: ["fraction.concept"] },
            { id: "ry3-kesr-l1-t3", type: "numeric", prompt: "10 almanın yarısı (1/2) neçə almadır?", answer: 5, xp: 10, explanation: "Yarısını tapmaq üçün 2-yə bölürük: 10 : 2 = 5 alma.", skills: ["fraction.of_quantity"] },
            { id: "ry3-kesr-l1-t4", type: "numeric", prompt: "12 konfetin yarısı (1/2) neçədir?", answer: 6, xp: 10, explanation: "Yarısını tapmaq üçün 2-yə bölürük: 12 : 2 = 6 konfet.", skills: ["fraction.of_quantity"] },
            { id: "ry3-kesr-l1-t5", type: "numeric", prompt: "9 almanın üçdə biri (1/3) neçə almadır?", answer: 3, xp: 10, explanation: "Üçdə birini tapmaq üçün 3-ə bölürük: 9 : 3 = 3 alma.", skills: ["fraction.of_quantity"] },
            { id: "ry3-kesr-l1-t6", type: "numeric", prompt: "8 konfetin dörddə biri (1/4) neçədir?", answer: 2, xp: 10, explanation: "Dörddə birini tapmaq üçün 4-ə bölürük: 8 : 4 = 2 konfet.", skills: ["fraction.of_quantity"] },
            { id: "ry3-kesr-l1-t7", type: "multiple_choice", prompt: "1/2 kəsrində alt ədəd (məxrəc) neçədir?", options: ["2", "1", "3", "4"], correctIndex: 0, xp: 10, explanation: "Kəsrin alt ədədi məxrəcdir və bütövün neçə hissəyə bölündüyünü göstərir. 1/2-də bu, 2-dir.", skills: ["fraction.concept"] },
            { id: "ry3-kesr-l1-t8", type: "numeric", prompt: "6 şarın yarısı neçədir?", answer: 3, xp: 10, explanation: "Yarısını tapmaq üçün 2-yə bölürük: 6 : 2 = 3 şar.", skills: ["fraction.concept"] },
            { id: "ry3-kesr-l1-t9", type: "numeric", prompt: "12 almanın üçdə biri (1/3) neçədir?", answer: 4, xp: 10, explanation: "Üçdə birini tapmaq üçün 3-ə bölürük: 12 : 3 = 4.", skills: ["fraction.of_quantity"] },
            { id: "ry3-kesr-l1-t10", type: "numeric", prompt: "20 konfetin dörddə biri (1/4) neçədir?", answer: 5, xp: 10, explanation: "Dörddə birini tapmaq üçün 4-ə bölürük: 20 : 4 = 5.", skills: ["fraction.of_quantity"] },
            { id: "ry3-kesr-l1-t11", type: "multiple_choice", prompt: "Hansı kəsr daha böyükdür?", options: ["1/2", "1/4", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "Sayları eynidir, ona görə məxrəclərə baxırıq. Bütöv nə qədər az hissəyə bölünsə, hər hissə bir o qədər böyük olur — deməli 1/2 böyükdür.", skills: ["fraction.compare"] },
            { id: "ry3-kesr-l1-t12", type: "numeric", prompt: "8 almanın yarısı neçədir?", answer: 4, xp: 10, explanation: "Yarısını tapmaq üçün 2-yə bölürük: 8 : 2 = 4.", skills: ["fraction.concept"] },
            { id: "ry3-kesr-l1-t13", type: "multiple_choice", prompt: "Bir bütövü 4 bərabər hissəyə bölsək, hər hissə nədir?", options: ["1/4", "1/2", "1/3", "4"], correctIndex: 0, xp: 10, explanation: "Bütöv 4 bərabər hissəyə bölünəndə hər hissə dörddə bir, yəni 1/4 olur.", skills: ["fraction.concept"] },
            { id: "ry3-kesr-l1-t14", type: "numeric", prompt: "15 almanın üçdə biri (1/3) neçədir?", answer: 5, xp: 10, explanation: "Üçdə birini tapmaq üçün 3-ə bölürük: 15 : 3 = 5.", skills: ["fraction.of_quantity"] },
            { id: "ry3-kesr-l1-t15", type: "numeric", prompt: "16 konfetin dörddə biri (1/4) neçədir?", answer: 4, xp: 15, explanation: "Dörddə birini tapmaq üçün 4-ə bölürük: 16 : 4 = 4.", skills: ["fraction.of_quantity"] },
          ],
          bonusTasks: [
            { id: "ry3-kesr-l1-b1", type: "numeric", prompt: "20 almanın yarısı neçədir?", answer: 10, xp: 15, explanation: "Yarısını tapmaq üçün 2-yə bölürük: 20 : 2 = 10.", skills: ["fraction.concept"] },
            { id: "ry3-kesr-l1-b2", type: "multiple_choice", prompt: "1/3 və 1/4 kəsrlərindən böyüyü hansıdır?", options: ["1/3", "1/4", "bərabər", "heç biri"], correctIndex: 0, xp: 15, explanation: "Sayları eynidir, ona görə məxrəclərə baxırıq: 3 < 4, yəni tort az hissəyə bölünüb. Az hissəyə bölünəndə hər pay böyük olur — deməli 1/3 böyükdür.", skills: ["fraction.compare"] },
            { id: "ry3-kesr-l1-b3", type: "numeric", prompt: "24 konfetin dörddə biri neçədir?", answer: 6, xp: 15, explanation: "Dörddə birini tapmaq üçün 4-ə bölürük: 24 : 4 = 6.", skills: ["fraction.concept"] },
            { id: "ry3-kesr-l1-b4", type: "numeric", prompt: "Tortu 2 bərabər hissəyə böldük, 1 hissəni yedik. Neçə hissə qaldı?", answer: 1, xp: 15, explanation: "Tort 2 hissəyə bölünüb, 1-i yeyilib: 2 − 1 = 1 hissə qaldı.", skills: ["problem.one_step","arith.sub.basic"] },
            { id: "ry3-kesr-l1-b5", type: "numeric", prompt: "18 almanın üçdə biri neçədir?", answer: 6, xp: 15, explanation: "Üçdə birini tapmaq üçün 3-ə bölürük: 18 : 3 = 6.", skills: ["fraction.concept"] },
          ],
        },
        {
          id: "ry3-kesr-l2",
          title: "Kəsrləri müqayisə et",
          intro: "Eyni bütövün hansı hissəsi böyükdür?",
          sections: [
            { heading: "Eyni məxrəc", body: "Məxrəclər eynidirsə, sayı böyük olan kəsr böyükdür: 3/5 > 2/5." },
            { heading: "Eyni say", body: "Saylar eynidirsə, MƏXRƏCİ KİÇİK olan böyükdür: 1/2 > 1/4, çünki bütövü az hissəyə bölmüşük." },
          ],
          tasks: [
            { id: "ry3-kesr-l2-t1", type: "multiple_choice", prompt: "Hansı böyükdür: 3/5 yoxsa 2/5?", options: ["3/5", "2/5", "Bərabərdir", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "Məxrəclər eynidir (5), ona görə saylara baxırıq: 3 > 2. Deməli 3/5 böyükdür.", skills: ["fraction.compare"] },
            { id: "ry3-kesr-l2-t2", type: "multiple_choice", prompt: "Hansı böyükdür: 1/2 yoxsa 1/4?", options: ["1/2", "1/4", "Bərabərdir", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "Sayları eynidir, məxrəclərə baxırıq: bütöv 2 hissəyə bölünəndə hər pay 4 hissəyə bölünəndəkindən böyük olur. Deməli 1/2 böyükdür.", skills: ["fraction.compare"] },
            { id: "ry3-kesr-l2-t3", type: "multiple_choice", prompt: "Hansı kiçikdir: 1/3 yoxsa 1/6?", options: ["1/6", "1/3", "Bərabərdir", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "Sayları eynidir, məxrəclərə baxırıq: 6 hissəyə bölünəndə hər pay daha kiçik olur. Deməli 1/6 kiçikdir.", skills: ["fraction.compare"] },
            { id: "ry3-kesr-l2-t4", type: "multiple_choice", prompt: "Məxrəclər eynidirsə hansı kəsr böyükdür?", options: ["Sayı böyük olan", "Sayı kiçik olan", "İkisi bərabərdir", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "Məxrəc eynidirsə, hissələrin ölçüsü də eynidir — kim daha çox hissə götürübsə, onunku böyükdür.", skills: ["fraction.compare"] },
            { id: "ry3-kesr-l2-t5", type: "multiple_choice", prompt: "2/4 kəsri hansına bərabərdir?", options: ["1/2", "1/4", "2/2", "3/4"], correctIndex: 0, xp: 10, explanation: "2/4 — bütövün 4 hissəsindən 2-si, yəni yarısıdır. Deməli 2/4 = 1/2.", skills: ["fraction.equivalent"] },
            { id: "ry3-kesr-l2-t6", type: "multiple_choice", prompt: "Bütöv bir kəsr hansıdır?", options: ["4/4", "3/4", "1/4", "2/4"], correctIndex: 0, xp: 10, explanation: "Sayla məxrəc bərabər olanda bütün hissələr götürülüb, yəni tam bütöv alınır: 4/4 = 1.", skills: ["fraction.concept"] },
            { id: "ry3-kesr-l2-t7", type: "numeric", prompt: "Bir tortu 8 bərabər hissəyə böldük. 3 hissə yeyildi. Neçə hissə qaldı?", answer: 5, xp: 10, explanation: "Tort 8 hissəyə bölünüb, 3-ü yeyilib: 8 − 3 = 5 hissə qaldı.", skills: ["problem.one_step","arith.sub.basic"] },
            { id: "ry3-kesr-l2-t8", type: "multiple_choice", prompt: "Saylar eynidirsə hansı kəsr böyükdür?", options: ["Məxrəci kiçik olan", "Məxrəci böyük olan", "Bərabərdir", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "Məxrəc kiçik olanda bütöv az hissəyə bölünür, deməli hər hissə böyük olur.", skills: ["fraction.compare"] },
            { id: "ry3-kesr-l2-t9", type: "multiple_choice", prompt: "Hansı böyükdür: 5/8 yoxsa 3/8?", options: ["5/8", "3/8", "Bərabərdir", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "Məxrəclər eynidir (8), ona görə saylara baxırıq: 5 > 3. Deməli 5/8 böyükdür.", skills: ["fraction.compare"] },
            { id: "ry3-kesr-l2-t10", type: "numeric", prompt: "Bir almanın 1/2-si nə deməkdir? Neçə bərabər hissəyə bölünüb?", answer: 2, xp: 10, explanation: "1/2-də məxrəc 2-dir, bu isə almanın 2 bərabər hissəyə bölündüyünü göstərir.", skills: ["fraction.add_sub_same"] },
          ],
          bonusTasks: [
            { id: "ry3-kesr-l2-b1", type: "multiple_choice", prompt: "1/2, 1/3, 1/5 — ən böyüyü hansıdır?", options: ["1/2", "1/3", "1/5", "Bərabərdirlər"], correctIndex: 0, xp: 15, explanation: "Sayları eynidir, məxrəclərə baxırıq: 2 < 3 < 5. Ən az hissəyə bölünəndə pay ən böyük olur — deməli 1/2.", skills: ["fraction.compare"] },
            { id: "ry3-kesr-l2-b2", type: "numeric", prompt: "Bir bütöv 6 hissədir. 6/6 neçə bütövdür?", answer: 1, xp: 15, explanation: "6 hissədən 6-sı, yəni bütün hissələr götürülüb: 6/6 = 1 bütöv.", skills: ["fraction.concept"] },
            { id: "ry3-kesr-l2-b3", type: "multiple_choice", prompt: "3/6 kəsri hansına bərabərdir?", options: ["1/2", "1/3", "1/6", "2/3"], correctIndex: 0, xp: 15, explanation: "3/6 — bütövün 6 hissəsindən 3-ü, yəni yarısıdır. Deməli 3/6 = 1/2.", skills: ["fraction.equivalent"] },
            { id: "ry3-kesr-l2-b4", type: "numeric", prompt: "12 konfetin 1/4-i neçə konfetdir?", answer: 3, xp: 15, explanation: "Dörddə birini tapmaq üçün 4-ə bölürük: 12 : 4 = 3 konfet.", skills: ["fraction.add_sub_same"] },
          ],
        },
        {
          id: "ry3-kesr-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry3-kesr-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 6. Həndəsə, ölçmə və məsələlər ═══════════════
    {
      id: "ry3-hendese",
      title: "Həndəsə, ölçmə və məsələlər",
      description: "Perimetr, ölçü vahidləri və mətn məsələləri.",
      lessons: [
        {
          id: "ry3-hendese-l1",
          title: "Perimetr və ölçmə",
          intro: "Fiqurun perimetri və ölçü vahidləri.",
          sections: [
            { heading: "Perimetr", body: "Perimetr fiqurun bütün tərəflərinin cəmidir. Kvadratın perimetri: 4 × tərəf. Düzbucaqlının perimetri: 2 × (uzunluq + en)." },
            { heading: "Ölçü vahidləri", body: "1 metr = 100 sm. 1 kq = 1000 qram. 1 litr, 1 saat = 60 dəqiqə." },
          ],
          tasks: [
            { id: "ry3-hendese-l1-t1", type: "numeric", prompt: "Kvadratın tərəfi 6 sm-dir. Perimetri neçədir? (4 × 6)", answer: 24, xp: 10, explanation: "Perimetr tərəflərin cəmidir. Kvadratın 4 bərabər tərəfi var: 4 × 6 = 24 sm.", skills: ["geom.perimeter","geom.shapes","measure.convert"] },
            { id: "ry3-hendese-l1-t2", type: "numeric", prompt: "Kvadratın tərəfi 10 sm-dir. Perimetri neçədir?", answer: 40, xp: 10, explanation: "Kvadratın 4 bərabər tərəfi var: 4 × 10 = 40 sm.", skills: ["geom.perimeter","geom.shapes","measure.convert"] },
            { id: "ry3-hendese-l1-t3", type: "numeric", prompt: "Düzbucaqlının tərəfləri 5 və 3 sm-dir. Perimetri? (2×(5+3))", answer: 16, xp: 10, explanation: "Düzbucaqlıda qarşı tərəflər bərabərdir: 2 × (5 + 3) = 2 × 8 = 16 sm.", skills: ["geom.perimeter","geom.shapes","measure.convert"] },
            { id: "ry3-hendese-l1-t4", type: "numeric", prompt: "Üçbucağın tərəfləri 4, 5, 6 sm-dir. Perimetri? (4+5+6)", answer: 15, xp: 10, explanation: "Perimetr bütün tərəflərin cəmidir: 4 + 5 + 6 = 15 sm.", skills: ["geom.perimeter","geom.shapes","measure.convert"] },
            { id: "ry3-hendese-l1-t5", type: "numeric", prompt: "1 metr neçə santimetrdir?", answer: 100, xp: 10, explanation: "Metr santimetrdən böyük vahiddir: 1 m = 100 sm.", skills: ["measure.convert"] },
            { id: "ry3-hendese-l1-t6", type: "numeric", prompt: "1 kiloqram neçə qramdır?", answer: 1000, xp: 10, explanation: "Kiloqram qramdan böyük vahiddir: 1 kq = 1000 q.", skills: ["measure.convert"] },
            { id: "ry3-hendese-l1-t7", type: "numeric", prompt: "1 saat neçə dəqiqədir?", answer: 60, xp: 10, explanation: "Saat 60 bərabər dəqiqəyə bölünür.", skills: ["measure.time"] },
            { id: "ry3-hendese-l1-t8", type: "numeric", prompt: "3 metr neçə santimetrdir?", answer: 300, xp: 10, explanation: "1 m = 100 sm, deməli 3 × 100 = 300 sm.", skills: ["measure.convert"] },
            { id: "ry3-hendese-l1-t9", type: "numeric", prompt: "2 kq neçə qramdır?", answer: 2000, xp: 10, explanation: "1 kq = 1000 q, deməli 2 × 1000 = 2000 q.", skills: ["measure.convert"] },
            { id: "ry3-hendese-l1-t10", type: "numeric", prompt: "Kvadratın tərəfi 8 sm-dir. Perimetri neçədir?", answer: 32, xp: 10, explanation: "Kvadratın 4 bərabər tərəfi var: 4 × 8 = 32 sm.", skills: ["geom.perimeter","geom.shapes","measure.convert"] },
            { id: "ry3-hendese-l1-t11", type: "numeric", prompt: "Düzbucaqlının tərəfləri 7 və 3 sm-dir. Perimetri?", answer: 20, xp: 10, explanation: "Düzbucaqlıda qarşı tərəflər bərabərdir: 2 × (7 + 3) = 2 × 10 = 20 sm.", skills: ["geom.perimeter","geom.shapes","measure.convert"] },
            { id: "ry3-hendese-l1-t12", type: "numeric", prompt: "Yarım saat neçə dəqiqədir?", answer: 30, xp: 10, explanation: "Yarım saat saatın yarısıdır: 60 : 2 = 30 dəqiqə.", skills: ["measure.time"] },
            { id: "ry3-hendese-l1-t13", type: "numeric", prompt: "Hər tərəfi 5 sm olan üçbucağın perimetri? (3 × 5)", answer: 15, xp: 10, explanation: "Üçbucağın 3 tərəfi var və hamısı bərabərdir: 3 × 5 = 15 sm.", skills: ["geom.perimeter","geom.shapes"] },
            { id: "ry3-hendese-l1-t14", type: "numeric", prompt: "500 qram + 500 qram neçə kiloqramdır?", answer: 1, xp: 10, explanation: "500 + 500 = 1000 qram, 1000 qram isə 1 kiloqramdır.", skills: ["measure.convert"] },
            { id: "ry3-hendese-l1-t15", type: "numeric", prompt: "Kvadratın perimetri 20 sm-dir. Bir tərəfi neçədir? (20 ÷ 4)", answer: 5, xp: 15, explanation: "Perimetr 4 bərabər tərəfin cəmidir, ona görə bir tərəfi tapmaq üçün 4-ə bölürük: 20 : 4 = 5 sm.", skills: ["geom.perimeter","geom.shapes","measure.convert"] },
          ],
          bonusTasks: [
            { id: "ry3-hendese-l1-b1", type: "numeric", prompt: "Düzbucaqlının tərəfləri 8 və 4 sm-dir. Perimetri?", answer: 24, xp: 15, explanation: "Düzbucaqlıda qarşı tərəflər bərabərdir: 2 × (8 + 4) = 2 × 12 = 24 sm.", skills: ["geom.perimeter","geom.shapes","measure.convert"] },
            { id: "ry3-hendese-l1-b2", type: "numeric", prompt: "5 metr neçə santimetrdir?", answer: 500, xp: 15, explanation: "1 m = 100 sm, deməli 5 × 100 = 500 sm.", skills: ["measure.convert"] },
            { id: "ry3-hendese-l1-b3", type: "numeric", prompt: "3 saat neçə dəqiqədir? (3 × 60)", answer: 180, xp: 15, explanation: "Bir saat 60 dəqiqədir: 3 × 60 = 180 dəqiqə.", skills: ["measure.time"] },
            { id: "ry3-hendese-l1-b4", type: "numeric", prompt: "Kvadratın perimetri 36 sm-dir. Bir tərəfi neçədir?", answer: 9, xp: 15, explanation: "Bir tərəfi tapmaq üçün perimetri 4-ə bölürük: 36 : 4 = 9 sm.", skills: ["geom.perimeter","geom.shapes","measure.convert"] },
            { id: "ry3-hendese-l1-b5", type: "numeric", prompt: "Kvadratın sahəsi: tərəf 4 sm-dirsə, sahə neçə kv.sm-dir? (4×4)", answer: 16, xp: 15, explanation: "Sahə uzunluqla enin hasilidir. Kvadratda hər ikisi eynidir: 4 × 4 = 16 kv.sm.", skills: ["geom.area","geom.shapes","measure.convert"] },
          ],
        },
        {
          id: "ry3-hendese-l2",
          title: "Mətn məsələləri",
          intro: "Toplama, çıxma, vurma və bölmə ilə məsələ həll edək.",
          sections: [
            { heading: "Məsələ", body: "Diqqətlə oxu, düzgün əməli seç, hesabla." },
          ],
          tasks: [
            { id: "ry3-hendese-l2-t1", type: "numeric", prompt: "Mağazada 250 kitab var idi, 130 satıldı. Neçə kitab qaldı?", answer: 120, xp: 10, explanation: "«Satıldı» azalma deməkdir: 250 − 130 = 120 kitab qaldı.", skills: ["problem.one_step","arith.sub.no_borrow"] },
            { id: "ry3-hendese-l2-t2", type: "numeric", prompt: "Hər sinifdə 25 şagird var. 4 sinifdə neçə şagird var?", answer: 100, xp: 10, explanation: "Hər sinifdəki 25 şagird 4 dəfə təkrarlanır: 4 × 25 = 100.", skills: ["problem.one_step","arith.mul.tables"] },
            { id: "ry3-hendese-l2-t3", type: "numeric", prompt: "72 alma 8 qutuya bərabər paylandı. Hər qutuda neçə alma var?", answer: 9, xp: 10, explanation: "72 almanı 8 qutuya bərabər paylayırıq: 72 : 8 = 9.", skills: ["problem.one_step","arith.div.tables"] },
            { id: "ry3-hendese-l2-t4", type: "numeric", prompt: "Aylının 340 manatı var idi, 150 manat xərclədi. Neçə manatı qaldı?", answer: 190, xp: 10, explanation: "«Xərclədi» azalma deməkdir: 340 − 150 = 190 manat qaldı.", skills: ["measure.money","problem.one_step","arith.sub.borrow"] },
            { id: "ry3-hendese-l2-t5", type: "numeric", prompt: "Kitabxanada 500 kitab var, 250 də əlavə olundu. Neçə kitab oldu?", answer: 750, xp: 10, explanation: "«Əlavə olundu» artım deməkdir: 500 + 250 = 750 kitab.", skills: ["problem.one_step","arith.add.no_carry"] },
            { id: "ry3-hendese-l2-t6", type: "numeric", prompt: "Hər gün 6 səhifə oxuyuram. 7 gündə neçə səhifə oxuyuram?", answer: 42, xp: 10, explanation: "Hər günkü 6 səhifə 7 dəfə təkrarlanır: 7 × 6 = 42.", skills: ["problem.one_step","arith.mul.tables"] },
            { id: "ry3-hendese-l2-t7", type: "numeric", prompt: "48 şəkil 6 albomda bərabər yerləşdi. Hər albomda neçə şəkil var?", answer: 8, xp: 10, explanation: "48 şəkli 6 alboma bərabər paylayırıq: 48 : 6 = 8.", skills: ["problem.one_step","arith.div.tables"] },
            { id: "ry3-hendese-l2-t8", type: "numeric", prompt: "Bağçada 200 gül var idi, 85 soldu. Neçə gül qaldı?", answer: 115, xp: 10, explanation: "«Soldu» azalma deməkdir: 200 − 85 = 115 gül qaldı.", skills: ["problem.one_step","arith.sub.borrow"] },
            { id: "ry3-hendese-l2-t9", type: "numeric", prompt: "Hər qutuda 9 qələm var. 5 qutuda neçə qələm var?", answer: 45, xp: 10, explanation: "Hər qutudakı 9 qələm 5 dəfə təkrarlanır: 5 × 9 = 45.", skills: ["problem.one_step","arith.mul.tables"] },
            { id: "ry3-hendese-l2-t10", type: "numeric", prompt: "63 konfet 9 uşağa bərabər paylandı. Hər biri neçə alır?", answer: 7, xp: 10, explanation: "63 konfeti 9 uşağa bərabər paylayırıq: 63 : 9 = 7.", skills: ["problem.one_step","arith.div.tables"] },
            { id: "ry3-hendese-l2-t11", type: "numeric", prompt: "İki qutuda 125 və 175 marka var. Cəmi neçə marka var?", answer: 300, xp: 10, explanation: "«Cəmi» toplama deməkdir: 125 + 175 = 300 marka.", skills: ["problem.one_step","arith.add.carry"] },
            { id: "ry3-hendese-l2-t12", type: "numeric", prompt: "Anarın 8 yaşı var. Atası ondan 4 dəfə böyükdür. Atası neçə yaşındadır?", answer: 32, xp: 10, explanation: "«4 dəfə böyük» vurma deməkdir: 8 × 4 = 32 yaş.", skills: ["problem.one_step","arith.mul.tables"] },
            { id: "ry3-hendese-l2-t13", type: "numeric", prompt: "600 manatlıq velosipedə 250 manat endirim edildi. Yeni qiymət neçədir?", answer: 350, xp: 10, explanation: "Endirim qiymətdən çıxılır: 600 − 250 = 350 manat.", skills: ["measure.money","problem.one_step","arith.sub.borrow"] },
            { id: "ry3-hendese-l2-t14", type: "numeric", prompt: "56 şagird 8 komandaya bərabər bölündü. Hər komandada neçə nəfər var?", answer: 7, xp: 10, explanation: "56 şagirdi 8 komandaya bərabər bölürük: 56 : 8 = 7.", skills: ["problem.one_step","arith.div.tables"] },
            { id: "ry3-hendese-l2-t15", type: "numeric", prompt: "Hər həftədə 7 gün var. 8 həftədə neçə gün var?", answer: 56, xp: 15, explanation: "Hər həftədəki 7 gün 8 dəfə təkrarlanır: 8 × 7 = 56.", skills: ["measure.time","problem.one_step","arith.mul.tables"] },
          ],
          bonusTasks: [
            { id: "ry3-hendese-l2-b1", type: "numeric", prompt: "Bir avtobusda 45 sərnişin var. 2 avtobusda neçə sərnişin var?", answer: 90, xp: 15, explanation: "Hər avtobusdakı 45 sərnişin 2 dəfə təkrarlanır: 2 × 45 = 90.", skills: ["problem.one_step","arith.mul.tables"] },
            { id: "ry3-hendese-l2-b2", type: "numeric", prompt: "1000 manatım var idi, 350 və 250 manat xərclədim. Neçə manat qaldı?", answer: 400, xp: 15, explanation: "Əvvəl xərcləri toplayırıq: 350 + 250 = 600. Sonra 1000 − 600 = 400 manat qalır.", skills: ["measure.money","problem.multi_step","arith.add.carry"] },
            { id: "ry3-hendese-l2-b3", type: "numeric", prompt: "81 kitab 9 rəfə bərabər yerləşdi. Hər rəfdə neçə kitab var?", answer: 9, xp: 15, explanation: "81 kitabı 9 rəfə bərabər paylayırıq: 81 : 9 = 9.", skills: ["problem.one_step","arith.div.tables"] },
            { id: "ry3-hendese-l2-b4", type: "numeric", prompt: "Hər qutuda 12 yumurta var. 6 qutuda neçə yumurta var?", answer: 72, xp: 15, explanation: "Hər qutudakı 12 yumurta 6 dəfə təkrarlanır: 6 × 12 = 72.", skills: ["problem.one_step","arith.mul.tables"] },
            { id: "ry3-hendese-l2-b5", type: "numeric", prompt: "240 səhifəlik kitabın 160 səhifəsini oxudum. Neçə səhifə qaldı?", answer: 80, xp: 15, explanation: "Oxunanı ümumi saydan çıxırıq: 240 − 160 = 80 səhifə qaldı.", skills: ["problem.one_step","arith.sub.borrow"] },
          ],
        },
        {
          id: "ry3-hendese-l3",
          title: "Perimetr və sahə",
          intro: "Fiqurun ətrafı və içi.",
          sections: [
            { heading: "Perimetr", body: "Perimetr — fiqurun bütün tərəflərinin cəmidir. Tərəfi 4 sm olan kvadratın perimetri: 4 + 4 + 4 + 4 = 16 sm." },
            { heading: "Sahə", body: "Sahə — fiqurun tutduğu yerdir. Düzbucaqlının sahəsi = uzunluq × en. 5 × 3 = 15 kvadrat sm." },
          ],
          tasks: [
            { id: "ry3-hendese-l3-t1", type: "numeric", prompt: "Tərəfi 4 sm olan kvadratın perimetri neçə sm-dir?", answer: 16, xp: 10, explanation: "Kvadratın 4 bərabər tərəfi var: 4 × 4 = 16 sm.", skills: ["geom.perimeter","geom.shapes","measure.convert"] },
            { id: "ry3-hendese-l3-t2", type: "numeric", prompt: "Tərəfləri 5 sm və 3 sm olan düzbucaqlının perimetri neçə sm-dir?", answer: 16, xp: 10, explanation: "Düzbucaqlıda qarşı tərəflər bərabərdir: 2 × (5 + 3) = 16 sm.", skills: ["geom.perimeter","geom.shapes","measure.convert","problem.one_step"] },
            { id: "ry3-hendese-l3-t3", type: "numeric", prompt: "Tərəfləri 5 sm və 3 sm olan düzbucaqlının sahəsi neçə kvadrat sm-dir?", answer: 15, xp: 10, explanation: "Sahə uzunluqla enin hasilidir: 5 × 3 = 15 kv.sm.", skills: ["geom.area","geom.shapes","measure.convert","problem.one_step"] },
            { id: "ry3-hendese-l3-t4", type: "numeric", prompt: "Tərəfi 6 sm olan kvadratın perimetri neçə sm-dir?", answer: 24, xp: 10, explanation: "Kvadratın 4 bərabər tərəfi var: 4 × 6 = 24 sm.", skills: ["geom.perimeter","geom.shapes","measure.convert"] },
            { id: "ry3-hendese-l3-t5", type: "numeric", prompt: "Tərəfi 6 sm olan kvadratın sahəsi neçə kvadrat sm-dir?", answer: 36, xp: 10, explanation: "Kvadratda uzunluqla en eynidir: 6 × 6 = 36 kv.sm.", skills: ["geom.area","geom.shapes","measure.convert"] },
            { id: "ry3-hendese-l3-t6", type: "multiple_choice", prompt: "Perimetr nədir?", options: ["Tərəflərin cəmi", "Fiqurun içi", "Tərəflərin sayı", "Bucaqların sayı"], correctIndex: 0, xp: 10, explanation: "Perimetr fiqurun ətrafının uzunluğudur, yəni bütün tərəflərinin cəmidir.", skills: ["geom.perimeter"] },
            { id: "ry3-hendese-l3-t7", type: "numeric", prompt: "Tərəfləri 7 sm və 2 sm olan düzbucaqlının sahəsi neçə kvadrat sm-dir?", answer: 14, xp: 10, explanation: "Sahə uzunluqla enin hasilidir: 7 × 2 = 14 kv.sm.", skills: ["geom.area","geom.shapes","measure.convert","problem.one_step"] },
            { id: "ry3-hendese-l3-t8", type: "multiple_choice", prompt: "Düzbucaqlının sahəsi necə tapılır?", options: ["Uzunluq × en", "Uzunluq + en", "Tərəflərin cəmi", "Uzunluq − en"], correctIndex: 0, xp: 10, explanation: "Sahə fiqurun içinə neçə vahid kvadrat sığdığını göstərir; bu isə uzunluqla enin hasilinə bərabərdir.", skills: ["geom.area","geom.shapes"] },
            { id: "ry3-hendese-l3-t9", type: "numeric", prompt: "Perimetri 20 sm olan kvadratın bir tərəfi neçə sm-dir?", answer: 5, xp: 10, explanation: "Bir tərəfi tapmaq üçün perimetri 4-ə bölürük: 20 : 4 = 5 sm.", skills: ["geom.perimeter","geom.shapes","measure.convert"] },
            { id: "ry3-hendese-l3-t10", type: "numeric", prompt: "Tərəfləri 8 sm və 4 sm olan düzbucaqlının perimetri neçə sm-dir?", answer: 24, xp: 10, explanation: "Düzbucaqlıda qarşı tərəflər bərabərdir: 2 × (8 + 4) = 24 sm.", skills: ["geom.perimeter","geom.shapes","measure.convert","problem.one_step"] },
          ],
          bonusTasks: [
            { id: "ry3-hendese-l3-b1", type: "numeric", prompt: "Sahəsi 24 kv.sm, eni 4 sm olan düzbucaqlının uzunluğu neçə sm-dir?", answer: 6, xp: 15, explanation: "Sahə = uzunluq × en. Uzunluğu tapmaq üçün sahəni enə bölürük: 24 : 4 = 6 sm.", skills: ["geom.area","geom.shapes","measure.convert","measure.compare","problem.one_step"] },
            { id: "ry3-hendese-l3-b2", type: "numeric", prompt: "Tərəfi 10 sm olan kvadratın sahəsi neçə kvadrat sm-dir?", answer: 100, xp: 15, explanation: "Kvadratda uzunluqla en eynidir: 10 × 10 = 100 kv.sm.", skills: ["geom.area","geom.shapes","measure.convert"] },
            { id: "ry3-hendese-l3-b3", type: "multiple_choice", prompt: "Eyni perimetrli iki fiqurun sahəsi eyni olmalıdırmı?", options: ["Xeyr, fərqli ola bilər", "Bəli, həmişə", "Yalnız kvadratda", "Bilmək olmur"], correctIndex: 0, xp: 15, explanation: "Məsələn, tərəfləri 4 və 4 olan fiqurun sahəsi 16, tərəfləri 6 və 2 olanınkı isə 12-dir — perimetrləri eyni (16 sm) olsa da sahələri fərqlidir.", skills: ["geom.perimeter","geom.area","geom.shapes"] },
            { id: "ry3-hendese-l3-b4", type: "numeric", prompt: "Bağın perimetri 30 m-dir, üç tərəfi 8 m, 9 m, 6 m-dir. Dördüncü tərəf neçə metrdir?", answer: 7, xp: 15, explanation: "Məlum üç tərəfi toplayırıq: 8 + 9 + 6 = 23. Dördüncü tərəf: 30 − 23 = 7 metr.", skills: ["geom.perimeter","geom.shapes","measure.convert","problem.multi_step"] },
          ],
        },
        {
          id: "ry3-hendese-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry3-hendese-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
  ],
};
