// Riyaziyyat — 2-ci sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Ədədlər 100-ə qədər  2) 100 dairəsində toplama  3) 100 dairəsində çıxma
// 4) Vurma (2,3,4,5)  5) Bölmə  6) Ölçmə, zaman, pul və fiqurlar.
// 2-ci sinif üçün suallar sadədir (rəqəm cavablar). id prefiksi ry2-*.

import type { Subject } from "../types";

export const math2: Subject = {
  slug: "riyaziyyat-2",
  name: "Riyaziyyat",
  grade: 2,
  icon: "R",
  color: "sky",
  units: [
    // ═══════════════ 1. Ədədlər 100-ə qədər ═══════════════
    {
      id: "ry2-yuzluk",
      title: "Ədədlər 100-ə qədər",
      description: "İkirəqəmli ədədləri oxumaq, yazmaq, onluq və təkliklərə ayırmaq, müqayisə etmək.",
      lessons: [
        {
          id: "ry2-yuzluk-l1",
          title: "İkirəqəmli ədədlər",
          intro: "Onluq və təklikləri tanıyaq.",
          sections: [
            { heading: "Onluq və təklik", body: "İkirəqəmli ədəd onluq və təklikdən ibarətdir. 34 = 3 onluq + 4 təklik. 50 = 5 onluq. 7 = 7 təklik." },
            { heading: "Sıra", body: "Ədədlər sıra ilə gedir: 20, 21, 22... Hər ədəddən sonra gələn 1 böyükdür." },
          ],
          tasks: [
            { id: "ry2-yuzluk-l1-t1", type: "numeric", prompt: "34 ədədində neçə onluq var?", answer: 3, xp: 10, explanation: "34 = 3 onluq + 4 təklik. Deməli onluqların sayı 3-dir.", skills: ["number.place_value"] },
            { id: "ry2-yuzluk-l1-t2", type: "numeric", prompt: "34 ədədində neçə təklik var?", answer: 4, xp: 10, explanation: "34 = 3 onluq + 4 təklik. Deməli təkliklərin sayı 4-dir.", skills: ["number.place_value"] },
            { id: "ry2-yuzluk-l1-t3", type: "numeric", prompt: "50 ədədində neçə onluq var?", answer: 5, xp: 10, explanation: "50 = 5 onluq + 0 təklik. Deməli onluqların sayı 5-dir.", skills: ["number.place_value"] },
            { id: "ry2-yuzluk-l1-t4", type: "numeric", prompt: "3 onluq + 5 təklik = ?", answer: 35, xp: 10, explanation: "3 onluq 30 deməkdir. Üstünə 5 təklik gəlir: 30 + 5 = 35.", skills: ["number.place_value"] },
            { id: "ry2-yuzluk-l1-t5", type: "numeric", prompt: "4 onluq + 2 təklik = ?", answer: 42, xp: 10, explanation: "4 onluq 40 deməkdir. Üstünə 2 təklik gəlir: 40 + 2 = 42.", skills: ["number.place_value"] },
            { id: "ry2-yuzluk-l1-t6", type: "numeric", prompt: "6 onluq = ?", answer: 60, xp: 10, explanation: "1 onluq 10-dur, ona görə 6 onluq = 6 × 10 = 60.", skills: ["number.place_value"] },
            { id: "ry2-yuzluk-l1-t7", type: "numeric", prompt: "29-dan sonra hansı ədəd gəlir?", answer: 30, xp: 10, explanation: "«Sonra gələn» 1 çox deməkdir: 29 + 1 = 30.", skills: ["number.count"] },
            { id: "ry2-yuzluk-l1-t8", type: "numeric", prompt: "50-dən əvvəl gələn ədəd hansıdır?", answer: 49, xp: 10, explanation: "«Əvvəl gələn» 1 az deməkdir: 50 − 1 = 49.", skills: ["number.count"] },
            { id: "ry2-yuzluk-l1-t9", type: "numeric", prompt: "99-dan sonra hansı ədəd gəlir?", answer: 100, xp: 10, explanation: "«Sonra gələn» 1 çox deməkdir: 99 + 1 = 100.", skills: ["number.count"] },
            { id: "ry2-yuzluk-l1-t10", type: "multiple_choice", prompt: "47 və 74 ədədlərindən böyüyü hansıdır?", options: ["74", "47", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "Onluqlara baxırıq: 7 onluq 4 onluqdan çoxdur, deməli 74 böyükdür.", skills: ["number.compare"] },
            { id: "ry2-yuzluk-l1-t11", type: "multiple_choice", prompt: "63 və 36 ədədlərindən kiçiyi hansıdır?", options: ["36", "63", "bərabər", "heç biri"], correctIndex: 0, xp: 10, explanation: "Onluqlara baxırıq: 3 onluq 6 onluqdan azdır, deməli 36 kiçikdir.", skills: ["number.compare"] },
            { id: "ry2-yuzluk-l1-t12", type: "numeric", prompt: "7 onluq + 0 təklik = ?", answer: 70, xp: 10, explanation: "7 onluq 70 deməkdir. Üstünə 0 təklik gəlir: 70 + 0 = 70.", skills: ["number.place_value"] },
            { id: "ry2-yuzluk-l1-t13", type: "numeric", prompt: "'səksən' ədədi rəqəmlə necə yazılır?", answer: 80, xp: 10, explanation: "«Səksən» 8 onluq deməkdir, ona görə rəqəmlə 80 yazılır.", skills: ["number.place_value"] },
            { id: "ry2-yuzluk-l1-t14", type: "numeric", prompt: "'iyirmi beş' ədədi rəqəmlə necə yazılır?", answer: 25, xp: 10, explanation: "«İyirmi» 2 onluq, «beş» isə 5 təklikdir: 20 + 5 = 25.", skills: ["number.place_value"] },
            { id: "ry2-yuzluk-l1-t15", type: "numeric", prompt: "90-dan sonra hansı ədəd gəlir?", answer: 91, xp: 15, explanation: "«Sonra gələn» 1 çox deməkdir: 90 + 1 = 91.", skills: ["number.count"] },
          ],
          bonusTasks: [
            { id: "ry2-yuzluk-l1-b1", type: "numeric", prompt: "56 və 65 ədədlərindən böyüyü hansıdır?", answer: 65, xp: 15, explanation: "Onluqlara baxırıq: 6 onluq 5 onluqdan çoxdur, deməli 65 böyükdür.", skills: ["number.compare"] },
            { id: "ry2-yuzluk-l1-b2", type: "numeric", prompt: "8 onluq + 8 təklik = ?", answer: 88, xp: 15, explanation: "8 onluq 80 deməkdir. Üstünə 8 təklik gəlir: 80 + 8 = 88.", skills: ["number.place_value"] },
            { id: "ry2-yuzluk-l1-b3", type: "numeric", prompt: "100 ədədində neçə onluq var?", answer: 10, xp: 15, explanation: "100 = 10 onluq + 0 təklik. Deməli onluqların sayı 10-dir.", skills: ["number.place_value"] },
            { id: "ry2-yuzluk-l1-b4", type: "numeric", prompt: "'qırx' ədədi rəqəmlə necə yazılır?", answer: 40, xp: 15, explanation: "«Qırx» 4 onluq deməkdir, ona görə rəqəmlə 40 yazılır.", skills: ["number.place_value"] },
            { id: "ry2-yuzluk-l1-b5", type: "numeric", prompt: "45, 54, 44 ədədlərindən ən böyüyü hansıdır?", answer: 54, xp: 15, explanation: "Onluqlara baxırıq: 54-də 5 onluq var, 45 və 44-də isə 4. Deməli ən böyüyü 54-dür.", skills: ["number.compare"] },
          ],
        },
        {
          id: "ry2-yuzluk-l2",
          title: "Ədədləri müqayisə et",
          intro: "Hansı böyükdür? Əvvəl onluqlara, sonra təkliklərə bax.",
          sections: [
            { heading: "Qayda", body: "İki ikirəqəmli ədədi müqayisə edərkən ƏVVƏL onluqlara bax. Onluqlar bərabərdirsə, təklikləri müqayisə et. Məsələn 47 və 42: onluqlar eynidir (4), təkliklərdə 7 > 2, deməli 47 > 42." },
            { heading: "İşarələr", body: "> böyükdür, < kiçikdir, = bərabərdir. İşarənin ağzı həmişə BÖYÜK ədədə baxır." },
          ],
          tasks: [
            { id: "ry2-yuzluk-l2-t1", type: "multiple_choice", prompt: "Hansı daha böyükdür: 47 yoxsa 42?", options: ["47", "42", "Bərabərdir", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "Əvvəl onluqlara baxırıq: 4 onluq 4 onluqdan çoxdur. Deməli 47 > 42.", skills: ["number.compare"] },
            { id: "ry2-yuzluk-l2-t2", type: "multiple_choice", prompt: "Hansı daha böyükdür: 38 yoxsa 83?", options: ["83", "38", "Bərabərdir", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "Əvvəl onluqlara baxırıq: 8 onluq 3 onluqdan çoxdur. Deməli 83 > 38.", skills: ["number.compare"] },
            { id: "ry2-yuzluk-l2-t3", type: "multiple_choice", prompt: "Hansı daha kiçikdir: 61 yoxsa 16?", options: ["16", "61", "Bərabərdir", "Bilmək olmur"], correctIndex: 0, xp: 10, explanation: "Onluqlara baxırıq: 16-da 1 onluq, 61-də 6 onluq var. Deməli 16 kiçikdir.", skills: ["number.compare"] },
            { id: "ry2-yuzluk-l2-t4", type: "multiple_choice", prompt: "Müqayisədə ƏVVƏL nəyə baxırıq?", options: ["Onluqlara", "Təkliklərə", "Sonuncu rəqəmə", "Fərqi yoxdur"], correctIndex: 0, xp: 10, explanation: "Onluq təklikdən böyük mərtəbədir, ona görə əvvəl onluqlar müqayisə edilir; onlar bərabər olanda təkliklərə baxılır.", skills: ["number.compare"] },
            { id: "ry2-yuzluk-l2-t5", type: "numeric", prompt: "25, 52, 35 — ən böyüyünü yaz.", answer: 52, xp: 10, explanation: "Onluqlar: 2, 5, 3. Ən çox onluq 52-dədir, deməli ən böyüyü odur.", skills: ["number.compare"] },
            { id: "ry2-yuzluk-l2-t6", type: "numeric", prompt: "74, 47, 44 — ən kiçiyini yaz.", answer: 44, xp: 10, explanation: "Onluqlar: 7, 4, 4. 47 və 44-də onluqlar bərabərdir, ona görə təkliklərə baxırıq: 4 < 7. Deməli ən kiçiyi 44-dür.", skills: ["number.compare"] },
            { id: "ry2-yuzluk-l2-t7", type: "multiple_choice", prompt: "60 ... 59 — hansı işarə düzgündür?", options: [">", "<", "=", "Heç biri"], correctIndex: 0, xp: 10, explanation: "60-da 6 onluq, 59-da isə 5 onluq var. Deməli 60 > 59.", skills: ["number.compare"] },
            { id: "ry2-yuzluk-l2-t8", type: "multiple_choice", prompt: "33 ... 33 — hansı işarə düzgündür?", options: ["=", ">", "<", "Heç biri"], correctIndex: 0, xp: 10, explanation: "Hər iki ədəd eynidir, ona görə aralarına bərabərlik işarəsi qoyulur: 33 = 33.", skills: ["number.compare"] },
            { id: "ry2-yuzluk-l2-t9", type: "numeric", prompt: "40-dan böyük, 42-dən kiçik ədəd hansıdır?", answer: 41, xp: 10, explanation: "40 ilə 42 arasında yalnız bir ədəd var — 41.", skills: ["number.compare"] },
            { id: "ry2-yuzluk-l2-t10", type: "fill_blank", prompt: "İşarənin ağzı həmişə ______ ədədə baxır. (bir söz)", accepted: ["böyük", "Böyük", "boyuk"], xp: 10, explanation: "«>» və «<» işarələrinin açıq ağzı həmişə böyük ədədə tərəf baxır.", skills: ["number.compare"] },
          ],
          bonusTasks: [
            { id: "ry2-yuzluk-l2-b1", type: "numeric", prompt: "İkirəqəmli ən böyük ədəd hansıdır?", answer: 99, xp: 15, explanation: "Ən böyük onluq 9, ən böyük təklik də 9-dur: 90 + 9 = 99.", skills: ["number.compare"] },
            { id: "ry2-yuzluk-l2-b2", type: "numeric", prompt: "İkirəqəmli ən kiçik ədəd hansıdır?", answer: 10, xp: 15, explanation: "İkirəqəmli ədəddə ən azı 1 onluq olmalıdır: 1 onluq + 0 təklik = 10.", skills: ["number.compare"] },
            { id: "ry2-yuzluk-l2-b3", type: "multiple_choice", prompt: "Onluğu 5, təkliyi 0 olan ədəd hansıdır?", options: ["50", "5", "15", "55"], correctIndex: 0, xp: 15, explanation: "5 onluq 50 edir, təklik 0 olduğu üçün üstünə heç nə əlavə olunmur: 50.", skills: ["number.compare"] },
            { id: "ry2-yuzluk-l2-b4", type: "numeric", prompt: "68 və 86 — bunların fərqi neçədir?", answer: 18, xp: 15, explanation: "Fərq böyükdən kiçiyi çıxmaqla tapılır: 86 − 68 = 18.", skills: ["number.compare"] },
          ],
        },
        {
          id: "ry2-yuzluk-l3",
          title: "Qonşu ədədlər və sıra",
          intro: "Hər ədədin bir əvvəlki və bir sonrakı qonşusu var.",
          sections: [
            { heading: "Qonşular", body: "Ədədin SOL qonşusu ondan 1 kiçik, SAĞ qonşusu 1 böyükdür. 39-un qonşuları: 38 və 40." },
            { heading: "Onluqla saymaq", body: "10, 20, 30, 40... — hər dəfə 10 artır. Bu, onluqla saymaqdır və toplamağı asanlaşdırır." },
          ],
          tasks: [
            { id: "ry2-yuzluk-l3-t1", type: "numeric", prompt: "39-dan sonra hansı ədəd gəlir?", answer: 40, xp: 10, explanation: "«Sonra gələn» 1 çox deməkdir: 39 + 1 = 40.", skills: ["number.count"] },
            { id: "ry2-yuzluk-l3-t2", type: "numeric", prompt: "70-dən əvvəl hansı ədəd gəlir?", answer: 69, xp: 10, explanation: "«Əvvəl gələn» 1 az deməkdir: 70 − 1 = 69.", skills: ["number.count"] },
            { id: "ry2-yuzluk-l3-t3", type: "numeric", prompt: "50, 60, 70, ... — növbəti ədəd?", answer: 80, xp: 10, explanation: "Sıra hər dəfə 10 artır: 50, 60, 70. Deməli növbəti ədəd 70 + 10 = 80.", skills: ["number.sequence"] },
            { id: "ry2-yuzluk-l3-t4", type: "numeric", prompt: "99-dan sonra hansı ədəd gəlir?", answer: 100, xp: 10, explanation: "«Sonra gələn» 1 çox deməkdir: 99 + 1 = 100.", skills: ["number.count"] },
            { id: "ry2-yuzluk-l3-t5", type: "numeric", prompt: "45-in sağ qonşusu hansıdır?", answer: 46, xp: 10, explanation: "Sağ qonşu ədəddən 1 böyükdür: 45 + 1 = 46.", skills: ["number.count"] },
            { id: "ry2-yuzluk-l3-t6", type: "numeric", prompt: "20, 30, 40, ... — növbəti ədəd?", answer: 50, xp: 10, explanation: "Sıra hər dəfə 10 artır: 20, 30, 40. Deməli növbəti ədəd 40 + 10 = 50.", skills: ["number.sequence"] },
            { id: "ry2-yuzluk-l3-t7", type: "multiple_choice", prompt: "Ədədin sol qonşusu ondan neçə kiçikdir?", options: ["1", "2", "10", "5"], correctIndex: 0, xp: 10, explanation: "Sol qonşu ədəddən bir addım geridə durur, yəni ondan 1 kiçikdir.", skills: ["number.count"] },
            { id: "ry2-yuzluk-l3-t8", type: "numeric", prompt: "63-ün sol qonşusu hansıdır?", answer: 62, xp: 10, explanation: "Sol qonşu ədəddən 1 kiçikdir: 63 − 1 = 62.", skills: ["number.count"] },
            { id: "ry2-yuzluk-l3-t9", type: "numeric", prompt: "2, 4, 6, 8, ... — növbəti ədəd?", answer: 10, xp: 10, explanation: "Sıra hər dəfə 2 artır: 2, 4, 6, 8. Deməli növbəti ədəd 8 + 2 = 10.", skills: ["number.sequence"] },
            { id: "ry2-yuzluk-l3-t10", type: "numeric", prompt: "5, 10, 15, 20, ... — növbəti ədəd?", answer: 25, xp: 10, explanation: "Sıra hər dəfə 5 artır: 5, 10, 15, 20. Deməli növbəti ədəd 20 + 5 = 25.", skills: ["number.sequence"] },
          ],
          bonusTasks: [
            { id: "ry2-yuzluk-l3-b1", type: "numeric", prompt: "100, 90, 80, ... — növbəti ədəd?", answer: 70, xp: 15, explanation: "Sıra hər dəfə 10 azalır: 100, 90, 80. Deməli növbəti ədəd 80 − 10 = 70.", skills: ["number.sequence"] },
            { id: "ry2-yuzluk-l3-b2", type: "numeric", prompt: "3, 6, 9, 12, ... — növbəti ədəd?", answer: 15, xp: 15, explanation: "Sıra hər dəfə 3 artır: 3, 6, 9, 12. Deməli növbəti ədəd 12 + 3 = 15.", skills: ["number.sequence"] },
            { id: "ry2-yuzluk-l3-b3", type: "multiple_choice", prompt: "Hansı sırada ədədlər 10-la artır?", options: ["15, 25, 35", "15, 20, 25", "15, 16, 17", "15, 30, 45"], correctIndex: 0, xp: 15, explanation: "15 → 25 → 35 sırasında hər dəfə onluq 1 artır, yəni ədəd 10 böyüyür.", skills: ["number.count"] },
            { id: "ry2-yuzluk-l3-b4", type: "numeric", prompt: "58 və 62 arasında neçə ədəd var?", answer: 3, xp: 15, explanation: "58 ilə 62 arasındakı ədədləri sayaq: 59, 60, 61 — cəmi 3 dənə.", skills: ["number.count"] },
          ],
        },
        {
          id: "ry2-yuzluk-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry2-yuzluk-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 2. 100 dairəsində toplama ═══════════════
    {
      id: "ry2-toplama",
      title: "100 dairəsində toplama",
      description: "İkirəqəmli ədədləri toplamaq.",
      lessons: [
        {
          id: "ry2-toplama-l1",
          title: "Toplama",
          intro: "Onluqları onluqlara, təklikləri təkliklərə əlavə edirik.",
          sections: [
            { heading: "Toplama", body: "20 + 30 = 50 (onluqlar). 23 + 14 = 37 (əvvəl təkliklər 3+4=7, sonra onluqlar 20+10=30)." },
          ],
          tasks: [
            { id: "ry2-toplama-l1-t1", type: "numeric", prompt: "20 + 30 = ?", answer: 50, xp: 10, explanation: "Onluqları toplayırıq: 2 onluq + 3 onluq = 5 onluq, yəni 50.", skills: ["arith.add.no_carry"] },
            { id: "ry2-toplama-l1-t2", type: "numeric", prompt: "40 + 10 = ?", answer: 50, xp: 10, explanation: "Onluqları toplayırıq: 4 onluq + 1 onluq = 5 onluq, yəni 50.", skills: ["arith.add.no_carry"] },
            { id: "ry2-toplama-l1-t3", type: "numeric", prompt: "23 + 14 = ?", answer: 37, xp: 10, explanation: "Onluqlar: 20 + 10 = 30. Təkliklər: 3 + 4 = 7. Nəticə: 30 + 7 = 37.", skills: ["arith.add.no_carry"] },
            { id: "ry2-toplama-l1-t4", type: "numeric", prompt: "31 + 25 = ?", answer: 56, xp: 10, explanation: "Onluqlar: 30 + 20 = 50. Təkliklər: 1 + 5 = 6. Nəticə: 50 + 6 = 56.", skills: ["arith.add.no_carry"] },
            { id: "ry2-toplama-l1-t5", type: "numeric", prompt: "12 + 6 = ?", answer: 18, xp: 10, explanation: "Onluqlar: 10 + 0 = 10. Təkliklər: 2 + 6 = 8. Nəticə: 10 + 8 = 18.", skills: ["arith.add.no_carry"] },
            { id: "ry2-toplama-l1-t6", type: "numeric", prompt: "45 + 4 = ?", answer: 49, xp: 10, explanation: "Onluqlar: 40 + 0 = 40. Təkliklər: 5 + 4 = 9. Nəticə: 40 + 9 = 49.", skills: ["arith.add.no_carry"] },
            { id: "ry2-toplama-l1-t7", type: "numeric", prompt: "50 + 25 = ?", answer: 75, xp: 10, explanation: "Onluqlar: 50 + 20 = 70. Təkliklər: 0 + 5 = 5. Nəticə: 70 + 5 = 75.", skills: ["arith.add.no_carry"] },
            { id: "ry2-toplama-l1-t8", type: "numeric", prompt: "33 + 33 = ?", answer: 66, xp: 10, explanation: "Onluqlar: 30 + 30 = 60. Təkliklər: 3 + 3 = 6. Nəticə: 60 + 6 = 66.", skills: ["arith.add.no_carry"] },
            { id: "ry2-toplama-l1-t9", type: "numeric", prompt: "60 + 40 = ?", answer: 100, xp: 10, explanation: "Onluqları toplayırıq: 6 onluq + 4 onluq = 10 onluq, yəni 100.", skills: ["arith.add.carry"] },
            { id: "ry2-toplama-l1-t10", type: "numeric", prompt: "17 + 12 = ?", answer: 29, xp: 10, explanation: "Onluqlar: 10 + 10 = 20. Təkliklər: 7 + 2 = 9. Nəticə: 20 + 9 = 29.", skills: ["arith.add.no_carry"] },
            { id: "ry2-toplama-l1-t11", type: "numeric", prompt: "25 + 25 = ?", answer: 50, xp: 10, explanation: "Təkliklər: 5 + 5 = 10 — bu, 1 onluq və 0 təklik deməkdir. Onluqlar: 20 + 20 = 40, üstünə keçən onluqla 50. Nəticə: 50 + 0 = 50.", skills: ["arith.add.carry"] },
            { id: "ry2-toplama-l1-t12", type: "numeric", prompt: "44 + 15 = ?", answer: 59, xp: 10, explanation: "Onluqlar: 40 + 10 = 50. Təkliklər: 4 + 5 = 9. Nəticə: 50 + 9 = 59.", skills: ["arith.add.no_carry"] },
            { id: "ry2-toplama-l1-t13", type: "numeric", prompt: "70 + 20 = ?", answer: 90, xp: 10, explanation: "Onluqları toplayırıq: 7 onluq + 2 onluq = 9 onluq, yəni 90.", skills: ["arith.add.no_carry"] },
            { id: "ry2-toplama-l1-t14", type: "numeric", prompt: "36 + 12 = ?", answer: 48, xp: 10, explanation: "Onluqlar: 30 + 10 = 40. Təkliklər: 6 + 2 = 8. Nəticə: 40 + 8 = 48.", skills: ["arith.add.no_carry"] },
            { id: "ry2-toplama-l1-t15", type: "numeric", prompt: "28 + 30 = ?", answer: 58, xp: 15, explanation: "Onluqlar: 20 + 30 = 50. Təkliklər: 8 + 0 = 8. Nəticə: 50 + 8 = 58.", skills: ["arith.add.no_carry"] },
          ],
          bonusTasks: [
            { id: "ry2-toplama-l1-b1", type: "numeric", prompt: "27 + 15 = ? (təkliklər 7+5=12, keçidli)", answer: 42, xp: 15, explanation: "Təkliklər: 7 + 5 = 12 — bu, 1 onluq və 2 təklik deməkdir. Onluqlar: 20 + 10 = 30, üstünə keçən onluqla 40. Nəticə: 40 + 2 = 42.", skills: ["arith.order_of_ops","arith.add.carry"] },
            { id: "ry2-toplama-l1-b2", type: "numeric", prompt: "48 + 26 = ?", answer: 74, xp: 15, explanation: "Təkliklər: 8 + 6 = 14 — bu, 1 onluq və 4 təklik deməkdir. Onluqlar: 40 + 20 = 60, üstünə keçən onluqla 70. Nəticə: 70 + 4 = 74.", skills: ["arith.add.carry"] },
            { id: "ry2-toplama-l1-b3", type: "numeric", prompt: "55 + 45 = ?", answer: 100, xp: 15, explanation: "Təkliklər: 5 + 5 = 10 — bu, 1 onluq və 0 təklik deməkdir. Onluqlar: 50 + 40 = 90, üstünə keçən onluqla 100. Nəticə: 100 + 0 = 100.", skills: ["arith.add.carry"] },
            { id: "ry2-toplama-l1-b4", type: "numeric", prompt: "19 + 19 = ?", answer: 38, xp: 15, explanation: "Təkliklər: 9 + 9 = 18 — bu, 1 onluq və 8 təklik deməkdir. Onluqlar: 10 + 10 = 20, üstünə keçən onluqla 30. Nəticə: 30 + 8 = 38.", skills: ["arith.add.carry"] },
            { id: "ry2-toplama-l1-b5", type: "numeric", prompt: "34 + 29 = ?", answer: 63, xp: 15, explanation: "Təkliklər: 4 + 9 = 13 — bu, 1 onluq və 3 təklik deməkdir. Onluqlar: 30 + 20 = 50, üstünə keçən onluqla 60. Nəticə: 60 + 3 = 63.", skills: ["arith.add.carry"] },
          ],
        },
        {
          id: "ry2-toplama-l2",
          title: "Keçidsiz toplama",
          intro: "Təkliklərin cəmi 10-dan kiçik olanda toplama asandır.",
          sections: [
            { heading: "Addımlar", body: "34 + 25: əvvəl təklikləri topla (4 + 5 = 9), sonra onluqları (30 + 20 = 50). Cavab: 59." },
            { heading: "Yoxlama", body: "Toplama nəticəsini çıxma ilə yoxlaya bilərsən: 59 − 25 = 34. Düz alındısa, toplama doğrudur." },
          ],
          tasks: [
            { id: "ry2-toplama-l2-t1", type: "numeric", prompt: "34 + 25 = ?", answer: 59, xp: 10, explanation: "Onluqlar: 30 + 20 = 50. Təkliklər: 4 + 5 = 9. Nəticə: 50 + 9 = 59.", skills: ["arith.add.no_carry"] },
            { id: "ry2-toplama-l2-t2", type: "numeric", prompt: "42 + 36 = ?", answer: 78, xp: 10, explanation: "Onluqlar: 40 + 30 = 70. Təkliklər: 2 + 6 = 8. Nəticə: 70 + 8 = 78.", skills: ["arith.add.no_carry"] },
            { id: "ry2-toplama-l2-t3", type: "numeric", prompt: "51 + 27 = ?", answer: 78, xp: 10, explanation: "Onluqlar: 50 + 20 = 70. Təkliklər: 1 + 7 = 8. Nəticə: 70 + 8 = 78.", skills: ["arith.add.no_carry"] },
            { id: "ry2-toplama-l2-t4", type: "numeric", prompt: "23 + 45 = ?", answer: 68, xp: 10, explanation: "Onluqlar: 20 + 40 = 60. Təkliklər: 3 + 5 = 8. Nəticə: 60 + 8 = 68.", skills: ["arith.add.no_carry"] },
            { id: "ry2-toplama-l2-t5", type: "numeric", prompt: "60 + 15 = ?", answer: 75, xp: 10, explanation: "Onluqlar: 60 + 10 = 70. Təkliklər: 0 + 5 = 5. Nəticə: 70 + 5 = 75.", skills: ["arith.add.no_carry"] },
            { id: "ry2-toplama-l2-t6", type: "numeric", prompt: "17 + 22 = ?", answer: 39, xp: 10, explanation: "Onluqlar: 10 + 20 = 30. Təkliklər: 7 + 2 = 9. Nəticə: 30 + 9 = 39.", skills: ["arith.add.no_carry"] },
            { id: "ry2-toplama-l2-t7", type: "numeric", prompt: "45 + 33 = ?", answer: 78, xp: 10, explanation: "Onluqlar: 40 + 30 = 70. Təkliklər: 5 + 3 = 8. Nəticə: 70 + 8 = 78.", skills: ["arith.add.no_carry"] },
            { id: "ry2-toplama-l2-t8", type: "multiple_choice", prompt: "Toplamanı hansı əməllə yoxlamaq olar?", options: ["Çıxma", "Vurma", "Bölmə", "Müqayisə"], correctIndex: 0, xp: 10, explanation: "Cəmdən toplananlardan birini çıxsaq, digəri alınmalıdır — ona görə toplama çıxma ilə yoxlanır.", skills: ["arith.inverse"] },
            { id: "ry2-toplama-l2-t9", type: "numeric", prompt: "31 + 8 = ?", answer: 39, xp: 10, explanation: "Onluqlar: 30 + 0 = 30. Təkliklər: 1 + 8 = 9. Nəticə: 30 + 9 = 39.", skills: ["arith.add.no_carry"] },
            { id: "ry2-toplama-l2-t10", type: "numeric", prompt: "26 + 12 = ?", answer: 38, xp: 10, explanation: "Onluqlar: 20 + 10 = 30. Təkliklər: 6 + 2 = 8. Nəticə: 30 + 8 = 38.", skills: ["arith.add.no_carry"] },
          ],
          bonusTasks: [
            { id: "ry2-toplama-l2-b1", type: "numeric", prompt: "Aysel 23 ₼, Nihad 45 ₼ yığıb. Birlikdə neçə manat?", answer: 68, xp: 15, explanation: "«Birlikdə» toplama deməkdir: 23 + 45 = 68 manat.", skills: ["measure.money","problem.one_step","arith.add.no_carry"] },
            { id: "ry2-toplama-l2-b2", type: "numeric", prompt: "12 + 23 + 14 = ?", answer: 49, xp: 15, explanation: "Soldan sağa toplayırıq: əvvəl 12 + 23 = 35, sonra 35 + 14 = 49.", skills: ["arith.add.no_carry"] },
            { id: "ry2-toplama-l2-b3", type: "numeric", prompt: "? + 24 = 46 — buraya hansı ədəd gəlir?", answer: 22, xp: 15, explanation: "Naməlum toplananı tapmaq üçün cəmdən məlum toplananı çıxırıq: 46 − 24 = 22.", skills: ["arith.inverse"] },
            { id: "ry2-toplama-l2-b4", type: "numeric", prompt: "35 + 41 = ?", answer: 76, xp: 15, explanation: "Onluqlar: 30 + 40 = 70. Təkliklər: 5 + 1 = 6. Nəticə: 70 + 6 = 76.", skills: ["arith.add.no_carry"] },
          ],
        },
        {
          id: "ry2-toplama-l3",
          title: "Keçidli toplama",
          intro: "Təkliklərin cəmi 10-u keçəndə bir onluq yuxarı keçir.",
          sections: [
            { heading: "Keçid nədir?", body: "27 + 15: təkliklər 7 + 5 = 12. 12-nin içində BİR onluq var — onu onluqlara ötürürük. Onluqlar: 20 + 10 + 10 = 40, təklik 2 qalır. Cavab: 42." },
            { heading: "Asan yol", body: "Əvvəl 10-a tamamla: 27 + 3 = 30, sonra qalan 12-dən 3 çıxıb 12-yə çatdır... yəni 30 + 12 = 42." },
          ],
          tasks: [
            { id: "ry2-toplama-l3-t1", type: "numeric", prompt: "27 + 15 = ?", answer: 42, xp: 10, explanation: "Təkliklər: 7 + 5 = 12 — bu, 1 onluq və 2 təklik deməkdir. Onluqlar: 20 + 10 = 30, üstünə keçən onluqla 40. Nəticə: 40 + 2 = 42.", skills: ["arith.add.carry"] },
            { id: "ry2-toplama-l3-t2", type: "numeric", prompt: "38 + 24 = ?", answer: 62, xp: 10, explanation: "Təkliklər: 8 + 4 = 12 — bu, 1 onluq və 2 təklik deməkdir. Onluqlar: 30 + 20 = 50, üstünə keçən onluqla 60. Nəticə: 60 + 2 = 62.", skills: ["arith.add.carry"] },
            { id: "ry2-toplama-l3-t3", type: "numeric", prompt: "46 + 19 = ?", answer: 65, xp: 10, explanation: "Təkliklər: 6 + 9 = 15 — bu, 1 onluq və 5 təklik deməkdir. Onluqlar: 40 + 10 = 50, üstünə keçən onluqla 60. Nəticə: 60 + 5 = 65.", skills: ["arith.add.carry"] },
            { id: "ry2-toplama-l3-t4", type: "numeric", prompt: "55 + 28 = ?", answer: 83, xp: 10, explanation: "Təkliklər: 5 + 8 = 13 — bu, 1 onluq və 3 təklik deməkdir. Onluqlar: 50 + 20 = 70, üstünə keçən onluqla 80. Nəticə: 80 + 3 = 83.", skills: ["arith.add.carry"] },
            { id: "ry2-toplama-l3-t5", type: "numeric", prompt: "17 + 18 = ?", answer: 35, xp: 10, explanation: "Təkliklər: 7 + 8 = 15 — bu, 1 onluq və 5 təklik deməkdir. Onluqlar: 10 + 10 = 20, üstünə keçən onluqla 30. Nəticə: 30 + 5 = 35.", skills: ["arith.add.carry"] },
            { id: "ry2-toplama-l3-t6", type: "numeric", prompt: "29 + 36 = ?", answer: 65, xp: 10, explanation: "Təkliklər: 9 + 6 = 15 — bu, 1 onluq və 5 təklik deməkdir. Onluqlar: 20 + 30 = 50, üstünə keçən onluqla 60. Nəticə: 60 + 5 = 65.", skills: ["arith.add.carry"] },
            { id: "ry2-toplama-l3-t7", type: "numeric", prompt: "48 + 27 = ?", answer: 75, xp: 10, explanation: "Təkliklər: 8 + 7 = 15 — bu, 1 onluq və 5 təklik deməkdir. Onluqlar: 40 + 20 = 60, üstünə keçən onluqla 70. Nəticə: 70 + 5 = 75.", skills: ["arith.add.carry"] },
            { id: "ry2-toplama-l3-t8", type: "numeric", prompt: "9 + 8 = ?", answer: 17, xp: 10, explanation: "Əvvəl 10-u tamamlayırıq: 9 + 1 = 10. 8-dən qalan 7 isə üstünə gəlir: 10 + 7 = 17.", skills: ["arith.add.basic"] },
            { id: "ry2-toplama-l3-t9", type: "multiple_choice", prompt: "Təkliklərin cəmi 10-u keçəndə nə baş verir?", options: ["Bir onluq yuxarı keçir", "Heç nə", "Bir onluq itir", "Cavab sıfır olur"], correctIndex: 0, xp: 10, explanation: "Hər 10 təklik 1 onluq edir. Təkliklərin cəmi 10-u keçəndə həmin onluq onluqlar mərtəbəsinə keçir.", skills: ["arith.add.carry"] },
            { id: "ry2-toplama-l3-t10", type: "numeric", prompt: "63 + 29 = ?", answer: 92, xp: 10, explanation: "Təkliklər: 3 + 9 = 12 — bu, 1 onluq və 2 təklik deməkdir. Onluqlar: 60 + 20 = 80, üstünə keçən onluqla 90. Nəticə: 90 + 2 = 92.", skills: ["arith.add.carry"] },
          ],
          bonusTasks: [
            { id: "ry2-toplama-l3-b1", type: "numeric", prompt: "Kitabxanada 47 kitab var idi, 38 kitab da gətirdilər. Neçə kitab oldu?", answer: 85, xp: 15, explanation: "«Gətirdilər» artım deməkdir: 47 + 38 = 85 kitab.", skills: ["problem.one_step","arith.add.carry"] },
            { id: "ry2-toplama-l3-b2", type: "numeric", prompt: "25 + 19 + 16 = ?", answer: 60, xp: 15, explanation: "Soldan sağa toplayırıq: əvvəl 25 + 19 = 44, sonra 44 + 16 = 60.", skills: ["arith.add.carry"] },
            { id: "ry2-toplama-l3-b3", type: "numeric", prompt: "34 + ? = 71 — buraya hansı ədəd gəlir?", answer: 37, xp: 15, explanation: "Naməlum toplananı tapmaq üçün cəmdən məlum toplananı çıxırıq: 71 − 34 = 37.", skills: ["arith.inverse"] },
            { id: "ry2-toplama-l3-b4", type: "numeric", prompt: "56 + 37 = ?", answer: 93, xp: 15, explanation: "Təkliklər: 6 + 7 = 13 — bu, 1 onluq və 3 təklik deməkdir. Onluqlar: 50 + 30 = 80, üstünə keçən onluqla 90. Nəticə: 90 + 3 = 93.", skills: ["arith.add.carry"] },
          ],
        },
        {
          id: "ry2-toplama-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry2-toplama-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 3. 100 dairəsində çıxma ═══════════════
    {
      id: "ry2-cixma",
      title: "100 dairəsində çıxma",
      description: "İkirəqəmli ədədlərdən çıxmaq.",
      lessons: [
        {
          id: "ry2-cixma-l1",
          title: "Çıxma",
          intro: "Onluqlardan onluqları, təkliklərdən təklikləri çıxırıq.",
          sections: [
            { heading: "Çıxma", body: "50 − 20 = 30 (onluqlar). 37 − 14 = 23 (təkliklər 7−4=3, onluqlar 30−10=20)." },
          ],
          tasks: [
            { id: "ry2-cixma-l1-t1", type: "numeric", prompt: "50 − 20 = ?", answer: 30, xp: 10, explanation: "Onluqları çıxırıq: 5 onluq − 2 onluq = 3 onluq, yəni 30.", skills: ["arith.sub.no_borrow"] },
            { id: "ry2-cixma-l1-t2", type: "numeric", prompt: "60 − 40 = ?", answer: 20, xp: 10, explanation: "Onluqları çıxırıq: 6 onluq − 4 onluq = 2 onluq, yəni 20.", skills: ["arith.sub.no_borrow"] },
            { id: "ry2-cixma-l1-t3", type: "numeric", prompt: "37 − 14 = ?", answer: 23, xp: 10, explanation: "Onluqlar: 30 − 10 = 20. Təkliklər: 7 − 4 = 3. Nəticə: 20 + 3 = 23.", skills: ["arith.sub.no_borrow"] },
            { id: "ry2-cixma-l1-t4", type: "numeric", prompt: "56 − 25 = ?", answer: 31, xp: 10, explanation: "Onluqlar: 50 − 20 = 30. Təkliklər: 6 − 5 = 1. Nəticə: 30 + 1 = 31.", skills: ["arith.sub.no_borrow"] },
            { id: "ry2-cixma-l1-t5", type: "numeric", prompt: "18 − 6 = ?", answer: 12, xp: 10, explanation: "18-dən 6 çıxırıq: 18 − 6 = 12.", skills: ["arith.sub.basic"] },
            { id: "ry2-cixma-l1-t6", type: "numeric", prompt: "49 − 4 = ?", answer: 45, xp: 10, explanation: "Onluqlar: 40 − 0 = 40. Təkliklər: 9 − 4 = 5. Nəticə: 40 + 5 = 45.", skills: ["arith.sub.no_borrow"] },
            { id: "ry2-cixma-l1-t7", type: "numeric", prompt: "75 − 25 = ?", answer: 50, xp: 10, explanation: "Onluqlar: 70 − 20 = 50. Təkliklər: 5 − 5 = 0. Nəticə: 50 + 0 = 50.", skills: ["arith.sub.no_borrow"] },
            { id: "ry2-cixma-l1-t8", type: "numeric", prompt: "66 − 33 = ?", answer: 33, xp: 10, explanation: "Onluqlar: 60 − 30 = 30. Təkliklər: 6 − 3 = 3. Nəticə: 30 + 3 = 33.", skills: ["arith.sub.no_borrow"] },
            { id: "ry2-cixma-l1-t9", type: "numeric", prompt: "100 − 50 = ?", answer: 50, xp: 10, explanation: "Onluqları çıxırıq: 10 onluq − 5 onluq = 5 onluq, yəni 50.", skills: ["arith.sub.borrow"] },
            { id: "ry2-cixma-l1-t10", type: "numeric", prompt: "29 − 12 = ?", answer: 17, xp: 10, explanation: "Onluqlar: 20 − 10 = 10. Təkliklər: 9 − 2 = 7. Nəticə: 10 + 7 = 17.", skills: ["arith.sub.no_borrow"] },
            { id: "ry2-cixma-l1-t11", type: "numeric", prompt: "40 − 15 = ?", answer: 25, xp: 10, explanation: "Təkliklər çatmır (0 < 5), ona görə bir onluğu açırıq: 10 − 5 = 5. Onluqlar: 30 − 10 = 20. Nəticə: 20 + 5 = 25.", skills: ["arith.sub.borrow"] },
            { id: "ry2-cixma-l1-t12", type: "numeric", prompt: "59 − 15 = ?", answer: 44, xp: 10, explanation: "Onluqlar: 50 − 10 = 40. Təkliklər: 9 − 5 = 4. Nəticə: 40 + 4 = 44.", skills: ["arith.sub.no_borrow"] },
            { id: "ry2-cixma-l1-t13", type: "numeric", prompt: "90 − 20 = ?", answer: 70, xp: 10, explanation: "Onluqları çıxırıq: 9 onluq − 2 onluq = 7 onluq, yəni 70.", skills: ["arith.sub.no_borrow"] },
            { id: "ry2-cixma-l1-t14", type: "numeric", prompt: "48 − 12 = ?", answer: 36, xp: 10, explanation: "Onluqlar: 40 − 10 = 30. Təkliklər: 8 − 2 = 6. Nəticə: 30 + 6 = 36.", skills: ["arith.sub.no_borrow"] },
            { id: "ry2-cixma-l1-t15", type: "numeric", prompt: "58 − 30 = ?", answer: 28, xp: 15, explanation: "Onluqlar: 50 − 30 = 20. Təkliklər: 8 − 0 = 8. Nəticə: 20 + 8 = 28.", skills: ["arith.sub.no_borrow"] },
          ],
          bonusTasks: [
            { id: "ry2-cixma-l1-b1", type: "numeric", prompt: "42 − 15 = ? (keçidli)", answer: 27, xp: 15, explanation: "Təkliklər çatmır (2 < 5), ona görə bir onluğu açırıq: 12 − 5 = 7. Onluqlar: 30 − 10 = 20. Nəticə: 20 + 7 = 27.", skills: ["arith.sub.borrow"] },
            { id: "ry2-cixma-l1-b2", type: "numeric", prompt: "74 − 26 = ?", answer: 48, xp: 15, explanation: "Təkliklər çatmır (4 < 6), ona görə bir onluğu açırıq: 14 − 6 = 8. Onluqlar: 60 − 20 = 40. Nəticə: 40 + 8 = 48.", skills: ["arith.sub.borrow"] },
            { id: "ry2-cixma-l1-b3", type: "numeric", prompt: "100 − 45 = ?", answer: 55, xp: 15, explanation: "Təkliklər çatmır (0 < 5), ona görə bir onluğu açırıq: 10 − 5 = 5. Onluqlar: 90 − 40 = 50. Nəticə: 50 + 5 = 55.", skills: ["arith.sub.borrow"] },
            { id: "ry2-cixma-l1-b4", type: "numeric", prompt: "38 − 19 = ?", answer: 19, xp: 15, explanation: "Təkliklər çatmır (8 < 9), ona görə bir onluğu açırıq: 18 − 9 = 9. Onluqlar: 20 − 10 = 10. Nəticə: 10 + 9 = 19.", skills: ["arith.sub.borrow"] },
            { id: "ry2-cixma-l1-b5", type: "numeric", prompt: "63 − 29 = ?", answer: 34, xp: 15, explanation: "Təkliklər çatmır (3 < 9), ona görə bir onluğu açırıq: 13 − 9 = 4. Onluqlar: 50 − 20 = 30. Nəticə: 30 + 4 = 34.", skills: ["arith.sub.borrow"] },
          ],
        },
        {
          id: "ry2-cixma-l2",
          title: "Keçidsiz çıxma",
          intro: "Yuxarıdakı təklik aşağıdakından böyükdürsə, çıxma asandır.",
          sections: [
            { heading: "Addımlar", body: "58 − 23: əvvəl təklikləri çıx (8 − 3 = 5), sonra onluqları (50 − 20 = 30). Cavab: 35." },
            { heading: "Yoxlama", body: "Çıxmanı toplama ilə yoxla: 35 + 23 = 58. Alınırsa, çıxma doğrudur." },
          ],
          tasks: [
            { id: "ry2-cixma-l2-t1", type: "numeric", prompt: "58 − 23 = ?", answer: 35, xp: 10, explanation: "Onluqlar: 50 − 20 = 30. Təkliklər: 8 − 3 = 5. Nəticə: 30 + 5 = 35.", skills: ["arith.sub.no_borrow"] },
            { id: "ry2-cixma-l2-t2", type: "numeric", prompt: "76 − 41 = ?", answer: 35, xp: 10, explanation: "Onluqlar: 70 − 40 = 30. Təkliklər: 6 − 1 = 5. Nəticə: 30 + 5 = 35.", skills: ["arith.sub.no_borrow"] },
            { id: "ry2-cixma-l2-t3", type: "numeric", prompt: "89 − 27 = ?", answer: 62, xp: 10, explanation: "Onluqlar: 80 − 20 = 60. Təkliklər: 9 − 7 = 2. Nəticə: 60 + 2 = 62.", skills: ["arith.sub.no_borrow"] },
            { id: "ry2-cixma-l2-t4", type: "numeric", prompt: "45 − 12 = ?", answer: 33, xp: 10, explanation: "Onluqlar: 40 − 10 = 30. Təkliklər: 5 − 2 = 3. Nəticə: 30 + 3 = 33.", skills: ["arith.sub.no_borrow"] },
            { id: "ry2-cixma-l2-t5", type: "numeric", prompt: "67 − 34 = ?", answer: 33, xp: 10, explanation: "Onluqlar: 60 − 30 = 30. Təkliklər: 7 − 4 = 3. Nəticə: 30 + 3 = 33.", skills: ["arith.sub.no_borrow"] },
            { id: "ry2-cixma-l2-t6", type: "numeric", prompt: "90 − 40 = ?", answer: 50, xp: 10, explanation: "Onluqları çıxırıq: 9 onluq − 4 onluq = 5 onluq, yəni 50.", skills: ["arith.sub.no_borrow"] },
            { id: "ry2-cixma-l2-t7", type: "numeric", prompt: "38 − 15 = ?", answer: 23, xp: 10, explanation: "Onluqlar: 30 − 10 = 20. Təkliklər: 8 − 5 = 3. Nəticə: 20 + 3 = 23.", skills: ["arith.sub.no_borrow"] },
            { id: "ry2-cixma-l2-t8", type: "multiple_choice", prompt: "Çıxmanı hansı əməllə yoxlamaq olar?", options: ["Toplama", "Vurma", "Bölmə", "Müqayisə"], correctIndex: 0, xp: 10, explanation: "Fərqin üstünə çıxılanı əlavə etsək, azalan alınmalıdır — ona görə çıxma toplama ilə yoxlanır.", skills: ["arith.inverse"] },
            { id: "ry2-cixma-l2-t9", type: "numeric", prompt: "99 − 55 = ?", answer: 44, xp: 10, explanation: "Onluqlar: 90 − 50 = 40. Təkliklər: 9 − 5 = 4. Nəticə: 40 + 4 = 44.", skills: ["arith.sub.no_borrow"] },
            { id: "ry2-cixma-l2-t10", type: "numeric", prompt: "64 − 21 = ?", answer: 43, xp: 10, explanation: "Onluqlar: 60 − 20 = 40. Təkliklər: 4 − 1 = 3. Nəticə: 40 + 3 = 43.", skills: ["arith.sub.no_borrow"] },
          ],
          bonusTasks: [
            { id: "ry2-cixma-l2-b1", type: "numeric", prompt: "Avtobusda 46 sərnişin var idi, 23-ü düşdü. Neçə nəfər qaldı?", answer: 23, xp: 15, explanation: "«Düşdü» azalma deməkdir: 46 − 23 = 23 sərnişin qaldı.", skills: ["problem.one_step","arith.sub.no_borrow"] },
            { id: "ry2-cixma-l2-b2", type: "numeric", prompt: "87 − 25 − 12 = ?", answer: 50, xp: 15, explanation: "Soldan sağa çıxırıq: əvvəl 87 − 25 = 62, sonra 62 − 12 = 50.", skills: ["arith.sub.no_borrow"] },
            { id: "ry2-cixma-l2-b3", type: "numeric", prompt: "? − 24 = 35 — buraya hansı ədəd gəlir?", answer: 59, xp: 15, explanation: "Azalanı tapmaq üçün fərqlə çıxılanı toplayırıq: 35 + 24 = 59.", skills: ["arith.inverse"] },
            { id: "ry2-cixma-l2-b4", type: "numeric", prompt: "78 − 43 = ?", answer: 35, xp: 15, explanation: "Onluqlar: 70 − 40 = 30. Təkliklər: 8 − 3 = 5. Nəticə: 30 + 5 = 35.", skills: ["arith.sub.no_borrow"] },
          ],
        },
        {
          id: "ry2-cixma-l3",
          title: "Keçidli çıxma",
          intro: "Təklik çatmayanda bir onluğu sındırıb 10 təklik alırıq.",
          sections: [
            { heading: "Onluğu sındır", body: "52 − 27: təkliklərdə 2-dən 7 çıxmır. Bir onluğu sındırırıq: 52 = 40 + 12. İndi 12 − 7 = 5, onluqlarda 40 − 20 = 20. Cavab: 25." },
            { heading: "Nə vaxt lazımdır?", body: "Yuxarıdakı təklik aşağıdakından KİÇİKDİRSƏ — onda onluq sındırılır." },
          ],
          tasks: [
            { id: "ry2-cixma-l3-t1", type: "numeric", prompt: "52 − 27 = ?", answer: 25, xp: 10, explanation: "Təkliklər çatmır (2 < 7), ona görə bir onluğu açırıq: 12 − 7 = 5. Onluqlar: 40 − 20 = 20. Nəticə: 20 + 5 = 25.", skills: ["arith.sub.borrow"] },
            { id: "ry2-cixma-l3-t2", type: "numeric", prompt: "63 − 38 = ?", answer: 25, xp: 10, explanation: "Təkliklər çatmır (3 < 8), ona görə bir onluğu açırıq: 13 − 8 = 5. Onluqlar: 50 − 30 = 20. Nəticə: 20 + 5 = 25.", skills: ["arith.sub.borrow"] },
            { id: "ry2-cixma-l3-t3", type: "numeric", prompt: "71 − 46 = ?", answer: 25, xp: 10, explanation: "Təkliklər çatmır (1 < 6), ona görə bir onluğu açırıq: 11 − 6 = 5. Onluqlar: 60 − 40 = 20. Nəticə: 20 + 5 = 25.", skills: ["arith.sub.borrow"] },
            { id: "ry2-cixma-l3-t4", type: "numeric", prompt: "40 − 18 = ?", answer: 22, xp: 10, explanation: "Təkliklər çatmır (0 < 8), ona görə bir onluğu açırıq: 10 − 8 = 2. Onluqlar: 30 − 10 = 20. Nəticə: 20 + 2 = 22.", skills: ["arith.sub.borrow"] },
            { id: "ry2-cixma-l3-t5", type: "numeric", prompt: "85 − 29 = ?", answer: 56, xp: 10, explanation: "Təkliklər çatmır (5 < 9), ona görə bir onluğu açırıq: 15 − 9 = 6. Onluqlar: 70 − 20 = 50. Nəticə: 50 + 6 = 56.", skills: ["arith.sub.borrow"] },
            { id: "ry2-cixma-l3-t6", type: "numeric", prompt: "34 − 17 = ?", answer: 17, xp: 10, explanation: "Təkliklər çatmır (4 < 7), ona görə bir onluğu açırıq: 14 − 7 = 7. Onluqlar: 20 − 10 = 10. Nəticə: 10 + 7 = 17.", skills: ["arith.sub.borrow"] },
            { id: "ry2-cixma-l3-t7", type: "numeric", prompt: "100 − 45 = ?", answer: 55, xp: 10, explanation: "Təkliklər çatmır (0 < 5), ona görə bir onluğu açırıq: 10 − 5 = 5. Onluqlar: 90 − 40 = 50. Nəticə: 50 + 5 = 55.", skills: ["arith.sub.borrow"] },
            { id: "ry2-cixma-l3-t8", type: "multiple_choice", prompt: "Onluq nə vaxt sındırılır?", options: ["Yuxarıdakı təklik kiçik olanda", "Həmişə", "Heç vaxt", "Cavab böyük olanda"], correctIndex: 0, xp: 10, explanation: "Azalanın təkliyi çıxılanın təkliyindən kiçik olanda təkliklər çatmır — məhz onda bir onluq sındırılıb 10 təkliyə çevrilir.", skills: ["arith.sub.borrow"] },
            { id: "ry2-cixma-l3-t9", type: "numeric", prompt: "56 − 19 = ?", answer: 37, xp: 10, explanation: "Təkliklər çatmır (6 < 9), ona görə bir onluğu açırıq: 16 − 9 = 7. Onluqlar: 40 − 10 = 30. Nəticə: 30 + 7 = 37.", skills: ["arith.sub.borrow"] },
            { id: "ry2-cixma-l3-t10", type: "numeric", prompt: "92 − 58 = ?", answer: 34, xp: 10, explanation: "Təkliklər çatmır (2 < 8), ona görə bir onluğu açırıq: 12 − 8 = 4. Onluqlar: 80 − 50 = 30. Nəticə: 30 + 4 = 34.", skills: ["arith.sub.borrow"] },
          ],
          bonusTasks: [
            { id: "ry2-cixma-l3-b1", type: "numeric", prompt: "Bağçada 63 ağac var idi, 28-i köçürüldü. Neçə ağac qaldı?", answer: 35, xp: 15, explanation: "«Köçürüldü» azalma deməkdir: 63 − 28 = 35 ağac qaldı.", skills: ["problem.one_step","arith.sub.borrow"] },
            { id: "ry2-cixma-l3-b2", type: "numeric", prompt: "80 − 35 − 16 = ?", answer: 29, xp: 15, explanation: "Soldan sağa çıxırıq: əvvəl 80 − 35 = 45, sonra 45 − 16 = 29.", skills: ["arith.sub.borrow"] },
            { id: "ry2-cixma-l3-b3", type: "numeric", prompt: "74 − ? = 39 — buraya hansı ədəd gəlir?", answer: 35, xp: 15, explanation: "Çıxılanı tapmaq üçün azalandan fərqi çıxırıq: 74 − 39 = 35.", skills: ["arith.inverse"] },
            { id: "ry2-cixma-l3-b4", type: "numeric", prompt: "41 + 29 − 30 = ?", answer: 40, xp: 15, explanation: "Soldan sağa hesablayırıq: əvvəl 41 + 29 = 70, sonra 70 − 30 = 40.", skills: ["arith.sub.borrow"] },
          ],
        },
        {
          id: "ry2-cixma-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry2-cixma-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 4. Vurma ═══════════════
    {
      id: "ry2-vurma",
      title: "Vurma (2, 3, 4, 5)",
      description: "Vurma cədvəlinin başlanğıcı: 2, 3, 4, 5 ilə vurma.",
      lessons: [
        {
          id: "ry2-vurma-l1",
          title: "Vurma nədir?",
          intro: "Vurma — eyni ədədin təkrar toplanmasıdır. 3 × 2 = 2 + 2 + 2 = 6.",
          sections: [
            { heading: "Vurma", body: "3 × 2 o deməkdir ki, 2-ni 3 dəfə toplayırıq: 2 + 2 + 2 = 6. Yəni 3 × 2 = 6." },
            { heading: "5 cədvəli", body: "5 × 1 = 5, 5 × 2 = 10, 5 × 3 = 15, 5 × 4 = 20, 5 × 5 = 25." },
          ],
          tasks: [
            { id: "ry2-vurma-l1-t1", type: "numeric", prompt: "2 × 2 = ?", answer: 4, xp: 10, explanation: "2 × 2 — 2-ni 2 dəfə toplamaq deməkdir: 2 + 2 = 4.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l1-t2", type: "numeric", prompt: "2 × 3 = ?", answer: 6, xp: 10, explanation: "2 × 3 — 3-ü 2 dəfə toplamaq deməkdir: 3 + 3 = 6.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l1-t3", type: "numeric", prompt: "2 × 5 = ?", answer: 10, xp: 10, explanation: "2 × 5 — 5-i 2 dəfə toplamaq deməkdir: 5 + 5 = 10.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l1-t4", type: "numeric", prompt: "3 × 3 = ?", answer: 9, xp: 10, explanation: "3 × 3 — 3-ü 3 dəfə toplamaq deməkdir: 3 + 3 + 3 = 9.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l1-t5", type: "numeric", prompt: "3 × 4 = ?", answer: 12, xp: 10, explanation: "3 × 4 — 4-ü 3 dəfə toplamaq deməkdir: 4 + 4 + 4 = 12.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l1-t6", type: "numeric", prompt: "4 × 2 = ?", answer: 8, xp: 10, explanation: "4 × 2 — 2-ni 4 dəfə toplamaq deməkdir: 2 + 2 + 2 + 2 = 8.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l1-t7", type: "numeric", prompt: "4 × 5 = ?", answer: 20, xp: 10, explanation: "4 × 5 — 5-i 4 dəfə toplamaq deməkdir: 5 + 5 + 5 + 5 = 20.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l1-t8", type: "numeric", prompt: "5 × 2 = ?", answer: 10, xp: 10, explanation: "5 × 2 — 2-ni 5 dəfə toplamaq deməkdir: 2 + 2 + 2 + 2 + 2 = 10.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l1-t9", type: "numeric", prompt: "5 × 5 = ?", answer: 25, xp: 10, explanation: "5 × 5 — 5-i 5 dəfə toplamaq deməkdir: 5 + 5 + 5 + 5 + 5 = 25.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l1-t10", type: "numeric", prompt: "5 × 4 = ?", answer: 20, xp: 10, explanation: "5 × 4 — 4-ü 5 dəfə toplamaq deməkdir: 4 + 4 + 4 + 4 + 4 = 20.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l1-t11", type: "numeric", prompt: "2 + 2 + 2 + 2 neçə edir? (4 × 2)", answer: 8, xp: 10, explanation: "Burada 2 dörd dəfə təkrarlanır, bu isə 4 × 2 = 8 deməkdir.", skills: ["arith.mul.concept"] },
            { id: "ry2-vurma-l1-t12", type: "numeric", prompt: "3 × 5 = ?", answer: 15, xp: 10, explanation: "3 × 5 — 5-i 3 dəfə toplamaq deməkdir: 5 + 5 + 5 = 15.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l1-t13", type: "numeric", prompt: "4 × 4 = ?", answer: 16, xp: 10, explanation: "4 × 4 — 4-ü 4 dəfə toplamaq deməkdir: 4 + 4 + 4 + 4 = 16.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l1-t14", type: "numeric", prompt: "2 × 1 = ?", answer: 2, xp: 10, explanation: "2 × 1 — 1-i 2 dəfə toplamaq deməkdir: 1 + 1 = 2.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l1-t15", type: "numeric", prompt: "5 × 3 = ?", answer: 15, xp: 15, explanation: "5 × 3 — 3-ü 5 dəfə toplamaq deməkdir: 3 + 3 + 3 + 3 + 3 = 15.", skills: ["arith.mul.tables"] },
          ],
          bonusTasks: [
            { id: "ry2-vurma-l1-b1", type: "numeric", prompt: "5 × 6 = ?", answer: 30, xp: 15, explanation: "5 × 6 — 6-nı 5 dəfə toplamaq deməkdir: 6 + 6 + 6 + 6 + 6 = 30.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l1-b2", type: "numeric", prompt: "4 × 6 = ?", answer: 24, xp: 15, explanation: "4 × 6 — 6-nı 4 dəfə toplamaq deməkdir: 6 + 6 + 6 + 6 = 24.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l1-b3", type: "numeric", prompt: "3 × 6 = ?", answer: 18, xp: 15, explanation: "3 × 6 — 6-nı 3 dəfə toplamaq deməkdir: 6 + 6 + 6 = 18.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l1-b4", type: "numeric", prompt: "2 × 8 = ?", answer: 16, xp: 15, explanation: "2 × 8 — 8-i 2 dəfə toplamaq deməkdir: 8 + 8 = 16.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l1-b5", type: "numeric", prompt: "Hər səbətdə 5 alma var. 3 səbətdə neçə alma var?", answer: 15, xp: 15, explanation: "Hər səbətdəki 5 alma 3 dəfə təkrarlanır: 3 × 5 = 15.", skills: ["problem.one_step","arith.mul.tables"] },
          ],
        },
        {
          id: "ry2-vurma-l2",
          title: "2 və 5 ilə vurma",
          intro: "Ən asan iki cədvəl: 2-yə vurmaq ikiqat, 5-ə vurmaq beş-beş saymaqdır.",
          sections: [
            { heading: "2 ilə vurma", body: "Bir ədədi 2-yə vurmaq — onu ÖZÜNƏ toplamaqdır. 7 × 2 = 7 + 7 = 14." },
            { heading: "5 ilə vurma", body: "5-ə vurulan ədədin sonu ya 0, ya 5 olur: 5, 10, 15, 20, 25, 30..." },
          ],
          tasks: [
            { id: "ry2-vurma-l2-t1", type: "numeric", prompt: "7 × 2 = ?", answer: 14, xp: 10, explanation: "7 × 2 — 7-ni 2 dəfə toplamaq deməkdir: 7 + 7 = 14.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l2-t2", type: "numeric", prompt: "9 × 2 = ?", answer: 18, xp: 10, explanation: "9 × 2 — 9-u 2 dəfə toplamaq deməkdir: 9 + 9 = 18.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l2-t3", type: "numeric", prompt: "6 × 5 = ?", answer: 30, xp: 10, explanation: "6 × 5 — 6-nı 5 dəfə toplamaq deməkdir: 6 + 6 + 6 + 6 + 6 = 30.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l2-t4", type: "numeric", prompt: "8 × 5 = ?", answer: 40, xp: 10, explanation: "8 × 5 — 8-i 5 dəfə toplamaq deməkdir: 8 + 8 + 8 + 8 + 8 = 40.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l2-t5", type: "numeric", prompt: "4 × 2 = ?", answer: 8, xp: 10, explanation: "4 × 2 — 2-ni 4 dəfə toplamaq deməkdir: 2 + 2 + 2 + 2 = 8.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l2-t6", type: "numeric", prompt: "10 × 5 = ?", answer: 50, xp: 10, explanation: "10 × 5 — 10-u 5 dəfə toplamaq deməkdir: 10 + 10 + 10 + 10 + 10 = 50.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l2-t7", type: "numeric", prompt: "3 × 5 = ?", answer: 15, xp: 10, explanation: "3 × 5 — 5-i 3 dəfə toplamaq deməkdir: 5 + 5 + 5 = 15.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l2-t8", type: "multiple_choice", prompt: "5-ə vurulan ədədin sonu necə olur?", options: ["0 və ya 5", "Həmişə 2", "Həmişə 1", "İstənilən rəqəm"], correctIndex: 0, xp: 10, explanation: "5 × 1 = 5, 5 × 2 = 10, 5 × 3 = 15... Nəticə növbə ilə ya 5, ya da 0 ilə bitir.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l2-t9", type: "numeric", prompt: "2 × 2 = ?", answer: 4, xp: 10, explanation: "2 × 2 — 2-ni 2 dəfə toplamaq deməkdir: 2 + 2 = 4.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l2-t10", type: "numeric", prompt: "9 × 5 = ?", answer: 45, xp: 10, explanation: "9 × 5 — 9-u 5 dəfə toplamaq deməkdir: 9 + 9 + 9 + 9 + 9 = 45.", skills: ["arith.mul.tables"] },
          ],
          bonusTasks: [
            { id: "ry2-vurma-l2-b1", type: "numeric", prompt: "Bir qutuda 5 alma var. 7 qutuda neçə alma var?", answer: 35, xp: 15, explanation: "Hər qutudakı 5 alma 7 dəfə təkrarlanır: 7 × 5 = 35.", skills: ["problem.one_step","arith.mul.tables"] },
            { id: "ry2-vurma-l2-b2", type: "numeric", prompt: "2 × 8 + 5 = ?", answer: 21, xp: 15, explanation: "Əvvəl vurma: 2 × 8 = 16. Sonra toplama: 16 + 5 = 21.", skills: ["arith.order_of_ops"] },
            { id: "ry2-vurma-l2-b3", type: "numeric", prompt: "5 × ? = 25 — buraya hansı ədəd gəlir?", answer: 5, xp: 15, explanation: "Naməlum vuruğu tapmaq üçün hasili məlum vuruğa bölürük: 25 : 5 = 5.", skills: ["arith.inverse"] },
            { id: "ry2-vurma-l2-b4", type: "multiple_choice", prompt: "7 × 2 ilə 2 × 7 eynidirmi?", options: ["Bəli, nəticə eynidir", "Xeyr", "Yalnız kiçik ədədlərdə", "Bilmək olmur"], correctIndex: 0, xp: 15, explanation: "Vuruqların yerini dəyişmək hasili dəyişmir: 7 × 2 = 14 və 2 × 7 = 14.", skills: ["arith.mul.tables"] },
          ],
        },
        {
          id: "ry2-vurma-l3",
          title: "3 və 4 ilə vurma",
          intro: "3 və 4 cədvəllərini təkrar toplama ilə öyrənək.",
          sections: [
            { heading: "3 cədvəli", body: "3, 6, 9, 12, 15, 18, 21, 24, 27, 30 — hər dəfə 3 artır." },
            { heading: "4 cədvəli", body: "4-ə vurmaq — 2-yə iki dəfə vurmaqdır. 6 × 4 = 6 × 2 × 2 = 12 × 2 = 24." },
          ],
          tasks: [
            { id: "ry2-vurma-l3-t1", type: "numeric", prompt: "4 × 3 = ?", answer: 12, xp: 10, explanation: "4 × 3 — 3-ü 4 dəfə toplamaq deməkdir: 3 + 3 + 3 + 3 = 12.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l3-t2", type: "numeric", prompt: "7 × 3 = ?", answer: 21, xp: 10, explanation: "7 × 3 — 7-ni 3 dəfə toplamaq deməkdir: 7 + 7 + 7 = 21.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l3-t3", type: "numeric", prompt: "6 × 4 = ?", answer: 24, xp: 10, explanation: "6 × 4 — 6-nı 4 dəfə toplamaq deməkdir: 6 + 6 + 6 + 6 = 24.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l3-t4", type: "numeric", prompt: "8 × 4 = ?", answer: 32, xp: 10, explanation: "8 × 4 — 8-i 4 dəfə toplamaq deməkdir: 8 + 8 + 8 + 8 = 32.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l3-t5", type: "numeric", prompt: "9 × 3 = ?", answer: 27, xp: 10, explanation: "9 × 3 — 9-u 3 dəfə toplamaq deməkdir: 9 + 9 + 9 = 27.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l3-t6", type: "numeric", prompt: "5 × 4 = ?", answer: 20, xp: 10, explanation: "5 × 4 — 4-ü 5 dəfə toplamaq deməkdir: 4 + 4 + 4 + 4 + 4 = 20.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l3-t7", type: "numeric", prompt: "10 × 3 = ?", answer: 30, xp: 10, explanation: "10 × 3 — 10-u 3 dəfə toplamaq deməkdir: 10 + 10 + 10 = 30.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l3-t8", type: "numeric", prompt: "9 × 4 = ?", answer: 36, xp: 10, explanation: "9 × 4 — 9-u 4 dəfə toplamaq deməkdir: 9 + 9 + 9 + 9 = 36.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l3-t9", type: "multiple_choice", prompt: "4-ə vurmaq nəyə bərabərdir?", options: ["2-yə iki dəfə vurmaq", "2-yə bir dəfə vurmaq", "3-ə vurmaq", "5-ə vurmaq"], correctIndex: 0, xp: 10, explanation: "4 = 2 × 2 olduğu üçün 4-ə vurmaq, ədədi əvvəl 2-yə, sonra bir də 2-yə vurmaqla eynidir.", skills: ["arith.mul.tables"] },
            { id: "ry2-vurma-l3-t10", type: "numeric", prompt: "3 × 3 = ?", answer: 9, xp: 10, explanation: "3 × 3 — 3-ü 3 dəfə toplamaq deməkdir: 3 + 3 + 3 = 9.", skills: ["arith.mul.tables"] },
          ],
          bonusTasks: [
            { id: "ry2-vurma-l3-b1", type: "numeric", prompt: "Sinifdə 4 sıra var, hər sırada 6 şagird. Neçə şagird var?", answer: 24, xp: 15, explanation: "Hər sıradakı 6 şagird 4 dəfə təkrarlanır: 4 × 6 = 24.", skills: ["problem.one_step","arith.mul.tables"] },
            { id: "ry2-vurma-l3-b2", type: "numeric", prompt: "3 × 6 + 4 × 2 = ?", answer: 26, xp: 15, explanation: "Əvvəl vurmalar: 3 × 6 = 18 və 4 × 2 = 8. Sonra toplama: 18 + 8 = 26.", skills: ["arith.order_of_ops"] },
            { id: "ry2-vurma-l3-b3", type: "numeric", prompt: "4 × ? = 28 — buraya hansı ədəd gəlir?", answer: 7, xp: 15, explanation: "Naməlum vuruğu tapmaq üçün hasili məlum vuruğa bölürük: 28 : 4 = 7.", skills: ["arith.inverse"] },
            { id: "ry2-vurma-l3-b4", type: "numeric", prompt: "3 × 8 = ?", answer: 24, xp: 15, explanation: "3 × 8 — 8-i 3 dəfə toplamaq deməkdir: 8 + 8 + 8 = 24.", skills: ["arith.mul.tables"] },
          ],
        },
        {
          id: "ry2-vurma-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry2-vurma-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 5. Bölmə ═══════════════
    {
      id: "ry2-bolme",
      title: "Bölmə",
      description: "Bölmənin başlanğıcı: bərabər hissələrə bölmək.",
      lessons: [
        {
          id: "ry2-bolme-l1",
          title: "Bölmə nədir?",
          intro: "Bölmə — bərabər hissələrə ayırmaqdır. 6 ÷ 2 = 3.",
          sections: [
            { heading: "Bölmə", body: "6 almanı 2 uşağa bərabər paylasaq, hər biri 3 alma alır: 6 ÷ 2 = 3. Bölmə vurmanın əksidir: 2 × 3 = 6, ona görə 6 ÷ 2 = 3." },
          ],
          tasks: [
            { id: "ry2-bolme-l1-t1", type: "numeric", prompt: "6 ÷ 2 = ?", answer: 3, xp: 10, explanation: "6-nı 2 bərabər hissəyə bölürük. Hər hissəyə 3 düşür, çünki 2 × 3 = 6.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l1-t2", type: "numeric", prompt: "8 ÷ 2 = ?", answer: 4, xp: 10, explanation: "8-i 2 bərabər hissəyə bölürük. Hər hissəyə 4 düşür, çünki 2 × 4 = 8.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l1-t3", type: "numeric", prompt: "10 ÷ 2 = ?", answer: 5, xp: 10, explanation: "10-u 2 bərabər hissəyə bölürük. Hər hissəyə 5 düşür, çünki 2 × 5 = 10.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l1-t4", type: "numeric", prompt: "9 ÷ 3 = ?", answer: 3, xp: 10, explanation: "9-u 3 bərabər hissəyə bölürük. Hər hissəyə 3 düşür, çünki 3 × 3 = 9.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l1-t5", type: "numeric", prompt: "12 ÷ 3 = ?", answer: 4, xp: 10, explanation: "12-ni 3 bərabər hissəyə bölürük. Hər hissəyə 4 düşür, çünki 3 × 4 = 12.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l1-t6", type: "numeric", prompt: "12 ÷ 4 = ?", answer: 3, xp: 10, explanation: "12-ni 4 bərabər hissəyə bölürük. Hər hissəyə 3 düşür, çünki 4 × 3 = 12.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l1-t7", type: "numeric", prompt: "20 ÷ 4 = ?", answer: 5, xp: 10, explanation: "20-ni 4 bərabər hissəyə bölürük. Hər hissəyə 5 düşür, çünki 4 × 5 = 20.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l1-t8", type: "numeric", prompt: "10 ÷ 5 = ?", answer: 2, xp: 10, explanation: "10-u 5 bərabər hissəyə bölürük. Hər hissəyə 2 düşür, çünki 5 × 2 = 10.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l1-t9", type: "numeric", prompt: "25 ÷ 5 = ?", answer: 5, xp: 10, explanation: "25-i 5 bərabər hissəyə bölürük. Hər hissəyə 5 düşür, çünki 5 × 5 = 25.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l1-t10", type: "numeric", prompt: "20 ÷ 5 = ?", answer: 4, xp: 10, explanation: "20-ni 5 bərabər hissəyə bölürük. Hər hissəyə 4 düşür, çünki 5 × 4 = 20.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l1-t11", type: "numeric", prompt: "4 ÷ 2 = ?", answer: 2, xp: 10, explanation: "4-ü 2 bərabər hissəyə bölürük. Hər hissəyə 2 düşür, çünki 2 × 2 = 4.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l1-t12", type: "numeric", prompt: "15 ÷ 3 = ?", answer: 5, xp: 10, explanation: "15-i 3 bərabər hissəyə bölürük. Hər hissəyə 5 düşür, çünki 3 × 5 = 15.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l1-t13", type: "numeric", prompt: "16 ÷ 4 = ?", answer: 4, xp: 10, explanation: "16-nı 4 bərabər hissəyə bölürük. Hər hissəyə 4 düşür, çünki 4 × 4 = 16.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l1-t14", type: "numeric", prompt: "6 almanı 3 uşağa bərabər paylasaq, hər biri neçə alır?", answer: 2, xp: 10, explanation: "6 almanı 3 uşağa bərabər paylayırıq: 6 : 3 = 2, yəni hər uşağa 2 alma düşür.", skills: ["problem.one_step","arith.div.tables"] },
            { id: "ry2-bolme-l1-t15", type: "numeric", prompt: "15 ÷ 5 = ?", answer: 3, xp: 15, explanation: "15-i 5 bərabər hissəyə bölürük. Hər hissəyə 3 düşür, çünki 5 × 3 = 15.", skills: ["arith.div.tables"] },
          ],
          bonusTasks: [
            { id: "ry2-bolme-l1-b1", type: "numeric", prompt: "30 ÷ 5 = ?", answer: 6, xp: 15, explanation: "30-u 5 bərabər hissəyə bölürük. Hər hissəyə 6 düşür, çünki 5 × 6 = 30.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l1-b2", type: "numeric", prompt: "24 ÷ 4 = ?", answer: 6, xp: 15, explanation: "24-ü 4 bərabər hissəyə bölürük. Hər hissəyə 6 düşür, çünki 4 × 6 = 24.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l1-b3", type: "numeric", prompt: "18 ÷ 3 = ?", answer: 6, xp: 15, explanation: "18-i 3 bərabər hissəyə bölürük. Hər hissəyə 6 düşür, çünki 3 × 6 = 18.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l1-b4", type: "numeric", prompt: "10 konfeti 2 uşağa bərabər paylasaq, hər biri neçə alır?", answer: 5, xp: 15, explanation: "10 konfeti 2 uşağa bərabər paylayırıq: 10 : 2 = 5, yəni hər uşağa 5 konfet düşür.", skills: ["problem.one_step","arith.div.tables"] },
            { id: "ry2-bolme-l1-b5", type: "numeric", prompt: "16 ÷ 2 = ?", answer: 8, xp: 15, explanation: "16-nı 2 bərabər hissəyə bölürük. Hər hissəyə 8 düşür, çünki 2 × 8 = 16.", skills: ["arith.div.tables"] },
          ],
        },
        {
          id: "ry2-bolme-l2",
          title: "2 və 5-ə bölmə",
          intro: "Bərabər paylamağı öyrənək.",
          sections: [
            { heading: "2-yə bölmə", body: "2-yə bölmək — yarıya bölməkdir. 14 ÷ 2 = 7, çünki 7 + 7 = 14." },
            { heading: "5-ə bölmə", body: "20 ÷ 5 = 4, çünki 5 × 4 = 20. Bölməni həmişə vurma ilə yoxlaya bilərsən." },
          ],
          tasks: [
            { id: "ry2-bolme-l2-t1", type: "numeric", prompt: "14 ÷ 2 = ?", answer: 7, xp: 10, explanation: "14-ü 2 bərabər hissəyə bölürük. Hər hissəyə 7 düşür, çünki 2 × 7 = 14.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l2-t2", type: "numeric", prompt: "18 ÷ 2 = ?", answer: 9, xp: 10, explanation: "18-i 2 bərabər hissəyə bölürük. Hər hissəyə 9 düşür, çünki 2 × 9 = 18.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l2-t3", type: "numeric", prompt: "20 ÷ 5 = ?", answer: 4, xp: 10, explanation: "20-ni 5 bərabər hissəyə bölürük. Hər hissəyə 4 düşür, çünki 5 × 4 = 20.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l2-t4", type: "numeric", prompt: "35 ÷ 5 = ?", answer: 7, xp: 10, explanation: "35-i 5 bərabər hissəyə bölürük. Hər hissəyə 7 düşür, çünki 5 × 7 = 35.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l2-t5", type: "numeric", prompt: "10 ÷ 2 = ?", answer: 5, xp: 10, explanation: "10-u 2 bərabər hissəyə bölürük. Hər hissəyə 5 düşür, çünki 2 × 5 = 10.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l2-t6", type: "numeric", prompt: "45 ÷ 5 = ?", answer: 9, xp: 10, explanation: "45-i 5 bərabər hissəyə bölürük. Hər hissəyə 9 düşür, çünki 5 × 9 = 45.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l2-t7", type: "numeric", prompt: "16 ÷ 2 = ?", answer: 8, xp: 10, explanation: "16-nı 2 bərabər hissəyə bölürük. Hər hissəyə 8 düşür, çünki 2 × 8 = 16.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l2-t8", type: "multiple_choice", prompt: "2-yə bölmək nə deməkdir?", options: ["Yarıya bölmək", "İkiqat etmək", "2 əlavə etmək", "2 çıxmaq"], correctIndex: 0, xp: 10, explanation: "2-yə bölmək ədədi iki bərabər hissəyə ayırmaq, yəni yarıya bölmək deməkdir.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l2-t9", type: "numeric", prompt: "25 ÷ 5 = ?", answer: 5, xp: 10, explanation: "25-i 5 bərabər hissəyə bölürük. Hər hissəyə 5 düşür, çünki 5 × 5 = 25.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l2-t10", type: "numeric", prompt: "12 ÷ 2 = ?", answer: 6, xp: 10, explanation: "12-ni 2 bərabər hissəyə bölürük. Hər hissəyə 6 düşür, çünki 2 × 6 = 12.", skills: ["arith.div.tables"] },
          ],
          bonusTasks: [
            { id: "ry2-bolme-l2-b1", type: "numeric", prompt: "20 konfeti 5 uşağa bərabər payladıq. Hərəyə neçə düşdü?", answer: 4, xp: 15, explanation: "20 konfeti 5 uşağa bərabər paylayırıq: 20 : 5 = 4, yəni hərəyə 4 konfet düşür.", skills: ["problem.one_step","arith.div.tables"] },
            { id: "ry2-bolme-l2-b2", type: "numeric", prompt: "30 ÷ 5 + 4 = ?", answer: 10, xp: 15, explanation: "Əvvəl bölmə: 30 : 5 = 6. Sonra toplama: 6 + 4 = 10.", skills: ["arith.order_of_ops"] },
            { id: "ry2-bolme-l2-b3", type: "numeric", prompt: "? ÷ 2 = 8 — buraya hansı ədəd gəlir?", answer: 16, xp: 15, explanation: "Bölünəni tapmaq üçün qismətlə böləni vururuq: 8 × 2 = 16.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l2-b4", type: "numeric", prompt: "40 ÷ 5 = ?", answer: 8, xp: 15, explanation: "40-ı 5 bərabər hissəyə bölürük. Hər hissəyə 8 düşür, çünki 5 × 8 = 40.", skills: ["arith.div.tables"] },
          ],
        },
        {
          id: "ry2-bolme-l3",
          title: "Vurma və bölmə əlaqəsi",
          intro: "Vurma və bölmə bir-birinin əksidir.",
          sections: [
            { heading: "Ailə", body: "3 × 4 = 12 bilirsənsə, 12 ÷ 4 = 3 və 12 ÷ 3 = 4 də bilirsən. Bu üç fakt bir ailədir." },
            { heading: "Yoxlama", body: "Bölmənin cavabını böləni ilə vur — bölünən alınmalıdır. 18 ÷ 3 = 6, yoxlama: 6 × 3 = 18. ✓" },
          ],
          tasks: [
            { id: "ry2-bolme-l3-t1", type: "numeric", prompt: "3 × 4 = 12-dirsə, 12 ÷ 4 = ?", answer: 3, xp: 10, explanation: "Vurma ilə bölmə tərs əməllərdir: 3 × 4 = 12 olduğuna görə 12 : 4 = 3.", skills: ["arith.order_of_ops","arith.mul.tables"] },
            { id: "ry2-bolme-l3-t2", type: "numeric", prompt: "18 ÷ 3 = ?", answer: 6, xp: 10, explanation: "18-i 3 bərabər hissəyə bölürük. Hər hissəyə 6 düşür, çünki 3 × 6 = 18.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l3-t3", type: "numeric", prompt: "24 ÷ 4 = ?", answer: 6, xp: 10, explanation: "24-ü 4 bərabər hissəyə bölürük. Hər hissəyə 6 düşür, çünki 4 × 6 = 24.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l3-t4", type: "numeric", prompt: "27 ÷ 3 = ?", answer: 9, xp: 10, explanation: "27-ni 3 bərabər hissəyə bölürük. Hər hissəyə 9 düşür, çünki 3 × 9 = 27.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l3-t5", type: "numeric", prompt: "32 ÷ 4 = ?", answer: 8, xp: 10, explanation: "32-ni 4 bərabər hissəyə bölürük. Hər hissəyə 8 düşür, çünki 4 × 8 = 32.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l3-t6", type: "multiple_choice", prompt: "Bölməni hansı əməllə yoxlayırıq?", options: ["Vurma", "Toplama", "Çıxma", "Müqayisə"], correctIndex: 0, xp: 10, explanation: "Qismətlə böləni vursaq, bölünən alınmalıdır — ona görə bölmə vurma ilə yoxlanır.", skills: ["arith.inverse"] },
            { id: "ry2-bolme-l3-t7", type: "numeric", prompt: "21 ÷ 3 = ?", answer: 7, xp: 10, explanation: "21-i 3 bərabər hissəyə bölürük. Hər hissəyə 7 düşür, çünki 3 × 7 = 21.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l3-t8", type: "numeric", prompt: "36 ÷ 4 = ?", answer: 9, xp: 10, explanation: "36-nı 4 bərabər hissəyə bölürük. Hər hissəyə 9 düşür, çünki 4 × 9 = 36.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l3-t9", type: "numeric", prompt: "9 ÷ 3 = ?", answer: 3, xp: 10, explanation: "9-u 3 bərabər hissəyə bölürük. Hər hissəyə 3 düşür, çünki 3 × 3 = 9.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l3-t10", type: "numeric", prompt: "5 × 6 = 30-dursa, 30 ÷ 6 = ?", answer: 5, xp: 10, explanation: "Vurma ilə bölmə tərs əməllərdir: 5 × 6 = 30 olduğuna görə 30 : 6 = 5.", skills: ["arith.order_of_ops","arith.mul.tables"] },
          ],
          bonusTasks: [
            { id: "ry2-bolme-l3-b1", type: "numeric", prompt: "24 kitabı 3 rəfə bərabər düzdük. Hər rəfdə neçə kitab var?", answer: 8, xp: 15, explanation: "24 kitabı 3 rəfə bərabər düzürük: 24 : 3 = 8, yəni hər rəfdə 8 kitab olur.", skills: ["problem.one_step","arith.div.tables"] },
            { id: "ry2-bolme-l3-b2", type: "numeric", prompt: "4 × 5 ÷ 2 = ?", answer: 10, xp: 15, explanation: "Soldan sağa hesablayırıq: əvvəl 4 × 5 = 20, sonra 20 : 2 = 10.", skills: ["arith.div.tables"] },
            { id: "ry2-bolme-l3-b3", type: "numeric", prompt: "? × 3 = 15 — buraya hansı ədəd gəlir?", answer: 5, xp: 15, explanation: "Naməlum vuruğu tapmaq üçün hasili məlum vuruğa bölürük: 15 : 3 = 5.", skills: ["arith.inverse"] },
            { id: "ry2-bolme-l3-b4", type: "multiple_choice", prompt: "0-ı istənilən ədədə bölsək nə alınır?", options: ["0", "1", "Həmin ədəd", "Alınmır"], correctIndex: 0, xp: 15, explanation: "Heç nəyi paylasaq, hər hissəyə yenə heç nə düşür — ona görə 0 istənilən ədədə bölünəndə 0 alınır.", skills: ["arith.div.tables"] },
          ],
        },
        {
          id: "ry2-bolme-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry2-bolme-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 6. Ölçmə, zaman, pul və fiqurlar ═══════════════
    {
      id: "ry2-olcme",
      title: "Ölçmə, zaman, pul və fiqurlar",
      description: "Uzunluq, saat, pul (qəpik/manat) və həndəsi fiqurlar.",
      lessons: [
        {
          id: "ry2-olcme-l1",
          title: "Ölçmə və zaman",
          intro: "Santimetr, saat, pul və fiqurları tanıyaq.",
          sections: [
            { heading: "Uzunluq", body: "Uzunluğu santimetr (sm) və metr (m) ilə ölçürük. 1 metr = 100 santimetr." },
            { heading: "Zaman", body: "Bir saatda 60 dəqiqə var. Bir gündə 24 saat var. Bir həftədə 7 gün var." },
            { heading: "Pul", body: "1 manat = 100 qəpik." },
          ],
          tasks: [
            { id: "ry2-olcme-l1-t1", type: "numeric", prompt: "1 metr neçə santimetrdir?", answer: 100, xp: 10, explanation: "Metr santimetrdən böyük vahiddir: 1 m = 100 sm.", skills: ["measure.convert"] },
            { id: "ry2-olcme-l1-t2", type: "numeric", prompt: "Bir saatda neçə dəqiqə var?", answer: 60, xp: 10, explanation: "Saat 60 bərabər dəqiqəyə bölünür.", skills: ["measure.time"] },
            { id: "ry2-olcme-l1-t3", type: "numeric", prompt: "Bir gündə neçə saat var?", answer: 24, xp: 10, explanation: "Gündüz və gecə birlikdə 24 saat edir.", skills: ["measure.time"] },
            { id: "ry2-olcme-l1-t4", type: "numeric", prompt: "Bir həftədə neçə gün var?", answer: 7, xp: 10, explanation: "Bazar ertəsindən bazara qədər sayırıq — həftədə 7 gün var.", skills: ["measure.time"] },
            { id: "ry2-olcme-l1-t5", type: "numeric", prompt: "1 manat neçə qəpikdir?", answer: 100, xp: 10, explanation: "Manat qəpiklərə bölünür: 1 manat = 100 qəpik.", skills: ["measure.money"] },
            { id: "ry2-olcme-l1-t6", type: "numeric", prompt: "Yarım saat neçə dəqiqədir?", answer: 30, xp: 10, explanation: "Yarım saat saatın yarısıdır: 60 : 2 = 30 dəqiqə.", skills: ["measure.time"] },
            { id: "ry2-olcme-l1-t7", type: "numeric", prompt: "2 metr neçə santimetrdir?", answer: 200, xp: 10, explanation: "1 m = 100 sm, deməli 2 m = 2 × 100 = 200 sm.", skills: ["measure.convert"] },
            { id: "ry2-olcme-l1-t8", type: "multiple_choice", prompt: "Kvadratın neçə tərəfi var?", options: ["4", "3", "5", "2"], correctIndex: 0, xp: 10, explanation: "Kvadratın 4 tərəfi var və hamısı bərabərdir.", skills: ["geom.shapes"] },
            { id: "ry2-olcme-l1-t9", type: "multiple_choice", prompt: "Üçbucağın neçə tərəfi var?", options: ["3", "4", "5", "2"], correctIndex: 0, xp: 10, explanation: "Üçbucağın adı «üç»dən gəlir: onun 3 tərəfi var.", skills: ["geom.shapes"] },
            { id: "ry2-olcme-l1-t10", type: "numeric", prompt: "İki həftədə neçə gün var? (7 + 7)", answer: 14, xp: 10, explanation: "Hər həftədə 7 gün var: 7 + 7 = 14 gün.", skills: ["measure.time"] },
            { id: "ry2-olcme-l1-t11", type: "numeric", prompt: "50 qəpik + 50 qəpik neçə manatdır?", answer: 1, xp: 10, explanation: "50 + 50 = 100 qəpik, 100 qəpik isə 1 manatdır.", skills: ["measure.money"] },
            { id: "ry2-olcme-l1-t12", type: "multiple_choice", prompt: "Hansı fiqurun bütün tərəfləri bərabərdir?", options: ["kvadrat", "düzbucaqlı", "dairə", "xətt"], correctIndex: 0, xp: 10, explanation: "Yalnız kvadratın dörd tərəfi də eyni uzunluqdadır. Düzbucaqlıda uzun və qısa tərəflər var.", skills: ["geom.shapes"] },
            { id: "ry2-olcme-l1-t13", type: "numeric", prompt: "Kvadratın bir tərəfi 5 sm-dir. Perimetri neçədir? (4 tərəf)", answer: 20, xp: 10, explanation: "Perimetr bütün tərəflərin cəmidir. Kvadratın 4 bərabər tərəfi var: 4 × 5 = 20 sm.", skills: ["geom.perimeter","geom.shapes","measure.convert"] },
            { id: "ry2-olcme-l1-t14", type: "numeric", prompt: "Səhər saat 8-də başladı, 2 saat keçdi. Saat neçədir?", answer: 10, xp: 10, explanation: "Başlanğıc vaxtın üstünə keçən vaxtı əlavə edirik: 8 + 2 = 10.", skills: ["measure.time","problem.one_step","arith.add.basic"] },
            { id: "ry2-olcme-l1-t15", type: "numeric", prompt: "Bir ildə neçə ay var?", answer: 12, xp: 15, explanation: "Yanvardan dekabra qədər sayırıq — bir ildə 12 ay var.", skills: ["measure.time"] },
          ],
          bonusTasks: [
            { id: "ry2-olcme-l1-b1", type: "numeric", prompt: "3 metr neçə santimetrdir?", answer: 300, xp: 15, explanation: "1 m = 100 sm, deməli 3 m = 3 × 100 = 300 sm.", skills: ["measure.convert"] },
            { id: "ry2-olcme-l1-b2", type: "numeric", prompt: "İki saatda neçə dəqiqə var? (60 + 60)", answer: 120, xp: 15, explanation: "Bir saat 60 dəqiqədir: 60 + 60 = 120 dəqiqə.", skills: ["measure.time"] },
            { id: "ry2-olcme-l1-b3", type: "numeric", prompt: "Üçbucağın hər tərəfi 4 sm-dir. Perimetri neçədir? (3 tərəf)", answer: 12, xp: 15, explanation: "Perimetr tərəflərin cəmidir. Üçbucağın 3 tərəfi var: 3 × 4 = 12 sm.", skills: ["geom.perimeter","geom.shapes","measure.convert"] },
            { id: "ry2-olcme-l1-b4", type: "numeric", prompt: "70 qəpik + 30 qəpik neçə manatdır?", answer: 1, xp: 15, explanation: "70 + 30 = 100 qəpik, 100 qəpik isə 1 manatdır.", skills: ["measure.money"] },
            { id: "ry2-olcme-l1-b5", type: "numeric", prompt: "Düzbucaqlının tərəfləri 3 sm və 5 sm-dir. Perimetri? (2×(3+5))", answer: 16, xp: 15, explanation: "Düzbucaqlıda qarşı tərəflər bərabərdir, ona görə perimetr 2 × (3 + 5) = 2 × 8 = 16 sm olur.", skills: ["geom.perimeter","geom.shapes","measure.convert"] },
          ],
        },
        {
          id: "ry2-olcme-l2",
          title: "Sadə məsələlər",
          intro: "Toplama, çıxma və vurma ilə məsələ həll edək.",
          sections: [
            { heading: "Məsələ", body: "Diqqətlə oxu, hansı əməli işlədəcəyini seç, sonra hesabla." },
          ],
          tasks: [
            { id: "ry2-olcme-l2-t1", type: "numeric", prompt: "Aylının 15 stikeri var, 12 də aldı. Neçə stikeri oldu?", answer: 27, xp: 10, explanation: "«Də aldı» artım deməkdir: 15 + 12 = 27 stiker.", skills: ["problem.one_step","arith.add.no_carry"] },
            { id: "ry2-olcme-l2-t2", type: "numeric", prompt: "Rəfdə 40 kitab var idi, 15-ni götürdük. Neçə kitab qaldı?", answer: 25, xp: 10, explanation: "«Götürdük» azalma deməkdir: 40 − 15 = 25 kitab qaldı.", skills: ["problem.one_step","arith.sub.borrow"] },
            { id: "ry2-olcme-l2-t3", type: "numeric", prompt: "Hər qutuda 5 qələm var. 4 qutuda neçə qələm var?", answer: 20, xp: 10, explanation: "Hər qutudakı 5 qələm 4 dəfə təkrarlanır: 4 × 5 = 20.", skills: ["problem.one_step","arith.mul.tables"] },
            { id: "ry2-olcme-l2-t4", type: "numeric", prompt: "12 konfeti 3 uşağa bərabər paylasaq, hər biri neçə alır?", answer: 4, xp: 10, explanation: "12 konfeti 3 uşağa bərabər paylayırıq: 12 : 3 = 4.", skills: ["problem.one_step","arith.div.tables"] },
            { id: "ry2-olcme-l2-t5", type: "numeric", prompt: "Bağçada 30 gül var idi, 25 də açdı. Neçə gül oldu?", answer: 55, xp: 10, explanation: "«Də açdı» artım deməkdir: 30 + 25 = 55 gül.", skills: ["problem.one_step","arith.add.no_carry"] },
            { id: "ry2-olcme-l2-t6", type: "numeric", prompt: "Elçinin 50 manatı var idi, 20 manat xərclədi. Neçə manatı qaldı?", answer: 30, xp: 10, explanation: "«Xərclədi» azalma deməkdir: 50 − 20 = 30 manat qaldı.", skills: ["measure.money","problem.one_step","arith.sub.no_borrow"] },
            { id: "ry2-olcme-l2-t7", type: "numeric", prompt: "Hər masada 2 uşaq oturur. 5 masada neçə uşaq var?", answer: 10, xp: 10, explanation: "Hər masadakı 2 uşaq 5 dəfə təkrarlanır: 5 × 2 = 10.", skills: ["problem.one_step","arith.mul.tables"] },
            { id: "ry2-olcme-l2-t8", type: "numeric", prompt: "20 alma 5 səbətə bərabər paylandı. Hər səbətdə neçə alma var?", answer: 4, xp: 10, explanation: "20 almanı 5 səbətə bərabər paylayırıq: 20 : 5 = 4.", skills: ["problem.one_step","arith.div.tables"] },
            { id: "ry2-olcme-l2-t9", type: "numeric", prompt: "Sinifdə 24 şagird var, 12-si qız. Neçə oğlan var?", answer: 12, xp: 10, explanation: "Oğlanların sayını tapmaq üçün ümumi saydan qızları çıxırıq: 24 − 12 = 12.", skills: ["problem.one_step","arith.sub.no_borrow"] },
            { id: "ry2-olcme-l2-t10", type: "numeric", prompt: "Hər gün 3 səhifə oxuyuram. 4 gündə neçə səhifə oxuyuram?", answer: 12, xp: 10, explanation: "Hər günkü 3 səhifə 4 dəfə təkrarlanır: 4 × 3 = 12.", skills: ["problem.one_step","arith.mul.tables"] },
            { id: "ry2-olcme-l2-t11", type: "numeric", prompt: "35 + 40 = ? (məsələ: iki qrupun cəmi)", answer: 75, xp: 10, explanation: "Onluqlar: 30 + 40 = 70. Təkliklər: 5 + 0 = 5. Nəticə: 70 + 5 = 75.", skills: ["arith.order_of_ops","arith.add.no_carry"] },
            { id: "ry2-olcme-l2-t12", type: "numeric", prompt: "Ağacda 18 quş var idi, 9-u uçdu. Neçə quş qaldı?", answer: 9, xp: 10, explanation: "«Uçdu» azalma deməkdir: 18 − 9 = 9 quş qaldı.", skills: ["problem.one_step","arith.sub.basic"] },
            { id: "ry2-olcme-l2-t13", type: "numeric", prompt: "Hər paketdə 4 peçenye var. 5 paketdə neçə peçenye var?", answer: 20, xp: 10, explanation: "Hər paketdəki 4 peçenye 5 dəfə təkrarlanır: 5 × 4 = 20.", skills: ["problem.one_step","arith.mul.tables"] },
            { id: "ry2-olcme-l2-t14", type: "numeric", prompt: "16 oyuncaq 4 uşağa bərabər paylandı. Hər biri neçə alır?", answer: 4, xp: 10, explanation: "16 oyuncağı 4 uşağa bərabər paylayırıq: 16 : 4 = 4.", skills: ["problem.one_step","arith.div.tables"] },
            { id: "ry2-olcme-l2-t15", type: "numeric", prompt: "60 manatım var idi, 25 manat kitaba, 15 manat da çantaya verdim. Neçə manat qaldı?", answer: 20, xp: 15, explanation: "Əvvəl xərcləri toplayırıq: 25 + 15 = 40. Sonra 60 − 40 = 20 manat qalır.", skills: ["measure.money","problem.multi_step","arith.add.carry"] },
          ],
          bonusTasks: [
            { id: "ry2-olcme-l2-b1", type: "numeric", prompt: "Hər həftədə 7 gün var. 3 həftədə neçə gün var?", answer: 21, xp: 15, explanation: "Hər həftədəki 7 gün 3 dəfə təkrarlanır: 3 × 7 = 21.", skills: ["measure.time","problem.one_step","arith.mul.tables"] },
            { id: "ry2-olcme-l2-b2", type: "numeric", prompt: "45 şəkil 5 albomda bərabər yerləşdi. Hər albomda neçə şəkil var?", answer: 9, xp: 15, explanation: "45 şəkli 5 alboma bərabər paylayırıq: 45 : 5 = 9.", skills: ["problem.one_step","arith.div.tables"] },
            { id: "ry2-olcme-l2-b3", type: "numeric", prompt: "İki dostun birində 28, digərində 34 marka var. Cəmi neçə marka var?", answer: 62, xp: 15, explanation: "«Cəmi» toplama deməkdir: 28 + 34 = 62 marka.", skills: ["problem.one_step","arith.add.carry"] },
            { id: "ry2-olcme-l2-b4", type: "numeric", prompt: "Hər qutuda 5 top var. 6 qutuda neçə top var?", answer: 30, xp: 15, explanation: "Hər qutudakı 5 top 6 dəfə təkrarlanır: 6 × 5 = 30.", skills: ["problem.one_step","arith.mul.tables"] },
            { id: "ry2-olcme-l2-b5", type: "numeric", prompt: "100 səhifəlik kitabın 60 səhifəsini oxudum. Neçə səhifə qaldı?", answer: 40, xp: 15, explanation: "Oxunanı ümumi saydan çıxırıq: 100 − 60 = 40 səhifə qaldı.", skills: ["problem.one_step","arith.sub.borrow"] },
          ],
        },
        {
          id: "ry2-olcme-l3",
          title: "Saat və zaman",
          intro: "Saatı oxumağı və vaxtı hesablamağı öyrənək.",
          sections: [
            { heading: "Saat", body: "Bir sutkada 24 saat, bir saatda 60 dəqiqə var. Qısa əqrəb saatı, uzun əqrəb dəqiqəni göstərir." },
            { heading: "Yarım və rüb", body: "Yarım saat = 30 dəqiqə. Rüb saat = 15 dəqiqə." },
          ],
          tasks: [
            { id: "ry2-olcme-l3-t1", type: "numeric", prompt: "Bir saatda neçə dəqiqə var?", answer: 60, xp: 10, explanation: "Saat 60 bərabər dəqiqəyə bölünür.", skills: ["measure.time"] },
            { id: "ry2-olcme-l3-t2", type: "numeric", prompt: "Bir sutkada neçə saat var?", answer: 24, xp: 10, explanation: "Sutka bir gün və bir gecə deməkdir, bu isə 24 saat edir.", skills: ["measure.time"] },
            { id: "ry2-olcme-l3-t3", type: "numeric", prompt: "Yarım saat neçə dəqiqədir?", answer: 30, xp: 10, explanation: "Yarım saat saatın yarısıdır: 60 : 2 = 30 dəqiqə.", skills: ["measure.time"] },
            { id: "ry2-olcme-l3-t4", type: "numeric", prompt: "Rüb saat neçə dəqiqədir?", answer: 15, xp: 10, explanation: "Rüb dörddə bir deməkdir: 60 : 4 = 15 dəqiqə.", skills: ["measure.time"] },
            { id: "ry2-olcme-l3-t5", type: "numeric", prompt: "Dərs 40 dəqiqə çəkir, 15 dəqiqə keçib. Neçə dəqiqə qalıb?", answer: 25, xp: 10, explanation: "Keçən vaxtı ümumi vaxtdan çıxırıq: 40 − 15 = 25 dəqiqə qalıb.", skills: ["measure.time","problem.one_step","arith.sub.borrow"] },
            { id: "ry2-olcme-l3-t6", type: "numeric", prompt: "2 saat neçə dəqiqədir?", answer: 120, xp: 10, explanation: "Bir saat 60 dəqiqədir: 2 × 60 = 120 dəqiqə.", skills: ["measure.time"] },
            { id: "ry2-olcme-l3-t7", type: "multiple_choice", prompt: "Saatda hansı əqrəb dəqiqəni göstərir?", options: ["Uzun əqrəb", "Qısa əqrəb", "Hər ikisi", "Heç biri"], correctIndex: 0, xp: 10, explanation: "Uzun əqrəb sürətli hərəkət edir və dəqiqələri göstərir; qısa əqrəb isə saatı.", skills: ["measure.time"] },
            { id: "ry2-olcme-l3-t8", type: "numeric", prompt: "Bir həftədə neçə gün var?", answer: 7, xp: 10, explanation: "Bazar ertəsindən bazara qədər sayırıq — həftədə 7 gün var.", skills: ["measure.time"] },
            { id: "ry2-olcme-l3-t9", type: "numeric", prompt: "Bir ildə neçə ay var?", answer: 12, xp: 10, explanation: "Yanvardan dekabra qədər sayırıq — bir ildə 12 ay var.", skills: ["measure.time"] },
            { id: "ry2-olcme-l3-t10", type: "numeric", prompt: "Saat 9-dur. 3 saatdan sonra saat neçə olacaq?", answer: 12, xp: 10, explanation: "Saatın üstünə keçən vaxtı əlavə edirik: 9 + 3 = 12.", skills: ["measure.time","problem.one_step","arith.add.basic"] },
          ],
          bonusTasks: [
            { id: "ry2-olcme-l3-b1", type: "numeric", prompt: "Film 90 dəqiqə çəkir. Bu, 1 saatdan neçə dəqiqə çoxdur?", answer: 30, xp: 15, explanation: "1 saat 60 dəqiqədir, film isə 90 dəqiqə çəkir: 90 − 60 = 30 dəqiqə çoxdur.", skills: ["measure.time","problem.one_step","arith.sub.no_borrow"] },
            { id: "ry2-olcme-l3-b2", type: "numeric", prompt: "3 saat neçə dəqiqədir?", answer: 180, xp: 15, explanation: "Bir saat 60 dəqiqədir: 3 × 60 = 180 dəqiqə.", skills: ["measure.time"] },
            { id: "ry2-olcme-l3-b3", type: "numeric", prompt: "Dərs 45 dəqiqə çəkir, tənəffüs 15 dəqiqə. İkisi birlikdə neçə dəqiqədir?", answer: 60, xp: 15, explanation: "İki müddəti toplayırıq: 45 + 15 = 60 dəqiqə, yəni tam 1 saat.", skills: ["measure.time","problem.one_step","arith.add.carry"] },
            { id: "ry2-olcme-l3-b4", type: "numeric", prompt: "2 həftədə neçə gün var?", answer: 14, xp: 15, explanation: "Hər həftədə 7 gün var: 2 × 7 = 14 gün.", skills: ["measure.time"] },
          ],
        },
        {
          id: "ry2-olcme-l4",
          title: "Pul və fiqurlar",
          intro: "Manat, qəpik və həndəsi fiqurları tanıyaq.",
          sections: [
            { heading: "Pul", body: "1 manat = 100 qəpik. Alış-verişdə qalıq hesablamaq üçün çıxma işlədilir." },
            { heading: "Fiqurlar", body: "Kvadratın 4 bərabər tərəfi var. Düzbucaqlının qarşı tərəfləri bərabərdir. Üçbucağın 3, dairənin isə heç tərəfi yoxdur." },
          ],
          tasks: [
            { id: "ry2-olcme-l4-t1", type: "numeric", prompt: "1 manat neçə qəpikdir?", answer: 100, xp: 10, explanation: "Manat qəpiklərə bölünür: 1 manat = 100 qəpik.", skills: ["measure.money"] },
            { id: "ry2-olcme-l4-t2", type: "numeric", prompt: "Kvadratın neçə tərəfi var?", answer: 4, xp: 10, explanation: "Kvadratın 4 tərəfi var və hamısı bərabərdir.", skills: ["geom.shapes"] },
            { id: "ry2-olcme-l4-t3", type: "numeric", prompt: "Üçbucağın neçə tərəfi var?", answer: 3, xp: 10, explanation: "Üçbucağın adı «üç»dən gəlir: onun 3 tərəfi var.", skills: ["geom.shapes"] },
            { id: "ry2-olcme-l4-t4", type: "numeric", prompt: "Çörək 80 qəpikdir. 1 manat verdin, neçə qəpik qalıq?", answer: 20, xp: 10, explanation: "1 manat 100 qəpikdir. Qalıq: 100 − 80 = 20 qəpik.", skills: ["measure.money","problem.one_step","arith.sub.borrow"] },
            { id: "ry2-olcme-l4-t5", type: "numeric", prompt: "2 manat neçə qəpikdir?", answer: 200, xp: 10, explanation: "1 manat 100 qəpikdir: 2 × 100 = 200 qəpik.", skills: ["measure.money"] },
            { id: "ry2-olcme-l4-t6", type: "multiple_choice", prompt: "Hansı fiqurun bütün tərəfləri bərabərdir?", options: ["Kvadrat", "Düzbucaqlı", "Üçbucaq", "Dairə"], correctIndex: 0, xp: 10, explanation: "Yalnız kvadratın dörd tərəfi də eyni uzunluqdadır.", skills: ["geom.shapes"] },
            { id: "ry2-olcme-l4-t7", type: "numeric", prompt: "Tərəfi 5 sm olan kvadratın perimetri neçə sm-dir?", answer: 20, xp: 10, explanation: "Perimetr tərəflərin cəmidir. Kvadratın 4 bərabər tərəfi var: 4 × 5 = 20 sm.", skills: ["geom.perimeter","geom.shapes","measure.convert"] },
            { id: "ry2-olcme-l4-t8", type: "numeric", prompt: "1 metr neçə santimetrdir?", answer: 100, xp: 10, explanation: "Metr santimetrdən böyük vahiddir: 1 m = 100 sm.", skills: ["measure.convert"] },
            { id: "ry2-olcme-l4-t9", type: "multiple_choice", prompt: "Dairənin neçə tərəfi var?", options: ["Heç biri", "1", "2", "4"], correctIndex: 0, xp: 10, explanation: "Dairə tam yumrudur, düz tərəfi və küncü yoxdur — ona görə tərəflərinin sayı yoxdur.", skills: ["geom.shapes"] },
            { id: "ry2-olcme-l4-t10", type: "numeric", prompt: "50 qəpik + 50 qəpik neçə manatdır?", answer: 1, xp: 10, explanation: "50 + 50 = 100 qəpik, 100 qəpik isə 1 manatdır.", skills: ["measure.money"] },
          ],
          bonusTasks: [
            { id: "ry2-olcme-l4-b1", type: "numeric", prompt: "Tərəfləri 3 sm və 5 sm olan düzbucaqlının perimetri neçə sm-dir?", answer: 16, xp: 15, explanation: "Düzbucaqlıda qarşı tərəflər bərabərdir: 2 × (3 + 5) = 2 × 8 = 16 sm.", skills: ["geom.perimeter","geom.shapes","measure.convert","problem.one_step"] },
            { id: "ry2-olcme-l4-b2", type: "numeric", prompt: "3 manat 40 qəpik neçə qəpikdir?", answer: 340, xp: 15, explanation: "3 manat = 3 × 100 = 300 qəpik. Üstünə 40 qəpik: 300 + 40 = 340 qəpik.", skills: ["measure.money"] },
            { id: "ry2-olcme-l4-b3", type: "numeric", prompt: "5 ₼-la 2 ₼-lıq dəftər aldın. Neçə manat qaldı?", answer: 3, xp: 15, explanation: "Verdiyimizdən qiyməti çıxırıq: 5 − 2 = 3 manat qaldı.", skills: ["measure.money","problem.one_step","arith.sub.basic"] },
            { id: "ry2-olcme-l4-b4", type: "numeric", prompt: "2 metr 50 santimetr neçə santimetrdir?", answer: 250, xp: 15, explanation: "2 metr = 2 × 100 = 200 sm. Üstünə 50 sm: 200 + 50 = 250 sm.", skills: ["measure.convert"] },
          ],
        },
        {
          id: "ry2-olcme-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry2-olcme-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
  ],
};
